SDK 3.13.0: Adds change log and bumps the SDK version
Azure/azure-cosmos-dotnet-v3 pull request #1858
Opened 2020-09-18 22:11 UTC by j82w

# Pull Request Template

## Description

This updates the changelog, adds the public contract, and bumps the SDK version

![image](https://user-images.githubusercontent.com/8868107/93649614-3caa0080-f9c1-11ea-9379-1c4c70736ab1.png)

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #IssueNumber

2020-09-18 22:14 UTC, ealsur approved these changes

2020-09-19 10:22 UTC, kirankumarkolli commented
Aren't these breaking changes. Why?

2020-09-19 10:23 UTC, kirankumarkolli requested changes
Waiting to understanding the breaking changes aspect.

2020-09-21 18:46 UTC, bchong95 requested changes
Blocking on Central SDK team approval of added dependencies

2020-09-23 13:22 UTC, kirankumarkolli approved these changes

2020-09-23 16:42 UTC, bchong95 submitted a review, later dismissed

2020-09-23 18:00 UTC, kirankumarkolli approved these changes

2020-09-23 18:14 UTC, merged