Client Encryption : Add Support for AAP , its Encryption Algorithm and KeyWrap Provider Services.
Azure/azure-cosmos-dotnet-v3 pull request #1861
Opened 2020-09-21 12:12 UTC by kr-santosh

## Description

This PR focuses on integrating with AAP's core encryption algorithm.
This integrates various services provided by AAP which include core encryption
algorithm for Encrypting and Decrypting Data  and AAP's EncryptionKeyStoreProvider which is used as a Key Wrap Provider for securely managing Data Encryption Keys.(Currently AAP_PH is used as place holder package name until an official package 
is released).

## Type of change

Please delete options that are not relevant.

- [] New feature (non-breaking change which adds functionality)

2020-09-21 12:50 UTC, abhijitpai commented on Microsoft.Azure.Cosmos.Encryption/src/AapEncryptionAlgorithm.cs
> +            // use direct Byte key? TODO
Fix

2020-09-21 12:59 UTC, abhijitpai commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapContainer.cs
> +            using (JsonDocument doc = JsonDocument.Parse(input))
Double parsing since we already had parsed the full response in line 747.

2020-09-21 12:59 UTC, abhijitpai commented on Microsoft.Azure.Cosmos.Encryption/src/AapEncryptionAlgorithm.cs
> +#pragma warning disable SA1402 // File may only contain a single type
Put it in a different file if we need this class.

2020-09-21 13:00 UTC, abhijitpai commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapContainer.cs
> +    internal sealed class AapContainer : Container
Do we need all these? Seems like AapEncryptionProcessor and EncryptionProcessor will have the same interface (see comments on parsing) and so the existing set of classes can be used -> Just have a common base like EncryptionProcessor that derives AapEncryptionProcessor and LegacyEncryptionProcessor.

2020-09-21 13:05 UTC, abhijitpai commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKeyContainerCore.cs
> +                if (this.DekProvider.EncryptionKeyStoreProvider != null)
If you need an if-else here, the point of your adapter is lost. You need to set AapKeyWrapProvider upon init of this class and remove the if-elses.

2020-09-21 13:08 UTC, abhijitpai commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionKeyWrapMetadata.cs
> +        internal EncryptionKeyWrapMetadata(string type, string value, string name, string path, string algorithm = null)
What is the difference between path and value? And you are exposing some public properties below just because you want to use something internally - do not do that.

2020-09-21 13:10 UTC, abhijitpai requested changes
Please see if we need AapContainer and the like.

2020-09-21 13:13 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionKeyWrapMetadata.cs
> +        internal EncryptionKeyWrapMetadata(string type, string value, string name, string path, string algorithm = null)
Yes , they are not required.

Since Master Key Requires a Name and Path (in my internal usage i dont  need both value and path they both are same). I kept the Value since it was legacy and users might need it.To manage something and have Name and Paths as per AAP APIs.

 Will remove it.

2020-09-22 05:25 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/AapEncryptionAlgorithm.cs
> +                // safe enough to use get/create?
Fix

2020-09-22 05:29 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapEncryptionProcessor.cs
> +        {
Add null checks

2020-09-22 05:32 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapEncryptionProcessor.cs
> +            using (Utf8JsonWriter writer = new Utf8JsonWriter(outputStream))
If encryptionOptions is null, the below code will still get executed?

2020-09-22 05:34 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapEncryptionProcessor.cs
> +                    if (string.Equals(propertyName, "id"))
What is this check for?

2020-09-22 05:38 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapEncryptionProcessor.cs
> +                    if (!itemJObj.TryGetValue(propertyName, out JToken propertyValue))
propertyValue isn't being used?

2020-09-22 05:39 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapEncryptionProcessor.cs
> +                input = AapEncryptionProcessor.BaseSerializer.ToStream(itemJObj);
Why do we need this? Also itemJObj hasn't changed..

2020-09-22 05:40 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapEncryptionProcessor.cs
> +            using (JsonDocument document = JsonDocument.Parse(input))
Double parsing happening. First to JObject and then to JsonDocument. Can we make do with one or the other?

2020-09-22 05:43 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapEncryptionProcessor.cs
> +                                byte[] cipherText = await encryptor.EncryptAsync(
Encryption and replacement is happening in this for loop, the above for loop seems redundant.

2020-09-22 05:44 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapEncryptionProcessor.cs
> +                                (TypeMarker typeMarker, byte[] plainText) = Serialize(property.Value);
this.Serialize

2020-09-22 05:47 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapEncryptionProcessor.cs
> +                            catch (Exception ex)
Should we throw the exception instead of continuing?

2020-09-22 05:51 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapEncryptionProcessor.cs
> +                outputStream = AapEncryptionProcessor.BaseSerializer.ToStream(itemJObj);
This is one more parsing of stream. Can we not add the EncryptedInfo property before line 132?

2020-09-22 06:07 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapEncryptionProcessor.cs
> +            }
This check would have been done before encryption. Is this needed here?

2020-09-22 06:08 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapEncryptionProcessor.cs
> +                        catch (Exception ex)
Same comment as above. Should we throw instead?

2020-09-22 06:08 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapEncryptionProcessor.cs
> +        {
Add null checks

2020-09-22 06:11 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapEncryptionProcessor.cs
> +            EncryptionProperties encryptionProperties = null,
Return if null?

2020-09-22 06:11 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapEncryptionProcessor.cs
> +                            DeserializeAndWritePropertyValue(
this.DeserializeAndWritePropertyValue

2020-09-22 06:12 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapEncryptionProcessor.cs
> +                    if (encryptionProperties.EncryptedPaths != null &&
Merge the if conditions

2020-09-22 06:15 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapFeedIterator.cs
> +    internal sealed class AapFeedIterator : FeedIterator
Same comment as for AapContainer. Please refactor.

2020-09-22 06:22 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapKeyWrapProvider.cs
> +        internal AapKeyWrapProvider(EncryptionKeyStoreProvider encryptionKeyStoreProvider)
Please make the methods public for internal class

2020-09-22 06:24 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapTransactionalBatch.cs
> +    internal sealed class AapTransactionalBatch : TransactionalBatch
Please refactor.

2020-09-24 04:55 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapEncryptionProcessor.cs
> +                    if (string.Equals(propertyName, "id"))
This basically checks for the unique id which should not be encrypted. The legacy processor had a different approach of encrypting where property/value fields were removed and moved to ed field in encryption option ei. Hence the downstream call to create item would eventually fail,so the check was not required. Since now we do an in-place replacement of the encrypted value it never gets caught.

2020-09-24 04:57 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapEncryptionProcessor.cs
> +                    if (!itemJObj.TryGetValue(propertyName, out JToken propertyValue))
moved it out.

2020-09-24 04:58 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapEncryptionProcessor.cs
> +                                (TypeMarker typeMarker, byte[] plainText) = Serialize(property.Value);
private static func..does not require an instance.

2020-09-24 04:58 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapEncryptionProcessor.cs
> +                outputStream = AapEncryptionProcessor.BaseSerializer.ToStream(itemJObj);
Will look into it and address the same. Thanks

2020-09-24 05:02 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapEncryptionProcessor.cs
> +                        catch (Exception ex)
I will revisit this and get back on this.

2020-09-24 05:08 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/AapEncryptionAlgorithm.cs
> +            this.encryptionSettings = AapEncryptionSettings.InitializeAapEncryptionAlogrithm(aapEncryptionSettingForKey, encryptionType);
Can we merge these to one constructor call for AapEncryptionSettings?

public AapEncryptionSettings(
            MasterKey masterKey,
            EncryptionKey encryptionKey,
            Data.AAP_PH.Cryptography.EncryptionType encryptionType)

2020-09-24 05:12 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapCosmosEncryptor.cs
> +        public AapCosmosEncryptor(EncryptionKeyStoreProvider wrapProvider)
Please fix the parameter name

2020-09-24 05:12 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapCosmosEncryptor.cs
> +        /// <param name="wrapProvider"> User provided TokenCredential for accessing Key Vault services. </param>
Fix comment

2020-09-24 05:28 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapCosmosEncryptor.cs
> +        /// Creates an Encryption Key Provider for wrap and unwrapping Data Encryption key via AAP  Key Vault.
Fix comment

2020-09-24 05:29 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapCosmosEncryptor.cs
> +        /// Creates an Encryption Key Provider for wrap and unwrapping Data Encryption key via AAP  Key Vault.
Fix comment and parameter description

2020-09-24 05:30 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapCosmosEncryptor.cs
> +        public DataEncryptionKeyProvider DataEncryptionKeyProvider { get; }
Is there need for both CosmosDataEncryptionKeyProvider & DataEncryptionKeyProvider ?

2020-09-24 05:32 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapCosmosEncryptor.cs
> +        public Task InitializeAsync(
Why do we need this here? This is exposed on DekProvider directly.

2020-09-24 05:38 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapEncryptionProcessor.cs
> +        internal static readonly CosmosJsonDotNetSerializer BaseSerializer =
Move to base class, since this is common to both implementation?

2020-09-24 05:41 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapEncryptionProcessor.cs
> +            {
Common code repeated, please refactor.

2020-09-24 05:52 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapEncryptionProcessor.cs
> +                    if (!root.TryGetProperty(pathToEncrypt.Substring(1), out JsonElement jj))
Fix parameter name

2020-09-24 05:55 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapEncryptionProcessor.cs
> +                    }
This needs to be checked only once. Maybe along with the check on line 71.

2020-09-24 06:06 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapEncryptionProcessor.cs
> +                    }
this can be simplified, if you merge the 'if' check

2020-09-24 06:17 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapEncryptionProcessor.cs
> +            return await Task.FromResult(outputStream);
Dispose "input" stream

2020-09-24 06:45 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapEncryptionProcessor.cs
> +
Repeated code, please refactor

2020-09-24 06:46 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapEncryptionProcessor.cs
> +                    if (cipherTextWithTypeMarker == null)
when will this happen?

2020-09-24 07:32 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapEncryptionProcessor.cs
> +                    byte[]plainText = await AapEncryptionProcessor.DecryptContentAsync(
Fix typo

2020-09-24 07:35 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapEncryptionProcessor.cs
> +                                (TypeMarker typeMarker, byte[] plainText) = Serialize(property.Value);
for static functions the norm is to specify class name. AapEncryptionProcessor.Serialize()

2020-09-24 07:37 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapEncryptionProcessor.cs
> +            using (JsonDocument document = JsonDocument.Parse(input))
why are we using JsonDocument here instead of JObject - which is used in rest of the places?

2020-09-24 07:46 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/CosmosDataEncryptionKeyProvider.cs
> +            this.EncryptionKeyWrapProvider = new AapKeyWrapProvider(encryptionKeyStoreProvider);
Why are we doing this? This doesn't seem right.
Why do we need EncryptionKeyWrapProvider when we are provided EncryptionKeyStoreProvider ?

2020-09-24 07:48 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKey.cs
> +            }
Redundant change. Can revert.

2020-09-24 07:49 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionContainer.cs
> +            this.EncryptionProcessor = encryptionProcessor;
add null check

2020-09-24 07:50 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionContainerExtensions.cs
> +
nit: remove

2020-09-24 07:51 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionFeedIterator.cs
> +            JObject contentJObj = LegacyEncryptionProcessor.BaseSerializer.FromStream<JObject>(content);
should be this.encryptionProcessor

2020-09-24 07:52 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionFeedIterator.cs
> +                    MemoryStream memoryStream = LegacyEncryptionProcessor.BaseSerializer.ToStream(document);
same - should be this.encryptionProcessor

2020-09-24 07:52 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionFeedIterator.cs
> +            return LegacyEncryptionProcessor.BaseSerializer.ToStream(decryptedResponse);
should be this.encryptionProcessor

2020-09-24 07:54 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/KeyVault/AzureKeyVaultKeyWrapMetadata.cs
> +            : base(AzureKeyVaultKeyWrapMetadata.TypeConstant, masterKeyUri.AbsoluteUri, null, null)
named parameters

2020-09-24 07:55 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/KeyVault/AzureKeyVaultKeyWrapProvider.cs
> +            EncryptionKeyWrapMetadata responseMetadata = new EncryptionKeyWrapMetadata(metadata.Type, metadata.Value, null, KeyVaultConstants.RsaOaep256);
named parameters for null

2020-09-24 12:15 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/CosmosDataEncryptionKeyProvider.cs
> +            this.EncryptionKeyWrapProvider = new AapKeyWrapProvider(encryptionKeyStoreProvider);
Yes you are right. I will address this.

2020-09-24 13:27 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapKeyWrapProvider.cs
> +            this.aapKeyVaultServices = new AapKeyVaultServices(encryptionKeyStoreProvider);
we shouldn't need another layer of AapKeyVaultServices.

2020-09-24 13:36 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/AapServices/AapKeyWrapProvider.cs
> +            this.aapKeyVaultServices = new AapKeyVaultServices(encryptionKeyStoreProvider);
Yes, this is sort of unnecessary. Will address it. Thanks

2020-09-30 12:14 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/CosmosDataEncryptionKeyProvider.cs
> +            this.EncryptionKeyWrapProvider = new AapKeyWrapProvider(encryptionKeyStoreProvider);
Fixed.

2020-09-30 17:25 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/CosmosDataEncryptionKeyProvider.cs
> +            this.EncryptionKeyWrapProvider = new AapKeyWrapProvider(encryptionKeyStoreProvider);
Fixed

2020-10-13 11:35 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/CosmosEncryptionAlgorithm.cs
> +        /// MDE Randomized Encryption Algorithm
Can we add a link or some more information here for user?

2020-10-13 11:39 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKeyContainerCore.cs
>                  cancellationToken);
nit: Indentation

2020-10-13 11:43 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/DekCache.cs
> +            this.dekPropertiesTimeToLive = dekPropertiesTimeToLive.HasValue == true ? dekPropertiesTimeToLive.Value : TimeSpan.FromMinutes(30);
Please put this default value in Constants.cs . Also, to be consistent with SQL, we should have the default value as 2hrs.

2020-10-13 11:45 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs
> +//------------------------------------------------------------
nit: undo

2020-10-13 11:56 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs
> +                      encryptionOptions.PathsToEncrypt);
nit: indentation

2020-10-13 11:57 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs
> -            Debug.Assert(input.CanSeek);
Why are we removing this check?

2020-10-13 11:58 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs
> +                    cancellationToken);
nit: indentation

2020-10-13 12:02 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs
> +                    Debug.Fail(string.Format("Unexpected Encryption Algorithm {0}", encryptionProperties.EncryptionAlgorithm));
throw new NotSupportedException($"Encryption Algorithm : {encryptionOptions.EncryptionAlgorithm} is not supported.");

2020-10-13 12:03 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs
> +                    cancellationToken);
nit : indentation

2020-10-13 12:04 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs
> +                    cancellationToken);
nit : indentation

2020-10-13 12:05 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs
> +                    Debug.Fail(string.Format("Unexpected Encryption Algorithm {0}", encryptionProperties.EncryptionAlgorithm));
throw exception

2020-10-13 12:06 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs
> +            }
Repeated code - please refactor

2020-10-13 12:10 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs
> +                if (document.TryGetValue(path.Substring(1), out JToken propertyValue))
throw if condition is not met?

2020-10-13 12:19 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs
> -            Debug.Assert(input.CanSeek);
Moved to helper func RetrieveItem(

2020-10-13 12:20 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs
> +                    Debug.Fail(string.Format("Unexpected Encryption Algorithm {0}", encryptionProperties.EncryptionAlgorithm));
This is more of a Debug/Catch a bug. Since we shouldn't be here, the encrypted info is updated with Algorithm during Item Creation and we should have caught it back then.Hence a Debug rather than Exception.

2020-10-13 13:44 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/CosmosEncryptionAlgorithm.cs
> +        /// MDE Randomized Encryption Algorithm
I will add once we have a Public package from MDE and get the corresponding official info from them.

2020-10-14 05:40 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/DekCache.cs
> +            this.dekPropertiesTimeToLive = dekPropertiesTimeToLive.HasValue == true ? dekPropertiesTimeToLive.Value : TimeSpan.FromMinutes(30);
Fixed.

2020-10-14 05:40 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs
> +            }
Refactored.

2020-10-14 05:40 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs
> +                if (document.TryGetValue(path.Substring(1), out JToken propertyValue))
Fixed.

2020-10-16 10:39 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/Constants.cs
> +        public const int DekPropertiesTTL = 120;
use Timespan data type? or else rename to something like DekPropertiesTTLInMinutes

2020-10-16 10:42 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/CosmosDataEncryptionKeyProvider.cs
> +        internal TimeSpan? CacheTimeToLive { get; }
pdekCacheTimeToLive or mdeCacheTimeToLive?

2020-10-16 10:43 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/CosmosDataEncryptionKeyProvider.cs
> +        /// <param name="cacheTimeToLive">Time to live for EncryptionKeyStoreProvider's ProtectedDataEncryptionKey before having to refresh.Default or 0 results in no Caching.</param>
Default results in no caching?

2020-10-16 10:44 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/CosmosDataEncryptionKeyProvider.cs
> +        /// <param name="cacheTimeToLive">Time to live for EncryptionKeyStoreProvider's ProtectedDataEncryptionKey before having to refresh.Default or 0 results in no Caching.</param>
Also please add a space between new sentence start. To void confusing it as refresh.Default

2020-10-16 10:53 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKeyContainerCore.cs
> +                  mdeKeyWrapProvider.EncryptionKeyStoreProvider);
nit: indentaion

2020-10-16 10:55 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/MdeEncryptionTests.cs
> +        private static CosmosDataEncryptionKeyProvider dualdekProvider;
dualDekProvider

2020-10-16 10:56 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/MdeEncryptionTests.cs
> +            MdeEncryptionTests.dekProvider = new CosmosDataEncryptionKeyProvider(MdeEncryptionTests.testKeyStoreProvider, cacheTimeToLive: TimeSpan.FromSeconds(0));
please add tests to cover the other scenarios also - passing no value, passing a value other than 0

2020-10-16 10:59 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/MdeEncryptionTests.cs
> +            MdeEncryptionTests.dekProvider = new CosmosDataEncryptionKeyProvider(MdeEncryptionTests.testKeyStoreProvider, cacheTimeToLive: TimeSpan.FromSeconds(0));
might be worth covering unit tests for CosmosDEKProvider separately

2020-10-16 11:08 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/MdeEncryptionTests.cs
> +            DataEncryptionKeyProperties dekProperties = await MdeEncryptionTests.CreateDekAsync(MdeEncryptionTests.dualdekProvider, dekId);
can you also create and check for DEK created with new algo, just so as to cover that scenario in this test

2020-10-16 11:09 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/MdeEncryptionTests.cs
> +            MdeEncryptionTests.dekProvider = new CosmosDataEncryptionKeyProvider(MdeEncryptionTests.testKeyStoreProvider, cacheTimeToLive: TimeSpan.FromSeconds(0));
Sure. I am in the processes of appending ...adding new test cases as i think over.

2020-10-16 11:37 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionKeyWrapMetadata.cs
> +            this.Name = name ?? this.Value;
pls add a comment

2020-10-16 11:40 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/MdeServices/MdeKeyWrapProvider.cs
> +            }
This is repeated in multiple places. Can we have a GetName() method on EncryptionKeyWrapMetadata and put this logic there?

2020-10-19 13:51 UTC, j82w commented on Microsoft.Azure.Cosmos.Encryption/src/CosmosDataEncryptionKeyProvider.cs
> +        internal TimeSpan? PdekCacheTimeToLive { get; }
What does the P stand for?

2020-10-19 13:51 UTC, j82w commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKey.cs
>                  throw new ArgumentException($"Encryption algorithm not supported: {encryptionAlgorithm}", nameof(encryptionAlgorithm));
nit: Can we add what algorithms are supported to the exception message?

2020-10-19 13:51 UTC, j82w commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKeyContainerCore.cs
> +            if (encryptionAlgorithm != CosmosEncryptionAlgorithm.AEAes256CbcHmacSha256Randomized &&
Can we create a helper somewhere for this instead of duplicating the logic in multiple places?

2020-10-19 13:51 UTC, j82w commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKeyContainerCore.cs
> +            string encryptionAlgorithm,
Is there any reason the encryptionAlgorithm is not an enum?

2020-10-19 13:51 UTC, j82w commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKeyContainerCore.cs
> +            if (encryptionAlgorithm != CosmosEncryptionAlgorithm.AEAes256CbcHmacSha256Randomized &&
Null check encryptionAlgorithm or use string.equals instead.

2020-10-19 13:51 UTC, j82w commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKeyContainerCore.cs
> +            {
Please refactor the inner code into a separate method and avoid the giant if else statements.

2020-10-19 13:51 UTC, j82w commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKeyContainerCore.cs
> +                if (!(this.DekProvider.EncryptionKeyStoreWrapProvider is MdeKeyWrapProvider mdeKeyWrapProvider))
Same comment as above to refactor the inner logic to separate methods to avoid the large methods. It almost seems like there should be an interface or abstraction layer to deal with this instead of having all of the if else logic everywhere.

2020-10-19 13:51 UTC, j82w commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionKeyWrapMetadata.cs
> +                   this.Name == other.Name;
Won't Name be null for all the existing customers? Please make sure you don't break upgrade scenarios. I would always recommend using `string.equals` instead to avoid possible null reference exceptions.

2020-10-19 13:51 UTC, j82w commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs
> +                    Debug.Fail(string.Format("Unexpected Encryption Algorithm {0}", encryptionProperties.EncryptionAlgorithm));
It's possible that the customer will have multiple SDK instance and some will have older version that doesn't have the new algorithm.

2020-10-19 13:51 UTC, j82w commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs
> +                if (document.TryGetValue(path.Substring(1), out JToken propertyValue))
nit. You can do the following to make it easier to read.
```c#
if (!document.TryGetValue(path.Substring(1), out JToken propertyValue))
{
   throw...
}
```

2020-10-19 13:51 UTC, j82w commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs
> +        private enum TypeMarker : byte
Please make sure to have unit test to ensure all the types are handled.

2020-10-19 13:51 UTC, j82w commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionProperties.cs
> +            IEnumerable<string> encryptedPaths = null)
I would recommend avoiding using default values unless necessary. It makes it very easy to miss somewhere in the code that should be setting it, but doesn't.

2020-10-20 06:48 UTC, abhijitpai commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKeyContainerCore.cs
> +            string encryptionAlgorithm,
This was based on discussion with @kirankumarkolli to keep the layers not needing to know about specific algo names. In future, for the non-per-item model also the proposal from Kiran is to have the encryption policy read happen in the core SDK, but the code SDK may not have the algorithms enum  since that depends on the encryption library.

2020-10-20 06:52 UTC, abhijitpai commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionKeyWrapMetadata.cs
> +                   this.Name == other.Name;
x == null and null == y are both fine in C# and compare intuitively, string.Equals is not required. We shouldn't update customer's metadata implicitly, but we can just use the .Value if the .Name is null at the point of use.

2020-10-20 08:20 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionKeyWrapMetadata.cs
> +                   this.Name == other.Name;
Yes will remove updating the MetaData.

2020-10-20 09:59 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/CosmosDataEncryptionKeyProvider.cs
> +        internal TimeSpan? PdekCacheTimeToLive { get; }
Protected Data Encryption Key

2020-10-20 10:05 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKeyContainerCore.cs
> +                if (!(this.DekProvider.EncryptionKeyStoreWrapProvider is MdeKeyWrapProvider mdeKeyWrapProvider))
Sure will refactor, looks bloated. The reason we have multi wrap provider is for Teams requirement for providing backward compatibility for reading back items which were encrypted with old algorithm with a single initialization of Encryptor within  a single instance of Client . This should go away once we deprecate the Old/Legacy encryption algorithm and move completely to MDE based algorithm.

2020-10-20 10:05 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionProperties.cs
> +            IEnumerable<string> encryptedPaths = null)
Sure.

2020-10-20 10:07 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs
> +                if (document.TryGetValue(path.Substring(1), out JToken propertyValue))
Sure, will do.

2020-10-20 10:07 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/Constants.cs
> +        public const int DekPropertiesTTL = 120;
Sure.

2020-10-20 10:08 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/MdeServices/MdeKeyWrapProvider.cs
> +            }
Sure.

2020-10-20 10:09 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKey.cs
>                  throw new ArgumentException($"Encryption algorithm not supported: {encryptionAlgorithm}", nameof(encryptionAlgorithm));
Sure, will add it.

2020-10-20 10:09 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKeyContainerCore.cs
> +            if (encryptionAlgorithm != CosmosEncryptionAlgorithm.AEAes256CbcHmacSha256Randomized &&
Moved the check to a helper.

2020-10-20 14:31 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs
> +        private enum TypeMarker : byte
Yes. Different data types have been introduced to cover this.

2020-10-27 19:12 UTC, abhijitpai commented on Microsoft.Azure.Cosmos.Encryption/tests/Microsoft.Azure.Cosmos.Encryption.Tests/Contracts/DotNetSDKEncryptionAPI.json
> +        "Microsoft.Azure.Cosmos.Encryption.EncryptionKeyWrapProvider EncryptionKeyStoreWrapProvider": {
Seems weird - what is this?

2020-10-28 03:36 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/tests/Microsoft.Azure.Cosmos.Encryption.Tests/Contracts/DotNetSDKEncryptionAPI.json
> +        "Microsoft.Azure.Cosmos.Encryption.EncryptionKeyWrapProvider EncryptionKeyStoreWrapProvider": {
This is for the teams requirement, to provide support for decrypting both Legacy and MDE encrypted items, so we init both the types of WrapProviders. One for KeyStoreProvider via MdeWrapProvider and other Legacy WrapProvider.

2020-11-02 10:36 UTC, abhijitpai commented on Microsoft.Azure.Cosmos.Encryption/src/Constants.cs
> +        public const int DekPropertiesTTLInMinutes = 120;
Add Default before TTL

2020-11-02 10:37 UTC, abhijitpai commented on Microsoft.Azure.Cosmos.Encryption/src/CosmosDataEncryptionKeyProvider.cs
> +        public EncryptionKeyWrapProvider EncryptionKeyStoreWrapProvider { get; }
Provide EncryptionKeyStoreProvider

2020-11-02 10:51 UTC, abhijitpai commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKey.cs
> +            if (!CosmosEncryptionAlgorithm.VerifyIfSupportedAlgorithm(encryptionAlgorithm))
Don't need this change.. we don't invoke this for the new algo, but use MDE code.

2020-11-02 10:52 UTC, abhijitpai commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKey.cs
> +                throw new ArgumentException($"Encryption algorithm not supported: {encryptionAlgorithm}.Supported Algorithms include '{CosmosEncryptionAlgorithm.AEAes256CbcHmacSha256Randomized}','{Co
space after .

2020-11-02 11:12 UTC, abhijitpai commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKeyContainerCore.cs
> +                        : throw new ArgumentException(string.Format("Unsupported Encryption Algorithm {0} for the initialized WrapProvider Service.", encryptionAlgorithm));
Maybe: 'Unsupported encryption algorithm {0}. Please initialize the Encryptor or CosmosDataEncryptionKeyProvider with an implementation of the EncryptionKeyStoreProvider / EncryptionKeyWrapProvider.

2020-11-02 11:19 UTC, abhijitpai commented on Microsoft.Azure.Cosmos.Encryption/src/CosmosDataEncryptionKeyProvider.cs
> +                cancellationToken: cancellationToken);
Check the algo compat here.

2020-11-02 11:20 UTC, abhijitpai commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKeyContainerCore.cs
> +            string encryptionAlgorithm,
Remove encryptionAlgorithm from here..

2020-11-02 11:23 UTC, abhijitpai commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKeyContainerCore.cs
> +                throw new ArgumentException(string.Format("Unsupported Encryption Algorithm {0} for the initialized WrapProvider Service.", dekProperties.EncryptionAlgorithm));
Fix similar to other instance.

2020-11-02 11:29 UTC, abhijitpai commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKeyContainerCore.cs
> +            if (!(this.DekProvider.EncryptionKeyWrapProvider is EncryptionKeyWrapProvider encryptionKeyWrapProvider))
Just do a null check - the DekProvider.EncryptionKeyWrapProvider is always going to be an EncryptionKeyWrapProvider

2020-11-02 11:32 UTC, abhijitpai commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKeyContainerCore.cs
> +                    $"{nameof(this.DekProvider)} needs to be initialized with {nameof(EncryptionKeyWrapProvider)}.");
this.DekProvider is an internal member. Please reword similar to other instances.

2020-11-02 11:34 UTC, abhijitpai commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKeyContainerCore.cs
> +        private async Task<(byte[], EncryptionKeyWrapMetadata, InMemoryRawDek)> GenerateAndWrapRawDekAsync(
Add something like ForLegacy in the name

2020-11-02 11:34 UTC, abhijitpai commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKeyContainerCore.cs
> +                    $"{nameof(this.DekProvider)} needs to be initialized with {nameof(MdeKeyWrapProvider)}.");
Fix similar to other instances.

2020-11-02 11:35 UTC, abhijitpai commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKeyContainerCore.cs
> +            if (!(this.DekProvider.EncryptionKeyStoreWrapProvider is MdeKeyWrapProvider mdeKeyWrapProvider))
Just make it a null check

2020-11-02 11:35 UTC, abhijitpai commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKeyContainerCore.cs
> +            if (!(this.DekProvider.EncryptionKeyWrapProvider is EncryptionKeyWrapProvider encryptionKeyWrapProvider))
null check

2020-11-02 11:35 UTC, abhijitpai commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKeyContainerCore.cs
> +                throw new InvalidOperationException($"For use of '{CosmosEncryptionAlgorithm.AEAes256CbcHmacSha256Randomized}' algorithm, " +
fix similar to others

2020-11-02 11:38 UTC, abhijitpai commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKeyContainerCore.cs
> +        private (byte[], EncryptionKeyWrapMetadata, InMemoryRawDek) GenerateAndWrapMdePdek(
nit: Needn't return InMemoryRawDek

2020-11-02 13:19 UTC, abhijitpai commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs
> -            Debug.Assert(input.CanSeek);
This is needed for the reset, where we do input.Position = 0; let's leave it here.

2020-11-02 13:21 UTC, abhijitpai commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs
> +            if (document == null)
Who is calling this with empty document? Would be better to revert it rather than silent return.

2020-11-02 13:35 UTC, abhijitpai commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs
>              if (!document.TryGetValue(Constants.EncryptedInfo, out JToken encryptedInfo))
Can call the RetrieveEncryptionProperties helper

2020-11-02 13:37 UTC, abhijitpai commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs
> +                    throw new ArgumentException($"{nameof(encryptionProperties.EncryptedPaths)} includes a path: '{path}' which was not found.");
InvalidOperationException

2020-11-02 13:43 UTC, abhijitpai commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs
> +                    path.Substring(1));
put it in propertyName variable above

2020-11-02 13:45 UTC, abhijitpai commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs
> +                    decryptionContext = await EncryptionProcessor.DecryptObjectAsync(
Put Mde and Legacy in the methods specific to the algo

2020-11-02 13:48 UTC, abhijitpai commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs
> +                itemJObj = JsonSerializer.Create().Deserialize<JObject>(jsonTextReader);
Use the JsonSerializerSettings with date parse handling

2020-11-02 14:11 UTC, abhijitpai commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs
> +                    return (TypeMarker.Float, sqlSerializerFactory.GetDefaultSerializer<float>().Serialize(propertyValue.ToObject<float>()));
Rename to TypeMarker.Double and do a GetDefaultSerializer<double>

2020-11-02 14:34 UTC, abhijitpai commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs
> +                    return (TypeMarker.RawText, sqlNvarcharSerializer.Serialize(propertyValue.ToString()));
Let's throw instead of this, and remove .RawText

2020-11-03 07:17 UTC, abhijitpai commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs
> +                    return (TypeMarker.Integer, sqlSerializerFactory.GetDefaultSerializer<int>().Serialize(propertyValue.ToObject<int>()));
Rename to TypeMarker.Long and do a GetDefaultSerializer< long >

2020-11-03 09:09 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/Constants.cs
> +        public const int DekPropertiesTTLInMinutes = 120;
Fixed.

2020-11-03 09:10 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/CosmosDataEncryptionKeyProvider.cs
> +        public EncryptionKeyWrapProvider EncryptionKeyStoreWrapProvider { get; }
Exposed EncryptionKeyStoreProvider  and using MdeKeyWrapProvider as internal moved out exposed EncryptionKeyWrapProvider .

2020-11-03 09:10 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKey.cs
> +            if (!CosmosEncryptionAlgorithm.VerifyIfSupportedAlgorithm(encryptionAlgorithm))
Fixed.

2020-11-03 09:10 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKeyContainerCore.cs
> +                        : throw new ArgumentException(string.Format("Unsupported Encryption Algorithm {0} for the initialized WrapProvider Service.", encryptionAlgorithm));
Fixed all.

2020-11-03 09:11 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/CosmosDataEncryptionKeyProvider.cs
> +                cancellationToken: cancellationToken);
Checking it here now.

2020-11-03 09:11 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKeyContainerCore.cs
> +            string encryptionAlgorithm,
As per suggestion moved out the Algo Compat check from here.

2020-11-03 09:12 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKeyContainerCore.cs
> +            if (!(this.DekProvider.EncryptionKeyWrapProvider is EncryptionKeyWrapProvider encryptionKeyWrapProvider))
Done, Fixed all instances.

2020-11-03 09:12 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKeyContainerCore.cs
> +        private async Task<(byte[], EncryptionKeyWrapMetadata, InMemoryRawDek)> GenerateAndWrapRawDekAsync(
Renamed as suggested.

2020-11-03 09:12 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKeyContainerCore.cs
> +        private (byte[], EncryptionKeyWrapMetadata, InMemoryRawDek) GenerateAndWrapMdePdek(
Fixed.

2020-11-03 09:12 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs
> +            if (document == null)
Fixed.

2020-11-03 09:13 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs
>              if (!document.TryGetValue(Constants.EncryptedInfo, out JToken encryptedInfo))
Using helper.

2020-11-03 09:13 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs
> +                    throw new ArgumentException($"{nameof(encryptionProperties.EncryptedPaths)} includes a path: '{path}' which was not found.");
Fixed.

2020-11-03 09:13 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs
> +                    decryptionContext = await EncryptionProcessor.DecryptObjectAsync(
Renamed as suggested.

2020-11-03 09:13 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs
> +                itemJObj = JsonSerializer.Create().Deserialize<JObject>(jsonTextReader);
Fixed.

2020-11-03 09:13 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs
> +                    return (TypeMarker.Float, sqlSerializerFactory.GetDefaultSerializer<float>().Serialize(propertyValue.ToObject<float>()));
Fixed.

2020-11-03 09:13 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs
> +                    return (TypeMarker.RawText, sqlNvarcharSerializer.Serialize(propertyValue.ToString()));
Fixed.

2020-11-03 09:14 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs
> +                    return (TypeMarker.Integer, sqlSerializerFactory.GetDefaultSerializer<int>().Serialize(propertyValue.ToObject<int>()));
Fixed. Moved Int to Long.

2020-11-03 09:17 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/tests/Microsoft.Azure.Cosmos.Encryption.Tests/Contracts/DotNetSDKEncryptionAPI.json
> +        "Microsoft.Azure.Cosmos.Encryption.EncryptionKeyWrapProvider EncryptionKeyStoreWrapProvider": {
Moved it out and using MdeKeyWrapProvider instead directly as internal and exposed public EncryptionKeyStoreProvider instead.

2020-11-03 11:47 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKey.cs
>                  throw new ArgumentException($"Encryption algorithm not supported: {encryptionAlgorithm}", nameof(encryptionAlgorithm));
Fixed.

2020-11-03 11:47 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKeyContainerCore.cs
> +            {
Fixed.

2020-11-04 07:22 UTC, abhijitpai commented on Microsoft.Azure.Cosmos.Encryption/src/CosmosDataEncryptionKeyProvider.cs
> +                if (!CosmosEncryptionAlgorithm.VerifyIfSupportedAlgorithm(dataEncryptionKeyProperties.EncryptionAlgorithm))
Why will it not be supported? Your helper should instead take 2 algorithms and verify compatibility.

2020-11-04 08:00 UTC, abhijitpai commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKeyContainerCore.cs
> +                            dekProperties.EncryptionAlgorithm));
encryptionAlgorithm

2020-11-04 08:05 UTC, abhijitpai commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKeyContainerCore.cs
> +            return new MdeEncryptionAlgorithm(
We should not use the encryption key Store provider to unwrap a key that has been created using the key Wrap provider. This confusion exists because we have passed the encryptionAlgorithm into unwrap rather than getting the unwrap result and then creating the required in memory key based on the requested algorithm.

2020-11-04 12:27 UTC, kirankumarkolli approved these changes
:shipit:

2020-11-05 05:59 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKeyContainerCore.cs
> +            return new MdeEncryptionAlgorithm(
Yes, you are right, I was thinking for the use case where we would want to use legacy DEK for MDE based encryption have a  derivative of Abstract class DataEncryptionKey and init the RootKey by calling base constructor, after we unwrap using the original wrap provider and then use the DataEncryptionKey to init the MDE Algorithm. This is required since we cannot use AAP provided ProtectedDataEncryptionKey which only accepts EncryptedKey.

2020-11-10 08:30 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/CosmosDataEncryptionKeyProvider.cs
> +                ?? throw new ArgumentNullException(nameof(encryptionKeyStoreProvider)));
Redundant null check, can remove this. Has been checked above.

2020-11-10 09:46 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/CosmosDataEncryptionKeyProvider.cs
> +                ?? throw new ArgumentNullException(nameof(encryptionKeyStoreProvider)));
Fixed.

2020-11-10 10:16 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKey.cs
>                  throw new ArgumentException($"Encryption algorithm not supported: {encryptionAlgorithm}", nameof(encryptionAlgorithm));
Add the supported algo to the message.

2020-12-03 15:24 UTC, j82w commented on Microsoft.Azure.Cosmos.Encryption/src/Microsoft.Azure.Cosmos.Encryption.csproj
> +      <HintPath>..\src\MdeServices\MdeCryptographyLib\Microsoft.Data.Encryption.Cryptography.dll</HintPath>
This will cause version conflicts in the future if the dll is changed or if other projects reference the same version.

2020-12-03 15:37 UTC, j82w commented on Microsoft.Azure.Cosmos.Encryption/src/Microsoft.Azure.Cosmos.Encryption.csproj
> +    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="3.1.7" />
If these are used in the SDK should the version be specified in the props file so they are always in sync?

2020-12-03 15:37 UTC, j82w commented on Microsoft.Azure.Cosmos.Encryption/src/MdeServices/MdeEncryptionAlgorithm.cs
> +namespace Microsoft.Azure.Cosmos.Encryption
Can we add a readme.md to explain the dll and ownership.

2020-12-03 15:40 UTC, j82w commented on Microsoft.Azure.Cosmos.Encryption/src/Microsoft.Azure.Cosmos.Encryption.csproj
> +    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="1.1.2" />
Please make sure all the new dependencies follow the [Azure Core guidelines](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-dependencies).

2020-12-04 04:50 UTC, abhijitpai commented on Microsoft.Azure.Cosmos.Encryption/src/Microsoft.Azure.Cosmos.Encryption.csproj
> +    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="1.1.2" />
@j82w - the point of the encryption package is to allow these dependencies. This is a dependency of the MDE package.

2020-12-04 05:23 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/MdeServices/MdeEncryptionAlgorithm.cs
> +namespace Microsoft.Azure.Cosmos.Encryption
Sure. Done

2020-12-04 05:29 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/Microsoft.Azure.Cosmos.Encryption.csproj
> +      <HintPath>..\src\MdeServices\MdeCryptographyLib\Microsoft.Data.Encryption.Cryptography.dll</HintPath>
This is just for short time period until get a formal nuget package from AAP. Since we are managing the dll ourselves and placing it in the folder and using it.  If there is an issue with multiple dll  which is highly unlikely since it is a private release , we ask the customer to upgrade if and when a need arises. Once we have a formal nuget package we move away from this arrangement.

2020-12-04 05:31 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/Microsoft.Azure.Cosmos.Encryption.csproj
> +    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="3.1.7" />
Not sure why is this required as this is dependency of the AAP dll and internal to AAP/Encryption package and will not affect the SDK.

2020-12-04 12:55 UTC, j82w commented on Microsoft.Azure.Cosmos.Encryption/src/Microsoft.Azure.Cosmos.Encryption.csproj
> +    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="3.1.7" />
As long as none of them are used by the SDK then it is fine. I'm just worried if the SDK is using version 3.2.0 and Encryption takes dependency on version 3.1.7 then it causes issues. Since the SDK does not have these dependencies then it is fine.

2020-12-04 15:18 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos.Encryption/src/Microsoft.Azure.Cosmos.Encryption.csproj
> +    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="1.1.2" />
As discussed with Raghav, AAP team will close on the dependency part in [CO]. 
The encryption library is still in [Preview] and we all agreed that with the string commitment to addresses in [CO] this path is reasonable. 

Also please note that we need to move to package dependency in [CO] before GA, so there is future committed backlog already.

2020-12-22 13:04 UTC, j82w commented on Microsoft.Azure.Cosmos.Encryption/src/MdeServices/MdeEncryptionAlgorithm.cs
> +                // no caching
Why is setting cacheTimeToLive to zero different then setting it to null?

2020-12-22 13:04 UTC, j82w commented on Microsoft.Azure.Cosmos.Encryption/src/MdeServices/MdeKeyWrapProvider.cs
> +            byte[] result = keyEncryptionKey.DecryptEncryptionKey(wrappedKey);
The lack of a diagnostic story is really worrisome for future CRIs. I don't see anything tracking the latency of the encryptions or possibly slow issues getting the encryption keys.

2020-12-22 13:17 UTC, j82w commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKeyContainerCore.cs
> +            if (string.Equals(dekProperties.EncryptionAlgorithm, CosmosEncryptionAlgorithm.AEAes256CbcHmacSha256Randomized))
Should there be a factory model for this to avoid all the if else statements?

2020-12-22 13:17 UTC, j82w commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKeyContainerCore.cs
> +                keyWrapResponse = string.Equals(encryptionAlgorithm, CosmosEncryptionAlgorithm.AEAes256CbcHmacSha256Randomized) && this.DekProvider.EncryptionKeyWrapProvider != null
This is difficult to read. Can this be switched to if statements?

2020-12-22 13:21 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/MdeServices/MdeEncryptionAlgorithm.cs
> +                // no caching
Hi Jake , these are the cases

1) If the customer like MS teams do not want to cache (use their own caching mechanism) we make sure the wrapped key is never cached and thus can be handled by their own cache.
2) They can provide a cache time to live.
3) If no value is provided / null we default to AAP's cache time to live. That's where GetorCreate if not provided with a TTL defaults to AAPs default value.

2020-12-22 14:21 UTC, abhijitpai submitted a review, later dismissed

2020-12-22 14:55 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKeyContainerCore.cs
> +            if (string.Equals(dekProperties.EncryptionAlgorithm, CosmosEncryptionAlgorithm.AEAes256CbcHmacSha256Randomized))
This was a specific requirement to support legacy encryption model until teams are able to completely migrate to AAP/MDE based encryption keep all the interfaces same. We will stop support this and as soon as they migrate to new encryption (AAP) based algorithm.

2020-12-22 14:58 UTC, j82w submitted a review, later dismissed

2020-12-22 15:14 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionKeyWrapMetadata.cs
> +            string algorithm = null,
Since this is an internal method.. and the parameters are optional.

2020-12-22 15:25 UTC, kr-santosh commented on Microsoft.Azure.Cosmos.Encryption/src/MdeServices/MdeEncryptionAlgorithm.cs
> +                if (cacheTimeToLive.Value == TimeSpan.FromMilliseconds(0))
Sure, Done.

2020-12-22 15:47 UTC, j82w commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionKeyWrapMetadata.cs
> +            string algorithm = null,
The problem is that callers might not realize they should be passing the values. It is easy to miss that a algorithm was provided, but forgotten to be passed into the EncryptionKeyWrapMetadata constructor. For example there has been several bugs where the cancellation token was not getting passed because it is default everywhere.

2020-12-22 16:57 UTC, j82w approved these changes

2020-12-22 16:58 UTC, merged