Session token support for transactional batch
Azure/azure-cosmos-dotnet-v3 pull request #1870
Opened 2020-09-23 11:26 UTC by rakkuma

# Session token support for transactional batch

## Description

This adds support for passing session token for transactional Batch. In TransactionalBatchRequestOptions new option namely SessionToken is added. 

## Type of change

- [] New feature (non-breaking change which adds functionality)

## Closing issues

To automatically close an issue: closes #1567

2020-09-23 11:51 UTC, j82w requested changes

2020-09-23 11:51 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchRequestOptions.cs
> +        public string SessionToken { get; set; }
Please run the [UpdateContracts.ps1](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/UpdateContracts.ps1) script

2020-09-23 16:40 UTC, ealsur requested changes
Waiting on the response to the behavior for the end user

2020-09-23 16:40 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchRequestOptions.cs
> +        /// The DocumentClient will use this token internally with each read/query/batch request to ensure that the set
```suggestion
        /// The CosmosClient will use this token internally with each read/query/batch request to ensure that the set
```

2020-09-23 16:40 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchRequestOptions.cs
> +        /// </remarks>
```suggestion
        /// <see href="https://docs.microsoft.com/azure/cosmos-db/consistency-levels" />
        /// </remarks>
```

2020-09-23 16:40 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchResponse.cs
> +                    if ((int)result.StatusCode != (int)StatusCodes.FailedDependency && (int)result.StatusCode >= (int)StatusCodes.StartingErrorCode)
In our Batch examples, we tell users to use FailedDependency to rule out the operations that failed because of some other failing in the batch (like, if you send 2 operations and one fails with a 409, the other would have the 424). Does this change with this PR?

2020-09-23 16:44 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchRequestOptions.cs
> +        /// Consider a web application with multiple nodes, each node will have its own instance of <see cref="DocumentClient"/>
CosmosClient

2020-09-23 16:45 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchRequestOptions.cs
> +        /// you would have to send the SessionToken from <see cref="ItemResponse{T}"/> of the write action on one node
BatchResponse

2020-09-23 16:55 UTC, rakkuma commented on Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchRequestOptions.cs
> +        public string SessionToken { get; set; }
Done. Thanks.

2020-09-23 16:58 UTC, rakkuma commented on Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchResponse.cs
> +                    if ((int)result.StatusCode != (int)StatusCodes.FailedDependency && (int)result.StatusCode >= (int)StatusCodes.StartingErrorCode)
No no. This won't change anything. It returns the status code of actual failed operation. This extra change is to handle status code 304 i.e. NotModified. In case of not modified we should return MultiStatus to the user.

2020-09-25 21:19 UTC, kirankumarkolli submitted a review, later dismissed

2020-09-25 21:19 UTC, kirankumarkolli commented
Please resolve all comments

2020-09-26 00:55 UTC, bchong95 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Batch/BatchTestBase.cs
> +            }
else if (from is VectorSessionToken)
else throw

2020-09-26 00:56 UTC, bchong95 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Batch/BatchTestBase.cs
> +                return new VectorSessionToken(from as VectorSessionToken, globalLSN);
>from as VectorSessionToken [](start = 46, length = 26)

This could return null if a new type is added.

2020-09-28 19:37 UTC, ealsur submitted a review, later dismissed
Left some comments for text/links updates

2020-09-29 06:38 UTC, rakkuma commented on Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchRequestOptions.cs
> +        /// The DocumentClient will use this token internally with each read/query/batch request to ensure that the set
Fixed. Thanks.

2020-09-29 06:38 UTC, rakkuma commented on Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchRequestOptions.cs
> +        /// Consider a web application with multiple nodes, each node will have its own instance of <see cref="DocumentClient"/>
Fixed. Thanks.

2020-09-29 06:38 UTC, rakkuma commented on Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchRequestOptions.cs
> +        /// </remarks>
Fixed. Thanks.

2020-09-29 06:39 UTC, rakkuma commented on Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchRequestOptions.cs
> +        /// you would have to send the SessionToken from <see cref="ItemResponse{T}"/> of the write action on one node
Fixed. Thanks.

2020-09-29 06:40 UTC, rakkuma commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Batch/BatchTestBase.cs
> +            }
Fixed. Thanks.

2020-10-08 14:43 UTC, j82w approved these changes

2020-10-08 16:50 UTC, abhijitpai approved these changes

2020-10-16 16:02 UTC, ealsur commented
@rakkuma Can you fix the Emulator tests that are failing? They are throwing NullReferenceException

2020-10-19 17:20 UTC, rakkuma commented
The change which enable few test cases are in 0901. So until the next emulator is built, we can wait.

2021-02-12 15:52 UTC, ealsur approved these changes
Please get a signoff from @kirankumarkolli due to the public API change

2021-02-12 18:08 UTC, kirankumarkolli approved these changes

2021-02-12 19:01 UTC, merged