ChangeFeedRequestOptions: Fixes Encryption SDK dependency
Azure/azure-cosmos-dotnet-v3 pull request #1893
Opened 2020-09-30 23:24 UTC by j82w

# Pull Request Template

## Description

Removing the Sealed ChangeFeedRequestOptions to make it compatible with Encryption preview SDK.

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #IssueNumber

2020-09-30 23:39 UTC, ealsur approved these changes

2020-10-01 01:04 UTC, bchong95 requested changes
As discussed. Patch the version of the encryption client that the internal team needs instead of unsealing the class.

2020-10-01 01:25 UTC, j82w commented
> As discussed. Patch the version of the encryption client that the internal team needs instead of unsealing the class.

As discussed this will get reverted after the hotfix is released.

2020-10-01 13:25 UTC, kirankumarkolli approved these changes

2020-10-08 12:25 UTC, closed without merging