Enable Subpartitioning feature to be available as public preview.
Azure/azure-cosmos-dotnet-v3 pull request #1952
Opened 2020-10-22 02:51 UTC by SrinikhilReddy

# Enable subpartitioning feature to be available as public preview.

## Description

The current change adds functionality to create containers with multiple partition key paths. 

1. Adds the new PartitionKind 'MultiHash' which accepts multiple Partition keys.
2. Changes done:
    1. New Class `PartitionKeyBuilder`. 
    2. New `ContainerProperties` constructor that accepts an `IReadOnlyList<string>` object as multiple partition key paths
    3. Changes to extract multiple partition keys from the Resource object.
  
Sample usage of Collection create with MultiHash Partition kind and multiple partition key paths.
```c#
CosmosClient client = TestCommon.CreateCosmosClient(true);
Cosmos.Database database = await client.CreateDatabaseAsync("mydb");

ContainerProperties containerProperties = new ContainerProperties("mycoll", new List<string>{"/Zipcode","/City"});
Container container = await database.CreateContainerAsync(containerProperties);

```
Sample Document Create, where the PartitionKey is extracted from the resource stream.
```c#
Document  doc1 = new Document { Id = "Id1" };
doc1.SetValue("ZipCode", 15232);
doc1.SetValue("Address", "Pittsburgh");
await container.CreateItemAsync<Document>(doc1);
```
Reading back the document with the PartitionKey set during the read call.
```c#
PartitionKey partitionKey = new PartitionKeyBuilder()
                .Add(15232)
                .Add("Pittsburgh")
                .Build();                    
Document readDocument = (await container.ReadItemAsync<Document>("Id1", partitionKey )).Resource;
```
## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

2020-10-22 11:38 UTC, j82w commented on Microsoft.Azure.Cosmos/src/CosmosClient.cs
> +            #if PREVIEW
Please run the ./UpdateContracts.ps1 to update the preview contract file.

2020-10-28 20:06 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/CosmosClient.cs
> +            #if PREVIEW
This is no longer INTERNAL, we should remove the Internal keyword from the PR

2020-10-28 20:07 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/CosmosClient.cs
> +            HttpConstants.Versions.CurrentVersion = HttpConstants.Versions.v2020_07_15;
Are there any other changes we are bringing with the version bump from the protocol/wire perspective?

2020-10-28 20:08 UTC, SrinikhilReddy commented on Microsoft.Azure.Cosmos/src/CosmosClient.cs
> +            #if PREVIEW
Removed.

2021-01-04 16:15 UTC, j82w commented
Closing since there has been no update for over 30 days. Please re-open if necessary.

2021-01-07 21:35 UTC, SrinikhilReddy commented
This PR was closed because of a lack of Java support for subpartitioning. Java PR is now out, https://github.com/Azure/azure-sdk-for-java/pull/18503. Reopening this PR for merge consideration.

2021-01-29 07:18 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/CosmosClient.cs
> +            HttpConstants.Versions.CurrentVersion = HttpConstants.Versions.v2020_07_15;
Had similar comments on JAVA version.

2021-01-29 07:19 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/PartitionKeyBuilder.cs
> +#if PREVIEW
Please cover in the code docs that its an ordered pk collection

2021-01-29 07:22 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs
> +#if PREVIEW
@j82w, @ealsur can this branch be made unconditional?
Or what's the use-case to make it conditional, if the top level composition is not available.

2021-01-29 07:24 UTC, kirankumarkolli requested changes
Lets please ensure that JAVA and .NET API's are in sync. 
JAVA has new comments and if deviates then similar changes are needed in .NET

2021-01-29 12:47 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs
> +#if PREVIEW
Yes, it was added to make it easier to produce a private nuget with the feature enabled.

2021-02-12 12:08 UTC, SrinikhilReddy commented on Microsoft.Azure.Cosmos/src/CosmosClient.cs
> +            HttpConstants.Versions.CurrentVersion = HttpConstants.Versions.v2020_07_15;
Hi @ealsur, @kirankumarkolli The version bump helps support the subpartitioning change. Currently subpartitiong and merge are the features supported on this version

2021-02-12 18:14 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/CosmosClient.cs
> +            HttpConstants.Versions.CurrentVersion = HttpConstants.Versions.v2020_07_15;
Sub-part version is just after current version. Not an issue here.

2021-02-12 18:15 UTC, kirankumarkolli submitted a review, later dismissed

2021-02-12 21:54 UTC, j82w approved these changes

2021-02-13 01:15 UTC, merged