Draft: Gateway exception handling: Adds additional retry logic and makes it more aggressive
Azure/azure-cosmos-dotnet-v3 pull request #1954
Opened 2020-10-22 22:40 UTC by j82w

# Pull Request Template

## Description

1. Adds the timeout logic described in issue: https://github.com/Azure/azure-cosmos-dotnet-v3/issues/1912
2. All HttpRequestExceptions for get operations are retried 3 times with a maximum of 30 seconds.

Tests are still in progress.

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #IssueNumber

2020-10-23 17:38 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClient.cs
> +                return TimeoutPolicy.ControlPlaneHotPath;
This is going to increase the number of timeouts for query plan. Without extensive diagnostics query is going to get all the CRIs.

2020-10-23 17:38 UTC, bchong95 requested changes
New timeouts for query plan need to be approved by query team.

2020-10-23 18:51 UTC, j82w commented on Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClient.cs
> +                return TimeoutPolicy.ControlPlaneHotPath;
1. The CosmosDiagnostics already includes the extensive diagnostics which records each failure and retry. This is already wired through with query diagnostics.
2. This is going to decrease the number of timeouts for query plan. It now fails fast, and has retry logic for the timeout failures. Before it would wait 65 seconds before timing out. Now it will retry .5 sec, 5 sec, 10 seconds to get the query plan which is way faster than the previous waiting of 65 seconds.

2020-10-23 20:19 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClient.cs
> +                return TimeoutPolicy.ControlPlaneHotPath;
If a query plan request takes +10 seconds, isn't that an issue that needs to be investigated anyway?

2020-10-23 20:21 UTC, ealsur approved these changes

2020-10-23 20:21 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
> +                }
Please add Traces when the operation is retried, similar to our Retry Policies, where we log the # of retries and backoff

2020-10-26 08:11 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClient.cs
> +                return TimeoutPolicy.ControlPlaneHotPath;
Can you send an example diagnostics when we hit a timeout from the gateway getting query plan? From there we can determine if it's dead obvious that the gateway failed. Otherwise query is just going to get a bunch of CRIs for timeouts it doesn't own.

2020-10-26 21:00 UTC, bchong95 submitted a review, later dismissed

2020-12-02 19:23 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/GatewayStoreClient.cs
> +            CosmosHttpClient.TimeoutPolicy timeoutPolicy,
nit; readTimeoutPolicy?

2020-12-02 21:03 UTC, j82w commented on Microsoft.Azure.Cosmos/src/GatewayStoreClient.cs
> +            CosmosHttpClient.TimeoutPolicy timeoutPolicy,
These timeout policies can impact writes and reads.

2020-12-02 22:53 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
> +                httpClientHandler.Proxy = webProxy;
WebProxy also throws PlatformNotSupported on WASM, if the user is creating a NETStandard library that they are then sharing on a Web App and WASM app, they could be setting the Proxy on both cases, but only one would apply. With this change, the Web App would apply it and the WASM would throw an exception. Before, both Apps would work, just that the WASM would not apply it due to the limitation on the platform.

2020-12-02 22:56 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
> +                        bool isOutOfRetries = (DateTime.UtcNow - startDateTimeUtc) > TimeSpan.FromSeconds(30) || // Maximum of 30 seconds for all retries
TimeSpan.FromSeconds should be cached as a static?

2020-12-02 22:57 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
> +                        bool isOutOfRetries = (DateTime.UtcNow - startDateTimeUtc) > TimeSpan.FromSeconds(30) || // Maximum of 30 seconds for all retries
Should it be 65 seconds instead of 30?

2020-12-02 22:57 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
> +                            timeoutPosition + 1 >= timeouts.Count; // No more retries are configured
nit: padding?

2020-12-02 22:59 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
> +            IReadOnlyList<TimeSpan> timeouts = timeoutPolicy switch
Is the switch over an enum better than an abstract base class with a Timeouts property/method? Just wondering for consistency's sake where should we choose one over the other in the future

2020-12-02 23:24 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
> +            TimeSpan.FromSeconds(5),
How did you arrive on these timeouts? In Java for query plan (and address refresh) we retry twice without back-off - but only on timeouts. The idea behind it is that these operations don't cause IO in the Gateway
I think doing an exponential back-off after the initial retry without any delay is fine - but I would argue the delay should stop earlier like overall 5 retries with back-offs like 0, 0.5, 1, 2, 4,

2020-12-02 23:25 UTC, j82w commented on Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
> +                        bool isOutOfRetries = (DateTime.UtcNow - startDateTimeUtc) > TimeSpan.FromSeconds(30) || // Maximum of 30 seconds for all retries
The current WebExceptionRetry policy was set to 30 seconds. I don't see an issue with making it 65 seconds.

2020-12-02 23:25 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
> +            TimeSpan.FromSeconds(5),
Never mind - these aren't the back-off but timeouts.

2020-12-02 23:26 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
> +            IReadOnlyList<TimeSpan> timeouts = timeoutPolicy switch
I would also prefer abstract base class approach.

2020-12-02 23:30 UTC, j82w commented on Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
> +            IReadOnlyList<TimeSpan> timeouts = timeoutPolicy switch
The abstract base class is probably the better model. The only reason I went with this model it reduces the number of files and classes being created. It also keeps all the logic isolated in the class. 

@ealsur and @FabianMeiswinkel do you have a preference of one model of the other?

2020-12-02 23:30 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
> +                        bool isOutOfRetries = (DateTime.UtcNow - startDateTimeUtc) > TimeSpan.FromSeconds(30) || // Maximum of 30 seconds for all retries
+1 - I would make the maxTotalTimeout also a property on the abstract base class - for hot path we can be more aggressive - like use something like 30 seconds - but for standrad we need to keep the old one.

2020-12-02 23:31 UTC, FabianMeiswinkel submitted a review, later dismissed
LGTM besides a couple of small comments

2020-12-02 23:33 UTC, j82w commented on Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
> +                httpClientHandler.Proxy = webProxy;
It seems dangerous that we are secretly bypassing the proxy for WASM users. The better model is to throw the exception to the user so they know it's not handled rather than it just ignoring the setting the customer spending a lot of time trying to figure out why the proxy is not getting used.

2020-12-07 21:01 UTC, j82w commented on Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
> +                        bool isOutOfRetries = (DateTime.UtcNow - startDateTimeUtc) > TimeSpan.FromSeconds(30) || // Maximum of 30 seconds for all retries
Please check the latest iteration.

2020-12-15 01:26 UTC, ealsur submitted a review, later dismissed
LGTM, just left some nits in case it makes sense to apply

2020-12-15 01:26 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicyControlPlaneHotPath.cs
> +        public override TimeSpan MaximumRetryTimeLimit => TimeSpan.FromSeconds(65);
nit: This constant can be reused from the `CosmosHttpClientCore.GatewayRequestTimeout` ?

2020-12-15 01:26 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicyControlPlaneRead.cs
> +        public override TimeSpan MaximumRetryTimeLimit => TimeSpan.FromSeconds(65);
Same comment as the other file, to avoid duplicating the same value and to tie all to the same?

2020-12-17 16:58 UTC, ealsur approved these changes

2020-12-17 22:31 UTC, merged