Internal Performance: Adds memory allocation gates to check-ins
Azure/azure-cosmos-dotnet-v3 pull request #1982
Opened 2020-11-03 19:34 UTC by j82w

# Pull Request Template

## Description

This PR ensures that if the memory allocation change by over 1000 bytes that gates will fail and the baseline will need to be updated. This will prevent accidental regressions for allocations.

This PR will not support latency validation as the gates have to much variance in performance to support reliable validation.

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #IssueNumber

2020-11-04 00:02 UTC, bchong95 requested changes

2020-11-04 00:02 UTC, bchong95 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Contracts/PerformanceValidation.cs
> +                double diff = currentResult.Value - baselineResult;
absolute value differences don't make sense when some benchmarks use more memory than others.

2020-11-04 00:57 UTC, j82w commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Contracts/PerformanceValidation.cs
> +                double diff = currentResult.Value - baselineResult;
Changed it to be %5 of the baseline results

2020-11-04 18:33 UTC, ealsur reviewed
Is the expectation that users run it locally in their machine to update the baseline and submit an updated JSON baseline?

2020-11-04 18:33 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Contracts/PerformanceValidation.cs
> +            currentDirectory += @"\Microsoft.Azure.Cosmos\tests\Microsoft.Azure.Cosmos.Performance.Tests\bin\Release\netcoreapp3.1\Contracts\";
If someone runs it locally without Release configuration, would this work? Should we have a compilation IF for the paths?

2020-11-04 18:34 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Contracts/PerformanceValidation.cs
> +                        "If this is by design please update the BenchmarkResults.json file using the CurrentBenchmarkResults.json in the output folder: " + currentBenchmarkResults);
Can we indicate how should the local user run the validation/update on the error message?

2020-11-04 20:28 UTC, j82w commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Contracts/PerformanceValidation.cs
> +            currentDirectory += @"\Microsoft.Azure.Cosmos\tests\Microsoft.Azure.Cosmos.Performance.Tests\bin\Release\netcoreapp3.1\Contracts\";
Fixed

2020-11-04 20:28 UTC, j82w commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Contracts/PerformanceValidation.cs
> +                        "If this is by design please update the BenchmarkResults.json file using the CurrentBenchmarkResults.json in the output folder: " + currentBenchmarkResults);
Please check the latest message

2020-11-04 20:39 UTC, j82w commented
> Is the expectation that users run it locally in their machine to update the baseline and submit an updated JSON baseline?

Yes, they can run it locally on their machine or they can get the output from the test in the gate to update the JSON baseline file. It works the same as the contract validation does.

2020-11-04 21:15 UTC, ealsur approved these changes

2020-11-04 21:21 UTC, kirankumarkolli submitted a review, later dismissed

2020-11-09 22:05 UTC, bchong95 approved these changes

2020-11-10 14:31 UTC, kirankumarkolli approved these changes

2020-11-10 14:33 UTC, kirankumarkolli commented
Unrelated test failure 
![image](https://user-images.githubusercontent.com/6880899/98687500-cf4a9880-238f-11eb-8691-968f17d0df06.png)

2020-11-10 14:33 UTC, merged