Internal Tracing: Adds wire up for ITrace for all feed operations.
Azure/azure-cosmos-dotnet-v3 pull request #1987
Opened 2020-11-07 21:28 UTC by bchong95

# Adds Wire Up For ITrace For All Feed Operations

## Description

Wired up ITrace throughout the stack. 

Sample usage:
```c#
FeedIteratorInternal<CosmosElement> feedIterator = (FeedIteratorInternal<CosmosElement>)container.GetItemQueryIterator<CosmosElement>(
	queryText: query,
	requestOptions: queryRequestOptions);
ITrace trace;
using (trace = Trace.GetRootTrace("Cross Partition Query"))
{
	while (feedIterator.HasMoreResults)
	{
		await feedIterator.ReadNextAsync(trace, default);
	}
}

string traceString = TraceWriter.TraceToText(trace);
```

Sample Output:

```
.
└── Cross Partition Query(f2c7e2c8-ba37-48ae-9a58-74c133fb5781)  Unknown-Component  GetRootTrace@Trace.cs:97  05:55:10:240  324.48 milliseconds  
    ├── Create Query Pipeline(6e6397ae-92a4-478f-b4b4-e7fd9d23c1e5)  Query-Component  TryCreateCoreContextAsync@CosmosQueryExecutionContextFactory.cs:86  05:55:10:275  79.67 milliseconds  
    │   ├── Get Container Properties(85994e95-eee8-44cb-8111-186eeb14d458)  Transport-Component  GetCachedContainerPropertiesAsync@ClientContextCore.cs:339  05:55:10:279  0.08 milliseconds  
    │   ├── Service Interop Query Plan(30d8aec8-72bb-42e1-8f45-b13eb6d99501)  Query-Component  GetQueryPlanWithServiceInteropAsync@QueryPlanRetriever.cs:58  05:55:10:282  47.84 milliseconds  
    │   └── Get Partition Key Ranges(cd6b13e4-fc75-48d5-b703-8f5720369ebd)  Routing-Component  GetTargetPartitionKeyRangesAsync@CosmosQueryClientCore.cs:250  05:55:10:340  4.97 milliseconds  
    ├── MoveNextAsync(d53a72e5-20b5-4d6e-9af4-fb3ebc3f474b)  Pagination-Component  MoveNextAsync@CrossPartitionRangePageAsyncEnumerator.cs:115  05:55:10:368  153.73 milliseconds  
    │   ├── Prefetching(528b083c-d883-4005-9831-1d80293fc122)  Pagination-Component  PrefetchInParallelAsync@ParallelPrefetch.cs:31  05:55:10:381  129.15 milliseconds  
    │   │   ├── Prefetch(4bb0ef70-e4d3-405e-a24c-af507544b694)  Pagination-Component  PrefetchAsync@BufferedPartitionRangePageAsyncEnumerator.cs:54  05:55:10:386  122.94 milliseconds  
    │   │   │   └── [,05C1C9CD673398) move next(d94ba583-3cb2-4ad0-8263-81683950d4ad)  Pagination-Component  MoveNextAsync@PartitionRangePageAsyncEnumerator.cs:54  05:55:10:391  117.37 milliseconds  
    │   │   │       │   (
    │   │   │       │       [Query Metrics]
    │   │   │       │       Retrieved Document Count                 :              10             
    │   │   │       │       Retrieved Document Size                  :           3,602 bytes       
    │   │   │       │       Output Document Count                    :              10             
    │   │   │       │       Output Document Size                     :             168 bytes       
    │   │   │       │       Index Utilization                        :          100.00 %           
    │   │   │       │       Total Query Execution Time               :            0.28 milliseconds
    │   │   │       │         Query Preparation Times
    │   │   │       │           Query Compilation Time               :            0.05 milliseconds
    │   │   │       │           Logical Plan Build Time              :            0.02 milliseconds
    │   │   │       │           Physical Plan Build Time             :            0.02 milliseconds
    │   │   │       │           Query Optimization Time              :            0.00 milliseconds
    │   │   │       │         Index Lookup Time                      :            0.00 milliseconds
    │   │   │       │         Document Load Time                     :            0.05 milliseconds
    │   │   │       │         Runtime Execution Times
    │   │   │       │           Query Engine Times                   :            0.03 milliseconds
    │   │   │       │           System Function Execution Time       :            0.00 milliseconds
    │   │   │       │           User-defined Function Execution Time :            0.00 milliseconds
    │   │   │       │         Document Write Time                    :            0.00 milliseconds
    │   │   │       │   )
    │   │   │       ├── Get Container Properties(eccb2d51-f7d5-49c7-8b2a-8d9298b66200)  Transport-Component  GetCachedContainerPropertiesAsync@ClientContextCore.cs:339  05:55:10:400  0.04 milliseconds  
    │   │   │       ├── Get Overlapping Feed Ranges(4cac09d2-74b0-46e2-8f9e-f2ccf830bfcc)  Routing-Component  GetTargetPartitionKeyRangeByFeedRangeAsync@CosmosQueryClientCore.cs:219  05:55:10:404  0.83 milliseconds  
    │   │   │       │   └── Get Partition Key Ranges(5df1db2a-0411-4e51-b83a-ef0db3d1512c)  Routing-Component  GetTargetPartitionKeyRangesAsync@CosmosQueryClientCore.cs:250  05:55:10:405  0.12 milliseconds  
    │   │   │       ├── Microsoft.Azure.Documents.ServerStoreModel Transport Request(5747013a-7409-4912-8999-f505cdef90bb)  Transport-Component  ProcessMessageAsync@TransportHandler.cs:85  05:55:10:412  16.46 milliseconds  
    │   │   │       │       (
    │   │   │       │           [CosmosClientSideRequestStatistics]
    │   │   │       │           {"Id":"AggregatedClientSideRequestStatistics","ContactedReplicas":[],"RegionsContacted":["https://127.0.0.1:8081/"],"FailedReplicas":[]}
    │   │   │       │       )
    │   │   │       └── Get Cosmos Element Response(bc30879f-97ed-42b7-a4b9-98bd019af7a8)  Json-Component  GetCosmosElementResponse@CosmosQueryClientCore.cs:295  05:55:10:435  70.77 milliseconds  
    <REDACTED>
    │   │   └── Prefetch(e85eaa3b-fac4-4ea8-9674-86244035c0a3)  Pagination-Component  PrefetchAsync@BufferedPartitionRangePageAsyncEnumerator.cs:54  05:55:10:387  122.78 milliseconds  
    │   │       └── [05C1E9CD673398,FF) move next(251d9804-2414-4d94-baf1-f98f7f5b2d91)  Pagination-Component  MoveNextAsync@PartitionRangePageAsyncEnumerator.cs:54  05:55:10:391  117.30 milliseconds  
    │   │           │   (
    │   │           │       [Query Metrics]
    │   │           │       Retrieved Document Count                 :              10             
    │   │           │       Retrieved Document Size                  :           3,622 bytes       
    │   │           │       Output Document Count                    :              10             
    │   │           │       Output Document Size                     :             165 bytes       
    │   │           │       Index Utilization                        :          100.00 %           
    │   │           │       Total Query Execution Time               :            0.26 milliseconds
    │   │           │         Query Preparation Times
    │   │           │           Query Compilation Time               :            0.04 milliseconds
    │   │           │           Logical Plan Build Time              :            0.03 milliseconds
    │   │           │           Physical Plan Build Time             :            0.01 milliseconds
    │   │           │           Query Optimization Time              :            0.00 milliseconds
    │   │           │         Index Lookup Time                      :            0.00 milliseconds
    │   │           │         Document Load Time                     :            0.05 milliseconds
    │   │           │         Runtime Execution Times
    │   │           │           Query Engine Times                   :            0.02 milliseconds
    │   │           │           System Function Execution Time       :            0.00 milliseconds
    │   │           │           User-defined Function Execution Time :            0.00 milliseconds
    │   │           │         Document Write Time                    :            0.00 milliseconds
    │   │           │   )
    │   │           ├── Get Container Properties(e8a42e01-f91d-409e-81d6-dfb84e3f2248)  Transport-Component  GetCachedContainerPropertiesAsync@ClientContextCore.cs:339  05:55:10:400  0.01 milliseconds  
    │   │           ├── Get Overlapping Feed Ranges(1147f0bf-cd5e-4ddf-97f6-9514d357da48)  Routing-Component  GetTargetPartitionKeyRangeByFeedRangeAsync@CosmosQueryClientCore.cs:219  05:55:10:404  0.76 milliseconds  
    │  [...]

2020-11-08 14:08 UTC, j82w requested changes
Blocking until benchmarks results are done.

2020-11-08 14:08 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Handler/RequestMessage.cs
> +            this.Trace = trace ?? throw new ArgumentNullException(nameof(trace));
Why is there both CosmosDiagnosticsContext and ITrace?

2020-11-08 14:08 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Resource/FeedIterators/FeedIteratorInternal{T}.cs
> +        public override Task<FeedResponse<T>> ReadNextAsync(CancellationToken cancellationToken = default)
Please run MockItemBenchmarks before and after this change.

2020-11-09 18:15 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Resource/FeedIterators/FeedIteratorInternal{T}.cs
> +        public override Task<FeedResponse<T>> ReadNextAsync(CancellationToken cancellationToken = default)
The number of nodes in the graph are different. It doesn't make sense to run a benchmark when one it's an apples to oranges comparison.

2020-11-09 18:16 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Handler/RequestMessage.cs
> +            this.Trace = trace ?? throw new ArgumentNullException(nameof(trace));
Leaving CosmosDiagnosticsContext for existing users. Once everyone migrates to ITrace then we can pull the other one out.

2020-11-09 18:18 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Resource/FeedIterators/FeedIteratorInternal{T}.cs
> +        public override Task<FeedResponse<T>> ReadNextAsync(CancellationToken cancellationToken = default)
Also by default we passing in NoOpTrace, so no additional work is being done.

2020-11-09 21:41 UTC, j82w submitted a review, later dismissed

2020-11-10 17:22 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Batch/BatchAsyncContainerExecutor.cs
> +                        trace: NoOpTrace.Singleton,
Can't we add this information to the current Diagnostics format? Or is this something we don't want users to see in the Diagnostics and it has other purposes?

2020-11-10 18:33 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Batch/BatchAsyncContainerExecutor.cs
> +                        trace: NoOpTrace.Singleton,
In the future we will. For now I don't want to break compute who uses visitors to parse out information they need. Once compute migrates to this, then we can flip the switch and do a forced upgrade.

2020-11-11 22:40 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Batch/BatchAsyncContainerExecutor.cs
> +                        trace: NoOpTrace.Singleton,
Ah got it, this ITrace interface is for compute.

2020-11-11 23:38 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Batch/BatchAsyncContainerExecutor.cs
> +                        trace: NoOpTrace.Singleton,
My only concern is, why do we need another tracing interface and why couldn't we improve the current Diagnostics to be compatible with what Compute required instead of rewriting it completely? We had a solution that was already polished and iterated, so I wondered why we needed a totally new thing. 
If the decision was already made, ok, just thought that I'd point that I don't see the why.

2020-11-25 18:51 UTC, sboshra approved these changes

2020-11-25 18:51 UTC, merged