[Preview] Change Feed: Adds change feed retention policy to container configuration
Azure/azure-cosmos-dotnet-v3 pull request #2020
Opened 2020-11-19 19:52 UTC by ealsur

## Description

This PR adds the Change Feed policy retention configuration to a container. Change Feed retention is used in Full Fidelity Change Feed and allows the user to define the time length during which deleted documents will be retained in the Change Feed.

### Creating a Container with change feed retention

```
ContainerProperties containerProperties = new ContainerProperties("myContainer", "/pk");
containerProperties.ChangeFeedPolicy.RetentionDuration = TimeSpan.FromMinutes(5);

CosmosContainerResponse containerCreateResponse = await database.CreateContainerAsync(containerProperties, 5000);
```

With the **Fluent** extensions:

```
string containerName = "myContainer";
string partitionKeyPath = "/pk";

ContainerResponse containerResponse =
    await database.DefineContainer(containerName, partitionKeyPath)
        .WithChangeFeedPolicy()
            .WithRetentionDuration(TimeSpan.FromMinutes(5))
            .Attach()
        .CreateAsync();
```

> Holding on until we get an Emulator update with the support to enable the Emulator tests.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

2020-12-02 21:19 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Resource/Settings/ChangeFeedPolicy.cs
> +        [JsonConverter(typeof(ChangeFeedRetentionConverter))]
To make it easier to read can there just be a private field that just holds the minutes?

2020-12-02 21:19 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Resource/Settings/ChangeFeedPolicy.cs
> +        /// Value is in TimeSpan. Any seconds will be ceiled as 1 minute.
Please throw an argument exception if seconds are used. It will avoid future CRIs if customer sets it to 10 seconds and doesn't read the docs.

2020-12-02 21:19 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Resource/Settings/ContainerProperties.cs
> +                if (this.changeFeedPolicyInternal == null)
Is there any reason to populate this by default? It just seems a little confusing that there is a change feed policy created even though I didn't create one.

2020-12-02 21:19 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Resource/Settings/ContainerProperties.cs
> +            set => this.changeFeedPolicyInternal = value ?? throw new ArgumentNullException($"{nameof(value)}");
Null is a valid value should it be blocked?

2020-12-14 17:46 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Settings/ChangeFeedPolicy.cs
> +        [JsonConverter(typeof(ChangeFeedRetentionConverter))]
Good call, done

2020-12-14 17:46 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Settings/ChangeFeedPolicy.cs
> +        /// Value is in TimeSpan. Any seconds will be ceiled as 1 minute.
Done

2020-12-14 17:47 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Settings/ContainerProperties.cs
> +                if (this.changeFeedPolicyInternal == null)
I also wondered that, but we have that same pattern for the other Policies in the same file.

2020-12-14 17:58 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Settings/ContainerProperties.cs
> +            set => this.changeFeedPolicyInternal = value ?? throw new ArgumentNullException($"{nameof(value)}");
Done

2020-12-16 00:10 UTC, mkolt commented on Microsoft.Azure.Cosmos/src/Resource/Settings/ChangeFeedPolicy.cs
> +                    throw new ArgumentOutOfRangeException(nameof(this.RetentionDuration), "Retention duration's minimum granularity is minutes.");
we should also throw for negative values of TimeSpan.

2020-12-16 00:11 UTC, mkolt commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Fluent/ContainerSettingsTests.cs
> +        [TestMethod]
can we also have a test for backward compat with v2 policy?

2020-12-16 00:19 UTC, mkolt submitted a review, later dismissed

2020-12-16 00:29 UTC, mkolt commented on Microsoft.Azure.Cosmos/src/Fluent/Settings/ChangeFeedPolicyDefinition.cs
> +            if (this.changeFeedPolicyRetention != null)
== null is not possible as TimeSpan is value type (struct). The check doesn't hurt though.

2020-12-17 22:15 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Settings/ChangeFeedPolicy.cs
> +                    throw new ArgumentOutOfRangeException(nameof(this.RetentionDuration), "Retention duration's minimum granularity is minutes.");
Good point

2020-12-17 22:15 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Fluent/ContainerSettingsTests.cs
> +        [TestMethod]
Not sure what this means. Which V2 policy?

2020-12-17 22:18 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Settings/ContainerProperties.cs
> +                if (this.changeFeedPolicyInternal == null)
Following our last meeting, there will be an empty policy by default.

2020-12-17 23:07 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Fluent/Settings/ChangeFeedPolicyDefinition.cs
> +#if PREVIEW
Preview features need to be done in Java first, right?

2020-12-17 23:08 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Fluent/Settings/ChangeFeedPolicyDefinition.cs
> +            this.parent = parent;
null check.

2020-12-17 23:08 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Fluent/Settings/ChangeFeedPolicyDefinition.cs
> +        public ChangeFeedPolicyDefinition WithFullFidelityRetention(TimeSpan retention)
check if it's a negative timespan.

2020-12-17 23:09 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Resource/Settings/ChangeFeedPolicy.cs
> +                if (value.Seconds > 0)
You also need to check for milliseconds.

2020-12-17 23:10 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Resource/Settings/ChangeFeedPolicy.cs
> +                    throw new ArgumentOutOfRangeException(nameof(this.FullFidelityRetention), "Retention's minimum granularity is minutes.");
no need for "minimum", since granularity implies that.

2020-12-17 23:10 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Fluent/Settings/ChangeFeedPolicyDefinition.cs
> +#if PREVIEW
We have customers requiring this on both, so both SDKs will add the preview

2020-12-17 23:12 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Fluent/Settings/ChangeFeedPolicyDefinition.cs
> +        public ChangeFeedPolicyDefinition WithFullFidelityRetention(TimeSpan retention)
Already checked on the TimeSpan setter on the ChangeFeedPolicy that gets called in Attach.

2020-12-17 23:12 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Settings/ChangeFeedPolicy.cs
> +                if (value.Seconds > 0)
Done

2020-12-17 23:13 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Fluent/Settings/ChangeFeedPolicyDefinition.cs
> +            this.parent = parent;
Done

2020-12-17 23:14 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Settings/ChangeFeedPolicy.cs
> +                    throw new ArgumentOutOfRangeException(nameof(this.FullFidelityRetention), "Retention's minimum granularity is minutes.");
Good idea

2021-01-06 17:12 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Fluent/Settings/ChangeFeedPolicyDefinition.cs
> +        public ChangeFeedPolicyDefinition WithFullFidelityRetention(TimeSpan retention)
Should the retention time be part of the constructor? It seems weird to create a ChangeFeedPolicyDefinition

```c#
ContainerResponse containerResponse =
    await database.DefineContainer(containerName, partitionKeyPath)
        .WithChangeFeedPolicy(retentionTime: TimeSpan.FromMinutes(5))
            .Attach()
        .CreateAsync();
```

2021-01-06 17:12 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Resource/Settings/ContainerProperties.cs
> +            set => this.changeFeedPolicyInternal = value;
What happens if an older SDK updates the container? Does it remove the retention time?

2021-01-06 17:13 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Settings/ContainerProperties.cs
> +            set => this.changeFeedPolicyInternal = value;
Yes, this was already discussed during our meetings. Old SDKs do not maintain container schema that do not understand.

2021-01-06 17:15 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Fluent/Settings/ChangeFeedPolicyDefinition.cs
> +        public ChangeFeedPolicyDefinition WithFullFidelityRetention(TimeSpan retention)
My only concern with this approach is if the Change Feed Policy later adds more options. Which ones go to the constructor?

2021-01-06 17:23 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Fluent/Settings/ChangeFeedPolicyDefinition.cs
> +        public ChangeFeedPolicyDefinition WithFullFidelityRetention(TimeSpan retention)
But it makes sense, I will change it

2021-01-06 17:27 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Fluent/Settings/ChangeFeedPolicyDefinition.cs
> +        public ChangeFeedPolicyDefinition WithFullFidelityRetention(TimeSpan retention)
The logic I was thinking is if it is a required value then it should be in the constructor. Optional values can be added later as new methods. It doesn't make since to create a changefeedpolicy if you don't set the retention time. This will help avoid confusion in scenarios where the user doesn't set the value but then expects the default value to be something other than 0.

2021-01-06 17:31 UTC, j82w approved these changes

2021-01-06 21:14 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Fluent/Settings/ChangeFeedPolicyDefinition.cs
> +#if PREVIEW
@bchong95 thanks for it.
Yes public preview is gated on availability in Java.

2021-01-06 21:16 UTC, kirankumarkolli requested changes
Preview gates on JAVA availability

2021-01-06 21:54 UTC, kirankumarkolli approved these changes

2021-01-06 21:54 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Fluent/Settings/ChangeFeedPolicyDefinition.cs
> +#if PREVIEW
PR no longer exposes it as preview

2021-01-06 22:43 UTC, merged

2023-01-20 10:15 UTC, fazil1987 commented
@ealsur,

 ChangefeedPolicy is marked as a private field in ContainerProperties class, so not sure how I can use like its suggested here. The library we are using is Microsoft.Azure.Cosmos - Version 3.31.2.  

Any help would be appreciated.

2023-01-20 14:31 UTC, ealsur commented
@fazil1987 This is related to the Full Fidelity feature, and it is currently in public preview. GA of SDK APIs aligns with GA of the service feature, when the service feature announces GA, then so will the SDKs. I don't have any specific dates that I am aware of and can share.

2023-01-23 09:22 UTC, fazil1987 commented
Thanks for the info @ealsur. Just want to know, is this feature stable and reliable enough to use it in production given this is been there for a year? Also would like to know what's stopping this feature from getting into GA given PR was merged a year ago? Is it overlooked?

2023-01-23 15:26 UTC, ealsur commented
@fazil1987 Features like this are driven by the service, not the client SDKs. Client SDKs just implement the APIs that customers can call to access these features, hence, the reason for a particular feature to be still in preview or when it will GA is directly defined by the service feature (the SDK will just move these APIs to the GA package once GA is achieved). How long until this feature is GA or if the feature is reliable to be used in production is not something that can be addressed in this repository because it is not directly related to the code here. I would not advise using any preview feature in production until the team explicitly states otherwise. 
I would think that once the feature is ready, it will be [announced](https://azure.microsoft.com/en-us/updates/?category=databases&query=Azure%20Cosmos%20DB) through the public channels.