Client Side Encryption : Adds Support for Managing Client Encryption Keys as a resource.
Azure/azure-cosmos-dotnet-v3 pull request #2048
Opened 2020-12-08 06:07 UTC by kr-santosh

## Description

This PR takes forward the Public Model of Client Side Data Encryption and is in conjunction with Anuj's PR [https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2019] and focuses on managing Client Encryption Keys via Create/Replace as a resource and as part of a database and retrieve the same via  ClientEncryptionKeyResponse as ClientEncryptionKeyProperties.

## Type of change

- [] New feature (non-breaking change which adds functionality)
- [] This change requires a documentation update

2020-12-08 11:35 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs
> +            ClientEncryptionKey GetClientEncryptionKey(string id)
Why is this being added the SDK? This should only be added to then encryption SDK.

2020-12-08 11:39 UTC, j82w requested changes

2020-12-08 11:39 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs
> +        public abstract ClientEncryptionKey GetClientEncryptionKey(string id);
Anything modifying the public SDK needs to go through a design review first. This way Java and other SDKs can give feedback. 

This can be added as extension methods in the encryption SDK. No reason to expose encryption logic on the public SDK.

2020-12-09 04:43 UTC, kr-santosh commented on Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs
> +        public abstract ClientEncryptionKey GetClientEncryptionKey(string id);
Jake, I thought this was agreed upon model which was discussed over in the Public Model Design meeting few weeks back.
@abhijitpai  @kirankumarkolli 

Do let me know you if there are reservations around this approach.

2021-01-05 11:49 UTC, abhijitpai commented on Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs
> +        public abstract Task<ClientEncryptionKeyResponse> ReplaceClientEncryptionKeyAsync(
>ryp [](start = 74, length = 3)

Shouldn't ReplaceAsync be on ClientEncryptionKey?

2021-01-05 11:54 UTC, abhijitpai commented on Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs
> +        public abstract FeedIterator<ClientEncryptionKeyProperties> GetClientEncryptionKeyIterator(
>yIt [](start = 89, length = 3)

Do we need to end this with QueryIterator instead of Iterator for consistency?

2021-01-05 12:51 UTC, abhijitpai commented on Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs
> +            ClientEncryptionKey clientEncryptionKey,
>Key clie [](start = 28, length = 8)

Create shouldn't take the CEK.

2021-01-06 11:56 UTC, kr-santosh commented on Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs
> +        public abstract Task<ClientEncryptionKeyResponse> ReplaceClientEncryptionKeyAsync(
Yes, introduced ReplaceAsync on CEK instead.

2021-01-06 11:56 UTC, kr-santosh commented on Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs
> +            ClientEncryptionKey clientEncryptionKey,
Removed cek parameter.

2021-01-11 05:26 UTC, abhijitpai commented on Microsoft.Azure.Cosmos/src/Resource/ClientEncryptionKey/ClientEncryptionKey.cs
> +        /// Replace a <see cref="ClientEncryptionKeyProperties"/> from the Azure Cosmos service as an asynchronous operation.
I think we should instead document this to not directly be called.

2021-01-11 05:26 UTC, abhijitpai commented on Microsoft.Azure.Cosmos/src/Resource/ClientEncryptionKey/ClientEncryptionKey.cs
> +    /// </summary>
nit: Remove the word backend, and database doesn't have replace for CEK/DEK.

2021-01-11 05:35 UTC, abhijitpai commented on Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs
> +        /// This should be invoked from the Encryption package.
This method is not meant to be invoked directly. Please see https://aka.ms/CosmosClientEncryption in order to use client-side encryption.

2021-01-11 06:02 UTC, kr-santosh commented on Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs
> +        /// This should be invoked from the Encryption package.
Fixed.

2021-01-11 06:03 UTC, kr-santosh commented on Microsoft.Azure.Cosmos/src/Resource/ClientEncryptionKey/ClientEncryptionKey.cs
> +    /// </summary>
Fixed

2021-01-11 07:01 UTC, abhijitpai submitted a review, later dismissed

2021-01-11 13:47 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos/src/Resource/ClientEncryptionKey/ClientEncryptionKey.cs
> +        /// ClientEncryptionKeyResponse response = await user.ReplaceClientEncryptionKeyAsync(clientEncryptionKeyProperties);
Please fix comment

2021-01-11 13:57 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos/src/Resource/ClientEncryptionKey/ClientEncryptionKeyProperties.cs
> +            this.EncryptionAlgorithmId = encryptionAlgorithm;
Add null check? Also, do we need the Id suffix?

2021-01-11 14:01 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos/src/Resource/ClientEncryptionKey/ClientEncryptionKeyResponse.cs
> +        public virtual ClientEncryptionKey DataEncryptionKey { get; }
Rename to ClientEncryptionKey?

2021-01-11 14:06 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos/src/Resource/CosmosResponseFactoryCore.cs
> +                ClientEncryptionKeyProperties dekProperties = this.ToObjectpublic<ClientEncryptionKeyProperties>(cosmosResponseMessage);
cekProperties instead of dekProperties?

2021-01-11 14:08 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs
> +        internal FeedIterator GetClientEncryptionKeyQueryStreamIterator(
Should it be private?

2021-01-11 14:10 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs
> +            ClientEncryptionKeyResponse dekResponse = this.ClientContext.ResponseFactory.CreateClientEncryptionKeyResponse(
cekResponse instead of dekResponse.

2021-01-11 14:12 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs
> +        private string GetResourceUriForReplaceClientEncryptionKey(string id)
Can be removed now.

2021-01-11 14:15 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs
> +        internal FeedIterator GetClientEncryptionKeyQueryStreamIterator(
private?

2021-01-11 14:24 UTC, kr-santosh commented on Microsoft.Azure.Cosmos/src/Resource/ClientEncryptionKey/ClientEncryptionKeyProperties.cs
> +            this.EncryptionAlgorithmId = encryptionAlgorithm;
do we need to force this?

2021-01-11 14:58 UTC, kr-santosh commented on Microsoft.Azure.Cosmos/src/Resource/ClientEncryptionKey/ClientEncryptionKey.cs
> +        /// ClientEncryptionKeyResponse response = await user.ReplaceClientEncryptionKeyAsync(clientEncryptionKeyProperties);
Fixed.

2021-01-11 14:58 UTC, kr-santosh commented on Microsoft.Azure.Cosmos/src/Resource/ClientEncryptionKey/ClientEncryptionKeyResponse.cs
> +        public virtual ClientEncryptionKey DataEncryptionKey { get; }
Done

2021-01-11 14:58 UTC, kr-santosh commented on Microsoft.Azure.Cosmos/src/Resource/CosmosResponseFactoryCore.cs
> +                ClientEncryptionKeyProperties dekProperties = this.ToObjectpublic<ClientEncryptionKeyProperties>(cosmosResponseMessage);
Fixed

2021-01-11 14:58 UTC, kr-santosh commented on Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs
> +            ClientEncryptionKeyResponse dekResponse = this.ClientContext.ResponseFactory.CreateClientEncryptionKeyResponse(
Fixed.

2021-01-11 14:58 UTC, kr-santosh commented on Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs
> +        private string GetResourceUriForReplaceClientEncryptionKey(string id)
yes, missed it.

2021-01-11 14:59 UTC, kr-santosh commented on Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs
> +        internal FeedIterator GetClientEncryptionKeyQueryStreamIterator(
yup. Helper func

2021-01-12 05:08 UTC, kr-santosh commented on Microsoft.Azure.Cosmos/src/Resource/ClientEncryptionKey/ClientEncryptionKeyProperties.cs
> +            this.EncryptionAlgorithmId = encryptionAlgorithm;
Fixed.

2021-01-12 05:31 UTC, anujtoshniwal submitted a review, later dismissed

2021-01-12 05:39 UTC, abhijitpai commented on Microsoft.Azure.Cosmos/src/Resource/ClientEncryptionKey/ClientEncryptionKey.cs
>          /// <![CDATA[
Remove the example.

2021-01-12 06:08 UTC, kr-santosh commented on Microsoft.Azure.Cosmos/src/Resource/ClientEncryptionKey/ClientEncryptionKey.cs
>          /// <![CDATA[
Fixed.

2021-01-12 06:18 UTC, abhijitpai submitted a review, later dismissed

2021-01-12 07:08 UTC, anujtoshniwal submitted a review, later dismissed

2021-01-12 10:56 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/ClientEncryptionKey/ClientEncryptionKey.cs
> +        abstract class ClientEncryptionKey
Its not a raw key right? 
On naming can it be updated to reflect the same?

2021-01-12 10:57 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/ClientEncryptionKey/ClientEncryptionKey.cs
> +        abstract class ClientEncryptionKey
Also do implemenation fail in-case raw key is provided (is it possible)?

2021-01-12 10:59 UTC, kirankumarkolli submitted a review, later dismissed
LGTM. Please also run it through with @j82w

2021-01-12 11:05 UTC, kr-santosh commented on Microsoft.Azure.Cosmos/src/Resource/ClientEncryptionKey/ClientEncryptionKey.cs
> +        abstract class ClientEncryptionKey
No its not a raw/Plain , this will managed by Encryption Package using AAP API to generate and wrap the key and passed as part of ClientEncryptionKeyProperties via CreateClientEncryptionKeyAsync

2021-01-12 15:44 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs
> +                CancellationToken cancellationToken = default)
Please follow the other methods and pass the CosmosDiagnostics into the method.

2021-01-12 16:39 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Resource/ClientEncryptionKey/ClientEncryptionKeyInlineCore.cs
> +    internal sealed class ClientEncryptionKeyInlineCore : ClientEncryptionKeyCore
Please add sample of the public use cases to the PR description.

2021-01-13 07:04 UTC, kr-santosh commented on Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs
> +                CancellationToken cancellationToken = default)
Fixed.

2021-01-13 07:06 UTC, kr-santosh commented on Microsoft.Azure.Cosmos/src/Resource/ClientEncryptionKey/ClientEncryptionKeyInlineCore.cs
> +    internal sealed class ClientEncryptionKeyInlineCore : ClientEncryptionKeyCore
The public use cases will be updated in the Encryption Package PR as these APIs will be exposed via Encryption Package.

2021-01-13 12:56 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Resource/ClientEncryptionKey/ClientEncryptionKeyInlineCore.cs
> +    internal sealed class ClientEncryptionKeyInlineCore : ClientEncryptionKeyCore
All the APIs that are labeled `#if  PREVIEW` are accessible via the Preview SDK.  The description should include samples of what those APIs will look like for users.

2021-01-14 05:09 UTC, kr-santosh commented on Microsoft.Azure.Cosmos/src/Resource/ClientEncryptionKey/ClientEncryptionKeyInlineCore.cs
> +    internal sealed class ClientEncryptionKeyInlineCore : ClientEncryptionKeyCore
Sure.

2021-01-19 13:11 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs
> +        public abstract FeedIterator<ClientEncryptionKeyProperties> GetClientEncryptionKeyQueryIterator(
In the future this should be put into it's own resource like Scripts to avoid polluting the Database object.

2021-01-19 13:11 UTC, abhijitpai approved these changes

2021-01-19 14:17 UTC, abhijitpai approved these changes

2021-01-19 14:58 UTC, j82w approved these changes

2021-01-19 14:58 UTC, merged