New feature - Add way to get UTF-8 string that isn't buffered.
Azure/azure-cosmos-dotnet-v3 pull request #2053
Opened 2020-12-10 01:03 UTC by jasontho-ms

# Pull Request Template

## Description

We can get the buffered UTF-8 string - this gets the unbuffered UTF-8 string.

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #IssueNumber

2020-12-10 01:11 UTC, bchong95 requested changes
Please incorporate the trick to avoid allocating a buffer.

2020-12-10 01:11 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Json/JsonReader.JsonTextReader.cs
> +                return Utf8Memory.UnsafeCreateNoValidation(Encoding.UTF8.GetBytes(this.GetStringValue()));
You can do the same trick for buffered string values here to avoid the allocation.

2020-12-10 03:36 UTC, jasontho-ms commented on Microsoft.Azure.Cosmos/src/Json/JsonReader.JsonTextReader.cs
> +                return Utf8Memory.UnsafeCreateNoValidation(Encoding.UTF8.GetBytes(this.GetStringValue()));
Done

2020-12-10 17:23 UTC, sboshra approved these changes

2020-12-10 17:46 UTC, invino4 requested changes

2020-12-10 17:46 UTC, invino4 commented on Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.Strings.cs
> +                return Utf8String.UnsafeFromUtf8BytesNoValidation(bufferedStringValue.Memory);
This seems like an unsafe operation.  This unsafe constructor can only be called if the buffer passed can be exclusive ownership transferred.  That seems almost certainly not true here.  Is it true?  Where did the underlying memory for the buffer come from and who has a reference/alias to it?

2020-12-10 17:46 UTC, invino4 commented on Microsoft.Azure.Cosmos/src/Json/JsonReader.JsonTextReader.cs
> +                    return Utf8String.UnsafeFromUtf8BytesNoValidation(memory.Memory);
same here.

2020-12-10 20:50 UTC, fnarenji commented on Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.Strings.cs
> +                return Utf8String.UnsafeFromUtf8BytesNoValidation(bufferedStringValue.Memory);
Replaced it with Utf8Span

2020-12-10 20:51 UTC, fnarenji commented on Microsoft.Azure.Cosmos/src/Json/JsonReader.JsonTextReader.cs
> +                    return Utf8String.UnsafeFromUtf8BytesNoValidation(memory.Memory);
Replaced it with Utf8Span

2020-12-10 20:53 UTC, bchong95 approved these changes

2020-12-10 20:54 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.Strings.cs
> +                return Utf8String.UnsafeFromUtf8BytesNoValidation(bufferedStringValue.Memory);
@invino4  and I discussed this offline. It's okay to use Utf8String in this case, because neither there reader nor the Utf8String will be writing to the buffer, so it's okay that both have access to it (interning of immutable types).

2020-12-11 01:34 UTC, fnarenji commented on Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.Strings.cs
> -        public static bool TryGetBufferedStringValue(
Moved this at the top with the other public ones.

2020-12-11 01:38 UTC, bchong95 approved these changes

2020-12-11 01:44 UTC, invino4 approved these changes

2020-12-11 02:50 UTC, sboshra approved these changes

2020-12-11 02:50 UTC, merged