unseal IncludedPath so it could be extended by compute
Azure/azure-cosmos-dotnet-v3 pull request #2059
Opened 2020-12-10 19:46 UTC by PaulCheng

Make IncludedPath.cs unsealed for internal use

- [] Bug fix (non-breaking change which fixes an issue)

2020-12-10 19:50 UTC, j82w approved these changes

2020-12-10 20:38 UTC, ealsur approved these changes

2020-12-10 20:38 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Settings/IncludedPath.cs
> +    public class IncludedPath
nit: maybe it's easier to have it always public and add the sealed conditionally, for example:
```
public
#if !INTERNAL
sealed
#endif
class IncludedPath
```

2020-12-11 00:46 UTC, bchong95 requested changes
What is the need for extending this class? Why can't we use composition instead and create a wrapper class?

2020-12-11 13:31 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Resource/Settings/IncludedPath.cs
> +#endif
> What is the need for extending this class? Why can't we use composition instead and create a wrapper class?
1. That would require duplicating and maintaining copies of ContainerProperties, IndexingPolicy, and IncludedPath to add a single property to the Include path.
2. Using composition would prevent the use of the existing Container interfaces. This would require exposing a new API to take this custom object. 

In the future please don't leave comments that can't be directly responded.

2020-12-11 19:01 UTC, bchong95 submitted a review, later dismissed

2020-12-11 19:12 UTC, kirankumarkolli approved these changes

2020-12-14 01:29 UTC, merged