Conditional patch introduction
Azure/azure-cosmos-dotnet-v3 pull request #2138
Opened 2021-01-21 16:24 UTC by deparash

# Pull Request Template

## Description

This PR Introduces the Conditional Patch variant to the general Patch.
This is done via a introduction of new type of request options.

## Type of change

Please delete options that are not relevant.

- [] New feature (non-breaking change which adds functionality)

## Closing issues
977613
1016952

2021-01-21 17:14 UTC, j82w commented on Microsoft.Azure.Cosmos/src/RequestOptions/PatchRequestOptions.cs
> +    public class PatchRequestOptions : ItemRequestOptions
Please add 

```
#if INTERNAL
    public
#else
    internal
#endif
```

2021-01-21 17:14 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Patch/PatchOperationsJsonConverter.cs
> +            PatchSpec patchSpec = (PatchSpec)value;
I don't see anything requiring this to be a PatchSpec. Won't this cause a runtime exception?

2021-01-21 17:14 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Patch/PatchSpec.cs
> +        //[JsonProperty(PropertyName = PatchConstants.PatchSpecAttributes.Condition)]
Nit: remove if it is not necessary

2021-01-21 17:14 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Patch/PatchSpec.cs
> +            this.PatchOperations = patchOperations;
Null check patch operations

2021-01-21 17:14 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Patch/PatchSpec.cs
> +        public IReadOnlyList<PatchOperation> PatchOperations { get; set; }
Can this be made as readonly?

2021-01-21 17:14 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Patch/PatchSpec.cs
> +        public string Condition { get; }
Please add documentation and samples on how to use Condition.

2021-01-22 07:37 UTC, deparash commented on Microsoft.Azure.Cosmos/src/Patch/PatchOperationsJsonConverter.cs
> +            PatchSpec patchSpec = (PatchSpec)value;
I guess no its fine. we are using it below.

2021-01-22 16:14 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/RequestOptions/PatchRequestOptions.cs
> +        public string Condition { get; set; }
>Condition [](start = 22, length = 9)

Condition as name is very generic. 

Suggestion on name? 
    - DocumentCondition
    - DocumentQueryCondition

2021-01-22 16:15 UTC, kirankumarkolli submitted a review, later dismissed
Please check comments

2021-01-22 19:54 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Patch/PatchOperationsJsonConverter.cs
> +            IReadOnlyList<PatchOperation> patchOperations = (IReadOnlyList<PatchOperation>)patchSpec.PatchOperations;
This downcast is bad. please go through the PatchOperations interface or rework it.

2021-01-22 19:54 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Patch/PatchOperationsJsonConverter.cs
> +            if (!string.IsNullOrWhiteSpace(patchSpec.PatchRequestOptions.Condition))
avoid using null or whitespace. use == null instead, so that we can differentiate between null strings and empty strings.

2021-01-22 19:54 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Patch/PatchSpec.cs
> +        class PatchSpec
sealed unless you have inheritance plans for it later.

2021-01-22 19:54 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Patch/PatchSpec.cs
> +            }
nit new line. 

Additionally you can use the new syntax for throwing exceptions:

```
this.PatchOperations = patchOperations ?? throw new ArgumentNullException() ;
```

2021-01-22 19:54 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Patch/PatchSpec.cs
> +            this.PatchOperations = patchOperations;
You need to make a deep copy of the list, since it's not immutable. The caller could later add to the patch operations and that would change the state of this class.

2021-01-22 19:54 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Patch/PatchSpec.cs
> +        class PatchSpec
This class only has two references. It's a good candidate to be a struct instead of a class.

2021-01-22 19:54 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/RequestOptions/PatchRequestOptions.cs
> +        public string Condition { get; set; }
`FilterPredicate` is what I would go for.

2021-01-25 09:03 UTC, deparash commented on Microsoft.Azure.Cosmos/src/Patch/PatchOperationsJsonConverter.cs
> +            IReadOnlyList<PatchOperation> patchOperations = (IReadOnlyList<PatchOperation>)patchSpec.PatchOperations;
not downcasting. its already of same type.

2021-01-25 09:03 UTC, deparash commented on Microsoft.Azure.Cosmos/src/Patch/PatchOperationsJsonConverter.cs
> +            if (!string.IsNullOrWhiteSpace(patchSpec.PatchRequestOptions.Condition))
not required here to differentiate

2021-01-29 08:25 UTC, abhijitpai commented on Microsoft.Azure.Cosmos/src/Patch/PatchOperationsJsonConverter.cs
> +            //PatchSpec patchSpec = (PatchSpec)value;
> //PatchSpe [](start = 11, length = 11)

Remove

2021-01-29 08:30 UTC, abhijitpai commented on Microsoft.Azure.Cosmos/src/Patch/PatchSpec.cs
> +        struct PatchSpec
>struct [](start = 8, length = 6)

[https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/choosing-between-class-and-struct](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/choosing-between-class-and-struct)

2021-01-29 08:33 UTC, abhijitpai commented on Microsoft.Azure.Cosmos/src/Patch/PatchSpec.cs
> +
Must always be internal

2021-01-29 08:39 UTC, abhijitpai commented on Microsoft.Azure.Cosmos/src/Patch/PatchOperationsJsonConverter.cs
> +            IReadOnlyList<PatchOperation> patchOperations = (IReadOnlyList<PatchOperation>)patchSpec.PatchOperations;
>(IReadOnlyList<PatchOperation>)p [](start = 60, length = 32)

It's already this, unnecessary cast

2021-01-29 08:41 UTC, abhijitpai commented on Microsoft.Azure.Cosmos/src/RequestOptions/PatchRequestOptions.cs
> +    /// Cosmos item request options
>ons [](start = 32, length = 3)

update

2021-01-29 08:41 UTC, abhijitpai commented on Microsoft.Azure.Cosmos/src/RequestOptions/PatchRequestOptions.cs
> +        /// condition only sql statement.
>// cond [](start = 9, length = 7)

Our documentation gets generated out of this. Please make sure to use proper casing, full stops etc.

2021-01-29 08:43 UTC, abhijitpai approved these changes
:shipit:

2021-01-29 10:48 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos/src/Patch/PatchOperationsJsonConverter.cs
> +                throw new ArgumentOutOfRangeException("Value Argument is not PatchSpec.");
nit: "nameof(value) should be of type PatchSpec."

2021-01-29 10:56 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos/src/RequestOptions/PatchRequestOptions.cs
> +
nit: extra line

2021-01-29 10:57 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos/src/RequestOptions/PatchRequestOptions.cs
> +    class PatchRequestOptions : ItemRequestOptions
sealed?

2021-01-29 10:58 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos/src/RequestOptions/PatchRequestOptions.cs
> +        /// condition only sql statement.
Also, can you please add sample?

2021-01-29 10:59 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +            PatchRequestOptions requestOptions = null,
Should this be ItemRequestOptions for consistency with the other APIs? You can then cast to PatchRequestOptions?

2021-01-29 11:01 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosSerializerCore.cs
> +                cosmosSerializer: this.customSerializer ?? new CosmosJsonDotNetSerializer(),
nit: indentation

2021-01-29 11:02 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContentResponseTests.cs
> +                EnableContentResponseOnWrite = false
Verify this in the test?

2021-01-29 11:02 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
> +                FilterPredicate = "from root where root.x = 3"
Validate?

2021-01-29 11:02 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
> +
nit: extra line

2021-01-29 11:03 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
> +            List<PatchOperation> patchOperationsUpdateNumTask12 = new List<PatchOperation>()
patchOperationsUpdateTaskNum12

2021-01-29 11:04 UTC, anujtoshniwal commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
> +            List<PatchOperation> patchOperationsUpdateNumTask14 = new List<PatchOperation>()
patchOperationsUpdateTaskNum14?

2021-01-29 13:20 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Patch/PatchOperationsJsonConverter.cs
> +                throw new ArgumentOutOfRangeException("Value Argument is not PatchSpec.");
Enrich the exception message to include the value type.

2021-01-29 13:22 UTC, kirankumarkolli approved these changes

2021-01-29 13:25 UTC, deparash commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +            PatchRequestOptions requestOptions = null,
I guess this is ok? we want to expose patchrequestoptions.

2021-01-29 13:27 UTC, deparash commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
> +                FilterPredicate = "from root where root.x = 3"
yes validated.

2021-01-29 13:31 UTC, deparash commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContentResponseTests.cs
> +                EnableContentResponseOnWrite = false
its getting validated below.

2021-01-29 14:17 UTC, rakkuma commented on Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchInternal.cs
> +    internal abstract class TransactionalBatchInternal : TransactionalBatch
Not needed?

2021-01-29 17:40 UTC, akhetarp approved these changes

2021-01-29 17:54 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Patch/PatchOperationsJsonConverter.cs
> +            }
Else case and throw an invalid operation exception?

2021-01-29 17:54 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Patch/PatchSpec.cs
> +    internal struct PatchSpec
`readonly struct`

Since the type is fully immutable.

2021-01-29 17:56 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Patch/PatchSpec.cs
> +            PatchRequestOptions patchRequestOptions = null)
Instead of taking either a PatchRequestOptions or a TransactionalBatchPatchRequestOptions consider creating an interface that both implement and store that instead. That way you can avoid the nullability. Or you can use `Either<PatchRequestOptions, TransactionalBatchPatchRequestOptions>`.

2021-01-29 17:56 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Patch/PatchSpec.cs
> +            this.PatchOperations = patchOperations ?? throw new ArgumentNullException(nameof(patchOperations));
This needs to be a deep copy otherwise any changes in state will reflect here.

2021-01-29 17:57 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/RequestOptions/PatchRequestOptions.cs
> +    public string FilterPredicate { get; set; }
nit: indent.

2021-01-29 17:57 UTC, bchong95 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
> +        [Ignore]
Should these tests be ignored?

2021-02-01 04:11 UTC, deparash commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
> +        [Ignore]
Yes Backend Emulator is not updated.

2021-02-01 05:44 UTC, abhijitpai commented on Microsoft.Azure.Cosmos/src/Batch/BatchCore.cs
> +                TransactionalBatchPatchRequestOptions requestOptions = null)
Please put Item within this class name - for eg. we have a TransactionalBatchRequestOptions for batch-wide options

2021-02-01 05:45 UTC, abhijitpai commented on Microsoft.Azure.Cosmos/src/RequestOptions/PatchRequestOptions.cs
> +    sealed class PatchRequestOptions : ItemRequestOptions
Again, good to have Item in this name

2021-02-01 06:51 UTC, rakkuma commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +            PatchRequestOptions requestOptions = null,
PatchItemRequestOptions?

2021-02-01 06:54 UTC, rakkuma commented on Microsoft.Azure.Cosmos/src/Patch/PatchSpec.cs
> +    using Microsoft.Azure.Cosmos.Query.Core.Monads;
Is this used?

2021-02-01 06:56 UTC, rakkuma commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
> +                Assert.AreEqual(HttpStatusCode.OK, response.StatusCode);
Verify the documents too.

2021-02-01 06:58 UTC, rakkuma commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
> +                Assert.AreEqual(HttpStatusCode.OK, response.StatusCode);
Why not validate the response here rather than reading again?

2021-02-01 07:01 UTC, rakkuma commented on Microsoft.Azure.Cosmos/src/Patch/PatchSpec.cs
> +                List<PatchOperation> patchOperationsClone = new List<PatchOperation>(patchOperations.Count);
Why clone? Is it needed?

2021-02-01 08:23 UTC, deparash commented on Microsoft.Azure.Cosmos/src/Patch/PatchSpec.cs
> +                List<PatchOperation> patchOperationsClone = new List<PatchOperation>(patchOperations.Count);
we need to do a deep copy.

2021-02-01 08:24 UTC, deparash commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
> +                Assert.AreEqual(HttpStatusCode.OK, response.StatusCode);
I wanted to check the status after the commit.

2021-02-01 08:57 UTC, rakkuma commented on Microsoft.Azure.Cosmos/src/Patch/PatchSpec.cs
> +                List<PatchOperation> patchOperationsClone = new List<PatchOperation>(patchOperations.Count);
But why? Any reason behind it to consume extra memory?

2021-02-01 08:57 UTC, rakkuma commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
> +                Assert.AreEqual(HttpStatusCode.OK, response.StatusCode);
But response will come after commit right?

2021-02-01 09:02 UTC, deparash commented on Microsoft.Azure.Cosmos/src/Patch/PatchSpec.cs
> +    using Microsoft.Azure.Cosmos.Query.Core.Monads;
yes. in Either<>

2021-02-01 09:03 UTC, deparash commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
> +                Assert.AreEqual(HttpStatusCode.OK, response.StatusCode);
yes will do it collectively.

2021-02-01 09:12 UTC, deparash commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
> +                Assert.AreEqual(HttpStatusCode.OK, response.StatusCode);
k Will update in future iteration.
Also by reading the doc later its a assurance that document is not getting updated in wrong format or something. even while reading as in future there might be a blind patch variant.
So I guess its ok to get it this way also.

2021-02-01 18:10 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Patch/PatchSpec.cs
> +            if (patchOperations != null)
You can avoid the nesting here by throwing the ArgumentNullException first:

if(patchOperations == null)
{
    throw ... 
}

// Do the copy here.

2021-02-01 18:10 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Patch/PatchSpec.cs
> +                this.PatchOperations = (IReadOnlyList<PatchOperation>)patchOperationsClone;
no need to for the explicit cast.

2021-02-01 18:41 UTC, bchong95 submitted a review, later dismissed

2021-02-02 05:08 UTC, deparash commented on Microsoft.Azure.Cosmos/src/Patch/PatchSpec.cs
> +                this.PatchOperations = (IReadOnlyList<PatchOperation>)patchOperationsClone;
we need it as casting from list to read only list.

2021-02-02 08:19 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchPatchItemRequestOptions.cs
> +        /// Creates a conditional SQL argument which is of format "FROM X where CONDITION",
NIT: (from-clause)

2021-02-02 08:19 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchPatchItemRequestOptions.cs
> +        /// the condition has to be withing the scope of the document which is supposed to be patched in the particular request.
typo - within

2021-02-02 08:20 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Patch/PatchOperationsJsonConverter.cs
> +                            if (!string.IsNullOrWhiteSpace(patchRequestOptions.FilterPredicate))
NIT: String vs. string for all static method invocations

2021-02-02 08:22 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/RequestOptions/PatchItemRequestOptions.cs
> +        /// Condition can only be a sql statement.
from-clause of a sql statement

2021-02-02 08:23 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/RequestOptions/PatchItemRequestOptions.cs
> +        /// the condition has to be withing the scope of the document which is supposed to be patched in the particular request.
typo - within

2021-02-02 08:23 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/RequestOptions/PatchItemRequestOptions.cs
> +        /// If the condition is satisfied the patch transaction will take place otherwise it will be retured with precondition failed.
typo returned

2021-02-02 08:24 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchPatchItemRequestOptions.cs
> +        /// If the condition is satisfied the patch transaction will take place otherwise it will be retured with precondition failed.
typo returned

2021-02-02 08:27 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosSerializerCore.cs
> +                return PatchOperationsJsonConverter.CreatePatchOperationsSerializer(
why don't you keep a reference to the newly created serializer and reuse that for the next call to GetSerializer<PatchSpec>()

2021-02-02 08:28 UTC, FabianMeiswinkel requested changes
Looks good overall - couple of NITs and one ask in GetSerializer<T>

2021-02-02 11:30 UTC, FabianMeiswinkel approved these changes
LGTM - thanks!

2021-02-02 14:34 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Patch/PatchSpec.cs
> +        public Either<PatchItemRequestOptions, TransactionalBatchPatchItemRequestOptions> RequestOptions { get; }
Is there any reason this can't just be the string of the FilterPredicate? I don't see a reason for needing the entire RequestOptions.

2021-02-02 14:34 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosSerializerCore.cs
> +            if (inputType == typeof(PatchSpec))
Can this not follow the same model as SqlQuerySpec?

2021-02-02 15:10 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosSerializerCore.cs
> +            if (inputType == typeof(PatchSpec))
No - it can't - the Json COnverter is required here - so even if no customSerializer is specified it needs to be applied.

2021-02-02 15:24 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchPatchItemRequestOptions.cs
> +        /// the condition has to be within the scope of the document which is supposed to be patched in the particular request.
Please call out what's error code in-case if its not.

2021-02-02 15:25 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchPatchItemRequestOptions.cs
> +        /// If the condition is satisfied the patch transaction will take place otherwise it will be returned with precondition failed.
Please expand on 'satisfied' part. I.e. what does the query need to evaluate to?

2021-02-02 15:26 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Patch/PatchSpec.cs
> +        public Either<PatchItemRequestOptions, TransactionalBatchPatchItemRequestOptions> RequestOptions { get; }
Or what's the future expected usage of the options?

2021-02-02 15:27 UTC, kirankumarkolli submitted a review, later dismissed

2021-02-02 16:54 UTC, deparash commented on Microsoft.Azure.Cosmos/src/Patch/PatchSpec.cs
> +        public Either<PatchItemRequestOptions, TransactionalBatchPatchItemRequestOptions> RequestOptions { get; }
there will be multiple such parameters that will be associated with patch.
such a set on create or sometime in future blind patch etc.
also these request items can also be combined with other base class items.

2021-02-02 16:59 UTC, deparash commented on Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchPatchItemRequestOptions.cs
> +        /// the condition has to be within the scope of the document which is supposed to be patched in the particular request.
its specified in line below.

2021-02-03 11:47 UTC, FabianMeiswinkel approved these changes
LGTM

2021-02-03 11:47 UTC, merged