Internal Pagination: Fixes APIs to be cleaner.
Azure/azure-cosmos-dotnet-v3 pull request #2144
Opened 2021-01-22 02:35 UTC by bchong95

# Internal Pagination: Fixes APIs to be cleaner.

## Description

This PR cleans up the pagination API by creating `PaginationOptions`, which groups together all the static options for a particular FeedOperation. We also wired through raw headers on the request and response path for custom headers on compute gateway. Finally we used the `FeedRangeState<TState>` which is a composite of FeedRange and State to lower the number of parameters on most functions that require both.

2021-01-22 05:05 UTC, DmitriMelnikov submitted a review, later dismissed
Looks good

2021-01-22 05:05 UTC, DmitriMelnikov commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/DocumentContainerChangeFeedTests.cs
> +                changeFeedPaginationOptions: new ChangeFeedPaginationOptions(ChangeFeedMode.Incremental, pageSizeHint: 10),
const

2021-01-22 05:05 UTC, DmitriMelnikov commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/DocumentContainerChangeFeedTests.cs
> +                    changeFeedPaginationOptions: new ChangeFeedPaginationOptions(ChangeFeedMode.Incremental, pageSizeHint: 10),
const

2021-01-22 05:05 UTC, DmitriMelnikov commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/NetworkAttachedDocumentContainerTests.cs
> +                feedRangeState: new FeedRangeState<ChangeFeedState>(new FeedRangePartitionKeyRange("0"), ChangeFeedState.Beginning()),
const for "0"

2021-01-22 05:05 UTC, DmitriMelnikov commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Pagination/DocumentContainerTests.cs
> +                            pageSizeHint: 1),
const for literals

2021-01-22 17:37 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/ChangeFeed/ChangeFeedCrossFeedRangeAsyncEnumerable.cs
> +            this.jsonSerializationFormatOptions = jsonSerializationFormatOptions;
JsonSerializationFormatOptions was not designed with a default. 

---
In reply to: [562376028](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2144#discussion_r562376028) [](ancestors = 562376028)

2021-01-22 17:38 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/ChangeFeed/Pagination/ChangeFeedPage.cs
> +            IReadOnlyDictionary<string, string> additionalHeaders,
im open to other names. 

For now I chose additonal headers, since we have requestCharge and activityId on the outer object. 

---
In reply to: [562377603](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2144#discussion_r562377603) [](ancestors = 562377603)

2021-01-22 17:39 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/ChangeFeed/Pagination/ChangeFeedPaginationOptions.cs
> +        protected override ImmutableHashSet<string> BannedAdditionalHeaders => throw new System.NotImplementedException();
This one actually needs to be implemented at some point. 

---
In reply to: [562378534](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2144#discussion_r562378534) [](ancestors = 562378534)

2021-01-22 17:40 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Pagination/CrossFeedRangePage.cs
> +            : base(backendEndPage.RequestCharge, backendEndPage.ActivityId, backendEndPage.AdditionalHeaders, state)
keep what separate from AdditionalHeaders?

---
In reply to: [562379752](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2144#discussion_r562379752) [](ancestors = 562379752)

2021-01-22 17:40 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Pagination/CrossFeedRangePage.cs
> +        protected override ImmutableHashSet<string> DerivedClassBannedHeaders => bannedHeaders;
This class is an exception. The other classes make it clear what this protected field is used for. 

---
In reply to: [562380821](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2144#discussion_r562380821) [](ancestors = 562380821)

2021-01-22 17:42 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Pagination/NetworkAttachedDocumentContainer.cs
> +                           request.Headers[HttpConstants.HttpHeaders.ContentSerializationFormat] = readFeedPaginationOptions.JsonSerializationFormat.Value.ToContentSerializationFormatString();
It's not a publicly facing header so not really. This PR also aims to touch as little outside of the Pagination library. 

---
In reply to: [562381567](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2144#discussion_r562381567) [](ancestors = 562381567)

2021-01-22 17:44 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CrossPartition/OrderBy/OrderByQueryPage.cs
> +        protected override ImmutableHashSet<string> DerivedClassBannedHeaders => bannedHeaders;
Stronger the better. It would be data loss if the class allowed the user to have an activity id as a property and also in the dictionary. By the time we need to serialize this schematized type to an http header we would have two potentially different values for the same header. Which one do we take at that point. To avoid this we ban the user from setting those headers. 

---
In reply to: [562386642](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2144#discussion_r562386642) [](ancestors = 562386642)

2021-01-22 17:44 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Pagination/NetworkAttachedDocumentContainer.cs
> +            foreach (string key in responseMessage.Headers)
We can refactor this out. 

---
In reply to: [562384562](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2144#discussion_r562384562) [](ancestors = 562384562)

2021-01-22 17:46 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Pagination/Page.cs
> +        public ImmutableDictionary<string, string> AdditionalHeaders { get; }
IReadOnlyDictionary can be casted down. It also reflects any modifications that happen to the underneath dictionary. This lets the caller know that the values will not change throughout the lifetime of this object, which is required for it to truly be immutable. Basically this is the use case for Immutable vs IReadOnly. 

---
In reply to: [562385085](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2144#discussion_r562385085) [](ancestors = 562385085)

2021-01-22 17:48 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Pagination/PaginationOptions.cs
> +        private static readonly ImmutableDictionary<string, string> EmptyDictionary = new Dictionary<string, string>()
You can do the same with ReadOnly by passing it into the copy constructor of another dictionary. Nothing will stop a user from doing something nonsensical. I talked about Immutable vs ReadOnly in another thread. 

---
In reply to: [562385963](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2144#discussion_r562385963) [](ancestors = 562385963)

2021-01-22 17:49 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/DCount/DCountQueryPipelineStage.Client.cs
> +                    additionalHeaders = sourcePage.AdditionalHeaders;
Yeah for these aggregation scenarios we just take the headers from the last response. We aggregate known headers that we know we need to aggregate but the we just keep the last page for those other headers. 

---
In reply to: [562387136](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2144#discussion_r562387136) [](ancestors = 562387136)

2021-01-22 17:50 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/SkipEmptyPageQueryPipelineStage.cs
> +        private ImmutableDictionary<string, string> cumulativeAdditionalHeaders;
It get's used on line 89

---
In reply to: [562387817](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2144#discussion_r562387817) [](ancestors = 562387817)

2021-01-22 17:51 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                additionalHeaders = null;
You have to allocate for an empty dictionary. The constructor of the type will init to an empty dictionary singleton, since it's an immutable dictionary (something you can do with ImmutableDictionary, but not IReadOnlyDictionary). 

---
In reply to: [562388967](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2144#discussion_r562388967) [](ancestors = 562388967)

2021-01-22 17:52 UTC, bchong95 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/DocumentContainerChangeFeedTests.cs
> +                changeFeedPaginationOptions: new ChangeFeedPaginationOptions(ChangeFeedMode.Incremental, pageSizeHint: 10),
These options very from request to request. 

---
In reply to: [562389686](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2144#discussion_r562389686) [](ancestors = 562389686)

2021-01-22 17:53 UTC, bchong95 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/DocumentContainerChangeFeedTests.cs
> +                    changeFeedPaginationOptions: new ChangeFeedPaginationOptions(ChangeFeedMode.Incremental, pageSizeHint: 10),
Variance from request to request. 

---
In reply to: [562389906](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2144#discussion_r562389906) [](ancestors = 562389906)

2021-01-22 17:55 UTC, bchong95 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Pagination/DocumentContainerTests.cs
> +                            pageSizeHint: 1),
You would have to declare the integer outside of the constructor. The variable is also passed by value, so it's not like const matters here. `const` is used when we want to ensure the value of the variable is not written to throughout it's lifetime. It doesn't matter much for a short lived variable. 

---
In reply to: [562390129](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2144#discussion_r562390129) [](ancestors = 562390129)

2021-01-22 18:00 UTC, bchong95 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/NetworkAttachedDocumentContainerTests.cs
> +                feedRangeState: new FeedRangeState<ChangeFeedState>(new FeedRangePartitionKeyRange("0"), ChangeFeedState.Beginning()),
refer to other threads about my take on when to use const.

2021-01-22 18:20 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/ChangeFeed/Pagination/ChangeFeedPaginationOptions.cs
> +        protected override ImmutableHashSet<string> BannedAdditionalHeaders => throw new System.NotImplementedException();
implemented it. 

---
In reply to: [562794985](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2144#discussion_r562794985) [](ancestors = 562794985,562378534)

2021-01-22 18:29 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Pagination/NetworkAttachedDocumentContainer.cs
> +                    Dictionary<string, string> additionalHeaders = new Dictionary<string, string>();
good point. 

---
In reply to: [562382879](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2144#discussion_r562382879) [](ancestors = 562382879)

2021-01-22 18:29 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Pagination/Page.cs
> +            this.AdditionalHeaders = additionalHeaders == null ? EmptyDictionary : additionalHeaders.ToImmutableDictionary();
The linter on this project prefers shorter names. 

---
In reply to: [562385271](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2144#discussion_r562385271) [](ancestors = 562385271)

2021-01-26 00:16 UTC, vivekr20 commented on Microsoft.Azure.Cosmos/src/Pagination/Page.cs
> +        private static readonly ImmutableDictionary<string, string> EmptyDictionary = new Dictionary<string, string>().ToImmutableDictionary();
If this is never going to be modified, can you just make this a ReadOnlyDictionary?

2021-01-26 00:46 UTC, vivekr20 commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                changeFeedRequestOptions?.JsonSerializationFormatOptions);
Do you need to pass this in?
We could reduce one param and just get it from changeFeedPaginationOptions?.JsonSerializationFormatOptions

2021-01-26 01:48 UTC, vivekr20 reviewed
changeFeedRequestOptions.Properties Values cannot be stringified (ToString()) as that will affect the serialization downstream.

2021-01-26 01:48 UTC, vivekr20 commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                additionalHeaders = new Dictionary<string, string>();
This has to be Dictionary<string, object> since header values are not always strings.
Example headers: "x-ms-schema-id" (int), "x-ms-schema-hash" (byte[]), "x-ms-cosmos-merge-static-id" (byte[])

2021-01-29 19:11 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Pagination/Page.cs
> +        private static readonly ImmutableDictionary<string, string> EmptyDictionary = new Dictionary<string, string>().ToImmutableDictionary();
There are many discussions on ReadOnly vs Immutable dictionary in this PR already.

2021-01-30 04:19 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                changeFeedRequestOptions?.JsonSerializationFormatOptions);
No the ChangeFeedPaginationOptions.JsonSerializationFormat is not the same as JsonSerializationFormatOptions.

2021-01-30 04:20 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                additionalHeaders = new Dictionary<string, string>();
Okay keeping it to just the string values.

2021-02-03 01:28 UTC, sboshra commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Pagination/InMemoryContainer.cs
> +                    .Take(readFeedPaginationOptions.PageSizeHint.GetValueOrDefault(int.MaxValue))
>PageSizeHint [](start = 52, length = 12)

should this be called hint?

2021-02-03 01:30 UTC, sboshra submitted a review, later dismissed
:shipit:

2021-02-03 18:57 UTC, vivekr20 approved these changes

2021-02-03 19:11 UTC, vivekr20 requested changes
Can you support non-string headers? This will break certain scenarios for Cassandra which worked earlier.

2021-02-03 19:11 UTC, vivekr20 commented on Microsoft.Azure.Cosmos/src/ChangeFeed/ChangeFeedIteratorCore.cs
> +                                additionalHeaders[keyValuePair.Key] = stringValue;
This still doesn't work for static Id or schemaHash headers which are byte[]. Please support passing non-string headers.

2021-02-03 20:02 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/ChangeFeed/ChangeFeedIteratorCore.cs
> +                                additionalHeaders[keyValuePair.Key] = stringValue;
This usecase is supported in ChangeFeedAsyncEnumerable. Not ChangeFeedIteratorCore. Please switch the API in your local testing.

2021-02-03 20:47 UTC, vivekr20 approved these changes

2021-02-03 21:18 UTC, vivekr20 commented on Microsoft.Azure.Cosmos/src/ChangeFeed/ChangeFeedIteratorCore.cs
> +                                additionalHeaders[keyValuePair.Key] = stringValue;
Ack. We will move usage of Cassandra and Mongo ChangeFeed to AsyncEnumerable following this change, when we add support for Scale Up and Scale down, and any other future ChangeFeed features,

2021-02-03 22:45 UTC, bchong95 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Pagination/InMemoryContainer.cs
> +                    .Take(readFeedPaginationOptions.PageSizeHint.GetValueOrDefault(int.MaxValue))
made it PageSizeLimit

2021-02-04 02:40 UTC, vivekr20 approved these changes

2021-02-05 01:06 UTC, sboshra approved these changes

2021-02-05 03:08 UTC, merged