Adding EnableContentResponseOnWrite to Client level settings
Azure/azure-cosmos-dotnet-v3 pull request #2145
Opened 2021-01-22 08:40 UTC by asketagarwal

# Pull Request Template

## Description

This PR adds a new field to the CosmosClient settings to enable/disable Content Response on write operations for Documents. Currently, this needs to be configured for every item request. We can now set this when creating CosmosClient. We can also override this in ItemRequestOptions while calling any Item operation.

2021-01-22 10:51 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        /// the resource back over the network and serializing it on the client.
What's expected of transactional-batch with read-only operations which is always routed to primary replica currently?

2021-01-22 10:51 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        /// the resource back over the network and serializing it on the client.
Please include code references for builder as well.

2021-01-22 10:52 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
> +        public CosmosClientBuilder WithContentResponseOnWriteEnabled(bool contentResponseOnWriteEnabled)
https://github.com/Azure/azure-cosmos-dotnet-v3/issues/1917#issuecomment-765314571

2021-01-22 10:54 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosClientContentResponseTests.cs
> +        public async Task ClientContentResponseWithItemRequestOverrideTrueTest()
Read tests (ReadItem, query, CF, etc...), ensure that the responses do exist with the option set.

2021-01-22 10:54 UTC, kirankumarkolli requested changes
Waiting for UT coverage

2021-01-22 12:11 UTC, asketagarwal commented on Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
> +        public CosmosClientBuilder WithContentResponseOnWriteEnabled(bool contentResponseOnWriteEnabled)
Currently, JAVA has boolean as an argument for this property.
https://docs.microsoft.com/en-us/java/api/com.azure.cosmos.cosmosclientbuilder.contentresponseonwriteenabled?view=azure-java-stable

2021-01-22 14:03 UTC, asketagarwal commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        /// the resource back over the network and serializing it on the client.
This property won't affect writes for TransactionBatch. Do you think it should ?

2021-01-22 17:45 UTC, j82w commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        /// the resource back over the network and serializing it on the client.
This property should work with TransactionalBatch and Bulk scenarios.

2021-01-22 17:45 UTC, j82w commented on Microsoft.Azure.Cosmos/src/RequestOptions/ItemRequestOptions.cs
> +            if (ShouldRemoveNoContentHeader(this.EnableContentResponseOnWrite, request.OperationType)
Why is this needed? Can the client level skip setting the value if the request option is set? It avoids unnecessary dictionary overhead of adding and removing values.

2021-01-22 21:58 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        /// the resource back over the network and serializing it on the client.
I think this property is wired for Bulk and TransactionalBatch.

See https://github.com/Azure/azure-cosmos-dotnet-v3/blob/9e51de53b3f10e20846b7fdb86837b1cccd4efae/Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchItemRequestOptions.cs#L43 and https://github.com/Azure/azure-cosmos-dotnet-v3/blob/9e51de53b3f10e20846b7fdb86837b1cccd4efae/Microsoft.Azure.Cosmos/src/Batch/ItemBatchOperation.cs#L170.

For bulk at least, it is only used on Write operations.

2021-01-22 21:59 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        /// </remarks>
Maybe link with `<seealso cref="ItemRequestOptions.EnableContentResponseOnWrite" />` ?

2021-01-22 22:02 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
> +            if (request.ResourceType == ResourceType.Document
This potentially won't work on Bulk. Bulk creates 1 network request with OperationType.Batch, and the EnableContentResponseOnWrite is set inside each operation through https://github.com/Azure/azure-cosmos-dotnet-v3/blob/9e51de53b3f10e20846b7fdb86837b1cccd4efae/Microsoft.Azure.Cosmos/src/Batch/ItemBatchOperation.cs#L170

It might need to be wired down there too.

2021-01-22 22:03 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/RequestOptions/ItemRequestOptions.cs
> +            if (ShouldRemoveNoContentHeader(this.EnableContentResponseOnWrite, request.OperationType)
If the ItemRequestOptions set the header, the client settings should not remove it. ItemRequestOptions should win over client settings.

2021-01-25 14:53 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Batch/ItemBatchOperation.cs
> +            CosmosClientContext cosmosClientContext = null)
Please make this field required. Prevents bugs caused by code paths not sending in the value.

2021-01-25 14:53 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Batch/ItemBatchOperation.cs
> +        internal CosmosClientContext ClientContext { get; set; }
nit: private since it is only being used internally.

2021-01-25 14:53 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Batch/ItemBatchOperation.cs
> +            if (((operation.RequestOptions != null && !operation.RequestOptions.EnableContentResponseOnWrite.HasValue) || operation.RequestOptions == null)
Can we have a single static method that takes in a ItemRequestOption and ClientOptions and does the logic? That way the logic for this validation and the RequestInvoker can share the same check.

2021-01-25 16:08 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
> +        internal static bool ShouldSetClientLevelNoContentResponseHeaders(RequestOptions requestOptions,
nit: 1 parameter per a line

2021-01-25 16:08 UTC, j82w commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosClientContentResponseTests.cs
> +            ItemResponse<ToDoActivity> itemResponseWithoutFlag = await this.containerWithoutFlag.CreateItemAsync(item);
This should be validated for Replace, Upsert, and other write operations.

2021-01-25 16:08 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Batch/ItemBatchOperation.cs
>                  if (ItemRequestOptions.ShouldSetNoContentHeader(
Can this be removed since the below case should handle it?

2021-01-25 17:37 UTC, asketagarwal commented on Microsoft.Azure.Cosmos/src/Batch/ItemBatchOperation.cs
>                  if (ItemRequestOptions.ShouldSetNoContentHeader(
this sets the header for the indivisual item in the batch

2021-01-25 17:44 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Batch/ItemBatchOperation.cs
> +            CosmosClientContext cosmosClientContext = null)
Not needed, the `CosmosInternal` instance that it's already available has the ClientContext

2021-01-25 17:44 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Batch/ItemBatchOperation.cs
>              ContainerInternal containerCore,
This ContainerInternal reference has a ClientContext property

2021-01-25 17:44 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Batch/ItemBatchOperation.cs
> +        private CosmosClientContext ClientContext { get; set; }
`private readonly CosmosClientContext` is better than private with get/set, since it defines that it is only set during constructor.

2021-01-25 17:48 UTC, asketagarwal commented on Microsoft.Azure.Cosmos/src/Batch/ItemBatchOperation.cs
>              ContainerInternal containerCore,
this class has 2 constructors, in which one does not set the ContainerInternal property

2021-01-25 18:07 UTC, asketagarwal commented on Microsoft.Azure.Cosmos/src/Batch/ItemBatchOperation.cs
> +        internal CosmosClientContext ClientContext { get; set; }
made private readonly

2021-01-25 18:07 UTC, asketagarwal commented on Microsoft.Azure.Cosmos/src/Batch/ItemBatchOperation.cs
> +            if (((operation.RequestOptions != null && !operation.RequestOptions.EnableContentResponseOnWrite.HasValue) || operation.RequestOptions == null)
made change

2021-01-25 18:08 UTC, asketagarwal commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosClientContentResponseTests.cs
> +            ItemResponse<ToDoActivity> itemResponseWithoutFlag = await this.containerWithoutFlag.CreateItemAsync(item);
added

2021-01-25 19:57 UTC, kirankumarkolli approved these changes

2021-01-25 19:58 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Batch/ItemBatchOperation.cs
>                  if (ItemRequestOptions.ShouldSetNoContentHeader(
This is a duplicate of the logic below where it does the client check right?

2021-01-25 22:52 UTC, j82w commented
/azp run

2021-01-25 23:16 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Batch/ItemBatchOperation.cs
>              ContainerInternal containerCore,
Yeah, that's why it only makes sense adding it in the one where we are not already passing the ContainerInternal. In this particular constructor, we already have the ContainerInternal, so we can always do `this.ClientContext= containerCore.ClientContext`.

2021-01-26 14:13 UTC, asketagarwal commented
/azp run

2021-01-26 14:23 UTC, j82w commented
/azp run

2021-01-27 14:11 UTC, j82w approved these changes

2021-01-27 14:46 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
> +        public CosmosClientBuilder WithContentResponseOnWriteEnabled(bool contentResponseOnWriteEnabled)
Can we make the new APIs part of the preview SDK?

@FabianMeiswinkel  and @ealsur what are your thoughts on the name? 

Should it just be `WithContentResponseOnWrite`? I don't see a reason for having Enabled in the name.

2021-01-27 17:28 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
> +        public CosmosClientBuilder WithContentResponseOnWriteEnabled(bool contentResponseOnWriteEnabled)
I agree with removing the `Enabled`, the boolean makes it kind of implicit.

2021-01-27 17:55 UTC, asketagarwal commented on Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
> +        public CosmosClientBuilder WithContentResponseOnWriteEnabled(bool contentResponseOnWriteEnabled)
https://docs.microsoft.com/en-us/java/api/com.azure.cosmos.cosmosclientbuilder.contentresponseonwriteenabled?view=azure-java-stable

Java has it named like this

2021-01-27 18:10 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
> +        public CosmosClientBuilder WithContentResponseOnWriteEnabled(bool contentResponseOnWriteEnabled)
@kushagraThapar is the "Enabled" some kind of Java standard?

2021-01-27 18:33 UTC, asketagarwal commented
/azp run

2021-01-27 19:00 UTC, j82w commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosClientContentResponseTests.cs
> +                     partitionKeyPath: "/status");
```suggestion
                     partitionKeyPath: "/pk");
```

2021-01-27 19:00 UTC, j82w commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosClientContentResponseTests.cs
> +                     partitionKeyPath: "/status");
```suggestion
                     partitionKeyPath: "/pk");
```

2021-01-29 20:14 UTC, ealsur approved these changes
LGTM @kirankumarkolli could you verify the public API change and see if it's fine?

2021-02-01 15:25 UTC, asketagarwal commented
/azp run

2021-02-01 15:41 UTC, j82w approved these changes

2021-02-01 16:51 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
> +            if (RequestInvokerHandler.ShouldSetNoContentResponseHeaders(request.RequestOptions, this.client.ClientOptions, request.OperationType, request.ResourceType))
Arguments on new line

2021-02-01 16:53 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
> +                    return IsItemNoRepsonseSet(itemRequestOptions.EnableContentResponseOnWrite.Value, operationType);
Prefix with the class names for static invocations. 

@j82w can it be coded into the style configuration?

2021-02-01 16:54 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
> +            if (requestOptions is TransactionalBatchItemRequestOptions batchRequestOptions)
Isn't the new configuration all based on ItemRequestOptions only?

2021-02-01 16:56 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
> +              operationType == OperationType.Patch);
Was wondering if we need a fine granular control in the future. 

I.e. CRU typically has full payload, where as patch result might be needed for applications. 
We could actually exclude Patch from here as one more alternative as well.

2021-02-01 17:15 UTC, asketagarwal commented on Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
> +            if (requestOptions is TransactionalBatchItemRequestOptions batchRequestOptions)
The ContentResponse flag is also available for TransactionalBatchRequestOptions

2021-02-01 17:46 UTC, asketagarwal commented on Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
> +              operationType == OperationType.Patch);
Even if we set the flag at the client level. It can always be overridden by the request level flag. So that should take care of it right?

2021-02-01 19:24 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
> +        "Microsoft.Azure.Cosmos.Fluent.CosmosClientBuilder WithContentResponseOnWriteEnabled(Boolean)": {
Can WithContentResponseOnWrite(boolean)

2021-02-01 19:25 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +#if PREVIEW
Why can't it be GA?

2021-02-01 19:28 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
> +              operationType == OperationType.Patch);
/cc: @deparash , @akhetarp

2021-02-01 19:29 UTC, moderakh commented on Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
> +        public CosmosClientBuilder WithContentResponseOnWriteEnabled(bool contentResponseOnWriteEnabled)
Java idom. our Java boolean flags all end with "Enabled" suffix.

2021-02-01 19:29 UTC, j82w commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +#if PREVIEW
Since we decided on `WithContentResponseOnWrite `then we can make it part of the GA SDK.

2021-02-01 19:31 UTC, moderakh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
> +        "Microsoft.Azure.Cosmos.Fluent.CosmosClientBuilder WithContentResponseOnWriteEnabled(Boolean)": {
for java we have both client level and request level option to control this:
client level:
https://azuresdkdocs.blob.core.windows.net/$web/java/azure-cosmos/latest/com/azure/cosmos/CosmosClientBuilder.html#contentResponseOnWriteEnabled-boolean-

request level: https://azuresdkdocs.blob.core.windows.net/$web/java/azure-cosmos/latest/com/azure/cosmos/models/CosmosItemRequestOptions.html#setContentResponseOnWriteEnabled-java.lang.Boolean-

2021-02-01 20:25 UTC, moderakh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
> +        "Microsoft.Azure.Cosmos.Fluent.CosmosClientBuilder WithContentResponseOnWriteEnabled(Boolean)": {
Jake I did not ask for "Enabled" suffix to be added on the Dot Net side. Java and DotNet are two different language with different culture for naming the apis. 

as long as the config name excluding "enable" "enabled" prefix/suffix is the same across both java and dotnet it is fine.
different language have different naming convention.

2021-02-02 12:53 UTC, j82w approved these changes

2021-02-02 13:18 UTC, kirankumarkolli approved these changes

2021-02-02 13:19 UTC, kirankumarkolli commented
FYI Arun also signed off to include Patch.

2021-02-02 13:58 UTC, merged