Session Token Optimization for Gateway Mode.
Azure/azure-cosmos-dotnet-v3 pull request #2165
Opened 2021-01-29 14:48 UTC by asketagarwal

# Pull Request Template

## Description

Currently in Gateway Mode, the entire session token from all Partitions is sent to the backend. With this change we try to resolve the partition of the request before sending to gateway and send only that session token. This will solve the issue of large headers leading to 400 errors. 
We first try to resolve the partition from PartitionKeyRangeCache. If we can't, we refresh the cache. If we still can't we send the GlobalSessionToken.

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #IssueNumber

2021-01-29 15:08 UTC, j82w commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +            if (request == null)
null check all the parameters

2021-01-29 15:08 UTC, j82w commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +            if (request.Headers[HttpConstants.HttpHeaders.PartitionKey] != null)
Set partition key value to a variable to avoid multiple dictionary accesses.

2021-01-29 15:08 UTC, j82w commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/GatewaySessionTokenTests.cs
> +        public async Task TestGatewayModelSession()
Can a test be added using the HttpHandler to validate the header is only for the single partition to validate the end to end scenario? Look at `HttpClientHandlerHelper`

1. Create an item and get the session token from the handler
2. Read the item and verify the same session token is used on the read request

2021-02-01 16:34 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +        internal PartitionKeyRangeCache PartitionKeyRangeCache { get; set; }
If the set is happening within GatewayStoreModel through SetCaches, these should be private.

2021-02-01 16:35 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +            if (!sessionConsistency || !request.IsReadOnlyRequest)
Right now we are not sending the token if the consistency is not session from what I understand from the code. Wouldn't this change make it so it would be sent for all read requests, regardless of consistency? Is this expected?

2021-02-01 16:36 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +                partitionKeyRange = await ResolvePartitionKeyRangeAsync(request, sessionContainer, partitionKeyRangeCache, clientCollectionCache, false);
named arguments, particularly for the `false` at the end, so it's easier to understand without having to jump to the definition

2021-02-01 16:40 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +            return null;
Instead of returning null, what about a method that is a `TryResolveSessionTokenAsync` that returns a true/false depending on the fact that it could resolve it and the session token as out parameter? That avoids having to return `null` and having the caller interpret what `null` means.

2021-02-01 16:42 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +                return await ResolvePartitionKeyRangeAsync(request, sessionContainer, partitionKeyRangeCache, clientCollectionCache, true);
named parameters, particularly for the `true`

2021-02-01 16:44 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +                    return null;
Again, I wonder if we can turn this around and void using `null` and instead have a Try approach?

2021-02-01 17:22 UTC, asketagarwal commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +            if (!sessionConsistency || !request.IsReadOnlyRequest)
if (!sessionConsistency || !request.IsReadOnlyRequest)
{
    return;
}

The method proceeds only if the request is sessionconsistent and read only

2021-02-01 17:22 UTC, asketagarwal commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +            return null;
makes sense

2021-02-01 19:38 UTC, j82w commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +            if (!sessionConsistency || !request.IsReadOnlyRequest)
There is no point in sending a session token for write operations.

2021-02-01 19:52 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +            if (!sessionConsistency || !request.IsReadOnlyRequest)
I read it the other way around, nevermind.

2021-02-02 13:07 UTC, asketagarwal commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +            return null;
it seems async methods can't have out parameters. Can you suggest a workaround

2021-02-02 14:05 UTC, j82w commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +            return null;
There is two options that I'm aware of.
1. Use `TryCatch` which lets you handle success and failure scenarios
2. Return a tuple like go. (bool isSuccess, string sessionToken).

2021-02-02 16:46 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +            if (!sessionConsistency || !request.IsReadOnlyRequest)
@j82w will it cover for batch (which can be read-only)?

2021-02-02 16:48 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Routing/AddressResolver.cs
> +                    return TryResolveServerPartitionByPartitionKey(
Prefix with class name.

2021-02-02 16:50 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +            PartitionKeyRangeCache partitionKeyRangeCache = null,
Why allow optional?

2021-02-02 16:52 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +            if (isSuccess)
What's the value of this if-clause outside. Or why not nest it previous if-clause?

2021-02-02 16:54 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +                    return new Tuple<bool, string>(true, partitionKeyRange.Id + ":" + localSessionToken);
Wondering why isn;t the formatting is done inside the Resolve API it-self? 
In other words why is this magic composition is needed?

2021-02-02 16:55 UTC, kirankumarkolli requested changes
Waiting on the session token composition.

2021-02-02 17:58 UTC, asketagarwal commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +                    return new Tuple<bool, string>(true, partitionKeyRange.Id + ":" + localSessionToken);
The resolve api is in Master Repo and that method only returns us the sessiontoken and not the partitionkeyrangeid

2021-02-05 14:22 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +                    return new Tuple<bool, string>(true, partitionKeyRange.Id + ":" + localSessionToken);
It might be that direct and gateway has different expectations. 
If so its better to have explicit contract on the SessionContainer for each and leverage.

2021-02-05 17:34 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +        private ClientCollectionCache ClientCollectionCache { get; set; }
nit, no need for `{ get; set; }`

2021-02-05 17:35 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +            if (!sessionConsistency || !request.IsReadOnlyRequest)
I think Batch is always considered a Write requests (it goes to ConsistencyWriter) regardless of the operations contained inside it

2021-02-05 17:37 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +            if (!isSuccess)
I wonder (not blocking, just an idea): Why not have this if inside the previous one? This avoids having to define variables outside of the scope

```
string sessionToken = null;
if (clientCollectionCache != null && partitionKeyRangeCache != null)
{	         
	(bool isSuccess, sessionToken) = await TryResolveSessionTokenAsync(request, sessionContainer, partitionKeyRangeCache, clientCollectionCache);
	if (!isSuccess)
	{
		sessionToken = sessionContainer.ResolveGlobalSessionToken(request);
	}
}
```

2021-02-08 16:33 UTC, asketagarwal commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +            if (!isSuccess)
In case the cache is null, we can Resolve the Global Session Token

2021-02-11 14:06 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +        private ClientCollectionCache ClientCollectionCache;
camelcase for instance members.

2021-02-11 14:09 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +            if (!sessionConsistency || !request.IsReadOnlyRequest)
@ealsur isn't that current implementation details. 
Or we will track it part of implementation change (we might miss this subtle aspect easily)

2021-02-11 14:14 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +        public void SetCaches(PartitionKeyRangeCache partitionKeyRangeCache, ClientCollectionCache clientCollectionCache)
Argument per line

2021-02-11 14:17 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +            if (!isSuccess)
What scenario needs it?

2021-02-11 14:18 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +            if (clientCollectionCache != null && partitionKeyRangeCache != null)
What scenario will need to allow null caches?

2021-02-11 14:20 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Routing/AddressResolver.cs
> -                range = this.TryResolveServerPartitionByPartitionKey(
AddressResolver.

2021-02-11 14:23 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/SessionContainer.cs
> +        private static string ResolvePartitionLocalSessionTokenForGateway(SessionContainerState self, DocumentServiceRequest request, string partitionKeyRangeId)
Argument per line

2021-02-11 14:26 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/SessionContainer.cs
> +                            return partitionKeyRangeId + ":" + sessionToken.ConvertToString();
@ealsur any possible merge impact?

2021-02-12 16:25 UTC, j82w commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +            if (!sessionConsistency || !request.IsReadOnlyRequest)
Add an exception for Batch requests.

2021-03-16 18:06 UTC, ealsur approved these changes
Left some nits, would be good to do a manual split test

2021-03-16 18:06 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +                return await TryResolvePartitionKeyRangeAsync(request, sessionContainer, partitionKeyRangeCache, clientCollectionCache, true);
nit: named parameters

2021-03-16 18:06 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +                return await TryResolvePartitionKeyRangeAsync(request, sessionContainer, partitionKeyRangeCache, clientCollectionCache, true);
nit: `this.TryResolvePartitionKeyRangeAsync` since it's a local method

2021-03-16 18:06 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +                return await TryResolvePartitionKeyRangeAsync(request, sessionContainer, partitionKeyRangeCache, clientCollectionCache, true);
Would be interesting to manually test a split:

* Do one operation on a 400 RU collection (Gateway mode). Like a Read document that exists.
* Increase RU to 12000 to trigger split and wait ~10 minutes. Pause or put a breakpoint.
* Repeat Read document on the same client instance after the breakpoint and verify if it works as expected.

2021-03-22 23:32 UTC, j82w approved these changes

2021-03-23 12:31 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +            if (!sessionConsistency || (!request.IsReadOnlyRequest && request.OperationType != OperationType.Batch))
Unsure on the batch condition part. 

In-case of batch with read-only won't we need to include session-token? 
In other words isn't it safe to include session token for all batch operations? (Its scoped to single PkRangId anyways)

2021-03-23 12:34 UTC, kirankumarkolli approved these changes
Please close on the batch part before merging.

/cc: @j82w

2021-03-23 13:02 UTC, asketagarwal commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +            if (!sessionConsistency || (!request.IsReadOnlyRequest && request.OperationType != OperationType.Batch))
This does set the session token for all batch operations.
(!request.IsReadOnlyRequest && request.OperationType != OperationType.Batch) will be false for Batch operations and the method will continue with setting the session token

2021-03-29 05:30 UTC, asketagarwal commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +                return await TryResolvePartitionKeyRangeAsync(request, sessionContainer, partitionKeyRangeCache, clientCollectionCache, true);
Thanks for suggesting this. I did this test on a prod container and it seems to work as expected. After a split, the sdk will send the lsn number of the parent of the new partitionkeyrange.

2021-03-29 05:31 UTC, asketagarwal commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +                return await TryResolvePartitionKeyRangeAsync(request, sessionContainer, partitionKeyRangeCache, clientCollectionCache, true);
Thanks for suggesting this. I did this test on a prod container and it seems to work as expected. After a split, the sdk will send the lsn number of the parent of the new partitionkeyrange.

2021-03-29 13:32 UTC, j82w approved these changes

2021-03-29 19:08 UTC, ealsur approved these changes
Thanks for testing splits

2021-03-29 19:59 UTC, merged