3.17.0 and 3.17.0-preview1: Adds changelog and contract files
Azure/azure-cosmos-dotnet-v3 pull request #2247
Opened 2021-02-23 15:38 UTC by j82w

# Pull Request Template

## Description

This bumps the SDK version to 3.17.0 and 3.17.0-preview1.

3.17.0-preview1 compared to 3.17.0-preview:
![image](https://user-images.githubusercontent.com/8868107/108866958-8ff43080-75a9-11eb-8e01-121704c5d601.png)

3.17.0 compared to 3.16.0
![image](https://user-images.githubusercontent.com/8868107/108867368-f9743f00-75a9-11eb-9fb3-acd512d58413.png)

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #IssueNumber

2021-02-23 15:46 UTC, FabianMeiswinkel approved these changes
LGTM

2021-02-23 17:30 UTC, kirankumarkolli approved these changes

2021-02-23 18:05 UTC, sboshra submitted a review, later dismissed
:shipit:

2021-02-23 20:48 UTC, ealsur approved these changes

2021-02-23 20:49 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
> +	</ItemGroup>
nit: What happened with the padding?

2021-02-23 20:52 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
> +	</ItemGroup>
This is the correct padding. I don't see a reason to keep modifying the file to use the wrong padding to just avoid a white space change. This will prevent future check-ins to avoid needing to deal with the bad formatting.

2021-02-23 23:05 UTC, bchong95 requested changes
Let's wait a few days. CTL shows a bug in the marshalling between the SDK and ServiceInterop. Query team is investigating.

2021-03-01 18:15 UTC, bchong95 submitted a review, later dismissed

2021-03-02 16:35 UTC, ealsur approved these changes

2021-03-02 16:36 UTC, FabianMeiswinkel approved these changes
LGTM

2021-03-02 18:02 UTC, merged