CosmosDiagnostics: Adds Client Configuration to CosmosDiagnostics
Azure/azure-cosmos-dotnet-v3 pull request #2250
Opened 2021-02-24 12:07 UTC by asketagarwal

# Pull Request Template

## Description

This PR adds some basic Client Configuration to Cosmos Diagnostics

## Closing issues

To automatically close an issue: closes #2233

2021-02-24 13:29 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientConfigurationTraceDatum.cs
> +        internal Dictionary<string, string> ConnectionConfig { get; set; }
Is there a reason for this being a dictionary? Can we not just have a property for rntbd and gateway?

2021-02-24 14:34 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientConfigurationTraceDatum.cs
> +        internal override void Accept(ITraceDatumVisitor traceDatumVisitor)
Please add a sample of the output for a read item to the PR description?

2021-02-24 14:35 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
> +                trace.AddDatum("Client Configuration", this.Client.ClientConfigurationTraceDatum);
Please validate this works with query.

2021-02-24 18:08 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/CosmosClient.cs
> +        internal static int numberOfClients = 0;
>= 0; [](start = 44, length = 4)

No need to initialize to default(T)

2021-02-24 18:09 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +                                                      this.ConnectionPolicy.EnableTcpConnectionEndpointRediscovery);
Can we make this a struct to avoid the need for allocating a string right here?

2021-02-24 18:09 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +                                                      this.ConnectionPolicy.EnableTcpConnectionEndpointRediscovery);
Basically it would be nice to defer the string.Format until the user wants to print out the diagnostics. 

---
In reply to: [582186337](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2250#discussion_r582186337) [](ancestors = 582186337)

2021-02-24 18:10 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
> +                trace.AddDatum("Client Configuration", this.Client.ClientConfigurationTraceDatum);
This is not going to work with query/readfeed/changefeed , since only point operations call into this code path. 

---
In reply to: [582009599](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2250#discussion_r582009599) [](ancestors = 582009599)

2021-02-24 18:11 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Tracing/TraceWriter.TraceJsonWriter.cs
> +                this.jsonWriter.WriteInt64Value(clientConfigurationTraceDatum.NumberOfClients);
>WriteInt64Value [](start = 32, length = 15)

Use WriteNumberValue instead, so we want this to be type agnostic.

2021-02-24 18:11 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Tracing/TraceWriter.TraceJsonWriter.cs
> +                foreach (string connectionType in clientConfigurationTraceDatum.ConnectionConfig.Keys)
>string connectionType in clientConfigurationTraceDatum.ConnectionConfig.Keys [](start = 25, length = 76)

Enumerate a dictionary using KeyValuePair<TKey, TValue> instead. This create unnecesary hash lookups.

2021-02-24 18:12 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Tracing/TraceWriter.TraceJsonWriter.cs
> +                this.jsonWriter.WriteStringValue(clientConfigurationTraceDatum.ConsistencyConfig);
>WriteStringValue [](start = 32, length = 16)

WriteStringValueOrNull unless you know this type is never going to be null.

2021-02-24 18:13 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientConfigurationTraceDatum.cs
> +        internal DateTime ClientCreatedDateTimeUtc { get; }
>internal [](start = 8, length = 8)

Make the visibilty of types as if the class itself is public. so in this case the visibilty should be public.

2021-02-24 18:16 UTC, bchong95 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientConfigurationDiagnosticTest.cs
> +    public class ClientConfigurationDiagnosticTest : BaseCosmosClientHelper
>ClientConfigurationDiagnosticTest [](start = 17, length = 33)

Please update the baseline tests to cover this

2021-02-25 21:47 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
> +                trace.AddDatum("Client Configuration", this.Client.ClientConfigurationTraceDatum);
This needs to be fixed so all paths go through this code.

2021-03-01 14:51 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientConfigurationTraceDatum.cs
> +            return string.Format(CultureInfo.InvariantCulture,
These objects are immutable. Generating a string for every call will add a log of overhead for a constant string. How about adding a Lazy<string> private property so the overhead is only done once?

2021-03-01 14:51 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientConfigurationTraceDatum.cs
> +    internal struct OtherConnectionConfig
Please add a [perf test](https://github.com/Azure/azure-cosmos-dotnet-v3/tree/master/Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Benchmarks) for read item Diagnostics.ToString(). Provide the additional before/after numbers of adding the new fields.

2021-03-01 14:51 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientConfigurationTraceDatum.cs
> +        public override string ToString()
How about adding a ToJsonString()? It makes parsing the text easier.

2021-03-01 14:55 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/TraceWriter.TraceJsonWriter.cs
> +                this.jsonWriter.WriteFieldName("Id");
No need for an Id in the object. It's a single object with the property name of ClientConfig.

2021-03-04 13:25 UTC, j82w commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.ChangeFeedAsync.xml
>      │                                       └── Microsoft.Azure.Documents.ServerStoreModel Transport Request(00000000-0000-0000-0000-000000000000)  Transport-Component  MemberName@FilePath:42  12:00:
Where is the new Client Configuration for this file?

2021-03-04 13:25 UTC, j82w commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.QueryAsync.xml
>      │               │                       └── Microsoft.Azure.Documents.ServerStoreModel Transport Request(00000000-0000-0000-0000-000000000000)  Transport-Component  MemberName@FilePath:42  12:00:
Where is the Client Configuration?

2021-03-04 13:25 UTC, j82w commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.ReadFeedAsync.xml
>      │                                       └── Microsoft.Azure.Documents.ServerStoreModel Transport Request(00000000-0000-0000-0000-000000000000)  Transport-Component  MemberName@FilePath:42  12:00:
Please make sure any where that removed the user agent the new client configuration was added.

2021-03-05 14:56 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientConfigurationTraceDatum.cs
> +            return JsonConvert.SerializeObject(this);
Please make this lazy too

2021-03-05 14:57 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientConfigurationTraceDatum.cs
> +            return JsonConvert.SerializeObject(this);
Lazy to avoid overhead

2021-03-05 15:03 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/TraceWriter.TraceJsonWriter.cs
> +                this.jsonWriter.WriteObjectStart();
Since this is singleton for the client instance is there any way to avoid rewriting the data out each time? Instead write directly to the buffer to avoid the overhead of serializing the content each time?

2021-03-08 18:15 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/CosmosClient.cs
> +            Interlocked.Increment(ref numberOfClients);
Can't we leverage the EnvironmentInformation? Could this become out of sync with it?

2021-03-08 18:15 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/CosmosClient.cs
> +            Interlocked.Increment(ref numberOfClients);
Worth refactoring into a private method to avoid duplication?

2021-03-08 18:15 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientConfigurationTraceDatum.cs
> +            this.OtherConnectionConfig = new OtherConnectionConfig(cosmosClientContext.DocumentClient.ConnectionPolicy.EnableEndpointDiscovery,
`cosmosClientContext.DocumentClient.ConnectionPolicy.EnableEndpointDiscovery` should be `cosmosClientContext.ClientOptions.LimitToEndpoint` instead.

2021-03-08 18:15 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientConfigurationTraceDatum.cs
> +            this.OtherConnectionConfig = new OtherConnectionConfig(cosmosClientContext.DocumentClient.ConnectionPolicy.EnableEndpointDiscovery,
Is it worth passing the CosmosClientOptions instead to avoid having to add more parameters if we want to log more information, like the PreferredRegions?

2021-03-08 18:15 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientConfigurationTraceDatum.cs
> +                                                                       cosmosClientContext.DocumentClient.ConnectionPolicy.RequestTimeout,
Why not use the CosmosClientOptions attributes instead of the ConnectionPolicy? To reduce dependency on DocumentClient.

2021-03-08 18:15 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientConfigurationTraceDatum.cs
> +            this.RequestTimeout = (int)requestTimeout.TotalSeconds;
Keep in mind that this requesttimeout value is not completely accurate, we have a minimum timeout for HttpClient of 65 seconds, so even if the customer sets 5 seconds, it gets overriden for HTTP calls (but not for TCP calls)

2021-03-08 18:15 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientConfigurationTraceDatum.cs
> +        public bool IsWebProxyConfigured { get; }
nit: Worth logging if the user is using HttpClientFactory?

2021-03-08 18:15 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientConfigurationTraceDatum.cs
> +        public int ConnectionTimeout { get; }
Please add PortReuseMode

2021-03-08 18:15 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientConfigurationTraceDatum.cs
> +        public bool EnableEndpointDiscovery { get; }
Rename to LimitToEndpoint, that's the configuration in V3 SDK

2021-03-08 18:15 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientConfigurationTraceDatum.cs
> +            this.MultipleWriteLocationsEnabled = multipleWriteLocationsEnabled;
not worth logging MultipleWriteLocationsEnabled, user cannot change this.

2021-03-08 18:30 UTC, j82w commented on Microsoft.Azure.Cosmos/src/CosmosClient.cs
> +            Interlocked.Increment(ref numberOfClients);
The EnvironmentInformation should use the new flag. The current EnvironmentInformation flag is very fragile. If someone creates a new EnvironmentInformation anywhere it will make it looks like there is 2 instance even though there is only one.

2021-03-08 18:36 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientConfigurationTraceDatum.cs
> +            this.RequestTimeout = (int)requestTimeout.TotalSeconds;
Maybe it should be labeled UserRequestTimeout?

2021-03-11 12:53 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs
> +            return new FeedIteratorInlineCore<T>(new FeedIteratorCore<T>(
Why is this the FeedIteratorInlineCore? The ContainerInlineCore should be wrapping it.

2021-03-11 12:53 UTC, j82w commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/EndToEndTraceWriterBaselineTests.cs
> +                List<ITrace> traces = new List<ITrace>();
Why does this need to be a list?

2021-03-11 12:53 UTC, j82w commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.StreamPointOperationsAsync.xml
> +    │       Redacted To Not Change The Baselines From Run To Run
Why is this redacted? From what I can see all the other fields in the trace are able to set default values here.

2021-03-11 13:12 UTC, asketagarwal commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs
> +            return new FeedIteratorInlineCore<T>(new FeedIteratorCore<T>(
addressed

2021-03-11 14:21 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/CosmosClient.cs
> +        internal static int numberOfClients;
creationCount  != #clients. 

This might quickly get mis-interpreted unless named rightly.

2021-03-11 14:27 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Tracing/TraceWriter.TraceTextWriter.cs
> +                    StringBuilder stringBuilder = new StringBuilder();
Is it rebuilt on every visit? If so is rebuilding necessary?

2021-03-11 14:28 UTC, kirankumarkolli commented
Please cover the diagnostics changes explicitly (Config, UserAgent etc...).

2021-03-11 14:29 UTC, kirankumarkolli commented
What's the perf impact of this change?

2021-03-11 14:29 UTC, kirankumarkolli requested changes
What's the perf impact of this change?

2021-03-11 14:47 UTC, asketagarwal commented on Microsoft.Azure.Cosmos/src/Tracing/TraceWriter.TraceTextWriter.cs
> +                    StringBuilder stringBuilder = new StringBuilder();
i think we can avoid building for text but not json. the json writer we use does not support WriteRawJson. The fields written are lazily computed strings and only has to be done once per client (except number of clients and useragentstring)

2021-03-12 09:23 UTC, asketagarwal commented on Microsoft.Azure.Cosmos/src/CosmosClient.cs
> +        internal static int numberOfClients;
renamed

2021-03-15 17:38 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Tracing/TraceWriter.TraceTextWriter.cs
> +                    StringBuilder stringBuilder = new StringBuilder();
Do system.text.json support it? If so we can switch the serialzier underneath transparently.

/cc: @ealsur

2021-03-15 17:39 UTC, kirankumarkolli commented
Collection might be optimized as the uber datums are cached. Size blot is one small concern as well (we are now reaching 4K)

What's the impact of it on serialization?

2021-03-15 18:50 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/TraceWriter.TraceTextWriter.cs
> +                    StringBuilder stringBuilder = new StringBuilder();
The problem is ITrace uses the internal IJsonWriter which doesn't support a write raw like newtonsoft does.

2021-03-23 15:15 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientConfigurationTraceDatum.cs
> +    internal class GatewayConnectionConfig
Does it need to nested class or separate classes.

2021-03-23 15:16 UTC, kirankumarkolli commented
1. Multiple top level classes in the same file
2. Serialization performance
3. Cache the serialization (add a overload to the serialization API)

2021-03-25 11:36 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/TraceWriter.TraceJsonWriter.cs
> +                if (this.jsonWriter is IJsonTextWriterExtensions jsonTextWriter)
Should this throw an exception if it is not IJsonTextWriterExtensions? Or maybe do the serialization and do a debug fail?

2021-03-25 11:38 UTC, j82w approved these changes

2021-03-25 12:20 UTC, asketagarwal commented on Microsoft.Azure.Cosmos/src/Tracing/TraceWriter.TraceJsonWriter.cs
> +                if (this.jsonWriter is IJsonTextWriterExtensions jsonTextWriter)
throwing not implemented exception

2021-03-30 17:24 UTC, kirankumarkolli approved these changes

2021-03-30 20:55 UTC, merged