Availability: Fixes detection for hot path during gateway hang
Azure/azure-cosmos-dotnet-v3 pull request #2279
Opened 2021-03-03 20:33 UTC by ealsur

If Gateway is a hung state where the HttpRequestException only happens after 60 seconds, the current Hot Path policy was only waiting up to 10 seconds and surfacing a RequestTimeout, and we could not apply the failover mechanics.

This only affected the hot path (address resolution or query plans) and not other Gateway calls.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

2021-03-03 21:23 UTC, j82w commented on Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicyControlPlaneRetriableHotPath.cs
>              (TimeSpan.FromSeconds(10), TimeSpan.Zero),
Should the 10 second just be converted to 65 seconds? I'm just thinking if it didn't resolve in 5 seconds I doubt the 10 seconds will work.

2021-03-03 21:42 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicyControlPlaneRetriableHotPath.cs
>              (TimeSpan.FromSeconds(10), TimeSpan.Zero),
Makes sense, done

2021-03-03 22:37 UTC, j82w approved these changes

2021-03-04 03:34 UTC, kirankumarkolli requested changes
Lets please wait merging this change.

Latency is also equally very important as well. 
May be we need to revisit basing all fail-over on just ReqeustException

2021-03-04 14:07 UTC, j82w commented
> Lets please wait merging this change.
> 
> Latency is also equally very important as well.
> May be we need to revisit basing all fail-over on just ReqeustException

@kirankumarkolli  I don't see any reason to block this PR. If it is decided that we want to revisit fail-over design it should be a separate PR after the current model is fixed.

2021-03-04 22:14 UTC, ealsur commented
I don't see how latency is involved here. We are already retrying 3 times, with .5, and 5 seconds, before the 65 seconds. If Gateway has a latency spike, it will be clear.
The 3 retries are to work around Gateway upgrades and try to reach other instances, not for latency (rather availability).

2021-03-09 16:30 UTC, kirankumarkolli approved these changes

2021-03-09 17:03 UTC, merged