Users/shkalsi/pending partition key delete header
Azure/azure-cosmos-dotnet-v3 pull request #2301
Opened 2021-03-12 06:58 UTC by Shaleen-Kalsi

# Added Pending PartitionKey Delete Header

## This PR includes changes to return PendingPartitionKeyDelete Header in Query Response. PendingPartitionKeyDelete indicates whether there is a pending PK Delete Registration at the time of the query. 

I have added PartitionKeyDeleteQueryHeaderTests which tests the following scenarios:
1. PendingPKDeleteHeaderFalseTest -> When there is no PK Delete in the system, header value should be false.
2. PendingPKDeleteHeaderTest -> After PK Delete is made, the query should have PendingPartitionKeyDelete value as true.
3. PendingPKDeleteHeaderMuliplePartitionTest
4. PendingPKDeleteHeaderFalseTest -> Verifies that after PK Delete is completed, the header in the query returns false.

## Type of change

- [] New feature (non-breaking change which adds functionality)
- [] This change requires a documentation update

2021-03-12 12:31 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Headers/Headers.cs
> +        public virtual string PendingPartitionKeyDelete
Can you please explain the user scenario here? Why does a user need to know this?

2021-03-12 12:33 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Headers/Headers.cs
> +        public virtual string PendingPartitionKeyDelete
Partition Key Delete isn't public or preview yet. Please make it internal or add the `if #INTERNAL` to make it public

2021-03-15 11:44 UTC, Shaleen-Kalsi commented on Microsoft.Azure.Cosmos/src/Headers/Headers.cs
> +        public virtual string PendingPartitionKeyDelete
The effects of Partition Key Delete operation may not show up immediately in case of certain queries, like count, where during an ongoing Partition Key Delete operation the results may not match the user expectation. This header will indicate whether the discrepancy in query results may be due to a pending Partition Key Delete operation.

2021-03-15 11:55 UTC, abhijitpai commented on Microsoft.Azure.Cosmos/src/Headers/Headers.cs
> +        public virtual string PendingPartitionKeyDelete
Should we call this PendingDeleteAllItemsByPartitionKeyOperations to match the API?

2021-03-15 12:01 UTC, abhijitpai commented on Microsoft.Azure.Cosmos/src/Headers/Headers.cs
> +        public virtual string PendingPartitionKeyDelete
This should be a bool, and we should add a comment, something like:
"Indicates whether there are in-progress operations which delete all items by partition key on the container. When there are such in-progress operations, query results with aggregates may return values that do not reflect the final state of data that will be reached after the completion of the operation."

2021-03-15 17:27 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/Aggregate/AggregateQueryPipelineStage.Client.cs
> +                bool pendingPKDelete = false;
> bool pendingPKDelete = false; [](start = 15, length = 30)

Why does this header need to be wired through the query stack? It can be passed as an additional header, since it doesn't need to be aggregated across pages nor is it part of the schema response.

2021-03-15 17:28 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryClientCore.cs
> +                        cosmosResponseMessage.Headers.PendingPartitionKeyDelete.Equals(bool.TrueString.ToLower()),
>bool.TrueString.ToLower() [](start = 87, length = 25)

This is going to cause an allocation every iteration.

2021-03-15 17:28 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryClientCore.cs
> +                        cosmosResponseMessage.Headers.PendingPartitionKeyDelete.Equals(bool.TrueString.ToLower()),
>PendingPartitionKeyDelete [](start = 54, length = 25)

If the header is not set, then it's going to cause a NRE.

2021-03-15 17:29 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Query/v3Query/QueryIterator.cs
>                  };
You need to do the same for readfeed and changefeed.

2021-03-15 17:30 UTC, bchong95 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/PartitionKeyDeleteQueryHeaderTests.cs
> +                true);
>true [](start = 16, length = 4)

named parameter for literals.

2021-03-15 17:30 UTC, bchong95 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/PartitionKeyDeleteQueryHeaderTests.cs
> +            string queryText = "select * from t where t.pk = '" + pKString + "'";
>"select * from t where t.pk = '" + pKString + "'" [](start = 31, length = 49)

Use string interpolation

2021-03-15 17:33 UTC, bchong95 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/PartitionKeyDeleteQueryHeaderTests.cs
> +            await containerInternal.DeleteAllItemsByPartitionKeyStreamAsync(partitionKey);
>await containerInternal.DeleteAllItemsByPartitionKeyStreamAsync(partitionKey); [](start = 12, length = 78)

Im confused why we allow this async method to return before the partition key delete operation finishes. How is the user supposed to know when it's complete besides running a random query?

2021-03-15 17:38 UTC, bchong95 requested changes
Please create a meeting to sync this design with Samer. Having the user check a random header on the query path is not an intuitive design. I think we should instead have the async call for "DeleteLogicalPartitionKeyAsync" not yield until the partition key is fully deleted. This way there is no ambiguity on the user's end.

2021-03-15 17:46 UTC, bchong95 commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/Aggregate/AggregateQueryPipelineStage.Client.cs
> +                    pendingPKDelete |= sourcePage.PendingPKDelete;
This also doesn't tell us which partition key is being deleted.

2021-03-19 12:45 UTC, abhijitpai commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/PartitionKeyDeleteQueryHeaderTests.cs
> +            await containerInternal.DeleteAllItemsByPartitionKeyStreamAsync(partitionKey);
@bchong95, this is very much discussed with @sboshra. User is not supposed to run the query to find if the PK delete is complete - the operation is supposed to be fire and forget because that is what customers want - this is just helping users to know that their query results maybe affected by in-progress PK deletes.

2021-03-19 12:45 UTC, abhijitpai commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/Aggregate/AggregateQueryPipelineStage.Client.cs
> +                    pendingPKDelete |= sourcePage.PendingPKDelete;
Again, that's not the intent. It is just trying to indicate query results maybe affected due to in-progress partition key delete operations.

2021-03-19 14:02 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Headers/Headers.cs
> +        public virtual string PendingPartitionKeyDelete
Can we please have a separate Teams call to go over the design and approach. If my understanding is correct here - and we basically inconsistent query results because we aren't able to delete logical partitions atomically than I would question whether not supporting the former is the more transparent and better approach. How would a customer reasonably react to this flag being true?

2021-03-19 14:05 UTC, FabianMeiswinkel requested changes
I don't understand why we believe the PKPending Delete flag/header would make the user experience in this scenario acceptable. How would a customer react when seeing that header? Can we please have a separate meeting/Teams call to go over the design, why the design decision to accept inconsistent results temporarily was made etc.? To me this looks like a potential CRI arm - I might be missing something but believe going through it in-person vs. a code review would be more efficient.

2021-03-19 17:35 UTC, bchong95 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/PartitionKeyDeleteQueryHeaderTests.cs
> +            await containerInternal.DeleteAllItemsByPartitionKeyStreamAsync(partitionKey);
let's have a quick sync on this. I think we can find a solution that works well for both of us. Right now I am thinking of having the operation block until the pk is fully deleted and if the user wants to fire and forget, then they can fire and forget the task itself.

2021-03-19 18:03 UTC, abhijitpai commented on Microsoft.Azure.Cosmos/src/Headers/Headers.cs
> +        public virtual string PendingPartitionKeyDelete
@FabianMeiswinkel the inconsistency is not that customers will see some subset of docs in the PK; it's that **aggregate** queries (which don't return document contents, but say just counts) may not show the full effect of the delete of partition key being complete.

This PR is actually coming out of the previous meeting with the SDK team where we walked through the design and approach and the feedback was to inform the customer of this inconsistency in some such way. The customer for eg. would know that the count is approximate - say a search result can say 'about x results' instead of 'x results' and then give a paginated read feed where they consider the read feed may end sooner than x is reached even if no other writes happened in that time duration from the customer.

2021-03-25 05:21 UTC, Shaleen-Kalsi commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/Aggregate/AggregateQueryPipelineStage.Client.cs
> +                bool pendingPKDelete = false;
This header does need to be aggregated across partitions in case of cross partition queries

2021-12-08 07:38 UTC, closed without merging