Add null handling
Azure/azure-cosmos-dotnet-v3 pull request #2310
Opened 2021-03-15 22:12 UTC by bemill

# Pull Request Template

## Description

Fixes null handling of Annotation in Indexing Policy

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #IssueNumber

2021-03-15 22:21 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Resource/Settings/IndexingPolicy.cs
> +        [JsonProperty(PropertyName = "annotation", NullValueHandling = NullValueHandling.Ignore)]
Please add a test.

2021-03-15 22:37 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Settings/IndexingPolicy.cs
> +        [JsonProperty(PropertyName = "annotation", NullValueHandling = NullValueHandling.Ignore)]
There are serialization tests in the UT project

2021-03-15 22:54 UTC, bemill commented on Microsoft.Azure.Cosmos/src/Resource/Settings/IndexingPolicy.cs
> +        [JsonProperty(PropertyName = "annotation", NullValueHandling = NullValueHandling.Ignore)]
This feature relies on a recent backend change that also requires an account config to be set.  Is this possible to test with the existing frameworks?

2021-03-16 00:51 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Resource/Settings/IndexingPolicy.cs
> +        [JsonProperty(PropertyName = "annotation", NullValueHandling = NullValueHandling.Ignore)]
@ealsur  the issue is none of our UT run with the Internal flag enabled from what I can tell. Since this is only used in compute the tests can be added in that project.

2021-03-16 01:17 UTC, j82w approved these changes

2021-03-16 08:34 UTC, FabianMeiswinkel requested changes
Please also add a unit test reproducing the serialization error you are seeing right now as a mechanism to avoid regressions in the future.

2021-03-16 12:07 UTC, FabianMeiswinkel approved these changes
Discussed offline with @Jake Willey (COSMOS DB) – he explained the reasoning for not having a serialization/derserialization unit test (property is only available if INTERNAL compiler switch is set – any testing would need to happen in Compute).

2021-03-16 12:09 UTC, merged