Diagnostics: Adds Gateway Request Stats
Azure/azure-cosmos-dotnet-v3 pull request #2324
Opened 2021-03-19 17:03 UTC by asketagarwal

# Pull Request Template

2021-03-19 17:30 UTC, j82w commented on Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClient.cs
> +            IClientSideRequestStatistics clientSideRequestStatistics,
Please remove the ITrace implementation. It is no longer needed with clientSideRequestStatistics. Everywhere is currently passing in a noop trace anyways.

2021-03-22 10:39 UTC, asketagarwal commented on Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClient.cs
> +            IClientSideRequestStatistics clientSideRequestStatistics,
done

2021-03-22 11:43 UTC, j82w commented on Microsoft.Azure.Cosmos/src/GatewayAccountReader.cs
> +                clientSideRequestStatistics: null,
We need to either track these or wire the contract through.

2021-03-22 12:05 UTC, j82w commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/GatewayClientSideRequestStats.cs
> +        public async Task GatewayRetryRequestStatsTest()
Please add a test that verifies that if the Container Properties, PK ranges, Addresses caches hits a Timeout or HttpRequestException that is logged. You can probably use roughly the same test, but just use a DataRow to pass which call to throw the exception on.

2021-03-22 12:05 UTC, j82w commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/GatewayClientSideRequestStats.cs
> +        private class TimeOutHttpClientHandler : DelegatingHandler
nit: You probably could of used HttpClientHandlerHelper

2021-03-22 12:10 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientSideRequestStatisticsTraceDatum.cs
> +            this.HttpResponseStatisticsList.Add(new HttpResponseStatistics(requestStartTimeUtc,
To be on the safe side there should be a lock to make it thread safe.

2021-03-22 16:03 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
> +                                if (isOutOfRetries || !timeoutPolicy.IsSafeToRetry(requestMessage.Method))
Would we have any policy that retries on an HttpRequestException? That would block any ClientRetryPolicy logic, right?

2021-03-22 16:06 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientSideRequestStatisticsTraceDatum.cs
> +        public sealed class HttpResponseStatistics
What is the benefit of it being a struct? The object itself is not really small (it has an Exception that can have a large stack trace)

2021-03-22 19:48 UTC, asketagarwal commented on Microsoft.Azure.Cosmos/src/GatewayStoreClient.cs
> +                clientSideRequestStatistics: clientSideRequestStatistics);
fixed

2021-03-22 19:48 UTC, asketagarwal commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientSideRequestStatisticsTraceDatum.cs
> +            if (!this.RequestEndTimeUtc.HasValue || requestEndTimeUtc > this.RequestEndTimeUtc)
fixed

2021-03-22 20:36 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientSideRequestStatisticsTraceDatum.cs
> +        public sealed class HttpResponseStatistics
Struct go on the stack which avoids heap allocaitons.

2021-03-22 20:51 UTC, j82w commented on Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
> +                                if (isOutOfRetries || !timeoutPolicy.IsSafeToRetry(requestMessage.Method))
The retry policy will retry on HttpRequestException. It will only retry 3 times and then throw the exception. Based on the recent testing it will only hit the HttpRequestException on the last retry. The first 2 retries will hit operation cancelled exception. If this is an issue it needs to be addressed in a separate PR.

2021-03-22 23:25 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Handler/TransportHandler.cs
> +                                                            message: "GatewayStoreClient Request Timeout",
nit: Remove the GatewayStoreClient. It's possible that something in the clients can cause this.

2021-03-23 15:19 UTC, kirankumarkolli commented
Do the address resolution statics cover these?

2021-03-23 15:34 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
> -            ITrace trace,
When to use ITrace vs IClientSideRequestStatistics?

2021-03-23 19:24 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Routing/ClientCollectionCache.cs
> +                                if (clientSideRequestStatistics == null)
Move this to line 87 right after is created. If the storeModel throws an exception it won't record the clientSideRequestStatistics.

2021-03-23 20:23 UTC, asketagarwal commented on Microsoft.Azure.Cosmos/src/Routing/ClientCollectionCache.cs
> +                                if (clientSideRequestStatistics == null)
fixed

2021-03-23 21:14 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientSideRequestStatisticsTraceDatum.cs
> +        public sealed class HttpResponseStatistics
Right, but if the object is large, wouldn't that be detrimental? https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/choosing-between-class-and-struct

![image](https://user-images.githubusercontent.com/1633401/112219298-081e3800-8be2-11eb-85d6-a4de312150b3.png)

2021-03-23 21:19 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientSideRequestStatisticsTraceDatum.cs
> +        public sealed class HttpResponseStatistics
HttpResponseStatistics only has 8 properties, but I guess if each one is 4 bytes then it will be 32 bytes which is over the recommended size.

2021-03-23 21:53 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
> +                clientSideRequestStatistics);
nit: parameter order, cancellation should be last

2021-03-23 21:53 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
> +            IClientSideRequestStatistics clientSideRequestStatistics)
parameter order

2021-03-23 21:53 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
> +                                if (isOutOfRetries || !timeoutPolicy.IsSafeToRetry(requestMessage.Method))
Ack. I would prefer no retry mechanism on HttpRequestException, unless we understand the nature of it and think it's transient. Can be addressed on another PR tracked by another issue.

2021-03-23 21:53 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
> -                    using (ITrace delayTrace = trace.StartChild("Retry Delay", TraceComponent.Transport, Tracing.TraceLevel.Info))
nit: If we have the `datum` available, can we add that information there?

2021-03-23 21:53 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Routing/PartitionKeyRangeCache.cs
> +                            DocumentServiceResponse response = await this.storeModel.ProcessMessageAsync(request);
nit: not needed?

2021-03-23 21:53 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Tracing/TraceWriter.TraceJsonWriter.cs
> +                    jsonWriter.WriteStringValue(stat.Exception.Message);
If it worth instead capturing the ToString instead of the Message? Or the stack trace?

2021-03-23 21:53 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/GatewayClientSideRequestStats.cs
> +    public class GatewayClientSideRequestStats
nit: `GatewayClientSideRequestStatsTests`

2021-03-24 06:32 UTC, asketagarwal commented on Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
> -                    using (ITrace delayTrace = trace.StartChild("Retry Delay", TraceComponent.Transport, Tracing.TraceLevel.Info))
that will be captured and figured out if we see the RequestStartTime of each retry.

2021-03-24 06:43 UTC, asketagarwal commented on Microsoft.Azure.Cosmos/src/Tracing/TraceWriter.TraceJsonWriter.cs
> +                    jsonWriter.WriteStringValue(stat.Exception.Message);
Is the size a concern? Stack trace and tostring which also prints the stack trace can be very large.

2021-03-30 17:19 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Tracing/TraceWriter.TraceJsonWriter.cs
> +                    jsonWriter.WriteStringValue(stat.Exception.Message);
Not the size, but rather, would we have enough troubleshooting information just from the message

2021-04-16 21:28 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/TraceWriter.TraceJsonWriter.cs
> +                    jsonWriter.WriteStringValue(stat.Exception.Message);
This will only include exception thrown by the HttpClient so I think it will be ok to just record the message. The Trace structure will let us know where it was thrown from.

2021-04-16 21:28 UTC, j82w submitted a review, later dismissed

2021-04-19 21:10 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Handler/TransportHandler.cs
> +                                                            message: ex.Data?["Message"].ToString(),
Why not just ex.Message?

2021-04-21 14:29 UTC, kirankumarkolli requested changes
Please verify that there is no perf impact in steady state.

2021-04-23 11:39 UTC, j82w commented
> Please verify that there is no perf impact in steady state.

I verified the perf shows no changes in steady state.

2021-04-23 11:46 UTC, merged