Change Feed: Fixes pull model request count for NotModified scenario
Azure/azure-cosmos-dotnet-v3 pull request #2405
Opened 2021-04-20 18:41 UTC by ealsur

## Expectation

Assuming a FeedRange that spans multiple partitions/EPK ranges, for example, EPK Range 1, 2, and 3.

Change Feed pull model logic when receiving a NotModified should be:

1. Received 304 (NotModified) on EPK Range 1.
2. Check EPK Range 2, if received 304 (NotModified), then:
3. Check EPK Range 3, if received 304 (NotModified) then:
4. Return 304 (NotModified) to the user, since we tested all ranges and all are returning 304.

If the FeedRange spans a single partition/EPK range, for example, EPK Range 1.

Change Feed pull model logic when receiving a NotModified should be:

1. Received 304 (NotModified) on EPK Range 1.
4. Return 304 (NotModified) to the user, since the FeedRange does not span more ranges.

## Current behavior

The current behavior is doing one extra request, that on the case of FeedRanges that span a single partition/EPK range, causes a 2x increase in number of requests.

Using the previous example, if the FeedRange spans EPK Range 1, 2, and 3, Change Feed pull model is doing:

1. Received 304 (NotModified) on EPK Range 1.
2. Check EPK Range 2, if received 304 (NotModified), then:
3. Check EPK Range 3, if received 304 (NotModified) then:
3. Check EPK Range 1, if received 304 (NotModified) then:
4. Return 304 (NotModified) to the user, since the last EPK Range matches the initial that returned 304.

If the FeedRange spans a single partition/EPK range, for example, EPK Range 1:

1. Received 304 (NotModified) on EPK Range 1.
3. Check EPK Range 1 again, if received 304 (NotModified) then:
4. Return 304 (NotModified) to the user, since the last EPK Range matches the initial that returned 304.

## Logical fix

To solve it, we are now tracking the current EPK Range and the Next one (the one that would be read in the MoveNext) in the `CrossPartitionRangePageAsyncEnumerator`.

And doing 2 optimizations:

1. When getting a 304, if the Current range is the same as the Next range, it means the FeedRange spans 1 EPK Range, do nothing and return the 304. This reduces the number of requests to 1 on this scenario.
2. Call MoveNext on the Enumerator until the Next matches the initial one that received the first 304. This avoids the repeat on the scenario where the FeedRange spans multiple EPK ranges.

The PR contains tests to cover the logic and also updates the Contract tests to match what internal teams are actually really doing, the Contract tests got modified on previous PRs and diverged from what they were meant to cover.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

2021-04-20 20:48 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Pagination/CrossPartitionRangePageAsyncEnumerator.cs
> +        public FeedRangeInternal NextRange { get; private set; }
Current and next semantics are really cumbersome. With iterators it even unclear what the expected semantics are. 

Try with CurrentRange seems a good contract.

2021-04-20 20:52 UTC, kirankumarkolli requested changes
Older Async enumerator contract seems reasonable. 
Current/Next model is ambiguous and leads to mis-interpretations. 

Can the looping be hardened with the current enumerator contract?

2021-04-20 20:52 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Pagination/CrossPartitionRangePageAsyncEnumerator.cs
> +        public FeedRangeInternal NextRange { get; private set; }
The problem is CurrentRange only points at the range that was last read and what we need to do is avoid the next read based on the fact that it would land on the initial range that produced the first 304.
I tried just using CurrentRange, but it yields the current problem, you need to do a request to get it, the Enumerator APIs do not expose what are the underlying items in the enumerator, so the caller cannot me the decision.

2021-04-20 20:54 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Pagination/CrossPartitionRangePageAsyncEnumerator.cs
> +        public FeedRangeInternal NextRange { get; private set; }
Also the current contract does not map to the IAsyncEnumerator API, CurrentRange is not part of it, so we are not using that API anyway.

2021-04-20 20:55 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Pagination/CrossPartitionRangePageAsyncEnumerator.cs
> +        public FeedRangeInternal NextRange { get; private set; }
The API surface used to communicate between the Enumerators is `CrossPartitionRangePageAsyncEnumerator`, not `IAsyncEnumerator`

2021-04-21 18:52 UTC, FabianMeiswinkel submitted a review, later dismissed
LGTM

2021-04-22 13:41 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Pagination/CrossPartitionRangePageAsyncEnumerator.cs
> +        public FeedRangeInternal NextRange { get; private set; }
Instead of exposing the new API could we use ChangeFeedState to signal that it reached the end ranges?

2021-04-22 14:07 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Pagination/CrossPartitionRangePageAsyncEnumerator.cs
> +        public FeedRangeInternal NextRange { get; private set; }
There are 2 options:
* Either we have a Current + MoveNext(out Next): This is not possible because async methods cannot have out parameters
* We extend adding a Next pointer

Given that the first one is technically not possible, I only see the second one as the alternative and that's why I choose it

2021-04-22 16:38 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Pagination/CrossPartitionRangePageAsyncEnumerator.cs
> +        public FeedRangeInternal NextRange { get; private set; }
> Instead of exposing the new API could we use ChangeFeedState to signal that it reached the end ranges? The caller can makes a decision based on the state?

ChangeFeedState only contains information required for 1 range (continuation, etc). Adding information about the Next range would create a dependency between states, creating a linked list that needs to also need to be updated on splits. It is a much complex solution IMO and adds information that the ChangeFeedState really doesn't need. This is a communication between Enumerators.

2021-04-23 12:13 UTC, j82w commented on Microsoft.Azure.Cosmos/src/ChangeFeed/Pagination/CrossPartitionChangeFeedAsyncEnumerator.cs
> +                    if (!originalRange.Equals(nextRange))
What happens if there is a split between the operations meaning the original range no longer exists?

2021-04-23 13:40 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/ChangeFeed/Pagination/CrossPartitionChangeFeedAsyncEnumerator.cs
> +                    if (!originalRange.Equals(nextRange))
Good call. the previous logic was using the `Min` range to compare while this one uses Equal, I'll change it to match the previous one. Comparing by `Min` is split proof because even if the range splits, the first child will always start as the parent.

2021-04-23 13:44 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/ChangeFeed/Pagination/CrossPartitionChangeFeedAsyncEnumerator.cs
> +                    if (!originalRange.Equals(nextRange))
So assume I have ranges 1, 2, and 3.

1. I read 1, get a 304. Right after, 1 splits, but the client won't know.
2. I read 2, get 304.
3. I read 3, get 304. The next would be 1, it stops.

There was no split detection involved so the comparison would be still valid.

2021-04-23 17:15 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Pagination/CrossPartitionRangePageAsyncEnumerator.cs
> +        public FeedRangeInternal NextRange { get; private set; }
After offline discussion: Moved to a TryPeekNext API definition

2021-04-23 17:18 UTC, j82w approved these changes

2021-04-23 17:26 UTC, kirankumarkolli approved these changes

2021-04-23 17:37 UTC, merged