PopulateAnalyticalMigrationProgress for Synapse link migration preview
Azure/azure-cosmos-dotnet-v3 pull request #2468
Opened 2021-05-14 19:48 UTC by armaansood

# Pull Request Template

## Description

Added PopulateAnalyticalMigrationProgress to ContainerRequestOptions, which populates the HTTP header "x-ms-cosmos-populate-analytical-migration-progress". When this header is provided on collection reads, the response header "x-ms-cosmos-analytical-migration-progress" will contain an integer representing the percentage progress of analytical store migration (Synapse link migration). This header will be -1 for containers that haven't used analytical store migration and 100 for containers that are ready to be queried by Synapse link connectors (Spark/SQL OD).

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

2021-05-14 19:51 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/RequestOptions/ContainerRequestOptions.cs
> +        /// PopulateAnalyticalMigrationProgress is used to enable/disable getting analytical migration progress for document collection read requests.
```suggestion
        /// PopulateAnalyticalMigrationProgress is used to enable/disable getting analytical migration progress for container read requests.
```

2021-05-14 19:51 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +            //if (options.PopulateAnalyticalMigrationProgress)
undo?

2021-05-14 19:52 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/RequestOptions/ContainerRequestOptions.cs
> +            if (this.PopulateAnalyticalMigrationProgress)
Add tests

2021-05-14 20:50 UTC, j82w commented on Microsoft.Azure.Cosmos/src/RequestOptions/ContainerRequestOptions.cs
> +        ///  Gets or sets the <see cref="PopulateAnalyticalMigrationProgress"/> for document collection read requests in the Azure Cosmos DB service.
Why is this not always set to true? Just return the header when it is in progress?

2021-05-14 20:50 UTC, j82w commented on Microsoft.Azure.Cosmos/src/RequestOptions/ContainerRequestOptions.cs
> +        bool PopulateAnalyticalMigrationProgress { get; set; }
Should it be added to the Headers to make it easier to access the response? Seems unreasonable to expect users to know the header string.

2021-05-14 21:18 UTC, armaansood commented on Microsoft.Azure.Cosmos/src/RequestOptions/ContainerRequestOptions.cs
> +        ///  Gets or sets the <see cref="PopulateAnalyticalMigrationProgress"/> for document collection read requests in the Azure Cosmos DB service.
It's not always set to true because it is a fanout operation. We check every partition for the progress and take the minimum, like PopulateQuotaInfo with reindexer progress. This puts pressure on the backend. Also, the only way to know if migration is in progress is by checking each partition on the backend, or by reading each root segment's hybrid row file.

2021-05-14 21:22 UTC, armaansood commented on Microsoft.Azure.Cosmos/src/RequestOptions/ContainerRequestOptions.cs
> +        bool PopulateAnalyticalMigrationProgress { get; set; }
Can you point me to this? I couldn't find anything like this for x-ms-documentdb-collection-index-transformation-progress, which is similar to x-ms-cosmos-analytical-migration-progress.

In the V2 SDK, we could do `container.IndexTransformationProgress` but in the V3 SDK, my impression is that the only way to get the index transformation progress is by doing `long.Parse(containerResponse.Headers["x-ms-documentdb-collection-index-transformation-progress"])`.

2021-05-14 22:17 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/RequestOptions/ContainerRequestOptions.cs
> +        bool PopulateAnalyticalMigrationProgress { get; set; }
Update the contract file by running `.\UpdateContracts.ps1` on the repo root

2021-05-14 23:17 UTC, krishnan1985 commented
> {

curious, what's the utility of this json file?

---
Refers to: Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json:1 in 6090ef1. [](commit_id = 6090ef19178d9c9cbce3f6650b28aef093478805, deletion_comment = False)

2021-05-14 23:18 UTC, krishnan1985 commented
> <Results>

no change?

---
Refers to: Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/TraceWriterBaselineTests.ScenariosAsync.xml:1 in 6090ef1. [](commit_id = 6090ef19178d9c9cbce3f6650b28aef093478805, deletion_comment = False)

2021-05-14 23:18 UTC, krishnan1985 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
> +            ContainerRequestOptions requestOptions = new ContainerRequestOptions
do we need one sanity test with migration?

2021-05-14 23:18 UTC, krishnan1985 approved these changes
:shipit:

2021-05-14 23:53 UTC, armaansood commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
> +            ContainerRequestOptions requestOptions = new ContainerRequestOptions
I don't think I can do that right now since migration is not enabled by default on the emulator.

2021-05-15 03:13 UTC, armaansood commented on Microsoft.Azure.Cosmos/src/RequestOptions/ContainerRequestOptions.cs
> +            if (this.PopulateAnalyticalMigrationProgress)
Hey @ealsur, I added a test, but it fails because the version of the emulator used is out of date with the backend that supports analytical migration progress.

2021-05-17 18:18 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
> +            ContainerRequestOptions requestOptions = new ContainerRequestOptions
I wouldn't know, @milismsft would be the best person to answer

2021-05-17 18:47 UTC, j82w commented on Microsoft.Azure.Cosmos/src/RequestOptions/ContainerRequestOptions.cs
> +        ///  Gets or sets the <see cref="PopulateAnalyticalMigrationProgress"/> for document collection read requests in the Azure Cosmos DB service.
What is the use case for this? This seems like a one time operation that can't even be enabled from the SDK so why would they need to monitor the progress of this one time operation inside the SDK?

2021-05-17 19:36 UTC, armaansood commented on Microsoft.Azure.Cosmos/src/RequestOptions/ContainerRequestOptions.cs
> +        ///  Gets or sets the <see cref="PopulateAnalyticalMigrationProgress"/> for document collection read requests in the Azure Cosmos DB service.
This can be enabled from the SDK through a collection replace, similar to when you update the index policy and can see the re-indexing progress after a PopulateQuotaInfo request.

2021-05-17 21:14 UTC, FabianMeiswinkel commented
Is there a Design one-pager for this protocol change? I personally feel like this doesn't belong in the SDK but should be a management API in the resource-provider/ARM-SDK.
Having a One-Pager describing the design would also help to understand how we protect customers from abusing this (sounds like there is quite some backend overhead when setting it to true - are we charging higher RU charge to reflect that and prevent customers form always setting it to true etc.?) 
More information is also needed on how to read/parse/process the response - -1 and 100 is explained - I would assume intermediary states are percentages? But do we return the lowest percentage across all partitions or is it some kind of weighted average?

2021-05-17 21:14 UTC, FabianMeiswinkel requested changes
Is there a Design one-pager for this protocol change? I personally feel like this doesn't belong in the SDK but should be a management API in the resource-provider/ARM-SDK.
Having a One-Pager describing the design would also help to understand how we protect customers from abusing this (sounds like there is quite some backend overhead when setting it to true - are we charging higher RU charge to reflect that and prevent customers form always setting it to true etc.?)
More information is also needed on how to read/parse/process the response - -1 and 100 is explained - I would assume intermediary states are percentages? But do we return the lowest percentage across all partitions or is it some kind of weighted average?

2021-05-19 16:30 UTC, closed without merging