CosmosDiagnostics: Fixes a race condition causing InvalidOperationException
Azure/azure-cosmos-dotnet-v3 pull request #2516
Opened 2021-06-02 17:44 UTC by j82w

# Pull Request Template

## Description

Introduced in 3.17.0 PR #2097

This is a regression caused by making the ClientSideRequestStatisticsTraceDatum private fields to public. Previously these lists were protected by locks and when they were made public the locks were removed. This PR is adding the locks back and adding tests to ensure that if a background thread does update it while the list is being enumerated that it will not throw a InvalidOperationCancelledException.

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #IssueNumber

2021-06-02 18:20 UTC, ealsur approved these changes
LGTM, only left 2 questions.

2021-06-02 18:20 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientSideRequestStatisticsTraceDatum.cs
> +                lock (this.lockObject)
nit: Could this cause contention since it uses the same lock object as EndpointToAddressResolutionStatistics? Or maybe this was the way it was before and it had no side effects.

2021-06-02 18:20 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Tracing/TraceWriter.TraceJsonWriter.cs
> +                if (clientSideRequestStatisticsTraceDatum.HttpResponseStatisticsList.Any())
Would it make sense to expose something to avoid Linq? Not sure if the Any() has any perf impact

2021-06-02 18:24 UTC, neildsh commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientSideRequestStatisticsTraceDatum.cs
> +                lock (this.lockObject)
+1

2021-06-02 18:24 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientSideRequestStatisticsTraceDatum.cs
> +                lock (this.lockObject)
This is the way the v2 SDK is coded, and we have not had any complaints.

2021-06-02 18:25 UTC, neildsh submitted a review, later dismissed

2021-06-02 18:27 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/TraceWriter.TraceJsonWriter.cs
> +                if (clientSideRequestStatisticsTraceDatum.HttpResponseStatisticsList.Any())
The only way to avoid it would be to refactor all the code to no longer expose these properties like the v2 model. This would be a much larger and breaking change. It something we should look at but should be done in a separate PR.

2021-06-02 19:43 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientSideRequestStatisticsTraceDatum.cs
> +                lock (this.lockObject)
This is a terrible idea and is asking for dead-locks.

The yield will basically just generate a helper class. You are now keeping the lock until the helper class gets disposed (which could even happen on another thread where the lock was taken)

2021-06-02 19:43 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientSideRequestStatisticsTraceDatum.cs
> +                lock (this.lockObject)
Instead create a shallow copy under a lock

2021-06-02 19:44 UTC, FabianMeiswinkel requested changes
The yiel under a lock is not thread-safe and needs to be changed.

2021-06-02 20:36 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientSideRequestStatisticsTraceDatum.cs
> +                lock (this.lockObject)
Creating a shallow lock is going to add a lot of overhead and create a objects unnecessarily.

The only way the deadlock can happen is if someone is not disposing of the enumerator.  Which should be a pretty rare since everyone accessing the list is simply iterating the lists.

2021-06-03 01:23 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientSideRequestStatisticsTraceDatum.cs
> +                lock (this.lockObject)
The latest iteration now does a lazy shallow copy.

2021-06-03 01:26 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientSideRequestStatisticsTraceDatum.cs
> +                lock (this.lockObject)
Please take a look at the latest iteration. The locks have been modified to use the specific list. The lock object is now only used for the end time being updated.

2021-06-03 06:47 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientSideRequestStatisticsTraceDatum.cs
> +            List<T> shallowCopy = new List<T>(originalList.Count);
Unnecessary - you can just use return new List(originalList) - I assumed the motivation for the code here was because you thought the List(IEnumerable<T>) ctor would not create a List with the right capacity?

This optimization is baked in into the Framework - see https://github.com/dotnet/runtime/blob/df6da138702c76f19299627b1ee89837d16ed219/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/List.cs#L57-L91

So just using new List(originalList) is cleaner, simpler and provides the same benefits.

2021-06-03 06:49 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientSideRequestStatisticsTraceDatum.cs
> +            List<KeyValuePair<string, T>> shallowCopy = new List<KeyValuePair<string, T>>(originalDict.Count);
Same here - just return new Dictionary(originalDict) - optimizations are baked into the Framework as well

https://github.com/dotnet/runtime/blob/df6da138702c76f19299627b1ee89837d16ed219/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/Dictionary.cs#L77-L86

2021-06-03 06:59 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientSideRequestStatisticsTraceDatum.cs
> +            lock (this.storeResponseStatistics)
NIT - I find it a little confusing to use the storeResponseStatisticds instance as the lock object for "this" - i get why you are doing it but would personally prefer either using a dedicated this.lockObject to ensure single-threaded access here (.Net GC is good enough to deal with that single allocation :-)) or at least add a comment that the lock isn't to preserve thread-safety in storeResponseStatistics but instead it is used as an instance-level lock here.

2021-06-03 07:08 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientSideRequestStatisticsTraceDatum.cs
> +            lock (this.storeResponseStatistics)
Actually this.lockObject is still there - so doesn't it make sense to use that one instead here?

2021-06-03 07:12 UTC, FabianMeiswinkel submitted a review, later dismissed
Thanks Jake - LGTM now - except for minor comments on simplifying the shallow copy implementation

2021-06-03 11:56 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientSideRequestStatisticsTraceDatum.cs
> +            lock (this.storeResponseStatistics)
There are 3 separate lists. Modifying each list only takes a lock for the list being modified. The lockObject is used for updating the RequestEndTime which is done when modifying any of the 3 lists.

2021-06-03 14:09 UTC, ealsur submitted a review, later dismissed

2021-06-03 19:36 UTC, neildsh submitted a review, later dismissed

2021-06-03 19:52 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientSideRequestStatisticsTraceDatum.cs
> +            lock (this.storeResponseStatistics)
Yes - but you aren't touching the storeResponseStatistics list within this lock statement, correct? The lock only exists to basically do an instance to sequentially set lastTimestamp

2021-06-03 20:10 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientSideRequestStatisticsTraceDatum.cs
> +            lock (this.storeResponseStatistics)
Fixed in the latest iteration to actually take a lock on the recordRequestHashCodeToStartTime.

2021-06-03 20:22 UTC, FabianMeiswinkel approved these changes
LGTM now - Thanks Jake!

2021-06-03 21:05 UTC, merged