ClientSideRequestStatistics: Fixes NullReferenceException caused by RegionsContacted in IClientSideRequestStatistics
Azure/azure-cosmos-dotnet-v3 pull request #2562
Opened 2021-06-16 18:47 UTC by asketagarwal

Issue introduced in #2312 

The original RegionsContacted hashset was never getting set so it is always null. There are certain service unavailable code paths that check if multiple regions were contacted. Since the hashset is never set it is null and causing the null reference exceptions.

2021-06-16 19:01 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientSideRequestStatisticsTraceDatum.cs
> +        private HashSet<Uri> contactedUris;
nit
```suggestion
        private HashSet<Uri> contactedUris = null;
```

2021-06-16 19:04 UTC, FabianMeiswinkel requested changes

2021-06-16 19:04 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientSideRequestStatisticsTraceDatum.cs
Sorry - I don't get this code. 
1) Why is it even needed - why do caller not use RegionsContactedWithName instead?
2) It isn't thread-safe. You need to acquire the same lock you use when modifying RegionsContactedWithName - otherwise the foreach over it is not thread-safe.
3) I assume you create separate HashSet to avoid doing the transformation over RegionsContactedByName every single time someone calls the property getter - on the other hand it always returned null so far - so there can't be that many callers? So why optimize for it now. And if you want to optimize for it with a separate dictionary - why not populate it at teh same time (under the same lock) as when you modify RegionsContactedWithName?

2021-06-16 19:09 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientSideRequestStatisticsTraceDatum.cs
The issue is the IClientSideRequestStats which is an interface with the HA layer. The v3 SDK implements it with ClientSideRequestStatisticsTraceDatum. Currently it is setting the RegionsContacted to null. The issue is a certain path in the [HA layer](https://msdata.visualstudio.com/CosmosDB/_git/CosmosDB?path=%2FProduct%2FMicrosoft.Azure.Documents%2FSharedFiles%2FGoneAndRetryWithRequestRetryPolicy.cs&version=GBmaster&line=183&lineEnd=184&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents) always assumes it is there. 

The plan is to mitigate the null reference exception by lazily loading the hashset for the one service unavailable exception that is using the old interface. In a separate PR in the msdata repo it will remove the old hashset and use the new one. 

The hashset is not thread safe and has been there for years. I don't see a reason to make it thread safe now. I agree in the future we should look at the thread safety of this a whole instead of trying to patch random properties.

2021-06-16 19:31 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Tracing/ContactedRegionsTests.cs
> +            ClientSideRequestStatisticsTraceDatum clientSideRequestStatistics = new ClientSideRequestStatisticsTraceDatum(DateTime.UtcNow);
Should we add a check with just the constructor and check that all APIs in the `IClientSideRequestStatistics` signature do not return `null`?

2021-06-16 19:31 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Tracing/ContactedRegionsTests.cs
> +            ClientSideRequestStatisticsTraceDatum clientSideRequestStatistics = new ClientSideRequestStatisticsTraceDatum(DateTime.UtcNow);
```
IClientSideRequestStatistics statistics = new ClientSideRequestStatisticsTraceDatum(DateTime.UtcNow);
```

And then call all methods in the interface asserting they don't return `null`?

2021-06-16 19:37 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientSideRequestStatisticsTraceDatum.cs
Jake and I chatted about it in a call. I think the best way forward is to get rid of the optimization attempts and just do a 

get 
{
    return new HashSet<Uri>(this.RegionsContactedWithName.Values);
}

2021-06-16 21:32 UTC, j82w commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Tracing/ContactedRegionsTests.cs
> +        public void ContactedRegionsWithoutNameTest()
The following test can be used to do validate  the fix:

```c#
[TestMethod]
        public async Task CreateDropItemTest()
        {
            bool throwTransportException = false;
            int count = 0;
            CosmosClient client = new CosmosClient("https://cosmosdbdotnetperf.documents.azure.com:443/",
                "",
                new CosmosClientOptions()
                {
                    TransportClientHandlerFactory = (x) =>
                        new TransportClientWrapper(client: x, interceptor: (uri, resource, dsr) =>
                        {
                            if (throwTransportException && count++ < 5)
                            {
                                throw TransportExceptions.GetGoneException(
                                 new Uri("https://localhost:8081"), Guid.NewGuid(), new TransportException(
                                    TransportErrorCode.RequestTimeout,
                                    null,
                                    Guid.NewGuid(),
                                    new Uri("https://localhost:8081"),
                                    "Test",
                                    true,
                                    true));
                            }

                            if(throwTransportException && count >= 5)
                            {
                                throw new NullReferenceException("Testing one two three");
                            }
                        })
                });

            Container testContainer = client.GetContainer("testdb", "temp");
            ToDoActivity testItem = ToDoActivity.CreateRandomToDoActivity();
            ItemResponse<ToDoActivity> response = await testContainer.CreateItemAsync<ToDoActivity>(item: testItem);
            Assert.IsNotNull(response);
            Assert.IsNotNull(response.Resource);
            Assert.IsNotNull(response.Diagnostics);
            Assert.IsTrue(!string.IsNullOrEmpty(response.Diagnostics.ToString()));
            Assert.IsTrue(response.Diagnostics.GetClientElapsedTime() > TimeSpan.Zero);

            response = await testContainer.ReadItemAsync<ToDoActivity>(testItem.id, new Cosmos.PartitionKey(testItem.pk));
            Assert.IsNotNull(response);
            Assert.IsNotNull(response.Resource);
            Assert.IsNotNull(response.Diagnostics);
            Assert.IsTrue(!string.IsNullOrEmpty(response.Diagnostics.ToString()));
            Assert.IsTrue(response.Diagnostics.GetClientElapsedTime() > TimeSpan.Zero);

            throwTransportException = true;
            try
            {
                response = await testContainer.ReadItemAsync<ToDoActivity>(testItem.id, new Cosmos.PartitionKey(testItem.pk));
                Assert.IsNotNull(response);
                Assert.IsNotNull(response.Resource);
                Assert.IsNotNull(response.Diagnostics);
                Assert.IsTrue(!string.IsNullOrEmpty(response.Diagnostics.ToString()));
                Assert.IsTrue(response.Diagnostics.GetClientElapsedTime() > TimeSpan.Zero);
            }
            catch (CosmosException e)
            {
                string m = e.ToString();
                Console.WriteLine(m);
            }
            catch (NullReferenceException e)
            {
                string m = e.ToString();
                Console.WriteLine(m);
            }
            catch (Exception e)
            {
                string m = e.ToString();
                Console.WriteLine(m);
            }


            Assert.IsNotNull(response.Headers.GetHeaderValue<string>(Documents.HttpConstants.HttpHeaders.MaxResourceQuota));
            Assert.IsNotNull(response.Headers.GetHeaderValue<string>(Documents.HttpConstants.HttpHeaders.CurrentResourceQuotaUsage));
            ItemResponse<ToDoActivity> deleteResponse = await testContainer.DeleteItemAsync<ToDoActivity>(partitionKey: new Cosmos.PartitionKey(testItem.pk), id: testItem.id);
            Assert.IsNotNull(deleteResponse);
            Assert.IsNotNull(response.Diagnostics);
            Assert.IsTrue(!string.IsNullOrEmpty(response.Diagnostics.ToString()));
            Assert.IsTrue(response.Diagnostics.GetClientElapsedTime() > TimeSpan.Zero);
        }
```

2021-06-17 15:03 UTC, j82w commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
> +            catch (NullReferenceException)
nit: Remove the catch and just let the test fail with the null ref. Currently it will lose the original null ref info.

2021-06-17 15:04 UTC, j82w commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
> +            catch (CosmosException ex)
when (ex.StatusCode == HttpStatusCode.ServiceUnavailable)
{
    // check that the original null ref exception is still in the exception.
}

2021-06-17 16:42 UTC, FabianMeiswinkel approved these changes
LGTM now...

2021-06-17 17:08 UTC, j82w approved these changes

2021-06-17 17:09 UTC, merged