added a new scenario for Change feed pull
Azure/azure-cosmos-dotnet-v3 pull request #2605
Opened 2021-07-09 22:24 UTC by jenglish81

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Include samples if adding new API, and include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #IssueNumber

2021-07-09 22:52 UTC, ealsur requested changes

2021-07-09 22:52 UTC, ealsur commented on .vscode/launch.json
> +{
delete this file

2021-07-09 22:52 UTC, ealsur commented on .vscode/tasks.json
> +{
delete this file

2021-07-09 22:52 UTC, ealsur commented on Microsoft.Azure.Cosmos.Samples/Tools/CTL/.vscode/launch.json
> +{
delete this file

2021-07-09 22:52 UTC, ealsur commented on Microsoft.Azure.Cosmos.Samples/Tools/CTL/.vscode/tasks.json
> +{
delete this file

2021-07-09 22:52 UTC, ealsur commented on Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ChangeFeedPullScenario.cs
> +    using Newtonsoft.Json;
Make sure you are using all the usings, if there are any not used, please remove it

2021-07-09 22:52 UTC, ealsur commented on Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ChangeFeedPullScenario.cs
> +            //Repeat the loop of creating a new Change Feed Iterator and all the steps until the run-time is completed.
remove comment

2021-07-09 22:52 UTC, ealsur commented on Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ChangeFeedPullScenario.cs
> +            Stopwatch stopWatch = new Stopwatch();
can be simplified:
```suggestion
            Stopwatch stopWatch = Stopwatch.StartNew();
```

And remove the Start line below

2021-07-09 22:52 UTC, ealsur commented on Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ChangeFeedPullScenario.cs
> +                        //Call ReadNextAsync on the iterator
Remove comment

2021-07-09 22:52 UTC, ealsur commented on Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ChangeFeedPullScenario.cs
> +                        //If there are new documents in the response, count them in a variable
Remove comment

2021-07-09 22:52 UTC, ealsur commented on Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ChangeFeedPullScenario.cs
> +                        //If there are no new changes, stop/break out of the iterator.
Remove comment

2021-07-09 22:52 UTC, ealsur commented on Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ChangeFeedPullScenario.cs
> +            while(stopWatch.Elapsed <= config.RunningTimeDurationAsTimespan)
indenting and spacing. If you open this in VS Code, I think you can use the Format File command. If you open it in VS, saving the file or adding new lines might do the trick.

For example, there needs to be an space between `while` and `(`

2021-07-09 22:52 UTC, ealsur commented on Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ChangeFeedPullScenario.cs
> +                    if(config.PreCreatedDocuments == documentTotal)
```suggestion
                    if (config.PreCreatedDocuments == documentTotal) 
```

2021-07-09 22:52 UTC, ealsur commented on Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ChangeFeedPullScenario.cs
> +                    if(config.PreCreatedDocuments == documentTotal)
new line after `}`

2021-07-09 22:52 UTC, ealsur commented on Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ChangeFeedPullScenario.cs
> +                        logger.LogInformation("Suceess: The number of new documents match the number of pre-created documents");
```suggestion
                        logger.LogInformation($"Success: The number of new documents match the number of pre-created documents {config.PreCreatedDocuments}");
```

2021-07-09 22:52 UTC, ealsur commented on Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ChangeFeedPullScenario.cs
> +                    //Compare the detected changes vs the prepopulated ones and if they don't match, log a warning with a text showing the 2 values and also log the
Remove comments

2021-07-09 22:52 UTC, ealsur commented on Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ChangeFeedPullScenario.cs
> +                        logger.LogError("The prepopulated documents and the new documents don't match.  Preconfigured Docs =" + config.PreCreatedDocuments + ", New Documents = "+ documentTotal);
Can be simplified with `$`:

```suggestion
                        logger.LogError($"The prepopulated documents and the new documents don't match.  Preconfigured Docs = {config.PreCreatedDocuments}, New Documents {documentTotal}");
```

2021-07-09 22:52 UTC, ealsur commented on Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ChangeFeedPullScenario.cs
> +                    //If there are any Exceptions in the loop (try/catch), log the errors
delete comment

2021-07-09 22:52 UTC, ealsur commented on Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ChangeFeedPullScenario.cs
> +            stopWatch.Stop();
new line after `}`

2021-07-09 22:52 UTC, ealsur commented on Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ChangeFeedPullScenario.cs
> +        internal class Range
this class is not used

2021-07-09 22:52 UTC, ealsur commented on Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ChangeFeedPullScenario.cs
> +        internal class LeaseSchema
this class is not used

2021-07-09 22:52 UTC, ealsur commented on Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ChangeFeedPullScenario.cs
> +        internal class FeedRange
this class is not used

2021-07-09 22:52 UTC, ealsur commented on Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ChangeFeedPullScenario.cs
> +        private class SimpleItem
This class is not used

2021-07-12 14:35 UTC, ealsur commented on Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ChangeFeedPullScenario.cs
> +            stopWatch.Start();
Remove the Start, it is not needed.

2021-07-12 14:35 UTC, ealsur commented on Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ChangeFeedPullScenario.cs
> +
remove empty line

2021-07-12 14:35 UTC, ealsur commented on Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ChangeFeedPullScenario.cs
> +
remove empty line

2021-07-12 14:37 UTC, ealsur commented on Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ChangeFeedPullScenario.cs
> +                        logger.LogInformation($"Suceess: The number of new documents match the number of pre-created documents: {config.PreCreatedDocuments}");
```suggestion
                        logger.LogInformation($"Success: The number of new documents match the number of pre-created documents: {config.PreCreatedDocuments}");
```

2021-07-12 14:38 UTC, ealsur commented
/azp run

2021-07-12 14:39 UTC, ealsur commented on Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ChangeFeedPullScenario.cs
> +                    if (config.PreCreatedDocuments == documentTotal)
new line between the `}` and `if`

2021-07-12 14:58 UTC, ealsur commented on Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ChangeFeedPullScenario.cs
> +
remove empty lines between usings

2021-07-12 19:01 UTC, jenglish81 commented on Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ChangeFeedPullScenario.cs
> +                        logger.LogInformation($"Suceess: The number of new documents match the number of pre-created documents: {config.PreCreatedDocuments}");
Fixed, Thank you.

2021-07-12 19:02 UTC, ealsur commented
/azp run

2021-07-12 19:03 UTC, ealsur commented on Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ChangeFeedPullScenario.cs
> +            if (config.PreCreatedDocuments > 0)
You are missing the creation  of the container that you initially had?

2021-07-12 22:46 UTC, ealsur commented
/azp run

2021-07-12 23:41 UTC, ealsur approved these changes
Looks good! Thanks @jenglish81 !

2021-07-13 00:37 UTC, jenglish81 commented
> Looks good! Thanks @jenglish81 !

Thank you for your help!

2021-07-13 20:29 UTC, ealsur commented
/azp run

2021-07-13 21:14 UTC, merged