Diagnostics: Adds Summary for Diagnostic message
Azure/azure-cosmos-dotnet-v3 pull request #2732
Opened 2021-09-14 09:45 UTC by asketagarwal

This PR adds a summary of the diagnostic to the top of the message.
### Sample
```
{
    "TotalTimeInMs": 45,
    "Direct": {
         "SuccessfulCalls": 2,
         "429": 1,
         "449": 1
     },
    "MaxBELatencyMs": 10,
    "Gateway": {
        "SuccessfulCalls": 1,
        "OperationCancelledException": 1
    },
    "MaxGatewayRequestTimeMs": 120
}
```

### Perf
Benchmark tool : ReadStreamExistsWithDiagnostics

2021-09-14 11:57 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/SummaryDiagnosticsTraceDatum.cs
> +    internal sealed class SummaryDiagnosticsTraceDatum : TraceDatum
To reduce the allocations is there any reason this can't be made a struct and don't inherit from TraceDatum? Making it a struct will avoid the memory allocations.

2021-09-14 20:08 UTC, asketagarwal commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/SummaryDiagnosticsTraceDatum.cs
> +    internal sealed class SummaryDiagnosticsTraceDatum : TraceDatum
made it structs

2021-09-14 21:26 UTC, j82w submitted a review, later dismissed

2021-09-14 21:43 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/SummaryDiagnostics.cs
> +                if (double.TryParse(storeResponseStatistics.StoreResult.BackendRequestDurationInMs, out double backendLatency))
Should this be using `CultureInfo.InvariantCulture` ? If this runs in a machine where the default culture is not en-US or using the `.` as separator for decimals, it might break

2021-09-14 21:44 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/SummaryDiagnostics.cs
> +                if (double.TryParse(storeResponseStatistics.StoreResult.BackendRequestDurationInMs, out double backendLatency))
Similar to what we do in RequestCharge parsing

2021-09-14 22:59 UTC, ealsur requested changes
Please fix the double parsing

2021-09-15 11:36 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/SummaryDiagnostics.cs
> +                                    NumberStyles.Number,
Is there a reason you specified NumberStyles? I don't see other double.TryParse setting this value.

2021-09-15 13:49 UTC, j82w approved these changes

2021-09-15 15:40 UTC, ealsur approved these changes

2021-09-21 12:59 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/SummaryDiagnostics.cs
> +                if (!this.GatewayRequestsSummary.Value.ContainsKey(statusCode))
Why are we not including substatus on http responses?

2021-09-21 12:59 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/SummaryDiagnostics.cs
> +        public Lazy<Dictionary<(int, int), int>> DirectRequestsSummary { get; private set; }
nit: named tuples (int statusCode, int subStatusCode)

2021-09-21 13:06 UTC, asketagarwal commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/SummaryDiagnostics.cs
> +                if (!this.GatewayRequestsSummary.Value.ContainsKey(statusCode))
There are no SubstatusCodes present in the HttpResponseMessage.
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpresponsemessage?view=net-5.0

2021-09-21 13:43 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/SummaryDiagnostics.cs
> +                if (!this.GatewayRequestsSummary.Value.ContainsKey(statusCode))
It would be a http header.

2021-09-22 18:43 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/SummaryDiagnostics.cs
> +                    if (!int.TryParse(gatewayHeaders.SubStatus,
Why not just store the string instead of parsing the int?

2021-09-22 18:43 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/SummaryDiagnostics.cs
> +            if (this.AllRegionsContacted.IsValueCreated)
Is there reason we removed the total time?

2021-09-22 19:05 UTC, asketagarwal commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/SummaryDiagnostics.cs
> +            if (this.AllRegionsContacted.IsValueCreated)
The Total time is already near the top of the diagnostics in the root trace and will be duplicated, we discussed this in the SDK scrum last time

2021-09-22 19:05 UTC, asketagarwal commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/SummaryDiagnostics.cs
> +                    if (!int.TryParse(gatewayHeaders.SubStatus,
i wanted to keep it consistent with the DirectSummary hence int, also if it is some invalid value we are writing it to the diagnostics as it is (less likely)

2021-09-22 20:57 UTC, j82w approved these changes

2021-09-23 11:49 UTC, kirankumarkolli approved these changes

2021-09-23 11:50 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/SummaryDiagnostics.cs
> +                jsonWriter.WriteNumber64Value(this.AllRegionsContacted.Value.Count);
Should it use the region names instead of a count?

2021-09-23 11:50 UTC, merged