Performance: Adds query improvement to load values lazily
Azure/azure-cosmos-dotnet-v3 pull request #2869
Opened 2021-11-09 22:02 UTC by sourabh1007

## Description

Loading values lazily in `CosmosQueryClientCore` to avoid execution on each request in order to Lod these objects on every call unnecessarily.

## Type of change

- [] Bug fix (non-breaking change which fixes an issue)

## Closing issues

Fixes 2,3 of the 3 issues: #2815

2021-11-09 22:29 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Query/Core/Metrics/QueryMetrics.cs
> +                ? BackendMetrics.Empty
nit: avoid multiple ternary operators
```c#
new Lazy<BackendMetrics>(() =>
{
    if(!string.IsNullOrEmpty(deliminatedString) &&
        BackendMetricsParser.TryParse(deliminatedString, out BackendMetrics backendMetrics))
    {
       return true;  
     }

     return false;
  });
```

2021-11-09 22:29 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryClientCore.cs
> +                  /*  CosmosQueryExecutionInfo cosmosQueryExecutionInfo;
nit: remove unused code

2021-11-09 22:29 UTC, j82w commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Program.cs
> +            argsList.Add("--allCategories=QueryGateBenchmark");
nit: remove. This should be set on the yaml file.

2021-11-09 22:29 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Query/Core/Metrics/QueryMetrics.cs
> +                    BackendMetrics.Accumulator.ToBackendMetrics(accumulator.BackendMetricsAccumulator).ToString(),
Need to avoid converting to a string and parsing it again. Have a constructor overload to take in the parsed backend metrics.

2021-11-09 22:30 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/Pagination/QueryPage.cs
> +            string cosmosQueryExecutionInfo,
This needs to take in a Lazy<CosmosQueryExecutionInfo>. Otherwise every new page is serializing and reparsing the content.

2021-11-09 22:32 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/Pagination/QueryPage.cs
> +        public CosmosQueryExecutionInfo CosmosQueryExecutionInfoObject => this.cosmosQueryExecutionInfoLazyObject.Value;
Why not expose a `Lazy<CosmosQueryExecutionInfo>`. That way each new page is just passing the same lazy object everywhere.

2021-11-09 23:53 UTC, kirankumarkolli commented
Can you please share the numbers?

Also one clarification: Do lazy materialization expose any gaps in the reference/buffer management?

2021-11-10 01:02 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryClientCore.cs
> +                        cosmosQueryExecutionInfoLazyObject = new Lazy<CosmosQueryExecutionInfo>(() => JsonConvert.DeserializeObject<CosmosQueryExecutionInfo>(queryExecutionInfoString));
This can be done in a future PR. Would this get better perf to create JObject. Then only get out the single value needed?

2021-11-10 08:43 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryClientCore.cs
> +                        cosmosQueryExecutionInfoLazyObject = new Lazy<CosmosQueryExecutionInfo>(() => default);
previously also it was set as "default"
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/8646349f30f4480bc5a32dd19ab4bad6b0d04978/Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryClientCore.cs#L327

2021-11-10 15:48 UTC, sourabh1007 commented
> Can you please share the numbers?
> 
> Also one clarification: Do lazy materialization expose any gaps in the reference/buffer management?

I have updated the number in the PR description. It showed improvement in memory allocation and op/s for some cases.
Clarification: There should not be any gaps, as we are already using it in SDK at many places. I really don't know how can I check this but if there is any issue in reference/buffer management, it should show up in our performance tests.

2021-11-10 16:10 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Query/Core/Metrics/QueryMetrics.cs
> +                if (!deliminatedString.Equals(string.Empty) &&
if (!String.IsNullOrWhitespace(deliminatedString)) instead

2021-11-10 16:21 UTC, FabianMeiswinkel requested changes
LGTM except for minor comments

2021-11-10 16:21 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Query/Core/Metrics/QueryMetrics.cs
> +                        BackendMetricsParser.TryParse(deliminatedString, out BackendMetrics backendMetrics))
What if TryParse returns false - in this case you would return null - shouldn't we return BackendMetrics.Empty instead?

2021-11-10 16:31 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Query/Core/Metrics/QueryMetrics.cs
> +                        BackendMetricsParser.TryParse(deliminatedString, out BackendMetrics backendMetrics))
It does return BackendMetrics.Empty at line 45.

2021-11-11 14:04 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryClientCore.cs
> +                            new QueryMetrics(cosmosResponseMessage.Headers.QueryMetricsText,
Is there any reason we didn't make the QueryMetricsTraceDatum lazy instead of the content of the QueryMetrics?

2021-11-11 14:04 UTC, j82w approved these changes

2021-11-11 14:42 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryClientCore.cs
> +                            new QueryMetrics(cosmosResponseMessage.Headers.QueryMetricsText,
I think thats what we discussed and why do you want to make QueryMetricsTraceDatum object lazy. It is already very light object (with no logic at all) and in this code, only there was only one calculation (i.e. parsing of backendMetrics) which might be taking memory, i have made that calculation lazy.

2021-11-11 20:36 UTC, kirankumarkolli commented
If I am reading right, for multipage interactions with the change is there RPS regression? 
Or is it variances if so even for single pages gains are not related to variance?

2021-11-11 21:36 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Query/Core/Metrics/QueryMetrics.cs
> +            this.BackendMetrics = backendMetrics;
nit: should we maintain the null check that was previously here?

2021-11-11 21:43 UTC, ealsur submitted a review, later dismissed
LGTM except some extra comments regarding testing and code duplicity

2021-11-11 21:43 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/Pagination/QueryPage.cs
> +    using Newtonsoft.Json;
Why is this using needed?

2021-11-11 21:43 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Query/Core/Metrics/QueryMetrics.cs
> +            string deliminatedString,
Are there any Unit Tests that need to include now this constructor call? If not, can we add them? For example:

* Call ctor with a null/empty value -> Expect BackendMetrics.Empty
* Call ctor with random text -> Expect BackendMetrics.Empty
* Call ctor with correct strings -> Expect parsed BackendMatrics

2021-11-11 21:43 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Query/Core/Metrics/QueryMetrics.cs
> +            this.IndexUtilizationInfo = indexUtilizationInfo ?? throw new ArgumentNullException(nameof(indexUtilizationInfo));
Is it possible to reduce duplicity by making this constructor call the other one?

```
public QueryMetrics(
            string deliminatedString,
            IndexUtilizationInfo indexUtilizationInfo,
            ClientSideMetrics clientSideMetrics)
: base (
      !String.IsNullOrWhiteSpace(deliminatedString) &&
                    BackendMetricsParser.TryParse(deliminatedString, out BackendMetrics backendMetrics)
                ? backendMetrics
                : BackendMetrics.Empty,
    indexUtilizationInfo,
    clientSideMetrics
){ }

2021-11-12 11:54 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Query/Core/Metrics/QueryMetrics.cs
> +            string deliminatedString,
This is all existing logic, I just refactored this code. Tests are already there, i.e.
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Metrics/BackendMetricsTests.cs

2021-11-15 12:02 UTC, sourabh1007 commented
> If I am reading right, for multipage interactions with the change is there RPS regression? Or is it variances if so even for single pages gains are not related to variance?

Prev results were from local. Now I ran benchmark on a VM and now you can notice the improvement in RPS and memory allocated also.

2021-11-15 16:34 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Query/Core/Metrics/QueryMetrics.cs
> +            this.BackendMetrics = backendMetrics ?? throw new ArgumentNullException(nameof(indexUtilizationInfo));
```suggestion
            this.BackendMetrics = backendMetrics ?? throw new ArgumentNullException(nameof(backendMetrics));
```

2021-11-15 16:36 UTC, ealsur submitted a review, later dismissed
LGTM - Just a nit

2021-11-15 20:01 UTC, kirankumarkolli approved these changes

2021-11-16 00:32 UTC, FabianMeiswinkel approved these changes
LGTM - Thanks

2021-11-16 01:01 UTC, j82w approved these changes

2021-11-16 01:02 UTC, merged