[Internal] Diagnostics: Fixes reinitialization of Region Contacted Information
Azure/azure-cosmos-dotnet-v3 pull request #2907
Opened 2021-11-24 17:37 UTC by sourabh1007

## Description

## Type of change
- [] Bug fix (non-breaking change which fixes an issue)

## Closing issues

To automatically close an issue: closes

2021-12-28 17:21 UTC, kirankumarkolli commented
What's the impact with-out regions-contracted collection in telemetry?

2021-12-28 17:36 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Handler/TransportHandler.cs
> +                processMessageAsyncTrace.UpdateRegionContacted(clientSideRequestStatisticsTraceDatum);
I assume this is the only line that changed here. Is that right?

One more option is to do a dummy commit with the original file and then do specific edits with current PR.

2021-12-28 17:38 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryHelper.cs
> +                return null;
Is the contract to have NULL or empty string?

2021-12-28 17:41 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Tracing/ITrace.cs
> +        void UpdateRegionContacted(HashSet<(string, Uri)> newRegionContacted);
Ideally RegionsContacted response it-self can be used to update/patch as needed right. 

With that assumption it will be max utility and can be an extension method for convenience.

2021-12-28 17:43 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Tracing/ITrace.cs
> +        HashSet<(string, Uri)> RegionsContacted { get; }
With this goal, demands HashSet for every nested hierarchy. Is it necessary?

2021-12-28 19:19 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Tracing/TraceJoiner.cs
> +
NIT remove excessive LF

2021-12-28 19:20 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Tracing/ITrace.cs
> +        HashSet<(string, Uri)> RegionsContacted { get; }
This shoudl be ISet<T> everywhere - or even IReadOnlySet - like with the other properties as well.

2021-12-28 19:23 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Benchmarks/TelemetryBenchmark.cs
> +                        using (ITrace thirdLevel = trace.StartChild("Third level Node", TraceComponent.Unknown, TraceLevel.Info))
No need for extra indentation in every line

just use...

using (x)
using (y)
using (z)
{
    DoWhateverYouWant()
}

2021-12-29 10:00 UTC, sourabh1007 commented
> What's the impact with-out regions-contracted collection in telemetry? This data point will help us understand how much is it contributing even with optimization.

https://github.com/Azure/azure-cosmos-dotnet-v3/issues/2952 This issue has all my RCA documented.

2021-12-29 13:39 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryHelper.cs
> +                return null;
It is "nullable". So as part of contract, If it is there in payload, it will save that value otherwise it won't. This column will be blank. So setting it as "null", won't set it in payload.

2021-12-29 16:48 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Tracing/ITrace.cs
> +        HashSet<(string, Uri)> RegionsContacted { get; }
> [ **Waiting** ] With this goal, demands HashSet for every nested hierarchy. Is it necessary?

`Tracedum ` has hashset of regioncontacted so to incorporate it we need hashset and current implementation is updating region information to all of its parents. So basically each node will have Hashset of region contacted information collected by itself + (unioun with) region contacted information collected by children

2021-12-29 17:14 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Benchmarks/TelemetryBenchmark.cs
> +                        using (ITrace thirdLevel = trace.StartChild("Third level Node", TraceComponent.Unknown, TraceLevel.Info))
yes we can use it...it is more clear which is nested to what otherwise without braces it is looking confusing.

2021-12-30 09:21 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Tracing/ITrace.cs
> -        interface ITrace : IDisposable
This is a breaking change that is avoidable. Please revert it. Breaking only when INTERNAL compiler switch is set - but even for Compute etc. we should avoid breaking changes as much as possible. And making interface a class is breaking because you can have a class inherit/implement multiple interfaces but not multiple abstract base classes.

2021-12-30 09:21 UTC, FabianMeiswinkel requested changes
Please revert the breaking change making ITrace abstract base class instead of interface

2022-01-07 09:27 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Tracing/ITrace.cs
> +        HashSet<(string, Uri)> RegionsContacted { get; set; }
This is still a Hashset - I commented before that it should instead be ISet - see other properties. If there is a reason for won't fixing a comment please leave that one active - so that it is clear why you rejected to address a comment.

2022-01-07 10:21 UTC, FabianMeiswinkel submitted a review, later dismissed
Looks good except for the ITrace.RegionsContacted still having type HashSet<T> instead of ISet<T> - please change that before merging.

2022-01-07 10:28 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Tracing/AbstractTrace.cs
> +    internal abstract class AbstractTrace : ITrace
Trace Base sounds better so renaming it to this.

2022-01-07 10:34 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Tracing/ITrace.cs
> +        HashSet<(string, Uri)> RegionsContacted { get; set; }
I made that change, after that I noticed a minor degradation in overall performance.....but again, I can't be really sure if it is really impacting as here I am talking about very minute difference..so to be on safer side I reverted that change but today I wrote a small test to see the impact of interface vs direct call on a class...looks like interface is slightly better than direct call...so I am making it ISet as per your comment.

2022-01-07 12:44 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/TraceBase.cs
> +    internal abstract class TraceBase : ITrace
Why is it necessary to create base class? It breaks the current design where everywhere is using the interface.

2022-01-07 12:44 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/ITrace.cs
> +        void UpdateRegionContacted(TraceDatum traceDatum);
Why can't this be done as part of the implementation?

2022-01-07 12:44 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/ITrace.cs
> +        ISet<(string, Uri)> RegionsContacted { get; set; }
Can this be made more generic object like AggregatedTraceInfo? That object is just passed down to all the child traces. Each child can append the region contacted and other info like the status code.

2022-01-07 12:52 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Tracing/TraceBase.cs
> +    internal abstract class TraceBase : ITrace
This class has default implementation of regionContacted collection logic...With old design, this default implementation has to be copied everywhere and tomorrow if you want to change anything in this logic you need to make that change everywhere consciously. Which was just leading to code duplicity.
In current design, I don't see any place where we can't go with abstract class.

2022-01-07 12:56 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Tracing/ITrace.cs
> +        ISet<(string, Uri)> RegionsContacted { get; set; }
May be we can do it as part of separate PR if we have more things to get aggregated like regioncontacted information.

2022-01-07 13:04 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/TraceBase.cs
> +    internal abstract class TraceBase : ITrace
There is no need for the base class. There is only 2 implementations. 1. The actual Trace.cs 2. NoOpTrace.cs. The no-op trace should do nothing. The only class that needs to be modified is the Trace.cs. There is no need for a base class.

2022-01-07 13:13 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/ITrace.cs
> +        ISet<(string, Uri)> RegionsContacted { get; set; }
We already have multiple scenarios where this is needed. I don't see any reason why it should be done in a follow up PR.

2022-01-07 13:16 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Tracing/TraceBase.cs
> +    internal abstract class TraceBase : ITrace
ITrace is implemented by all these classes so I need to give default implementation there.
![image](https://user-images.githubusercontent.com/6362382/148549215-776fce49-fd09-4250-ad19-3440349a9da7.png)

I don't think its a good idea.

2022-01-07 13:18 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Tracing/ITrace.cs
> +        ISet<(string, Uri)> RegionsContacted { get; set; }
We didn't identify that multiple scenario yet...so before implementing that..we need to identify all those scenario and then implement them. That's why I am suggesting separate PR. 
May be you can create a bug or something where we can identify all the information which we would need aggregated.

2022-01-07 13:24 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/ITrace.cs
> +        ISet<(string, Uri)> RegionsContacted { get; set; }
This should be exposed as a IReadOnlyList<(string, Uri). ISet can be modified which goes against the design. Notice how all the other properties are read only. It prevents them from be modified outside the class. For example the no-op trace uses a singleton that is shared across all instance. If someone adds a property all of the requests that use a no-op will get it.

2022-01-07 14:21 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/TraceBase.cs
> +    internal abstract class TraceBase : ITrace
1. Only one that needs the implementation is Traces.cs. 
2. NoOpTrace should not do anything with it. 
3. Tests for validating the baseline don't need this.
4. TraceJoiner needs its own custom implementation to merge the 2 lists.
The logic for TraceJoiner is unique and the 2 tests classes don't need it.

2022-01-07 16:39 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Tracing/TraceBase.cs
> +    internal abstract class TraceBase : ITrace
Does it mean..So you prefer to have empty override function (in trace joiner and test classes) over having default functionality? and still I am not able to understand the problem with current implementation...what is the harm with current implementation?

2022-01-07 17:24 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Tracing/TraceBase.cs
> +    internal abstract class TraceBase : ITrace
What problem you are trying to solve here?

2022-01-07 19:33 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Tracing/TraceBase.cs
> +    internal abstract class TraceBase : ITrace
I think what @j82w is saying is that you don't need the base class, the logic you are adding is just for the `Trace.cs` file, it is not needed on `NoOpTrace.cs`, nor `TraceJoiner.cs` and definetively not on the tests, so the base class is not needed, there is nothing to share.

2022-01-07 20:15 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Tracing/TraceBase.cs
> +    internal abstract class TraceBase : ITrace
Even if This logic is not getting used by anything. But as a contract, ITrace will have RegionContacted information so either I have to leave this implementation empty(incomplete code) or write something there (lead to code duplicity). Thats why I have base class with default implementation, now its upto implement class if they want to use this or not.

2022-01-07 20:43 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Handler/TransportHandler.cs
> +                        : await storeProxy.ProcessMessageAsync(serviceRequest, cancellationToken);
1. This throws DocumentClientException which mean the code below will never get called so it won't collection regions on failure scenarios. Only a few error scenarios are handled without exceptions.
2. Several of the caches do not go through the handlers. It won't collect the region information in those scenarios.

Possible solutions:
Create a SharedTraceInfo object. Pass it down to each child trace and to the ClientSideRequestStats. Then the clientsiderequeststat object will add the region to the ShareTraceInfo object.

2022-01-07 22:45 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Tracing/TraceBase.cs
> +                this.RegionsContacted = clientSideRequestStatisticsTraceDatum.RegionsContacted?.ToList();
Isn't it replacing always. Not matching the update intent.

2022-01-07 22:49 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Tracing/TraceBase.cs
> +    internal abstract class TraceBase : ITrace
There are two independent parts lets go-over them one-by one
1. Existing Trace implementations (NoOp, Trace) have lots of common context but both duplicated. @j82w is it intentional? If so is it to avoid virtual performance cost? 
2. Where to have the implementation logic: It also comes to what is expected of NoOp implementation. If its meant to differ from the actual ones then the choice is clear, the logic needs to be specific for each implementation.

2022-01-10 10:13 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Tracing/TraceBase.cs
> +                this.RegionsContacted = clientSideRequestStatisticsTraceDatum.RegionsContacted?.ToList();
setter has the logic..it will just call the setter with the value.

2022-01-10 10:24 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Tracing/TraceBase.cs
> +    internal abstract class TraceBase : ITrace
NoOp doesn't have any functionality so in current implementation, common code won't  even get executed in this case. It get executed only in case of Trace and TraceJoiner and in case of tests (although they don't use this information at all) but according to me if we are writing a logic for Traces it should be available for all the child classes and Region Contacted related information is not that kind of information which everybody (child classes) would want to implement it  differently.

2022-01-10 12:09 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Handler/TransportHandler.cs
> +                request.Trace.UpdateRegionContacted(clientSideRequestStatisticsTraceDatum);
Why not put this in a finally to avoid the call in all these catch scenarios?

2022-01-10 12:09 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Handler/TransportHandler.cs
> +            ClientSideRequestStatisticsTraceDatum clientSideRequestStatisticsTraceDatum = new ClientSideRequestStatisticsTraceDatum(DateTime.UtcNow);
This won't catch region for the cache refreshes as they don't go through the pipeline. Should the ClientSideRequestStatisticsTraceDatum take in a trace object and then have it call the update method?

2022-01-10 12:53 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Handler/TransportHandler.cs
> +                request.Trace.UpdateRegionContacted(clientSideRequestStatisticsTraceDatum);
makes sense

2022-01-10 12:54 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Handler/TransportHandler.cs
> +            ClientSideRequestStatisticsTraceDatum clientSideRequestStatisticsTraceDatum = new ClientSideRequestStatisticsTraceDatum(DateTime.UtcNow);
Do we have any test to verify this? If it was already happening.

2022-01-10 15:46 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/ITrace.cs
> +        string Name { get; set; }
Revert

2022-01-10 17:33 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Tracing/TraceBase.cs
> +                if (this.Parent != null)
This will be very expensive as all the entries in the hierarchy is forces to have this hasset. 
Is it necessary at and every layer?

2022-01-10 17:49 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Tracing/TraceBase.cs
> +                if (this.Parent != null)
refactored this logic to update only root object.

2022-01-10 18:05 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Tracing/ITrace.cs
> +        IReadOnlyList<(string, Uri)> RegionsContacted { get; set; }
@j82w will it impact compute?

2022-01-10 18:06 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Tracing/TraceBase.cs
> +                if (this.Parent != null)
LGTM

2022-01-10 18:07 UTC, kirankumarkolli approved these changes

2022-01-10 19:24 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/ITrace.cs
> +        IReadOnlyList<(string, Uri)> RegionsContacted { get; set; }
Yes, it will. Any methods to ITrace will impact compute and cause sync conflicts.

2022-01-11 12:50 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/ITrace.cs
> +        IReadOnlyList<(string, Uri)> RegionsContacted { get; set; }
Why does this need to have set?

2022-01-11 12:50 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/ITrace.cs
> +        void UpdateRegionContacted(TraceDatum traceDatum);
Why doesn't this just take a IClientSideRequestStats interface and avoid the type check?

2022-01-11 12:57 UTC, j82w commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.BatchOperationsAsync.xml
> +﻿<Results>
Please revert the baseline files. This is only changing the white space.

2022-01-11 13:02 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Tracing/ITrace.cs
> +        IReadOnlyList<(string, Uri)> RegionsContacted { get; set; }
fir this https://github.com/Azure/azure-cosmos-dotnet-v3/blob/832edc8e6c410d00f5f4ce6c509c0914bea447f7/Microsoft.Azure.Cosmos/src/Tracing/Trace.cs#L71

2022-01-11 13:11 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/ITrace.cs
> +        IReadOnlyList<(string, Uri)> RegionsContacted { get; set; }
That won't work correctly. There are scenarios like query and changefeed. Where a single trace will have multiple children.

Scenario:
TraceA -> TraceB
            -> TraceC
TraceB will set the parent. TraceC will get a contacted region. TraceA will already have a list from TraceB. The regions from TraceC will never be added to TraceA. 

Every request should have contact at least 1 region. I recommend creating the hashset when the parent trace is created and pass it down to all the children. Then it needs to take a lock on adding to the hashset to avoid concurrency issues.

2022-01-11 13:30 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Tracing/ITrace.cs
> +        IReadOnlyList<(string, Uri)> RegionsContacted { get; set; }
are you talking about this scenario? https://github.com/Azure/azure-cosmos-dotnet-v3/blob/ec8b8bb943f13be5affefea0da4263f03c0ef00e/Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Tracing/ContactedRegionsTests.cs#L17

2022-01-11 13:46 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Tracing/ITrace.cs
> +        void UpdateRegionContacted(TraceDatum traceDatum);
D:\a\1\s\Microsoft.Azure.Cosmos\src\Tracing\ITrace.cs(133,14): error CS0051: Inconsistent accessibility: parameter type 'IClientSideRequestStatistics' is less accessible than method 'ITrace.UpdateRegionContacted(IClientSideRequestStatistics)' [D:\a\1\s\Microsoft.Azure.Cosmos\src\Microsoft.Azure.Cosmos.csproj]
 
getting this error for "Internal" package build

2022-01-11 14:51 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/ITrace.cs
> +        IReadOnlyList<(string, Uri)> RegionsContacted { get; set; }
1. That test should cover this scenario, but the test has a bug it. It always adds the children to the same root. None of them are nested. 
2. I reviewed it more and it does work correctly because it's always iterating to the root parent. I find the implementation confusing, because this could be accomplished with a simple while loop to find the root instead. 
3. This isn't thread safe. If TraceB and TraceC try to add regions at the same time it will break. There needs to be a lock when modifying the hashset to make it thread safe.

2022-01-11 15:44 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/ITrace.cs
> +        void UpdateRegionContacted(TraceDatum traceDatum);
Then I guess leave it as TraceDatum.

2022-01-11 16:37 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Tracing/ITrace.cs
> +        IReadOnlyList<(string, Uri)> RegionsContacted { get; set; }
added a lock around it.

2022-01-11 17:05 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Tracing/Trace.cs
> +                    lock (this.RegionsContactedTemporary)
This will throw an exception if it is null.

2022-01-11 17:16 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Tracing/Trace.cs
> +                    lock (this.RegionsContactedTemporary)
yes I realized it later...pipelines were failing due to this...moved it inside not null condition.

2022-01-11 21:32 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Diagnostics/CosmosTraceDiagnostics.cs
> +            return this.Value?.RegionsContacted?.ToList();
Why is the ToList() needed?

2022-01-12 11:58 UTC, j82w commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Benchmarks/RegionContactedInDiagnosticsBenchmark.cs
> +            using (ITrace secondLevel = trace.StartChild("Second level Node", TraceComponent.Unknown, TraceLevel.Info))
Fix the benchmark to actually nest the traces. It should be:

```c#
using (ITrace secondLevel = firstLevel.StartChild("Second level Node", TraceComponent.Unknown, TraceLevel.Info))
using (ITrace thirdLevel = secondLevel .StartChild("Second level Node", TraceComponent.Unknown, TraceLevel.Info))
```

2022-01-12 11:58 UTC, j82w commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/TraceJoiner.cs
> +namespace Microsoft.Azure.Cosmos.Tracing
Please fix the line endings.

2022-01-12 15:01 UTC, j82w approved these changes

2022-01-12 23:49 UTC, merged