feat: Implement an optimized path for member access in LINQ-to-SQL
Azure/azure-cosmos-dotnet-v3 pull request #2924
Opened 2021-12-06 22:59 UTC by notheotherben

# Pull Request Template

## Description
This optimization handles the common case of accessing a member (variable, field, property) in the ambient scope, as shown below:

```csharp
var bob = "Bob";
users.Where(u => u.Username == bob);
```

In this scenario, we will attempt to avoid compiling a lambda expression to evaluate `bob` and instead rely on reflection member access to retrieve the constant value. This helps us avoid the global lock held by `System.Reflection.Emit.DynamicMethod` while constructing the dynamic method table, which alleviates a serious performance bottleneck on highly threaded systems. In particular, this helps avoid a pathological async-over-sync situation which can lead to thread pool exhaustion and hot-lock thrashing.

The goal of this change is to provide teams who face this problem with a reasonable means of optimizing their query code (use variables which hold pre-computed constants to avoid delegate compilations), instead of forcing them to rewrite their codebases to use stored SQL, or to implement some form of SQL caching.

## Type of change
- [x] New feature (non-breaking change which adds functionality)

2021-12-06 23:13 UTC, ndrwrbgs reviewed
Overall comment:
Is the underlying problem here isolated to Constants? I think this change could help in the scenario that is currently your focus - but is there anything more architecturally that could/should be changed to accommodate a large class of issues?

2021-12-06 23:13 UTC, ndrwrbgs commented on Microsoft.Azure.Cosmos/src/Linq/SubtreeEvaluator.cs
> +        private static readonly Dictionary<(Type Type, string Member), MemberInfo> memberInfoCache = new Dictionary<(Type Type, string Member), MemberInfo>();
Is concurrency a concern in this class/library?

2021-12-06 23:13 UTC, ndrwrbgs commented on Microsoft.Azure.Cosmos/src/Linq/SubtreeEvaluator.cs
> +            // This is an optimization which attempts to avoid the compilation of a delegate lambda for
[nit] this needed a pretty big comment and extended the relative size of the method pretty substantially. Would it be okay to refactor to a `bool Try(out)` method instead to encapsulate the cohesive logic?

2021-12-06 23:13 UTC, ndrwrbgs commented on Microsoft.Azure.Cosmos/src/Linq/SubtreeEvaluator.cs
> +        private static readonly Dictionary<(Type Type, string Member), MemberInfo> memberInfoCache = new Dictionary<(Type Type, string Member), MemberInfo>();
:outdated

2021-12-06 23:15 UTC, ndrwrbgs commented on Microsoft.Azure.Cosmos/src/Linq/SubtreeEvaluator.cs
> +            while (expression.CanReduce)
Are there contractual guarantees that CanReduce will eventually return `false`?
Under what scenarios would `Reduce()` return an `Expression` which still has `CanReduce`?

2021-12-06 23:17 UTC, notheotherben commented on Microsoft.Azure.Cosmos/src/Linq/SubtreeEvaluator.cs
> +        private static readonly Dictionary<(Type Type, string Member), MemberInfo> memberInfoCache = new Dictionary<(Type Type, string Member), MemberInfo>();
This is outdated (and unused), sorry for the confusion :)

2021-12-06 23:18 UTC, notheotherben commented on Microsoft.Azure.Cosmos/src/Linq/SubtreeEvaluator.cs
> +            while (expression.CanReduce)
Here are the docs for the `Reduce()` method:

```csharp
// Summary:
//     Reduces this node to a simpler expression. If CanReduce returns true, this should
//     return a valid expression. This method can return another node which itself must
//     be reduced.
//
// Returns:
//     The reduced expression.
```

Based on that, it seems like the correct thing to do is to recursively reduce this.

2021-12-07 01:23 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Linq/SubtreeEvaluator.cs
> +            if (expression is MemberExpression memberExpression && memberExpression.Expression is ConstantExpression targetConstant)
Please add a performance test to see the before and after: https://github.com/Azure/azure-cosmos-dotnet-v3/tree/master/Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests

2021-12-07 09:59 UTC, notheotherben commented on Microsoft.Azure.Cosmos/src/Linq/SubtreeEvaluator.cs
> +            // This is an optimization which attempts to avoid the compilation of a delegate lambda for
Can certainly do so, there may be value in extracting this logic out anyway so that we can do recursive resolution of member access (enabling us to do queries like `db.Where(d => d.Username == context.User.Name)`), which are currently not possible with this implementation.

Let's see whether this is something the Cosmos DB folks are interested in before we expand the functionality.

2021-12-07 10:03 UTC, notheotherben commented on Microsoft.Azure.Cosmos/src/Linq/SubtreeEvaluator.cs
> +            if (expression is MemberExpression memberExpression && memberExpression.Expression is ConstantExpression targetConstant)
Certainly 👍

2021-12-07 10:31 UTC, notheotherben commented on Microsoft.Azure.Cosmos/src/Linq/SubtreeEvaluator.cs
> +            if (expression is MemberExpression memberExpression && memberExpression.Expression is ConstantExpression targetConstant)
Here's a quick result from executing an example benchmark which forces the legacy delegate-style evaluation and compares it against the new reflection approach (test code committed in the latest revision):

![image](https://user-images.githubusercontent.com/1760260/145012897-67e36faf-c181-4440-b101-1dee79641fa9.png)

2021-12-07 11:04 UTC, notheotherben commented on Microsoft.Azure.Cosmos/src/Linq/SubtreeEvaluator.cs
> +            if (expression is MemberExpression memberExpression && memberExpression.Expression is ConstantExpression targetConstant)
Testing this on `net472` (which is our usage target), we see about a 20x performance improvement in this LINQ to SQL translation, while on `net6.0` we only see a 5x improvement due to optimizations done in the BCL.

2021-12-08 15:13 UTC, ealsur commented
/azp run

2021-12-09 12:57 UTC, j82w commented
/azp run

2021-12-10 15:04 UTC, j82w approved these changes

2021-12-10 18:14 UTC, j82w commented
@khdang and @sboshra and @timsander1 please review this PR.

2021-12-11 23:08 UTC, ndrwrbgs submitted a review, later dismissed

2021-12-16 20:39 UTC, khdang requested changes

2022-02-01 10:26 UTC, notheotherben commented on Microsoft.Azure.Cosmos/src/Linq/SubtreeEvaluator.cs
> +        private Expression EvaluateMemberAccess(Expression expression)
Hi @khdang, I can certainly add some further tests which exercise this code path, however they'll be identical to the existing test suite.

This code change is responsible for handling any `.x.y.z` property accesses, which would previously have required the compilation and invocation of a delegate. Given that ambient variables are captured in an implicit structure, this applies to any query which attempts to pattern match to an ambient variable.

As such, this acts as a transparent performance optimization for this (very) common use case without any external behavioural changes. Paired with the fact that the list of expressions which are evaluated is pre-filtered, and I suspect that it should be very rare indeed that this code path is not followed (which is a good thing given the performance and concurrency benefits).

2022-05-04 17:38 UTC, j82w commented
/azp run

2022-05-04 18:16 UTC, merged

2022-05-05 09:14 UTC, notheotherben commented
Thanks for getting this merged folks, I suspect this should have a pretty sizeable benefit for our user-base.