Added  flag to user agent string if preview SDK.
Azure/azure-cosmos-dotnet-v3 pull request #2960
Opened 2021-12-27 17:49 UTC by SchintaMicrosoft

# Pull Request Template

## Description

Added flag to user agent string if preview SDK.

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

 #2831

2022-01-03 12:31 UTC, j82w requested changes

2022-01-03 12:31 UTC, j82w commented on Microsoft.Azure.Cosmos/src/UserAgentContainer.cs
> +            string baseUserAgent = $"cosmos-netstandard-sdk/{clientVersion}" + "P" + Regex.Replace($"|{directVersion}|{this.clientId}|{processArchitecture}|{operatingSystem}|{runtimeFramework}|", @"[
This is being added to all user agent strings instead of just the preview version. This needs to be included in the preprocessor `#if PREVIEW`.

2022-01-03 18:51 UTC, j82w commented on Microsoft.Azure.Cosmos/src/UserAgentContainer.cs
> +            string baseUserAgent = $"cosmos-netstandard-sdk/{clientVersion}" + "P" + Regex.Replace($"|{directVersion}|{this.clientId}|{processArchitecture}|{operatingSystem}|{runtimeFramework}|", @"[
Instead of duplicating the complex string logic why not do something like this?
```c#
string previewFlag = string.Empty;
#if PREVIEW
     previewFlag = "P";
#endif

string baseUserAgent = $"cosmos-netstandard-sdk/{clientVersion}" + previewFlag + Regex.Replace($"|{directVersion}|{this.clientId}|{processArchitecture}|{operatingSystem}|{runtimeFramework}|", @"[^0-9a-zA-Z\.\|\-]+", " ");
```

if(

2022-01-04 14:22 UTC, kirankumarkolli submitted a review, later dismissed

2022-01-06 15:14 UTC, j82w approved these changes

2022-01-06 15:53 UTC, merged