Session: Fixes session token being sent if request had a different consistency level
Azure/azure-cosmos-dotnet-v3 pull request #2965
Opened 2022-01-03 23:19 UTC by ealsur

## Description

On Gateway mode, if the account is Session consistency but the user is sending a request where the `ItemRequestOptions` has a ConsistencyLevel != Session, we were sending the session token anyway.

This PR makes it so the request level configuration is honored over the account level configuration.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

2022-01-04 01:18 UTC, kirankumarkolli approved these changes

2022-01-04 09:24 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +            bool requestHasConsistencySet = !string.IsNullOrEmpty(requestConsistencyLevel);
requestHasConsistencyset should only ever be true for read operations - for writes we need to ignore it. Otherwise your change is causing a regression where the session token for writes won't be sent when request consistency level override exists.

2022-01-04 09:25 UTC, FabianMeiswinkel requested changes
The "requestHasConsistencySet" needs to check whether it is read-only operation (or that condition needs to be added to sessionConsistency calculation

2022-01-04 16:35 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +            bool requestHasConsistencySet = !string.IsNullOrEmpty(requestConsistencyLevel);
The check for the type of request is already done down below, this is only checking if the request even has Session at some level.

See https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs#L276-L279

2022-01-04 17:39 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +            bool requestHasConsistencySet = !string.IsNullOrEmpty(requestConsistencyLevel);
This puts Gateway mode on the same logic as Direct mode. Direct mode does not send the session token on multi master if the request is Eventual

2022-01-04 18:30 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +            bool requestHasConsistencySet = !string.IsNullOrEmpty(requestConsistencyLevel);
I removed my blocking "request for changes" - to me this is still a bug. We document that request-level override of consistency models is only possible for read/query - not write requests. So any request level consistency level shouldn't have any side effects for writes. https://docs.microsoft.com/en-us/azure/cosmos-db/sql/how-to-manage-consistency?tabs=portal%2Cdotnetv2%2Capi-async#override-the-default-consistency-level

2022-01-05 22:22 UTC, FabianMeiswinkel submitted a review, later dismissed
LGTM - Thanks!

2022-01-05 22:30 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +            bool isConsideredAReadRequest = request.IsReadOnlyRequest || request.OperationType == OperationType.Batch;
Why is batch a Read request?

2022-01-05 22:30 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +            bool requestHasConsistencySet = !string.IsNullOrEmpty(requestConsistencyLevel);
After offline discussion, request level override is now only for read operations

2022-01-05 22:36 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +            bool isConsideredAReadRequest = request.IsReadOnlyRequest || request.OperationType == OperationType.Batch;
Renamed for clarity

2022-01-05 22:38 UTC, kirankumarkolli approved these changes

2022-01-05 23:08 UTC, merged