Validation added for RequestTimeOut
Azure/azure-cosmos-dotnet-v3 pull request #2991
Opened 2022-01-20 19:27 UTC by SchintaMicrosoft

# Pull Request Template

## Description
Validation added for Request Timeout to check Request Timeout cannot be set less than 1 second. This must be set in the Timespan of seconds.

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #958

2022-01-21 13:37 UTC, j82w commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +            set
Every change should add tests to cover what is being changed. Please add tests.

2022-01-21 19:46 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +                    throw new ArgumentException($"{nameof(this.requestTimeout)} can not be set less than 1 second. This must be set in the Timespan of seconds.");
nit: We should use the public property name
```suggestion
                    throw new ArgumentException($"{nameof(this.RequestTimeout)} can not be set less than 1 second. This must be set in the Timespan of seconds.");
```

2022-01-21 19:47 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +                this.requestTimeout = value;
nit: Should we validate that the TimeSpan has no milliseconds? and that is positive? Like in https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2991/files

2022-02-03 21:14 UTC, FabianMeiswinkel requested changes
Breaking change

2022-02-03 21:14 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +                    throw new ArgumentOutOfRangeException($"{nameof(this.RequestTimeout)} can not be set less than 1 second. This must be set in the Timespan of seconds.");
Check and error message are out of sync - code only would throw with negative timespan. error message indicates it would throw even when seconds == 0

Also this is a breaking change - throwing Argument Exceptions where it didn't before. If it is scoped to just negative timeouts it owuld be good to explain what is happening before this PR and explain why it is ok to break. If the plan is to throw any exception for postive Tiemspan i think this breaking change is unacceptable.

2022-02-03 23:05 UTC, j82w commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +                    throw new ArgumentOutOfRangeException($"{nameof(this.RequestTimeout)} can not be set less than 1 second. This must be set in the Timespan of seconds.");
The SDK did throw an exception from version 3.0 to 3.6. The check got removed because of some changes in the direct layer. This is not a breaking change. It's simply adding back the original check.

2022-02-04 09:07 UTC, bartelink commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +                this.requestTimeout = value;
Please don't reject non-zero milliseconds - I would not be surprised if people use values like 4.5 or 5.5s, and this logic can often be buried in long-established deep config paths which won't do useful error logging and hence be hard to troubleshoot. (if the granularity was truly seconds, then also consider a `int timeoutS` representation)

2022-02-04 10:29 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +                    throw new ArgumentOutOfRangeException($"{nameof(this.RequestTimeout)} can not be set less than 1 second. This must be set in the Timespan of seconds.");
It is still a breaking change if there is any minor version in the same 3.* major version that did not throw. Removing exceptions from a public API is a one-way-street, you can't revert that decision without moving to a new major version.

2022-02-04 17:25 UTC, j82w commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +                    throw new ArgumentOutOfRangeException($"{nameof(this.RequestTimeout)} can not be set less than 1 second. This must be set in the Timespan of seconds.");
How is adding validation for an invalid value a breaking change? Throwing an invalid argument exception on a config value should be expected. It will be thrown on the set so it is a fast failure with a clear error. If the customer does any testing or validation, it will fail and they can actually fix their application. This seems to be a far better user experience then ignoring the value which will eventually lead to a live site issue because they built their app on the assumption, they could do a request timeout of 100ms.

2022-02-04 23:08 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +                this.requestTimeout = value;
Normally I would say that I rather have an exception than false expectations. But in this case, this is an API that already existed, and on the configuration path (possibly a place where the client is created as part of the application initialization). Any new exceptions being thrown there would cause the application to restart/enter a cycle that the user might not know how to recover from ("I just updated my SDK and now my app does not start, I was simply setting timeout as 1.356 seconds").

If this was a new API introduced, then yeah, the check makes sense.

2022-06-09 19:26 UTC, SchintaMicrosoft commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +                    throw new ArgumentOutOfRangeException($"{nameof(this.RequestTimeout)} can not be set less than 1 second. This must be set in the Timespan of seconds.");
@FabianMeiswinkel , @j82w any further suggestions here  or proceed with this change.

2022-06-10 12:09 UTC, bartelink commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +                if (value.Seconds < 0)
should be TotalSeconds

2022-06-10 12:11 UTC, bartelink commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +                    throw new ArgumentOutOfRangeException($"{nameof(this.RequestTimeout)} can not be set less than 1 second. This must be set in the Timespan of seconds.");
use overload with argument name, don't embed it in the message. Lose the second half of the message as you have removed that semantic

2022-06-10 12:17 UTC, bartelink commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +                if (value.Seconds < 0)
You probably mean `<1` per the PR title. 

The overview does not provide a clear message as to the goal; I feel that getting that right will make it easier to determine whether an exception message does or does not concisely convey the intent.

I believe this has been traversed elsewhere in this PR review but arbitrarily saying you can't make the timeout be 5.1 seconds is definitely a bad idea (I personally don't see whats magic about 1s vs 500ms either in the context of a call to Cosmos in the same data center given a typical request latency of <100ms for the bulk of requests)

Long story short, please don't get distracted by picky comments on the impl - IMO the high level intent is not clear and that should be established first.

2022-06-10 12:19 UTC, bartelink commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
> +            cosmosClientOptions = new CosmosClientOptions { RequestTimeout = TimeSpan.FromMilliseconds(500) };
so 500ms is allowed? Or not?

2022-06-22 21:08 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +                    throw new ArgumentOutOfRangeException($"{nameof(this.RequestTimeout)} can not be set less than 1 second. This must be set in the Timespan of seconds.");
```suggestion
                    throw new ArgumentOutOfRangeException(nameof(this.RequestTimeout), "Timeout can not be set less than 1 second. This must be set in the Timespan of seconds.");
```

2022-06-22 21:09 UTC, ealsur approved these changes
Please sync with Fabian and get clarification if we want to move forward with the new exception thrown. cc @kirankumarkolli

2022-06-30 21:02 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        /// <value>Default value is 10 seconds.</value>
[Unrelated to current PR]
@ealsur do default 10 seconds apply for gateway meta-data calls? If so will it impact fail-overs?

2022-06-30 21:05 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
> +            cosmosClientOptions = new CosmosClientOptions { RequestTimeout = TimeSpan.FromMilliseconds(500) };
With 500ms won't this line throw exception?

2022-06-30 21:09 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +                    throw new ArgumentOutOfRangeException($"{nameof(this.RequestTimeout)} can not be set less than 1 second. This must be set in the Timespan of seconds.");
Semantically what @FabianMeiswinkel said is true. Post 3.6 the customers might have used values which are invalid but silently ignored now so it might break such customers. 

Its better to be very explicit on what is not supported. 
How about documenting it clearly in release notes as possible impact?

2022-06-30 23:50 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +                    throw new ArgumentOutOfRangeException($"{nameof(this.RequestTimeout)} can not be set less than 1 second. This must be set in the Timespan of seconds.");
I am against this breaking change - what is the motivation for arguing that this breaking change is worth violating semantic versioning? How many CRIs have we seen because customers were confused that their timeouts < 1 second haven't been accepted. And if they are confused they won't like either that they can't set those shorter timeouts. So, either you open the flood gate and allow customers to set whatever timeout you want as real TimeSpan  (taking the risk that they shoot themselves in the foot and end-up with bad availability) or you keep the current behavior and document it as clearly as possible in API doc - but this breaking change is not helping much and is still causing the pain breaking changes can have.

2022-06-30 23:51 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +                    throw new ArgumentOutOfRangeException($"{nameof(this.RequestTimeout)} can not be set less than 1 second. This must be set in the Timespan of seconds.");
Closing this PR unmerged is better than taking this change IMO. At least in V3

2022-07-01 02:56 UTC, bartelink commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +                    throw new ArgumentOutOfRangeException($"{nameof(this.RequestTimeout)} can not be set less than 1 second. This must be set in the Timespan of seconds.");
I would tend to round up or down rather than throw an exception as config wiring like this will often not traverse exception paths, much less be covered in tests IRL.
>`This must be set in the Timespan of seconds.`
If it is to proceed, perhaps a better wording is `The Timespan must be in whole Seconds.`

2022-08-03 21:34 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +                    throw new ArgumentOutOfRangeException($"{nameof(this.RequestTimeout)} can not be set less than 1 second. This must be set in the Timespan of seconds.");
There is consensus on not introducing the breaking change. 
Let's abandon this PR.

2022-08-05 16:16 UTC, SchintaMicrosoft commented
Abandoning this PR because of breaking charge.

2022-08-05 16:16 UTC, closed without merging