Revert #2826: Refactors to add Client Encryption APIs to GA SDK
Azure/azure-cosmos-dotnet-v3 pull request #3035
Opened 2022-02-16 05:12 UTC by anujtoshniwal

This reverts commit b73ed615e03aed0e7adec5ec309ad3eecc2d293a.

# Pull Request Template

## Description

Need this to GA the client-encryption feature.

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #IssueNumber

2022-02-16 06:59 UTC, abhijitpai approved these changes

2022-02-16 07:59 UTC, kr-santosh approved these changes

2022-02-16 10:42 UTC, FabianMeiswinkel requested changes
We had arch board review with the Azure Central team yesterday for the Java version of the library. There was some feedback that needs further discussion with them and is relevant across Java and .Net (mostly how to expose way for crypto algorithms and how to wrap/unwrap keys) - please hold this PR until we have a clear way forward there (because it could impact public surface area)

2022-03-07 04:06 UTC, anujtoshniwal commented
> 

Hi @FabianMeiswinkel, @j82w, @kirankumarkolli, now that the feedback has been addressed, please help review and close on this PR. Thanks!

2022-03-08 14:55 UTC, abhijitpai submitted a review, later dismissed

2022-03-08 14:58 UTC, kr-santosh approved these changes

2022-03-09 18:20 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs
> +namespace Microsoft.Azure.Cosmos
Please revert the line ending changes.

2022-03-09 18:23 UTC, kirankumarkolli submitted a review, later dismissed

2022-03-09 19:18 UTC, FabianMeiswinkel approved these changes
LGTM - thanks

2022-03-10 12:09 UTC, j82w approved these changes

2022-03-10 12:09 UTC, merged