Binary vs Text performance tool
Azure/azure-cosmos-dotnet-v3 pull request #3048
Opened 2022-02-23 17:32 UTC by hdetroja

This tool measures the performance of text response vs binary response for a query.

2022-02-23 20:24 UTC, neildsh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +                string TextMasterKey = "";
Read from config

2022-02-23 20:27 UTC, neildsh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +            using (FeedIterator<dynamic> iterator = container.GetItemQueryIterator<dynamic>(
>dynamic [](http://example.com/codeflow?start=32&length=7)

As discussed last month, please create an object model and use that (strong type) instead of dynamic

2022-02-23 20:27 UTC, neildsh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +                    FeedResponse<dynamic> response = await iterator.ReadNextAsync();
>response [](http://example.com/codeflow?start=42&length=8)

`using` response

2022-02-23 20:28 UTC, neildsh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +                    FeedResponse<dynamic> response = await iterator.ReadNextAsync();
>FeedResponse [](http://example.com/codeflow?start=20&length=12)

start the stopwatch before this line

2022-02-23 20:33 UTC, neildsh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/FindQueryMetrics.cs
> +                ClientSideRequestStatisticsTraceDatum.StoreResponseStatistics storeResponse = clientSideRequestStatisticsTraceDatum.StoreResponseStatisticsList[0];
>t[0]; [](http://example.com/codeflow?start=158&length=5)

What about the other elements ?

2022-02-23 20:38 UTC, neildsh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/FindQueryMetrics.cs
> +        public readonly List<double> RetrievedDocumentCount = new List<double>();
>public readonly List [](http://example.com/codeflow?start=8&length=20)

Do not use public mutable fields. Use immutable properties instead

2022-02-23 20:39 UTC, neildsh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/FindQueryMetrics.cs
> +        public class RequestTimeline
>public [](http://example.com/codeflow?start=8&length=6)

inner classes should not be public

2022-02-23 20:40 UTC, neildsh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/FindQueryMetrics.cs
> +        public readonly List<double> Completed = new List<double>();
please use an immutable class with a builder rather than these thirteen lists

2022-02-23 20:41 UTC, neildsh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/FindQueryMetrics.cs
> +                    if (transportStats.RequestTimeline[0].Event == "Created")
>"Created" [](http://example.com/codeflow?start=67&length=9)

Please use constants

2022-02-23 20:43 UTC, neildsh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/FindQueryMetrics.cs
> +                if (storeResponse.StoreResult.StatusCode == StatusCodes.Ok)
>storeResponse.StoreResult.StatusCode == StatusCodes.Ok [](http://example.com/codeflow?start=20&length=54)

Please track the other status codes as well

2022-02-23 20:49 UTC, neildsh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/FindQueryMetrics.cs
> +    class FindMetrics : ITraceDatumVisitor
>FindMetrics [](http://example.com/codeflow?start=10&length=11)

consider changing the name to `QueryStatisticsAccumulator`

2022-02-23 20:50 UTC, neildsh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/FindQueryMetrics.cs
> +            public double DurationInMs { get; set; }
>double [](http://example.com/codeflow?start=19&length=6)

`TimeSpan`

2022-02-23 20:51 UTC, neildsh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +                        this.ContentSerialization,
please use named arguments

2022-02-23 20:52 UTC, neildsh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +            this.EndtoEndTime.Add(stopwatch.ElapsedMilliseconds);
this should be inside the loop above

2022-02-23 20:52 UTC, neildsh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +                    break;
> break; [](http://example.com/codeflow?start=19&length=7)

loop executes only once

2022-02-23 20:53 UTC, neildsh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +                    break;
>break; [](http://example.com/codeflow?start=20&length=6)

loop executes only once

2022-02-23 20:54 UTC, neildsh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +            ITrace Poco = BinaryPerf.FindQueryClientMetrics(Trace, "POCO Materialization");
>"POCO Materialization" [](http://example.com/codeflow?start=67&length=22)

please use constants

2022-02-23 20:54 UTC, neildsh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +            ITrace GetCosmosElementResponse = BinaryPerf.FindQueryClientMetrics(Trace, "Get Cosmos Element Response");
>"Get Cosmos Element Response" [](http://example.com/codeflow?start=87&length=29)

please use constants

2022-02-23 20:56 UTC, neildsh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +        private readonly FindMetrics FindMetrics = new FindMetrics();
>FindMetrics [](http://example.com/codeflow?start=37&length=11)

Please follow the coding conventions used in this repository:

members and local variables are camel cased.
names should be descriptive
constants are pascal cased etc.

everywhere

2022-02-23 21:01 UTC, neildsh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +                    return node;
>return node; [](http://example.com/codeflow?start=20&length=12)

This only processes the first query metrics that is found

2022-02-23 21:02 UTC, neildsh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +                if (node.Data.ContainsKey("Client Side Request Stats") & node.Name == "Microsoft.Azure.Documents.ServerStoreModel Transport Request")
>& [](http://example.com/codeflow?start=71&length=1)

this is a bitwise and. Please use the logical and: `&&`

2022-02-23 21:05 UTC, neildsh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +            return null;
>null [](http://example.com/codeflow?start=19&length=4)

do not return `null`. Instead we should have some error propagation

2022-02-23 23:17 UTC, hdetroja commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +                return;
Done

2022-02-23 23:20 UTC, hdetroja commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +                    FeedResponse<dynamic> response = await iterator.ReadNextAsync();
Done

2022-02-23 23:22 UTC, hdetroja commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/FindQueryMetrics.cs
> +        public class RequestTimeline
Done

2022-02-23 23:32 UTC, hdetroja commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/FindQueryMetrics.cs
> +    class FindMetrics : ITraceDatumVisitor
Done

2022-02-23 23:36 UTC, hdetroja commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +                    break;
fixed

2022-02-23 23:37 UTC, hdetroja commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +                    return node;
fixed

2022-02-23 23:37 UTC, hdetroja commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +                if (node.Data.ContainsKey("Client Side Request Stats") & node.Name == "Microsoft.Azure.Documents.ServerStoreModel Transport Request")
Done

2022-02-23 23:39 UTC, neildsh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +        }
please do not repeat code, use an appropriate parameter for the method

2022-02-23 23:44 UTC, neildsh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +        private readonly List<double> GetCosmosElementResponseTime = new List<double>();
These do not need to be members

2022-02-23 23:45 UTC, neildsh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +            if(this.FindMetrics.RetrievedDocumentCount.Count > 20)
>if(this.FindMetrics.RetrievedDocumentCount.Count > 20)  [](http://example.com/codeflow?start=12&length=55)

why is this required?

2022-02-23 23:45 UTC, neildsh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +            Console.WriteLine((double)this.FindMetrics.RetrievedDocumentCount.Count / 20);
>20 [](http://example.com/codeflow?start=86&length=2)

avoid magic numbers

2022-02-24 00:12 UTC, neildsh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +            }
Avoid serializing by hand, as recommended in the other file, please use a strong type and use a built in serializer like System.Text.Json

2022-02-24 00:15 UTC, neildsh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +            Console.WriteLine(this.CalculateMedian(this.GetCosmosElementResponseTime));
Pass a stream to a serializer and avoid repeating code: 

` Task SerializeAsync(QueryperformanceMetrics metrics, Stream stream)`

Now the same method can be used for a file as well as the Console

2022-02-24 00:16 UTC, neildsh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +            AvgList = AvgList.GetRange(this.WarmupRounds, AvgList.Count - this.WarmupRounds);
>AvgList.GetRange(this.WarmupRounds, AvgList.Count - this.WarmupRounds); [](http://example.com/codeflow?start=22&length=71)

Avoid mixing concerns: a method that calculates average should not silently ignore part of its input

2022-02-24 00:17 UTC, neildsh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +            MedianList = MedianList.GetRange(this.WarmupRounds, MedianList.Count - this.WarmupRounds);
> MedianList = MedianList.GetRange(this.WarmupRounds, MedianList.Count - this.WarmupRounds); [](http://example.com/codeflow?start=11&length=91)

same as above:

Avoid mixing concerns: a method that calculates median should not silently ignore part of its input, and it should not mutate its input

2022-02-24 00:32 UTC, neildsh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/FindQueryMetrics.cs
> +            public string Event { get; set; }
>string [](http://example.com/codeflow?start=19&length=6)

`enum EventType`

2022-02-24 00:34 UTC, neildsh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +    public class BinaryVsTextPerfTest
>BinaryVsTextPerfTest [](http://example.com/codeflow?start=17&length=20)

Consider `ContentSerializationPerformanceTests`

2022-02-24 00:35 UTC, neildsh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +        private readonly string ContentSerialization = "JsonText";
>readonly [](http://example.com/codeflow?start=16&length=8)

`const`

2022-02-24 15:50 UTC, j82w commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +                await this.RunQueryAsync(container, this.Query);
This will give skew the data because it is including the cost of initializing the cache and creating connections. It should do multiple iterations that are ignored to warmup the SDK.

2022-02-24 15:50 UTC, j82w commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +            for (int i = 0; i < this.NumberOfIterations; i++)
This won't show a realistic impact to users because this is only doing a single query at a time.  The issue with sending binary is the SDK is now forced to convert it back to text so the JSON serializer can understand it. That will add additional CPU overhead to each query. With only a single query running at a time the CPU can handle the additional overhead without impacting latency too much. This will cause the throughput of the SDK to drop significantly because it will not be able to process as many requests in parallel as before.

2022-02-24 17:29 UTC, hdetroja commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +                await this.RunQueryAsync(container, this.Query);
the warmup iterations are ignored, that logic is in the CalculateAverage method. Moving that logic to different place as recommended by Neil.

2022-02-24 17:31 UTC, hdetroja commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +    public class BinaryVsTextPerfTest
Done

2022-02-24 17:34 UTC, hdetroja commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +        private readonly string ContentSerialization = "JsonText";
Done

2022-02-24 17:34 UTC, hdetroja commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +            Console.WriteLine((double)this.FindMetrics.RetrievedDocumentCount.Count / 20);
Done

2022-02-24 17:41 UTC, hdetroja commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +            if(this.FindMetrics.RetrievedDocumentCount.Count > 20)
if there are multiple round trips the count would be greater than the number of iterations, this would print only the distinct values in those round trips.

2022-02-24 17:46 UTC, j82w commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +                await this.RunQueryAsync(container, this.Query);
How is this being handled for scenarios where it is not using the average like this? 
Console.WriteLine((double)this.FindMetrics.TotalQueryExecutionTime.Count / 20);

2022-02-24 17:48 UTC, j82w commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +        private readonly int WarmupRounds = 3;
There are 4 replicas that are randomly selected from for each request. Doing only 3 rounds of warmups won't even open  up connections to all replicas. This number should be higher like 10 to to avoid connections being created.

2022-02-24 17:49 UTC, hdetroja commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +                await this.RunQueryAsync(container, this.Query);
yes, it is not being handled in those cases so moving the ignoring warmup iterations logic from CalculateAverage method to some place else where it will be used.

2022-02-24 17:51 UTC, hdetroja commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +        private readonly int WarmupRounds = 3;
Increasing it to a higher number.

2022-02-24 18:08 UTC, hdetroja commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +        }
Done

2022-02-28 12:01 UTC, j82w commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/FindQueryMetrics.cs
> +        public readonly List<double> RetrievedDocumentCount = new List<double>();
Immutable adds a lot of overhead. I would recommend only using immutable if it is a singleton. Instead use the IReadOnlyList.

2022-02-28 19:55 UTC, hdetroja commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/FindQueryMetrics.cs
> +                ClientSideRequestStatisticsTraceDatum.StoreResponseStatistics storeResponse = clientSideRequestStatisticsTraceDatum.StoreResponseStatisticsList[0];
Done

2022-02-28 19:55 UTC, hdetroja commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +                    FeedResponse<dynamic> response = await iterator.ReadNextAsync();
Done

2022-02-28 19:56 UTC, hdetroja commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/FindQueryMetrics.cs
> +                if (storeResponse.StoreResult.StatusCode == StatusCodes.Ok)
Done

2022-02-28 19:56 UTC, hdetroja commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +            this.EndtoEndTime.Add(stopwatch.ElapsedMilliseconds);
Done

2022-02-28 22:23 UTC, hdetroja commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BinaryVsTextPerfTest.cs
> +            AvgList = AvgList.GetRange(this.WarmupRounds, AvgList.Count - this.WarmupRounds);
Done

2022-03-31 22:17 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContentSerializationPerformanceTests.cs
> +            cosmosDatabase = client.GetDatabase(cosmosDatabaseId);
>cosmosDatabase [](http://example.com/codeflow?start=12&length=14)

Please demote this static field to a local variable.

2022-03-31 22:25 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContentSerializationPerformanceTests.cs
> +                string endpoint = System.Configuration.ConfigurationManager.AppSettings["GatewayEndpoint"];
Do we have an option of checking in an example configuration file pointing to local emulator like in case of query oracle?

[https://msdata.visualstudio.com/_git/CosmosDB?path=/Product/Tools/QueryOracle/UnitTests/App.Config&version=GBmaster&line=3&lineEnd=9&lineStartColumn=3&lineEndColumn=17&lineStyle=plain&_a=contents](https://msdata.visualstudio.com/_git/CosmosDB?path=/Product/Tools/QueryOracle/UnitTests/App.Config&version=GBmaster&line=3&lineEnd=9&lineStartColumn=3&lineEndColumn=17&lineStyle=plain&_a=contents)

2022-03-31 23:21 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContentSerializationPerformanceTests.cs
> +    public class ContentSerializationPerformanceTests
>ContentSerializationPerformanceTests [](http://example.com/codeflow?start=17&length=36)

Move to master repo, with internal visibility?

2022-03-31 23:23 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryStatisticsAccumulatorBuilder.cs
> +    public List<double> badRequestCompletedList = new();
Instead of having separate disconnected lists, consider capturing each data point into a structure:

class
{
RetrievedDocumentCOuntList;
RetrievedDocumentSizeList;
. . .
. . .
BadRequestCOmpletedList;
}

2022-03-31 23:35 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContentSerializationPerformanceTests.cs
> +                {
Please abstract this as a format and not special case for a specific writer.

2022-03-31 23:37 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContentSerializationPerformanceTests.cs
> +            string backendNodeValue = "[,FF) move next";
>[,FF) move next [](http://example.com/codeflow?start=39&length=15)

Make this more robust.

2022-03-31 23:40 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContentSerializationPerformanceTests.cs
> +            using (TextWriter rawDataFile = new StreamWriter(rawDataPath))
>using [](http://example.com/codeflow?start=12&length=5)

Nit: Newline before.

2022-03-31 23:43 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContentSerializationPerformanceTests.cs
> +            {
sql.Contains("distinct", StringCOmparison.OrdinalIgnoreCase);

2022-03-31 23:46 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContentSerializationPerformanceTests.cs
> +                        distinctQueryStopwatch.Start();
>distinctQueryStopwatch [](http://example.com/codeflow?start=24&length=22)

Separate stopwatch for inclusive and exclusive times?

2022-04-01 00:02 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContentSerializationPerformanceTests.cs
> +        private const string query = "";
>private const string query = ""; [](http://example.com/codeflow?start=8&length=32)

2 options as discussed during the meeting:
Either queries come from a configuration file.
Or have a set of tests here for each query that we want to benchmark.
I am ok to go with either one as first cut.

2022-04-01 00:02 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContentSerializationPerformanceTests.cs
> +        private const string contentSerialization = "";
Maybe these need to come from a configuration file?

2022-04-01 00:02 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContentSerializationPerformanceTests.cs
> +        private const int warmupIterations = 10;
Part of configuration file?

2022-04-01 00:04 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContentSerializationPerformanceTests.cs
> +            {
Curious question: Is try...catch strictly required since the test will fail without it just as well? I am fine with having it if you need this for better interaction with the test.
I thought that if the test failed with an exception, you also get a clickable callstack regardless.

2022-04-01 00:05 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContentSerializationPerformanceTests.cs
> +            string rawDataPath = "";
Please make sure you have file names here.

2022-04-01 00:06 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContentSerializationPerformanceTests.cs
> +            for (int i = 0; i < numberOfIterations; i++)
>numberOfIterations [](http://example.com/codeflow?start=32&length=18)

Since this is configuration based, you may need to pass it in.

2022-04-01 00:10 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContentSerializationPerformanceTests.cs
> +            }
Nit, consider named parameter for literal values for readability:

this.SerializeAsync(rawDataFile, this.queryStatisticsAccumulator, rawData:true);

2022-04-01 00:14 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContentSerializationPerformanceTests.cs
> +        }
Please move this into a separate class of its own.

2022-04-01 00:17 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContentSerializationPerformanceTests.cs
> +        }
Curious - how are these getting used?

2022-04-01 00:17 UTC, adityasa requested changes
:clock1:

2022-04-13 22:02 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContentSerializationPerformanceTests.cs
> +    internal class SerializeData : ContentSerializationPerformanceTests
I would move this to a separate file.

2022-04-13 22:02 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContentSerializationPerformanceTests.cs
> +        /*private List<double> CalculateMedian(List<QueryMetrics> getMedianList)
Remove if not required.

2022-04-13 22:06 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContentSerializationPerformanceTests.cs
> +            string rawDataPath = "RawData.csv";
>"RawData.csv" [](http://example.com/codeflow?start=33&length=13)

Generally speaking, this is a bit risky since you can end up overwriting an existing file either now owned by this test/code or the result of previous run. Consider pre-pending the test class name, to help alleviate part of problem.

2022-04-13 22:06 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContentSerializationPerformanceTests.cs
> +                    /*textWriter.WriteLine("Median");
Remove if not required.

2022-04-13 22:06 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryStatisticsAccumulatorBuilder.cs
> +    public QueryMetrics queryMetrics = new();
>QueryMetrics [](http://example.com/codeflow?start=11&length=12)

Neat.

2022-04-13 22:07 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryStatisticsAccumulatorBuilder.cs
> +internal class QueryMetrics
>QueryMetrics [](http://example.com/codeflow?start=15&length=12)

Move to a separate file.

2022-04-13 22:12 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContentSerializationPerformanceTests.cs
> +        private readonly int warmupIterations = int.Parse(System.Configuration.ConfigurationManager.AppSettings["WarmupIterations"]);
Generally, it's preferred to do all the assignments in a constructor (single place).

2022-04-13 22:37 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContentSerializationPerformanceTests.cs
> +    internal class FetchMetrics : ContentSerializationPerformanceTests
Separate file.

2022-04-13 22:37 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContentSerializationPerformanceTests.cs
> +    internal class FetchMetrics : ContentSerializationPerformanceTests
>ContentSerializationPerformanceTests [](http://example.com/codeflow?start=34&length=36)

Why do you need this inheritance?

2022-04-13 22:38 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContentSerializationPerformanceTests.cs
> +    internal class FetchMetrics : ContentSerializationPerformanceTests
>FetchMetrics [](http://example.com/codeflow?start=19&length=12)

Use nouns for class name (and verb for method names).

2022-04-13 23:00 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContentSerializationPerformanceTests.cs
> +        private List<ITrace> FindQueryMetrics(ITrace trace, string nodeName = null, string keyName = null)
>private List<ITrace> FindQueryMetrics(ITrace trace, string nodeName = null, string keyName = null) [](http://example.com/codeflow?start=8&length=98)

I would turn this into something like following:
private List<ITrace> FindQueryMetrics(ITrace trace, string nodeOrKey, bool findNode)

2022-04-13 23:14 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContentSerializationPerformanceTests.cs
> +        private ITrace FindQueryClientMetrics(ITrace trace, string nodeName)
>FindQueryClientMetrics [](http://example.com/codeflow?start=23&length=22)

This doesn't look that much different from prior method:FindQueryMetrics

2022-04-13 23:14 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContentSerializationPerformanceTests.cs
> +        private ITrace FindQueryClientMetrics(ITrace trace, string nodeName)
Any chance you can share code or have single method do both?

2022-04-14 17:20 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContentSerializationPerformanceTests.cs
> +            if (sql.Contains("distinct", StringComparison.OrdinalIgnoreCase))
>sql.Contains("distinct", StringComparison.OrdinalIgnoreCase) [](http://example.com/codeflow?start=16&length=60)

Please make this a part of test configuration to indicate whether to use a strongly typed iterator or not.

2022-04-14 17:23 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContentSerializationPerformanceTests.cs
> +            }
using (FeedIterator iterator = this.CreateIterator(test))
{
   await this.GetIteratorResponse(iterator);
}

GetIterator(test) =>test.UseStronglyTyped? new FeedIterator<States> ... : new FeedIterator<dynamic> . ..

2022-04-14 17:37 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContentSerializationPerformanceTests.cs
> +                    textWriter.WriteLine();
Consider extension method:

textWriter.WriteLines(line1, line2, line3);

internal static class TextWriterExtensions
{
   public static void WriteLines(this TextWriter textWriter, params string[] lines)
   {
     foreach (string line in lines)
     {
         textWriter.WriteLine(line);
     }
   }
}

2022-04-14 17:39 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContentSerializationPerformanceTests.cs
> +            avgList.Add(getAverageList.Average(metric => metric.Completed));
Same as below. Consider using AddRange or a dedicated method with a loop.

2022-04-19 18:40 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/FeedResponseObjectStates.cs
> +    [JsonProperty(PropertyName = "id")]
>[ [](http://example.com/codeflow?start=4&length=1)

Newline before please.

2022-04-19 18:41 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/FeedResponseObjectStates.cs
> +    public static string PartitionKeyPath => "/myPartitionKey";
>string [](http://example.com/codeflow?start=18&length=6)

readonly string.

2022-04-19 18:42 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/FeedResponseObjectStates.cs
> +    public static string PartitionKeyPath => "/myPartitionKey";
>PartitionKeyPath [](http://example.com/codeflow?start=25&length=16)

Is this required? I don't see any references.

2022-04-19 18:42 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/FeedResponseObjectStates.cs
> +    public static string PartitionKeyPath => "/myPartitionKey";
I would move it to the class that makes use of this (and mark private if that's the only class using it).

2022-04-19 18:43 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/FeedResponseObjectRecipientList.cs
> +    [JsonProperty(PropertyName = "city")]
>[ [](http://example.com/codeflow?start=4&length=1)

Newline before please. Same for remaining properties.

2022-04-19 18:43 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/FeedResponseObjectTags.cs
> +    [JsonProperty(PropertyName = "numbers")]
Newline before please. Same for remaining properties.

2022-04-19 18:44 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsSerializer.cs
> +internal class MetricsSerializer
>MetricsSerializer [](http://example.com/codeflow?start=15&length=17)

Cool.

2022-04-19 18:44 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsAccumulator.cs
> +        string transportKeyValue = "Client Side Request Stats";
>string [](http://example.com/codeflow?start=8&length=6)

Newline before please.

2022-04-19 18:44 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsAccumulator.cs
> +        string clientParseTimeNode = "POCO Materialization";
Newline before please.

2022-04-19 18:44 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsAccumulator.cs
> +        string clientDeserializationTimeNode = "Get Cosmos Element Response";
Newline before please.

2022-04-19 18:44 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsAccumulator.cs
> +        return queryMetricsNodes;
Newline before please.

2022-04-19 18:45 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsSerializer.cs
> +        return medianList;
Newline before please.

2022-04-19 18:45 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsSerializer.cs
> +        return sumOfRoundTripsList;
Newline before please.

2022-04-19 18:48 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/QueryStatisticsAccumulator.cs
> +        {
Newline before please.

2022-04-19 18:53 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/QueryStatisticsAccumulator.cs
> +                        if (transportStats.RequestTimeline[0].Event == RequestTimeline.EventType.Created)
>transportStats.RequestTimeline[0].Event == RequestTimeline.EventType.Created [](http://example.com/codeflow?start=28&length=76)

This and all the if conditions in this method below seem a bit too restrictive. What happens if we start returning the events in a different order or add more events?

I *believe* you only care about the event types to match them with corresponding metric. More specifically I don't think you care that first event be Created. If that's the case, you simply need to line them up by their names. This can be done in a for loop as well:

for (int i =0; i< numberOfEvents;i++)
{
  switch (RequestTimeline[i].Event)
  {
    case Created:
        queryMetrics.Created = RequestTimeline[i].DurationInMs;
break;
   . . .
   default:
      Console.WriteLine($"Unknown event ignored : '{RequestTimeline[i].Event}'");
    break;
  }
}

2022-04-19 18:56 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/QueryStatisticsAccumulatorBuilder.cs
> +internal class QueryStatisticsAccumulatorBuilder
>QueryStatisticsAccumulatorBuilder [](http://example.com/codeflow?start=15&length=33)

QueryStatisticsBuilder may be sufficient (instead of having 2 actor nouns in the name).

2022-04-19 18:57 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/QueryStatisticsAccumulatorBuilder.cs
> +    public List<QueryMetrics> QueryMetricsList { get; set; } = new List<QueryMetrics>();
public QueryMetrics QueryMetrics { get; } = new();

Always use properties for access from outside the class.

2022-04-19 18:58 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/QueryStatisticsAccumulatorBuilder.cs
> +    public List<QueryMetrics> QueryMetricsList { get; set; } = new List<QueryMetrics>();
>set; [](http://example.com/codeflow?start=54&length=4)

Is a setter necessary?

2022-04-19 18:58 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/QueryStatisticsAccumulator.cs
> +            }
Newline before please.

2022-04-19 18:58 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/TextWriterExtension.cs
> +    public static void WriteLines(this TextWriter textWriter, params double[] metrics)
>WriteLines [](http://example.com/codeflow?start=23&length=10)

Nit, WriteMetrics ?

2022-04-19 19:01 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/QueryStatisticsAccumulator.cs
> +    internal class QueryStatisticsAccumulator : ITraceDatumVisitor
>QueryStatisticsAccumulator [](http://example.com/codeflow?start=19&length=26)

QueryStatisticsDatumVisitor may be better. Derived classes typically share a common postfix with their base class.

2022-04-19 19:06 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/QueryStatisticsAccumulator.cs
> +            this.queryStatisticsAccumulatorBuilder.queryMetrics.RetrievedDocumentCount = queryMetricsTraceDatum.QueryMetrics.BackendMetrics.RetrievedDocumentCount;
>queryMetrics [](http://example.com/codeflow?start=51&length=12)

I would reinitialize the queryMetrics field to a new object before setting these values. Especially important in cases when subsequent iteration has a missing metric and you don't want to accidently use a value from previous iteration (since we don't abort in case of missing data).

2022-04-19 19:07 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/QueryStatisticsAccumulator.cs
> +                });
If you re-initialize queryMetrics to new object at the top level Visit method (see comment above), no need to create new object, simply add it here to the list as is.

2022-04-19 19:10 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/QueryStatisticsAccumulator.cs
> +    using System.Runtime.Serialization;
Please ensure consistency across files : either put usings on top of the file (outside the namespace) or put them inside the top level namespace before any other declaration.

I would personally vote for putting them all on top of the file, outside any namespace.

2022-04-19 19:14 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsAccumulator.cs
> +        List<ITrace> backendMetrics = this.FindQueryMetrics(trace: trace, nodeNameOrKeyName: backendKeyValue, hasKey: true);
>List<ITrace> backendMetrics = this.FindQueryMetrics [](http://example.com/codeflow?start=8&length=51)

Ensure that FindQueryMetrics _always_ returns a non-null List<ITrace>. If it couldn't find any, it returns an empty, but non-null list. Callers can then use this contract and skip the unnecessary null checks.

This comment is applicable not just for FindQueryMetrics but most such contracts that return a collection.

2022-04-19 19:15 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsAccumulator.cs
> +                    queryStatisticsAccumulator.Visit((QueryMetricsTraceDatum)kvp.Value);
>(QueryMetricsTraceDatum)kvp.Value [](http://example.com/codeflow?start=53&length=33)

Is this hard cast guaranteed to succeed?

2022-04-19 19:18 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsAccumulator.cs
> +                    queryStatisticsAccumulator.Visit((QueryMetricsTraceDatum)kvp.Value);
>queryStatisticsAccumulator.Visit((QueryMetricsTraceDatum)kvp.Value); [](http://example.com/codeflow?start=20&length=68)

This isn't the best way to invoke the visitor method. You might want to invert the call, to avoid hard cast to most specific type:

Debug.Assert(kvp.Value is TraceDatum, "Unexpected type!");
((TraceDatum)kvp.Value).Accept(queryStatisticsAccumulator);

2022-04-21 17:19 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsSerializer.cs
> +        private readonly Func<QueryMetrics, double>[] metricsDelegate = new Func<QueryMetrics, double>[] { metric => metric.RetrievedDocumentCount,
I would keep each func declaration on a separate line.

2022-04-21 17:21 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsAccumulator.cs
> +                        case TraceDatum:
>case TraceDatum: [](http://example.com/codeflow?start=24&length=16)

case TraceDatum traceDatum:
    traceDatum.Accept(queryStatisticsDatumVisitor);
    break;

2022-04-21 17:22 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsAccumulator.cs
> +                            Console.WriteLine("Unexpected trace type");
>"Unexpected trace type" [](http://example.com/codeflow?start=46&length=23)

$"Unexpected type {kvp.Value.GetType()}"

2022-04-21 17:26 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/QueryStatisticsAccumulator.cs
> +    internal class QueryStatisticsAccumulator
The class is no longer needed.

2022-04-21 17:27 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/QueryStatisticsAccumulator.cs
> +        public List<QueryMetrics> QueryMetricsList { get; } = new();
>List<QueryMetrics> [](http://example.com/codeflow?start=15&length=18)

You can have a private readonly field on QueryStatisticsDatumVisitor of this type. All write operations in that class can use the field.

You can then expose the field as a readonly property (IReadOnlyList<QueryMetrics QueryMetricsList {get ... }) from that class for consumption in QueryMetrics class.

2022-04-21 17:30 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/ContentSerializationPerformanceTests.cs
> +        public ContentSerializationPerformanceTests()
Newline before please.

2022-04-21 17:31 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/ContentSerializationPerformanceTests.cs
> +        private readonly QueryStatisticsDatumVisitor queryStatisticsDatumVisitor = new();
> = new() [](http://example.com/codeflow?start=80&length=8)

Nit, initialize in single place with other fields (constructor).

2022-04-21 17:34 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/ContentSerializationPerformanceTests.cs
> +            string rawDataPath = "ContentSerializationPerformanceTestsRawData.csv";
You can do rawDataPath = Path.GetFullPath("..."); so that it's clear what the value is (especially during debugging).

2022-04-21 17:39 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsAccumulator.cs
> +        public void GetTrace<T>(FeedResponse<T> Response, QueryStatisticsDatumVisitor queryStatisticsDatumVisitor)
>GetTrace [](http://example.com/codeflow?start=20&length=8)

I would rename this to something like ExtractMetrics or ReadFromTrace.

2022-04-21 17:41 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/ContentSerializationPerformanceTests.cs
> +            this.queryStatisticsDatumVisitor.queryMetrics.EndToEndTime = totalTime.ElapsedMilliseconds - getTraceTime.ElapsedMilliseconds;
>queryMetrics [](http://example.com/codeflow?start=45&length=12)

Instead of exposing queryMetrics, just expose a method to do this. Something like:

public void Finish(long totalTime)

2022-04-21 17:46 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsAccumulator.cs
> +            string clientDeserializationTimeNode = "Get Cosmos Element Response";
Move these as private const string fields on top of the class.

2022-04-21 17:46 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsAccumulator.cs
> +            string transportKeyValue = "Client Side Request Stats";
Move these as private const string fields on top of the class.

2022-04-21 17:48 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsAccumulator.cs
> +                else if (node.Name == nodeNameOrKeyName)
>(node.Name == nodeNameOrKeyName [](http://example.com/codeflow?start=24&length=31)

Better if you combine this condition (||) with prior if.

2022-04-21 17:49 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsAccumulator.cs
> +                }
>} [](http://example.com/codeflow?start=16&length=1)

What should happen in the else case? Are we potentially missing data?

2022-04-21 17:50 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsSerializer.cs
> +            else
No newline.

2022-04-21 17:50 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsSerializer.cs
> +                textWriter.Close();
Can be outside if...else.

2022-04-21 17:50 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsSerializer.cs
> +                textWriter.Close();
Can be outside if...else.

2022-04-21 17:51 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsSerializer.cs
> +                textWriter.WriteLine("Median");
>"Median" [](http://example.com/codeflow?start=37&length=8)

private readonly const fields on top of the class.

2022-04-21 17:51 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsSerializer.cs
> +                textWriter.WriteLine("QueryMetrics");
>"QueryMetrics" [](http://example.com/codeflow?start=37&length=14)

private readonly const fields on top of the class.

2022-04-21 17:51 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsSerializer.cs
> +                textWriter.WriteLine("BadRequest");
>"BadRequest" [](http://example.com/codeflow?start=37&length=12)

private readonly const fields on top of the class.

2022-04-21 17:51 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/QueryStatisticsDatumVisitor.cs
> +
Nit, new newline after.

2022-04-21 17:52 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/QueryStatisticsDatumVisitor.cs
> +        private readonly int numberOfEvents = 6;
>readonly [](http://example.com/codeflow?start=16&length=8)

const.

2022-04-21 17:53 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/RequestTimeline.cs
> +            [EnumMember(Value = "Transit Time")]
Newline before may be better.

2022-04-21 17:54 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/TransportStats.cs
> +        public List<RequestTimeline> RequestTimeline { get; set; }
>set [](http://example.com/codeflow?start=60&length=3)

Do you need the setter? Or can you just initialize like before:
         List<RequestTimeline> RequestTimeline { get; } = new();

2022-04-21 17:54 UTC, adityasa requested changes
:clock1:

2022-04-22 18:52 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/testhost.dll.config
> +		<add key="MasterKey" value=""/>
Curious question: any reason why these are removed? 
I wouldn't checkin keys to a production account but emulator may be ok, especially if they were already not present (not added by you) ?

2022-04-22 18:57 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/ContentSerializationPerformanceTests.cs
> +            Console.WriteLine(rawDataPath);
>rawDataPath [](http://example.com/codeflow?start=30&length=11)

A meaningful message indicating what this file path is would be nice. :)

2022-04-22 19:01 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsAccumulator.cs
> +                if ((hasKey && node.Data.ContainsKey(nodeNameOrKeyName)) || node.Name == nodeNameOrKeyName)
>node.Name == nodeNameOrKeyName [](http://example.com/codeflow?start=76&length=30)

Putting this on a newline indented right below previous condition would make this more readable.

2022-04-22 19:04 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/QueryStatisticsDatumVisitor.cs
> +        private const int numberOfEvents = 6;
Each of these should be grouped together:
consts
statics
instances

2022-04-22 19:06 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/ContentSerializationPerformanceTests.cs
> +            string rawDataPath = Path.GetFullPath("ContentSerializationPerformanceTestsRawData.csv");
>"ContentSerializationPerformanceTestsRawData.csv" [](http://example.com/codeflow?start=50&length=49)

A const on top of the class would be nice.

2022-04-22 19:07 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/ContentSerializationPerformanceTests.cs
> +            else
No newline between else and previous closing brace }.

2022-04-22 19:11 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsAccumulator.cs
> +        private const string backendKeyValue = "Query Metrics";
>backendKeyValue [](http://example.com/codeflow?start=29&length=15)

As a convention, const fields start with capital letter for e.g. BackendKeyValue. Same for all other consts.

2022-04-22 19:14 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsSerializer.cs
> +                List<QueryMetrics> metricsPerRoundTrip = new();
>List<QueryMetrics> metricsPerRoundTrip [](http://example.com/codeflow?start=16&length=38)

No need to create and initialize here. Just inline declaration at line 75?

2022-04-22 19:17 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/QueryStatisticsDatumVisitor.cs
> +        public IReadOnlyList<QueryMetrics> QueryMetricsList => this.queryMetricsList;
Newline before, since this is a property.

2022-04-22 19:19 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/QueryStatisticsDatumVisitor.cs
> +        }
Does this ever get invoked or is expected to? If not, consider adding Debug.Fail("QueryStatisticsDatumVisitor Assert", "CpuHistoryTraceDatum is not supported");

Same for methods below.

2022-04-22 19:19 UTC, adityasa approved these changes
:shipit:

2022-04-22 22:43 UTC, hdetroja commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/testhost.dll.config
> +		<add key="MasterKey" value=""/>
No particular reason to remove these, I can keep them as they were.

2022-04-26 23:52 UTC, sboshra commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/ContentSerializationPerformanceTests.cs
> +
move this above the readonly fields and add a separator line

2022-04-27 00:06 UTC, sboshra commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsAccumulator.cs
> +            List<ITrace> poco = this.FindQueryMetrics(trace: trace, nodeNameOrKeyName: ClientParseTimeNode, hasKey: false);
>poco [](http://example.com/codeflow?start=25&length=4)

queryMetricsTraces

2022-04-27 00:06 UTC, sboshra commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsAccumulator.cs
> +            List<ITrace> getCosmosElementResponse = this.FindQueryMetrics(trace: trace, nodeNameOrKeyName: ClientDeserializationTimeNode, hasKey: false);
>getCosmosElementResponse [](http://example.com/codeflow?start=25&length=24)

retrieveCosmosElementTraces

2022-04-27 00:08 UTC, sboshra commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsAccumulator.cs
> +                            break;
Debug.Fail()

2022-04-27 00:12 UTC, sboshra commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsAccumulator.cs
> +        private List<ITrace> FindQueryMetrics(ITrace trace, string nodeNameOrKeyName, bool hasKey)
>hasKey [](http://example.com/codeflow?start=91&length=6)

isKeyName

2022-04-27 00:12 UTC, sboshra commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsAccumulator.cs
> +                     node.Name == nodeNameOrKeyName)
>node.Name == nodeNameOrKeyNam [](http://example.com/codeflow?start=21&length=29)

()

2022-04-27 00:21 UTC, sboshra commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsSerializer.cs
> +        public void SerializeAsync(TextWriter textWriter, QueryStatisticsDatumVisitor queryStatisticsDatumVisitor, int numberOfIterations, int warmupIterations, bool rawData)
>SerializeAsync [](http://example.com/codeflow?start=20&length=14)

Serialize

2022-04-27 00:22 UTC, sboshra commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsSerializer.cs
> +        }
you shouldn't close it by yourself

2022-04-27 00:24 UTC, sboshra commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/QueryStatisticsDatumVisitor.cs
> +        private readonly QueryMetrics queryMetrics = new();
Consider moving the initialization into a constructor

2022-04-27 00:24 UTC, sboshra commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/QueryStatisticsDatumVisitor.cs
> +        public void AddPocoTime(double totalTime)
>totalTime [](http://example.com/codeflow?start=39&length=9)

time

2022-04-27 00:27 UTC, sboshra approved these changes
:shipit:

2022-04-27 23:07 UTC, KishanSingh77 approved these changes

2022-04-28 13:57 UTC, j82w commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/ContentSerializationPerformanceTests.cs
> +        private const string RawDataFileName = "ContentSerializationPerformanceTestsRawData.csv";
Can the PR description include the results of this test?

2022-04-28 13:57 UTC, j82w commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/ContentSerializationPerformanceTests.cs
> +            using (CosmosClient client = new CosmosClient(endpoint, authKey,
This should be in Microsoft.Azure.Cosmos.EmulatorTests instead of Microsoft.Azure.Cosmos.Tests. Microsoft.Azure.Cosmos.Tests contains all the unit tests. This requires the emulator so it should go in the emulator test project.

2022-05-02 18:24 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsAccumulator.cs
> +            List<ITrace> backendMetrics = this.FindQueryMetrics(trace: trace, nodeNameOrKeyName: BackendKeyValue, isKeyName: true);
>List<ITrace> backendMetrics = this.FindQueryMetrics(trace: trace, nodeNameOrKeyName: BackendKeyValue, isKeyName: true); [](http://example.com/codeflow?start=12&length=119)

Please add a comment before describing how many times per iteration, per roundtrip can this type of metric occur.

2022-05-02 18:25 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsAccumulator.cs
> +            List<ITrace> transitMetrics = this.FindQueryMetrics(trace: trace, nodeNameOrKeyName: TransportKeyValue, isKeyName: true, currentNodeName: TransportNodeName);
>List<ITrace> transitMetrics = this.FindQueryMetrics(trace: trace, nodeNameOrKeyName: TransportKeyValue, isKeyName: true, currentNodeName: TransportNodeName); [](http://example.com/codeflow?start=12&length=157)

Please add a comment before describing how many times per iteration, per roundtrip can this type of metric occur.

2022-05-02 18:25 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsAccumulator.cs
> +            List<ITrace> retrieveQueryMetricTraces = this.FindQueryMetrics(trace: trace, nodeNameOrKeyName: ClientParseTimeNode, isKeyName: false);
>List<ITrace> retrieveQueryMetricTraces = this.FindQueryMetrics(trace: trace, nodeNameOrKeyName: ClientParseTimeNode, isKeyName: false); [](http://example.com/codeflow?start=12&length=135)

Please add a comment before describing how many times per iteration, per roundtrip can this type of metric occur.

2022-05-02 18:25 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsAccumulator.cs
> +            List<ITrace> retrieveCosmosElementTraces = this.FindQueryMetrics(trace: trace, nodeNameOrKeyName: ClientDeserializationTimeNode, isKeyName: false);
>List<ITrace> retrieveCosmosElementTraces = this.FindQueryMetrics(trace: trace, nodeNameOrKeyName: ClientDeserializationTimeNode, isKeyName: false); [](http://example.com/codeflow?start=12&length=147)

Please add a comment before describing how many times per iteration, per roundtrip can this type of metric occur.

2022-05-02 18:29 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsAccumulator.cs
> +                }
I would rewrite this as follows:
if ((isKeyName && node.Data.ContainsKey(nodeNameOrKeyName) && (currentNodeName == null || node.Name == currentNodeName)) ||
                        (node.Name == nodeNameOrKeyName))
                    {
                        queryMetricsNodes.Add(node);
                    }
                    foreach (ITrace child in node.Children)
                    {
                        queue.Enqueue(child);
                    }

2022-05-02 18:30 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsAccumulator.cs
> +                        {
Please add a line describing this line.

2022-05-02 18:41 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsAccumulator.cs
> +                        }
I would rewrite this entire section (line 43-79) as follows:

int backendIncrement = clientSideRequestStatisticsTraceDatum.StoreResponseStatisticsList.Count > 1 ? 0 : 1;
foreach (ClientSideRequestStatisticsTraceDatum.StoreResponseStatistics storeResponse in clientSideRequestStatisticsTraceDatum.StoreResponseStatisticsList)
{
 if (storeResponse.StoreResult.StatusCode == StatusCodes.Ok)
 {
  backendAndClientMetrics.Add(Tuple.Create(retrieveCosmosElementTraces[k], backendMetrics[j], transitMetrics[i]));
  j++;
  k++;
 }
 else if (storeResponse.StoreResult.StatusCode != StatusCodes.Ok)
 {
  backendAndClientMetrics.Add(Tuple.Create<ITrace, ITrace, ITrace>(null, null, transitMetrics[i]));
 }
 
 i += backendIncrement;
}

2022-05-02 18:45 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsAccumulator.cs
> +            {
Before this line, what is the condition of i, j and k? Should they all be equal to their corresponding collection item counts?

i < transitMetrics.Count && j < backendMetrics.Count && k < retrieveCosmosElementTraces.Count

2022-05-02 19:12 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsAccumulator.cs
> +                            foreach (ClientSideRequestStatisticsTraceDatum.StoreResponseStatistics storeResponse in clientSideRequestStatisticsTraceDatum.StoreResponseStatisticsList)
>foreach (ClientSideRequestStatisticsTraceDatum.StoreResponseStatistics storeResponse in clientSideRequestStatisticsTraceDatum.StoreResponseStatisticsList) [](http://example.com/codeflow?start=28&length=154)

By the way, I don't think clientSideRequestStatisticsTraceDatum.StoreResponseStatisticsList.Count is > 1 here, due to check at line 43. Therefore technically you don't need a loop here.

Therefore you technically _never_ need a separate if...else (line 43 and 61 and instead go with a single foreach loop and increment i inside the loop.

2022-05-04 05:51 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsAccumulator.cs
> +                        //we add null values to the tuple as status codes other than Ok will not have data for query metrics and Get Cosmos Element Response
Nit, extra newline @ line 59.

2022-05-04 05:53 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsAccumulator.cs
> +                ClientSideRequestStatisticsTraceDatum clientSideRequestStatisticsTraceDatum = (ClientSideRequestStatisticsTraceDatum)kvp.Value;
>ClientSideRequestStatisticsTraceDatum clientSideRequestStatisticsTraceDatum = (ClientSideRequestStatisticsTraceDatum)kvp.Value; [](http://example.com/codeflow?start=16&length=127)

Please assert the type before casting.

2022-05-04 05:54 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsAccumulator.cs
> +                Debug.Assert(node.Data.Count == 1, "More values of transit metrics may be missing");
>More values of transit metrics may be missing [](http://example.com/codeflow?start=52&length=45)

Instead use:
"Exactly one transit metric expected".

2022-05-04 05:55 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsAccumulator.cs
> +                        //we add null values to the tuple as status codes other than Ok will not have data for query metrics and Get Cosmos Element Response
>as [](http://example.com/codeflow?start=58&length=2)

since.

2022-05-04 05:55 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsAccumulator.cs
> +                        //we add null values to the tuple as status codes other than Ok will not have data for query metrics and Get Cosmos Element Response
>//we [](http://example.com/codeflow?start=24&length=4)

// We

2022-05-04 05:55 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsAccumulator.cs
> +                        //we add null values to the tuple as status codes other than Ok will not have data for query metrics and Get Cosmos Element Response
>query metrics [](http://example.com/codeflow?start=111&length=13)

'query metrics'

2022-05-04 05:55 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsAccumulator.cs
> +                        //we add null values to the tuple as status codes other than Ok will not have data for query metrics and Get Cosmos Element Response
>Get Cosmos Element Response [](http://example.com/codeflow?start=129&length=27)

'Get Cosmos Element Response'

2022-05-04 05:58 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsAccumulator.cs
> +            Debug.Assert(i == transitMetrics.Count && j == backendMetrics.Count && k == retrieveCosmosElementTraces.Count, "Metrics data might be missing");
>Debug.Assert(i == transitMetrics.Count && j == backendMetrics.Count && k == retrieveCosmosElementTraces.Count, "Metrics data might be missing"); [](http://example.com/codeflow?start=12&length=144)

I would break this into 3 separate asserts:

Debug.Assert(i == transitMetrics.Count, "All 'transit metrics' must be grouped.");

likewise for other two types of metrics.

2022-05-04 05:58 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsAccumulator.cs
> +            {
A newline before please.

2022-05-04 06:02 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryPerfTest/MetricsAccumulator.cs
> +                    queryStatisticsDatumVisitor.AddGetCosmosElementResponseTime(metrics.Item1.Duration.TotalMilliseconds);
>metrics.Item1 [](http://example.com/codeflow?start=80&length=13)

Please assert before that this is not null either.

2022-05-10 23:06 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/QueryPerfTest/ContentSerializationPerformanceTests.cs
> +                    this.queryStatisticsDatumVisitor.PopulateMetrics();
Since it's crucial to do this at the end of the iteration, I will move this outside the while loop.

2022-05-10 23:16 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/QueryPerfTest/MetricsAccumulator.cs
> +            foreach (ITrace queryMetricTrace in retrieveQueryMetricTraces)
Code should reflect the comment. foreach should be replaced by Debug.Assert followed by a single statement indexing sole item from the list.

2022-05-10 23:16 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/QueryPerfTest/MetricsAccumulator.cs
> +            List<ITrace> retrieveQueryMetricTraces = this.FindQueryMetrics(trace: trace, nodeNameOrKeyName: ClientParseTimeNode, isKeyName: false);
>retrieveQueryMetricTraces [](http://example.com/codeflow?start=25&length=25)

I would rename this more specifically like pocoTraces.

2022-05-10 23:17 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/QueryPerfTest/MetricsAccumulator.cs
> +        private const string ClientParseTimeNode = "POCO Materialization";
>ClientParseTimeNode [](http://example.com/codeflow?start=29&length=19)

PocoMaterializationNode

2022-05-10 23:32 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/QueryPerfTest/MetricsAccumulator.cs
> +        private const string ClientDeserializationTimeNode = "Get Cosmos Element Response";
>ClientDeserializationTimeNode [](http://example.com/codeflow?start=29&length=29)

GetCosmosElementResponseNode.

2022-05-10 23:33 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/QueryPerfTest/MetricsAccumulator.cs
> +        private const string TransportNodeName = "Microsoft.Azure.Documents.ServerStoreModel Transport Request";
>TransportNodeName [](http://example.com/codeflow?start=29&length=17)

TransportRequestNode

2022-05-10 23:33 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/QueryPerfTest/MetricsAccumulator.cs
> +        private const string BackendKeyValue = "Query Metrics";
>BackendKeyValue [](http://example.com/codeflow?start=29&length=15)

QueryMetricsKey

2022-05-10 23:33 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/QueryPerfTest/MetricsAccumulator.cs
> +        private const string TransportKeyValue = "Client Side Request Stats";
>TransportKeyValue [](http://example.com/codeflow?start=29&length=17)

CLientSideRequestStatsKey

2022-05-10 23:34 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/QueryPerfTest/MetricsAccumulator.cs
> +            List<ITrace> backendMetrics = this.FindQueryMetrics(trace: trace, nodeNameOrKeyName: BackendKeyValue, isKeyName: true);
>backendMetrics [](http://example.com/codeflow?start=25&length=14)

backendTraces

List variable names typically end with the plural form of type name or a suitable noun.

2022-05-10 23:36 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/QueryPerfTest/MetricsAccumulator.cs
> +                ClientSideRequestStatisticsTraceDatum clientSideRequestStatisticsTraceDatum = (ClientSideRequestStatisticsTraceDatum)kvp.Value;
Debug.Assert(kvp.Value is ClientSideRequestStatisticsTraceDatum ...)

Debug.* for logic assumptions/invariants/documentation etc.
Assert.* for test validation.

2022-05-10 23:37 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/QueryPerfTest/MetricsAccumulator.cs
> +            foreach (Tuple<ITrace, ITrace, ITrace> metrics in backendAndClientMetrics)
>Tuple<ITrace, ITrace, ITrace> [](http://example.com/codeflow?start=21&length=29)

Tuple with named properties would be nice.

2022-05-10 23:38 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/QueryPerfTest/MetricsSerializer.cs
> +                                        "\"{11}\",\"{12}\",\"{13}\",\"{14}\",\"{15}\",\"{16}\",\"{17}\"", "Iteration", "RoundTrip",
A constant would be nice.

2022-05-10 23:39 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/QueryPerfTest/MetricsSerializer.cs
> +                                        "Completed", "PocoTime", "GetCosmosElementResponseTime", "EndToEndTime"));
You don't really need string.Format, since all values are constant strings.

2022-05-10 23:40 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/QueryPerfTest/MetricsSerializer.cs
> +                                                metrics.Completed, metrics.PocoTime, metrics.GetCosmosElementResponseTime, metrics.EndToEndTime));
Alternative:

WriteLine($"{iterationCount},{roundTripCount},{metrics.RetrievedDocumentCount},. . . "

2022-05-10 23:40 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/QueryPerfTest/MetricsSerializer.cs
> +                                                metrics.Completed, metrics.PocoTime, metrics.GetCosmosElementResponseTime, metrics.EndToEndTime));
Same as before, please use $"" syntax for increased validation.

2022-05-10 23:40 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/QueryPerfTest/MetricsSerializer.cs
> +                        metrics.BadRequestReceived, metrics.BadRequestCompleted));
Same as before, please use $"" syntax for increased validation.

2022-05-10 23:41 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/QueryPerfTest/MetricsSerializer.cs
> +            if (rawData == false)
nit, if (!rawData)

2022-05-10 23:43 UTC, adityasa commented
Files in old location still need to be removed?
Microsoft.Azure.Cosmos\tests\Microsoft.Azure.Cosmos.Tests\QueryPerfTest\...

2022-05-10 23:44 UTC, adityasa submitted a review, later dismissed
:shipit:

2022-05-11 15:55 UTC, sboshra submitted a review, later dismissed

2022-05-11 16:11 UTC, j82w reviewed
@hdetroja 
1. Can you please share the results of the performance difference? 
2. How is this validating the higher CPU caused by the binary conversion will not cause lower throughput? The test only seems to be running 1 query at a time and is ignoring throughput of the SDK. I reopened a comment about this that was resolved, but I'm putting the question here to because it's hard to find it.

2022-05-16 20:42 UTC, sboshra approved these changes

2022-05-16 21:18 UTC, merged