Client Telemetry: Adds VMId or Unique Id in payload
Azure/azure-cosmos-dotnet-v3 pull request #3100
Opened 2022-03-21 19:42 UTC by sourabh1007

## Description

Please include a summary of the change and which issue is fixed. Include samples if adding new API, and include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [] New feature (non-breaking change which adds functionality)
## Closing issues

To automatically close an issue: closes #3096

2022-03-21 21:15 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +                        this.clientTelemetryInfo.MachineId = ClientTelemetry.UniqueId;
Please make sure the same prefixes as in Java are used - the whole purpose was to make it easy to identify in Kusto/ClientTelemetry whether it is an actual VmId or not

2022-03-21 21:17 UTC, FabianMeiswinkel requested changes
The vmId should be added to request diagnostics as well

2022-03-22 06:33 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +                        this.clientTelemetryInfo.MachineId = ClientTelemetry.UniqueId;
Thanks for pointing it out. If I am not wrong, if it is azure instance, `machineId` will have a value otherwise it will have `vmId: + <generated guid>`

2022-03-22 16:32 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +        internal static readonly string UniqueId = "vmId:" + Guid.NewGuid().ToString();
Prefix here should be uuid i guess?

2022-03-22 16:34 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryHelper.cs
> +                    {
Don't fake AzureVMMetadata - use it as null instead. And then make the condition whether to use uuid-machineId or actual one based on it. Non-null Azure VM Metadata instance with all kind of fields being null can just cause trouble later

2022-03-23 14:18 UTC, ealsur submitted a review, later dismissed

2022-03-29 15:18 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Telemetry/VmMetadataApiHandler.cs
> +            {
Fine here - but in general it is recommended to do intiial check without lock for better perf on the "common" case (already initialized)

so

if (VmMetadataApiHandler.instance != null)
{
    return VmMetadataApiHandler.instance;
}

lock ...

2022-03-29 15:18 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Telemetry/VmMetadataApiHandler.cs
> +            {
At least for variables like this one that are mutable only for the null -> Some Value transformation

2022-03-29 15:19 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Telemetry/VmMetadataApiHandler.cs
> +
NIT remove LF

2022-03-29 15:23 UTC, FabianMeiswinkel approved these changes
LGTM except for few small comments

2022-03-30 17:42 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +        private VmMetadataApiHandler vmMetadataApiHandler;
so that it can be initialized and dispose with document client.

2022-03-30 17:47 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +            this.vmMetadataApiHandler?.Dispose();
cleaning the cached Value.. at least while running the tests. .it was required to clean the cache while switching to non-azure instance test from azure instance tests.. I don't see any real world scenario but according to me its good to clean cache while disposing.

2022-03-30 17:50 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/VmMetadataApiHandler.cs
> +                string vmMetadataUrlProp = ConfigurationManager.GetEnvironmentVariable<string>(
it was initially designed like this...i didn't touch it right now...but we can remove it in a separate PR.

2022-03-30 18:46 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/VmMetadataApiHandler.cs
> +                VmMetadataApiHandler.instance = new VmMetadataApiHandler(httpClient);
Added init flag, as it will avoid calling this API every time during initialization in a non-azure machine. This class has all VM Metadata related code, if tomorrow I want to add more utility functions, that would come here.

2022-03-30 18:46 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/VmMetadataApiHandler.cs
> +            return VmMetadataApiHandler.azMetadata == null ? VmMetadataApiHandler.UniqueId : VmMetadataApiHandler.azMetadata.Compute.VMId;
Whole intention of adding this vmId/machineId is to have an identifier which can tell if requests are coming from same machine or different machines. 
That purpose will still be fulfilled. btw this value will change even application is restarted. If you have any other way to fetch machine id (non PII), we can consider that.

2022-04-01 12:14 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Telemetry/VmMetadataApiHandler.cs
> +            return VmMetadataApiHandler.azMetadata == null ? VmMetadataApiHandler.UniqueId : VmMetadataApiHandler.azMetadata.Compute.VMId;
It should be defaulted with null instead of using a static variable. Every time the process restarts it will register as a new machine. Even if they are on the same machine, but in different processes it will show them as different machines. This will add a lot of confusion and be very ambiguous. It seems better to not have it if we there isn't a clear signal.

2022-04-01 12:15 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Telemetry/VmMetadataApiHandler.cs
> +                string vmMetadataUrlProp = ConfigurationManager.GetEnvironmentVariable<string>(
Once this is supported removing it can be seen as a breaking change because someone could take a dependency on this. It's better to not add environment variables unless it is needed.

2022-04-01 12:16 UTC, j82w commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +            this.vmMetadataApiHandler?.Dispose();
This is a machine level property. Why would the cache ever need to be cleared?

2022-04-01 15:41 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +            this.vmMetadataApiHandler?.Dispose();
Yes, We can skip the clearing of cache on dispose but adding a function just for tests

2022-04-01 16:14 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/VmMetadataApiHandler.cs
> +            return VmMetadataApiHandler.azMetadata == null ? VmMetadataApiHandler.UniqueId : VmMetadataApiHandler.azMetadata.Compute.VMId;
having them different values, will at least tell that. these given diagnostics are from different process. So, if there is an issue with that request, we can checkout if it belongs to same process ( otherwise, same machine ).

@FabianMeiswinkel

2022-04-01 16:28 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Telemetry/VmMetadataApiHandler.cs
> +            return VmMetadataApiHandler.azMetadata == null ? VmMetadataApiHandler.UniqueId : VmMetadataApiHandler.azMetadata.Compute.VMId;
Then there should be a process id and a machine id. They should be treated separately to avoid any confusion.

2022-04-01 16:34 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Telemetry/VmMetadataApiHandler.cs
> +            return VmMetadataApiHandler.azMetadata == null ? VmMetadataApiHandler.UniqueId : VmMetadataApiHandler.azMetadata.Compute.VMId;
If we want a more reliable way beside process id we could use a hash of the different environment variables that are available. Something like
Environment.MachineName + Environment.Version + Environment.OSVersion + Environment.ProcessorCount +Environment.UserName => hash

2022-04-01 18:42 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/VmMetadataApiHandler.cs
> +            return VmMetadataApiHandler.azMetadata == null ? VmMetadataApiHandler.UniqueId : VmMetadataApiHandler.azMetadata.Compute.VMId;
As discussed, offline, Vmid --> fallback to --> hashedMachineName --> fallback to --> Generated uuid

2022-04-06 11:13 UTC, j82w commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +        private VmMetadataApiHandler vmMetadataApiHandler;
This is no longer disposed so why is it needed?

2022-04-06 11:25 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Telemetry/VmMetadataApiHandler.cs
> +                VmMetadataApiHandler.instance = new VmMetadataApiHandler(httpClient);
What is the benefit of having an entire class to do this instead of just having a single method that does it? The current implementation will hold a ref to the http client which could be bad if they are recreating clients.

2022-04-06 13:10 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/VmMetadataApiHandler.cs
> +                VmMetadataApiHandler.instance = new VmMetadataApiHandler(httpClient);
I am not sure if we should worry about performance and object holding...as it is during initialization and non-blocking call. Ideally it won't affect anything.
Anyway I have made the changes as per your suggestion.

2022-04-06 18:10 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +                                                    HttpTimeoutPolicyNoRetry.Instance,
Is there a reason to remove the retry policy when trying to send the payload to the service?

2022-04-06 18:10 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Telemetry/VmMetadataApiHandler.cs
> +            VmMetadataApiHandler.httpClient = httpClient ?? throw new ArgumentNullException(nameof(httpClient));
nit: Avoid lock contention by first checking if it is already initialized outside the lock.  

```c#

if (VmMetadataApiHandler.isInitialized)
{
   return;
}

lock (VmMetadataApiHandler.lockObject)
{
        if (VmMetadataApiHandler.isInitialized)
        {
           return;
        }
        DefaultTrace.TraceInformation("Initializing VM Metadata API ");

        VmMetadataApiHandler.isInitialized = true;

        _ = Task.Run(MetadataApiCallAsync, default)
                    .ContinueWith(t => DefaultTrace.TraceWarning($"Exception while making metadata call {t.Exception}"),
                    TaskContinuationOptions.OnlyOnFaulted);
}
```

2022-04-06 18:18 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Telemetry/VmMetadataApiHandler.cs
> +        private static string HashedMachineName => "hashedMachineName:" + VmMetadataApiHandler.ComputeHash(Environment.MachineName);
This should not be a delegate. This will cause it to recompute every call.

2022-04-06 18:18 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Telemetry/VmMetadataApiHandler.cs
> +            using (SHA1 sha1Hash = SHA1.Create())
Should this be SHA256 or SHA512?

2022-04-06 18:18 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Telemetry/VmMetadataApiHandler.cs
> +        internal static void Clear()
Why is this needed for tests? This can be done via reflection if necessary. It's not good practice to add code just for testing purposes.

2022-04-06 18:46 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +                                                    HttpTimeoutPolicyNoRetry.Instance,
Yes we don't want to retry in any case. I was not aware that Default policy retries, so fixing it in this PR. May be in future we will have conscious decision on retry mechanism for Client Telemetry.

2022-04-06 18:47 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/VmMetadataApiHandler.cs
> +            using (SHA1 sha1Hash = SHA1.Create())
Any SHA algorithm is fine here, as here intention is to generate hash code of value, just to hide the original information.

2022-04-06 18:53 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Telemetry/VmMetadataApiHandler.cs
> +            using (SHA1 sha1Hash = SHA1.Create())
IN theory you are right - we use it for non-crypto purposes. Problem is we have static code analysis tools flagging usage of Sha-1 - and you have to explain why it is safe to use it here - blah, blah. So just use Sha-512 and you save a lot of work :-)

2022-04-06 19:14 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/VmMetadataApiHandler.cs
> +        internal static void Clear()
**Why is this needed for tests?**
As mentioned in the comment : this cache needs to clear while switching between Azure System tests and non Azure system tests.

This function is there to clean the cached value, as of now I don't see any use of it in main code but in future we might want to use it to clear the cache. This function has real functionality, not a test specific code. it makes this class complete also like we generate cache here and have a utility function to clear it also if required.

Anyway, I am removing this function.

2022-04-07 12:28 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Telemetry/VmMetadataApiHandler.cs
> +        private static readonly string HashedMachineName = "hashedMachineName:" + VmMetadataApiHandler.ComputeHash(Environment.MachineName);
This can fail when initializing the variable. Why not make it a lazy variable?

```c#
private static readonly Lazy<string> uniqueId = new Lazy<string>(() =>
{
     try{
          return "hashedMachineName:" + VmMetadataApiHandler.ComputeHash(Environment.MachineName);
     }catch(exception e){
         DefaultTrace.....
     }

      return "uuid:" + Guid.NewGuid().ToString();
}
```

2022-04-07 20:20 UTC, j82w approved these changes

2022-04-07 20:29 UTC, FabianMeiswinkel approved these changes
LGTM - thanks

2022-04-07 21:02 UTC, merged