Query: Fixes a bug where custom serializer not used in query plan creation
Azure/azure-cosmos-dotnet-v3 pull request #3154
Opened 2022-04-21 17:54 UTC by j82w

# Pull Request Template

## Description
The custom serializer is not applied when the query plan is generated locally. This can cause it to not generate the correct query plan which could target the wrong partition if the query is filtered by the partition value.

Solution:
Convert the method to take a string and have the correct serializer convert it to a string. Then send it to the service interop.

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #3153

2022-04-21 18:41 UTC, neildsh commented on Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPartitionProvider.cs
> +            string querySpecJsonString,
>string querySpecJsonString, [](http://example.com/codeflow?start=12&length=27)

This is fishy, we should not replace a strong type with a weak one

2022-04-21 19:05 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPartitionProvider.cs
> +            string querySpecJsonString,
In the end the contract is a string. The strong type is not used anywhere. The alternative is to pass the serializer and resource type all the way down to just convert it to a string. There doesn't seem to be any benefits in converting it to the string at a higher level vs passing multiple objects to just convert it to a string at a lower level.

2022-04-21 20:14 UTC, neildsh commented on Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPartitionProvider.cs
> +            string querySpecJsonString,
Why not add a `SqlQuerySpecInternal` that encapsulates all this info and has a `Serialize` method ?

2022-04-21 20:22 UTC, neildsh commented on Microsoft.Azure.Cosmos/src/Routing/PartitionRoutingHelper.cs
> +            string querySpecJsonString,
>string querySpecJsonString, [](http://example.com/codeflow?start=12&length=27)

Same here please do not use a weak type

2022-04-21 20:24 UTC, neildsh commented
Please add more description to explain why this change is required. A good example would be something like this: [https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3137](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3137)

2022-04-21 20:25 UTC, neildsh commented
Please add baseline tests that illustrate how this change is used

2022-04-22 05:57 UTC, neildsh requested changes
:clock1:

2022-04-22 20:28 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Routing/PartitionRoutingHelper.cs
> +            string querySpecJsonString,
I updated the PR description to explain why this model was chosen.

2022-04-22 21:38 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPartitionProvider.cs
> +            string querySpecJsonString,
The alternatives are kind of three IMO:

1. Pass the SqlQuerySpec but also pass the serializer reference across all the components.
2. Pass a SqlQuerySpecInternal as suggested with a Serialize method 
3. Pass a string, which is immutable in itself.

Solutions 2 and 3 avoid the Separations of Concern issue of 1. What I don't like about 2 is that it seems to over complicate the solution. A string (solution 3) achieves the same thing (it's inmutable), separates concerns (lower components don't care how it was serialized) and it's less complex from the Type perspective.

2022-04-22 21:38 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPartitionProvider.cs
> +            if (querySpecJsonString == null || partitionKeyDefinition == null)
nit: Should it check for NullOrWhitespace?

2022-04-22 21:39 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Query/v2Query/DocumentQueryExecutionContextBase.cs
> +                querySpecJsonString: JsonConvert.SerializeObject(this.QuerySpec),
nit: Do we really still use these files?

2022-04-22 21:40 UTC, ealsur approved these changes
LGTM, only minor comments

2022-04-25 11:05 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Query/v2Query/DocumentQueryExecutionContextBase.cs
> +                querySpecJsonString: JsonConvert.SerializeObject(this.QuerySpec),
No, but removing it would require going through and deleting a lot of code from DocumentClient.cs. It was decided a while back to not do it to keep it close to the v2 code base. I think there is enough diverged enough to just delete it at this point.

2022-04-26 08:50 UTC, kr-santosh approved these changes

2022-04-26 18:11 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Query/v2Query/DefaultDocumentQueryExecutionContext.cs
> +                        querySpecJsonString: JsonConvert.SerializeObject(this.QuerySpec),
The v2 code needs to be cleaned up that should be done by the query team in a separate PR.

2022-04-28 12:29 UTC, kr-santosh commented
@sboshra  Hi Samer could you have a look at it and sign off on the PR.

2022-04-29 13:58 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryClientCore.cs
>          public override async Task<TryCatch<PartitionedQueryExecutionInfo>> TryGetPartitionedQueryExecutionInfoAsync(
Correct, this is the v3 specific client logic.

2022-04-29 14:46 UTC, ealsur submitted a review, later dismissed

2022-04-29 20:21 UTC, neildsh commented on Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPartitionProvider.cs
> +            string querySpecJsonString,
The class' contract is the method signature, so I think it does make sense to pass in the serializer, either as method or ctor arg.

2022-04-29 20:24 UTC, neildsh commented on Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryClientCore.cs
> +                using (Stream stream = this.clientContext.SerializerCore.ToStreamSqlQuerySpec(sqlQuerySpec, resourceType))
>sqlQuerySpec, resourceType [](http://example.com/codeflow?start=94&length=26)

why does the serialization depend on resourceType ?

2022-04-30 00:21 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryClientCore.cs
> +                using (Stream stream = this.clientContext.SerializerCore.ToStreamSqlQuerySpec(sqlQuerySpec, resourceType))
It's required because internal types like account info or pk ranges should not use the user's custom serialization logic.

2022-05-02 22:22 UTC, neildsh approved these changes
:shipit:

2022-05-02 22:30 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPartitionProvider.cs
> +            string querySpecJsonString,
We had a meeting on this and closed that since the string is only used in 1 layer that it is fine to avoid the complexity of passing the serialization logic around.

2022-05-03 14:54 UTC, merged