Add support for new PartitionKey Constructor and allow partition key path and id to be part of client encryption policy.
Azure/azure-cosmos-dotnet-v3 pull request #3211
Opened 2022-05-23 06:26 UTC by kr-santosh

## Description

The PR brings in the following changes.

- Support a new constructor for Partition Key. Allowing long type. This is required in order to support partition key encryption.
Encryption package adds a marker/type header (higher precision marker int -> long, decimal/float -> double - https://github.com/Azure/azure-cosmos-dotnet-v3/blob/22309840d9b4b78a7c0a4cb8da0dfec4a352f5c6/Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs#L213) along with the encrypted string and hence this constructor is required to match the supported types. The public object member RawPartitionKeyValue  is required to fetch the value from the partitionKey object passed during point/query operations.

- Allow support to include partition key path and id during encryption policy creation (only deterministic encryption type) and bumps up the format version.

## Type of change

Please delete options that are not relevant.

- [] New feature (non-breaking change which adds functionality)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #IssueNumber

2022-05-23 13:45 UTC, j82w commented on Microsoft.Azure.Cosmos/src/PartitionKey.cs
> +        public object RawPartitionKeyValue { get; }
Why can't this be extracted from the JSON? This will not support the new subpartitioning.

2022-05-23 13:45 UTC, j82w commented on Microsoft.Azure.Cosmos/src/PartitionKey.cs
> +        public PartitionKey(long partitionKeyValue)
PartitionKeyInternal cast everything to a double why is this needed?

2022-05-23 15:08 UTC, abhijitpai commented on Microsoft.Azure.Cosmos/src/Resource/Settings/ClientEncryptionPolicy.cs
> +            this.PolicyFormatVersion = 2;
We could make the version 2 only if pk/id are encrypted, and tell customers not to create such collections until they have fully upgraded. Alternatively, we can take the version as input.

2022-05-23 16:02 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Resource/Settings/ClientEncryptionPolicy.cs
> +            this.PolicyFormatVersion = 2;
They can only change it when creating the container then? Just want to confirm it's not possible to change after the container is created.

2022-05-24 04:07 UTC, kr-santosh commented on Microsoft.Azure.Cosmos/src/PartitionKey.cs
> +        public object RawPartitionKeyValue { get; }
This is primarily for the read path. As described in the PR description when we encrypt, we add a header which is basically the type and hence we would need what type the data is.  Can you point me to what this sub partitioning is? Hence, we are introducing new constructors primarily for float/double/decimal since precision change affects the crypto string that would be generated.

2022-05-24 04:25 UTC, kr-santosh commented on Microsoft.Azure.Cosmos/src/Resource/Settings/ClientEncryptionPolicy.cs
> +            this.PolicyFormatVersion = 2;
Distributed system you mean customer managed client cluster? Yes, this is a good point, if the customers don't intend on say adding PK or Id to their new containers this will sort of force them to upgrade all their clients at one go.  We could set the default to 1 in constructor and fail with an exception to change the Format to 2 if PK or Id paths are included in the Policy.

2022-05-24 04:27 UTC, kr-santosh commented on Microsoft.Azure.Cosmos/src/Resource/Settings/ClientEncryptionPolicy.cs
> +                    if (string.Equals(this.IncludedPaths.Where(p => p.Path.Substring(1).Equals(topLevelToken)).Select(et => et.EncryptionType).FirstOrDefault(), "Randomized"))
partition key token dont begin with "/" hence the substring(1). This should be linear since its a list and not really a concern the list length would not be too big. Sure will add the comment.

2022-05-24 06:11 UTC, kr-santosh commented on Microsoft.Azure.Cosmos/src/Resource/Settings/ClientEncryptionPolicy.cs
> +            this.PolicyFormatVersion = 2;
now allowing format version to be passed.

2022-05-24 06:34 UTC, abhijitpai commented on Microsoft.Azure.Cosmos/src/Resource/Settings/ClientEncryptionPolicy.cs
> +        public ClientEncryptionPolicy(IEnumerable<ClientEncryptionIncludedPath> includedPaths, int policyFormatVersion = 1)
Expose via ClientEncryptionPolicyDefinition too.

2022-05-24 06:35 UTC, abhijitpai commented on Microsoft.Azure.Cosmos/src/PartitionKey.cs
> +        public object RawPartitionKeyValue { get; }
Sub-partitioning is where the partition key has multiple properties - check PartitionKeyBuilder.

2022-05-24 06:44 UTC, kr-santosh commented on Microsoft.Azure.Cosmos/src/Resource/Settings/ClientEncryptionPolicy.cs
> +        public ClientEncryptionPolicy(IEnumerable<ClientEncryptionIncludedPath> includedPaths, int policyFormatVersion = 1)
my bad. Thanks much

2022-05-24 07:12 UTC, kr-santosh commented on Microsoft.Azure.Cosmos/src/Resource/Settings/ClientEncryptionPolicy.cs
> +        public ClientEncryptionPolicy(IEnumerable<ClientEncryptionIncludedPath> includedPaths, int policyFormatVersion = 1)
add check for supported versions.

2022-05-24 08:29 UTC, kr-santosh commented on Microsoft.Azure.Cosmos/src/PartitionKey.cs
> +        public object RawPartitionKeyValue { get; }
sure, let me have a look at it.

2022-05-24 09:01 UTC, kr-santosh commented on Microsoft.Azure.Cosmos/src/PartitionKey.cs
> +        public object RawPartitionKeyValue { get; }
> Why can't this be extracted from the JSON? This will not support the new subpartitioning.

I guess we can expose the object list of partition key values?

2022-05-24 14:02 UTC, kr-santosh commented on Microsoft.Azure.Cosmos/src/PartitionKey.cs
> +        public object RawPartitionKeyValue { get; }
give me a day let me check this ToString() thing, if this can be leveraged.

2022-05-25 04:44 UTC, kr-santosh commented on Microsoft.Azure.Cosmos/src/PartitionKey.cs
> +        public object RawPartitionKeyValue { get; }
@j82w  this would work for non number types, but since this ToString JSON string relies on internal key which will always be double so we will end up with Float type and we will not be able to rebuild the encrypted partition key.

2022-05-25 09:07 UTC, kr-santosh commented on Microsoft.Azure.Cosmos/src/PartitionKeyBuilder.cs
> +            return new PartitionKey(partitionKeyInternal, valueArray);
Update supported types for Encryption pkg.

2022-05-25 09:26 UTC, FabianMeiswinkel requested changes
My 2 cents: Don't even try to support non-strings as partition keys. numbers in json are evil (neither range nor precision are clearly standardized - so supported ranges/precisions depend on the json parsers/libraries used - and this can cause hard to diagnose and mitigate issues). The good thing for end-to-end encryption is that all workloads are green-field - no scenario where a customer has TBs of data already. I think we should simply only support strings, instead of hacking something together that might work in most scenarios but doesn't solve the underlying problem that json doesn't have a clear definition for numbers - that solves the encryption-specific challenge of having to know the type and prevents customers form running into the other issues with numbers as PK later.

2022-05-26 04:15 UTC, kr-santosh commented on Microsoft.Azure.Cosmos/src/PartitionKey.cs
> +        public object RawPartitionKeyValue { get; }
this will be handled via JSON string to JArray.

2022-05-26 04:15 UTC, kr-santosh commented
> My 2 cents: Don't even try to support non-strings as partition keys. numbers in json are evil (neither range nor precision are clearly standardized - so supported ranges/precisions depend on the json parsers/libraries used - and this can cause hard to diagnose and mitigate issues). The good thing for end-to-end encryption is that all workloads are green-field - no scenario where a customer has TBs of data already. I think we should simply only support strings, instead of hacking something together that might work in most scenarios but doesn't solve the underlying problem that json doesn't have a clear definition for numbers - that solves the encryption-specific challenge of having to know the type and prevents customers form running into the other issues with numbers as PK later. To be honest only supporting strings as PK is what we should have done across the board - too late now, because it is a breaking change. But with encryption we have the benefit of a "fresh start" for every workload - so let's do it right this time.

Fixed.

2022-05-26 04:16 UTC, kr-santosh commented
Closed by mistake :)

2022-05-26 04:17 UTC, kr-santosh commented
> My 2 cents: Don't even try to support non-strings as partition keys. numbers in json are evil (neither range nor precision are clearly standardized - so supported ranges/precisions depend on the json parsers/libraries used - and this can cause hard to diagnose and mitigate issues). The good thing for end-to-end encryption is that all workloads are green-field - no scenario where a customer has TBs of data already. I think we should simply only support strings, instead of hacking something together that might work in most scenarios but doesn't solve the underlying problem that json doesn't have a clear definition for numbers - that solves the encryption-specific challenge of having to know the type and prevents customers form running into the other issues with numbers as PK later. To be honest only supporting strings as PK is what we should have done across the board - too late now, because it is a breaking change. But with encryption we have the benefit of a "fresh start" for every workload - so let's do it right this time.

Fixed.

2022-05-26 07:27 UTC, abhijitpai commented on Microsoft.Azure.Cosmos/src/Resource/Settings/ClientEncryptionPolicy.cs
> +                if (string.Equals(clientEncryptionIncludedPath.EncryptionType, "Randomized"))
> if (strin [](http://example.com/codeflow?start=15&length=10)

nit: EncryptionType != "Deterministic"

2022-05-26 07:31 UTC, abhijitpai commented
>         public IEnumerable<ClientEncryptionIncludedPath> IncludedPaths

Please add a comment on this class, something like: 'The <see cref=ClientEncryptionPolicy should be initialized with policyFormatVersion 2 if "id" or properties that are part of the partition key need to be encrypted'. Goal is that this documentation should suffice to let customers know how to use the functionality. Ideally add some examples too where possible.

---
Refers to: Microsoft.Azure.Cosmos/src/Resource/Settings/ClientEncryptionPolicy.cs:40 in cba1c4d. [](commit_id = cba1c4dac05cd7df432f3e9734ad47659bfdbe62, deletion_comment = False)

2022-05-26 07:44 UTC, abhijitpai commented on Microsoft.Azure.Cosmos/src/Resource/Settings/ClientEncryptionPolicy.cs
> +                        if (string.Equals(encryptedPartitionKeyPath.Select(et => et.EncryptionType).FirstOrDefault(), "Randomized"))
>), "R [](http://example.com/codeflow?start=115&length=5)

!= "Deterministic"

2022-05-26 11:21 UTC, abhijitpai approved these changes
:shipit:

2022-05-26 11:28 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Fluent/Settings/ContainerBuilder.cs
> +        public ClientEncryptionPolicyDefinition WithClientEncryptionPolicy(int policyFormatVersion = 1)
Why is the default not 2? Don't we want new customer to target the new version by default?

2022-05-26 11:34 UTC, kr-santosh commented on Microsoft.Azure.Cosmos/src/Fluent/Settings/ContainerBuilder.cs
> +        public ClientEncryptionPolicyDefinition WithClientEncryptionPolicy(int policyFormatVersion = 1)
we already have customer hence set it to 1. Else they will have to upgrade the application,

2022-05-26 13:18 UTC, j82w commented on Microsoft.Azure.Cosmos/src/Fluent/Settings/ContainerBuilder.cs
> +        public ClientEncryptionPolicyDefinition WithClientEncryptionPolicy(int policyFormatVersion = 1)
If they have this option they already upgraded there SDK to one that supports it. I don't see a reason we would want the default to be the older version. They only need to set the older version if they have some scenario where multiple apps are using the container and some are not upgraded.

2022-06-06 15:06 UTC, ealsur approved these changes
@kirankumarkolli Please review public API change

2022-06-07 15:33 UTC, kirankumarkolli approved these changes

2022-06-09 18:35 UTC, merged