[JsonPatch] Implementation of the Move Operation in accordance with the JSONPATCH RFC6902.
Azure/azure-cosmos-dotnet-v3 pull request #3262
Opened 2022-06-10 20:59 UTC by amaanhaque

# Pull Request Template

## Description

The move operation removes the value at a specified location and adds it to the target location.
It takes in 2 parameters "path" (destination path) and "from" (source path).
Functionally it is identical to an add operation at the destination followed by a remove at the source path.
This operation is discussed in the JSONPATCH RFC6902.

## Type of change

Please delete options that are not relevant.

- [] New feature (non-breaking change which adds functionality)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #IssueNumber

2022-06-10 21:58 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Batch/BatchSinglePartitionKeyTests.cs
> +                //PatchOperation.Add("/noDate", patchDate)
nit: This comment is not needed?

2022-06-10 21:59 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Batch/BatchSinglePartitionKeyTests.cs
>              Assert.IsTrue(dateJson.Contains(response.Resource["date"].ToString()));
This should be false? If the test moves `/date` to `/TodayDate` why is the document still have a `/date`?

2022-06-10 22:01 UTC, ealsur commented
/azp run

2022-06-11 06:53 UTC, amaanhaque commented
/azp run

2022-06-13 14:18 UTC, ealsur commented
/azp run

2022-06-13 18:13 UTC, ealsur requested changes
Emulator tests are failing with:
`Microsoft.Azure.Cosmos.CosmosException: Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: d48a11a6-af63-47ff-b6ea-1146e212e8a1; Reason: (Message: {"Errors":["Invalid value of the patch operation 'op' property in patch request: 'move'"]}`

Does this require a new Emulator release?

2022-06-15 05:26 UTC, amaanhaque commented
> Emulator tests are failing with: `Microsoft.Azure.Cosmos.CosmosException: Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: d48a11a6-af63-47ff-b6ea-1146e212e8a1; Reason: (Message: {"Errors":["Invalid value of the patch operation 'op' property in patch request: 'move'"]}`
> 
> Does this require a new Emulator release?

It doesn't.

2022-06-21 09:58 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Patch/PatchOperation.cs
> +        public abstract string From { get; }
This is a breaking change. Adding any new abstract member on a public non-sealed class is considered breaking. Because customers could have inherited from that class and now would hit a compiler error. Make this property virtual please with a default (I assume returning null when you follow what you did in Java)

2022-06-21 09:59 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Patch/PatchOperationCore{T}.cs
> +                    : value.ToString();
Nothing prevents value form being null in the first place. And that would result in a NullReferenceException here. String.IsNullOrWhiteSpace(value)  instead of String.IsNullOrWhiteSpace(value.ToString()) fixes that

2022-06-21 10:02 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Patch/PatchOperationType.cs
> +        /// <summary>
Strictly speaking adding new enum values is also breaking - I think this is acceptable here because it clearly is a contract class - but that is the reaosn why usually it is a bad idea in frameworks to expsoe enums in Json contract classes - and usage of Strings is safer.

Please add a comment on this enum - class level to clearly call out that customers should expect to values to be added - and any switch / case assuming new enums would only be added for new major (breaking) versions is discouraged.

2022-06-21 10:03 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Patch/PatchOperationsJsonConverter.cs
> +                }
shouldn't this be else if here - if it is move value would never be needed

2022-06-21 10:05 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Patch/PatchOperation.cs
> +            string path,
In Java you have switched the order PatchOperation Move(string from, string path) - I personally think that is much more intuitive. And would be my preference for .Net as well.

2022-06-21 10:06 UTC, FabianMeiswinkel requested changes
Mostly looks good - few comments that need to be addressed

2022-08-25 17:16 UTC, ealsur commented
Duplicate of https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3389

2022-08-25 17:16 UTC, closed without merging