Get Failed count and GetStartTime and TraceSummary implemented
Azure/azure-cosmos-dotnet-v3 pull request #3268
Opened 2022-06-14 17:34 UTC by SchintaMicrosoft

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Include samples if adding new API, and include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #IssueNumber

2022-06-14 18:27 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Diagnostics/CosmosTraceDiagnostics.cs
> +            return this.Value.Summary.GetFailedCount();
What if the Summary is null? (just in case, we can never be too sure 😄 )

2022-06-14 18:32 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
> +            Assert.AreEqual(0, response.Diagnostics.GetFailedRequestCount());
Where are we testing at least a failure scenario? There should be currently some test that is generating some failure (like mocking a 429) or any of test that is failing on purpose (like `NegativeCreateItemTest` in this file). Can we check that in those cases the number of FailedRequests is not 0?

2022-06-14 19:12 UTC, SchintaMicrosoft commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
> +            Assert.AreEqual(0, response.Diagnostics.GetFailedRequestCount());
In NegativeCreateDropItemTest , we are checking the failure scenario.

2022-06-14 19:43 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
> +            Assert.AreEqual(0, response.Diagnostics.GetFailedRequestCount());
Missed it

2022-06-14 19:44 UTC, ealsur approved these changes

2022-06-14 22:46 UTC, ealsur commented
@kirankumarkolli Can you review the public API changes?

2022-06-14 23:36 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnostics.cs
> +        /// <summary>
This si a breaking change. Adding any new abstract member to a public non-sealed class is considered breaking (because any implementation would not work without code changes after upgrade)

2022-06-14 23:37 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnostics.cs
> +        /// <summary>
Needs to be virtual with throwing NotImplementedException as GetClientElapsedTime above.

2022-06-14 23:40 UTC, FabianMeiswinkel commented
> @kirankumarkolli Can you review the public API changes?

The public API needs to be changes - adding new abstract members to a public non-sealed class is a breaking change.

2022-06-15 14:03 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnostics.cs
> +        /// <summary>
Similar to `public virtual TimeSpan GetClientElapsedTime()`

2022-06-15 19:12 UTC, SchintaMicrosoft commented on Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnostics.cs
> +        /// <summary>
GetContactedRegions is already abstract member . Based on this i added these 2 abstract members.

2022-06-16 20:16 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnostics.cs
> +        /// <summary>
What Fabian is saying is that they should be:

```
public virtual DateTime GetStartTimeUtc()
{
	// Default implementation avoids breaking change for users upgrading.
	throw new NotImplementedException($"CosmosDiagnostics.GetElapsedTime");
}

public virtual int GetFailedRequestCount()
{
	// Default implementation avoids breaking change for users upgrading.
	throw new NotImplementedException($"CosmosDiagnostics.GetElapsedTime");
}
```

Adding new members to an abstract class that is public is a breaking change. Any new member added after the abstract class was originally created needs to be `virtual` with the throw as shown.

2022-06-28 18:43 UTC, ealsur approved these changes

2022-06-28 18:46 UTC, SchintaMicrosoft commented on Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnostics.cs
> +        /// <summary>
@FabianMeiswinkel suggested changes applied.

2022-06-28 19:30 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnostics.cs
> +        ///  This represent the count of failed requests.
```suggestion
        ///  This represents the count of failed requests.
```

2022-06-28 19:32 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Diagnostics/CosmosTraceDiagnostics.cs
> +
```suggestion
```

2022-06-28 19:33 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/GatewayAccountReader.cs
>                      {
```suggestion
```

2022-06-28 19:34 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/GatewayAccountReader.cs
> +                        using (DocumentServiceResponse documentServiceResponse = await ClientExtensions.ParseResponseAsync(responseMessage))
```suggestion
                    using (DocumentServiceResponse documentServiceResponse = await ClientExtensions.ParseResponseAsync(responseMessage))
```

2022-06-28 19:34 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/GatewayAccountReader.cs
> +                        {
```suggestion
                    {
```

2022-06-28 19:34 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/GatewayAccountReader.cs
> +                            return CosmosResource.FromStream<AccountProperties>(documentServiceResponse);
```suggestion
                        return CosmosResource.FromStream<AccountProperties>(documentServiceResponse);
```

2022-06-28 19:34 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/GatewayAccountReader.cs
> +                        }
```suggestion
```

2022-06-28 19:38 UTC, FabianMeiswinkel requested changes
Few more minor comments - but looks better now.

2022-06-29 21:43 UTC, ealsur submitted a review, later dismissed

2022-06-30 21:15 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionCosmosDiagnostics.cs
> +            return this.coreDiagnostics.GetFailedRequestCount();
[Non blocking]
@ealsur Any encryption context that needs to be included in here?

2022-06-30 21:21 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Diagnostics/CosmosTraceDiagnostics.cs
> +            if (this.Value == null)
How about mark the contract as nullable and return null?

2022-06-30 21:22 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/GatewayAccountReader.cs
> +                                                message: ex.Data?["Message"].ToString(),
Is this change intentional?

2022-06-30 21:33 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/GatewayAccountReader.cs
> -            IClientSideRequestStatistics stats = new ClientSideRequestStatisticsTraceDatum(DateTime.UtcNow);
Why are changes to AccountReader?

2022-06-30 21:33 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/GatewayAccountReader.cs
> +                                                message: ex.Data?["Message"].ToString(),
Or incorrect conflict resolution?

2022-06-30 21:37 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Routing/ClientCollectionCache.cs
> -            ICosmosAuthorizationTokenProvider tokenProvider,
Unrelated change.

git checkout master -- <filename>

It might help is resetting the file

2022-06-30 21:41 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Tracing/TraceSummary.cs
> +#if INTERNAL
public always? 

Why does it needs to be conditionally set?

2022-07-01 18:00 UTC, SchintaMicrosoft commented on Microsoft.Azure.Cosmos/src/Diagnostics/CosmosTraceDiagnostics.cs
> +            if (this.Value == null)
Making nullable will be good approach. Please suggest to proceed with that change.

2022-07-01 19:12 UTC, SchintaMicrosoft commented on Microsoft.Azure.Cosmos/src/Routing/ClientCollectionCache.cs
> -            ICosmosAuthorizationTokenProvider tokenProvider,
we have added trace.summary in this file

2022-07-01 20:24 UTC, SchintaMicrosoft commented on Microsoft.Azure.Cosmos/src/GatewayAccountReader.cs
> -            IClientSideRequestStatistics stats = new ClientSideRequestStatisticsTraceDatum(DateTime.UtcNow);
Need to update ClientSideRequestStatisticsTraceDatum with tracesummary parameter

2022-07-01 20:27 UTC, SchintaMicrosoft commented on Microsoft.Azure.Cosmos/src/GatewayAccountReader.cs
> +                                                message: ex.Data?["Message"].ToString(),
It is incorrect conflict resolution . updated now.

2022-07-05 20:22 UTC, SchintaMicrosoft commented on Microsoft.Azure.Cosmos/src/Tracing/TraceSummary.cs
> +#if INTERNAL
Changed to public

2022-07-06 11:50 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Tracing/TraceSummary.cs
> +#if INTERNAL
Please publish updates and resolve the comments.

2022-07-06 18:34 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
> +    "Microsoft.Azure.Cosmos.Tracing.TraceSummary;System.Object;IsAbstract:False;IsSealed:False;IsInterface:False;IsEnum:False;IsClass:True;IsValueType:False;IsNested:False;IsGenericType:False;IsSeria
[Waiting]
It's supposed to be implementation details not public type.

2022-07-07 18:44 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Tracing/TraceSummary.cs
> +    public class TraceSummary
This needs to be internal, not public

2022-07-08 21:01 UTC, ealsur commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionCosmosDiagnostics.cs
> +            return this.coreDiagnostics.GetFailedRequestCount();
I am not aware of encryption related information honestly.

2022-07-08 21:05 UTC, ealsur approved these changes

2022-07-11 17:07 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnostics.cs
> +             throw new NotImplementedException($"{nameof(CosmosDiagnostics)}.{nameof(GetStartTimeUtc)})");
```suggestion
            throw new NotImplementedException($"{nameof(CosmosDiagnostics)}.{nameof(GetStartTimeUtc)})");
```

2022-07-11 17:07 UTC, FabianMeiswinkel submitted a review, later dismissed
LGTM now.

2022-07-13 15:32 UTC, ealsur approved these changes

2022-07-13 16:16 UTC, merged