[PREVIEW] AI Integration: Adds Open telemetry Support for Point Operations
Azure/azure-cosmos-dotnet-v3 pull request #3277
Opened 2022-06-20 18:13 UTC by sourabh1007

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Include samples if adding new API, and include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #IssueNumber

2022-06-24 15:27 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
> +                catch (CosmosException ex)
Why do you need the specialized case?

2022-06-24 15:28 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Conflict/ConflictsInlineCore.cs
> +                openTelemetry: (response) => new OpenTelemetryResponse(response));
Can this be addressed now that we are wiring things through? https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3212

2022-06-24 15:32 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryResponse.cs
> +                return Convert.ToString(response.Content.Length);
Why not return the int instead of materializing strings?

2022-06-24 15:33 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientTests.cs
> +            OpenTelemetryTests.ClassInitialize(context);
Is this needed for all tests?

2022-06-24 15:35 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Telemetry/OpenTelemetryTests.cs
> +    public abstract class OpenTelemetryTests
Who inherits from this class? (because it's abstract). Otherwise, why is it not a static class? Why is it decorated as `[TestClass]`

2022-06-24 18:51 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
> +                catch (CosmosException ex)
I one of the test I found this exception were thrown out of SDK...so I think it make sense to capture it in open telemetry (in case it comes up for any edge case). other wise open telemetry won't record this exception.

2022-06-24 18:55 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Resource/Conflict/ConflictsInlineCore.cs
> +                openTelemetry: (response) => new OpenTelemetryResponse(response));
Not right, still all the cases are not covered right now.. 
May be, You can suggest me, does it make sense to make changes for all the operations? Right now ,As part of this PR,I was targeting specific kind of APIs as mentioned in the PR description.

2022-06-24 18:58 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryResponse.cs
> +                return Convert.ToString(response.Content.Length);
ResponseContentLength is string type.

2022-06-24 21:55 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientTests.cs
> +            OpenTelemetryTests.ClassInitialize(context);
yes..where ever I want to enable open telemetry

2022-06-29 20:23 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryAttributes.cs
> +            this.RequestContentLength = requestMessage?.Headers?.ContentLength ?? "0";
We might actually always buffer (transfer to MemoryStream) - but I don't know for sure - and definitely we should have test coverage because that could other wise be easily regressed

2022-06-29 20:33 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryAttributes.cs
> +            this.RequestContentLength = requestMessage?.Headers?.ContentLength ?? "0";
Just changed to "NA" if request content length information is "Not available". I have similar code in client telemetry to get the response content siz where we are checking if it is memory stream otherwise check it in header.
For Request stream, Content stream is always closed at this point of time, so we are relied on header value, if available. I have an issue https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3317 created to get request size from diagnostic string which can be used here.

2022-06-29 20:45 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +        public void MarkFailed<T>(T exception)
This method needs some refactoring - right now it is very easy to miss making the necessary changes here when introducing a new CosmosException, because it is hard to discover that you also need to touch this file when adding a new CosmosException. Unfortunately we have CosmosException and CosmosOperationCancelledException being public and not sealed - so adding any interface would be considered a breaking change.
My proposal would be this:
- introduce a Dictionary<Type, Action<Exception, DiagnosticScope>> where you register the different CosmosExceptions with an Action that is a static method on the exception class. Then you iterate through the dictionary's keys here - check whether the Exception can be casted to the type in the dictionary and if so you call the registered action. There you cast the Exception into the expected strong type and do whatever you have in the if statements here right now.
- Add a unit test that iterates through all exceptions in the ComsosExceptions namespace and checks whether the dictionary registered in thsi class has an entry with it. It should fail if there is any COmsosException without entry in the dictionary.

That way when introducing a new CosmosException it becomes more discoverable that some special handling is needed for diagnostics - and you can more easily add test coverage to validate it.

2022-06-29 20:51 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryResponse.cs
> +            : base(responseMessage.RequestMessage)
At least assert or throw ArguemntNullException if responseMessage is null -= like

: base((responseMessage ?? throw new ArgumentNullException(nameof(responseMessage))).RequestMessage)

2022-06-29 20:54 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryResponse.cs
> +                return Convert.ToString(response.Content.Length);
See - https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.canseek?view=net-6.0#remarks - better way than checking if this is MemoryStream would be to use response.Content.CanSeek (Can Read always has to be true for response content - you can assert on it - or if you feel safer add it to the condition)

2022-06-29 20:56 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryResponse.cs
> +                return Convert.ToString(response.Content.Length);
I also think even if the Stream is non-seekable we should have at least a way to determine whether payload is <= 1024 bytes or not - this would require us injecting some kind of buffered Stream that we can use to determine the Is!kbPayload flag wihtout causing too aggressive memory overhead/allocations. This is applicable for request and response - and I am fine with doing it in a separate PR - but please add an issue to trakc this so that it doesn't get lost.

2022-06-29 21:14 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryResponse{T}.cs
> +            //TODO: ItemCount needs to be added
What ItemCount - you mean for FeedResponse<T>?

2022-06-29 21:15 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosBadReplicaTests.cs
> +            OpenTelemetryTests.ClassInitialize();
Please put this in a base class that you inherit from instead

2022-06-29 21:17 UTC, FabianMeiswinkel requested changes
Looks pretty good already - just left a few comments.

2022-06-29 21:28 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
> +                catch (CosmosException ex)
What I mean is, you have a Catch for Exception, that will also catch CosmosException

2022-06-29 21:30 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Conflict/ConflictsInlineCore.cs
> +                openTelemetry: (response) => new OpenTelemetryResponse(response));
If there are for example 30 APIs and you are wiring right now 25, I would prefer that you wired the remaining 5 and remove the default null. Basically, if the percentage of remaining APIs is low, then why not.

2022-06-29 21:37 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Telemetry/OpenTelemetryTests.cs
> +    public abstract class OpenTelemetryTests
Unresolving, this is not addressed. This should not have the `[TestClass]` decorator. Also if you want to enable OpenTelemetry on a Test Class that already has a `[ClassInitialize]` it won't work (also you cannot inherit from multiple abstract classes if the test class already inherited from another, so that limits your approach)

2022-06-30 00:21 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
> -                    throw new CosmosOperationCanceledException(oe, trace);
Can recorder be null, if so how is it handled?

2022-06-30 00:27 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInlineCore.cs
> +                (response) => new OpenTelemetryResponse<ContainerProperties>(response));
OTResponse creation spilled through all consumers. 
Thoughts on possibility of limiting it to OperationHelper only? 

/cc: @ealsur , @FabianMeiswinkel

2022-06-30 20:56 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
> +                catch (CosmosException ex)
`CosmosException `has _requestcharge_, _statuscode_, _diagnostics_, which is not there in `Exception`.

2022-06-30 20:58 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Resource/Conflict/ConflictsInlineCore.cs
> +                openTelemetry: (response) => new OpenTelemetryResponse(response));
As mentioned in PR description, I am wiring almost all the API but this model is not working for few API as there we are not return response object, these special case needs to be handled in future PRs, before going GA.

2022-06-30 21:10 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryResponse.cs
> +                return Convert.ToString(response.Content.Length);
@FabianMeiswinkel 
1) Using CanSeek  flag if stream can give Length information.
2) This is all happening at hot path, so it is not good idea to do much work with stream here. Maybe we should find a place in SDK where we can get it easily and can use here without impacting the performance.

@ealsur We are getting it from header as string and we need it as a string. Thats why converted it also in string instead of converting it `long` and then to `string`.

2022-06-30 21:13 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Telemetry/OpenTelemetryTests.cs
> +    public abstract class OpenTelemetryTests
Removed this class and written new baseline test to Test Open telemetry feature

2022-06-30 21:25 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryResponse.cs
> +            : base(responseMessage.RequestMessage)
I don't want to fail customers calls if anything fails in OpenTelemetry system, if something is not working in Opentelemetry, then that part only should misbehave.
In this case, if response is null anyhow (which is kind of impossible) then, I don't think customer can do anything to fix it, instead of that open telemetry attributes should be blank or should say "Not Available" on listener

2022-06-30 21:25 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryResponse.cs
> +            return response?.Headers?.ContentLength ?? "0";
done

2022-06-30 21:35 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryResponse{T}.cs
> +            //TODO: ItemCount needs to be added
So from opentelemetry perspective it doesnot care which kind of response it is, if this information is available in header it will just add it..in my new changes i have added this information also.

2022-06-30 21:55 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosBadReplicaTests.cs
> +            OpenTelemetryTests.ClassInitialize();
removed these changes

2022-06-30 21:55 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
> -                    throw new CosmosOperationCanceledException(oe, trace);
it can be default which will behave like NoOp.

2022-06-30 21:57 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInlineCore.cs
> +                (response) => new OpenTelemetryResponse<ContainerProperties>(response));
I started with that but for that we would need to typecast TResult to a specific type of response (depends on the operation) to get the values out of it which was not straightforward. Thats why went into this way.

2022-07-01 02:29 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInlineCore.cs
> +                (response) => new OpenTelemetryResponse<ContainerProperties>(response));
Let's go-over it tomorrow and close on it.

2022-07-01 23:57 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +        public void MarkFailed<T>(T exception)
done

2022-07-02 01:16 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/ChangeFeed/ChangeFeedIteratorCore.cs
> +                Console.WriteLine(ex.Message);
Is it intentional?

2022-07-02 01:22 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
> +#if PREVIEW
Let's please push such decision to where defaults are defined.

2022-07-02 01:25 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +        public void MarkFailed<T>(T exception)
Usage/implementation is generic, Is <t> generic required?

2022-07-02 01:26 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
> +                    recorder.MarkFailed(cex);
Is specialization required for CosmosException vs Exception?

2022-07-02 01:30 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +        internal static IDictionary<Type, Action<Exception, DiagnosticScope>> oTelCompatibleExceptions = new Dictionary<Type, Action<Exception, DiagnosticScope>>()
Thoughts on Dict lookup for delegate vs if-else?
Performance wise I am guessing that Dict version might have more overhead.

2022-07-02 01:33 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.BulkOperationsAsync.xml
> +    List<List<string>> oTelActivities = new List<List<string>>();
How about two baselines with and with-out otel?

2022-07-02 10:34 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/ChangeFeed/ChangeFeedIteratorCore.cs
> +                Console.WriteLine(ex.Message);
it was not intentional.

2022-07-02 10:44 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
> +#if PREVIEW
done

2022-07-02 10:51 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +        public void MarkFailed<T>(T exception)
It is not required...i don't think it really matter we are using conditional generics or Exception type input.

2022-07-02 10:56 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
> +                    recorder.MarkFailed(cex);
yes...cosmos exception has diagnostics info but Exception has.

2022-07-02 11:48 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +            if (OpenTelemetryCoreRecorder.oTelCompatibleExceptions.TryGetValue(exception.GetType(), out Action<Exception, DiagnosticScope> value))
This is wrong - you would only map to exact exceptions - not Exceptions inheriting from any of the CosmosXXX exceptions. Some of the CosmosXXX exceptions are unsealed and public - so customers could inherit fomr it. This was the reason why just adding an interface would be breaking in the first place.

So instead you have to do somethign like

foreach (KeyValuePair<Type, Action<Exception, DiagnosticScope>> registeredEceptionHandlers in OpenTelemetryCoreRecorder.oTelCompatibleExceptions)
{
    Type exceptionType = exception.GetType();
    if (exceptionType .IsAssignableFrom(registeredEceptionHandlers.Key) || exceptionType .IsImplicitlyCastableTo(registeredEceptionHandlers.Key))
    {
        registeredEceptionHandlers.Value(exception, scope);
        break;
    }
}

2022-07-02 11:49 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +        internal static IDictionary<Type, Action<Exception, DiagnosticScope>> oTelCompatibleExceptions = new Dictionary<Type, Action<Exception, DiagnosticScope>>()
Irrelevant because Dictionary lookup isn't sufficiant anyway. But otherwise I would prefer Dictionary because the main motivation was to not have a fixed list that would need to be extended in this File when adding another exception - any switch/case or if/else based variant would make it easier to screw up here. And the perf difference is negligible - especially because it only would happen in exception case anyway.

2022-07-02 11:50 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/EndToEndTraceWriterBaselineTests.cs
> +            Console.WriteLine("RUnning bulk");
NIT typo

2022-07-02 11:51 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/EndToEndTraceWriterBaselineTests.cs
> +            Console.WriteLine("RUnning bulk");
NIT typo

2022-07-02 11:55 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Telemetry/OpenTelemetryRecorderTests.cs
> +                .GetTypes()
NIT - IMO a comment clarifying that GetTypes (unlike GetExportedTypes) also returns internal types. I had to look it up when reviewing the code - so, I assume some other devs are also not super familiar to know the difference. Many other Reflection APIs require you to opt-in to see internal properties/methods etc. And it is critical here to include internal types.

2022-07-02 11:58 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInlineCore.cs
> +                (response) => new OpenTelemetryResponse<ContainerProperties>(response));
I am fine either way - all internal and from my perspective not a maintenance issue as is. But let's see - if there are better proposals, perfect.

2022-07-03 09:20 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +        internal static IDictionary<Type, Action<Exception, DiagnosticScope>> oTelCompatibleExceptions = new Dictionary<Type, Action<Exception, DiagnosticScope>>()
It will get looked up only in case of failure, I don't think this much performance hit should be concerned here at all.

2022-07-03 09:21 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.BulkOperationsAsync.xml
> +    List<List<string>> oTelActivities = new List<List<string>>();
why? can you please explain what would be the benefit? Once open telemetry is GAed...then baseline without OTel won't be of any use.

2022-07-03 09:22 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/EndToEndTraceWriterBaselineTests.cs
> +            Console.WriteLine("RUnning bulk");
removed.

2022-07-04 11:06 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +            if (OpenTelemetryCoreRecorder.oTelCompatibleExceptions.TryGetValue(exception.GetType(), out Action<Exception, DiagnosticScope> value))
You can ignroe the second part of the condition and just us exceptionType .IsAssignableFrom(registeredEceptionHandlers.Key) 

That checks whether the class is of that type or a sub-class - which is good enough for our use case

2022-07-04 20:43 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +            bool isExceptionRegistered = false;
```suggestion
```

2022-07-04 20:43 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +            return isExceptionRegistered;
```suggestion
            return false;
```

2022-07-04 20:43 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +                    isExceptionRegistered = true;
```suggestion
                    return true;
```

2022-07-04 20:44 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +                    break;
```suggestion
```

2022-07-04 20:44 UTC, FabianMeiswinkel submitted a review, later dismissed
LGTM - except for NITs around making the is `IsExceptionRegistered` implementation prettier and more concise

2022-07-05 11:45 UTC, FabianMeiswinkel approved these changes
LGTM

2022-07-06 13:49 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +#if PREVIEW
Some critical internal workloads are running with preview (including our gateway). Lets talk through this.

2022-07-06 22:03 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/Exceptions/ChangeFeedProcessorUserException.cs
> +            scope.AddAttribute(OpenTelemetryAttributeKeys.ExceptionMessage, exception.Message);
You are not doing anything special in this case, why do you need to special case it? Can't this be a generic capture of the exception.Message?

2022-07-06 22:05 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +            { typeof(ChangeFeedProcessorUserException), (exception, scope) => ChangeFeedProcessorUserException.RecordOtelAttributes((ChangeFeedProcessorUserException)exception, scope)}
No need to special case `ChangeFeedProcessorUserException`, this does not go over the pipeline.

2022-07-06 22:37 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +            { typeof(ChangeFeedProcessorUserException), (exception, scope) => ChangeFeedProcessorUserException.RecordOtelAttributes((ChangeFeedProcessorUserException)exception, scope)}
1) https://github.com/Azure/azure-cosmos-dotnet-v3/blob/0a11752acb6a0a5e71665ff7717d6f6f1a92cdb7/Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.ChangeFeedAsync.xml#L3491

Baseline tests are showing that open telemetry attributes are getting captured in ChangeFeed operation also so having `ChangeFeedProcessorUserException `in this dictionary makes sense.

2) I think we should keep the things simple here, lets apply same rule (i.e. recording otel attrs)  for all the exception classes otherwise in future it will be confusing which one to include or which one not. it will get called if applicable otherwise it will never look for that particular key in the dictionary.

2022-07-06 22:38 UTC, ealsur approved these changes

2022-07-06 22:38 UTC, merged