Direct: Adds version 3.29.0
Azure/azure-cosmos-dotnet-v3 pull request #3308
Opened 2022-06-27 11:22 UTC by imanvt

# Pull Request Template

## Description

* Adds Direct Version 3.29.0
* Performance: Replaces DateTime.UtcNow.ToString("r") with Rfc1123DateTimeCache.UtcNow() 

## Type of change
- [ ] New feature (non-breaking change which adds functionality)

## Closing issues
Part 1 of 2 for Issue #3274

2022-06-30 14:53 UTC, j82w commented on Directory.Build.props
> +		<DirectVersion>3.29.0</DirectVersion>
Doesn't this file needed to be updated to include the new dependencies?
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.targets

based on this PR?
https://msdata.visualstudio.com/CosmosDB/_git/CosmosDB/pullrequest/782198

2022-06-30 14:55 UTC, j82w commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DirectContractTests.cs
> +                { "System.Configuration.ConfigurationManager", new Version(6, 0, 0) },
Please include the version change in the PR description.

2022-06-30 14:58 UTC, ealsur commented on Directory.Build.props
> +		<DirectVersion>3.29.0</DirectVersion>
We'll do it in a separate PR

2022-06-30 15:56 UTC, FabianMeiswinkel requested changes
Question regarding version upgrade

2022-06-30 19:17 UTC, ealsur commented on Directory.Build.props
> +		<DirectVersion>3.29.0</DirectVersion>
Reference https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3322

2022-07-01 18:27 UTC, imanvt commented on Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
> -		<PackageReference Include="System.Configuration.ConfigurationManager" Version="4.7.0" />
updated the description and will make sure to add this into next set of release notes in changelog.

2022-07-05 12:56 UTC, j82w approved these changes

2022-07-05 13:17 UTC, FabianMeiswinkel approved these changes
LGTM

2022-07-05 13:29 UTC, merged

2023-01-31 16:33 UTC, LeszekKalibrate commented
`Adds Direct Version 3.29.0, which upgrades System.Configuration.ConfigurationManager dependency from 4.7.0 to 6.0.0`
This is a breaking change when the CosmosDB SDK is used in Azure Function .Net Core 3.1.