[Preview] AIIntegration: Adds Client and other information in attributes
Azure/azure-cosmos-dotnet-v3 pull request #3331
Opened 2022-07-07 21:04 UTC by sourabh1007

## Description

PR to collect remaining information:

<html>
<body>

db.name | < Database Name > |  
-- | -- | --
db.operation | ReadItemAsync, DeleteItemStreamAsync etc | Database Operation Name
net.peer.name | e.g. sourabhjaintemp | Account Name + Cloud

</body>
</html>

<html>
<body>

Attribute | Value | Comment
-- | -- | --
db.cosmosdb.client_id | Unique Client Id | Combination of client id and machine id can tell us, if customer is following best practices to create singleton client
db.cosmosdb.machine_id | Unique Machine Id |  
db.cosmosdb.user_agent | < User Agent With SDK version> | Useful to identify the SDK version
db.cosmosdb.connection_mode | Direct/Gateway | go through

</body>
</html>
## Type of change

- [] New feature (non-breaking change which adds functionality)

## Closing issues

To automatically close an issue: closes #3324

2022-07-07 21:54 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryAttributes.cs
> +            this.ContainerName = requestMessage?.ContainerId ?? "NA";
nit: Should all the NA be a private const to reduce allocations?

2022-07-07 21:56 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +                                        .Append(clientContext.DocumentClient?.AccountProperties?.Id)
Is this Record call happening after the operation executed or before? If before, there is a chance this is empty for the first request since initialization didn't happen? Should we simply not log it then?

2022-07-07 21:57 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/VmMetadataApiHandler.cs
> +        private static readonly string nonAzureCloud = "NonAzureCloud";
This could also happen when running in an Azure service that does not support this API call right? Or are we sure all Azure hosting options allow this?

2022-07-07 21:58 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +        internal AccountProperties AccountProperties { get; set; }
What's the external setter for?

2022-07-07 22:01 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +            this.AccountProperties = accountProperties;
This information is already available in the `accountServiceConfiguration`. What is the benefit of exposing this as yet another property instead of changing the accessor of `accountServiceConfiguration`?

2022-07-08 15:52 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +                                        .Append(clientContext.DocumentClient?.AccountProperties?.Id)
It is getting called during operation (create /delete item etc) call. by that time we must have account information available.

2022-07-08 16:18 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/VmMetadataApiHandler.cs
> +        private static readonly string nonAzureCloud = "NonAzureCloud";
This service runs inside the virtual machine so it will be there always. I think I should rename it to "NonAzureVM" it can Azure cloud but but it is possible that it is not VM

2022-07-08 16:21 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +        internal AccountProperties AccountProperties { get; set; }
removed it..other comment makes sense

2022-07-11 20:12 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +                                        .Append(clientContext.DocumentClient?.accountServiceConfiguration?.AccountProperties?.Id)
When is this going to be null `clientContext.DocumentClient?.accountServiceConfiguration?.AccountProperties?.Id`  ?

Assuming this is executed after the client initialized, then it should never be null.

If this can execute before the client initializes, then if would be better not adding `netPeerName` until this has a valid value

2022-07-11 20:33 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +                                        .Append(clientContext.DocumentClient?.accountServiceConfiguration?.AccountProperties?.Id)
if anyhow it gets called before client initialization then Account Information will be null. but still it will tell us if customer is on AzureVM or not this information won't be null. So IMO having `netPeerName ` makes sense.

Here I am assuming, client initialization means `accountServiceConfiguration ` Initialization. because I think initializing a client is very first step to use cosmosdb SDK.

2022-07-11 20:56 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +                                        .Append(clientContext.DocumentClient?.accountServiceConfiguration?.AccountProperties?.Id)
Correct, but initialization happens on the first request. That is why it's important to know exactly when this method is executed.

If `clientContext.DocumentClient?.accountServiceConfiguration?.AccountProperties?.Id` can be null, you are appending a `null` to the StringBuilder, the final value would be `({VM info})` and then on the next request if the client is initialized it would change to `accountName ({VM info})` which would be inconsistent.

That is why I would think that, if this is expected to execute after initialization, then getting a `null` would be an error and we shouldn't hide it.

If it can execute before initialization, having inconsistent information would not be ideal, we could just skip that value until it has consistent information.

2022-07-11 21:06 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +                                        .Append(clientContext.DocumentClient?.accountServiceConfiguration?.AccountProperties?.Id)
This concatenation should only happen once and be cached in AccountProperties?

2022-07-11 21:08 UTC, FabianMeiswinkel requested changes
LGTM except for the one comment about the inefficient computation of netPerrname for every event

2022-07-11 21:23 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +                                        .Append(clientContext.DocumentClient?.accountServiceConfiguration?.AccountProperties?.Id)
It can be cached inside this class? As it depends on 2 values (account properties and VM identifier) that are not related to each other?

2022-07-11 21:40 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +                                        .Append(clientContext.DocumentClient?.accountServiceConfiguration?.AccountProperties?.Id)
This method gets called after the actual operation call. https://github.com/Azure/azure-cosmos-dotnet-v3/blob/a3b0cefc15acda2a9f878480f943ecb5d9428831/Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs#L488.

So getting a null would be an error.

2022-07-11 21:40 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +                                        .Append(clientContext.DocumentClient?.accountServiceConfiguration?.AccountProperties?.Id)
Made this change.

2022-07-11 22:32 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Resource/Settings/AccountProperties.cs
> +        internal string AccountNameWithCloudInformation => new StringBuilder()
My main point was to cache the calculation - and invalidate it only if Id or GetCloudInformation change - otherwise you allocate a new string and calculate the content every single time - and always create the same string

2022-07-12 15:00 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Resource/Settings/AccountProperties.cs
> +        internal string AccountNameWithCloudInformation => new StringBuilder()
got it..made the changes.and made it a part of `AccountProperties `only so...I don't have to worry about invalidation logic and as soon as we have new `AccountProperties ` available it will calculate this value only at first call after that it will use the cached value.

2022-07-14 14:39 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Settings/AccountProperties.cs
> +        private string accountNameWithCloudInformation;
Why do you need this variable?

2022-07-14 14:39 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Settings/AccountProperties.cs
> +            if (!string.IsNullOrEmpty(this.accountNameWithCloudInformation) && this.prevId == this.Id)
What is the point of this check? This method will be run only once

2022-07-14 17:47 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Resource/Settings/AccountProperties.cs
> +            if (!string.IsNullOrEmpty(this.accountNameWithCloudInformation) && this.prevId == this.Id)
why do you think it will run only once? it will get called everytime OpenTelemetry sets an attribute.

2022-07-14 17:48 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Resource/Settings/AccountProperties.cs
> +        private string accountNameWithCloudInformation;
to cache the information. I have removed the "Lazy" logic.

2022-07-14 18:24 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Settings/AccountProperties.cs
> +        private string accountNameWithCloudInformation;
Why? Doesn't this mean then that the caller of this method is calling it before initialization is complete? And if so, then isn't that the problem?

2022-07-14 18:24 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Settings/AccountProperties.cs
> +        private string accountNameWithCloudInformation;
Why doesn't the Lazy approach work?

2022-07-14 18:24 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Settings/AccountProperties.cs
> +            if (!string.IsNullOrEmpty(this.accountNameWithCloudInformation) && this.prevId == this.Id)
Because a Lazy is calculated/constructed only once

2022-07-14 22:49 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Resource/Settings/AccountProperties.cs
> +        private string accountNameWithCloudInformation;
what is the benefit of using lazy here?

2022-07-15 15:13 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Settings/AccountProperties.cs
> +            if (!string.IsNullOrEmpty(this.accountNameWithCloudInformation) && this.prevId == this.Id)
That is the whole point of Lazy: https://docs.microsoft.com/en-us/dotnet/api/system.lazy-1?view=net-6.0, the value of the object is only calculated once, afterwards, all accesses of the Value use the calculated value.

2022-07-15 15:14 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Settings/AccountProperties.cs
> +        private string accountNameWithCloudInformation;
Calculating the value of the property only once and reusing across all other reads, the string is only constructed once (1 allocation)

2022-07-15 17:28 UTC, ealsur submitted a review, later dismissed

2022-07-22 16:13 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Settings/AccountProperties.cs
> +        private string AppendAccountAndCloudInfo()
As proposed by Fabian:

```
        [JsonProperty(PropertyName = Constants.Properties.Id)]
        public string Id
        {
            get
            {
                return this.id;
            }
            
            internal set
            {
                this.id = value;
                this.accountNameWithCloudInfo = null;
            }
        }
```

```
[JsonIgnore]
        internal string AccountNameWithCloudInformation
        {
            get
            {
                string accountNameWithCloudInfoSnapshot = this.accountNameWithCloudInfo;
                if (!string.IsNullOrEmpty(accountNameWithCloudInfoSnapshot))
                {
                    return accountNameWithCloudInfoSnapshot;
                }

                return this.accountNameWithCloudInfo = $"{this.Id}({VmMetadataApiHandler.GetCloudInformation()})";
            }
        }
```

That removes the need for `prevId` variable and the lock.

2022-07-25 17:28 UTC, FabianMeiswinkel approved these changes
LGTM

2022-07-25 17:38 UTC, ealsur approved these changes

2022-07-25 17:38 UTC, merged