Memory Improvements - Adopt RecyclableMemoryStream.
Azure/azure-cosmos-dotnet-v3 pull request #3382
Opened 2022-08-10 22:10 UTC by fhibf

## Description

RecyclableMemoryStream is a MemoryStream replacement that offers superior behavior for performance-critical systems.

The motivation for start using it is: 
* Eliminate Large Object Heap allocations by using pooled buffers.
* Avoid memory leaks by having a bounded pool size.
* Avoid memory fragmentation.

## Type of change

Please delete options that are not relevant.

- [x] Performance improvement.
- [x] This change requires a documentation update

2022-08-11 21:24 UTC, neildsh commented on CONTRIBUTING.md
> +- `Microsoft.IO.RecyclableMemoryStream` - This package contains the RecyclableMemoryStream, a MemoryStream replacement that offers superior behavior for performance-critical systems.
>`Microsoft.IO.RecyclableMemoryStream` - Thi [](http://example.com/codeflow?start=2&length=43)

Thank you for taking an interest in this project and contributing!

Since you seem to be Microsoft internal, it would be a good idea to set up a design review, since this change can have a major impact on the sdk. Please send a design document ahead of the meeting so that participants can add comments.

2022-08-12 01:11 UTC, fhibf commented on CONTRIBUTING.md
> +- `Microsoft.IO.RecyclableMemoryStream` - This package contains the RecyclableMemoryStream, a MemoryStream replacement that offers superior behavior for performance-critical systems.
Hey, @neildsh.
Thanks for the comment. Is there a discussion list that I could reach out to schedule the design review. 
It would be great if you folks have a list of items that you expect to see during the design review. 
Thanks!

2022-08-17 15:16 UTC, ealsur requested changes
We cannot take dependency on `Microsoft.IO.RecyclableMemoryStream`. We have future plans to allow users to pass their own pool to be used for these operations. This project only contains part of the SDK, the TCP protocol stack is in the `Microsoft.Azure.Cosmos.Direct` and the TCP communication already uses memory pools (https://github.com/Azure/azure-cosmos-dotnet-v3/blob/direct/main/Microsoft.Azure.Cosmos/src/direct/Connection.cs#L82). We can sync offline for further details if you want

2022-11-28 18:32 UTC, brendankowitz commented on Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
> +		<PackageReference Include="Microsoft.IO.RecyclableMemoryStream" Version="2.2.0" />
Hi @ealsur, wanted to loop back on this. Question: would it be acceptable to make StreamManager have a settable provider which we could replace? This should introduce no additional dependencies, but allow us to override.

On very large Cosmos instances it looks like the large objects used to buffer are continually causing OutOfMemoryExceptions. Allowing Recyclable streams should be a way to mitigate the creation of so many of these

2023-01-25 00:27 UTC, kirankumarkolli commented
Closing in-active PR's

2023-01-25 00:27 UTC, closed without merging