Query: Fixes LINQ ToString got absorbed during translation
Azure/azure-cosmos-dotnet-v3 pull request #3385
Opened 2022-08-15 19:40 UTC by leminh98

# Pull Request Template

## Description

This PR fixes the issue of  ToString got removed during the LINQ to SQL translation process. 

Before: container.GetItemLinqQueryable().select(doc => doc.field_a.ToString()) will get translated to SELECT VALUE r.field_a FROM r
After: this query will translate to use the CosmosDB ToString function: SELECT VALUE ToString(r.field_a) FROM r

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

closes #3346 

To automatically close an issue: closes #IssueNumber

2022-08-18 16:02 UTC, khdang commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.ValidateLinqQueries.xml
> +WHERE (ToString(root["id"]) = "098aa945-7ed8-4c50-b7b8-bd99eddb54bc")]]></SqlQuery>
can we try to not emit ToString for types that are represented in string in Cosmos DB (e.g. string, guid)? 

Due to the nature of the execution, ToString() wouldn't use the index very efficiently. If we know that the type is represented by a string, then emitting ToString() is not needed and would result in a lost of the type information, which is available in .NET runtime but not in the query execution (ie. backend cannot know the type of 'id' here, but from the data model we know it is a Guid and is stored as string in the backend).

2022-08-23 20:33 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Linq/BuiltinFunctions/StringBuiltinFunctions.cs
> +                    null)
Nit, ok to use same line.

2022-08-23 20:34 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqTranslationBaselineTests.cs
> +                new LinqTestInput("Substring", b => getQuery(b).Select(doc => doc.StringField.ToString())),
>Substring [](http://example.com/codeflow?start=35&length=9)

ToString?

2022-08-23 20:37 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.ValidateLinqQueries.xml
> +WHERE (ToString(root["id"]) = "098aa945-7ed8-4c50-b7b8-bd99eddb54bc")]]></SqlQuery>
Curious questions:
Do we know the type of the value of a property? Also, given that it can vary across documents, will that create an issue?

2022-08-23 20:41 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestThenByTranslation.xml
> +        ORDER BY (root["IsRegistered"] ? root["FamilyId"] : ToString(root["Int"])) DESC, (v0[0] % 1000) ASC
>ToString(root["Int"]) [](http://example.com/codeflow?start=60&length=21)

I wonder if there's a back-compat issue here.

Does our ToString implementation guarantee that ToString(v) == v?

where v can be any valid json type?

2022-08-23 20:42 UTC, adityasa requested changes
:clock1:

2022-08-25 23:28 UTC, leminh98 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestThenByTranslation.xml
> +        ORDER BY (root["IsRegistered"] ? root["FamilyId"] : ToString(root["Int"])) DESC, (v0[0] % 1000) ASC
That's for the BE to decide, right? Since that is dependent on the ToString system function

2022-09-19 08:13 UTC, leminh98 commented on Microsoft.Azure.Cosmos/src/Linq/BuiltinFunctions/StringBuiltinFunctions.cs
> +                    null)
I'm keeping it consistent with other stringvisit functions that are keeping them on separate lines as well

2022-09-19 08:14 UTC, leminh98 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqTranslationBaselineTests.cs
> +                new LinqTestInput("Substring", b => getQuery(b).Select(doc => doc.StringField.ToString())),
fixed

2022-09-19 08:15 UTC, leminh98 commented on Microsoft.Azure.Cosmos/src/Linq/BuiltinFunctions/BuiltinFunctionVisitor.cs
> +                 methodCallExpression.Object != null))
Exostomg tests from before the changes should cover it. (I.e the change in ThenBy for example)

2022-09-19 08:44 UTC, leminh98 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.ValidateLinqQueries.xml
> +WHERE (ToString(root["id"]) = "098aa945-7ed8-4c50-b7b8-bd99eddb54bc")]]></SqlQuery>
@adityasa We know the type of the value of the object like in the example above because they are concretely typed in that object initializer.
@khdang I added the exception for these two types: string and guid. Do we have any other types that we want to create exception for?

2022-09-20 18:21 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqTranslationBaselineTests.cs
> +                new LinqTestInput("ToString", b => getQuery(b).Select(doc => doc.StringField.ToString())),
>doc.StringField.ToString() [](http://example.com/codeflow?start=77&length=26)

Please add ToString projections for all fields for added coverage.

2022-09-20 18:23 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqTranslationBaselineTests.cs
> +                new LinqTestInput("ToString", b => getQuery(b).Select(doc => doc.StringField.ToString())),
Can you add cases where ToString is an embedded expression:

doc => doc.StringField.StartsWith(doc.SomeOtherField.ToString(), StringComparison.Ordinal)

2022-09-20 18:23 UTC, adityasa approved these changes
:shipit:

2022-09-20 18:27 UTC, adityasa reviewed
Waiting for a final review.

2022-09-20 18:28 UTC, adityasa requested changes
Waiting for final review.

2022-09-30 17:17 UTC, sboshra commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqTranslationBaselineTests.cs
>                  // ToUpper
please add tests for different data types

2022-09-30 17:17 UTC, sboshra submitted a review, later dismissed
:shipit:

2022-10-11 20:17 UTC, leminh98 commented
/azp stop

2022-10-11 20:17 UTC, leminh98 commented
/azp run

2022-10-12 22:01 UTC, adityasa approved these changes
:shipit:

2022-10-13 21:53 UTC, merged