Make `PatchOperation<T>` public
Azure/azure-cosmos-dotnet-v3 pull request #3404
Opened 2022-08-24 05:05 UTC by decodingahmed

## Description

The `PatchOperation<T>` object is now made public.  This will allow consumers to cast any `PatchOperation` objects to the `PatchOperation<T>` class in order to access the `Value` property. 

For the author's use-case this will allow tests to check that the service level code is passing correct values into the patch request.

In order to avoid introducing a breaking change, these changes do not change the return type of the `Add`, `Set`, `Replace` and `Increment` methods of the `PatchOperation` class.

This PR addresses: https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3374

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Closing issues
Closes https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3374

2022-08-24 05:44 UTC, decodingahmed commented
/azp run

2022-08-24 14:11 UTC, ealsur commented
/azp run

2022-08-24 14:32 UTC, ealsur approved these changes

2022-08-24 14:35 UTC, ealsur requested changes

2022-08-24 14:35 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Patch/PatchOperationTests.cs
> +namespace Microsoft.Azure.Cosmos.Tests.Patch
Can we keep the same namespace as before?

2022-08-24 14:35 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Patch/PatchOperation{T}Tests.cs
> +namespace Microsoft.Azure.Cosmos.Tests.Patch
Can we keep the same namespace as the other test files? `Microsoft.Azure.Cosmos.Tests`

2022-08-25 09:08 UTC, decodingahmed commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Patch/PatchOperation{T}Tests.cs
> +namespace Microsoft.Azure.Cosmos.Tests.Patch
Sure no problem.

2022-08-25 09:08 UTC, decodingahmed commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Patch/PatchOperationTests.cs
> +namespace Microsoft.Azure.Cosmos.Tests.Patch
Sure no problem

2022-08-25 09:28 UTC, decodingahmed commented
/azp run

2022-08-25 14:17 UTC, ealsur commented
/azp run

2022-08-25 15:25 UTC, ealsur approved these changes

2022-08-25 15:25 UTC, merged