[Internal] Query: Adds parsing resilience to IndexMetrics
Azure/azure-cosmos-dotnet-v3 pull request #3418
Opened 2022-08-25 23:16 UTC by leminh98

# Pull Request Template

## Description

This change adds the ability for the SDK to parse information sent back from the IndexMetrics in a more resilient manner, so that the BE can freely change the format of the header value. 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

2022-09-14 20:46 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Handler/ResponseMessage.cs
> +                        }
Shouldn't this be based on the request header?

2022-09-14 20:47 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Handler/ResponseMessage.cs
> +                        if (tryDeserializeNonBase64 == false)
Nit : if(!tryDeserializeNonBase64)

2022-09-14 20:48 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Metrics/IndexUtilizationInfoTests.cs
> +            Console.WriteLine(stringBuilder.ToString());
Is this needed?

2022-09-14 20:52 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Metrics/IndexUtilizationInfoTests.cs
> +            Assert.IsNotNull(parsedInfo);
>Assert.IsNotNull(parsedInfo); [](http://example.com/codeflow?start=12&length=29)

Compare with actual text or turn this into a baseline test?

2022-09-14 20:53 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Metrics/IndexUtilizationInfoTests.cs
> +
Same as before?

2022-09-14 20:55 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Metrics/IndexUtilizationInfoTests.cs
> +            // Valid Json missing entire IndexUtilization arrays
>// Valid Json missing entire IndexUtilization arrays [](http://example.com/codeflow?start=12&length=52)

Could you also include a test with additional fields in the json?

2022-09-14 20:56 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Metrics/IndexUtilizationInfoTests.cs
> +        public void TestBase64Parse()
>TestBase64Parse [](http://example.com/codeflow?start=20&length=15)

We have more coverage for plaintext than base64. Is there a specific reason?

Consider using same cases for both for better coverage.

2022-09-14 20:59 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/IndexMetricsParserBaselineTest.cs
> +            };
Not needed?

2022-09-14 21:00 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/IndexMetricsParserBaselineTest.cs
> +            cosmosClient = TestCommon.CreateCosmosClient();
>cosmosClient [](http://example.com/codeflow?start=12&length=12)

this. prefix (here and in the rest of this file)?

2022-09-14 21:04 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/IndexMetricsParserBaselineTest.cs
> +                  description: "Unicode 1",
Nit, inconsistent indentation. Also in remaining cases.

2022-09-14 21:12 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/IndexMetricsParserBaselineTest.cs
> +                return new IndexMetricsParserTestOutput(String.Empty, LinqTestsCommon.BuildExceptionMessageForTest(e));
Is this hit? Did I miss it in the baseline?

2022-09-14 21:13 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/IndexMetricsParserBaselineTest.cs
> +                return new IndexMetricsParserTestOutput(String.Empty, LinqTestsCommon.BuildExceptionMessageForTest(e));
If not, please remove try...catch and let the exception bubble up (and fail the test).

2022-09-14 21:17 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Query/Core/Metrics/SingleIndexUtilizationEntity.cs
> +            this.FilterExpression = filterExpression; // ?? throw new ArgumentNullException(nameof(filterExpression));
>// ?? throw new ArgumentNullException(nameof(filterExpression)); [](http://example.com/codeflow?start=54&length=64)

Kindly restore or remove.

2022-09-14 21:17 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Query/Core/Metrics/SingleIndexUtilizationEntity.cs
> +            this.IndexDocumentExpression = indexDocumentExpression; // ?? throw new ArgumentNullException(nameof(indexDocumentExpression));
Same.

2022-09-14 21:17 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Query/Core/Metrics/SingleIndexUtilizationEntity.cs
> +            this.IndexImpactScore = indexImpactScore; // ?? throw new ArgumentNullException(nameof(indexImpactScore));
Same.

2022-09-14 21:20 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Query/Core/Metrics/IndexUtilizationInfo.cs
>              this.UtilizedSingleIndexes = utilizedSingleIndexesCopy;
>this.UtilizedSingleIndexes = utilizedSingleIndexesCopy; [](http://example.com/codeflow?start=12&length=55)

Consider following instead of all the code above:
this.UtilizedSingleIndexes = (utilizedSingleIndexesCopy ?? Enumerable.Empty<SingleIndexUtilizationEntity>()).Where(item => item != null).ToList();

2022-09-14 21:22 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Query/Core/Metrics/IndexUtilizationInfo.cs
> +            catch
>catch [](http://example.com/codeflow?start=12&length=5)

We should catch only a specific set of well known exceptions here.

2022-09-14 21:23 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Query/Core/Metrics/IndexUtilizationInfo.cs
>              catch
>catch [](http://example.com/codeflow?start=12&length=5)

Same as above.

2022-09-14 21:24 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Query/Core/Metrics/IndexUtilizationInfo.cs
> +                result ??= IndexUtilizationInfo.Empty;
Combine the two statements?

}) ?? IndexUtilizationInfo.Empty;

2022-09-14 21:25 UTC, adityasa requested changes
:clock1:

2022-09-19 07:16 UTC, leminh98 commented on Microsoft.Azure.Cosmos/src/Handler/ResponseMessage.cs
> +                        }
We are being permissive here. I don't think we get to know what the request headers are (correct me if I'm wrong there). 
Moreover, I think if there is any issues with receiving the request from the backend, it defaults to base 64.

2022-09-19 07:19 UTC, leminh98 commented on Microsoft.Azure.Cosmos/src/Handler/ResponseMessage.cs
> +                        if (tryDeserializeNonBase64 == false)
fixed

2022-09-19 07:21 UTC, leminh98 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Metrics/IndexUtilizationInfoTests.cs
> +            Console.WriteLine(stringBuilder.ToString());
Oh oops. That was some test snippets to make sure the header I receive from the BE was the expectation. Removed

2022-09-19 07:23 UTC, leminh98 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Metrics/IndexUtilizationInfoTests.cs
> +            Assert.IsNotNull(parsedInfo);
I added a baseline test suite. This one is just to make sure the parser is permissive

2022-09-19 07:23 UTC, leminh98 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Metrics/IndexUtilizationInfoTests.cs
> +
same comment as above

2022-09-19 07:24 UTC, leminh98 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Metrics/IndexUtilizationInfoTests.cs
> +        public void TestBase64Parse()
Those are legacy test code. But good suggestion. I will turn them into a loop

2022-09-19 07:44 UTC, leminh98 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Metrics/IndexUtilizationInfoTests.cs
> +            // Valid Json missing entire IndexUtilization arrays
done

2022-09-19 07:47 UTC, leminh98 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/IndexMetricsParserBaselineTest.cs
> +            };
this was mirroring other baseline files. But yeah this seems unnecesarry so i'll remove them

2022-09-19 07:51 UTC, leminh98 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/IndexMetricsParserBaselineTest.cs
> +            cosmosClient = TestCommon.CreateCosmosClient();
it's a static instance.

2022-09-19 07:53 UTC, leminh98 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/IndexMetricsParserBaselineTest.cs
> +                  description: "Unicode 1",
fixed

2022-09-19 07:56 UTC, leminh98 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/IndexMetricsParserBaselineTest.cs
> +                return new IndexMetricsParserTestOutput(String.Empty, LinqTestsCommon.BuildExceptionMessageForTest(e));
It's not hit in these test cases because the exception is in case there is wrong with any of the execution, (but there shouldn't). I'm not sure there is even a way to force it to fail.

This effectively also fail the test too because if the catch is ever hit, it will also change the baseline, which in turns fail the comparison for the baseline, which fails the test. So I think we should keep it as is as a try catch

2022-09-19 07:57 UTC, leminh98 commented on Microsoft.Azure.Cosmos/src/Query/Core/Metrics/SingleIndexUtilizationEntity.cs
> +            this.FilterExpression = filterExpression; // ?? throw new ArgumentNullException(nameof(filterExpression));
we are allowing them to be null instead of argument check for parsing flexibility

2022-09-19 08:00 UTC, leminh98 commented on Microsoft.Azure.Cosmos/src/Query/Core/Metrics/IndexUtilizationInfo.cs
> +            catch
Aren't we making it less resilient by doing that?

2022-09-19 08:01 UTC, leminh98 commented on Microsoft.Azure.Cosmos/src/Query/Core/Metrics/IndexUtilizationInfo.cs
> +                result ??= IndexUtilizationInfo.Empty;
That's neat. Fixed

2022-09-19 21:54 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/IndexMetricsParserBaselineTest.cs
> +        private static Container testContainer;
readonly

2022-09-20 17:52 UTC, leminh98 commented on Microsoft.Azure.Cosmos/src/Handler/ResponseMessage.cs
> +                        }
After discussion, we have decided to separate them

2022-09-20 17:53 UTC, leminh98 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/IndexMetricsParserBaselineTest.cs
> +                return new IndexMetricsParserTestOutput(String.Empty, LinqTestsCommon.BuildExceptionMessageForTest(e));
after discussion, we have decided to remove the try-catch

2022-09-22 21:20 UTC, sboshra commented on Microsoft.Azure.Cosmos/src/Handler/ResponseMessage.cs
> +
should not be initialized;

2022-09-22 21:24 UTC, sboshra commented on Microsoft.Azure.Cosmos/src/Query/Core/Metrics/CompositeIndexUtilizationEntity.cs
>          public IReadOnlyList<string> IndexDocumentExpressions { get; }
new line above

2022-09-22 21:26 UTC, sboshra commented on Microsoft.Azure.Cosmos/src/Query/Core/Metrics/IndexUtilizationInfo.cs
>              {
we should not allow null values in the entity list in the first place

2022-09-22 21:27 UTC, sboshra commented on Microsoft.Azure.Cosmos/src/Query/Core/Metrics/IndexUtilizationInfo.cs
>              {
newline above

2022-09-22 21:29 UTC, sboshra commented on Microsoft.Azure.Cosmos/src/Query/Core/Metrics/IndexUtilizationInfo.cs
if this does not throw, move it outside of the try/catch

2022-09-22 21:29 UTC, sboshra commented on Microsoft.Azure.Cosmos/src/Query/Core/Metrics/IndexUtilizationInfo.cs
> +            }
reconsider the try/catch

2022-09-22 21:30 UTC, sboshra commented
>             }

catch specific exceptions 

---
Refers to: Microsoft.Azure.Cosmos/src/Query/Core/Metrics/IndexUtilizationInfo.cs:148 in d3c7963. [](commit_id = d3c796306ac49abff542a56d7e9d4dee8b98427b, deletion_comment = False)

2022-09-22 21:32 UTC, sboshra commented
>         }

please remove

---
Refers to: Microsoft.Azure.Cosmos/src/Query/Core/Metrics/IndexUtilizationInfo.cs:159 in d3c7963. [](commit_id = d3c796306ac49abff542a56d7e9d4dee8b98427b, deletion_comment = False)

2022-09-22 21:34 UTC, sboshra commented
>             }

Can this be removed?

---
Refers to: Microsoft.Azure.Cosmos/src/Query/Core/Metrics/IndexUtilizationInfo.cs:196 in d3c7963. [](commit_id = d3c796306ac49abff542a56d7e9d4dee8b98427b, deletion_comment = False)

2022-09-22 21:38 UTC, sboshra commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/IndexMetricsParserBaselineTest.cs
> +     **/
//

2022-09-22 21:47 UTC, sboshra submitted a review, later dismissed
:shipit:

2022-09-28 17:29 UTC, leminh98 commented
>         }

we will repurpose this to the top level parsing function to move the logic for deciding whether we deserialize base64 outside of response message


---
In reply to: [1255571554](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3418#issuecomment-1255571554) [](http://example.com/codeflow?ancestors=1255571554,1255571554)

---
Refers to: Microsoft.Azure.Cosmos/src/Query/Core/Metrics/IndexUtilizationInfo.cs:159 in d3c7963. [](commit_id = d3c796306ac49abff542a56d7e9d4dee8b98427b, deletion_comment = False)

2022-09-28 17:30 UTC, leminh98 commented on Microsoft.Azure.Cosmos/src/Query/Core/Metrics/IndexUtilizationInfo.cs
> +            catch
we are only going to catch JsonException

2022-09-28 17:52 UTC, leminh98 commented on Microsoft.Azure.Cosmos/src/Query/Core/Metrics/IndexUtilizationInfo.cs
>              {
the deserializer already ignore so we just going to remove the null checks

2022-09-28 17:54 UTC, leminh98 commented on Microsoft.Azure.Cosmos/src/Query/Core/Metrics/IndexUtilizationInfo.cs
>              this.UtilizedSingleIndexes = utilizedSingleIndexesCopy;
Neat. Converted

2022-09-28 18:00 UTC, leminh98 commented
>             }

This is currently used in the QueryMetrics, which is a pending new work item. I will handle removing this (if necessary) in the PR for that work item

---
In reply to: [1255578020](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3418#issuecomment-1255578020) [](http://example.com/codeflow?ancestors=1255578020,1255578020)

---
Refers to: Microsoft.Azure.Cosmos/src/Query/Core/Metrics/IndexUtilizationInfo.cs:196 in d3c7963. [](commit_id = d3c796306ac49abff542a56d7e9d4dee8b98427b, deletion_comment = False)

2022-09-29 17:14 UTC, ealsur approved these changes

2022-09-29 17:14 UTC, merged