IGNORE ME
Azure/azure-cosmos-dotnet-v3 pull request #3455
Opened 2022-09-12 21:30 UTC by NaluTripician

# Pull Request Template

## Description

Ignore this pr.

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #IssueNumber

2022-09-12 21:41 UTC, imanvt requested changes

2022-09-12 21:41 UTC, imanvt commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        private string applicationName;
nit: move this up to where the rest of the private variables are declared.

2022-09-12 21:41 UTC, imanvt commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +                HttpClient httpClient = new HttpClient();
client is not needed

2022-09-12 21:41 UTC, imanvt commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +                    using System.Net.Http.Headers.HttpHeaderParser.ParseValue(value);
add at top of file:
`using System.Net.Http.Headers.HttpHeaderParser; `
then here, just do `ParseValue(value)`

2022-09-12 21:41 UTC, imanvt commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +                catch (FormatException formatException)
As mentioned, seems like it would be better to wrap this FormatException in a BadRequestException and perhaps add a new substatus code.

2022-09-12 21:41 UTC, imanvt commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTests.cs
> +        public void InvalidApplicationNameCatchTest()
1. Add Asserts so the test fails without the changes, and passes with the changes.
2. WriteLines are fine for intermediate testing, but make sure to remove them before publishing PR.

2022-09-13 15:16 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +                    ApplicationNameException e = new ApplicationNameException(value);//new exception i was thinking of making
Just throw an ArgumentException with the text explaining the issue and including the value, don't add a new type.

2022-09-13 15:17 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +                HttpClient httpClient = new HttpClient();
You are not using this HttpClient in the below code, you can remove it.

2022-09-13 15:17 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        private string applicationName;
Please move the private declaration up top with any other private declarations

2022-09-13 16:06 UTC, imanvt commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +                catch (FormatException formatException)
Yes, you are right, an ArgumentException would be better. I originally had this idea for if the validation was done prior to the network request instead of in the set method and forgot that it is not relevant here. Thanks

2022-09-13 19:38 UTC, NaluTripician commented
I also want to note that like @ealsur mentioned in the issue the actual validation is not being done by the SDK therefore we cannot use the ` HttpHeaderParser.ParseValue` method to check to see if the value will 100% work.  When an `ApplicaitonName` is added, the final parsing is on not just the `ApplicaitonName` but additional text added by the `HttpClient`. For instance, if our application name is `<Run>d__9` like the user had in their issue, the actual text the parser checks is `6.0.0-rc.2.21480.5|N|<Run>d__9`. Although we are not checking the entirety of what the `HttpHeaderParser` does, I imagine that checking for these illegal characters will provide a fix for most if not all similar problems.

2022-09-13 21:14 UTC, ealsur commented
@NaluTripician The source of the problem is the HttpHeader failure, why did we revert that in place of the individual character validation? What is the benefit? Are there any characters that could still make the HttpHeader fail?

2022-09-14 14:21 UTC, NaluTripician commented
> @NaluTripician The source of the problem is the HttpHeader failure, why did we revert that in place of the individual character validation? What is the benefit? Are there any characters that could still make the HttpHeader fail?

The previous function I was using was using in the HttpHeader class was not working however I have found the correct one and updated the code to use that.

2022-09-14 14:26 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +                    throw new ArgumentException("Application Name " + fme.Message.Substring(20));
Why Substring 20 (I assume you want to skip the 20 characters of a constant/prefix?) - if so, using that constant.Length instead of 20 might be better. Or at least explain why you want to skip the first 20 chars in a comment?

2022-09-14 14:28 UTC, FabianMeiswinkel requested changes
Substring(20) seems artificial on initial glance - needs some explanation or changes to the code to make it easier to understand.

2022-09-14 15:32 UTC, imanvt commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +                    throw new ArgumentException("Application Name " + fme.Message.Substring(20));
Would it be better to use this constructor and wrap the Format exception instead? 
`public ArgumentException (string? message, Exception? innerException)`
https://docs.microsoft.com/en-us/dotnet/api/system.argumentexception.-ctor?view=net-6.0#system-argumentexception-ctor(system-string-system-exception)

2022-09-14 16:36 UTC, NaluTripician commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +                    throw new ArgumentException("Application Name " + fme.Message.Substring(20));
Changed to wrap the Format Exception

2022-09-14 16:39 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +                    NameValueHeaderValue nvhv = NameValueHeaderValue.Parse(value);
nit:

```suggestion
                    NameValueHeaderValue.Parse(value);
```

The `nvhv` variable is not used

2022-09-14 16:41 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTests.cs
> +        public void InvalidApplicationNameCatchTest()
Please move this test to the unit test project: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/CONTRIBUTING.md#tests

You are not performing any operations, but doing validations on the `CosmosClientOptions`. The test could simply create the `CosmosClientOptions` and call the `ApplicationName` setter.

There is a test file for CosmosClientOptions tests: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs

2022-09-14 16:41 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/PassThroughQueryBaselineTests.NegativePassThroughOutput.xml
> +      <Description>Null Partition Key Value</Description>
These changes are weird, how did they come to be?

2022-09-14 16:45 UTC, NaluTripician commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/PassThroughQueryBaselineTests.NegativePassThroughOutput.xml
> +      <Description>Null Partition Key Value</Description>
One of the tests that was failing was saying to un the UpdateContracts.ps1 script, I did that and I guess those were some of the changes it made.

2022-09-14 17:51 UTC, FabianMeiswinkel submitted a review, later dismissed
LGTM

2022-09-14 17:59 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTests.cs
> +    using System.Data.Common;
Undo the changes in this file please

2022-09-14 17:59 UTC, imanvt commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +                    throw new ArgumentException("Application Name " + fme.Message.Substring(20));
Exactly my thoughts, thanks for confirming Fabian.

2022-09-14 18:00 UTC, ealsur submitted a review, later dismissed
Thanks! Just one small comment, please mark the PR ready for review

2022-09-14 18:08 UTC, imanvt submitted a review, later dismissed

2022-09-14 18:51 UTC, ealsur submitted a review, later dismissed

2022-09-16 20:47 UTC, imanvt commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +                    HttpRequestMessage dummyMessage = new HttpRequestMessage(HttpMethod.Head, "https://microsoft.com");
might be better to just test against localhost instead?

2022-09-16 20:50 UTC, imanvt commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +                    dummyMessage.Headers.Add("User-Agent", value);
Use this constant instead of the hardcoded string "User-Agent"
`HttpConstants.HttpHeaders.UserAgent`

2022-09-16 21:20 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +                    HttpRequestMessage dummyMessage = new HttpRequestMessage(HttpMethod.Head, "https://microsoft.com");
You can also try with the empty constructor? https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httprequestmessage.-ctor?view=net-6.0#system-net-http-httprequestmessage-ctor

```suggestion
                    HttpRequestMessage dummyMessage = new HttpRequestMessage();
```

2022-09-19 15:37 UTC, merged