Documentation: Update Database.ReadAsync description
Azure/azure-cosmos-dotnet-v3 pull request #3457
Opened 2022-09-13 22:15 UTC by SaurabhSharma-MSFT

# Pull Request Template

## Description

Documentation: Update Database.ReadAsync description.
Fixes [30503](https://github.com/Azure/azure-sdk-for-net/issues/30503)

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #IssueNumber

2022-09-14 14:08 UTC, ealsur requested changes

2022-09-14 14:08 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs
> +        /// However, there is an implicit conversion from DatabaseResponse to DatabaseProperties
Why is this note needed? All `XXXXXProperties` across the SDK have implicit conversions from the `XXXXXResponse`, the code of the `XXXXXResponse` states it so.

For example: https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.databaseresponse?view=azure-dotnet#operators

2022-09-27 00:18 UTC, SaurabhSharma-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs
> +        /// However, there is an implicit conversion from DatabaseResponse to DatabaseProperties
Makes sense.  Updated the file as per your recommendations.

2022-09-27 11:14 UTC, FabianMeiswinkel submitted a review, later dismissed
Thx

2022-09-29 21:22 UTC, ealsur approved these changes

2022-09-29 21:23 UTC, ealsur requested changes
remarks is not being correctly escaped

2022-09-29 21:23 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs
> +        <remarks>
Missing the `///`
```suggestion
///        <remarks>
```

2022-09-30 22:22 UTC, ealsur approved these changes

2022-09-30 22:22 UTC, ealsur commented
/azp run

2022-09-30 22:48 UTC, ealsur commented
/azp run

2022-09-30 23:46 UTC, ealsur approved these changes

2022-11-08 14:52 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Linq/CosmosLinqExtensions.cs
> +        /// This extension method gets the StreamIterator from LINQ IQueryable to execute query asynchronously.
Can we undo these changes to this file? `StreamIterator` is not a used term. Let's just do the `Database.cs` file changes so we can merge it without extra signoffs?

2022-12-12 11:48 UTC, ealsur approved these changes

2022-12-12 11:48 UTC, ealsur commented
/azp run

2023-02-21 15:55 UTC, ealsur commented
/azp run

2023-03-01 03:31 UTC, kirankumarkolli approved these changes

2023-03-01 03:31 UTC, merged