ClientRetryPolicy: Fixes behavior to handling of 503 HTTP errors
Azure/azure-cosmos-dotnet-v3 pull request #3479
Opened 2022-09-29 20:02 UTC by NaluTripician

# Pull Request Template

## Description

https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3008 introduced a regression on the cross-region handling for 503s.

This PR added different substatus codes for 503s to identify different scenarios (was the 503 from client side connectivity issues, did the 503 came from the service, was it due to quorum loss, etc) which gives actionable details to components and consumers of these 503s.

But the `ClientRetryPolicy` was not adjusted to reflect this behavior with the new combination of substatus codes, the code is still checking for substatus 0. Changed the behavior to handle the new 503 status codes allong with tests to avoid future regressions.

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)

## Closing issues

To automatically close an issue: closes #3478

2022-09-29 20:14 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ClientRetryPolicyTests.cs
> +            SubStatusCodes sdkGenerated = SubStatusCodes.TransportGenerated503;
nit: Can we use [DataTestMethod] and define a list of test cases for different substatus codes?

2022-09-29 20:15 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ClientRetryPolicyTests.cs
> +        public void Http503SubStatusHandelingTests()
Can you please add a description/ `<summary>` for this test covering what it does, expectations etc.

2022-09-29 20:16 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ClientRetryPolicyTests.cs
> +            SubStatusCodes sdkGenerated = SubStatusCodes.TransportGenerated503;
Example: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/11b774459a894657dcca8cbf89b945b42e008a86/Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/FeedProcessorCoreTests.cs#L123-L126

Then you have a single test with all the substatuscodes combinations and less code

2022-09-29 20:17 UTC, ealsur requested changes
Nice work, let's please add the extra tests

2022-09-29 20:18 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ClientRetryPolicyTests.cs
> +            SubStatusCodes sdkGenerated = SubStatusCodes.TransportGenerated503;
```
[DataRow(SubStatusCodes.TransportGenerated503)]
...
... other substatus for 503
...
[DataRow(SubStatusCodes.Unknown)]
[DataTestMethod]
public void Http503SubStatusHandlingTests(SubstatusCodes substatus)
```

2022-09-29 21:06 UTC, imanvt commented on Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs
> +        private static bool IsRetriableServiceUnavailable(SubStatusCodes? subStatusCode)
nit: I think it's best to be concise here.

```
return subStatusCode == SubStatusCodes.Unknown || 
(subStatusCode.HasValue && subStatusCode.Value.IsSDKGeneratedSubStatus()));
           

```

2022-09-29 21:07 UTC, imanvt commented
Great work with the quick turnaround on the fix for the regression. Left one minor comment

2022-09-30 14:54 UTC, ealsur approved these changes
Thanks for adding the tests, great work!

2022-09-30 14:54 UTC, merged