Client Telemetry: Adds functionality to collect telemetry for collection cache
Azure/azure-cosmos-dotnet-v3 pull request #3484
Opened 2022-09-30 19:47 UTC by sourabh1007

## Description

As part of this PR following changes have been made:
1. Added _"Collection Read information"_ from `ClientCollectionCache`. Client Telemetry Payload will have this section. Backend service already support this.
![image](https://user-images.githubusercontent.com/6362382/195128401-c622c64c-9787-4332-81ac-60a8c06b9e2e.png)
2. Change type of SubStatusCode from `string` to `integer`
3. Refactored Code to initializing/Running Client Telemetry Job during `DocumentClient` initialization instead of `ClientContextCore`
4. Moved all the Client Telemetry Models into a new folder i.e. Models

## Type of change
- [] New feature (non-breaking change which adds functionality)

2022-10-10 13:55 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +        internal ClientTelemetry clientTelemetry { get; set; }
Let's try to avoid adding more things to the DocumentClient, remember that the eventual goal is to remove it, why cannot it be on the ClientContext?

2022-10-10 13:56 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +        private IReadOnlyList<string> applicationPreferredRegions;
Where are these new private variables used?

2022-10-10 14:35 UTC, ealsur requested changes
Left some comments regarding the new files. How do we envision (if we are planning to) cover the other caches? Would other caches require more refactoring (moving the Telemetry somewhere else?) or is the current place correct to cover the other caches?

2022-10-10 14:35 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +        internal ClientTelemetry clientTelemetry { get; set; }
Could you explain why you needed to put it on DocumentClient? Is the Context not available to the caches? Why is this need to be `internal`?

2022-10-10 14:35 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Routing/ClientCollectionCache.cs
> +                                if (this.clientTelemetry != null)
Just a thought: Any way to avoid the null checks? Is there a NoOp Client Telemetry implementation?

2022-10-10 14:35 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +            Compute vmInformation = VmMetadataApiHandler.GetMachineInfo();
This can be not yet available when it is read here? How is that accounted for on the telemetry?

2022-10-10 14:35 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +            string regionsContacted = ClientTelemetryHelper.GetContactedRegions(new List<(string regionName, Uri uri)>(regionsContactedList));
Why do you need to create a new list off the HashSet? Both HashSet and List are `System.Collections.Generic.IReadOnlyCollection`, can you use that on `ClientTelemetryHelper.GetContactedRegions`?

2022-10-10 14:35 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +        internal void Collect(string cacheRefreshSource,
nit: Would the name be better as reflecting this method is for Caches?

2022-10-10 14:35 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +                            string databaseId = null,
When would you have a containerId without a databaseId?

2022-10-10 14:35 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +            if (this.cancellationTokenSource != null &&
When is the tokensource null? It is created in the constructor, right?

2022-10-10 14:35 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryHelper.cs
> +            DefaultTrace.TraceInformation("Aggregating CacheRefreshInfo information to list started");
Should this be a Verbose?

2022-10-10 14:35 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryHelper.cs
> +                payloadForLatency.MetricInfo = new MetricInfo(ClientTelemetryOptions.RequestLatencyName, ClientTelemetryOptions.RequestLatencyUnit);
Is this modifying the object in the Dictionary? Is it expected?

2022-10-10 14:35 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryHelper.cs
> +        internal static string GetContactedRegions(IReadOnlyList<(string regionName, Uri uri)> regionList)
Would `System.Collections.Generic.IReadOnlyCollection` achieve the same? Or any of the base interfaces?

2022-10-10 14:35 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/Models/CacheRefreshInfo.cs
> +            long? responseSizeInBytes,
ideally optional parameters are last

2022-10-10 14:35 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/Models/ClientTelemetryProperties.cs
> +        internal List<CacheRefreshInfo> CacheRefreshInfo { get; set; }
Why is the access modifier change needed?

2022-10-10 14:35 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/Models/OperationInfo.cs
> +        internal string RegionsContacted { get; set; }
Why the internal setter? Can't the CacheRefreshInfo simply call the base() constructor?

2022-10-10 14:35 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/Models/CacheRefreshInfo.cs
> +            bool isequal = obj is CacheRefreshInfo payload &&
Why not use `base.Equals()` and then just add the new condition based on the property this class has (CacheRefreshSource)?

2022-10-10 14:35 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/Models/CacheRefreshInfo.cs
> +            hash = (hash * 7) ^ (this.RegionsContacted == null ? 0 : this.RegionsContacted.GetHashCode());
Use `base.GetHashCode` and then add the hash of the properties in this class?

2022-10-10 14:35 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/Models/CacheRefreshInfo.cs
> +        {
call `base` here with the parameters instead of using the setters.

2022-10-10 14:56 UTC, FabianMeiswinkel requested changes
Few comments:

- I really think this PR should be split-up - some of the refactoring (3 out of the four included high-level changes) could be as separate PRs instead - making it easier to review and make sense whether the refactoring is needed/right.

- We have discussed whether to include cache refresh as first-class telemetry before. I still don't think this is the right move (metadata requests being included whether cache or not are sufficient IMO). - but what is definitely indisputable is that we need to fix the client telemetry to make it useful first (missing service endpoint and/or PKId + replicaId) - which right now is the P0 work item.

2022-10-10 16:10 UTC, sourabh1007 commented
> Few comments:
> 
> * I really think this PR should be split-up - some of the refactoring (3 out of the four included high-level changes) could be as separate PRs instead - making it easier to review and make sense whether the refactoring is needed/right.
> * We have discussed whether to include cache refresh as first-class telemetry before. I still don't think this is the right move (metadata requests being included whether cache or not are sufficient IMO). - but what is definitely indisputable is that we need to fix the client telemetry to make it useful first (missing service endpoint and/or PKId + replicaId) - which right now is the P0 work item.

1. I agree I am touching 33 files as part of this PR, but most of them are minor changes such as import changes, added one more argument in `ClientCollectionCache` class (corresponding tests). Still, you feel that it makes sense to split it up, I can do it.
2. Include cache information in client telemetry was always a requirement. So as part of this PR, I picked up `CollectionCache` and later PRs you will see telemetry from other caches (partition key range, location etc.). IMO, we cache only metadata information. We can definitely debate/discuss on what metrics we want to capture exactly. Right now, it is capturing only latency + system usage.
About Replicaid/pkid/service endpoint, I need clarity on this. What information we want to include in client telemetry, I don't want to end up including all backend information and partial information (e.g top 10 replica). It will be an end-to-end change SDK + Service + Kusto.

2022-10-10 19:51 UTC, sourabh1007 commented
> nvision (if we are planning to) cover the other caches? Would other caches require more refactoring (moving the Telemetry somewhere else?) or is the current place correct to cover the other caches

At current place, `CollectionCache` and `PartitionKeyRangeCache` are getting initialized. So, it should be good for these 2 kinds of caches, for other caches we might need to refactor again. 
There is one more reason for refactoring this code, we are initializing all job/task during `DocumentClient `initialization. So, I felt that it is the right place for client telemetry job also.

2022-10-10 19:59 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +        internal ClientTelemetry clientTelemetry { get; set; }
There are 2 reasons for this refactoring:
1. All the jobs/tasks are getting initialized during `DocumentClient `initialization. So, I felt that it is the right place for client telemetry job also.
2. At current place, `CollectionCache` and `PartitionKeyRangeCache` are getting initialized. So, telemetry context will be available at least for these 2 kinds of caches.

2022-10-10 20:03 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Routing/ClientCollectionCache.cs
> +                                if (this.clientTelemetry != null)
It has been handled till now like this and as far as I remember in the initial PR we decided to go with this approach. I have no issue in revisiting it but this is something which we can take as part of some other PR.

2022-10-10 20:22 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +            Compute vmInformation = VmMetadataApiHandler.GetMachineInfo();
Ideally this information should be available immediately as metadata API is hosted inside the machine only.
In `DocumentClient`, it is made sure that Client telemetry job is getting started after metadata call. So chance of availability of this information will increase. I think that's all we can do here. 
If this information is not loaded anyhow then, this information will be null in telemetry record.

2022-10-10 21:56 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +            if (this.cancellationTokenSource != null &&
null check was added for test cases where client telemetry was initialized using default constructor. But I have changed it now, I think it makes sense to initialize cancellation token in default constructor also.

2022-10-10 21:59 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryHelper.cs
> +                payloadForLatency.MetricInfo = new MetricInfo(ClientTelemetryOptions.RequestLatencyName, ClientTelemetryOptions.RequestLatencyUnit);
We don't care if dictionary is modified. Here we are converting Dictionary to List with metrics information.

2022-10-10 22:13 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/Models/CacheRefreshInfo.cs
> +            long? responseSizeInBytes,
this paramaters are not optional only nullable.

2022-10-10 22:13 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/Models/ClientTelemetryProperties.cs
> +        internal List<CacheRefreshInfo> CacheRefreshInfo { get; set; }
for tests.

2022-10-11 16:49 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +            Compute vmInformation = VmMetadataApiHandler.GetMachineInfo();
Got your point. I misunderstood it from some other thing. it makes sense, it can fall into this situation. Fixed it

2022-10-12 21:07 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Routing/ClientCollectionCache.cs
> +                                ClientCollectionCache.GetDatabaseAndCollectionName(collectionLink, out string databaseName, out string collectionName);
Isn't this information avaialble in the `containerProperties`?

2022-10-12 21:14 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +                machineId: VmMetadataApiHandler.GetMachineId());
Wouldn't this have the same problem as the previous iteration of this PR? This is snapshot here, this is created  on the DocumentClient.Initialize, which is right away, no delays. 

If the MachineId is generated only once, what is the issue of calling it on all requests?

2022-10-12 21:14 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +                            string databaseId = null,
The point of this is, the databaseId should not be null

2022-10-12 21:18 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryHelper.cs
> +            if (regionList == null || regionList.Count == 0)
Should this also have the `if (regionList.Count == 1)` optimization?

2022-10-12 21:20 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/Models/ClientTelemetryProperties.cs
> +        internal List<CacheRefreshInfo> CacheRefreshInfo { get; set; }
Can we make the getter internal then?

2022-10-12 21:21 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/Models/ClientTelemetryProperties.cs
> +                this.IsDirectConnectionMode = true;
```suggestion
                this.IsDirectConnectionMode = connectionMode == ConnectionMode.Direct;
```

2022-10-13 14:25 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Telemetry/Models/CacheRefreshInfo.cs
> +            bool isequal = base.Equals(obj) && obj is CacheRefreshInfo payload &&
```suggestion
            return base.Equals(obj) && 
    obj is CacheRefreshInfo payload && 
   String.OrdinalCompare(this.CacheRefreshSource, payload.CacheRefreshSource) == 0;
```

2022-10-13 14:25 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Telemetry/Models/CacheRefreshInfo.cs
> +                        (this.CacheRefreshSource != null && payload.CacheRefreshSource != null &&
Also isequal variable isn't necessary.

2022-10-13 14:31 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +                DefaultTrace.TraceInformation("Client Telemetry Disabled.");
Similar log should be emitted after successful initialization in line 1045

2022-10-13 14:34 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Handler/ClientPipelineBuilder.cs
> +            this.diagnosticsHandler = null;
this isn't necessary - diagnosticsHandler is always null at this point anyway.

2022-10-13 14:44 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Resource/CosmosExceptions/CosmosException.cs
> +            scope.AddAttribute(OpenTelemetryAttributeKeys.Region, ClientTelemetryHelper.GetContactedRegions(exception.Diagnostics.GetContactedRegions()));
```suggestion
            scope.AddAttribute(OpenTelemetryAttributeKeys.Region, ClientTelemetryHelper.GetContactedRegions(exception.Diagnostics?.GetContactedRegions()));
```

2022-10-13 14:44 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Resource/CosmosExceptions/CosmosNullReferenceException.cs
> +            scope.AddAttribute(OpenTelemetryAttributeKeys.Region, ClientTelemetryHelper.GetContactedRegions(exception.Diagnostics.GetContactedRegions()));
```suggestion
            scope.AddAttribute(OpenTelemetryAttributeKeys.Region, ClientTelemetryHelper.GetContactedRegions(exception.Diagnostics?.GetContactedRegions()));
```

2022-10-13 14:45 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Resource/CosmosExceptions/CosmosObjectDisposedException.cs
> +            scope.AddAttribute(OpenTelemetryAttributeKeys.Region, ClientTelemetryHelper.GetContactedRegions(exception.Diagnostics.GetContactedRegions()));
```suggestion
            scope.AddAttribute(OpenTelemetryAttributeKeys.Region, ClientTelemetryHelper.GetContactedRegions(exception.Diagnostics?.GetContactedRegions()));
```

2022-10-13 14:52 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Routing/ClientCollectionCache.cs
> +                                ClientCollectionCache.GetDatabaseAndCollectionName(collectionLink, out string databaseName, out string collectionName);
It doesn't ContainerProperties has no link back to DatabaseId - except for the self-link

2022-10-13 14:54 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +                machineId: VmMetadataApiHandler.GetMachineId());
+1 - I can't say I am against this change - but I also don't understand why it was made. One of the reasons why I would really prefer having PRs for individual changes - like these Mono PRs

2022-10-13 15:01 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Routing/ClientCollectionCache.cs
> +                                ClientCollectionCache.GetDatabaseAndCollectionName(collectionLink, out string databaseName, out string collectionName);
The collection link doesn't have the names either, right? Doesn't it contain the RIDs?

2022-10-13 15:10 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Resource/CosmosExceptions/CosmosException.cs
> +            scope.AddAttribute(OpenTelemetryAttributeKeys.Region, ClientTelemetryHelper.GetContactedRegions(exception.Diagnostics.GetContactedRegions()));
```suggestion
            scope.AddAttribute(OpenTelemetryAttributeKeys.Region, ClientTelemetryHelper.GetContactedRegions(exception.Diagnostics?.GetContactedRegions()));
```

2022-10-13 15:10 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Resource/CosmosExceptions/CosmosNullReferenceException.cs
> +            scope.AddAttribute(OpenTelemetryAttributeKeys.Region, ClientTelemetryHelper.GetContactedRegions(exception.Diagnostics.GetContactedRegions()));
```suggestion
            scope.AddAttribute(OpenTelemetryAttributeKeys.Region, ClientTelemetryHelper.GetContactedRegions(exception.Diagnostics?.GetContactedRegions()));
```

2022-10-13 15:11 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Resource/CosmosExceptions/CosmosObjectDisposedException.cs
> +            scope.AddAttribute(OpenTelemetryAttributeKeys.Region, ClientTelemetryHelper.GetContactedRegions(exception.Diagnostics.GetContactedRegions()));
```suggestion
            scope.AddAttribute(OpenTelemetryAttributeKeys.Region, ClientTelemetryHelper.GetContactedRegions(exception.Diagnostics?.GetContactedRegions()));
```

2022-10-13 15:11 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Resource/CosmosExceptions/CosmosOperationCanceledException.cs
> +            scope.AddAttribute(OpenTelemetryAttributeKeys.Region, ClientTelemetryHelper.GetContactedRegions(exception.Diagnostics.GetContactedRegions()));
```suggestion
            scope.AddAttribute(OpenTelemetryAttributeKeys.Region, ClientTelemetryHelper.GetContactedRegions(exception.Diagnostics?.GetContactedRegions()));
```

2022-10-13 15:14 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Telemetry/Models/OperationInfo.cs
> +        internal OperationInfo()
why would we ever need this ctor?

2022-10-13 15:15 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Benchmarks/RegionContactedInDiagnosticsBenchmark.cs
> +            ClientTelemetryHelper.GetContactedRegions(cosmosDiagnostics.GetContactedRegions());
```suggestion
            ClientTelemetryHelper.GetContactedRegions(cosmosDiagnostics?.GetContactedRegions());
```

2022-10-13 15:16 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Mocks/MockDocumentClient.cs
> +            this.collectionCache = new Mock<ClientCollectionCache>(null, new ServerStoreModel(null), null, null, null);
for humans - not the compiler of course :-)

2022-10-13 15:17 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ClientTelemetryTests.cs
> +            string json = JsonConvert.SerializeObject(new ClientTelemetryProperties("clientId", "", null, ConnectionMode.Direct, null, 10, null), ClientTelemetryOptions.JsonSerializerSettings);
named parameters

2022-10-13 15:17 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs
> +                           clientCollectionCache: new Mock<ClientCollectionCache>(new SessionContainer("testhost"), gatewayStoreModel, null, null, null).Object,
named parameters for null

2022-10-13 15:17 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs
> +                    clientCollectionCache: new Mock<ClientCollectionCache>(new SessionContainer("testhost"), gatewayStoreModel, null, null, null).Object,
dito

2022-10-13 15:17 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs
> +                                clientCollectionCache: new Mock<ClientCollectionCache>(new SessionContainer("testhost"), gatewayStoreModel, null, null, null).Object,
dito

2022-10-13 15:17 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs
> +                                clientCollectionCache: new Mock<ClientCollectionCache>(new SessionContainer("testhost"), gatewayStoreModel, null, null, null).Object,
dito

2022-10-13 15:17 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs
> +                    clientCollectionCache: new Mock<ClientCollectionCache>(new SessionContainer("testhost"), gatewayStoreModel, null, null, null).Object,
dito

2022-10-13 15:18 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs
> +                    clientCollectionCache: new Mock<ClientCollectionCache>(new SessionContainer("testhost"), gatewayStoreModel, null, null, null).Object,
dito

2022-10-13 15:18 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs
> +            Mock<ClientCollectionCache> clientCollectionCache = new Mock<ClientCollectionCache>(new SessionContainer("testhost"), storeModel, null, null, null);
dito

2022-10-13 15:18 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs
> +            Mock<ClientCollectionCache> clientCollectionCache = new Mock<ClientCollectionCache>(new SessionContainer("testhost"), storeModel, null, null, null);
dito

2022-10-13 15:18 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs
> +                    clientCollectionCache: new Mock<ClientCollectionCache>(sessionContainer, gatewayStoreModel, null, null, null).Object,
dito

2022-10-13 15:18 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs
> +                    clientCollectionCache: new Mock<ClientCollectionCache>(sessionContainer, gatewayStoreModel, null, null, null).Object,
dito

2022-10-13 15:18 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs
> +            ClientCollectionCache clientCollectionCache = new Mock<ClientCollectionCache>(new SessionContainer("testhost"), storeModel, null, null, null).Object;
one more

2022-10-13 15:19 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Utils/MockDocumentClient.cs
> +            this.collectionCache = new Mock<ClientCollectionCache>(new SessionContainer("testhost"), new ServerStoreModel(null), null, null, null);
named paramaters please

2022-10-13 15:19 UTC, FabianMeiswinkel requested changes
Few comments left - design looks ok

2022-10-13 16:29 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Handler/ClientPipelineBuilder.cs
>                  this.telemetryHandler = new TelemetryHandler(telemetry);
telemetry object will be null for internal as telemetry job/task won't even run for INTERNAL

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/e4e4a296089be10f7864ec8a83657ae31dfc4be5/Microsoft.Azure.Cosmos/src/DocumentClient.cs#L947

2022-10-13 16:37 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +                            string databaseId = null,
Sorry, I didn't remove this null assignment...but passed databaseId.

2022-10-13 16:45 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/Models/ClientTelemetryProperties.cs
> +        internal List<CacheRefreshInfo> CacheRefreshInfo { get; set; }
I just realized in test and even in code it is getting used. i.e https://github.com/Azure/azure-cosmos-dotnet-v3/blob/e4e4a296089be10f7864ec8a83657ae31dfc4be5/Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs#L192

2022-10-13 17:09 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Routing/ClientCollectionCache.cs
> +                                ClientCollectionCache.GetDatabaseAndCollectionName(collectionLink, out string databaseName, out string collectionName);
![image](https://user-images.githubusercontent.com/6362382/195660582-cd593b33-161d-406f-ba12-236e43354458.png)
![image](https://user-images.githubusercontent.com/6362382/195661083-231a7cac-9c83-4db6-bf44-ca41f5354e64.png)

`SelfLink` has rids but `collectionLink` has `dbName/containerName`

2022-10-13 18:15 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryHelper.cs
> +            if (regionList == null || regionList.Count == 0)
I removed that because I couldn't find any non-LINQ way to do if. Anyway, I have put a LINQ way... not sure if it is going to optimize anything.

2022-10-13 19:07 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Benchmarks/RegionContactedInDiagnosticsBenchmark.cs
> +            ClientTelemetryHelper.GetContactedRegions(cosmosDiagnostics.GetContactedRegions());
we already have a null check above.

2022-10-13 19:24 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Mocks/MockDocumentClient.cs
> +            this.collectionCache = new Mock<ClientCollectionCache>(null, new ServerStoreModel(null), null, null, null);
It is just a mock class in our test, I don't think humans also ever try see this code, until unless something is broken in their own code.
Since its a mock class initialization, I don't think we can pass named parameter.

2022-10-13 19:29 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs
> +                           clientCollectionCache: new Mock<ClientCollectionCache>(new SessionContainer("testhost"), gatewayStoreModel, null, null, null).Object,
Since its a mock class initialization, I don't think we can pass named parameter.

2022-10-13 19:30 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs
> +                    clientCollectionCache: new Mock<ClientCollectionCache>(new SessionContainer("testhost"), gatewayStoreModel, null, null, null).Object,
Since its a mock class initialization, I don't think we can pass named parameter.

2022-10-13 19:30 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs
> +                                clientCollectionCache: new Mock<ClientCollectionCache>(new SessionContainer("testhost"), gatewayStoreModel, null, null, null).Object,
Since its a mock class initialization, I don't think we can pass named parameter.

2022-10-13 19:30 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs
> +                    clientCollectionCache: new Mock<ClientCollectionCache>(new SessionContainer("testhost"), gatewayStoreModel, null, null, null).Object,
Since its a mock class initialization, I don't think we can pass named parameter.

2022-10-13 19:31 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs
> +            Mock<ClientCollectionCache> clientCollectionCache = new Mock<ClientCollectionCache>(new SessionContainer("testhost"), storeModel, null, null, null);
Since its a mock class initialization, I don't think we can pass named parameter.

2022-10-13 19:31 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs
> +            Mock<ClientCollectionCache> clientCollectionCache = new Mock<ClientCollectionCache>(new SessionContainer("testhost"), storeModel, null, null, null);
Since its a mock class initialization, I don't think we can pass named parameter.

2022-10-13 19:31 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs
> +                    clientCollectionCache: new Mock<ClientCollectionCache>(sessionContainer, gatewayStoreModel, null, null, null).Object,
Since its a mock class initialization, I don't think we can pass named parameter.

2022-10-13 19:31 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs
> +                    clientCollectionCache: new Mock<ClientCollectionCache>(sessionContainer, gatewayStoreModel, null, null, null).Object,
Since its a mock class initialization, I don't think we can pass named parameter.

2022-10-13 19:31 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs
> +            ClientCollectionCache clientCollectionCache = new Mock<ClientCollectionCache>(new SessionContainer("testhost"), storeModel, null, null, null).Object;
Since its a mock class initialization, I don't think we can pass named parameter.

2022-10-13 19:31 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Utils/MockDocumentClient.cs
> +            this.collectionCache = new Mock<ClientCollectionCache>(new SessionContainer("testhost"), new ServerStoreModel(null), null, null, null);
Since its a mock class initialization, I don't think we can pass named parameter.

2022-10-13 19:31 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs
> +                                clientCollectionCache: new Mock<ClientCollectionCache>(new SessionContainer("testhost"), gatewayStoreModel, null, null, null).Object,
Since its a mock class initialization, I don't think we can pass named parameter.

2022-10-13 20:22 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Handler/ClientPipelineBuilder.cs
> +            this.diagnosticsHandler = null;
![image](https://user-images.githubusercontent.com/6362382/195702718-1254914e-b8a3-4318-bd8e-a1a3c5cca735.png)

Thats why, this null assignment is required. It was always like this only.

2022-10-13 22:03 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Routing/ClientCollectionCache.cs
> +                                ClientCollectionCache.GetDatabaseAndCollectionName(collectionLink, out string databaseName, out string collectionName);
Move this in the if that checks for client telemetry, parsing this when client telemetry is disabled is cost that is useless

2022-10-13 22:05 UTC, ealsur reviewed
Only 1 nit, nice improvement throughout the iterations

2022-10-14 12:54 UTC, FabianMeiswinkel approved these changes
LGTM now - thanks!

2022-10-17 14:20 UTC, ealsur approved these changes

2022-10-17 14:20 UTC, merged