ReadThroughputAsync: Fixes behavior to Database.ReadThroughputAsync overload for databases without provisioned throughput
Azure/azure-cosmos-dotnet-v3 pull request #3496
Opened 2022-10-10 14:48 UTC by NaluTripician

# Pull Request Template

## Description

The `database.ReadThroughputAsync` overload that takes `RequestOptions` a `CosmosException` when the database doesn't have throughput provisioned. A `ThroughputResponse` with null properties is expected.

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #2959

2022-10-10 19:06 UTC, NaluTripician commented on Microsoft.Azure.Cosmos/src/Resource/Offer/CosmosOffers.cs
> +                    return new ThroughputResponse(HttpStatusCode.NoContent, null, null, null, null);
Here in the `ThroughputResponse` with null properties do we need to do anything with the `requestCharge` output of `GetOfferV2Async`? From my testing it looks like when the `OfferV2` is null the `requestCharge` will be 0 but I wanted to make sure that this is the case.

2022-10-10 20:13 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Offer/CosmosOffers.cs
> +            if (requestOptions == null)
Why is this new logic related to the user passing or not passing request Options?

2022-10-10 21:27 UTC, ealsur requested changes
Let's think about the potential options that would not generate breaking changes

2022-10-19 13:46 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs
> +        /// <exception>https://aka.ms/cosmosdb-dot-net-exceptions</exception>
```suggestion
        /// <exception>https://aka.ms/cosmosdb-dot-net-exceptions#stream-api</exception>
```

2022-10-19 13:51 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Offer/CosmosOffers.cs
> +            ResponseMessage responseMessage = await this.ClientContext.ProcessResourceOperationStreamAsync(
There is certainly an awful lot of duplication in this file. This method has almost the same code as ReadThroughputAsync.

Is there any way to start reusing code? 

For example:

* Can `ReadThroughputAsync` call `ReadThroughputStreamAsync` and just convert the ResponseMessage using `return this.ClientContext.ResponseFactory.CreateThroughputResponse(responseMessage);`?
* Can `GetThroughputResponseAsync` just return the ResponseMessage so `ReadThroughputStreamAsync` can use it?

Do you think we could clean it up a bit to start reusing code, so in the future we don't need to modify a lot of methods if a change is needed.

2022-10-19 13:52 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosThroughputTests.cs
> +    using System.Security.Cryptography.X509Certificates;
Why is this using needed?

2022-10-19 13:52 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosThroughputTests.cs
> +            Assert.AreEqual(HttpStatusCode.BadRequest, responseMessage1.StatusCode);
Doesn't it return a 404 / NotFound?

2022-10-19 17:19 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs
> +                return new ResponseMessage(
Don't create a new response message, you can simply return the one from line 101, right?

2022-10-19 17:21 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Offer/CosmosOffers.cs
> +                    errorMessage: $"Throughput is not configured for {targetRID}");
Why do we need to fabricate this message? Can't we just return the result of `ProcessResourceOperationStream`?

2022-10-19 18:26 UTC, NaluTripician commented on Microsoft.Azure.Cosmos/src/Resource/Offer/CosmosOffers.cs
> +                    errorMessage: $"Throughput is not configured for {targetRID}");
The problem with using the result of ProcessResourceOperationStream is the `resourceUri` field. If there is provisioned throughput the `resourceUri` will be made from the `OfferV2` and will be something like: `offers/HJNA/`. I could still call `ProcessResourceOperationStream` and have the `resourceUri` be empty. This would change the error message to `The value '' specified  for query '$resolveFor' is invalid.` rather than `Throughput is not configured for {targetRID}`. Any thoughts?

2022-10-20 19:20 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs
> +                return new ResponseMessage(
Here its not 1-1 mapping with BE. 
Non-success if for the data not for the offer. Won't it be confusing to CX?

2022-10-20 19:21 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseInlineCore.cs
> +        }
nit: new line after closing braces

2022-10-20 19:37 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Offer/CosmosOffers.cs
> +                    errorMessage: $"Throughput is not configured for {targetRID}");
Assumed that today's flow do return 404 as exception. 
So, it's still 404 but with "The value '' **specified for query '$resolveFor' is invalid**" exception message.

2022-10-20 19:38 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Offer/CosmosOffers.cs
> +                    errorMessage: $"Throughput is not configured for {targetRID}");
In general manufacturing response stream is best to avoid.

2022-10-21 17:38 UTC, ealsur approved these changes
Please update the PR title reflecting what the PR now has

2022-10-24 17:09 UTC, merged

2022-10-25 02:20 UTC, abhijitpai commented
@NaluTripician @ealsur would have been good to remove the following remark from that API documentation to reduce confusion along with adding the exception details:

 /// <remarks>
 /// Null value indicates a database with no throughput provisioned.
 /// </remarks>

2022-10-25 14:10 UTC, ealsur commented
@abhijitpai Missed it, thanks!