[Internal] Client Telemetry: Refactor code to remove hashing from VM Id
Azure/azure-cosmos-dotnet-v3 pull request #3512
Opened 2022-10-21 18:54 UTC by sourabh1007

## Description

Before this PR, we were hashing VM ID due to security concern but in recent talk with security team it is decided that VM ID is not PII hence can be store as it is without Hashing.

## Type of change
- [] Bug fix (non-breaking change which fixes an issue)

2022-10-21 20:22 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/Models/Compute.cs
> +            this.VMId = $"{VmMetadataApiHandler.VmIdPrefix}{vMId}";
Is someone using `HashingExtension.ComputeHash` ?

2022-10-21 20:34 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/Models/Compute.cs
> +            this.VMId = $"{VmMetadataApiHandler.VmIdPrefix}{vMId}";
yes..hashing machine name and processid using this.

2022-10-23 04:09 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/VmMetadataApiHandler.cs
> +        internal const string VmIdPrefix = "vmId:";
Approving this PR to unblock. 
But let's go-over the plan forward on how to guard contractual guarantees/divergences.

2022-10-23 04:09 UTC, kirankumarkolli approved these changes

2022-10-23 04:16 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/VmMetadataApiHandler.cs
>          internal const string HashedMachineNamePrefix = "hashedMachineName:";
Who is the consumer for HashedMachineNamePrefix ?

2022-10-23 04:23 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/VmMetadataApiHandler.cs
> +        internal const string VmIdPrefix = "vmId:";
Also checking service code some variables do use hashed in naming, please update them accordingly.

2022-10-23 04:23 UTC, kirankumarkolli requested changes
Please check comments

2022-10-23 17:38 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/VmMetadataApiHandler.cs
> +        internal const string VmIdPrefix = "vmId:";
> Can you please refractor code to make it consistent across? (Both ClientTelemetry and diagnostics)

This will be separate PR and need to find out the right way to do it because these variables are used for column name and as of now, I have taken care of it without changing these variables.

2022-10-23 17:49 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/VmMetadataApiHandler.cs
> +        internal const string VmIdPrefix = "vmId:";
> hashedid is used ex:

Here Logic to get the machine Id is:
1. if Azure VM, Check for VM Id since it is not PII, it will not be hashed.
2. If anyhow it is not able to fetch VM id (e.g., non-azure VM), then it will try to get Machine Name, as it is a PII so it will be hashed automatically.
3. If for any reason it is not able to fetch Machine Name also then, it will generate a UUID and return that value.

and there is a prefix added to represent the same (vmId, hashedMachineName, Uuid). 

So, the Point is: Here contract is that you can request for a MachineId, now this function will decide on the basis of above criteria that what it should be, and prefix will tell, what is it.

I couldn't understand inconsistency you are talking about here. Can you please explain more on this?

2022-10-23 17:50 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/VmMetadataApiHandler.cs
>          internal const string HashedMachineNamePrefix = "hashedMachineName:";
I think above comment should answer your question.

2022-10-24 13:03 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/VmMetadataApiHandler.cs
> +        internal const string VmIdPrefix = "vmId:";
You are gith. I mis-understood the code. 
SDK code is good to go.

2022-10-24 13:03 UTC, kirankumarkolli approved these changes

2022-10-24 13:04 UTC, kirankumarkolli approved these changes

2022-10-24 13:04 UTC, merged