Open Telemetry Support and AI integration
Azure/azure-cosmos-dotnet-v3 pull request #3598
Opened 2022-12-07 17:20 UTC by sourabh1007

## Description

## Type of change
- [] New feature (non-breaking change which adds functionality)

2022-12-09 01:51 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +            bool DisableDistributedTracing { get; set; }
Naming wise, other option is EnableDistributedTracing and default to TRUE. 
Both are logically correct, IMO Enable sounds better :-)

2022-12-09 01:54 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/RequestOptions/RequestOptions.cs
> +#if PREVIEW
Is this also recommended by central team? Or our choice?
We can late bind this API if we are still unsure of customization scenarios.

2022-12-09 01:56 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/DistributedTracingOptions.cs
> +        public TimeSpan? LatencyThresholdForRequestDiagnosticEventTrace { get; set; }
LatencyThreshold was used as suffix before, is moving it to Prefix intentional?

2022-12-09 02:21 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/DistributedTracingOptions.cs
> +        public TimeSpan? LatencyThresholdForRequestDiagnosticEventTrace { get; set; }
Yes, trying to make it more align to what it is doing. This Latency threshold value is for "Request Diagnostics Trace Event". Previous name can be easily confused with, if we are doing filtering at activity level.

2022-12-09 02:22 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/RequestOptions/RequestOptions.cs
> +#if PREVIEW
I don't think, Central team has any recommendation on this. @lmolkova can you correct me here?

2022-12-09 02:25 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +            bool DisableDistributedTracing { get; set; }
I am ok with anything here. @lmolkova can you please confirm if central SDK has any recommendation on this flag?

2022-12-09 17:10 UTC, lmolkova commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/DistributedTracingOptions.cs
> +        public TimeSpan? LatencyThresholdForRequestDiagnosticEventTrace { get; set; }
```suggestion
        public TimeSpan? LatencyThresholdForDiagnosticEvent { get; set; }
```

or 

```suggestion
        public TimeSpan? LatencyThresholdForRequestDiagnosticEvent { get; set; }
```

2022-12-09 17:32 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/RequestOptions/RequestOptions.cs
> +#if PREVIEW
JFYI: Right now, it just has one configuration using which customer can control generation of event with request diagnostic string and yes if required in future we can add more such configuration like you suggested above.

2022-12-09 18:28 UTC, lmolkova commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +            bool DisableDistributedTracing { get; set; }
We call it [`IsDistributedTracingEnabled`](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/DiagnosticsOptions.cs#L74) and it defaults to true. Would be nice to have consistent naming.

2022-12-12 19:42 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        = true;
What's the performance impact on team which upgrade preview upgrade with default ON?

2022-12-12 19:43 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
> +            this.clientOptions.IsDistributedTracingEnabled = false;
Conditional on preview?

2022-12-13 03:24 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        = true;
In case of Open telemetry/AI Integration support, perf is totally dependent on the listener. As a source, there will be no perf impact at all. Still, I am expecting a new customer to go through the complete software lifecycle, in order to make sure if this new feature is not impacting them in any way.

2022-12-13 12:23 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        /// This flag is there to disable it from source.
nit: Comment is redundant, the property is called IsXXXEnabled and it's a `bool`, disabled (false) or enabled (true) is implied. What needs to be properly communicated is what is the default.

2022-12-13 12:25 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
> +        /// Disables Operation level activity generation even if listener is subscribed to Azure.Cosmos.operation source and clears <see cref="DistributedTracingOptions"/> configured for this client
For consistency with the other property, source name should be the same?

```suggestion
        /// Disables Operation level activity generation even if listener is subscribed to "Azure.Cosmos.Operation" source.
```

Also, why do we mention that it clears the options? This is the client builder, how does the user set the DistributedTracingOptions and call Disable after?

2022-12-13 12:26 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
> +        /// <exception cref="ArgumentException">If Distributed Tracing is disabled</exception>
This exception comment is not correct, is it? Unless it is possible for the user to Disable and set the options too after?

2022-12-13 12:26 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
> +        internal CosmosClientBuilder EnableDistributedTracingWithOptions(DistributedTracingOptions options = default)
Shouldn't this be public for preview?

2022-12-13 12:27 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
> +        internal CosmosClientBuilder EnableDistributedTracingWithOptions(DistributedTracingOptions options = default)
Or the PR is only for the Enabled flag and not the options?

2022-12-13 12:28 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/DistributedTracingOptions.cs
> +        /// SDK generates <see cref="System.Diagnostics.Tracing.EventSource"/> (Event Source Name is "Azure-Cosmos-Operation-Request-Diagnostics") with Request Diagnostics String, If Operation level
Is "Azure-Cosmos-Operation-Request-Diagnostics" still valid as the name?

2022-12-13 12:36 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        /// This flag is there to disable it from source.
Using `<value>` like https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs#L199

2022-12-13 12:37 UTC, ealsur requested changes
Please address the public API documentation comments and make sure the PR title follows the pattern

2022-12-14 01:08 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
> +        /// Disables Operation level activity generation even if listener is subscribed to Azure.Cosmos.operation source and clears <see cref="DistributedTracingOptions"/> configured for this client
DistributedTracingOptions is internal as of now. No need to mention it is the doc yet.
Right now, this feature in on by default and builder has API to disable it.

2022-12-14 01:09 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
> +        internal CosmosClientBuilder EnableDistributedTracingWithOptions(DistributedTracingOptions options = default)
We decided to go step my step hence exposing the tracing flag right now.

2022-12-14 17:43 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
> +        /// Disables Operation level activity generation even if listener is subscribed to "Azure.Cosmos.Operation" source.
'if listener is subscribed to "Azure.Cosmos.Operation" source" 
Is enable dependent on subscription?

2022-12-14 17:45 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
> +            CosmosClientBuilder DisableDistributedTracing()
For boolean types we are using With<operation(bool). 
Please check WithLimitToEndpoint(bool )

2022-12-14 17:50 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        /// This flag is there to disable it from source.
Remove this line.

2022-12-14 17:50 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        = true;
Keep in mind, Teams (Microsoft Teams), uses preview packages.

2022-12-14 17:55 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        /// By default, SDK (Source Name is "Azure.Cosmos.Operation") generates operation level <see cref="System.Diagnostics.Activity"/> for methods calls.
Other properties that enable/disable use the "Gets or sets the flag...", what is the default is already explained in the `<value>` tag.

```suggestion
        /// Gets or sets the flag to generate operation level <see cref="System.Diagnostics.Activity"/> for methods calls using the Source Name "Azure.Cosmos.Operation".
```

2022-12-14 17:56 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
> +        /// Disables Operation level activity generation even if listener is subscribed to "Azure.Cosmos.Operation" source.
yes, in order to subscribe to the telemetry, customer has to enable is using `isDistributedTracingEnabled` flag (which is by default true) and subscribe to `Azure.Cosmos.Operation` source (AI SDK is already subscribed to this source name).

So, it means, app insight users, really don't have to do anything in order to enable this feature and that's the reason, I added an option to disable it in builder class, in case they don't want to use it.

2022-12-14 17:56 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        /// This flag is there to disable it from source.
If you want to add explanations, use `<remarks>`

2022-12-15 05:43 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        = true;
Teams is another customer for me. If you and @kirankumarkolli are not comfortable with this feature enabled by default. Then we can keep this flag off by default. and let the customer enable it explicitly.

2022-12-15 11:34 UTC, ealsur requested changes
Few remaining text changes

2022-12-15 11:34 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        /// <remarks> Applicable only when Operation level distributed tracing is not disabled i.e. <see cref="Microsoft.Azure.Cosmos.CosmosClientOptions.IsDistributedTracingEnabled"/></remarks>
nit: not disabled => enabled for clarity

```suggestion
        /// <remarks> Applicable only when Operation level distributed tracing is enabled through <see cref="Microsoft.Azure.Cosmos.CosmosClientOptions.IsDistributedTracingEnabled"/></remarks>
```

2022-12-15 11:34 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
> +        /// <param name="isEnabled"></param>
```suggestion
        /// <param name="isEnabled">Whether <see cref="CosmosClientOptions.IsDistributedTracingEnabled"/> is enabled.</param>
```

2022-12-15 11:34 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
> +        /// Disables Operation level activity generation even if listener is subscribed to "Azure.Cosmos.Operation" source.
Summary is no longer valid. Maybe something like (feel free to adjust):

```suggestion
        /// Sets whether Distributed Tracing for "Azure.Cosmos.Operation" source is enabled.
```

2022-12-15 11:34 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
> +        internal CosmosClientBuilder WithDistributedTracingOptions(DistributedTracingOptions options)
nit: This method might probably need to be refactored afterwards when the Options type is public, having 2 with the same name means they can be called twice on the same builder

2022-12-15 11:34 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        /// Gets or sets the flag to generate operation level <see cref="System.Diagnostics.Activity"/> for methods calls using the Source Name "Azure.Cosmos.Operation"..
```suggestion
        /// Gets or sets the flag to generate operation level <see cref="System.Diagnostics.Activity"/> for methods calls using the Source Name "Azure.Cosmos.Operation".
```

2022-12-15 18:41 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
> +        internal CosmosClientBuilder WithDistributedTracingOptions(DistributedTracingOptions options)
yes I agree....

2022-12-16 10:17 UTC, ealsur approved these changes

2022-12-16 10:18 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/AssertActivity.cs
> +    using Castle.Core.Internal;
nit: I don't think you are using Castle.Core?

2022-12-19 19:12 UTC, ealsur approved these changes

2022-12-19 19:12 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
> +    "Microsoft.Azure.Cosmos.CosmosClientOptions;System.Object;IsAbstract:False;IsSealed:False;IsInterface:False;IsEnum:False;IsClass:True;IsValueType:False;IsNested:False;IsGenericType:False;IsSerial
Please get an API approval from @kirankumarkolli

2023-01-12 20:14 UTC, kirankumarkolli approved these changes

2023-01-12 20:15 UTC, merged