[WIP] add support for decimal type as part of Number64
Azure/azure-cosmos-dotnet-v3 pull request #3609
Opened 2022-12-17 14:38 UTC by AmriHS

# Pull Request Template

## Description
**WIP**
Please include a summary of the change and which issue is fixed. Include samples if adding new API, and include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #IssueNumber

2022-12-19 08:18 UTC, ealsur commented
/azp run

2022-12-20 10:41 UTC, ealsur commented
@adityasa Can you review this proposed change?

2022-12-22 00:01 UTC, AmriHS commented
/azp run

2022-12-22 19:23 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Number64.cs
> +            else if (this.IsDecimal)
>else [](http://example.com/codeflow?start=12&length=4)

Nit, no need for else.

2022-12-22 19:23 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Number64.cs
> +        private Number64(decimal value)
A newline before would be nice.

2022-12-22 19:26 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Number64.cs
> +            else if (number64.IsDecimal)
>else [](http://example.com/codeflow?start=12&length=4)

Nit, no need for else.

2022-12-22 19:27 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Number64.cs
> +            else if (number64.IsInteger)
>else [](http://example.com/codeflow?start=12&length=4)

Same as before.

2022-12-22 19:27 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Number64.cs
> +            else if (number64.IsInteger)
>else [](http://example.com/codeflow?start=12&length=4)

Same.

2022-12-22 19:28 UTC, adityasa commented
>                 comparison = first.CompareTo(second);

Does this work for Decimal numbers correctly?

---
Refers to: Microsoft.Azure.Cosmos/src/Number64.cs:312 in d3be84f. [](commit_id = d3be84fb51a5f602fc889a98fe56456f6681ca31, deletion_comment = False)

2022-12-22 19:35 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Linq/CosmosLinqJsonConverterTests.cs
> +                { -0.00000000000000000012m, "-0.00000000000000000012" },
Can you also add
Decimal.MinValue and MaxValue?

2022-12-22 19:38 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Linq/CosmosLinqJsonConverterTests.cs
> +        public void DecimalMaxValueIsPreservedTest()
>DecimalMaxValueIsPreservedTest [](http://example.com/codeflow?start=20&length=30)

I see this as a dedicated test. Is there a specific reason (that I am missing) why it's a test method by itself?

2022-12-22 19:42 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/SqlObjects/Visitors/SqlObjectTextSerializer.cs
> +                stringBuilder.Append(value.ToString("G", CultureInfo.InvariantCulture));
Curious, is this exercised by one of the tests you added?

2022-12-22 19:44 UTC, adityasa commented
>         public int CompareTo(Number64 other)

While I admit that we may be missing existing coverage, this may be a good opportunity to add some for this method, whose implementation correctness seems critical.

---
Refers to: Microsoft.Azure.Cosmos/src/Number64.cs:292 in d3be84f. [](commit_id = d3be84fb51a5f602fc889a98fe56456f6681ca31, deletion_comment = False)

2022-12-22 19:45 UTC, adityasa commented
Thank you for taking care of this.

2022-12-22 19:46 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Linq/ExpressionToSQL.cs
> -                }
@neildsh - are you aware of any reasons why this was handled specially (in this manner) here, instead of proposed implementation?

2022-12-27 23:43 UTC, AmriHS commented
[[](url)](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/814e72eca593e855838434766596e7bf8945e1b7/Microsoft.Azure.Cosmos/src/Json/JsonSerializer.cs#L340)

@adityasa 
I don't think these changes causing any regression on JsonSerializer. However, this referenced code is not right. It is converting decimal to double as part of JSON serialization. If this also need to handle decimal as part of this PR, please let me know as I have the changes locally. Otherwise, I can create another Bug and raise another PR.

2023-01-10 17:58 UTC, adityasa approved these changes
:shipit:

2023-01-10 19:23 UTC, neildsh commented
This change is trying to stuff a 128 bit value (`decimal`) into a `Number64` which is, as the name indicates, supposed to be 64 bits wide. This change breaks serialization for `Number64` completely. As such, we cannot take this change.

2023-01-10 19:26 UTC, neildsh requested changes
This change is trying to stuff a 128 bit value (`decimal`) into a `Number64` which is, as the name indicates, supposed to be 64 bits wide. This change breaks serialization for `Number64` completely. As such, we cannot take this change.

At this point I am not sure if we actually need a type that is 128 bits wide, since the backend query implementation only supports 64 bits right now.

2023-05-26 20:53 UTC, closed without merging