Client Telemetry: Adds ClientConfig API support
Azure/azure-cosmos-dotnet-v3 pull request #3623
Opened 2023-01-02 03:06 UTC by sourabh1007

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Include samples if adding new API, and include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #IssueNumber

2023-01-11 16:07 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +            if (this.GatewayStoreModel is GatewayStoreModel gatewayModel)
nit: The caller is already all these checks, is the duplication adding anything?

2023-01-11 16:07 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Settings/AccountProperties.cs
> +        internal AccountClientConfiguration ClientConfiguration { get; set; }
Should it have a `[JsonIgnore]`?

2023-01-17 01:31 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +                HttpTimeoutPolicyNoRetry.Instance,
TTN: not retrying

2023-01-17 01:39 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +                DefaultTrace.TraceError($"Error while fetching client configuration. Sevice Endpoint: {serviceEndpoint}, Exception: {ex.StackTrace}");
returning null if this API fails

2023-02-03 20:39 UTC, kirankumarkolli commented
GatewayStoreModel is created after the GatewayAccountReader is created (which is also passed to the GlobalEndpointManager). 

How about passing GatewayAccountReader into the GatewayStoreModel?

2023-02-03 20:56 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientCreateAndInitializeTest.cs
> +                        httpCallsMade++;
Move the increment before the if

2023-02-03 20:56 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientCreateAndInitializeTest.cs
> +                        httpCallsMade++;
Increment before the if, otherwise it is not reflecting the true number of http calls

2023-02-03 20:57 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientCreateAndInitializeTest.cs
> +            Assert.AreEqual(6, httpCallsMade);
Why is this increasing? How is the test enabling Client Telemetry?

2023-02-03 20:57 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientCreateAndInitializeTest.cs
> +                    Console.WriteLine(request.RequestUri);
Remove

2023-02-03 20:57 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientCreateAndInitializeTest.cs
> +            Assert.AreEqual(2, httpCallsMade); // Account Call and Client Config call
Why is this increasing? How is the test enabling Client Telemetry?

2023-02-03 20:59 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDatabaseAccountSettingsTests.cs
> +            cosmosClient.Dispose();
Why not `using`?

2023-02-03 21:00 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDatabaseAccountSettingsTests.cs
> +            CosmosClient cosmosClient = TestCommon.CreateCosmosClient(
```suggestion
            using CosmosClient cosmosClient = TestCommon.CreateCosmosClient(
```

That way if the test fails, the client is disposed anyway. Removing the dispose call

2023-02-03 21:00 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDatabaseAccountSettingsTests.cs
> +                useGateway: true);
Why Gateway mode? The original TestInitialization was not using it

2023-02-03 21:24 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientCreateAndInitializeTest.cs
> +            Assert.AreEqual(6, httpCallsMade);
Http call to get client configuration will always be there. It returns telemetry configuration, does matter if it was already enabled or disabled.

2023-02-03 21:26 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientCreateAndInitializeTest.cs
> +            Assert.AreEqual(2, httpCallsMade); // Account Call and Client Config call
it not about enabling client telemetry..its about making http call to get client config from gateway.

2023-02-03 21:45 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDatabaseAccountSettingsTests.cs
> +                useGateway: true);
in this case it doesn't matter but point taken.

2023-02-03 22:07 UTC, sourabh1007 commented
> out passing GatewayAccountReader into the GatewayStor

We can do a lot of refactoring, but I would like to avoid it doing as part of this PR. maybe I can take it as separate PR.

2023-02-03 22:29 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/GatewayAccountReader.cs
> +                verb: "GET",
Why not keep `HttpConstants.HttpMethods.Get`?

2023-02-03 22:29 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/GatewayAccountReader.cs
> +                        clientSideRequestStatistics: null,
Wouldn't this drop the trace?

2023-02-03 22:29 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/GatewayAccountReader.cs
> +        private async Task<T> GetDatabaseAccountAsync<T>(Uri serviceEndpoint)
What other `T` is there to read the DatabaseAccount that is not `AccountProperties`?

2023-02-03 22:29 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +                timeoutPolicy: HttpTimeoutPolicyNoRetry.Instance,
Do we use the same NoRetry policy to get the account information?

2023-02-03 22:40 UTC, ealsur requested changes
So this will be one more HTTP call during initialization, what happens if it fails? What is the availability of this endpoint? Is it the same as the account endpoint? What if we get the account information but the call to get the Client Telemetry config fails? Would it be disabled? Can we add these details to the Description?

2023-02-03 22:40 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +                timeoutPolicy: HttpTimeoutPolicyNoRetry.Instance,
What if it fails?

2023-02-03 22:50 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientCreateAndInitializeTest.cs
> +            Assert.AreEqual(6, httpCallsMade);
Can this be called out in the Description? What is the explicit endpoints involved? Is there a Design that shows the sequence of endpoints involved?

2023-02-05 02:32 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/GatewayAccountReader.cs
> +        private async Task<T> GetDatabaseAccountAsync<T>(Uri serviceEndpoint)
`AccountClientConfigutaion`, it is similar to account API. just endpoint/url is changed.

2023-02-06 16:11 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/GatewayAccountReader.cs
> +        private async Task<T> GetDatabaseAccountAsync<T>(Uri serviceEndpoint)
But then it is not the DatabaseAccount (the method is called GetDatabaseAccountAsync). Why are we reusing the method for a different model?

2023-02-06 16:16 UTC, ealsur commented
> What happens if it fails?
> Right now, it fetches only client telemetry configuration. but still I believe, it should behave similar to Account Properties API. > **Hence initialization should fail if this API fails.**

> What if we get the account information but the call to get the Client Telemetry config fails? Would it be disabled?
> It is any like any other configuration where we will have a flag which will tell if feature is enabled or not and other information > will be client telemetry URL. Client Telemetry Job will act according to the returned config.

The question here is how does the SDK react on the scenario where the account information was obtained, but for whatever reason, the Client Telemetry call fails. 

Why would we fail the client initialization if the Client Telemetry configuration fails? The SDK client has all the information needed to initialize, wouldn't this add a new failure point to customers initializing? Could we make it more resilient? What if it fails to initialize and we set it as disabled, and 5 minutes after with the refresh, it gets the right information, would the client telemetry job initialize?

What happens if the first initialization works (we get the information, we enable the Client Telemetry Job) but in one of the 5 min refreshes we fail to get it? Would we disable the Client Telemetry job? Or retain the previous known configuration (that it's enabled)?

Is the new client config endpoint available in all regions? For example, if the account is in West US, we can fetch the account information from `myaccount.documents.azure.com` and from `myaccount-westus.documents.azure.com`, is the same valid for the new API? Or is it just limited to the global endpoint `myaccount.documents.azure.com`?

2023-03-06 16:50 UTC, sourabh1007 commented
@ealsur Please see my comments below:

**The question here is how does the SDK react on the scenario where the account information was obtained, but for whatever reason, the Client Telemetry call fails.**
_You mean "Account Client Config API" call is failed? If yes, then, first there should not any reason to fail this call only because it is developed and hosted similar to "Database Account Properties" call. Even if it fails, I think it is important for us to know that it is failing and should be fixed or supported by us like any other API. Suppressing failure of this API will increase the problem for us as we will never know that this API is failing at all._

**Why would we fail the client initialization if the Client Telemetry configuration fails? The SDK client has all the information needed to initialize, wouldn't this add a new failure point to customers initializing? Could we make it more resilient? What if it fails to initialize and we set it as disabled, and 5 minutes after with the refresh, it gets the right information, would the client telemetry job initialize?**
_Same as above, there should not any scenario where "only" this API should be failing. If it is happening, we should know.  It is re-checking for the job configuration in every 5 minutes and start and stop the job accordingly._

**What happens if the first initialization works (we get the information, we enable the Client Telemetry Job) but in one of the 5 min refreshes we fail to get it? Would we disable the Client Telemetry job? Or retain the previous known configuration (that it's enabled)?**
_it should mimic the AccountProperties API behavior._

**Is the new client config endpoint available in all regions? For example, if the account is in West US, we can fetch the account information from myaccount.documents.azure.com and from myaccount-westus.documents.azure.com, is the same valid for the new API? Or is it just limited to the global endpoint myaccount.documents.azure.com?**
_It is account level configuration hence shouldn't matter which region call it is. this API will return client configuration for that account._

2023-04-28 17:17 UTC, sourabh1007 commented
incorporating all changes/feedback in a new PR which is a new design for this feature.

2023-04-28 17:17 UTC, closed without merging