CosmosClientOptions: Adds ServerCertificateCustomValidationCallback for Http and TCP
Azure/azure-cosmos-dotnet-v3 pull request #3636
Opened 2023-01-09 15:36 UTC by aavasthy

# Pull Request Template

## Description
[Issue 3336](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3336): **Parameterize server ssl cert name override in direct connectivity mode**
In scenarios where the client service cannot take a dependency on Dns (i.e connecting to cosmosDb server using IP).
The ssl handshake with direct connectivity fails since url doesn't match the SN/SAN of the server certificate.

## Solution
Adding ServerCertificateCustomValidationCallback contract field for HTTP and TCP SSL callbacks. 
Include the callback field in StoreClientFactory in direct package 3.30.0 version via this PR https://msdata.visualstudio.com/CosmosDB/_git/CosmosDB/pullrequest/951432

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Closing issues

To automatically close an issue: closes #3336

2023-01-12 22:07 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs
> +        public Func<HttpRequestMessage, X509Certificate2, X509Chain, SslPolicyErrors, Boolean> ServerCertificateCustomValidationCallback
nit: newline inbetween properties

2023-01-12 22:07 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        /// Certificate validation function
Please add more details about this. Also add a `<remarks>` section with any extra information that might be relevant, for example, which are the scenarios where someone would use it for and which are the caveats if any (for example, you'd not want to have this on a production environment)

2023-01-12 22:07 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        internal RemoteCertificateValidationCallback SslCustomValidationCallBack
This internal property sounds a bit off, could it be simply generated on the place it is needed (DocumentClient) instead of here?

2023-01-12 22:23 UTC, aavasthy commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        internal RemoteCertificateValidationCallback SslCustomValidationCallBack
> This internal property sounds a bit off, could it be simply generated on the place it is needed (DocumentClient) instead of here?

This internal property calls the main public delegate and gets passed as parameter from clientCOntextCore -> DocumentCLient.
Should I define it in DocumentCLient and then try to invoke the main validationCallBack from there?

2023-01-13 00:39 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +        /// <param name="remoteCertificateValidationCallback"></param>
Can you add some unit tests for `DocumentClient` ?

2023-01-13 00:40 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +        /// <param name="remoteCertificateValidationCallback"></param>
Add some descriptions and context about `remoteCertificateValidationCallback` as a part of `<param></param>`

2023-01-13 16:13 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        public Func<HttpRequestMessage, X509Certificate2, X509Chain, SslPolicyErrors, bool> ServerCertificateCustomValidationCallback { get; set; }
For certificate validation is HttpReqeuwstMessage needed? 

For TCP HttpMessage seems confusing right?

2023-01-13 16:16 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        /// Certificate validation function
Also callout about Handler override expectations as well.
With override guide them to do in application code.

2023-01-13 16:22 UTC, aavasthy commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        public Func<HttpRequestMessage, X509Certificate2, X509Chain, SslPolicyErrors, bool> ServerCertificateCustomValidationCallback { get; set; }
Yes I get your concern. I was trying to match signature when putting this callback equal to httphandler callback.
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/a41da657643fac47cd4d0ab13d601da0549e6d0f/Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs#L116

I l see if there is a workaround

2023-01-17 14:39 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        internal RemoteCertificateValidationCallback SslCustomValidationCallBack
Right, my point is, creating a property enables other components to call it, and in general you'd want this if you expect multiple callers to use it. In this case, at least on the code in the PR, the only consumer creating a `RemoteCertificateValidationCallback` is the `DocumentClient` class. Why not just defer the creation of the `RemoteCertificateValidationCallback` to inside the `DocumentClient` when it is needed, if there is noone else consuming it.

2023-01-17 22:23 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        public Func<object, X509Certificate2, X509Chain, SslPolicyErrors, bool> ServerCertificateCustomValidationCallback { get; set; }
What is expected of first argument (object), how about exclude that argument it-self?

2023-01-17 22:24 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
> +                }
nit: new line after closing braces.

2023-01-17 22:27 UTC, ealsur requested changes

2023-01-17 22:27 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        public Func<object, X509Certificate2, X509Chain, SslPolicyErrors, bool> ServerCertificateCustomValidationCallback { get; set; }
The Azure SDK version does not have the object/HttpRequestMessage:

```
public ServerCertificateCustomValidationArgs(X509Certificate2? certificate, X509Chain? certificateAuthorityChain, SslPolicyErrors sslPolicyErrors)
```

Can it be simply:

```suggestion
        public Func<X509Certificate2, X509Chain, SslPolicyErrors, bool> ServerCertificateCustomValidationCallback { get; set; }
```

And for HTTP, we can simply do like https://github.com/Azure/azure-sdk-for-net/blob/4f54c9cb440c9db05d26b0538ff3bce2bbc3c82d/sdk/core/Azure.Core/src/Pipeline/HttpClientTransport.cs#L565

```
if (serverCertificateCustomValidationCallback != null)
{
	httpHandler.ServerCertificateCustomValidationCallback = (_, certificate2, x509Chain, sslPolicyErrors) =>
	{
		return serverCertificateCustomValidationCallback(certificate2, x509Chain, sslPolicyErrors));
	};
}
```

2023-01-17 22:34 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
> +                return (obj, cert, chain, policy) => serverCertificateCustomValidationCallback(obj, (X509Certificate2)cert, chain, policy);
```suggestion
                return serverCertificateCustomValidationCallback == null ? null : (obj, cert, chain, policy) => serverCertificateCustomValidationCallback(obj, (X509Certificate2)cert, chain, policy);
```

2023-01-17 22:36 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
> +        },
I believe there are no changes in this file. Only the line numbers were altered due to `UpdateCoontract.ps1` script. If this is the case, please reset this to original so that the differences do no appear.

2023-01-17 22:38 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientConfigurationDiagnosticTest.cs
> +        [TestMethod]
Please add some description on what is expected from the test.

2023-01-17 23:32 UTC, aavasthy commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        public Func<object, X509Certificate2, X509Chain, SslPolicyErrors, bool> ServerCertificateCustomValidationCallback { get; set; }
It will give errors as RemoteCertificateValidationCallback has object parameter.

public delegate bool RemoteCertificateValidationCallback(object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors);

2023-01-17 23:32 UTC, aavasthy commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        public Func<object, X509Certificate2, X509Chain, SslPolicyErrors, bool> ServerCertificateCustomValidationCallback { get; set; }
It will give errors as RemoteCertificateValidationCallback has object parameter.

public delegate bool RemoteCertificateValidationCallback(object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors);

2023-01-18 05:00 UTC, aavasthy commented on Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs
> +        public Func<HttpRequestMessage, X509Certificate2, X509Chain, SslPolicyErrors, Boolean> ServerCertificateCustomValidationCallback
Updated

2023-01-18 05:01 UTC, aavasthy commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        /// Certificate validation function
Added more description about callback delegate.

2023-01-18 05:01 UTC, aavasthy commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +        /// <param name="remoteCertificateValidationCallback"></param>
Moved the main function to clientcontext core and added a unit test for it

2023-01-18 05:01 UTC, aavasthy commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +        /// <param name="remoteCertificateValidationCallback"></param>
Added description

2023-01-18 05:07 UTC, aavasthy commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        public Func<object, X509Certificate2, X509Chain, SslPolicyErrors, bool> ServerCertificateCustomValidationCallback { get; set; }
Removed object parameter ServerCertificateCustomValidationCallback

2023-01-18 05:07 UTC, aavasthy commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        public Func<object, X509Certificate2, X509Chain, SslPolicyErrors, bool> ServerCertificateCustomValidationCallback { get; set; }
updated

2023-01-18 05:07 UTC, aavasthy commented on Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
> +                return (obj, cert, chain, policy) => serverCertificateCustomValidationCallback(obj, (X509Certificate2)cert, chain, policy);
Updated

2023-01-18 05:09 UTC, aavasthy commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
> +        },
I copied this file from master and pushed it but the build failed in the pipeline. The issue asked to run UpdateContracts script.

2023-01-18 11:05 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs
add documentation.

2023-01-18 14:38 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientConfigurationDiagnosticTest.cs
> +            RntbdConnectionConfig tcpconfig = cosmosClient.ClientConfigurationTraceDatum.RntbdConnectionConfig;
nit: This variable is not used

2023-01-18 14:38 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientConfigurationDiagnosticTest.cs
> +            CosmosClient cosmosClient = TestCommon.CreateCosmosClient(options);
nit: variable not used

2023-01-18 14:38 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientConfigurationDiagnosticTest.cs
> +            CosmosClientOptions options = new CosmosClientOptions
nit: variable not used

2023-01-18 14:40 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientConfigurationDiagnosticTest.cs
> +            Assert.IsTrue(context.DocumentClient.remoteCertificateValidationCallback(new object(), x509Certificate2, x509Chain, sslPolicyErrors));
How is this assert verifying that the `clientOptions.ServerCertificateCustomValidationCallback` is called or that the `remoteCertificateValidationCallback` is not `null`?

Also, does this need to be an Emulator test (do you need the Emulator to be running) to make this assertion?

2023-01-19 01:35 UTC, aavasthy commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientConfigurationDiagnosticTest.cs
> +            CosmosClient cosmosClient = TestCommon.CreateCosmosClient(options);
updated

2023-01-19 01:36 UTC, aavasthy commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientConfigurationDiagnosticTest.cs
> +            CosmosClientOptions options = new CosmosClientOptions
updated

2023-01-19 01:36 UTC, aavasthy commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientConfigurationDiagnosticTest.cs
> +            RntbdConnectionConfig tcpconfig = cosmosClient.ClientConfigurationTraceDatum.RntbdConnectionConfig;
updated

2023-01-19 01:36 UTC, aavasthy commented on Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs
updated

2023-01-19 01:37 UTC, aavasthy commented on Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
> +                }
updated

2023-01-19 01:42 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        /// This is applicable when client service has issue connecting to server using IP and needs certificate validation.
Let's think this one through. This API would not solve any issue when the user is interacting with the service normally, would it? In theory, what does it do? It allows the user to customize the certificate validation process (for both TCP and HTTP).

Should we add a notice that it should not be used for production environments? @kirankumarkolli Any ideas?

2023-01-19 01:42 UTC, ealsur approved these changes
LGTM, let's polish the public comment though

2023-01-19 18:28 UTC, ealsur commented
@aavasthy Also please update the PR title with the right format

2023-01-20 14:51 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
> +        internal static RemoteCertificateValidationCallback SslCustomValidationCallBack(Func<X509Certificate2, X509Chain, SslPolicyErrors, bool> serverCertificateCustomValidationCallback)
nit: This can be `private`, it is not being accessed by other classes

2023-01-20 20:14 UTC, aavasthy commented on Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
> +        internal static RemoteCertificateValidationCallback SslCustomValidationCallBack(Func<X509Certificate2, X509Chain, SslPolicyErrors, bool> serverCertificateCustomValidationCallback)
updated

2023-01-20 20:14 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        /// This is applicable when client service has issue connecting to server using IP and needs certificate validation.
It only allows custom certification validation if the application desires one.

2023-01-20 21:08 UTC, aavasthy commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        internal RemoteCertificateValidationCallback SslCustomValidationCallBack
updated

2023-01-20 23:32 UTC, ealsur submitted a review, later dismissed
LGTM, please see the last small nit and comment about the public API text

2023-01-20 23:32 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientConfigurationDiagnosticTest.cs
> +    using System.Net.Security;
Not needed, undo this file

2023-01-22 23:19 UTC, aavasthy commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientConfigurationDiagnosticTest.cs
> +    using System.Net.Security;
updated

2023-01-23 21:28 UTC, ealsur approved these changes

2023-01-23 21:53 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientResourceUnitTests.cs
> +            Assert.IsTrue(context.DocumentClient.remoteCertificateValidationCallback(new object(), x509Certificate2, x509Chain, sslPolicyErrors));
Please assert that the call-back is called at-least twice (once for GW and direct)

2023-01-23 21:53 UTC, kirankumarkolli approved these changes

2023-01-24 15:39 UTC, ealsur approved these changes

2023-01-24 16:52 UTC, merged