3.32.0: Adds new SDK version and contract files
Azure/azure-cosmos-dotnet-v3 pull request #3687
Opened 2023-02-03 18:15 UTC by aavasthy

# Pull Request Template

## Description
This bumps the SDK version from 3.31.2 to 3.32.0. Please see the below changes in the GA public contract.

<img width="767" alt="image" src="https://user-images.githubusercontent.com/113193425/216677097-b0d71e81-4fa2-4afd-a056-8c8409e2cd0a.png">

Also highlighted below are the preview contract changes.
<img width="862" alt="image" src="https://user-images.githubusercontent.com/113193425/216676873-2158116d-a3ef-4f0e-9e49-53a2764b06c4.png">

2023-02-03 19:10 UTC, ealsur requested changes

2023-02-03 19:10 UTC, ealsur commented on Microsoft.Azure.Cosmos/contracts/API_3.32.0.txt
> +    public class ChangeFeedMetadata
This is not public on the GA build (`dotnet build -c Release`), please verify how this file was generated

2023-02-03 19:12 UTC, ealsur commented on changelog.md
> +- [#3664](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3664) Query: Adds EnableOptimisticDirectExecution flag to QueryRequestOptions
Remove, this was incorrectly tagged as public (missing [Internal]), the API that was added was not public

2023-02-03 19:17 UTC, ealsur commented on changelog.md
> +- [#3680](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3680) LocalQuorum: Adds Quorum reads on Consistent Prefix Accounts
Missing:

* https://github.com/Azure/azure-cosmos-dotnet-v3/commit/612337cfbd445a95042457b672819e36e0a6319e
* https://github.com/Azure/azure-cosmos-dotnet-v3/commit/6632168410079b849aa5d6f31f9bdd6f1ef52da1
* https://github.com/Azure/azure-cosmos-dotnet-v3/commit/b24eeb96babef246d8deb2305e08accb7ceffc7d
* https://github.com/Azure/azure-cosmos-dotnet-v3/commit/010e4ba7198b62cb13b680baf4f6b2d6f9538cef
* https://github.com/Azure/azure-cosmos-dotnet-v3/commit/2681be80b9674fc8a09f1a7552894ef8741b23e2
* https://github.com/Azure/azure-cosmos-dotnet-v3/commit/c38346dd8d029bf32dc523c678b6df95e8c1b9b9
* https://github.com/Azure/azure-cosmos-dotnet-v3/commit/ab1f249c4074545765e466ece547a8c96fe51095
* https://github.com/Azure/azure-cosmos-dotnet-v3/commit/68b980523bd89fa4b298b1589e6d7d5148df3748
* https://github.com/Azure/azure-cosmos-dotnet-v3/commit/c0ac87af429fcf526b125f8777b02a3bd3997704
* https://github.com/Azure/azure-cosmos-dotnet-v3/commit/63a846de8cb108cccb17addefa9b1937557979ca
* https://github.com/Azure/azure-cosmos-dotnet-v3/commit/748f86c052934796590c12d80e836f7f031d8525
* https://github.com/Azure/azure-cosmos-dotnet-v3/commit/f679c3ba9368b3b297be873e41c131729da123fd
* https://github.com/Azure/azure-cosmos-dotnet-v3/commit/ff01c1448fe40226d2a8433c135e48d47f66d9b9

2023-02-03 19:21 UTC, ealsur commented on changelog.md
> +- [#3598](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3598) AI integration: Adds IsDistributedTracingEnabled flag as public API to enable/disable this feature
@sourabh1007 Is this the right text? Can we better describe the introduction of this as a feature. Maybe something like:

```suggestion
- [#3598](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3598) AI integration: Adds Distributed Tracing support. Enabled by default, which can be disabled through `CosmosClientOptions.IsDistributedTracingEnabled`
```

2023-02-03 19:26 UTC, ealsur commented on changelog.md
> +- [#3640](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3640) Fix for service using Microsoft.Azure.Cosmos 3.30.1 getting token expiry errors
This PR link is repeated, could it be a different one?

2023-02-03 19:26 UTC, ealsur commented on changelog.md
> +- [#3640](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3640) Upgrade Resiliency: Refactors Implementation for Opening Rntbd Connections to Backend Replicas in Direct Mode.
@kundadebdatta Is this something that is released or under the env variable? If under an env variable, then we should remove it?

2023-02-03 19:28 UTC, aavasthy commented on changelog.md
> +- [#3640](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3640) Fix for service using Microsoft.Azure.Cosmos 3.30.1 getting token expiry errors
This PR closed two different issues.

2023-02-03 19:35 UTC, kundadebdatta commented on changelog.md
> +- [#3640](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3640) Upgrade Resiliency: Refactors Implementation for Opening Rntbd Connections to Backend Replicas in Direct Mode.
@ealsur : This was merged (however not released yet) back in October with this [PR 3508](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3508) and this new PR - 3640 just refactors the implementation to match with the Direct code refactors. The replica validation feature changes that is backed by the environment variable is yet to be merged.

2023-02-03 19:48 UTC, ealsur commented on changelog.md
> +- [#3640](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3640) Upgrade Resiliency: Refactors Implementation for Opening Rntbd Connections to Backend Replicas in Direct Mode.
Then this PR is not really shipping anything yet, correct? We can remove it from the changelog?

2023-02-03 19:48 UTC, ealsur commented on changelog.md
> +- [#3640](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3640) Fix for service using Microsoft.Azure.Cosmos 3.30.1 getting token expiry errors
You are correct

2023-02-03 20:20 UTC, kundadebdatta commented on changelog.md
> +- [#3640](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3640) Upgrade Resiliency: Refactors Implementation for Opening Rntbd Connections to Backend Replicas in Direct Mode.
This PR refactors the `CosmosClient.CreateAndInitializeAsync()` to initialize and warm up the caches by opening up the Rntbd connections to the backend replica nodes, instead of using the dummy querys on all feed ranges to open connection. This is separate from the replica validation feature _(which internally uses some of the changes from this PR to open connections to the replica nodes)_, and IMO should be included as a part of the release.

2023-02-03 20:49 UTC, ealsur commented on changelog.md
> +- [#3640](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3640) Upgrade Resiliency: Refactors Implementation for Opening Rntbd Connections to Backend Replicas in Direct Mode.
What about https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3508? Should we then mention both and rewrite the text to say something about CreateAndInitializeAsync? The current text is not very clear

2023-02-03 21:11 UTC, kundadebdatta commented on changelog.md
> +- [#3640](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3640) Upgrade Resiliency: Refactors Implementation for Opening Rntbd Connections to Backend Replicas in Direct Mode.
That's probably a good idea! Let's mention both and update the verbiage. Let me know how you feel about the below text for #3640 :

> Upgrade Resiliency: Refactors `CosmosClient` Initialization to use `IOpenConnectionHandler` for Opening Rntbd Connections to Backend Replicas in Direct Mode.

@aavasthy - If we agree, can you please update the verbiage ?

2023-02-03 21:57 UTC, aavasthy commented on changelog.md
> +- [#3664](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3664) Query: Adds EnableOptimisticDirectExecution flag to QueryRequestOptions
Removed PR 3664

2023-02-03 21:58 UTC, aavasthy commented on changelog.md
> +- [#3680](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3680) LocalQuorum: Adds Quorum reads on Consistent Prefix Accounts
updated

2023-02-03 21:59 UTC, aavasthy commented on changelog.md
> +- [#3598](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3598) AI integration: Adds IsDistributedTracingEnabled flag as public API to enable/disable this feature
@sourabh1007 updated the title based on the above suggestion. Let me know if you're good with the change.

2023-02-03 21:59 UTC, aavasthy commented on changelog.md
> +- [#3640](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3640) Upgrade Resiliency: Refactors Implementation for Opening Rntbd Connections to Backend Replicas in Direct Mode.
updated

2023-02-03 22:05 UTC, ealsur commented on changelog.md
> +- [#3496](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3496) ReadThroughputAsync: Adds XML comment to Database.ReadThroughputAsync definition
```suggestion
- [#3496](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3496) Documentation: Adds XML comment to Database.ReadThroughputAsync definition
```

2023-02-03 22:06 UTC, ealsur commented on changelog.md
> +- [#3555](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3555) Client Retry Policy: Adds HTTP timeouts with request-level cross-region retry
```suggestion
- [#3555](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3555) Availability: Adds HTTP timeouts with request-level cross-region retry
```

2023-02-03 22:06 UTC, ealsur commented on changelog.md
> +- [#3581](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3581) AI Integration: Removed EnableDiagnosticsTraceForAllRequests Config
Remove

2023-02-03 22:06 UTC, ealsur commented on changelog.md
> +- [#3508](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3508) CosmosClient Initialization: Adds implementation for opening Rntbd connections to backend replica nodes in Direct mode
```suggestion
- [#3508](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3508) CosmosClient Initialization: Fixes implementation for opening Rntbd connections to backend replica nodes in Direct mode
```

2023-02-03 22:07 UTC, ealsur commented on changelog.md
> +- [#3566](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3566) Change Feed Processor: Adds support for Resource Tokens
Anything that is "Adds" should be in an "Added" section on the same level as the "Fixed" section

2023-02-03 22:08 UTC, ealsur commented on changelog.md
> +- [#3643](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3643) Fixed CosmosClientBuilder.WithConnectionModeGateway documentation
```suggestion
- [#3643](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3643) Documentation: Fixed CosmosClientBuilder.WithConnectionModeGateway documentation
```

2023-02-03 22:08 UTC, ealsur commented on changelog.md
> +- [#3680](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3680) LocalQuorum: Adds Quorum reads on Consistent Prefix Accounts
This is internal, remove

2023-02-03 22:10 UTC, ealsur commented on changelog.md
> +- [#3508](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3508) CosmosClient Initialization: Adds implementation for opening Rntbd connections to backend replica nodes in Direct mode
```suggestion
- [#3508](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3508) CosmosClient Initialization: Refactors implementation for opening Rntbd connections to backend replica nodes in Direct mode
```

2023-02-03 22:10 UTC, ealsur commented on changelog.md
> +- [#3640](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3640) Upgrade Resiliency: Refactors CosmosClient.CreateAndInitializeAsync() to use IOpenConnectionHandler for Opening Rntbd Connections
Remove. In the line where we have `[#3508](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3508)` add this PR also, so it ends up being `- [#3508](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3508), [#3640](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3640)`

2023-02-03 22:12 UTC, ealsur commented on changelog.md
> +- [#3640](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3640) Fix for service using Microsoft.Azure.Cosmos 3.30.1 getting token expiry errors
```suggestion
- [#3640](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3640) Token expiration: Fixes token expired errors happening on some environments
```

2023-02-03 22:13 UTC, ealsur reviewed
Just a few more polishes on texts and it's good to go

2023-02-03 22:27 UTC, aavasthy commented on changelog.md
> +- [#3566](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3566) Change Feed Processor: Adds support for Resource Tokens
Even if it is a bug fix?

2023-02-03 22:51 UTC, ealsur commented on changelog.md
> +- [#3566](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3566) Change Feed Processor: Adds support for Resource Tokens
If its a bug fix, the text should be Fixes, right?

2023-02-03 23:45 UTC, ealsur submitted a review, later dismissed
@kirankumarkolli Can you approve/review the public API changes?

2023-02-06 17:27 UTC, kirankumarkolli commented on changelog.md
> +- [#3596](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3596) Full Fidelity Change Feed: Adds new LatestVersion and AllVersionsAndDeletes to ChangeFeedMode
How about calling the older name removal?

2023-02-06 17:27 UTC, kirankumarkolli submitted a review, later dismissed

2023-02-06 17:31 UTC, ealsur commented on changelog.md
> +- [#3596](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3596) Full Fidelity Change Feed: Adds new LatestVersion and AllVersionsAndDeletes to ChangeFeedMode
Maybe something like: 

```suggestion
- [#3596](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3596) Full Fidelity Change Feed: Adds new LatestVersion to ChangeFeedMode. `FullFidelity` is now renamed to `AllVersionsAndDeletes`.
```

2023-02-06 18:00 UTC, ealsur approved these changes

2023-02-06 18:38 UTC, kirankumarkolli approved these changes

2023-02-06 18:39 UTC, merged