[Internal] Client Telemetry: Adds logic to limit payload size to 2 MB
Azure/azure-cosmos-dotnet-v3 pull request #3717
Opened 2023-02-20 22:18 UTC by sourabh1007

## Description

Client Telemetry Service accepts maximum 2 Mb of payload so, making sure, payload is less than that. 

There will be very minimal chances that payload size can grow more than 2 MB even after this.

## Type of change
- [] New feature (non-breaking change which adds functionality)

2023-02-22 15:15 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> -        private async Task EnrichAndSendAsync()
Why is this a ValueTask? On which scenario the operation will return a non-async response?

2023-02-22 15:17 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +                    this.ProcessAndSend(
How is this change related to the 2MB limit? This is changing how the telemetry is sent from foreground to a fire-and-forget task

2023-02-22 15:19 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +                        json = JsonConvert.SerializeObject(this.clientTelemetryInfo, settings);
Is it possible for 1 of these `property` objects to be greater than 2Mb? What if the whole reason it was 2Mb was because there was 1 property that was larger?

2023-02-22 17:12 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +                    this.ProcessAndSend(
As processing part is growing over time, it is code refactoring to put all the processing part at one function which will be fire and forget.

2023-02-22 17:20 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> -        private async Task EnrichAndSendAsync()
`ValueTask` is kind of Wrapper on Task only, and it has its benefits in terms of memory allocation. Thats I am using `ValueTask` here. Please enlighten me if it won't provide any benefit over `Task`.

2023-02-25 19:26 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +                        json = JsonConvert.SerializeObject(this.clientTelemetryInfo, settings);
covering this also.

2023-03-01 03:00 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryProcessor.cs
> +                    clientTelemetryInfo.OperationInfo = null; //clearing everything
Is clearing in every loop iteration needed?

2023-03-01 03:04 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryProcessor.cs
> +                    clientTelemetryInfo.CacheRefreshInfo = null;
SystemInfo is repeated with each iteration right is it exacted?

2023-03-01 03:06 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryProcessor.cs
> +                    if (property == "OperationInfo")
One other alternative is to dynamically keep adding records one by one and see if its reaching the limits. 
Please check out CosmosTraceDiagnostics serialization.

2023-03-01 03:08 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryProcessor.cs
> +                foreach (string property in ClientTelemetryOptions.PropertiesContainMetrics)
What's the point of this loop, we can just do section one for OperationInfo and other for CacheRefreshInfo right?

2023-03-01 03:09 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryProcessor.cs
> +                    if (property == "OperationInfo")
It will allow combining both OperationInfo and CacheRefreshInfo also into a single reqeust.

2023-03-01 03:11 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryOptions.cs
> +            { "OperationInfo", 1000 },
Where are these limits coming from?

2023-03-01 03:12 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryProcessor.cs
> +                            = this.GetPages<OperationInfo, (LongConcurrentHistogram latency, LongConcurrentHistogram requestcharge)>(operationInfoSnapshot, property);
Am under assumption that we are limiting the @pages or entries we publish to start with. 
This needs to be guarded on service and appropriately throttle as well.

2023-03-01 03:25 UTC, kirankumarkolli requested changes

2023-03-01 03:25 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryProcessor.cs
> +                    request.Headers.Add(HttpConstants.HttpHeaders.DatabaseAccountName, globalDatabaseAccountName);
I understand that its a older decision. 
Wondering if addressing also needs to change to include account info. 
Address will allow most web services to parameterize and flow context natively (including tracing even in-case of errors before header processing)

2023-03-01 03:25 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryProcessor.cs
> +                    DefaultTrace.TraceError("Juno API response not successful. Status Code : {0},  Message : {1}", response.StatusCode, response.ReasonPhrase);
"Juno" is internal name, please exclude.

2023-03-01 03:25 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryProcessor.cs
> +                    DefaultTrace.TraceError("Juno API response not successful. Status Code : {0},  Message : {1}", response.StatusCode, response.ReasonPhrase);
Prefer: $"... Status Code : {response.StatusCode},  Message : {response.ReasonPhrase}"

2023-03-01 03:25 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryProcessor.cs
> +            return Task.Run(async () => await this.GenerateOptimalSizeOfPayloadAndSendAsync(clientTelemetryInfo, operationInfoSnapshot, cacheRefreshInfoSnapshot, cancellationToken), cancellationToken
Task might fail (missing exception handling and goes un-observed)

2023-03-01 13:37 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryOptions.cs
> +            { "OperationInfo", 1000 },
I checked the size of each JSON block and calculated how many JSON blocks it will take to make it 1.5 MB (.5 MB is reserved for other info and future enhancements) and then rounded off to a nearby number.

2023-03-01 13:38 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryProcessor.cs
> +                            = this.GetPages<OperationInfo, (LongConcurrentHistogram latency, LongConcurrentHistogram requestcharge)>(operationInfoSnapshot, property);
yes..you are right.. I will add the number of page limit also

2023-03-01 13:47 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryProcessor.cs
> +                    DefaultTrace.TraceError("Juno API response not successful. Status Code : {0},  Message : {1}", response.StatusCode, response.ReasonPhrase);
I did that but got a comment to remove revert it to this again. @ealsur what do you think?

2023-03-01 13:48 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryProcessor.cs
> +            return Task.Run(async () => await this.GenerateOptimalSizeOfPayloadAndSendAsync(clientTelemetryInfo, operationInfoSnapshot, cacheRefreshInfoSnapshot, cancellationToken), cancellationToken
it is being tracked in ClientTelemetry class line 185. Yes, I missed to put the loggers there, putting it.

2023-03-01 14:49 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryProcessor.cs
> +                    clientTelemetryInfo.CacheRefreshInfo = null;
yes...it is same.

2023-03-01 16:11 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> -        private async Task EnrichAndSendAsync()
ValueTask is used when an async method can return a cached value without performing an async operation most of the time.

2023-03-01 16:16 UTC, ealsur requested changes
Please undo the foreground/background change when sending data and defer that to another PR, focus of this PR is the 2Mb limit, right?

2023-03-01 16:16 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +                    _ = this.processor
This is a behavior change that is unrelated to the 2Mb size. This is changing the sending of the telemetry data from async in-line, to fire-and-forget. Can you please undo this and treat this as a separate PR with some indication of why is this a beneficial change? What is the performance benefit? How is concurrency handled on `this.numberOfFailures`?

2023-03-03 15:10 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryProcessor.cs
> +                    clientTelemetryInfo.OperationInfo = null; //clearing everything
old code, not applicable now..hence resolving

2023-03-03 15:11 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryProcessor.cs
> +                    if (property == "OperationInfo")
old code, not applicable now..hence resolving. Implemented as you suggested.

2023-03-03 15:11 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryOptions.cs
> +            { "OperationInfo", 1000 },
old code, not applicable now..hence resolving

2023-03-03 15:12 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryProcessor.cs
> +                            = this.GetPages<OperationInfo, (LongConcurrentHistogram latency, LongConcurrentHistogram requestcharge)>(operationInfoSnapshot, property);
it will be covered as separate PR.

2023-03-03 15:13 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryProcessor.cs
> +                    request.Headers.Add(HttpConstants.HttpHeaders.DatabaseAccountName, globalDatabaseAccountName);
as discussed in last catch up with tools federation team. we will revisit it if anything comes up in security review.

2023-03-03 15:53 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +                    _ = this.processor
As part of 2Mb payload size change, I wrote a custom serialization logic for client telemetry payload which will break the payload and will send those chunks and decided to run this new logic in a separate Task. Existing tests are working fine.
This implementation is not part of any performance enhancement.
for `this.numberOfFailures`, why do you think concurrency needs to be handled. It is a job which runs in every 10 min.

2023-03-03 15:54 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryProcessor.cs
> +                foreach (string property in ClientTelemetryOptions.PropertiesContainMetrics)
removed.

2023-03-03 16:57 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +                    _ = this.processor
How is that custom logic related to this change? This is changing an inline async execution to a background fire-and-forget pattern. This is unrelated to the serialization or the 2Mb problem.

2023-03-03 17:31 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Json/IJsonWriter.cs
> +        void WriteInt32Value(int value, bool withPrefix = true);
Undo. No need to use IJsonWriter to do JSon serialization. You can use Newtonsoft.JsonWriter

2023-03-03 21:33 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +                    _ = this.processor
made changes as we discussed.

2023-03-06 17:27 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +                        DefaultTrace.TraceError("Telemetry Job Processor failed with error : ", ex);
```suggestion
                        DefaultTrace.TraceError("Telemetry Job Processor failed with error : {0}", ex);
```

2023-03-06 22:41 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryPayloadWriter.cs
> +                    long lengthNow = stringBuilder.Length;
Who is appending to this StringBuilder? It nevers grows. Line 41 is checking the length (let's assume 0 initially), then line 60 calls `ToString()` but where is anything that Appends? When is the `writer` content go into the StringBuilder?

2023-03-06 22:44 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryPayloadWriter.cs
> +                    writer.WriteRawValue(requestChargeMetrics);
Are these 2 (latencyMetrics, requestChargeMetrics) never going to go beyond 2Mb?

2023-03-06 22:49 UTC, ealsur approved these changes

2023-03-06 23:31 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryPayloadWriter.cs
> +                    writer.WriteRawValue(requestChargeMetrics);
it has to go together (because belong to the same operation)...i cannot send them separately.

2023-03-07 14:48 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +                        this.numberOfFailures = 0;
Is the counter meant for #NWFailures or #EnrichAndSendAsync?

2023-03-07 14:51 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryHelper.cs
> +            List<SystemInfo> systemInfoCollection = new List<SystemInfo>
nit: Specify the capacity for know cases which avoid any list re-initializations

2023-03-07 15:00 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryPayloadWriter.cs
> +        private static readonly StringBuilder stringBuilder = new StringBuilder(ClientTelemetryOptions.PayloadSizeThreshold);
Why global state? 
If the goal is to reduce allocations then please prefer pooling instead.

2023-03-07 15:03 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryPayloadWriter.cs
> +            if (operationInfoSnapshot != null && operationInfoSnapshot.Count > 0)
nit: Prefer Any() instead of Count

2023-03-07 15:04 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryPayloadWriter.cs
> +                var opsEnumerator = operationInfoSnapshot.GetEnumerator();
nit: 'foreach (var entry in operationInfoSnapshot)' will be more intutive

2023-03-07 15:14 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryProcessor.cs
> +        internal async Task GenerateOptimalSizeOfPayloadAndSendAsync(ClientTelemetryProperties clientTelemetryInfo,
How about inline this method with above one?

2023-03-07 16:10 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +                        this.numberOfFailures = 0;
here any failure related to Client Telemetry Service API will increase this counter.
**ref.** https://github.com/Azure/azure-cosmos-dotnet-v3/blob/f262f8941f541332509eba64a2297e9d5e221675/Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs#L462
**ref.** https://github.com/Azure/azure-cosmos-dotnet-v3/blob/f262f8941f541332509eba64a2297e9d5e221675/Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs#L475

and resetting the counter on any successful call https://github.com/Azure/azure-cosmos-dotnet-v3/blob/f262f8941f541332509eba64a2297e9d5e221675/Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs#L468

FYI: it is existing code, not part of this PR.

2023-03-07 16:14 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryHelper.cs
> +            List<SystemInfo> systemInfoCollection = new List<SystemInfo>
There will be only 5 elements in the list, So reinitialization won't trigger at all. Setting capacity to "5", it will save some bits.

2023-03-07 18:45 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryPayloadWriter.cs
> +            if (operationInfoSnapshot.Any())
nit: operationInfoSnapshot?.Any()

2023-03-07 18:46 UTC, kirankumarkolli approved these changes

2023-03-08 17:41 UTC, kirankumarkolli approved these changes

2023-03-09 15:37 UTC, merged