[Internal] Client Telemetry: Refactors code to run client telemetry data processing task in background.
Azure/azure-cosmos-dotnet-v3 pull request #3783
Opened 2023-03-29 19:33 UTC by sourabh1007

## Description
Right now, if processing takes 1 minute then client telemetry window size will increase from 10 min to 10 + 1 = 11 min. Hence running it as a separate background job triggered by client telemetry job.

## Type of change
- [] New feature (non-breaking change which adds functionality)

2023-03-31 21:03 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +                        tempProcessorTask.Start(); // run it in background
Doesn't `Run` already start the task?

2023-03-31 21:40 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +                        this.processorTask?.Wait(this.processorCancellationTokenSource.Token);
This is a blocking call, why not `await` instead?

2023-03-31 21:41 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +                    catch (OperationCanceledException)
Why not use the pattern with Task.WhenAny and a Task.Delay along with the processorTask? If the Task.Delay finishes sooner, then it means the processorTask timed out and should be canceled

2023-03-31 21:59 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryOptions.cs
> +        internal const int ProcessorTimeOutInMs = 5 * 60 * 1000; // 5 minutes
Why not use TimeSpan.FromMinutes(5)?

2023-03-31 21:59 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> -                    if (this.numberOfFailures == allowedNumberOfFailures)
Who is using `allowedNumberOfFailures`? Should it be removed?

2023-03-31 21:59 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> -                    if (this.numberOfFailures == allowedNumberOfFailures)
What is `this.numberOfFailures` used for now?

2023-03-31 22:01 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +                        this.processorTask?.Wait(this.processorCancellationTokenSource.Token);
Also, the `this.processorCancellationTokenSource` has 5 minute lifespan, you are not resetting it, which means, after 5 min it is completely cancelled and it will forever stop the processing

2023-04-03 17:58 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +                        this.processorTask?.Wait(this.processorCancellationTokenSource.Token);
yes if particular batch is taking more than 5 min in processing.. just kill that task and give space to another upcoming task, I don't want to be in a situation when all the tasks are either piled up or eating resources in order to complete the processing task. I want to keep moving forward with whatever we have in our hand.

2023-04-03 18:01 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> -                    if (this.numberOfFailures == allowedNumberOfFailures)
I have removed this code.

2023-04-03 18:21 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
>                          DefaultTrace.TraceError("Telemetry Job Processor failed with error : {0}", ex);
added continue with block for this task and inside processor, there are other try-catchs available.

2023-04-03 18:40 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> -                    if (this.numberOfFailures == allowedNumberOfFailures)
already removed

2023-04-03 18:51 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +                            cancellationToken: this.processorCancellationTokenSource.Token)
`processorCancellationTokenSource` is created, but it is never reset. It is being created as a readonly on the class scope, you cannot reuse the CancellationTokenSource, it is not how it works.

When you create a CancellationTokenSource, it can be used once, it will cancel 5 minutes after it is created. You need to re-create it in order to use it in another subsequent request/operation.

2023-04-03 18:53 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +                                                .ContinueWith((i) =>
Avoid `ContinueWith`. You can do the same thing using an async method:

```
private static async Task ProcessAndObserve(Task processingTask)
{
    try
    {
        await processingTask;
    }
    catch (Exception ex)
    {
        DefaultTrace.TraceError($"Client Telemetry data processing task faulted. {0}", ex);
    }}
```

2023-04-03 18:58 UTC, ealsur requested changes
CancellationToken wiring on ProcessAndSendAsync is not enforcing timeouts and re-usage of CancellationTokenSource needs to be fixed

2023-04-03 18:58 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryProcessor.cs
> +        private readonly CancellationTokenSource serviceCancellationToken = new CancellationTokenSource(ClientTelemetryOptions.ClientTelemetryServiceTimeOut);
Same problem here. You are creating a CancellationTokenSource and reusing it, this will only work once

2023-04-03 18:58 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +                            cancellationToken: this.processorCancellationTokenSource.Token)
You are using `Task.Run` with CancellationToken parameter -> https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.run?view=net-8.0#system-threading-tasks-task-run(system-func((system-threading-tasks-task))-system-threading-cancellationtoken)

This does not work for a timeout enforcement, because `Task.Run` only check the CancellationToken state **before** the async work starts.

> A cancellation token that can be used to cancel the work if it has not yet started. [Run(Func<Task>, CancellationToken)](https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.run?view=net-8.0#system-threading-tasks-task-run(system-func((system-threading-tasks-task))-system-threading-cancellationtoken)) does not pass cancellationToken to action.

2023-04-03 20:54 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +                            cancellationToken: this.processorCancellationTokenSource.Token)
made changes

2023-04-05 18:12 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +                        CancellationTokenSource cancellationToken = new CancellationTokenSource(ClientTelemetryOptions.ClientTelemetryProcessorTimeOut);
The code in this method is not really enforcing the timeout, just passing the CT, if the enforcement is on the `ProcessAndSendAsync` why not create the CancellationTokenSource there?

2023-04-05 18:12 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +            finally
Should the catch with the TraceError be moved here?

2023-04-05 18:12 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryOptions.cs
> +
nit: remove extra spaces

2023-04-05 18:12 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryPayloadWriter.cs
> +                    if (cancellationToken.IsCancellationRequested)
Shouldn't the `callback.Invoke` also take the CancellationToken to cancel network calls?

2023-04-05 18:12 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryProcessor.cs
> +                if (cancellationToken.IsCancellationRequested)
This is only checking the 5 minute at the beginning, when do we expect 5 min to be elapsed if we check it only on the beginning? Should the 5 min better be enforced with a Task.Delay and WhenAny along with `SerializedPayloadChunksAsync`

2023-04-06 05:46 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +                        CancellationTokenSource cancellationToken = new CancellationTokenSource(ClientTelemetryOptions.ClientTelemetryProcessorTimeOut);
Here requirement is to check if processor task is taking more time than the configured timeout. There are 2 ways to solve this problem:
1. Using WhenAny() with Delay Thread or similar function to identify if my task is taking more than configured delay task : With this approach I see 2 problems, 
a) I will be spinning 2 extra tasks to identify the time taken by processor. Here, I want to avoid spinning up more threads. 
b) once it identified that processor task is taking more time, we get the instance of delay task but won't be able to cancel the processor task actually.

2. Cancellation Token approach (current approach): It is not actual timeout approach but it will serve the purpose, here I have a cancellation token with configured time, and I am checking for cancellation token status at the points where I think more time can be consumed. Now if in one of those places if it finds that token has been cancelled. it will just come out of the task and will stop consuming more resources.

**why not create the CancellationTokenSource there?** To include the time taken in spinning up a new thread (imagine a scenario with thread contention and anyhow processor took time to start)

2023-04-06 05:48 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +            finally
I intentionally moved it out of this. It is easier to write test along with this function otherwise, It will throw exception and just print the error. And I need to use mocking or something to do assertions.

2023-04-06 05:51 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryProcessor.cs
> +                if (cancellationToken.IsCancellationRequested)
it is not just in the beginning, it is there in all the data loops, these data loops might take time, I don't see any other code where time can be consumed.

2023-04-06 14:46 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +                        CancellationTokenSource cancellationToken = new CancellationTokenSource(ClientTelemetryOptions.ClientTelemetryProcessorTimeOut);
First, a Task is not a thread. Second, creating the CT here is not accounting the time to spin up the Task because you are not awaiting it. Third, because a Task is not a Thread, using solution one does not use more threads. And last, you can certainly cancel the processor task when the timeout happens, you can signal a CT inside the processor or dispose the Task directly.

2023-04-06 14:51 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +            finally
But your catch on the other function will not catch anything, because you are creating the Task using Task.Run (fire and forget), so you are dropping any exception logging.

2023-04-06 15:46 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryProcessor.cs
> +                if (cancellationToken.IsCancellationRequested)
Nevermind, I just saw the different parameters

2023-04-06 15:47 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryProcessor.cs
> +                if (cancellationToken.IsCancellationRequested)
```suggestion
cancellationToken.ThrowIfCancellationRequested();
```

2023-04-06 15:48 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryPayloadWriter.cs
> +                    if (cancellationToken.IsCancellationRequested)
Replace all the `throw new TimeoutException` with

```suggestion
                    cancellationToken.ThrowIfCancellationRequested();
```

2023-04-06 15:52 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryProcessor.cs
> +            CancellationTokenSource serviceCancellationToken = new CancellationTokenSource(ClientTelemetryOptions.ClientTelemetryServiceTimeOut);
Should this be a Linked CancellationToken?

```suggestion
            CancellationTokenSource serviceCancellationToken = new CancellationTokenSource(ClientTelemetryOptions.ClientTelemetryServiceTimeOut);
            CancellationTokenSource serviceCancellationToken = new CancellationTokenSource.CreateLinkedTokenSource(serviceCancellationToken.Token, cancellationToken);
```

2023-04-06 15:57 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +                        CancellationTokenSource cancellationToken = new CancellationTokenSource(ClientTelemetryOptions.ClientTelemetryProcessorTimeOut);
Example of how we enforce timeout on a Task -> https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedProcessing/FeedProcessorCore.cs#L52-L65

2023-04-06 21:11 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryProcessor.cs
> +            CancellationTokenSource serviceCancellationToken = new CancellationTokenSource(ClientTelemetryOptions.ClientTelemetryServiceTimeOut);
Linking service token with processor token.

2023-04-06 21:11 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryProcessor.cs
> +                if (cancellationToken.IsCancellationRequested)
removed cancellation

2023-04-06 21:35 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryProcessor.cs
> +            CancellationTokenSource processorCancelToken)
```suggestion
            CancellationToken processorCancellationToken)
```

2023-04-06 21:36 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryProcessor.cs
> +                using CancellationTokenSource cancellationToken = CancellationTokenSource.CreateLinkedTokenSource(processorCancelToken.Token);
This is not needed because you are not linking 2 tokens with different time

2023-04-06 21:36 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryProcessor.cs
> +                    callback: async (payload) => await this.SendAsync(clientTelemetryInfo.GlobalDatabaseAccountName, payload, cancellationToken.Token));
```suggestion
                    callback: async (payload) => await this.SendAsync(clientTelemetryInfo.GlobalDatabaseAccountName, payload, processorCancellationToken));
```

2023-04-06 21:37 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +                        DefaultTrace.TraceError("Exception while processing the data : {0} with telemetry date as {1}", ex.Message, this.clientTelemetryInfo.DateTimeUtc);
This catch block is not catching any processing error.

2023-04-06 21:43 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +                    throw new TimeoutException($"Processor task with date as {telemetryDate} is cancelled as it did not finish in {ClientTelemetryOptions.ClientTelemetryProcessorTimeOut} milliseconds
```suggestion
                    throw new OperationCanceledException($"Processor task with date as {telemetryDate} is cancelled as it did not finish in {ClientTelemetryOptions.ClientTelemetryProcessorTimeOut} milliseconds.");
```

2023-04-06 21:44 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +                    DefaultTrace.TraceVerbose($"Processor task with date as {telemetryDate} is cancelled as it did not finish in {ClientTelemetryOptions.ClientTelemetryProcessorTimeOut} milliseconds.
```suggestion
                    DefaultTrace.TraceVerbose($"Processor task with date as {telemetryDate} is canceled as it did not finish in {ClientTelemetryOptions.ClientTelemetryProcessorTimeOut} milliseconds.");
```

2023-04-06 21:45 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryOptions.cs
> +        internal static TimeSpan ClientTelemetryProcessorTimeOut = TimeSpan.FromMinutes(5); // 5 minutes
```suggestion
        internal static TimeSpan ClientTelemetryProcessorTimeOut = TimeSpan.FromMinutes(5);
```

2023-04-07 15:46 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +                    DefaultTrace.TraceVerbose($"Processor task with date as {telemetryDate} is canceled as it did not finish in {ClientTelemetryOptions.ClientTelemetryProcessorTimeOut}");
just realized the method takes the timespan as parameter. If we want to use `ClientTelemetryOptions.ClientTelemetryProcessorTimeOut` on the error trace then we need to use it on the Task.Delay and remove it from the parameters, or, change the message to:

```suggestion
                    DefaultTrace.TraceVerbose($"Processor task with date as {telemetryDate} is canceled as it did not finish in {timeout}");
```

2023-04-07 15:46 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +                    throw new OperationCanceledException($"Processor task with date as {telemetryDate} is canceled as it did not finish in {ClientTelemetryOptions.ClientTelemetryProcessorTimeOut}");
Same as the other comment:

```suggestion
                    throw new OperationCanceledException($"Processor task with date as {telemetryDate} is canceled as it did not finish in {timeout}");
```

2023-04-07 15:47 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Telemetry/ClientTelemetryTests.cs
> +            Environment.SetEnvironmentVariable(ClientTelemetryOptions.EnvPropsClientTelemetryEndpoint, "http://dummy.telemetry.endpoint/");
Shouldn't we reset this value after the test is done?

2023-04-07 15:48 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Telemetry/ClientTelemetryTests.cs
> +                await ClientTelemetry.RunProcessorTaskAsync(DateTime.Now.ToString(), processorTask, TimeSpan.FromTicks(1));
```suggestion
                await Assert.ThrowsAsync<OperationCanceledException>(() -> ClientTelemetry.RunProcessorTaskAsync(DateTime.Now.ToString(), processorTask, TimeSpan.FromTicks(1)));
```

This removes the try/catch and all the other Asserts

2023-04-08 11:25 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Telemetry/ClientTelemetryTests.cs
> +            Environment.SetEnvironmentVariable(ClientTelemetryOptions.EnvPropsClientTelemetryEndpoint, "http://dummy.telemetry.endpoint/");
doesn't matter...i need to set this value to pass some validation in client teemetry code. and If I need it in other tests, I always setting it some value.

2023-04-10 13:47 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Telemetry/ClientTelemetryTests.cs
> +            Environment.SetEnvironmentVariable(ClientTelemetryOptions.EnvPropsClientTelemetryEndpoint, "http://dummy.telemetry.endpoint/");
I understand, but from the correctness perspective, this test is setting an Environment variable, which affects all tests that run after it, and you cannot tell which are them, or if any of them, now or in the future, might be affected by this global variable. Shouldn't we reset the variable to the previous state when the test is done? You can read the current value, run the test and on a `finally` clause, set the value to what it was originally. That way the test cleans up after itself and has no posibility of impacting a future test.

2023-04-10 14:49 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Telemetry/ClientTelemetryTests.cs
> +            Environment.SetEnvironmentVariable(ClientTelemetryOptions.EnvPropsClientTelemetryEndpoint, "http://dummy.telemetry.endpoint/");
cleaning up this in test clean up.

2023-04-10 17:21 UTC, ealsur submitted a review, later dismissed

2023-04-10 18:26 UTC, ealsur approved these changes

2023-04-10 19:12 UTC, merged