SummaryDiagnostics: Refactors Code to Remove Dependency of HttpResponseHeadersWrapper to fetch Sub Status Codes
Azure/azure-cosmos-dotnet-v3 pull request #3792
Opened 2023-03-31 20:49 UTC by kundadebdatta

# Pull Request Template

## Description

When trying to log cosmos exception, by doing `cosmosException.ToString()` is causing `IndexOutOfRangeException` and the stack trace points out to `HttpResponseHeadersWrapper` constructor. This PR fixes the bug by removing the dependency of `HttpResponseHeadersWrapper` and fetching the required headers from http response/ content message headers.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## Closing issues

To automatically close an issue: closes #3765

2023-03-31 20:52 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/SummaryDiagnostics.cs
> +                .Content?
The Content will never have this header, this can be simplified, it is just the first case

2023-03-31 20:53 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/SummaryDiagnostics.cs
> +                .Contains(Documents.WFConstants.BackendHeaders.SubStatus))
TryGetValues does the same thing as Contains, you can just use TryGetValues

2023-03-31 20:53 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/SummaryDiagnosticsTests.cs
> +            CosmosClient cosmosClient = TestCommon.CreateCosmosClient(useGateway: false);
```suggestion
            using CosmosClient cosmosClient = TestCommon.CreateCosmosClient(useGateway: false);
```

2023-03-31 20:54 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/SummaryDiagnosticsTests.cs
> +                Container container = cosmosClient.GetContainer(databaseName, containerName);
Simplify by using Guids, no need to set other variables

2023-03-31 20:54 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/SummaryDiagnosticsTests.cs
> +                ItemResponse<dynamic> readResponse = await container.ReadItemAsync<dynamic>(partitionKey, new Cosmos.PartitionKey(partitionKey));
Use Guids, the actual value doesn't matter

2023-03-31 21:04 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/SummaryDiagnostics.cs
> +                .Content?
Thanks for the info. Refactored the code.

2023-03-31 21:04 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/SummaryDiagnostics.cs
> +                .Contains(Documents.WFConstants.BackendHeaders.SubStatus))
Addressed.

2023-03-31 21:05 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/SummaryDiagnosticsTests.cs
> +            CosmosClient cosmosClient = TestCommon.CreateCosmosClient(useGateway: false);
Done.

2023-03-31 21:05 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/SummaryDiagnosticsTests.cs
> +                ItemResponse<dynamic> readResponse = await container.ReadItemAsync<dynamic>(partitionKey, new Cosmos.PartitionKey(partitionKey));
Sure. To make it more cleaner, updated the code with `Guid`.

2023-03-31 21:05 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/SummaryDiagnosticsTests.cs
> +                Container container = cosmosClient.GetContainer(databaseName, containerName);
Done.

2023-03-31 21:07 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/SummaryDiagnosticsTests.cs
> +                ItemResponse<dynamic> readResponse = await container.ReadItemAsync<dynamic>(partitionKey, new Cosmos.PartitionKey(partitionKey));
For partition key, I feel it doesn't matter. Kept the code as is.

2023-03-31 21:14 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/SummaryDiagnostics.cs
> +                    if (!int.TryParse(SummaryDiagnostics.GetSubStatusCodes(httpResponseStatistics),
`SummaryDiagnostics.GetSubStatusCodes(httpResponseStatistics)` can return you comma separated values, in that case this parsing will fail.

2023-03-31 21:15 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/SummaryDiagnostics.cs
> +                        values: out IEnumerable<string> httpResponseHeaderValues) ?
Do we expect multiple "substatuscodes" here? If no. then just get the first value out of this enumerable.

2023-03-31 21:17 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/SummaryDiagnosticsTests.cs
> +        public async Task SummaryDiagnostics_WhenContainerDoesNotExists_ShouldRecordSubStatusCode()
is it `WhenContainerDoesNotExists` or `WhenItemDoesNotExists`?

2023-03-31 21:18 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/SummaryDiagnostics.cs
> +                    if (!int.TryParse(SummaryDiagnostics.GetSubStatusCodes(httpResponseStatistics),
If you look at the [code here](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Headers/HttpResponseHeadersWrapper.cs#L128-L143), this is the exact same way it behaves today. I am just trying to mimic the same behavior.

2023-03-31 21:18 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/SummaryDiagnosticsTests.cs
> +        public async Task SummaryDiagnostics_WhenContainerDoesNotExists_ShouldRecordSubStatusCode()
It's about the container that does not exists.

2023-03-31 21:21 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/SummaryDiagnostics.cs
> +                        values: out IEnumerable<string> httpResponseHeaderValues) ?
Same behavior by looking at the code today. I would be a bit hesitant to change the existing way it behaves.

2023-03-31 21:24 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/SummaryDiagnostics.cs
> +                    if (!int.TryParse(SummaryDiagnostics.GetSubStatusCodes(httpResponseStatistics),
The code which you are referring is generic code for all the keys, but here you are dealing with specific key i.e substatuscode. in that case we should handle it accordingly. 
It might work all the time because we never get comma separated substatuscodes but this code will fail if we start getting it. So, either assume that we are going to get only one substatuscode OR write generic code which can handle comma separated substatuscode also.

2023-03-31 21:27 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/SummaryDiagnosticsTests.cs
> +        public async Task SummaryDiagnostics_WhenContainerDoesNotExists_ShouldRecordSubStatusCode()
So `readItem` will never run because "GetContainer" call will fail because we are trying to get the container which does not exist.

2023-03-31 21:50 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/SummaryDiagnostics.cs
> +                    if (!int.TryParse(SummaryDiagnostics.GetSubStatusCodes(httpResponseStatistics),
Discussed offline. This means our default behavior of handling the sub status code is faulty in nature. I will address this and refactor the code to consider the first one in the list. Thanks for bringing this up!

2023-03-31 21:51 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/SummaryDiagnostics.cs
> +                        values: out IEnumerable<string> httpResponseHeaderValues) ?
Will be addressed along with the previous comment.

2023-04-03 16:05 UTC, ealsur approved these changes

2023-04-03 18:24 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/SummaryDiagnostics.cs
> +                    .TryGetValues(
Use https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Headers/Headers.cs#LL357C31-L357C48

We can probably remove this helper function all together

2023-04-03 18:25 UTC, ealsur requested changes
Simplify by using GetValueOrDefault

2023-04-03 18:29 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/SummaryDiagnostics.cs
> +                    .TryGetValues(
So, I have already explored this option. The `Headers` here is an implementation of `System.Net.Http.Headers.HttpResponseHeaders` which does not have a method `GetValueOrDefault()`.

2023-04-03 18:31 UTC, ealsur approved these changes

2023-04-03 18:41 UTC, kirankumarkolli approved these changes

2023-04-03 18:42 UTC, merged