[Internal] OpenTelemetry: Add Open Telemetry functionality
Azure/azure-cosmos-dotnet-v3 pull request #3801
Opened 2023-04-05 22:38 UTC by aavasthy

# Pull Request Template

## Description
[Feature 3459:](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3459) Adds open telemetry support to the SDK for network level requests for both HTTP and TCP requests.
Second PR for Distributed Tracing changes:

- Update OpentelmetryRecorder and factory for including logic to have a parent Id at operation level
- Add distributed trace id in Diagnostics 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

2023-04-05 22:48 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +            this.activity = new Activity(operationName);
What is the default value of scope? And is it Disposable?

2023-04-05 22:50 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +        public OpenTelemetryCoreRecorder(string operationName)
nit: separate functions with empty lines

2023-04-05 22:52 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +        public OpenTelemetryCoreRecorder(DiagnosticScope scope)
This class has now 3 constructors, which is used when? And would it be better to have a private constructor and static methods with different names? For example: CreateWithDiagnosticScope() or CreateWithActivity(). Particularly the second one (activity) takes a string, it is rather obscure that it ends up creating an Activity instead of a scope

2023-04-05 22:52 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientSideRequestStatisticsTraceDatum.cs
> -
undo this file?

2023-04-06 20:55 UTC, sourabh1007 commented
Can you please give proper title to this PR, operation level Open telemetry is already there. This PR is related to distributed tracing and generating and logging operation level traceid.

2023-04-06 20:56 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
> +                                    trace: trace,
Instead of passing Trace in factory. you can add datum with key vaue pair here.

2023-04-06 20:57 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryAttributeKeys.cs
> +        public const string NetworkLevelPrefix = "Request";
Why are we adding it here? You must be added it already in direct package. please use the same reference here

2023-04-06 20:58 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +        public OpenTelemetryCoreRecorder(DiagnosticScope scope)
Open telemetry Factory is already there to take this decision, which constructor needs to be called. May be adding a proper documentation here would make more sense.

2023-04-06 21:35 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +            else
Isn't this.scope null check required for above if?

2023-04-06 21:37 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +            else
Also all this.scope usages in this file right?

2023-04-06 21:38 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +        public OpenTelemetryCoreRecorder(DiagnosticScope scope)
The three CTOR's contracts are confusing. 
Last one is a union one.

2023-04-09 22:16 UTC, aavasthy commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryAttributeKeys.cs
> +        public const string NetworkLevelPrefix = "Request";
In Direct Package, NetworkLevelPrefix is not part of a constants file. It is being used in OpenTelemetryRecorderFactory
https://msdata.visualstudio.com/CosmosDB/_git/CosmosDB?path=/Product/Microsoft.Azure.Documents/SharedFiles/Telemetry/OpenTelemetryRecorderFactory.cs&_a=contents&version=GBmaster

2023-04-09 22:41 UTC, aavasthy commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +            this.activity = new Activity(operationName);
Default value is null and it is disposable. The call to openTelemetryRecorder is within using block so it will get disposed.
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/789f70183a2323259d6518eb7d463aca38f4ae08/Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs#L492

2023-04-09 23:51 UTC, aavasthy commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +        public OpenTelemetryCoreRecorder(string operationName)
updated

2023-04-14 17:21 UTC, aavasthy commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +        public OpenTelemetryCoreRecorder(DiagnosticScope scope)
Added comments for better understanding of the use case of each constructor. The three constructors are being used for three different scenarios depending on which listener is available.

2023-04-18 23:37 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryRecorderFactory.cs
> +                trace.AddDatum("DistributedTraceId", Activity.Current?.Id);
Shouldn't it be just "TraceId"

2023-04-18 23:40 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/DistributedTracingOTelTests.cs
> +        public async Task OperationScopeEnabled(bool enableDistributingTracing, bool enableActivitySource, string source, int activityCount)
if enabledistributingtracing, enableActivitySource, activitycount are not changing in Datarow, please hardcode it in the test itself.

2023-04-18 23:42 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/DistributedTracingOTelTests.cs
> +    public sealed class DistributedTracingOTelTests
This should cover all the scenarios like what if operation and request listeners are subscribed together or nothing is subscribed.

2023-04-18 23:43 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/DistributedTracingOTelTests.cs
> +                Assert.AreEqual(source, CustomOtelExporter.CollectedActivities.FirstOrDefault().Source.Name);
please assert on header also which we are setting for context propagation.

2023-04-18 23:45 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/BenchmarkConfig.cs
> +        public bool EnableDistributedTracing { get; set; } = true;
by default set it false.

2023-04-18 23:47 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
> +                                    trace: trace,
for any scenario, activity instance should be present here. because we are disposing it with recorder.

2023-04-20 17:17 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +            this.activity = new Activity(operationName);
If the default value is null, then shouldn't we check before using it? On the Dispose method in this class, there is no guard against it being null

2023-04-20 17:20 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +        public OpenTelemetryCoreRecorder(DiagnosticScope scope)
One pattern to make it easier on this cases is making the constructors private and have X static methods with descriptive names.

For example:

```
public static OpenTelemetryCoreRecorder CreateForOneScenario(some parameters)

public static OpenTelemetryCoreRecorder CreateForAnotherScenario(some other parameters)

```

That way it is clear for the consumer which to use.

Last constructor seems to allow all cases though? Is that correct?

2023-04-24 01:22 UTC, aavasthy commented on Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
> +                                    trace: trace,
if it is kept outside in clientContextCore then IsDistributedTracingEnabled check would need to be added explicitly. But currently it is added in OpenTelemetryRecorderFactory for scenario where EnableDistributedTracing flag is on and there is already a parent activity but no listeners on network or operation level.

2023-04-24 07:18 UTC, aavasthy commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/DistributedTracingOTelTests.cs
> +                Assert.AreEqual(source, CustomOtelExporter.CollectedActivities.FirstOrDefault().Source.Name);
updated and added tests for asserting header for gateway as well as direct mode.

2023-04-24 07:19 UTC, aavasthy commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/DistributedTracingOTelTests.cs
> +    public sealed class DistributedTracingOTelTests
Updated tests and covering scenarios with different sources.

2023-04-24 07:52 UTC, aavasthy commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +        public OpenTelemetryCoreRecorder(DiagnosticScope scope)
Added 3 new public static methods for each constructor with description. The last constructor doesn't allow all cases, the parameters in last constructor are not optional.

2023-04-24 08:04 UTC, aavasthy commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +            else
Diagnostic Scope is a struct and wouldn't be null.

2023-04-24 08:20 UTC, aavasthy commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +            this.activity = new Activity(operationName);
Updated the above comment. DiagnosticScope is not a class but a struct so it would not be null and would have a valid instance. So, default(DiagnosticScope) would return an instance of DiagnosticScope with '_activityAdapter':null, '_suppressedNestedClientActivities': false and 'IsEnabled': false.
https://github.com/Azure/azure-sdk-for-net/blob/dbd2b6d7b1db29e109255c1ddd2d9b284eff5196/sdk/core/Azure.Core/src/Shared/DiagnosticScope.cs#L34

DiagnosticScope dispose will dispose 'ActivityAdapter' object and will call 'Activity.Current' to end the activity and stop tracing https://github.com/Azure/azure-sdk-for-net/blob/dbd2b6d7b1db29e109255c1ddd2d9b284eff5196/sdk/core/Azure.Core/src/Shared/DiagnosticScope.cs#L398

2023-04-24 15:12 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +        /// Used for creating parent activity in scenario where there are listeners at operation level
If there are present at network level, would it make a difference? My understanding is no, from reading this, but wanted to confirm

2023-04-24 15:14 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +        public static OpenTelemetryCoreRecorder CreateNetworkLevelParentActivity(DiagnosticScope scope)
This is the parent scope for network? If yes, can we rename the variable accordingly to differentiate from other `scope` in the other methods?

2023-04-24 15:16 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +        public static OpenTelemetryCoreRecorder CreateParentActivity(string operation)
Nit: for consistency, this is the operation name? In the other method we used `operationName`

2023-04-24 16:18 UTC, aavasthy commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +        /// Used for creating parent activity in scenario where there are listeners at operation level
No it would not make a difference in this case if in there are listeners at network level or not. We are creating an activity here as there is listener at operation level.

2023-04-24 19:51 UTC, aavasthy commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +        DiagnosticScope scope,
updated

2023-04-24 19:53 UTC, aavasthy commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +        public static OpenTelemetryCoreRecorder CreateParentActivity(string operation)
updated

2023-04-24 20:24 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryRecorderFactory.cs
> +                trace.AddDatum("DistributedTraceId", Activity.Current?.Id);
Add only trace id in the request diagnostics. Instead of whole activity id.

2023-04-24 20:32 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/TestCommon.cs
> +                cosmosClientBuilder = cosmosClientBuilder.WithHttpClientFactory(httpClientFactory);
You can use the `customizeClientBuilder` parameter for this.

2023-04-24 20:34 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +        DiagnosticScope operationScope,
nit: padding, the parameters are normally padded in

2023-04-24 20:36 UTC, ealsur submitted a review, later dismissed

2023-04-24 23:28 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryRecorderFactory.cs
> +                    DiagnosticScope requestScope = LazyScopeFactory.Value.CreateScope(name: $"{OpenTelemetryAttributeKeys.NetworkLevelPrefix}.{operationName}");
Can you please expand more context? 
Scope is changing from operation -> NWLevel and its unclear to me.

2023-04-24 23:43 UTC, aavasthy commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryRecorderFactory.cs
> +                    DiagnosticScope requestScope = LazyScopeFactory.Value.CreateScope(name: $"{OpenTelemetryAttributeKeys.NetworkLevelPrefix}.{operationName}");
The main aim is to have a parent activity created in all scenarios.
The first scope here checks for listeners at Operation Level. If there are listeners at operation level then scope is enabled and activity is created.
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/2837201bf9fc7c55c8a3177f6dd57306eb48ccc6/Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryRecorderFactory.cs#L40

The second check is to see if there isn't any existing parent id(no activity created by the client) then check if there is a listener at Network level. If there is a source at network level then create a dummy scope that creates a parent id.
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/2837201bf9fc7c55c8a3177f6dd57306eb48ccc6/Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryRecorderFactory.cs#L58

And if there is no listener at operation and network level then create a dummy activity with poperationName that acts as a parent Activity.
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/2837201bf9fc7c55c8a3177f6dd57306eb48ccc6/Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryRecorderFactory.cs#L60

2023-04-25 08:35 UTC, aavasthy commented
@msftbot make sure to wait for @sourabh1007 and @kirankumarkolli to approve

2023-04-25 15:38 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryRecorderFactory.cs
> +                    DiagnosticScope requestScope = LazyScopeFactory.Value.CreateScope(name: $"{OpenTelemetryAttributeKeys.NetworkLevelPrefix}.{operationName}");
> second check is to see if there isn't any existing parent id(no activity created by the client) then check if there is a listener at Network level.

Do this check needs to be conditional on no-activity?

2023-05-09 08:51 UTC, aavasthy commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/TestCommon.cs
> +                cosmosClientBuilder = cosmosClientBuilder.WithHttpClientFactory(httpClientFactory);
Updated and now using customizeClientBuilder.

2023-05-09 08:52 UTC, aavasthy commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +        DiagnosticScope operationScope,
updated

2023-05-09 08:54 UTC, aavasthy commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryRecorderFactory.cs
> +                    DiagnosticScope requestScope = LazyScopeFactory.Value.CreateScope(name: $"{OpenTelemetryAttributeKeys.NetworkLevelPrefix}.{operationName}");
Yes we only generate a network level parent activity if there isn't an existing parent activity. The whole point is to have a parentActivity at root level.

2023-05-09 08:55 UTC, aavasthy commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryRecorderFactory.cs
> +                trace.AddDatum("DistributedTraceId", Activity.Current?.Id);
Updated

2023-05-12 18:58 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqTranslationWithCustomSerializerBaseline.TestMemberInitializer.xml
> +  <Result>
This file might not be needed, doesn't sound like you are changing anything that should affect it, why is it being generated I don't know though, but doesn't sound like it should be being pushed.

2023-05-12 18:59 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/DistributedTracingOTelTests.cs
> +                await this.database.DeleteStreamAsync();
Please use this.TestCleanUp, otherwise you are not disposing the underlying client.

2023-05-12 19:02 UTC, ealsur requested changes
Waiting on the tests cleanup

2023-05-12 19:02 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/BaseCosmosClientHelper.cs
> +        public async Task TestInit(
Isn't distributed tracing available in `CosmosClientBuilder.WithDistributedTracing`? You don't need to add this method, you can simply do:

```
customizeClientBuilder: builder => builder.WithDistributedTracing(true)
```

WIth the existing TestInit

2023-05-13 02:02 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +                this.activity?.Stop();
this.activity is set only in else case right? 

One generic alternative might be to Stop() conditional on JUST this.activity set.

2023-05-13 02:10 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryRecorderFactory.cs
> +                    openTelemetryRecorder = requestScope.IsEnabled ? OpenTelemetryCoreRecorder.CreateNetworkLevelParentActivity(networkScope: requestScope) : OpenTelemetryCoreRecorder.CreateParentAct
Is namespace not needed for activity creation?

2023-05-14 22:17 UTC, aavasthy commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/DistributedTracingOTelTests.cs
> +                await this.database.DeleteStreamAsync();
updated

2023-05-17 08:47 UTC, aavasthy commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/BaseCosmosClientHelper.cs
> +        public async Task TestInit(
Updated

2023-05-19 20:44 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/DistributedTracingOTelTests.cs
> +            await base.TestInit();
Inside each test, you are creating a custom client, and also a database. What is the point then to call `base.TestInit` if nothing the TestInit is doing is something you are taking advantage of?

2023-05-19 20:45 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/DistributedTracingOTelTests.cs
> +                this.cosmosClientBuilder = this.cosmosClientBuilder
Why not use instead: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/BaseCosmosClientHelper.cs#L38-L48

```
await base.TestInit(
  validateSinglePartitionKeyRangeCacheCall: false,
  customizeClientBuilder : (builder) => builder.WithDistributedTracing(true));
```

It sets the client, and also creates the database.

2023-05-19 20:45 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/DistributedTracingOTelTests.cs
> +                this.cosmosClientBuilder = this.cosmosClientBuilder
Same here and everywhere you are creating a custom client

2023-05-19 20:54 UTC, kirankumarkolli submitted a review, later dismissed

2023-05-19 21:12 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/DistributedTracingOTelTests.cs
> +                this.cosmosClientBuilder = this.cosmosClientBuilder
```
await base.TestInit(
  validateSinglePartitionKeyRangeCacheCall: false,
  customizeClientBuilder : (builder) => builder
      .WithHttpClientFactory(() => new HttpClient(httpClientHandlerHelper))
      .WithDistributedTracing(true));
```

2023-05-19 21:14 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/DistributedTracingOTelTests.cs
> +                this.SetClient(useGateway
Replace with:

```
if (useGateway)
{
await base.TestInit(
  validateSinglePartitionKeyRangeCacheCall: false,
  customizeClientBuilder : (builder) => builder
     .WithConnectionModeGateway()
     .WithDistributedTracing(true));
}
else
{
await base.TestInit(
  validateSinglePartitionKeyRangeCacheCall: false,
  customizeClientBuilder : (builder) => builder
     .WithDistributedTracing(true));
}
```

2023-05-25 03:14 UTC, aavasthy commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/DistributedTracingOTelTests.cs
> +                this.SetClient(useGateway
Updated

2023-05-25 03:14 UTC, aavasthy commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/DistributedTracingOTelTests.cs
> +                this.cosmosClientBuilder = this.cosmosClientBuilder
updated

2023-05-25 03:14 UTC, aavasthy commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/DistributedTracingOTelTests.cs
> +                this.cosmosClientBuilder = this.cosmosClientBuilder
Updated

2023-05-25 03:15 UTC, aavasthy commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/DistributedTracingOTelTests.cs
> +            await base.TestInit();
updated and using the existing TestInit() now

2023-05-25 03:38 UTC, aavasthy commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +                this.activity?.Stop();
discussed offline

2023-05-25 03:38 UTC, aavasthy commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryRecorderFactory.cs
> +                    openTelemetryRecorder = requestScope.IsEnabled ? OpenTelemetryCoreRecorder.CreateNetworkLevelParentActivity(networkScope: requestScope) : OpenTelemetryCoreRecorder.CreateParentAct
discussed offline

2023-05-26 20:43 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryRecorderFactory.cs
> +                trace.AddDatum("DistributedTraceId", Activity.Current?.TraceId);
Is it explicitly needed?
Our activityid's capture down steam mgiht alreay have this context right?

2023-05-26 20:44 UTC, aavasthy commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryRecorderFactory.cs
> +                trace.AddDatum("DistributedTraceId", Activity.Current?.TraceId);
This gets added to the Diagnostic Log. We currently don't have DistributedTraceId in that.

2023-05-30 18:53 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/BaseCosmosClientHelper.cs
> +            this.cosmosClient = null;
nit: Why is this needed?

2023-05-31 15:38 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryRecorderFactory.cs
> +                trace.AddDatum("DistributedTraceId", Activity.Current?.TraceId);
@kirankumarkolli  I don't thing we capture `Activity.Current?.TraceId` anywhere except this place. if you think that something like this already exists and should be addressed, please provide some context, maybe we can address it as part of next PR.

2023-05-31 15:45 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/DistributedTracingOTelTests.cs
> +    public sealed class DistributedTracingOTelTests : BaseCosmosClientHelper
Please add few more assertions:
1. Assert if we have traceid in header (Direct and TCP) both if this feature is enable. (like we have in Direct package)
2. Assert Whatever `traceid `we are putting in request diagnostics is same as what we are sending in headers.
3. Assert when we are creating dummy activity at operation level. It doesn't have any attribute. Ideally, all the attributes should be null.

We should assert everything what we expect from a feature and what we don't expect. It will be a good reference point for somebody who wants to understand the feature.

2023-05-31 15:51 UTC, aavasthy commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
> +        private readonly Documents.OperationType operationType = Documents.OperationType.Invalid;
OperationType doesn't get set for scenarios when there is no subscription at operation level.
Documents.OperationType operationType = Documents.OperationType.Invalid has been kept as invalid as the default. OperationType is non-nullable field.

2023-06-01 07:46 UTC, aavasthy commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/DistributedTracingOTelTests.cs
> +    public sealed class DistributedTracingOTelTests : BaseCosmosClientHelper
- Assert if we have traceid in header (Direct and TCP) both if this feature is enable. (like we have in Direct package)
The existing test cases are already asserting that. First and second test case already assert TraceId is present in header in direct and gateway mode.
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/c217a21b5e5e3d720f8f3a631f929895ccd43d4b/Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/DistributedTracingOTelTests.cs#L65
- Assert Whatever traceid we are putting in request diagnostics is same as what we are sending in headers.
Currently it is asserting that generated activity traceId is same as the diagnostics logs and same as reesponse  traceid.
- Assert when we are creating dummy activity at operation level. It doesn't have any attribute. Ideally, all the attributes should be null.
For dummy activity created via network scope it has default tags which gets added when scope is created. For summy activty created via Activity.Start(), CustomOtelExporter doesn't capture those type of activities.

2023-06-06 16:28 UTC, sourabh1007 approved these changes
LGTM.

2023-06-06 16:32 UTC, aavasthy commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/BaseCosmosClientHelper.cs
> +            this.cosmosClient = null;
removed as part of code cleanup

2023-06-06 18:54 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/DistributedTracingOTelTests.cs
> +        [TestMethod]
nit: If you are using DataRow, doesn't this need to be a DataTestMethod?

Prefer to add names to DataRows so when the test fails, it is clear what was being tested, for example:

```
[DataRow(param1, param2,...., DisplayName = "Checks for scenario1")]
[DataRow(param1, param2,...., DisplayName = "Checks for scenario2")]
```

2023-06-06 18:55 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/DistributedTracingOTelTests.cs
> +        [DataRow(false, true)]
nit: Consider adding `DisplayName` to the DataRow so it's a bit more clear what the test case is when it fails

2023-06-06 18:55 UTC, ealsur submitted a review, later dismissed

2023-06-06 19:00 UTC, sourabh1007 approved these changes

2023-06-06 20:08 UTC, kirankumarkolli submitted a review, later dismissed

2023-06-06 20:48 UTC, aavasthy commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/DistributedTracingOTelTests.cs
> +        [TestMethod]
updated

2023-06-07 00:26 UTC, sourabh1007 approved these changes

2023-06-07 16:15 UTC, merged