[Internal] Upgrade Resiliency: Adds Replica Health State Diagnostics.
Azure/azure-cosmos-dotnet-v3 pull request #3835
Opened 2023-05-01 22:10 UTC by kundadebdatta

# Pull Request Template

## Description

Adds the replica health statuses into the cosmos sdk diagnostics JSON. The updated diagnostics will look similar to the below.

```
"RetryAfterInMs": null,
"BELatencyInMs": "0.465",
"ReplicaHealthStatuses": [
    "14338:Connected",
    "15877:Connected",
    "14790:Connected",
    "14338:Unknown"
],
"transportRequestTimeline": {
    "requestTimeline": [
        {
            "event": "Created",
            "startTimeUtc": "2023-01-19T01:12:03.1785624Z",
            "durationInMs": 5.6755
        }
    ]
}
```

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## Closing issues

To automatically close an issue: closes #IssueNumber

2023-06-06 19:49 UTC, philipthomas-MSFT approved these changes
LGTM

2023-06-06 22:08 UTC, philipthomas-MSFT submitted a review, later dismissed
approving again but talked with Deb offline on the change to 5 seconds.

2023-06-08 22:59 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs
> +        private const int defaultRequestTimeout = 5;
Can you explain the motivation for this in the PR description? Backend request timeout is 5 seconds - using client-side request timeout of 5 seconds as well by default means we can fail even when backend process request successfully. For queries, stored proc executions and even point operations with really large documents that seems risky?

2023-06-08 23:11 UTC, xinlian12 commented on Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs
> +        private const int defaultRequestTimeout = 5;
i think this maps to the transient timeout we used in java SDK which is 5s by default

2023-06-08 23:15 UTC, xinlian12 submitted a review, later dismissed
LGTM, thanks

2023-06-08 23:16 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs
> +        private const int defaultRequestTimeout = 5;
But we even know of cases where cx had to increase it when backend took regularly close to 5s - why move into the same problem in .Net - especially because this can be considered a breaking change?

2023-06-08 23:30 UTC, xinlian12 commented on Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs
> +        private const int defaultRequestTimeout = 5;
i think it is based on during upgrades, we observed that in .Net the maxLatency can go up to 10s because of the request timeout config @kundadebdatta please correct me here for the reasoning. But if the 10s is particularly chosen due to the above scenarios, then yes we should still keep as 10s.

2023-06-08 23:33 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs
> +        private const int defaultRequestTimeout = 5;
What about using 6 seconds (or maybe 5.5 seocnds) - still some buffer when backend takes 5 seconds - but reduces the tail latency?

2023-06-08 23:34 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs
> +        private const int defaultRequestTimeout = 5;
And please call this change out for Gateway teams - especially on Mongo (where they changes response size to up to 16 MB they might need to tune this)

2023-06-08 23:35 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs
> +        private const int defaultRequestTimeout = 5;
Sounds like a good proposal. I agree to push it to '6` seconds, by keeping a second aside as a buffer.

2023-06-08 23:58 UTC, FabianMeiswinkel approved these changes
LGTM when changing the request timeout to 6 seconds

2023-06-09 00:23 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs
> +        private const int defaultRequestTimeout = 5;
https://msdata.visualstudio.com/CosmosDB/_git/CosmosDB?path=/Product/Cosmos/Compute/Host/TenantClientResolver.cs&version=GBmaster&line=509&lineEnd=510&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents

Its explicitly configured and default is not used.

2023-06-09 00:30 UTC, kirankumarkolli requested changes
Changes LGTM
Let's please split it into multiple PRs

2023-06-09 18:28 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs
> +        private const int defaultRequestTimeout = 5;
Broken this PR into 2 parts. The second part can be [found here](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3902).

2023-06-09 21:56 UTC, FabianMeiswinkel approved these changes
LGTM

2023-06-09 22:04 UTC, xinlian12 approved these changes
LGTM, thanks

2023-06-10 02:07 UTC, kirankumarkolli approved these changes

2023-06-10 04:39 UTC, merged