Integrated cache: Add BypassIntegratedCache to DedicatedGatewayRequestOptions
Azure/azure-cosmos-dotnet-v3 pull request #3836
Opened 2023-05-03 20:29 UTC by jiajunpeng-msft

# Pull Request Template

## Description

This is to add a new DedicatedGatewayRequestOption "BypassIntegratedCache".

Currently, integrated cache is used by default for Dedicated Gateway. Customers cannot skip cache for particular requests or data unless they shift to multi-tenant Gateway,which will lose the benefits of Dedicated Gateway.

For customers to have more control over integrated cache, we're introducing a new "RequestOption" called "BypassIntegratedCache". This option will allow the customer to decide whether to use integrated cache for each request or not. If this value is set to true, the item/query will be served from backend and won't be cached in Dedicated Gateway.

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #IssueNumber

2023-05-03 22:36 UTC, ealsur commented
@msftbot wait for @kirankumarkolli to approve, this PR modifies public API surface

2023-05-05 14:13 UTC, ealsur requested changes
Waiting on confirmation wheter this is preview or GA

2023-05-05 14:13 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Settings/DedicatedGatewayRequestOptions.cs
> +        public bool? BypassIntegratedCache { get; set; }
If this is for Public Preview, it should not be public, it should be conditionally public. For example: 
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/17203a5966e906e0d66d52a95cf4d482add3c51e/Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs#L1018-L1023

Or is this already GAed?

Is this already planned to be added to other SDKs?

2023-05-11 14:26 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Settings/DedicatedGatewayRequestOptions.cs
> +        public bool? BypassIntegratedCache { get; set; }
Which SDK is it on is orthogonal. Is this feature GA? Or are you introducing it for users to test it (public preview)?

2023-05-11 22:26 UTC, jiajunpeng-msft commented on Microsoft.Azure.Cosmos/src/Resource/Settings/DedicatedGatewayRequestOptions.cs
> +        public bool? BypassIntegratedCache { get; set; }
After discussed with my manager, we decided to push this under public preview. Will update the PR soon. Previously we were thinking to directly GA this feature as this is a small change but feels like under public preview is safer.

2023-05-17 13:31 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Settings/DedicatedGatewayRequestOptions.cs
> +            if (dedicatedGatewayRequestOptions?.BypassIntegratedCache != null)
This is a `bool?` the correct way would be to use HasValue to check if it has been set, and Value to extract the value and compare if it's true.

2023-05-17 13:33 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Settings/DedicatedGatewayRequestOptions.cs
> +            if (dedicatedGatewayRequestOptions?.BypassIntegratedCache != null)
Please add tests to confirm the header is set only when the property is set to True, and not when it's not set or set to False

2023-05-18 01:15 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Settings/DedicatedGatewayRequestOptions.cs
> +        /// Gets or sets if bypass the integrated cache or not associated with the request in the Azure CosmosDB service.
Please expand with more context on what it does if possible, with an example. 
At-least we need to cover that it doesn't server from cache and also the response is also not cached.

2023-05-18 20:58 UTC, jiajunpeng-msft commented on Microsoft.Azure.Cosmos/src/Resource/Settings/DedicatedGatewayRequestOptions.cs
> +            if (dedicatedGatewayRequestOptions?.BypassIntegratedCache != null)
Updated.

2023-05-18 20:59 UTC, jiajunpeng-msft commented on Microsoft.Azure.Cosmos/src/Resource/Settings/DedicatedGatewayRequestOptions.cs
> +        /// Gets or sets if bypass the integrated cache or not associated with the request in the Azure CosmosDB service.
Updated.

2023-05-22 15:28 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos.Encryption.Custom/tests/Microsoft.Azure.Cosmos.Encryption.Custom.Tests/Contracts/DotNetSDKEncryptionCustomAPI.json
> +          "Attributes": [
Does this PR includes change n encryption project also? Please revert this file if not.

2023-05-22 21:06 UTC, jiajunpeng-msft commented on Microsoft.Azure.Cosmos.Encryption.Custom/tests/Microsoft.Azure.Cosmos.Encryption.Custom.Tests/Contracts/DotNetSDKEncryptionCustomAPI.json
> +          "Attributes": [
Reverted.

2023-05-23 15:27 UTC, ealsur approved these changes

2023-05-25 22:23 UTC, kirankumarkolli approved these changes

2023-05-31 16:12 UTC, merged