Benchmarking: Adds use of ARM Templates for benchmarking
Azure/azure-cosmos-dotnet-v3 pull request #3838
Opened 2023-05-08 20:52 UTC by NaluTripician

# Pull Request Template

## Description

Adds use of ARM templates for benchmarking

## Type of change

Please delete options that are not relevant.

- [] New feature (non-breaking change which adds functionality)
- [] This change requires a documentation update

2023-05-08 21:20 UTC, ealsur commented on Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/ARMTemplate/README.md
> +[ARM Templates](https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/) makes executing the Azure Cosmos DB SDK Benchmark extremely easy, with very few steps involved, and it's mor
```suggestion
[ARM Templates](https://learn.microsoft.com/azure/azure-resource-manager/templates/) makes executing the Azure Cosmos DB SDK Benchmark extremely easy, with very few steps involved, and it's more cost-effective than using Virtual Machines for burst or single-use scenarios. Plus, it lets you test and evaluate performance quickly on multiple resource (CPU/RAM) configurations and across multiple Azure regions seamlessly.
```

2023-05-08 21:25 UTC, ealsur commented on Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/ARMTemplate/README.md
> +For a complete reference of options, please visit the [official Azure container instance ARM Template refrence](https://learn.microsoft.com/en-us/azure/templates/microsoft.containerinstance/container
This paragraph might not apply?

2023-05-08 21:26 UTC, ealsur commented on Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/ARMTemplate/README.md
> +We'll be using [Azure CLI](https://docs.microsoft.com/cli/azure/install-azure-cli?view=azure-cli-latest) to create the Azure Container Instance and execute the YAML file. Azure CLI is cross-platform.
This is also not valid, we are not using COntainer Instances nor YAML files

2023-05-08 21:28 UTC, ealsur commented on Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/ARMTemplate/README.md
> +### Step 4 - Create Respurce Group
Is creating a Resource Group required with the ARM template or is the ARM template creating the Resource Group?

2023-05-08 21:29 UTC, ealsur commented on Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/ARMTemplate/README.md
> +1. It will create a Linux container named `cosmosdbsdkperf` and provision an image with NET Core inside an instance with the configured CPU and RAM.
```suggestion
1. It will create a Linux container named `cosmosdbsdkperf` and provision an image with NET 6 inside an instance with the configured CPU and RAM.
```

2023-05-08 21:34 UTC, ealsur requested changes
See text comments, can we make the experience a 1 click like "Deploy To Azure"?

2023-05-08 21:34 UTC, ealsur commented on Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/ARMTemplate/README.md
> +az deployment group create --resource-group <your-resource-group> --template-file benchmarkTemplate.json --parameters parameters.json
Is there an alternative to doing an ARM deployment without the Azure CLI? (for example, on the Portal)

I remember there used to be a way to do on-click, see the button on https://github.com/ealsur/serverlessnotifications, there is a Deploy To Azure button and Visualize. And the folder has 2 json files:

![image](https://user-images.githubusercontent.com/1633401/236939967-9f8c0500-48ed-4107-b33c-cec63cdcae94.png)

2023-05-08 21:50 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/ARMTemplate/parameters.json
> +      "value": "100000"
100K will burn lots of money. Lets make it prompt and CX choose.

2023-05-08 21:53 UTC, NaluTripician commented on Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/ARMTemplate/README.md
> +az deployment group create --resource-group <your-resource-group> --template-file benchmarkTemplate.json --parameters parameters.json
Yes, you can also deploy using the portal. Is that preferable?

2023-05-08 21:54 UTC, NaluTripician commented on Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/ARMTemplate/parameters.json
> +      "value": "100000"
100K was the default for the Container Instance. I will make this a required choice for the CX

2023-05-09 17:06 UTC, ealsur commented on Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/ARMTemplate/parameters.json
> +{
This file is needed only if they use the CLI, if we decide to have both documentations, keep it, if not, remove it?

2023-05-09 17:08 UTC, ealsur commented on Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/ARMTemplate/benchmarkTemplate.json
> +    "CLEANUPFINISH": {
Please review the casing of all parameters, otherwise on the UI in the Portal they look completely different:

![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/1633401/434edb97-1963-46b2-9f0d-ce4693851a6b)

2023-05-10 15:04 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/ARMTemplate/README.md
> +[![Deploy to Azure](https://aka.ms/deploytoazurebutton)](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fazure-cosmos-dotnet-v3%2Fmaster%2FAR
Is there any prerequisite or specific permission required to access this? or it should work for everybody?

2023-05-10 15:07 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/ARMTemplate/README.md
> +Please populate the `ENDPOINT` and `KEY` for your Azure Cosmos DB account. You can [obtain these from the Azure Portal or through CLI](https://learn.microsoft.com/azure/cosmos-db/secure-access-to-dat
do I need to login into the container to update this config. Can you please provide the steps to do that. It might be straightforward but for a new person, it can be confusing.

2023-05-10 15:47 UTC, simplynaveen20 reviewed
We have single place for benchmarking Azure databases https://github.com/azure/azure-db-benchmarking , can this go there, easier for internal user and customer to discover .

2023-05-10 15:47 UTC, simplynaveen20 commented on Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/ARMTemplate/README.md
> +![Benchmark results](./arm3.png)
Do we have logs for periodic latency , and what max percentile we are measuring ?

2023-05-10 15:47 UTC, simplynaveen20 commented on Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/ARMTemplate/README.md
> +[ARM Templates](https://learn.microsoft.com/azure/azure-resource-manager/templates/) makes executing the Azure Cosmos DB SDK Benchmark extremely easy, with very few steps involved, and it's more cost
Does this support multiple machine run ?
What max throughput this can reach ?

2023-05-10 15:47 UTC, simplynaveen20 commented on Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/ARMTemplate/README.md
> +[ARM Templates](https://learn.microsoft.com/azure/azure-resource-manager/templates/) makes executing the Azure Cosmos DB SDK Benchmark extremely easy, with very few steps involved, and it's more cost
What is the benefit using container , using VM instead would help in scaling this solution for multiple machine going forward.
Also this is benchmarking with predefined load, so it would be more cost effective to fine tune and use VM , if cost is the concern ?

2023-05-10 16:59 UTC, RaviTella commented on Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/ARMTemplate/README.md
> +[ARM Templates](https://learn.microsoft.com/azure/azure-resource-manager/templates/) makes executing the Azure Cosmos DB SDK Benchmark extremely easy, with very few steps involved, and it's more cost
+1 
Multiple clients and higher RPS will be needed for some validations.

2023-05-10 20:33 UTC, NaluTripician commented on Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/ARMTemplate/README.md
> +[![Deploy to Azure](https://aka.ms/deploytoazurebutton)](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fazure-cosmos-dotnet-v3%2Fmaster%2FAR
This should work for anyone as long as they have an Azure account

2023-05-10 20:35 UTC, NaluTripician commented on Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/ARMTemplate/benchmarkTemplate.json
> +    "cpuCores": {
Will add all other config options.

2023-05-10 21:28 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/ARMTemplate/README.md
> +[ARM Templates](https://learn.microsoft.com/azure/azure-resource-manager/templates/) makes executing the Azure Cosmos DB SDK Benchmark extremely easy, with very few steps involved, and it's more cost
ACI do support multi-instance and template can be modified to support #instances/scale-factor. 

>What max throughput this can reach?
Similar to VM based on the resourcing given. 
Currently on a 4 vCore VM our benchmark is getting close to 12-13K RPS (Reads)

2023-05-10 21:35 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/ARMTemplate/README.md
> +[ARM Templates](https://learn.microsoft.com/azure/azure-resource-manager/templates/) makes executing the Azure Cosmos DB SDK Benchmark extremely easy, with very few steps involved, and it's more cost
In general ACI do cost more than bare bone VM, if cost is a concern then we can move to VM's

2023-05-24 15:06 UTC, ealsur commented on Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/ARMTemplate/README.md
> +Just click in the Deploy to **Azure button** and it will guide you into automatically running the benchmarking.
Nit: 
```suggestion
Just click in the **Deploy to Azure button** and it will guide you into automatically running the benchmarking.
```

2023-05-24 15:09 UTC, ealsur commented on Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/ARMTemplate/README.md
> +Additionally, the file lets you customize the size of the instance, which you can make as similar as possible to the instance you will be running in production to simulate results.
Think it like you were just reading this Deploy with 1 click section: what file are you talking about?

2023-05-24 17:57 UTC, NaluTripician commented
@msftbot do not merge until @kirankumarkolli approves.

2023-05-24 18:10 UTC, ealsur approved these changes

2023-05-24 23:52 UTC, kirankumarkolli approved these changes

2023-05-25 15:55 UTC, NaluTripician commented
@msftbot forget everything I just told you

2023-05-25 15:55 UTC, merged