OperationName fix
Azure/azure-cosmos-dotnet-v3 pull request #3845
Opened 2023-05-11 19:14 UTC by sourabh1007

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Include samples if adding new API, and include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #IssueNumber

2023-05-11 22:25 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryRecorderFactory.cs
> +                    .CreateScope(name: operationName,
Namespace now had OperationPrefix. 
Can you please explain how it show-up in E2E experiences and why this change is needed?

2023-05-11 22:28 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/AssertActivity.cs
> +            if(!activity.Source.Name.Contains("Operation"))
Is EndsWith more constraint?

2023-05-13 11:27 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryRecorderFactory.cs
> +                    .CreateScope(name: operationName,
updated PR description

2023-05-15 18:12 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/CustomListener.cs
> +                "rntbd.sub_status_code",
nit: Is `rntbd` something we are ok from the naming perspective to be made public? What does it mean for the customer?

2023-05-15 21:39 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/CustomListener.cs
> +                "rntbd.sub_status_code",
So that is not public then? It will not appear in AI?

2023-05-16 22:08 UTC, kirankumarkolli submitted a review, later dismissed

2023-05-17 13:37 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/CustomListener.cs
> +                "rntbd.sub_status_code",
Not even in the custom properties?

2023-05-17 16:21 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/CustomListener.cs
> +                "rntbd.sub_status_code",
My question is the name. `rntbd`. Let's say we give the option to include Network activities, they will then start to see `rntbd`, even if we add documentation, isn't the name obscure and around a very internal concept that users would not understand? Why not use `tcp`? The problem with leaving `rntbd` is that once we add the configuration, we won't rethink the name or changing the name afterwards is costlier than now?

2023-05-17 16:28 UTC, ealsur requested changes
Holding off until name clarification

2023-05-17 18:38 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/CustomListener.cs
> +                "rntbd.sub_status_code",
Taking this feedback, this needs to be made in Direct package. Updated my current active PR in direct package with this change. After next Direct pkg upgrade, it should reflect here

2023-05-17 19:52 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/CustomListener.cs
> +                "rntbd.sub_status_code",
Should we then remove these from the list?

2023-05-17 20:15 UTC, ealsur approved these changes

2023-05-17 20:54 UTC, kirankumarkolli approved these changes

2023-05-17 20:59 UTC, merged