Documentation: Linking limit documentation to Container.CreateTransactionalBatch(Par…
Azure/azure-cosmos-dotnet-v3 pull request #3860
Opened 2023-05-18 19:50 UTC by rinatmini

…titionKey) method

# Pull Request Template

## Description

Linking limit documentation to [Container.CreateTransactionalBatch(PartitionKey) method](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.createtransactionalbatch?view=azure-dotnet)

## Type of change

- This change requires a documentation update

## Closing issues

To automatically close an issue: closes #3853

2023-05-18 20:31 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +        /// <seealso href="https://learn.microsoft.com/en-us/azure/cosmos-db/concepts-limits#per-request-limits">Transaction limits on batches</seealso>
Also can you please add these to TransactionalBatch type description and As well ExecuteAsync() method in it.

2023-05-19 05:51 UTC, kirankumarkolli approved these changes

2023-05-19 06:08 UTC, sourabh1007 approved these changes

2023-05-19 14:56 UTC, ealsur requested changes

2023-05-19 14:56 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +        /// <seealso href="https://docs.microsoft.com/azure/cosmos-db/concepts-limits#per-request-limits">Limits on TransactionalBatch requests</seealso>
Please update the link to the latest url form https://learn.microsoft.com/azure/cosmos-db/concepts-limits#per-request-limits

2023-05-19 16:10 UTC, ealsur approved these changes

2023-05-22 13:19 UTC, merged