Added Trace when converting HTTP Timeout to 503
Azure/azure-cosmos-dotnet-v3 pull request #3866
Opened 2023-05-19 20:53 UTC by rinatmini

# Pull Request Template

## Description

Added trace when converting HTTP Timeout to 503 to avoid generating empty diagnostics

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Closing issues

To automatically close an issue: closes #3831

2023-05-19 22:51 UTC, ealsur requested changes

2023-05-19 22:51 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
> +            ITrace trace)
nit: CancellationToken should always be the last parameter.

2023-05-19 22:51 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
> +            using (ITrace trace = Trace.GetRootTrace(nameof(SendHttpAsync), TraceComponent.Transport, TraceLevel.Info))
The idea is that whoever calls CosmosHttpClientCore already has a Trace, that is the trace that needs to be passed down here. 

So we need to find who calls this SendHttpAsync method and pass it down.

Interestingly, this method receives already

`IClientSideRequestStatistics clientSideRequestStatistics`, which is part of the Trace, in fact, below this code does:

```
if (clientSideRequestStatistics is ClientSideRequestStatisticsTraceDatum datum)
```

ClientSideRequestStatisticsTraceDatum contains the reference to the trace through its `TraceSummary` property.

Either use this to access the original Trace or receive the Trace along with the `IClientSideRequestStatistics` and make sure all the callers pass it (this last option might be more involved in terms of code changes)

2023-05-25 00:11 UTC, rinatmini commented on Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
> +            using (ITrace trace = Trace.GetRootTrace(nameof(SendHttpAsync), TraceComponent.Transport, TraceLevel.Info))
@ealsur @sourabh1007
Added receiving the Trace along with the `IClientSideRequestStatisticsIn` in the hierarchy of calls. 
Most of the callers don't have `Trace` or don't use it - so in most cases, `Trace/Diagnostic` is still empty or default (`NoOps`). Looks like will be required additional work to add using and populating the `Trace` object during calls to get correct and desired diagnostics.
Also `CosmosExceptionFactory.CreateServiceUnavailableException` expects `ITrace` and `TraceSummary` and cannot be used to get access the original Trace.

2023-05-26 10:10 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +                    trace: null);
No need to pass null, you can make it optional in the function itself

2023-05-26 10:13 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +                trace,
Why are you passing trace here? are we going to capture traces from GetDatabaseAccount Call also?

2023-05-30 16:33 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
> +            using (ITrace trace = Trace.GetRootTrace(nameof(SendHttpAsync), TraceComponent.Transport, TraceLevel.Info))
Have we tested this (that the ClientSideRequestStatistics have no Trace) with the SDK in GatewayMode? We need to remember that there are 2 groups of calls, there are initialization calls that are for Metadata and then there are Data Plane calls.

You mentioned that most don't have `Trace`, which ones do?

When I see in the `TransportHandler` how the ClientSideRequestStatistics is created, it should have a Summary: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Handler/TransportHandler.cs#L96-L97

I wonder, can we check for this and IF there is a Summary, then pass the Trace to the `CreateServiceUnavailableException` call and if not (there is no Summary), then pass a `NoOpTrace.Singleton`.

But first understand which are the cases where there is a Summary and which where there isn't?

2023-05-30 16:34 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
> +                trace,
GetDatabaseAccount is part of the initialization, there is no harm in adding the trace there?

2023-05-31 15:03 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosHttpClientCoreTests.cs
> +                using (ITrace trace = Trace.GetRootTrace(nameof(RetryTransientIssuesTestAsync)))
Where is this trace used?

2023-06-01 19:00 UTC, ealsur submitted a review, later dismissed

2023-06-01 20:05 UTC, sourabh1007 approved these changes

2023-06-01 20:05 UTC, sourabh1007 approved these changes

2023-06-01 20:33 UTC, ealsur approved these changes

2023-06-01 22:03 UTC, merged