Documentation: Adds additional remarks to CosmosClient
Azure/azure-cosmos-dotnet-v3 pull request #3891
Opened 2023-06-02 23:29 UTC by rinatmini

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Include samples if adding new API, and include relevant motivation and context. List any dependencies that are required for this change.

## Type of change
- [x] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #3886

2023-06-05 14:50 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/CosmosClient.cs
> +    /// except the initialization cases when the SDK warms up the caches and connections before the first call to the service is made (CosmosClient.CreateAndInitializeAsync calls).
I'd remove the "except..." paragraph, the same expectations are clear after the first paragraph. @kirankumarkolli thoughts?

2023-06-05 14:51 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
> +        /// <see href="https://docs.microsoft.com/azure/cosmos-db/performance-tips">performance guide</see>.
Please use the current URL from learn, not the old docs site

2023-06-05 14:57 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
> +        /// CosmosClient is thread-safe. Its recommended to maintain a single instance of CosmosClient per lifetime
Everywhere where you say CosmosClient prefer "cosmos client". You see how the casing is used in the existing paragraph before this one.

2023-06-05 14:57 UTC, ealsur requested changes
See link and text corrections

2023-06-05 18:31 UTC, rinatmini commented on Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
> +        /// In addition to that it initializes the client with containers provided i.e The SDK warms up the caches and
This is a phrasing from existing public documentation for [CreateAndInitializeAsync ](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.cosmosclient.createandinitializeasync?view=azure-dotnet#microsoft-azure-cosmos-cosmosclient-createandinitializeasync(system-string-system-collections-generic-ireadonlylist((system-valuetuple((system-string-system-string))))-microsoft-azure-cosmos-cosmosclientoptions-system-threading-cancellationtoken)) that would be better to place here too because this method internally invokes CreateAndInitializeAsync.

2023-06-05 18:35 UTC, rinatmini commented on Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
> +        /// CosmosClient is thread-safe. Its recommended to maintain a single instance of CosmosClient per lifetime
This phrasing is also from the public documentation [CosmosClient](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.cosmosclient?view=azure-dotnet) that will be better to place here too. If we change it here then we should change it everywhere in the public docs for consistency

2023-06-05 19:27 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
> +        /// In addition to that it initializes the client with containers provided i.e The SDK warms up the caches and
Got it, I prefer consistency, if we already have this text, then so be it.

2023-06-06 10:46 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/CosmosClient.cs
> +    /// except the initialization cases when the SDK warms up the caches and connections before the first call to the service is made (CosmosClient.CreateAndInitializeAsync calls).
+1 this doc you can put over `CosmosClient.CreateAndInitializeAsync` instead of here.

2023-06-06 10:49 UTC, sourabh1007 commented
> # Pull Request Template
> ## Description
> Please include a summary of the change and which issue is fixed. Include samples if adding new API, and include relevant motivation and context. List any dependencies that are required for this change.
> 
> ## Type of change
> * [x]  This change requires a documentation update
> 
> ## Closing issues
> To automatically close an issue: closes #3886

Add description about the PR. mention if you are targeting specific APIs to improve the documentation.

2023-06-06 13:50 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/CosmosClient.cs
> +        /// The returned reference doesn't guarantee credentials or connectivity validations because initialization doesn't make any network calls.
And initialize connections

2023-06-08 14:29 UTC, merged