[Internal] Upgrade Resiliency: Refactors Rntbd Open Connection Logic to Validate Replicas Accurately
Azure/azure-cosmos-dotnet-v3 pull request #3918
Opened 2023-06-16 19:11 UTC by kundadebdatta

# Pull Request Template

## Description

This PR bumps up the `Cosmos.Direct` package version to `3.32.1` which addresses the below issues:

- Fixes crashing `CosmosClient` on the `Dispose()` stage.
- Marking the `Israel Central` as a public region.
- Improves the `LoadBalancingPartition.OpenChannelAsync()` located inside the `Cosmos.Direct` package, to add a validation on the maximum number of channels that is permitted to open by the user. The changes are described below in detail.

  - Code changes to refactor open connection logic in the `LoadBalancingPartition` to add max channel validation.
  - Code changes to refactor the `ChannelDictionary` to remove the check on the existing channels. This change will help to establish Rntbd connections to backend replica nodes, during the replica validation flow.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Closing issues

To automatically close an issue: closes #3700, #3908

2023-06-16 19:21 UTC, ealsur requested changes

2023-06-16 19:21 UTC, ealsur commented on Directory.Build.props
> +		<DirectVersion>3.31.2</DirectVersion>
Add the new region to `Regions.cs`

2023-06-16 19:21 UTC, NaluTripician submitted a review, later dismissed

2023-06-16 19:26 UTC, kundadebdatta commented on Directory.Build.props
> +		<DirectVersion>3.31.2</DirectVersion>
Added.

2023-06-16 20:02 UTC, kirankumarkolli submitted a review, later dismissed

2023-06-16 20:02 UTC, kirankumarkolli commented
@msbot please wait for @ealsur signoff

2023-06-16 20:03 UTC, kirankumarkolli commented on Directory.Build.props
> +		<DirectVersion>3.31.2</DirectVersion>
Is there test coverage for it?

2023-06-16 20:10 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqTranslationWithCustomSerializerBaseline.TestMemberInitializer.xml
> +﻿<Results>
Undo this file, it is not needed

2023-06-16 22:43 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqTranslationWithCustomSerializerBaseline.TestMemberInitializer.xml
> +﻿<Results>
Deleted this file.

2023-06-16 23:32 UTC, ealsur approved these changes

2023-06-17 00:10 UTC, kirankumarkolli approved these changes

2023-06-17 00:29 UTC, merged