Subpartitioning: Fixes bug for queries on subpartitioned containers
Azure/azure-cosmos-dotnet-v3 pull request #3934
Opened 2023-06-22 21:10 UTC by NaluTripician

# Pull Request Template

## Description

Similar to #3879.  For queries across physical partition with prefix partition keys using `top` in the queries, `ReadNextAsync` will get stuck in an infinite loop. 

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)

## Closing issues

To automatically close an issue: closes #3933

2023-06-23 01:22 UTC, KevinPoorDeveloper commented
Hi Nalu,
Thank you for your quick work on this. 

I'm pretty convinced that this isn't the only issue here. Our partial partition key that we discussed crossed 40GB, and I assume an additional physical partition was created. Since then, queries work on localhost through VS, but fail on production, whenever we only include part of the partition key in the query. All queries work fine with the full partition query.
Perhaps we shall speak again tomorrow.
Thank you for your time and help,
-Kevin

2023-06-23 14:34 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> +    using Microsoft.Azure.Cosmos.Serialization.HybridRow.Schemas;
Why is this dependency needed?

2023-06-23 14:50 UTC, NaluTripician commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> +    using Microsoft.Azure.Cosmos.Serialization.HybridRow.Schemas;
Looks like it was added automatically by intellisense and I missed it in the cleanup. Removed in latest push.

2023-06-26 20:48 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> +    using global::Azure;
nit: is this using needed?

2023-06-26 20:52 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Query/Core/QueryClient/ContainerQueryProperties.cs
> +        public List<Range<string>> EffectivePartitionKeyRanges { get; }
```suggestion
        public List<Range<string>> EffectiveRanges { get; }
```

These are just Ranges, not PartitionKeyRanges

2023-06-26 20:53 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Query/Core/QueryClient/ContainerQueryProperties.cs
> +        public List<Range<string>> EffectivePartitionKeyRanges { get; }
Why a list of Ranges if `GetEffectivePartitionKeyRange` returns a single `Range<string>`?

2023-06-26 20:54 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryClientCore.cs
> +            List<Range<string>> effectivePartitionKeyRange = null;
nit: Shouldn't this be simply:

```suggestion
            Range<string> effectivePartitionKeyRange = null;
```

2023-06-26 20:54 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryClientCore.cs
> +                effectivePartitionKeyRange.Add(PartitionKeyInternal.GetEffectivePartitionKeyRange(
```suggestion
                effectivePartitionKeyRange = PartitionKeyInternal.GetEffectivePartitionKeyRange(
```

2023-06-26 20:55 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> +        private static Documents.Routing.PartitionKeyInternal GetNoneValue(
When is this used?

2023-06-26 20:56 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> +    using Microsoft.Azure.Documents;
Undo this and use the `Documents.` where it is needed, otherwise you have to also do the `Cosmos.PartitionKey` at the bottom of the file

2023-06-26 20:57 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> +                                    trace);
Why change `createQueryPipelineTrace` for `trace`?

2023-06-26 20:58 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Query/Core/QueryClient/ContainerQueryProperties.cs
> +        public List<Range<string>> EffectivePartitionKeyRanges { get; }
Is it because `QueryClient.GetTargetPartitionKeyRangesAsync` takes a list?

2023-06-26 20:59 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryClientCore.cs
> +                effectivePartitionKeyRange.Add(PartitionKeyInternal.GetEffectivePartitionKeyRange(
WOuldn't this throw? `effectivePartitionKeyRange` is `null`, you didn't initialize it.

2023-06-26 20:59 UTC, ealsur requested changes
Please see the comments

2023-06-27 14:23 UTC, NaluTripician commented on Microsoft.Azure.Cosmos/src/Query/Core/QueryClient/ContainerQueryProperties.cs
> +        public List<Range<string>> EffectivePartitionKeyRanges { get; }
Yes, in all of the cases where we would use this it takes a list.

2023-06-27 14:24 UTC, NaluTripician commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> +        private static Documents.Routing.PartitionKeyInternal GetNoneValue(
Left in from first iteration. Removed in latest push.

2023-06-27 14:55 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> +        }
nit: undo line

2023-06-27 17:13 UTC, ealsur approved these changes
Please get a review from the query folks

2023-07-11 16:47 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Query/Core/QueryClient/ContainerQueryProperties.cs
> +        public List<Range<string>> EffectivePartitionKeyRanges { get; }
>List [](http://example.com/codeflow?start=15&length=4)

IReadOnlyList would be nice (if possible).

2023-07-11 16:49 UTC, adityasa commented
Hi Nalu, thanks for taking this on, much appreciated.
Can you kindly add coverage/regression test for the specific query in question?

2023-07-11 17:30 UTC, NaluTripician commented
> Hi Nalu, thanks for taking this on, much appreciated. Can you kindly add coverage/regression test for the specific query in question?

Yes, @SrinikhilReddy is currently working on the tests.

2023-07-12 06:08 UTC, neildsh commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> +                                    trace);
I believe this is so that the trace is properly nested

2023-07-12 06:18 UTC, neildsh commented on Microsoft.Azure.Cosmos/src/Query/Core/QueryClient/ContainerQueryProperties.cs
> +        public List<Range<string>> EffectivePartitionKeyRanges { get; }
I do not quite understand this. If we always return a list with a single element, why return a list at all ? If the caller needs a list, they can wrap it themselves.

2023-07-12 06:25 UTC, neildsh commented on Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryClientCore.cs
> +                            isMaxInclusive: true))
`Range<PartitionKeyInternal>.GetPointRange(partitionKeyInternal)`

2023-07-12 06:28 UTC, neildsh commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> -                                List<Documents.PartitionKeyRange> targetRanges = await cosmosQueryContext.QueryClient.GetTargetPartitionKeyRangesByEpkStringAsync(
>GetTargetPartitionKeyRangesByEpkStringAsync [](http://example.com/codeflow?start=118&length=43)

I think we can delete this method from `CosmosQueryClient`

2023-07-12 14:14 UTC, NaluTripician commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> -                                List<Documents.PartitionKeyRange> targetRanges = await cosmosQueryContext.QueryClient.GetTargetPartitionKeyRangesByEpkStringAsync(
It looks like it is used in other places. 
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/d0aac27bfdd5fb90a7ab0523491897454f69ba6b/Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs#L649

2023-07-12 14:27 UTC, NaluTripician commented on Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryClientCore.cs
> +                            isMaxInclusive: true))
Here I think we do not want to use a point range. This is similar to the earlier fix we had to do. For split physical partitions a point range will not work, but in the case where there is only one physical partition this should return the correct result. Here is the[ previous PR](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3879/files) for more context.

2023-07-13 06:43 UTC, neildsh commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> -                                List<Documents.PartitionKeyRange> targetRanges = await cosmosQueryContext.QueryClient.GetTargetPartitionKeyRangesByEpkStringAsync(
wouldn't we need the same fix in other places too, then?

2023-07-14 15:58 UTC, NaluTripician commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> -                                List<Documents.PartitionKeyRange> targetRanges = await cosmosQueryContext.QueryClient.GetTargetPartitionKeyRangesByEpkStringAsync(
Other than the place that I mentioned above are there other places in Query that are assuming PK -> Single Range? And would the changes we made cause the code to enter the first if statement in this block?

2023-07-17 23:12 UTC, neildsh commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> -                                List<Documents.PartitionKeyRange> targetRanges = await cosmosQueryContext.QueryClient.GetTargetPartitionKeyRangesByEpkStringAsync(
I think pretty much all code prior to the subpartitioning change assumes that a PK value implies a single range

2023-08-09 20:12 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Query/Core/QueryClient/ContainerQueryProperties.cs
> +        public IReadOnlyList<Range<string>> EffectivePartitionKeyRanges { get; }
nit: The name of this property suggest it can be used for any Range, but it is only used for cases when there is a PartitionKey. Would a better name for this be something like `EffectiveRangesForPartitionKey` and add a comment on the property explaining that a PartitionKey equals to 1 range when it's a full Partition Key Value or it can span many if it's a Partial Partition Key value from Subpartitioning?

2023-08-09 20:18 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Routing/PartitionKeyHash.cs
> +        public PartitionKeyHash(UInt128[] values)
Is this code used just for testing?

2023-08-09 20:24 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Routing/PartitionKeyHash.cs
> +        public UInt128[] hashValues
Is this really public? If so, should the casing be `HashValues`?

Also, the getter is recalculating it always, not not just equal this to the original `UInt128[] values` and instead do the String ToHex only when ToString is called?

2023-08-09 20:25 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Routing/PartitionKeyHash.cs
> +        public UInt128[] hashValues
Like, constructor just sets the value of `HashValues`, `ToString` can do the StringBuilder thing, or even better, do it once and cache it in a private property if needed.

2023-08-09 22:17 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Routing/PartitionKeyHash.cs
> +        internal static class HexConvert
Isn't this the same that exists in PartitionKeyInternal type?

2023-08-30 01:16 UTC, SrinikhilReddy commented on Microsoft.Azure.Cosmos/src/Routing/PartitionKeyHash.cs
> +        public UInt128[] hashValues
Changed as suggested, thanks.

2023-08-30 01:17 UTC, SrinikhilReddy commented on Microsoft.Azure.Cosmos/src/Routing/PartitionKeyHash.cs
> +        internal static class HexConvert
Yes, removed the reused methods, had to retain one method which is not a public method in PartitionKeyInternal.cs

2023-08-30 01:19 UTC, SrinikhilReddy commented on Microsoft.Azure.Cosmos/src/Routing/PartitionKeyHash.cs
> +        public PartitionKeyHash(UInt128[] values)
yes, changed to the modifier to `internal`

2023-08-30 15:44 UTC, ealsur reviewed
Some nits and final comments

2023-08-30 15:44 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Routing/PartitionKeyHash.cs
> +        internal PartitionKeyHash(UInt128[] values)
nit: Mix/match of public/internal constructors. This class is already `internal`, marking properties or methods as `internal` does not yield any benefits.

Either use `private` if it is not meant to be used outside this type or `public`.

2023-08-30 15:44 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Routing/PartitionKeyHash.cs
> +        private readonly UInt128[] values;
nit: reorder. `private` local variables go before the constructor.

2023-08-30 15:44 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Routing/PartitionKeyHashRange.cs
> +        public PartitionKeyHash GetMidPoint()
Where is this method used in the PR code?

2023-08-30 16:23 UTC, NaluTripician commented on Microsoft.Azure.Cosmos/src/Routing/PartitionKeyHashRange.cs
> +        public PartitionKeyHash GetMidPoint()
removing

2023-08-31 20:43 UTC, ealsur submitted a review, later dismissed

2023-08-31 22:19 UTC, NaluTripician commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> -                                List<Documents.PartitionKeyRange> targetRanges = await cosmosQueryContext.QueryClient.GetTargetPartitionKeyRangesByEpkStringAsync(
removing method.

2023-09-01 14:31 UTC, ealsur submitted a review, later dismissed

2023-09-05 14:47 UTC, ealsur approved these changes

2023-09-05 20:34 UTC, neildsh commented on Microsoft.Azure.Cosmos/src/Query/Core/QueryClient/ContainerQueryProperties.cs
> +            List<Range<string>> effectivePartitionKeyRanges,
>List [](http://example.com/codeflow?start=12&length=4)

`IReadOnlyList` please

2023-09-05 20:38 UTC, neildsh commented on Microsoft.Azure.Cosmos/src/Routing/PartitionKeyHash.cs
> +        public readonly UInt128[] HashValues => this.values;
>UInt128[] [](http://example.com/codeflow?start=24&length=9)

We should not expose this as a mutable array. Please consider changing this to be immutable

2023-09-05 20:49 UTC, neildsh commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> -        private static bool TryGetEpkProperty(
>TryGetEpkProperty [](http://example.com/codeflow?start=28&length=17)

I am not sure this change is safe, since the earlier version was allowing the callers to pass in the pk in the properties and the new version just ignores this

2023-09-05 21:58 UTC, NaluTripician commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> -        private static bool TryGetEpkProperty(
Added back check for Pk in properties, then convert the string to a range.

2023-09-07 14:19 UTC, ealsur submitted a review, later dismissed

2023-09-08 16:31 UTC, NaluTripician commented
@msftbot wait to merge until @ealsur and @neildsh approve

2023-09-11 06:13 UTC, neildsh commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> +    using System.Runtime.CompilerServices;
>using System.Runtime.CompilerServices; [](http://example.com/codeflow?start=4&length=38)

is this required?

2023-09-11 06:19 UTC, neildsh commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> +                    { new Documents.Routing.Range<string>(effectivePartitionKeyString, effectivePartitionKeyString, true, true) };
>(effectivePartitionKeyString, effectivePartitionKeyString, true, true) [](http://example.com/codeflow?start=57&length=70)

Do we have to worry about the same prefix issue with hierarchical partition keys here?

2023-09-11 06:21 UTC, neildsh commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> +                targetRanges = feedRangeInternal != null
>feedRangeInternal != null [](http://example.com/codeflow?start=31&length=25)

It would be easier to read if you pull this condition up as an `else if` since we are already in a conditional ladder

2023-09-11 06:37 UTC, neildsh commented
>     internal abstract class PartitionKeyHashRangeSplitterAndMerger

looks like this class is not used anywhere except in test code. Should this be moved to the tests folder?

---
Refers to: Microsoft.Azure.Cosmos/src/Routing/PartitionKeyHashRangeSplitterAndMerger.cs:14 in 48557c9. [](commit_id = 48557c97f6b2bdbebc45ff74a614a29255d0d505, deletion_comment = False)

2023-09-11 06:39 UTC, neildsh commented on Microsoft.Azure.Cosmos/src/Routing/PartitionKeyHashRangeSplitterAndMerger.cs
> +                _ => throw new ArgumentOutOfRangeException($"Unknown {nameof(SplitOutcome)}: {splitOutcome}."),
>ArgumentOutOfRangeException [](http://example.com/codeflow?start=31&length=27)

This is not quite correct. There are other split outcomes possible. Please consider a custom `RangeSplitException` instead

2023-09-11 06:42 UTC, neildsh commented on Microsoft.Azure.Cosmos/src/Routing/PartitionKeyHash.cs
> +            this.values = values;
This is very dangerous. `this.Value` is an immutable string, so far so good. However, `this.values` is a mutable array, which allows both of these members to go out of sync. Please use an immutable structure.

2023-09-11 06:49 UTC, neildsh commented on Microsoft.Azure.Cosmos/src/Routing/PartitionKeyHash.cs
> +        private readonly UInt128[] values;
>UInt128[] values; [](http://example.com/codeflow?start=25&length=17)

Can you please add unit tests that exercise the new logic (the full array of UInt128[] values)? PartitionKeyHashRanges also has some significant new logict hat does not seem to be covered.

2023-09-11 16:25 UTC, NaluTripician commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> +    using System.Runtime.CompilerServices;
removed.

2023-09-12 18:50 UTC, neildsh commented
>             if (!UInt128.TryParse(value, out UInt128 uInt128))

This only parses a single UInt128. If we expect there to be multiple UINt128's , then this would have to change

---
Refers to: Microsoft.Azure.Cosmos/src/Routing/PartitionKeyHash.cs:91 in 48557c9. [](commit_id = 48557c97f6b2bdbebc45ff74a614a29255d0d505, deletion_comment = False)

2023-09-12 19:03 UTC, neildsh commented on Microsoft.Azure.Cosmos/src/Routing/PartitionKeyHashRanges.cs
> +                    if (partitionKeyHashRange.StartInclusive.Value.HashValues[0] < minStart)
>partitionKeyHashRange.StartInclusive.Value.HashValues[0] < minStart [](http://example.com/codeflow?start=24&length=67)

Would this still work if we have multiple ranges with the same hash prefix, but differ in Value.HashValues[1]  ?

2023-09-14 18:51 UTC, neildsh approved these changes

2023-09-14 20:01 UTC, ealsur approved these changes

2023-09-14 21:35 UTC, merged

2023-09-14 21:36 UTC, NaluTripician commented
A separate PR will be out to move several files only used for testing to the Test library.