[Internal] Upgrade Resiliency: Expose Replica Validation Feature Through `CosmosClientOptions`
Azure/azure-cosmos-dotnet-v3 pull request #3951
Opened 2023-06-27 22:47 UTC by kundadebdatta

# Pull Request Template

## Description

This PR exposes the replica validation feature through the `CosmosClientOptions` contract. Replica validation is currently applicable only for preview package and supported only for the Direct mode.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Closing issues

To automatically close an issue: closes #3922

2023-06-28 21:22 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        bool EnableAdvancedReplicaSelectionForTcp { get; set; }
Let me know how you feel about this new naming. Cc: @ealsur @kirankumarkolli

2023-06-28 21:25 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs
> +                    await Task.WhenAll(openConnectionTasks);
Addressing from [previous review comment](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3939#discussion_r1242321783).

2023-06-28 21:25 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs
> +        public bool EnableReplicaValidation
Let's align the names, if it's called `EnableAdvancedReplicaSelectionForTcp` in CosmosClientOptions, let's sync it here

2023-06-28 21:26 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs
> +                        if (cancellationToken.IsCancellationRequested)
Addressing from [previous review comment](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3939#discussion_r1242638346).

2023-06-28 21:27 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        bool EnableAdvancedReplicaSelectionForTcp { get; set; }
I don't have a better name, words could be shuffled around, but I don't know if the result is better (EnableTcpAdvancedReplicaSelection)

2023-06-28 21:29 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        /// status, and based on status, it prioritizes the replicas which are connected to the backend, so that the requests can be sent
```suggestion
        /// status, and based on status, it prioritizes the replicas which show healthy stable connections
```

2023-06-28 21:29 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        /// confidently to the particular replica. This helps the cosmos client to become more resilient and effictive to any connection
```suggestion
        /// This helps the cosmos client to become more resilient and effective to any connectivity issue.
```

Some wording suggestions

2023-06-28 21:32 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        /// <para>This is optimal for workloads where latency spikes are critical due to connection timeouts. Does not apply if <see cref="ConnectionMode.Gateway"/> is used.</para>
> This is optimal for workloads where latency spikes are critical due to connection timeouts

I wonder if there is a different way to word this?

Like:

"This is optimal for latency-sensitive workloads"

2023-06-28 21:36 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        /// <para>This is optimal for workloads where latency spikes are critical due to connection timeouts. Does not apply if <see cref="ConnectionMode.Gateway"/> is used.</para>
Sounds much better!

2023-06-28 22:46 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs
> +        public bool EnableReplicaValidation
Updated the code to reflect this.

2023-06-28 22:47 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        /// status, and based on status, it prioritizes the replicas which are connected to the backend, so that the requests can be sent
Updated the verbiage.

2023-06-28 22:47 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        /// confidently to the particular replica. This helps the cosmos client to become more resilient and effictive to any connection
Updated the verbiage.

2023-06-28 22:47 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        /// <para>This is optimal for workloads where latency spikes are critical due to connection timeouts. Does not apply if <see cref="ConnectionMode.Gateway"/> is used.</para>
Updated the verbiage.

2023-06-28 22:49 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        bool EnableAdvancedReplicaSelectionForTcp { get; set; }
Because this is applicable for `preview` mode, and this will never be in GA, my preference is to keep the same name, i.e.`EnableAdvancedReplicaSelectionForTcp `

2023-06-29 03:50 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        bool EnableAdvancedReplicaSelectionForTcp { get; set; }
Per our conversation, public API contract changes doesn't apply any more.

2023-06-29 03:51 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        /// status, and based on status, it prioritizes the replicas which are connected to the backend, so that the requests can be sent
Per our conversation, public API contract changes doesn't apply any more.

2023-06-29 03:51 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        /// confidently to the particular replica. This helps the cosmos client to become more resilient and effictive to any connection
Per our conversation, public API contract changes doesn't apply any more.

2023-06-29 04:08 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +            this.isReplicaAddressValidationEnabled = ConfigurationManager
How about ENV state always overrides default for both GA and preview.

2023-06-29 04:27 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs
> +                                cancellationToken: linkedTokenSource.Token));
Incoming token is enough right, TokenSource is not needed here.

2023-06-29 04:30 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs
> +                            break;
OnCancellation behavior: With new changes its trying to gracefully complete right? 
Current existing pattern across is to throw exception
> cancellationToken.ThrowIfCancellationRequested()

2023-06-29 04:33 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Routing/GlobalAddressResolver.cs
> +            this.isReplicaAddressValidationEnabled = ConfigurationManager
non-blocker: Do we ever need it to be driven from the a single decision point/source instead of spilling it all through the codebase.

2023-06-29 14:38 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs
> +                                cancellationToken: linkedTokenSource.Token));
Correct, you are not using the linked token for anything. Linked token is for when you need to issue a cancellation from within the context's logic

2023-06-29 14:40 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs
> +                            break;
Isn't this used during the CreateAndInitialize call? If so, we should avoid throwing. CreateAndInitialize is a best effort operation, if we throw, it will probably break customer application initialization

2023-06-29 14:40 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Routing/GlobalAddressResolver.cs
> +        private const string ReplicaConnectivityValidationEnabled = "AZURE_COSMOS_REPLICA_VALIDATION_ENABLED";
Should we put this on the Constants to avoid duplication?

2023-06-29 18:32 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +            this.isReplicaAddressValidationEnabled = ConfigurationManager
Thanks for the recommendation. I have updated the code accordingly.

2023-06-29 18:33 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs
> +                                cancellationToken: linkedTokenSource.Token));
Updated!

2023-06-29 18:33 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Routing/GlobalAddressResolver.cs
> +            this.isReplicaAddressValidationEnabled = ConfigurationManager
Thanks! I think it's a good idea. I have consolidated the logic inside `ConfigurationManager.IsReplicaAddressValidationEnabled()`

2023-06-29 18:37 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Routing/GlobalAddressResolver.cs
> +        private const string ReplicaConnectivityValidationEnabled = "AZURE_COSMOS_REPLICA_VALIDATION_ENABLED";
`Constants` is a part of our direct package. Because the `AZURE_COSMOS_REPLICA_VALIDATION_ENABLED` constant has been [removed from the direct package](https://msdata.visualstudio.com/CosmosDB/_git/CosmosDB/pullrequest/1093168?path=/Product/Microsoft.Azure.Documents/SharedFiles/Constants.cs&_a=files), and eventually this will no longer be needed if we enable by default, IMO we can keep it at the same place as is.

2023-06-29 20:09 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +        private readonly bool isReplicaAddressValidationEnabled;
Please update PR description with more context (ENV variable and behaviors)

2023-06-29 20:09 UTC, kirankumarkolli submitted a review, later dismissed

2023-06-29 20:22 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +        private readonly bool isReplicaAddressValidationEnabled;
Updated the description to add more details.

2023-06-29 20:26 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +        private readonly bool isReplicaAddressValidationEnabled;
Test comment, please do not resolve (testing the bot to see if it merges open comments now)

2023-06-29 20:29 UTC, ealsur approved these changes

2023-06-29 20:36 UTC, ealsur requested changes
Verify `CosmosBadReplicaTests.TestGoneFromServiceScenarioAsync` failure:

```
Failed TestGoneFromServiceScenarioAsync [154 ms]
  Error Message:
   Assert.AreEqual failed. Expected:<1>. Actual:<5>. 
  Stack Trace:
     at Microsoft.Azure.Cosmos.Tests.CosmosBadReplicaTests.TestGoneFromServiceScenarioAsync() in D:\a\1\s\Microsoft.Azure.Cosmos\tests\Microsoft.Azure.Cosmos.Tests\CosmosBadReplicaTests.cs:line 163

```

2023-06-29 22:05 UTC, kundadebdatta commented
> Verify `CosmosBadReplicaTests.TestGoneFromServiceScenarioAsync` failure:
> 
> ```
> Failed TestGoneFromServiceScenarioAsync [154 ms]
>   Error Message:
>    Assert.AreEqual failed. Expected:<1>. Actual:<5>. 
>   Stack Trace:
>      at Microsoft.Azure.Cosmos.Tests.CosmosBadReplicaTests.TestGoneFromServiceScenarioAsync() in D:\a\1\s\Microsoft.Azure.Cosmos\tests\Microsoft.Azure.Cosmos.Tests\CosmosBadReplicaTests.cs:line 163
> ```

Fixed this with latest commit.

2023-06-29 22:14 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosBadReplicaTests.cs
> +                    Assert.IsTrue(
Unset the Environment variable on a `finally` clause?

2023-06-29 22:27 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosBadReplicaTests.cs
> +                    Assert.IsTrue(
It's now done!

2023-06-29 22:54 UTC, ealsur approved these changes

2023-06-29 23:43 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs
> +                            break;
Yes, this is used in the `CreateAndInitializeAsync()` flow and throwing the exception might broke it, because the connection opening are more of a best effort, and should continue even if some of the connection warm ups failed.

2023-06-30 02:06 UTC, merged