[Internal] Query: Updated certain tests to not fail when EnableOptimisticDirectExecution is set to true in 3.35.0-preview package
Azure/azure-cosmos-dotnet-v3 pull request #3955
Opened 2023-06-28 04:22 UTC by akotalwar

# Pull Request Template

## Description

When we enabled Optimistic Direct Execution in Preview Mode for Nuget package 3.35.0-preview, it caused 27 tests to fail. These tests were not related to Optimistic Direct Execution, but they were affected by the new behavior of choosing the Optimistic Direct Execution pipeline. To avoid losing test coverage, I updated these tests to not choose the Optimistic Direct Execution pipeline in Preview Mode.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] 
## Closing issues

To automatically close an issue: closes #IssueNumber

2023-06-28 17:16 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosBasicQueryTests.cs
> +#if PREVIEW
I wonder if this is missing also on the EndToEndTraceWriterBaselineTests that are for Query

2023-06-28 17:22 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosBasicQueryTests.cs
> +#if PREVIEW
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/a25730a77ab43a8e460ddc292f1a6d8eb193395a/Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/EndToEndTraceWriterBaselineTests.cs#L464

2023-06-28 18:01 UTC, akotalwar commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosBasicQueryTests.cs
> +#if PREVIEW
This is the error message I see with QueryAsync(). Does not seem to be ODE related.

Assert.IsTrue failed.
Please run the ..\azure-cosmos-dotnet-v3\UpdateContracts.ps1 script to update the baselines.
Expected: iseconds││└──GetPartitionKeyRanges(00000000-0000-0000-0000-000000000000)Routing-Component00:00:00:00,
Actual:   iseconds││├──GetPartitionKeyRanges(00000000-0000-0000-0000-000000000000)Routing-Component00:00:00:00,
OutputPath: D:\a\1\s\Microsoft.Azure.Cosmos\tests\Microsoft.Azure.Cosmos.EmulatorTests\bin\Release\net6.0\BaselineTest\TestOutput\EndToEndTraceWriterBaselineTests.QueryAsync.xml,
BaselinePath: D:\a\1\s\Microsoft.Azure.Cosmos\tests\Microsoft.Azure.Cosmos.EmulatorTests\bin\Release\net6.0\BaselineTest\TestBaseline\EndToEndTraceWriterBaselineTests.QueryAsync.xml

2023-06-28 18:38 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosBasicQueryTests.cs
> +#if PREVIEW
Mmmm if you modify the request to disable optimistic execution, does it still happen?

This is just one line diff, but the difference could be somewhere else and that is pushing the content down some lines

2023-06-28 19:10 UTC, akotalwar commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosBasicQueryTests.cs
> +#if PREVIEW
Yes, it still happens even with ODE is turned off my default.

2023-06-28 21:08 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosBasicQueryTests.cs
> +#if PREVIEW
After changing the test code, can you run UpdateContracts.ps1? The output should change because you are modifying the test code (which is also part of the file)

2023-07-03 21:29 UTC, sourabh1007 commented
> # Pull Request Template
> ## Description
> When we enabled Optimistic Direct Execution in Preview Mode for Nuget package 3.35.0-preview, it caused 27 tests to fail. These tests were not related to Optimistic Direct Execution, but they were affected by the new behavior of choosing the Optimistic Direct Execution pipeline. To avoid losing test coverage, I updated these tests to not choose the Optimistic Direct Execution pipeline in Preview Mode.
> 
> ## Type of change
> Please delete options that are not relevant.
> 
> * [x]  Bug fix (non-breaking change which fixes an issue)
> 
> ## Closing issues
> To automatically close an issue: closes #IssueNumber

I am wondering if its a known gap in the feature thats why these tests are failing. Why are we disabling this feature instead of fixing the gap? This flag is by default "true" in public API (for preview package) does it mean that preview pkg is not in stable state right now?

2023-07-06 14:50 UTC, ealsur commented
@sourabh1007 These tests are failing because the new flag behaves differently and optimizes query execution. Because we only have one set of tests and one set of End To End Traces files, when they are run on for the Preview package **release** they fail because the XML files were not generated with the new feature on. This is exactly like when the Open Telemetry tests were failing on Preview release. Nothing to do with stability.

2023-07-06 22:37 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.QueryAsync.xml
> +    │                   │   ├── Get Collection Cache(00000000-0000-0000-0000-000000000000)  Routing-Component  00:00:00:000  0.00 milliseconds
Are you generating this from running the test in VS or through UpdateContracts.ps1 file execution?

2023-07-06 22:37 UTC, akotalwar commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.QueryAsync.xml
> +    │                   │   ├── Get Collection Cache(00000000-0000-0000-0000-000000000000)  Routing-Component  00:00:00:000  0.00 milliseconds
Generating it from UpdateContracts.ps1 file execution

2023-07-07 11:25 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.QueryAsync.xml
> +    <ATTRIBUTE key="net.peer.name">akotalwar-test.documents-staging.windows-ppe.net</ATTRIBUTE>
this particular test is going to talk to real stage account?

2023-07-07 15:40 UTC, ealsur requested changes

2023-07-07 15:40 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.QueryAsync.xml
> +    <ATTRIBUTE key="net.peer.name">akotalwar-test.documents-staging.windows-ppe.net</ATTRIBUTE>
Was this run with a config change to point to another account?

2023-07-07 18:31 UTC, akotalwar commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.QueryAsync.xml
> +    <ATTRIBUTE key="net.peer.name">akotalwar-test.documents-staging.windows-ppe.net</ATTRIBUTE>
It should not, this was done by accident.

2023-07-07 20:14 UTC, ealsur reviewed
Lgtm

2023-07-07 20:39 UTC, ealsur approved these changes

2023-07-07 20:39 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/EndToEndTraceWriterBaselineTests.cs
> +
nit: Adding a test comment, want to confirm if auto-merge will merge with open comments, please don't resolve

2023-07-07 20:59 UTC, merged