[Preview] Integrated cache: Adds ShardKey to DedicatedGatewayRequestOptions
Azure/azure-cosmos-dotnet-v3 pull request #3997
Opened 2023-07-20 01:03 UTC by jiajunpeng-msft

# Pull Request Template

## Description

Currently, integrated cache is not distributed. Requests will randomly land on any of the Dedicated Gateway instances, which causes inconsistency.

We are introducing a new "RequestOption" called "ShardKey" to specify the Dedicated Gateway request shard key. Shard key will be used to route the request to the correlated instance.

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #IssueNumber

2023-07-21 09:23 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/GatewayStoreClient.cs
> +                        string useHttp2String = Environment.GetEnvironmentVariable("UseHttp2");
you can use this to read environment variable https://github.com/Azure/azure-cosmos-dotnet-v3/blob/5ec7b4bcd7e2e0698736cd374f2196682227c913/Microsoft.Azure.Cosmos/src/Util/ConfigurationManager.cs#L18

2023-07-24 21:20 UTC, jiajunpeng-msft commented on Microsoft.Azure.Cosmos/src/GatewayStoreClient.cs
> +                        string useHttp2String = Environment.GetEnvironmentVariable("UseHttp2");
Thanks for sharing this! Changed to use `ConfigurationManager`.

2023-07-24 21:36 UTC, sourabh1007 submitted a review, later dismissed

2023-07-29 01:44 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Settings/DedicatedGatewayRequestOptions.cs
> +#if PREVIEW
When is backend ready for public preview? 
Ideally this needs to be public after-wards. 

Private preview: As discussed before public contract is not a requirement and can be worked around through using custom-headers right? 

/cc: @jcocchi

2023-07-29 01:45 UTC, kirankumarkolli requested changes
Preview contracts are for public previews. Waiting for clarifiation

2023-07-31 16:46 UTC, jcocchi commented on Microsoft.Azure.Cosmos/src/Resource/Settings/DedicatedGatewayRequestOptions.cs
> +#if PREVIEW
Sharding public preview is several months out and our private preview will be limited, at least in the initial phase. Using custom headers makes sense for now so we don't confuse existing customers with new options that aren't widely available yet

2023-08-08 23:46 UTC, jiajunpeng-msft commented on Microsoft.Azure.Cosmos/src/Resource/Settings/DedicatedGatewayRequestOptions.cs
> +#if PREVIEW
This makes sense to me. I removed ShardKey request option and modified the http2 to be used when it's Dedicated Gateway request and has the environment variable set.

Let me know if this makes sense to you @kirankumarkolli @jcocchi.

2024-09-13 18:56 UTC, kirankumarkolli commented
Closing inactive PRs older than 3-months, please re-active it needed.

2024-09-13 18:56 UTC, closed without merging