[Internal] Client Telemetry: Refactors code for collectors
Azure/azure-cosmos-dotnet-v3 pull request #4037
Opened 2023-08-14 10:17 UTC by sourabh1007

## Description

This PR is part 1/3 of this https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3816 PR.

As part of PR, refactoring client telemetry code to add Collector abstraction.

## Type of change

- [] Bug fix (non-breaking change which fixes an issue)

2023-08-14 14:36 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +            if (this.TelemetryToServiceHelper != null)
HttpClient is also used by TelemetryServiceHelper and HttpClient should be after from dependency wise right?

2023-08-14 14:39 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +#if !INTERNAL
For compute it will be NULL and results in NullReference for CollectionCaches. Thoughts?

2023-08-14 14:41 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +#if !INTERNAL
#if !INTERNAL

TelemetryToServiceHelper.CreateAndInitializeClientConfigAndTelemetryJob implementation it-self is covering for INTERNAL, is above precondition here needed?

2023-08-14 14:44 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
> +		<None Include="..\..\LICENSE" Pack="true" PackagePath="" Visible="false" />
Spaces only change, not needed, undo.

2023-08-14 14:45 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Routing/ClientCollectionCache.cs
> +                                     () => new TelemetryInformation
ClientCollectionCache.GetDatabaseAndCollectionName is not used and dead code.

2023-08-14 14:47 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +            if (!data.RequestLatency.HasValue)
Is latency based filtering only for collectionCache interactions.

2023-08-14 15:03 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/TelemetryToServiceHelper.cs
> +                DefaultTrace.TraceInformation($"Error While starting Telemetry Job : {ex.Message}. Hence disabling Client Telemetry");
This needs to be at-least warning level right?

2023-08-14 15:06 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/TelemetryToServiceHelper.cs
> +            this.clientTelemetry?.Dispose();
Explicit Dispose had concurrency issues right? 

Since we only expect one clientTelemetry, dispose can deferred to the Finalizer.

2023-08-14 15:06 UTC, kirankumarkolli requested changes
Please check comments

2023-08-14 15:50 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +#if !INTERNAL
removing it. it is already handled inside.

2023-08-14 15:51 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +#if !INTERNAL
removed this one and kept inside one. So we don't have to deal with null helper anywhere.

2023-08-14 16:25 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
> +		<None Include="..\..\LICENSE" Pack="true" PackagePath="" Visible="false" />
missed to push :(..will push now

2023-08-14 16:39 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +            if (!data.RequestLatency.HasValue)
No...if latency info is missing..I am skipping that datapoint for operation telemetry also...

2023-08-14 17:51 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/TelemetryToServiceHelper.cs
> +            this.collector = new TelemetryCollectorNoOp();
added documentation. . anyway after other PR's it should become clearer automatically.

2023-08-14 18:00 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +            if (this.TelemetryToServiceHelper != null)
I don't think it matters, `httpclient ` will anyway throw exception if there is any inflight http call and for that, already try catch is there.

2023-08-14 18:06 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/TelemetryToServiceHelper.cs
> +            this.clientTelemetry?.Dispose();
I am not sure about concurrency issue here, as dispose get called only once. It is an attempt to stop everything using cancellation token (which is inside dispose).

2023-08-19 12:52 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/TelemetryToServiceHelper.cs
> +#if INTERNAL
INTERNAL is spilled through. 
Can this be handled at the connectionPolicy level it-self? It will naturally just flow through right?

2023-08-19 12:59 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/TelemetryToServiceHelper.cs
> +        public bool IsClientTelemetryJobRunning()
With collectors the telemetry is running or not is implementation details right? 

The only scenarios is when the client is explicitly opting out at the client scope. And that the caller (PipelineBuiler) can base the decision on the ClientOptions right?

2023-08-19 13:03 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/TelemetryToServiceHelper.cs
> +            this.clientTelemetry?.Dispose();
Assuming that only one instance of ClientTelemetry is created and used by only instance of TelemetryCollector then we can delegate the dispose requirement to TelemetryCollector. Which the finalizer will take care of right?

2023-08-19 13:05 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/Collector/TelemetryCollector.cs
> +                DefaultTrace.TraceError($"Error while collecting cache {cacheName} telemetry. Exception : {ex}");
nit: Move all traces to argument based to avoid unnecessary materialization.

2023-08-19 13:07 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +            if (!data.RequestLatency.HasValue)
Is it expected to not have latency? If not how about at-least tracing?

2023-08-19 13:08 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +            if (!data.RequestLatency.HasValue)
As system telemetry do such data points help us proactively discover the gaps? Thoughts (follow-up)

2023-08-19 13:10 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Handler/ClientPipelineBuilder.cs
> +            if (telemetryToServiceHelper.IsClientTelemetryJobRunning())
Eventually the only time handler is unexpected is when client explicitly disables right? 
If so can it be based on the client options?

2023-08-19 13:12 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +            if (this.telemetryToServiceHelper != null)
telemetryToServiceHelper  uses HttpClient. So telemetryToServiceHelper  needs to be disposed before httpclient. 

Please do check the lifeitmes dependencies in all places.

2023-08-19 13:14 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/TelemetryToServiceHelper.cs
> +#if INTERNAL
No it is not spilled..it just used to decide if telemetry helper should be no op or not..that's it.after that it works naturally....it makes sure that pkg doesn't even contain telemetry related code...

2023-08-19 13:15 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/TelemetryToServiceHelper.cs
> +        public bool IsClientTelemetryJobRunning()
No once we have API integration.....this will change...opt in/out will be based on API response.

2023-08-19 13:20 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Handler/ClientPipelineBuilder.cs
> +            if (telemetryToServiceHelper.IsClientTelemetryJobRunning())
And when it is disabled by client config API

2023-08-19 13:22 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +            if (this.telemetryToServiceHelper != null)
Exception during httclient dispose is already handled.

If you notice other components like gem, authorisation is also getting disposed later, I believe they also make http calls like client telemetry

2023-08-19 13:24 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Handler/ClientPipelineBuilder.cs
> +            if (telemetryToServiceHelper.IsClientTelemetryJobRunning())
And along with that, i don' t want to spill connection policy and client option check in the code.... telemetry helper is already deciding, what to do based on the connection policy....

2023-08-19 17:17 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +            if (this.telemetryToServiceHelper != null)
Agree that other components have this issue. Ideally then we should move down the httpclient right? (Can be a separate PR if needed). 

/cc: @ealsur thoughts?

2023-08-19 17:24 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Handler/ClientPipelineBuilder.cs
> +            if (telemetryToServiceHelper.IsClientTelemetryJobRunning())
What's the necessity of the pipeline conditional composition? 

If collection overhead is almost ignorable in-case of dynamic disable, then the same model be used here as well right? 
i.e. Handler will always be present the collector will ignore it. In that case the check in Pipelinebuiilder is unnecessary right? 

If above assumption is not true, few alternatives are
1. Pipeline is dynamically rebuilt: Today we don't modify the pipeline at-all. Its a much bigger impactful change. 
2. TelemetryHandler always present but will be a simple pass-through (i.e. no overhead) when disabled. 

In any case pipeline conditional composition is not required right?

2023-08-19 17:26 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/TelemetryToServiceHelper.cs
> +        public bool IsClientTelemetryJobRunning()
If eventually (i.e. after one more PR) pipeline will not be conditional then why to even start with it now?

check: https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4037#discussion_r1299228622

2023-08-19 17:30 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +            if (this.telemetryToServiceHelper != null)
Let's take this up as separate PR I will create a bug for this.

2023-08-21 01:50 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +            if (!data.RequestLatency.HasValue)
Added traces and comment.  It is not expected to have null latency, since it is `nullable`, hence put this null check.

2023-08-21 02:02 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Handler/ClientPipelineBuilder.cs
> +            if (telemetryToServiceHelper.IsClientTelemetryJobRunning())
removed the condition.

2023-08-21 02:02 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/TelemetryToServiceHelper.cs
> +        public bool IsClientTelemetryJobRunning()
removed this condition.

2023-08-21 02:05 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +            if (this.telemetryToServiceHelper != null)
We need to dispose it...as it is cancelling background client telemetry job. I have moved dispose of telemetry at the top..to get it disposed first.

2023-08-21 02:06 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/TelemetryToServiceHelper.cs
> +            this.clientTelemetry?.Dispose();
We need to dispose it...as it is cancelling background client telemetry job. I have moved dispose of telemetry at the top..to get it disposed first.

2023-08-21 19:55 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
> +                    throw new OperationCanceledException(string.Format($"Processor task with date as {0} is canceled as it did not finish in {1}", telemetryDate, timeout));
Exception inlining is okey, which is expected to materialize always anyways right?

2023-08-21 20:02 UTC, kirankumarkolli submitted a review, later dismissed

2023-08-22 15:05 UTC, kirankumarkolli approved these changes

2023-08-22 16:09 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Contracts/BenchmarkResults.json
> +  "MockedItemBenchmark.ReadItemNotExists;[Type=OfTWithDiagnosticsToString]": 64764.75,
Is it with collection OOF? 

Is it a clickstop to get back to with future PRs?

2023-08-22 17:01 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Contracts/BenchmarkResults.json
> +  "MockedItemBenchmark.ReadItemNotExists;[Type=OfTWithDiagnosticsToString]": 64764.75,
yes, it is when collection is OFF. 

I am not sure if it is due to any change in this PR and that too only for `ReadItemNotExists`. These numbers keep fluctuating.

2023-08-22 17:14 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Contracts/BenchmarkResults.json
> +  "MockedItemBenchmark.ReadItemNotExists;[Type=OfTWithDiagnosticsToString]": 64764.75,
https://github.com/Azure/azure-cosmos-dotnet-v3/issues/4049 created issue to track this. I will look into once all the functional PRs are merged.

2023-08-22 17:25 UTC, kirankumarkolli approved these changes

2023-08-22 17:25 UTC, merged