[Internal] Parallel Hedging: Adds Docs
Azure/azure-cosmos-dotnet-v3 pull request #4082
Opened 2023-09-14 00:07 UTC by NaluTripician

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Include samples if adding new API, and include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #IssueNumber

2023-09-14 00:15 UTC, kirankumarkolli commented on docs/Parallel Hedging Preview.md
> +client.UpdatePreferredRegions(new List<string>() { "West US", "East US" });
ObservableCollection is also one alternative. https://learn.microsoft.com/en-us/dotnet/api/system.collections.objectmodel.observablecollection-1?view=netstandard-2.0

2023-09-14 00:16 UTC, kirankumarkolli commented on docs/Parallel Hedging Preview.md
> +    SpeculativeProcessor = new ThresholdSpeculator(TimeSpan.FromMilliseconds(500))
Is SpeculativeProcessor a public contract CX can add/extend?

2023-09-14 00:17 UTC, kirankumarkolli commented on docs/Parallel Hedging Preview.md
> +client.DisableSpeculativeProcessing(); // Disables speculative processing
Request level granular is also one ASK. 
Assuming if we have that then are these APIs at Client scope still necessary?

2023-09-14 00:18 UTC, kirankumarkolli commented on docs/Parallel Hedging Preview.md
> +    LocationToRouteTo = "West US"
Will it be a single Region or Equivalent to PReferredRegions?

2023-09-14 20:47 UTC, NaluTripician commented on docs/Parallel Hedging Preview.md
> +    SpeculativeProcessor = new ThresholdSpeculator(TimeSpan.FromMilliseconds(500))
I think it might be better to have it be a private contract here. I will make it so it's only a private contract.

2023-09-14 21:57 UTC, FabianMeiswinkel commented on docs/Parallel Hedging Preview.md
> +    .WithSpeculativeProcessing(type: SpeculationType.Threshold, speculativeThreshold: TimeSpan.FromMilliseconds(500))
Remove Speculative/Speculation term everywhere

This has burned us already with Walmart - for customers "speculation" sounds too random. In Java we have used the term ThresholdBasedAvailabilityStartegy or something along those lines.

2023-09-14 21:58 UTC, FabianMeiswinkel commented on docs/Parallel Hedging Preview.md
> +    .WithSpeculativeProcessing(type: SpeculationType.Threshold, speculativeThreshold: TimeSpan.FromMilliseconds(500))
Like here
WithAvailabilityStrategy(AvailabilityStartegyType.Threshold) or such

2023-09-14 21:59 UTC, FabianMeiswinkel commented on docs/Parallel Hedging Preview.md
> +client.UpdatePreferredRegions(new List<string>() { "West US", "East US" });
Making this mutable is risky - in Java we have instead allowed specifying excluded regions (and made that mutable) as well as configurable per request options. Achieves the same - but hasn't the same implications of making preferred regions mutable everywhere

2023-09-14 22:00 UTC, FabianMeiswinkel commented on docs/Parallel Hedging Preview.md
> +client.DisableSpeculativeProcessing(); // Disables speculative processing
+1 requestOptions level override definitely is needed - especially for queries (but not just)

2023-09-14 22:06 UTC, FabianMeiswinkel commented on docs/Parallel Hedging Preview.md
> +    LocationToRouteTo = "West US"
Again - why do the opposite of Java (we used excluded regions here) - region to route to as an override owuld allow routing to a region which is not even in preferred regions?

I think it just opens a can of worms

2023-09-14 22:07 UTC, FabianMeiswinkel commented on docs/Parallel Hedging Preview.md
> +    RegionConsistencyLevel = new ObservableCollection<string, ConsistencyLevel>()
Wow - why is this needed?

2023-09-19 08:47 UTC, FabianMeiswinkel requested changes
As discussed - public API has too many inconsistencies with Java that have been discussed before and are pitfalls.

2023-09-27 20:51 UTC, jeet1995 commented on docs/Parallel Hedging Preview.md
> +};
This is more from a reusability perspective - you already have a user defined type in `AvailabilityStrategyOptions`. Can't we use this type and inject into `RequestOptions`?

2023-09-27 20:54 UTC, jeet1995 commented on docs/Parallel Hedging Preview.md
> +    AvailabilityStrategyFallbackConsistencyLevel = ConsistencyLevel.Eventual
This can be encapsulated by `AvailabilityStrategyOptions` as well right? Also, what are the consistency override semantics here - availability strategy level config overrides request level config overrides client level config?

2024-10-10 22:48 UTC, closed without merging