[Internal] Query: Detect disallowed queries using string match for Optimistic Direct Execution code path
Azure/azure-cosmos-dotnet-v3 pull request #4090
Opened 2023-09-15 21:00 UTC by akotalwar

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Include samples if adding new API, and include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Closing issues

To automatically close an issue: closes #IssueNumber

2023-09-15 23:01 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> +
Nit, unnecessary extra indentation.

2023-09-15 23:02 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> +            bool parsed = SqlQueryParser.TryParse(inputParameters.SqlQuerySpec.QueryText, out SqlQuery sqlQuery);
I think the conclusion in the meeting was to use string search for unsupported patterns.

2023-09-15 23:04 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/OptimisticDirectExecutionQueryBaselineTests.cs
> +                Assert.IsTrue(true);
>Assert.IsTrue(true); [](http://example.com/codeflow?start=16&length=20)

Nit, unnecessary.

2023-09-15 23:04 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/OptimisticDirectExecutionQueryBaselineTests.cs
> +            Assert.IsFalse(true);
>Assert.IsFalse(true); [](http://example.com/codeflow?start=12&length=21)

Please use Assert.Fail instead

2023-09-18 19:59 UTC, adityasa approved these changes
:shipit:

2023-09-18 20:02 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> +            string[] queryOperators = new string[] { "GROUPBY", "COUNT(", "MIN(", "MAX(", "DISTINCT" };
>GROUPBY [](http://example.com/codeflow?start=54&length=7)

This should be "GROUP BY", no?

2023-09-18 20:03 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> +            string[] queryOperators = new string[] { "GROUPBY", "COUNT(", "MIN(", "MAX(", "DISTINCT" };
>( [](http://example.com/codeflow?start=70&length=1)

I wouldn't include the parentheses since there could be a space between them.

2023-09-18 20:03 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> +                if (inputParameters.SqlQuerySpec.QueryText.Contains(clause))
Should we use case insensitive comparison?

2023-09-18 20:04 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> +            foreach (string clause in queryOperators)
I think using Regex would be better than the string search.

2023-09-18 20:05 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/OptimisticDirectExecutionQueryBaselineTests.cs
> +                query: "Select COUNT(1) + 5 FROM c",
>"Select COUNT(1) + 5 FROM c" [](http://example.com/codeflow?start=23&length=28)

Please add more coverage:
- each aggregate your code covers
- case sensitivity

2023-09-18 20:07 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> +                    PartitionedQueryExecutionInfo queryPlan = await CheckQueryValidityWithQueryPlanAsync(
>CheckQueryValidityWithQueryPlanAsync [](http://example.com/codeflow?start=68&length=36)

I was expecting this to be called from only the ODE codepath. Doing it earlier affects non-ODE codepaths in perpetuity.

2023-09-18 20:08 UTC, adityasa requested changes
Kindly take a look at earlier comments.

2023-09-19 16:43 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> +            string pattern = @"\s+(GROUP BY|COUNT|MIN|MAX|AVG|SUM|DISTINCT)\s*\(";
>  [](http://example.com/codeflow?start=40&length=1)

\s+

2023-09-19 16:46 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> +            if (Regex.IsMatch(inputParameters.SqlQuerySpec.QueryText, pattern, options))
>Regex.IsMatch [](http://example.com/codeflow?start=16&length=13)

Please avoid using this. Instead save a regex instance with the pattern and RegexOptions as a private static member of this class and reuse.

2023-09-19 16:48 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/OptimisticDirectExecutionQueryBaselineTests.cs
> +                "SELECT AVG(c.price) * 50 FROM c",
Also include GROUP BY, DISTINCT and examples with spaces/newline in them.

2023-09-19 16:48 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/OptimisticDirectExecutionQueryBaselineTests.cs
> +                    // Confirming that an exception is thrown for an unsupported query
Please assert the exception and exact message.

2023-09-20 21:57 UTC, neildsh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/OptimisticDirectExecutionQueryBaselineTests.cs
> +                ("SELECT   COUNT     (1)   + 5 FROM c", "Compositions of aggregates and other expressions are not allowed"),
>"Compositions of aggregates and other expressions are not allowed" [](http://example.com/codeflow?start=56&length=66)

please add a const string instead of repeating this literal

2023-09-20 21:57 UTC, neildsh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/OptimisticDirectExecutionQueryBaselineTests.cs
> +            List<(string, string)> testVariations = new List<(string, string)>
>testVariations [](http://example.com/codeflow?start=35&length=14)

Please consider adding cases with scalar subqueries like:

SELECT (SELECT VALUE COUNT(1) FROM a IN c.arr) as count
FROM c

2023-09-25 23:19 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/OptimisticDirectExecutionQueryBaselineTests.cs
> +            List<(string, string)> testVariations = new List<(string, string)>
Neat - allows more comprehensive coverage.
Nit, for readability:
List<(string Query, string ExpectedMessage)> testVariations = ...;

This allows L433 to be :
query: testCase.Query

And L458 to be:
Assert.IsTrue(ex.InnerException.Message.Contains(testCase.ExpectedMessage));

2023-09-25 23:21 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> +        private const string ValidQueryRegex = @"\s+(GROUP\s+BY\s+|COUNT\s*\(|MIN\s*\(|MAX\s*\(|AVG\s*\(|SUM\s*\(|DISTINCT\s+)";
>ValidQueryRegex [](http://example.com/codeflow?start=29&length=15)

ValidQueryPattern

2023-09-25 23:21 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> +        private static readonly Regex ValidQueryValidation = new Regex(ValidQueryRegex, RegexOptions.IgnoreCase | RegexOptions.Compiled);
>ValidQueryValidation [](http://example.com/codeflow?start=38&length=20)

ValidQueryRegex

2023-09-25 23:23 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> +            ITrace createQueryPipelineTrace = default)
> = default [](http://example.com/codeflow?start=43&length=10)

Is there a reason why you chose a default value? Won't we miss out on diagnostics since callers are passing in null.

2023-09-25 23:24 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> +                PartitionedQueryExecutionInfo queryPlanFromValidityCheck = await CheckQueryValidityWithQueryPlanAsync(
>queryPlanFromValidityCheck [](http://example.com/codeflow?start=46&length=26)

I am not too sure I fully get the variable name.
Why not simply call queryPlan or partitionedQueryExecutionInfo?

2023-09-25 23:32 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> +        private static async Task<PartitionedQueryExecutionInfo> CheckQueryValidityWithQueryPlanAsync(
IMHO, the method contract+naming can be improved. Typically Check* methods would be expected to return true/false.

I would call this
private static async Task<bool> ForceSpecializedPipeline(..., out PartitionedQueryExecutionInfo queryPlan)

and modify callsite accordingly (something like:)
bool forceSpecializedPipeline = await this.ForceSpecializedPipeline(...)
if(forceSpecializedPipeline)
{
 . . .
}

2023-09-26 18:31 UTC, neildsh commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> +            ITrace createQueryPipelineTrace = default)
>ITrace [](http://example.com/codeflow?start=12&length=6)

A method should not take more than one ITrace parameter

2023-09-26 18:34 UTC, neildsh commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> +        private static async Task<PartitionedQueryExecutionInfo> CheckQueryValidityWithQueryPlanAsync(
>CheckQueryValidityWithQueryPlanAsync [](http://example.com/codeflow?start=65&length=36)

This method has a single call site and a single if block in the body. Please inline the method at the call site. Having it separate hurts readability in addition to Aditya's comments regarding naming.

2023-09-27 17:47 UTC, akotalwar commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> +            ITrace createQueryPipelineTrace = default)
The test did not report any issues because the production environment lacked a caller that would provide both a null query plan and a null trace. Instead, out of the 2 prod callers, one caller provided a query plan with a null trace, while the other provided a valid trace but no query plan. As a result, the new code would not trigger a null reference exception. To encounter such an exception, we would need a prod caller that provides neither a query plan nor a trace. Therefore, this is not a matter of insufficient test coverage.

2023-09-27 18:13 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> +                        documentContainer,
As discussed, please remove.

2023-09-27 18:14 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> +                if (QueryInspectionRegex.IsMatch(inputParameters.SqlQuerySpec.QueryText))
The two if conditions can be merged into a single if.

2023-09-27 18:26 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/OptimisticDirectExecutionQueryBaselineTests.cs
> +                TryCatch<PartitionedQueryExecutionInfo> queryPlan = TryGetPartitionedQueryExecutionInfo(sqlQuerySpecJsonString, input.PartitionKeyDefinition);
Please double check if/why we need to retrieve the query plan in test code for any cases. It would be ideal to have product code logic exercised through all test methods (and not just the new ones you added).

2023-09-27 19:43 UTC, adityasa commented
>         public override async Task<TryCatch<PartitionedQueryExecutionInfo>> TryGetPartitionedQueryExecutionInfoAsync(SqlQuerySpec sqlQuerySpec, ResourceType resourceType, PartitionKeyDefinition partitionKeyDefinition, bool requireFormattableOrderByQuery, bool isContinuationExpected, bool allowNonValueAggregateQuery, bool hasLogicalPartitionKey, bool allowDCount, bool useSystemPrefix, Cosmos.GeospatialType geospatialType, CancellationToken cancellationToken)

Can you remove this method, since there are no callers?

---
Refers to: Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/OptimisticDirectExecutionQueryBaselineTests.cs:1098 in fd83c7b. [](commit_id = fd83c7bb9139e040613dba0cff7caa3ec6c9a80c, deletion_comment = False)

2023-09-27 19:44 UTC, adityasa approved these changes
:shipit:

2023-09-28 18:09 UTC, neildsh approved these changes
:shipit:

2023-09-28 18:11 UTC, neildsh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/OptimisticDirectExecutionQueryBaselineTests.cs
> +                Assert.Fail();
>Assert.Fail(); [](http://example.com/codeflow?start=16&length=14)

[Nit] Move this to line 445 to make it easier to read, and add an error message

2023-09-28 18:11 UTC, neildsh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/OptimisticDirectExecutionQueryBaselineTests.cs
> +                    description: @"Unsupported queries in CosmosDB that were previousely supported by Ode pipeline and returning wrong resutls",
>resutls [](http://example.com/codeflow?start=135&length=7)

[Nit] typo

2023-09-28 18:12 UTC, neildsh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/OptimisticDirectExecutionQueryBaselineTests.cs
> +                    description: @"Unsupported queries in CosmosDB that were previousely supported by Ode pipeline and returning wrong resutls",
>previousely [](http://example.com/codeflow?start=77&length=11)

[Nit] typo

2023-09-28 18:12 UTC, neildsh commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/OptimisticDirectExecutionQueryBaselineTests.cs
> +        // these queries with previous ODE implementation would have succedded. However, with the new query validity check, they should all throw an exception
>succedded [](http://example.com/codeflow?start=69&length=9)

[Nit] typo

2023-09-28 19:03 UTC, merged