[Internal] Query: Remove ForcePassThrough support
Azure/azure-cosmos-dotnet-v3 pull request #4160
Opened 2023-10-26 23:47 UTC by akotalwar

# Pull Request Template

## Description
Removing forcePassThrough from the codebase. It is dead code and does not support any actual user cases. 
Further, with the addition of Ode, we don't need forcePassThrough ability anymore

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #IssueNumber

2023-10-30 21:01 UTC, neildsh commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> -                    // This is to short circuit the need to go to the gateway to get the query plan.
Why is this code being removed? It is not dead and does not rely on ForcePassthrough

2023-10-30 23:46 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
>              bool createPassthroughQuery = streamingSinglePartitionQuery || streamingCrossContinuationQuery;
>createPassthroughQuery [](http://example.com/codeflow?start=17&length=22)

Is this required?

2023-10-30 23:46 UTC, adityasa commented
>                     tryCreatePipelineStage = CosmosQueryExecutionContextFactory.TryCreatePassthroughQueryExecutionContext(

Is this required?

---
Refers to: Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs:294 in 9ac78f9. [](commit_id = 9ac78f9a94582f30a32f48cbf956560d76645d26, deletion_comment = False)

2023-10-30 23:47 UTC, adityasa requested changes
:clock1:

2023-10-31 07:50 UTC, neildsh commented
>         public override async Task<TryExecuteQueryResult> TryExecuteQueryAsync(

Can we remove this method? I believe that you already removed the caller in Compute gateway

---
Refers to: Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs:343 in 9ac78f9. [](commit_id = 9ac78f9a94582f30a32f48cbf956560d76645d26, deletion_comment = False)

2023-10-31 07:51 UTC, neildsh approved these changes
:shipit:

2023-11-02 00:21 UTC, neildsh submitted a review, later dismissed

2023-11-02 22:16 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> +                || ((partitionedQueryExecutionInfo.QueryRanges.Count == 1)
Indent, please.

2023-11-02 22:16 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> +                && partitionedQueryExecutionInfo.QueryRanges[0].IsSingleValue);
Indent, please.

2023-11-02 22:16 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> +                    serverStreamingQuery
I would start this expression in the previous line after = for consistency with rest of the code.

2023-11-02 22:20 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/SanityQueryTests.cs
> -        public async Task TestTryExecuteQuery()
Could you kindly confirm that these cases are already covered by existing tests (ODE v/s non-ODE)?

2023-11-02 22:23 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> +                bool streamingSinglePartitionQuery = singleLogicalPartitionKeyQuery && serverStreamingQuery;
I am not suggesting to do this as part of this change, but isn't this automatically false (since ODE will already handle single partition case above)?

If so this should turn into an assert?

2023-11-02 22:25 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
> +                bool streamingSinglePartitionQuery = singleLogicalPartitionKeyQuery && serverStreamingQuery;
There is a case where above may not be true (when continuation token is malformed), but in that case we could do the cleanup differently.

2023-11-02 22:27 UTC, adityasa approved these changes
:shipit:

2023-11-02 22:31 UTC, neildsh approved these changes

2023-11-03 14:13 UTC, ealsur approved these changes

2023-11-03 14:13 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInternal.cs
> -        public abstract Task<TryExecuteQueryResult> TryExecuteQueryAsync(
Is this not used by any of the internal access teams? (Compute)

2023-11-03 16:33 UTC, akotalwar commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInternal.cs
> -        public abstract Task<TryExecuteQueryResult> TryExecuteQueryAsync(
We removed it from there so it has no callers

2023-11-03 16:33 UTC, merged