Diagnostics: Adds constructor that merges several CosmosTraceDiagnostics Instances
Azure/azure-cosmos-dotnet-v3 pull request #4175
Opened 2023-11-07 19:19 UTC by NaluTripician

# Pull Request Template

## Description

This PR adds a constructor for `CosmosTraceDiagnostics` that takes in a list of `CosmosTraceDiagnostics` and merges them into one. This feature will be used for when parallel request hedging is added to the SDK as a way to have the full context for a request that sends out multiple parallel requests. 

## Type of change

Please delete options that are not relevant.

- [] New feature (non-breaking change which adds functionality)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #IssueNumber

2023-11-10 20:07 UTC, xinlian12 commented on Microsoft.Azure.Cosmos/src/Diagnostics/CosmosTraceDiagnostics.cs
> +                maxElpasedTime += trace.GetClientElapsedTime();
I think the elapsed time should be calculated based on the earliest starting time and the latest end time

2023-11-14 06:29 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
> +            CosmosTraceDiagnostics mergedDiagnostics1 = new CosmosTraceDiagnostics(new List<CosmosTraceDiagnostics>() { cosmosTraceDiagnostics1, cosmosTraceDiagnostics2 });
Why did you decide to with a constructor instead of a static function (something like CosmosTraceDiagnostics.Merge(arg1, arg2))? 
At least to me, it is not very clear by looking at the constructor that what is the functionality.

2023-11-22 17:37 UTC, NaluTripician commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
> +            CosmosTraceDiagnostics mergedDiagnostics1 = new CosmosTraceDiagnostics(new List<CosmosTraceDiagnostics>() { cosmosTraceDiagnostics1, cosmosTraceDiagnostics2 });
Replaced public constructor with a static method like you suggested.

2023-11-28 09:23 UTC, sourabh1007 commented
1. Just a suggestion, in this PR we are getting multiple diagnostics and then merging them into one. Did you explore, if it is possible to do it during collection itself and keep logic to generate JSON generic? 
2. Do we need `operation name` in each block?
3. can you please link a document which talks about the feature.

2023-12-04 19:28 UTC, NaluTripician commented
> 1. Just a suggestion, in this PR we are getting multiple diagnostics and then merging them into one. Did you explore, if it is possible to do it during collection itself and keep logic to generate JSON generic?
> 2. Do we need `operation name` in each block?
> 3. can you please link a document which talks about the feature.

1. Yes, for parallel request hedging, we need to send out the parallel requests on a layer before the diagnostics are created. This also aligns with what the Java SDK does. 
2.  For `operaton name` "child" diagnostic needs to have a name. Currently the default name is the operation name. 
3. I have linked the work item for this feature in the PR discription (#4179 )

2024-01-11 22:01 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Diagnostics/CosmosTraceDiagnostics.cs
> +            TraceSummary traceSummary = new TraceSummary();
Is the summary for every merge? 

ex: 
ReadItem -> Inside RequestInvoker, will it include a summary?
Queries -> Which might go multiple NW interactions, will every interaction have its own summary?

2024-01-11 22:25 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Diagnostics/CosmosTraceDiagnostics.cs
> +            TraceSummary traceSummary = new TraceSummary();
Summar of offline sync-up: For initial version having the simple version with hint/context to dis-ambiguate if it's a hedging or not is good enough.

2024-01-11 22:25 UTC, kirankumarkolli requested changes
Scope: Lets just have the hint about retrycontext

2024-01-22 17:01 UTC, kirankumarkolli commented
If the hedging is from ReqeustInvoker, then clientconfig will not be present there right? 
Just adding the traces should do to get started with right? 

Diagnostics might get repeated but that's something we can follow-up later. 
Thoughts?

2024-01-22 19:57 UTC, kirankumarkolli commented
> If the hedging is from ReqeustInvoker, then clientconfig will not be present there right? Just adding the traces should do to get started with right?
> 
> Diagnostics might get repeated but that's something we can follow-up later. Thoughts?

Follow-up from offline sync-up: Start with how the hedged diagnostics look like. Mostly only system info might be repeated and for initial preview we can live with it.

2024-08-15 23:03 UTC, closed without merging