[Internal] Per Partition Automatic Failover: Fixes Metadata Requests Retry Policy
Azure/azure-cosmos-dotnet-v3 pull request #4205
Opened 2023-12-06 22:34 UTC by kundadebdatta

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Include samples if adding new API, and include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Closing issues

To automatically close an issue: closes #IssueNumber

2023-12-08 20:42 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
> +                                                ? SubStatusCodes.PartitionKeyRangeGone
What does this change affect?

2023-12-08 20:44 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicyDefault.cs
> +            (TimeSpan.FromSeconds(10), TimeSpan.Zero),
Last should always be 65 seconds

2023-12-08 20:46 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Routing/PartitionKeyRangeCache.cs
> +                    new MetadataRequestThrottleRetryPolicy(
Why not use the ClientRetryPolicy?

2023-12-08 20:47 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/MetadataRequestThrottleRetryPolicy.cs
> +        public MetadataRequestThrottleRetryPolicy(
If we are adding a new policy that does a similar tihng to the ClientRetryPolicy:

* Why are we not using the ClientRetryPolicy? What is different on this one?
* Why not name it specifically for the scenario, like PartitionKeyRangeRetryPolicy?

2023-12-08 20:49 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Routing/PartitionKeyRangeCache.cs
> -        public async Task<PartitionKeyRange> TryGetRangeByPartitionKeyRangeIdAsync(string collectionRid,
Was this not used?

2023-12-08 20:49 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Routing/PartitionKeyRangeCache.cs
> +                    this.pkRangeLocationEndpoint = this.endpointManager.ResolveServiceEndpoint(request);
Should this be done on the OnBeforeSendRequest of the policy?

2023-12-09 00:42 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Routing/PartitionKeyRangeCache.cs
> -        public async Task<PartitionKeyRange> TryGetRangeByPartitionKeyRangeIdAsync(string collectionRid,
I tried to look for the usage of this particular methos, and found none. Therefore, it's better to clean-up the code.

2023-12-09 01:00 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/MetadataRequestThrottleRetryPolicy.cs
> +        public MetadataRequestThrottleRetryPolicy(
Great Question! Please see the responses below and let me know if this make sense:

> Why are we not using the ClientRetryPolicy? What is different on this one?

There are two reasons for this. 

- Firstly, the request scope for the `ClientRetryPolicy` is the `DocumentServiceRequest` intended for the **OperationType**: `Create` and **ResourceType**: `Document`, while the request scope for the `MetadataRequestThrottleRetryPolicy`  is the `DocumentServiceRequest` intended for the **OperationType**: `ReadFeed` and **ResourceType**: `PartitionKeyRange`. There are cases where the `locationendpointuri` for the two requests could be different, and it is required to `MarkEndpointUnavailableForRead()` applicable for the correct URI. To understand more on this, please take a [look at these lines](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/77bc01d14ff3794484767f68ecd4d7526cc5b1c1/Microsoft.Azure.Cosmos/src/Routing/PartitionKeyRangeCache.cs#L261-L283).

- Secondly, we wanted to create a separate retry policy applicable for all the metadata requests. This will give us more flexibility on the retry logic specifically for the metadata reads. Cc: @FabianMeiswinkel

2023-12-09 01:04 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Routing/PartitionKeyRangeCache.cs
> +                    this.pkRangeLocationEndpoint = this.endpointManager.ResolveServiceEndpoint(request);
Not really. We need to capture the `pkRangeLocationEndpoint`, at a point when the document service request is being created.

2023-12-11 19:29 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs
> +            if (exception is CosmosException cosmosException)
Please include code-doc

2023-12-11 19:33 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
> +                                                ? SubStatusCodes.PartitionKeyRangeGone
Also feels very hacky

2023-12-11 19:34 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicy.cs
> -            if (documentServiceRequest.ResourceType == ResourceType.PartitionKeyRange)
With this change, PkRange now uses default retry-policy right? Is this intended?

2023-12-11 19:35 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicyDefault.cs
> +            (TimeSpan.FromSeconds(3), TimeSpan.Zero),
Now with the change PkRange moved to default. 
Its unclear why default for everyone needs change.

2023-12-11 19:41 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Routing/PartitionKeyRangeCache.cs
> -        public async Task<PartitionKeyRange> TryGetRangeByPartitionKeyRangeIdAsync(string collectionRid,
Even in master there is no reference. 
@kundadebdatta how about moving cleanup into a separate PR?

2023-12-11 19:42 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/MetadataRequestThrottleRetryPolicy.cs
> +        public MetadataRequestThrottleRetryPolicy(
Can we please go over the design once with team?

2023-12-13 18:54 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/MetadataRequestThrottleRetryPolicy.cs
> +        public MetadataRequestThrottleRetryPolicy(
> he request scope for the ClientRetryPolicy is the DocumentServiceRequest intended for the OperationType: Create and ResourceType: Document, while the request scope for the MetadataRequestThrottleRetryPolicy is the DocumentServiceRequest intended for the OperationType: ReadFeed and ResourceType: PartitionKeyRange.

What I mean is, why not wrap this operation in a `new ClientRetryPolicy`.

2023-12-13 18:55 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Routing/PartitionKeyRangeCache.cs
> +                    this.pkRangeLocationEndpoint = this.endpointManager.ResolveServiceEndpoint(request);
OnBeforeSendRequest receives the DocumentServiceRequest when it is created

2023-12-13 20:09 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/MetadataRequestThrottleRetryPolicy.cs
> +        public MetadataRequestThrottleRetryPolicy(
So, the `ClientRetryPolicy` has it's own implementation of `ShouldRetryAsync()` , `OnBeforeSendRequest()` which is not really applicable for the Get PkRange flow. Therefore, I would prefer to use the `MetadataRequestThrottleRetryPolicy`.

Happy to discuss this further, if needed.

2023-12-15 00:48 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicy.cs
> -            if (documentServiceRequest.ResourceType == ResourceType.PartitionKeyRange)
+1 PKRange FeedRange should still use hot path? like retry pretty aggressively?

2023-12-15 00:49 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicyDefault.cs
> +            (TimeSpan.FromSeconds(3), TimeSpan.Zero),
+1 - If we can't use default or hot better to create one explicitly for PkRange

2023-12-15 00:50 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicyDefault.cs
> +            (TimeSpan.FromSeconds(3), TimeSpan.Zero),
BUt I guess you also wanted to be more aggressive for collection read? Which I agree with - just still better to carve out an extra policy for those two vs. changing the default

2023-12-15 00:50 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicyDefault.cs
> +            (TimeSpan.FromSeconds(10), TimeSpan.Zero),
+1

2023-12-15 00:53 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/MetadataRequestThrottleRetryPolicy.cs
> +        public MetadataRequestThrottleRetryPolicy(
I agree with @kundadebdatta to have a separate retry policy - we did the same in Java - because this retry policy unlike ClientRetryPolicy is not applied on the entire SDK operation - but individual metadata requests. And I also agree that the name should not be specific to PKRange - same retry strategy should be applied for Collection-read (CollectionName -> CollectionRid mapping) as well - and like said there will probably be others (reading throughput/offer if we ever add client throughput control in .Net etc.)

2023-12-15 00:56 UTC, FabianMeiswinkel reviewed
LGTM except for few small issues

2023-12-19 02:51 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicyDefault.cs
> +            (TimeSpan.FromSeconds(3), TimeSpan.Zero),
Correct. The idea was to make the default policy to be more aggressive, so that the gateway calls, for e.g. `Read Collection` can fail faster. I have updated the last one to be 65 seconds, so that the call gets enough time to be successful or time out!

2023-12-19 02:51 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Routing/PartitionKeyRangeCache.cs
> +                    new MetadataRequestThrottleRetryPolicy(
The rationale has been explained below.

2023-12-19 02:53 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Routing/PartitionKeyRangeCache.cs
> -        public async Task<PartitionKeyRange> TryGetRangeByPartitionKeyRangeIdAsync(string collectionRid,
@kirankumarkolli : This is just one single method, which is deprecated/ removed. There are no impacts to the test project due to this. Therefore, I feel keeping this single change/ clean-up in this PR itself, should be good enough.

2023-12-19 20:05 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/MetadataRequestThrottleRetryPolicy.cs
> +        public MetadataRequestThrottleRetryPolicy(
Makes sense. My concern was mainly duplicated failover logic

2023-12-19 20:46 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs
> +            if (exception is CosmosException cosmosException)
Added in-line code doc.

2023-12-19 20:47 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Routing/PartitionKeyRangeCache.cs
> +                    this.pkRangeLocationEndpoint = this.endpointManager.ResolveServiceEndpoint(request);
Refactored the code to set this within the `OnBeforeSendRequest()` method.

2023-12-19 23:35 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicyDefault.cs
> +            (TimeSpan.FromSeconds(10), TimeSpan.Zero),
Refactored the code. I have created a separate TimeoutPolicy specifically for the metadata reads.

2023-12-19 23:37 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicyDefault.cs
> +            (TimeSpan.FromSeconds(3), TimeSpan.Zero),
Refactored the code to create a separate timeout policy for metadata reads. The default policy is now stays the same.

2023-12-21 16:20 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Routing/PartitionKeyRangeCache.cs
> +                    retryPolicy?.OnBeforeSendRequest(request);
nit: is `retryPolicy` expected to be `null` ever?

2023-12-21 20:54 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
> +                                                ? SubStatusCodes.PartitionKeyRangeGone
I have refactored the code to throw `TransportGenerated503` as the sub status code. Therefore, this piece of the code is now unchanged.

2023-12-21 20:58 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicy.cs
> -            if (documentServiceRequest.ResourceType == ResourceType.PartitionKeyRange)
This change (basically using the `HttpTimeoutPolicyControlPlaneRetriableHotPath`) was originally intended for the address resolution calls, and not the Pk Range calls. The PkRange calls will now utilize the `MetadataRequestThrottleRetryPolicy` which should throw a 503 on timeout, and therefore, it can be retried, which is exactly we intend to achieve.

2023-12-21 21:21 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicyMetadataRead.cs
> +            this.shouldThrow503OnTimeout = shouldThrow503OnTimeout;
Is there a case where this is false? If not, then simply remove this from the constructor and rename InstanceShouldThrow503OnTimeout to Instance, have a single one.

The reason this bool exists in other policies is for cases where the same policy is used to throw 503 or not. In this case, it is not needed as it will always throw 503.

2023-12-21 21:22 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicyMetadataRead.cs
> +            (TimeSpan.FromSeconds(10), TimeSpan.Zero),
Last one should always be 65

2023-12-21 21:23 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicy.cs
> -            if (documentServiceRequest.ResourceType == ResourceType.PartitionKeyRange)
Isn't HttpTimeoutPolicyControlPlaneRetriableHotPat good enough for PKRanges? Maybe add an OR here and use a single one?

2023-12-21 21:25 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/MetadataRequestThrottleRetryPolicy.cs
> +                && cosmosException.Headers.SubStatusCode == SubStatusCodes.TransportGenerated503)
This only covers 503s from transient connectivity, not 503s from the service. This marks the entire region as unavailable for read, which is something we do not do on ClientRetryPolicy. Why are we doing it for this one?

2023-12-21 21:26 UTC, ealsur requested changes
Waiting on the policy behavior that marks the region as unavailable on 503s. We explicitly document publicly we do not do this: https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/troubleshoot-sdk-availability#transient-connectivity-issues-on-tcp-protocol

2023-12-22 17:40 UTC, ealsur reviewed
Unblocking the PR as changes are coming

2023-12-22 20:52 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/MetadataRequestThrottleRetryPolicy.cs
> +                && cosmosException.Headers.SubStatusCode == SubStatusCodes.TransportGenerated503)
I thought about it, and you are right. We should not mark the entire region as unavailable for reads. Therefore, I have refactored the code to tweak the logic a bit. The new logic is to increment the location index when such exception occurs so that the metadata request could be retried on the next preferred region, instead of marking that region unavailable for reads.

2023-12-22 20:53 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicyMetadataRead.cs
> +            (TimeSpan.FromSeconds(10), TimeSpan.Zero),
Updated.

2023-12-22 20:54 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicyMetadataRead.cs
> +            this.shouldThrow503OnTimeout = shouldThrow503OnTimeout;
I still feel we should keep this, because tomorrow we are going to use this retry policy for other metadata calls, where such case could appear to have `shouldThrow503OnTimeout` as false. Therefore, I am inclined towards keeping this change.

2023-12-22 20:55 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Routing/PartitionKeyRangeCache.cs
> +                    retryPolicy?.OnBeforeSendRequest(request);
Should not be, but keeping this check adds extra null check validation, which doesn't harm.

2023-12-22 20:57 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicy.cs
> -            if (documentServiceRequest.ResourceType == ResourceType.PartitionKeyRange)
Not really, because `HttpTimeoutPolicyControlPlaneRetriableHotPath` does not have the logic to throw 503 on timeout, which is needed to retry the request from MetadataRetry policy.

2023-12-22 21:01 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicyMetadataRead.cs
> +            this.shouldThrow503OnTimeout = shouldThrow503OnTimeout;
The key with policies and 503 is if the policy handles also writes, you dont want to retry writes from timeouts. If the policy is only for reads, then I don't see any scenario where you would not retry?

2023-12-22 21:03 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicy.cs
> -            if (documentServiceRequest.ResourceType == ResourceType.PartitionKeyRange)
Yes it does, use HttpTimeoutPolicyControlPlaneRetriableHotPath.InstanceShouldThrow503OnTimeout

2023-12-22 21:03 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicy.cs
> -            if (documentServiceRequest.ResourceType == ResourceType.PartitionKeyRange)
You can have one for Addresses, one for PKRanges. The one for addresses is the `....Instance` and the one for PKRanges is `....InstanceShouldThrow503OnTimeout`

2023-12-22 21:06 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/MetadataRequestThrottleRetryPolicy.cs
> +        private const int DefaultMaxWaitTimeInSeconds = 60;
If the max retry is 60 seconds but the underlying retry policy has 3 retries, last one with 65 seconds, shouldn't this number be larger? Otherwise, there might not be 3 retries?

2023-12-22 21:17 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/MetadataRequestThrottleRetryPolicy.cs
> +            request.RequestContext.ClearRouteToLocation();
`if (this.retryContext != null)`

2023-12-22 21:20 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Routing/PartitionKeyRangeCache.cs
> +                    retryPolicy?.OnBeforeSendRequest(request);
I would validate then with a null check and throw if its null (ArgumentNullException). If its null in a production execution, then the retries are broken. Better to know that we introduced a bug than silently be disabling retries

2023-12-22 21:20 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/MetadataRequestThrottleRetryPolicy.cs
> +            request.RequestContext.ClearRouteToLocation();
`retryContext` is always initialized in the constructor. It can't be null in any way:

```
            this.retryContext = new MetadataRetryContext
            {
                RetryLocationIndex = 0,
                RetryRequestOnPreferredLocations = true,
            };
```

2023-12-22 21:21 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/MetadataRequestThrottleRetryPolicy.cs
> +            request.RequestContext.ClearRouteToLocation();
Im blind, sorry

2023-12-22 21:48 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/MetadataRequestThrottleRetryPolicy.cs
> +        private const int DefaultMaxWaitTimeInSeconds = 60;
This is true for the original throttle retry policy actually: see[ these line of codes](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/5a096d11369124f85063747e7b767e0e9a400114/Microsoft.Azure.Cosmos/src/ResourceThrottleRetryPolicy.cs#L17) for details. 
 
and our `ClientRetryPolicy` has the value `RetryOptions.DefaultMaxRetryWaitTimeInSeconds` = 30.

2023-12-22 21:57 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicy.cs
> -            if (documentServiceRequest.ResourceType == ResourceType.PartitionKeyRange)
Discussed offline - I have removed the `HttpTimeoutPolicyMetadataRead` and used the `HttpTimeoutPolicyControlPlaneRetriableHotPath.InstanceShouldThrow503OnTimeout` instead. This will keep the metadata requests in sync. Also we could use this timeout policy for all the metadata reads.

Cc: @FabianMeiswinkel.

2023-12-22 21:58 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Routing/PartitionKeyRangeCache.cs
> +                    retryPolicy?.OnBeforeSendRequest(request);
`retryPolicy.OnBeforeSendRequest` should cover this. Refactored.

2023-12-22 21:59 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicyMetadataRead.cs
> +            this.shouldThrow503OnTimeout = shouldThrow503OnTimeout;
Discussed offline - I have removed the `HttpTimeoutPolicyMetadataRead` and used the `HttpTimeoutPolicyControlPlaneRetriableHotPath.InstanceShouldThrow503OnTimeout` instead. This will keep the metadata requests in sync. Also we could use this timeout policy for all the metadata reads.

2023-12-22 22:38 UTC, ealsur approved these changes

2023-12-22 22:38 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicy.cs
> +                return HttpTimeoutPolicyControlPlaneRetriableHotPath.InstanceShouldThrow503OnTimeout;
Consider adding an if for PKRanges, not changing the one for all. If we want to adjust the one for other cases like Read Collection, we can do it separately?

2023-12-27 12:32 UTC, FabianMeiswinkel approved these changes
LGTM now

2023-12-27 20:17 UTC, xinlian12 commented on Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs
> +            if (exception is CosmosException cosmosException)
why this handling is still needed when the retry behavior is handled in MetadataRequestThrottleRetryPolicy

2023-12-27 20:23 UTC, xinlian12 commented on Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs
> +            if (exception is CosmosException cosmosException)
a side question, not related to this PR. 

for the pkRangesRequest, if it fails with taskCancellationException, which then converted into CosmosException 503, seems like the traces will be missed as this part only looks for DocumentClientException? 

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/77bc01d14ff3794484767f68ecd4d7526cc5b1c1/Microsoft.Azure.Cosmos/src/Routing/PartitionKeyRangeCache.cs#L312

2023-12-27 20:26 UTC, xinlian12 commented on Microsoft.Azure.Cosmos/src/MetadataRequestThrottleRetryPolicy.cs
> +        /// Marks an endpoint unavailable in the global endpoint manager, for any future read requests.
nit: conflicting of the comments and the logic - there is no marking region unavailable anymore.

2023-12-28 19:53 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs
> +            if (exception is CosmosException cosmosException)
This is needed to retry the `Read Collection` calls. Those calls still uses the `ClientRetryPolicy` to retry the requests, therefore this logic was needed. However, we have plans to use the `MetadataRequestThrottleRetryPolicy` for `Read Collection` calls in the future. At that point, this change won't be needed and we can very well remove it.

Regarding the second point, it will mark `this.partitionKeyRangeLocationCache.TryMarkEndpointUnavailableForPartitionKeyRange`, only when the request is a write request. See [these lines of code](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/5a096d11369124f85063747e7b767e0e9a400114/Microsoft.Azure.Cosmos/src/Routing/GlobalPartitionEndpointManagerCore.cs#L108-L111) to understand more on this.

2023-12-28 19:56 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs
> +            if (exception is CosmosException cosmosException)
This is a good point. Let me think about it. If needed, I will refactor the code to catch the `CosmosException`. Thanks for bringing this up Annie!

2023-12-28 22:02 UTC, xinlian12 commented on Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs
> +            if (exception is CosmosException cosmosException)
so then two questions, just want to check my understanding is correct:
1. In case the pkRangeCache requests to all regions have failed with timeout, then when the exception bubbled up to ClientRetryPolicy, it will be retried again right? 

```
Region A, B, C
Region A -> PkRangeCache in A, B C
ClientRetryPolicy -> Region B -> PkRangeCache in A, B, C
ClientRetryPolicy -> Region C -> PkRangeCache in A, B, C
```

2.  If the request is write operation, then it will trigger the flow TryMarkEndpointUnavailableForPartitionKeyRange? 

C WriteRequest -> due to cold start -> pkRangeCache -> retried in A, B, C all failed -> write request will fail with 503 -> exception being bubbled up to ClientRetryPolicy -> mark the endpoint unavailable for pkRange

2023-12-28 23:24 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs
> +            if (exception is CosmosException cosmosException)
- If the `pkRangeCache requests` fails in all the regions, then there will be no retry because the SDK has failed to get the PK range information and therefore the client initialization will fail. The exception message will look like this: `Exception Occurred: One or more errors occurred. (Response status code does not indicate success: ServiceUnavailable (503); Substatus: 20003`

- The flow will look like this: WriteRequest -> due to cold start -> pkRangeCache -> retried in A, B, C all failed -> Get Pk Range request will fail with 503 -> exception being bubbled up to ClientRetryPolicy -> mark the endpoint unavailable for pkRange (this won't happen because there will be no pk range information fetched) --> Client Initialization will fail.

2023-12-29 18:09 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/MetadataRequestThrottleRetryPolicy.cs
> +        /// Marks an endpoint unavailable in the global endpoint manager, for any future read requests.
Addressed.

2023-12-29 18:09 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs
> +            if (exception is CosmosException cosmosException)
I have added the trace handling for the `CosmosException`.

2023-12-29 18:58 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicy.cs
> +                return HttpTimeoutPolicyControlPlaneRetriableHotPath.InstanceShouldThrow503OnTimeout;
Refactored the code to reflect the change.

2023-12-29 19:49 UTC, xinlian12 approved these changes
LGTM, thanks

2023-12-30 12:51 UTC, FabianMeiswinkel approved these changes
LGTM - Thanks

2023-12-30 12:51 UTC, merged