Users/nalutripician/3.37.1
Azure/azure-cosmos-dotnet-v3 pull request #4231
Opened 2024-01-02 19:51 UTC by NaluTripician

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Include samples if adding new API, and include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #IssueNumber

2024-01-02 20:40 UTC, kundadebdatta approved these changes
LGTM!

2024-01-02 21:34 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +                if (Interlocked.Increment(ref this.disposeCounter) == 1)
Is it done as safe practice? (AFAIR its not followed in other places)

2024-01-02 21:34 UTC, kirankumarkolli submitted a review, later dismissed

2024-01-02 21:55 UTC, NaluTripician commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +                if (Interlocked.Increment(ref this.disposeCounter) == 1)
I believe so, yes. Please look at Fabian's comment on the original PR. https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4226#discussion_r1437594014

2024-01-03 15:32 UTC, ealsur requested changes
No code changes in version bump/release PRs

2024-01-03 15:56 UTC, ealsur commented on changelog.md
> +
nit: remove empty line

2024-01-03 15:57 UTC, ealsur approved these changes

2024-01-03 16:02 UTC, ealsur approved these changes

2024-01-03 18:40 UTC, kundadebdatta approved these changes

2024-01-03 18:40 UTC, merged