RequestOptions: Fixes API Documentation for `RequestOptions.IfMatchEtag`
Azure/azure-cosmos-dotnet-v3 pull request #4249
Opened 2024-01-11 18:59 UTC by kundadebdatta

# Pull Request Template

## Description

This PR fixes the API documentation for `RequestOptions.IfMatchEtag`.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Closing issues

To automatically close an issue: closes #IssueNumber

2024-01-11 19:05 UTC, ealsur approved these changes
Please link issues to close them

2024-01-11 19:07 UTC, philipthomas-MSFT submitted a review, later dismissed
LGTM

2024-01-11 19:22 UTC, NaluTripician approved these changes

2024-01-11 20:37 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/RequestOptions/RequestOptions.cs
> +        /// Most commonly used with the Delete* and Replace* methods of <see cref="Container"/> such as <see cref="Container.ReplaceItemAsync{T}(T, string, PartitionKey?, ItemRequestOptions, System.T
nit: How about also covering it part of ReadItem* code-doc remarks.

2024-01-11 23:41 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/RequestOptions/RequestOptions.cs
> +        /// Most commonly used with the Delete* and Replace* methods of <see cref="Container"/> such as <see cref="Container.ReplaceItemAsync{T}(T, string, PartitionKey?, ItemRequestOptions, System.T
Added the code doc on `ContainerInlineCore.ReadItemAsync()`

2024-01-12 15:40 UTC, ealsur requested changes

2024-01-12 15:40 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInlineCore.cs
> +            // Currently, ReadItemAsync does not support the use of RequestOptions.IfMatchEtag property.
I think Kiran meant on the public API of ReadItem, which is in Container (that is the public class). This comment here does not appear on the public docs

2024-01-12 20:06 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInlineCore.cs
> +            // Currently, ReadItemAsync does not support the use of RequestOptions.IfMatchEtag property.
Make sense. I have refactored the code to reflect the API doc update.

2024-01-12 21:06 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/RequestOptions/RequestOptions.cs
> +        /// Most commonly used with the Delete* and Replace* methods of <see cref="Container"/> such as <see cref="Container.ReplaceItemAsync{T}(T, string, PartitionKey?, ItemRequestOptions, System.T
Patch I think also supports it?

2024-01-12 21:07 UTC, ealsur approved these changes
LGTM. Just left a nit regarding new line handling

2024-01-12 21:07 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +        /// the usage of <see cref="RequestOptions.IfMatchEtag"/> property at the moment.
```suggestion
        /// Note that, this API does not support the usage of <see cref="RequestOptions.IfMatchEtag"/> property at the moment.
```

2024-01-12 21:07 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +        /// * "ttl": Gets the time to live in seconds of the item in the Azure Cosmos DB service. Note that, this API does not support
```suggestion
        /// * "ttl": Gets the time to live in seconds of the item in the Azure Cosmos DB service.
```

2024-01-12 21:58 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/RequestOptions/RequestOptions.cs
> +        /// Most commonly used with the Delete* and Replace* methods of <see cref="Container"/> such as <see cref="Container.ReplaceItemAsync{T}(T, string, PartitionKey?, ItemRequestOptions, System.T
Not sure on that @FabianMeiswinkel. Do you want me to cover that as well? Cc: @ealsur , @kirankumarkolli.

2024-01-12 23:45 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/RequestOptions/RequestOptions.cs
> +        /// Most commonly used with the Delete* and Replace* methods of <see cref="Container"/> such as <see cref="Container.ReplaceItemAsync{T}(T, string, PartitionKey?, ItemRequestOptions, System.T
If Patch supports it, sure

2024-01-16 21:31 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +        /// the usage of <see cref="RequestOptions.IfMatchEtag"/> property at the moment.
Updated.

2024-01-16 21:31 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +        /// * "ttl": Gets the time to live in seconds of the item in the Azure Cosmos DB service. Note that, this API does not support
Updated.

2024-01-16 21:57 UTC, ealsur submitted a review, later dismissed

2024-01-16 22:17 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +        /// Note that, this API does not support the usage of <see cref="RequestOptions.IfMatchEtag"/> property at the moment.
Similar to above can we please move this to <remarks> section?

2024-01-16 22:17 UTC, kirankumarkolli approved these changes

2024-01-16 22:25 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +        /// Note that, this API does not support the usage of <see cref="RequestOptions.IfMatchEtag"/> property at the moment.
This is already in `<remarks>` what section would it go to?

2024-01-17 00:51 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/RequestOptions/RequestOptions.cs
> +        /// Most commonly used with the Delete* and Replace* methods of <see cref="Container"/> such as <see cref="Container.ReplaceItemAsync{T}(T, string, PartitionKey?, ItemRequestOptions, System.T
Added relevant documentation in `<remarks>` section.

2024-01-17 01:06 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +        /// Note that, this API does not support the usage of <see cref="RequestOptions.IfMatchEtag"/> property at the moment.
Apologies :-)

2024-01-17 01:07 UTC, kirankumarkolli approved these changes

2024-01-17 14:58 UTC, ealsur approved these changes

2024-01-17 17:50 UTC, merged