CosmosClientOptions: Adds Custom Domain Names
Azure/azure-cosmos-dotnet-v3 pull request #4265
Opened 2024-01-19 00:24 UTC by kundadebdatta

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Include samples if adding new API, and include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #IssueNumber

2024-01-23 23:26 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs
> +        public void SetRegionalEndpoints(
Pattern: All existing pattern for get and set is pattern. 
Do RegionalEndpoints really need different pattern?

2024-01-23 23:27 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs
> +        /// Sets the regional endpoints required to fetch account information from
Region endpoint is a new concept and lets cover more context. 
Call out with an example and in which scenario this needs to be used.

2024-01-23 23:41 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        /// During the CosmosClient initialization the account information, including the available regions, is obtained from the <see cref="CosmosClient.Endpoint"/>.
Please call out when to use this API? 
Region endpoints is kind of relatively new concept and needs more explanation and when to use it.

2024-01-23 23:43 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        public ISet<string> RegionalEndpoints { get; set; }
IEnumerable might be a based denomintor we can use right? Is ISet really needed?

2024-01-23 23:53 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/GatewayAccountReader.cs
> +                    AccountProperties databaseAccount = await GlobalEndpointManager.GetDatabaseAccountFromAnyLocationsAsync(
Conceptually, we can imagine that `this.serviceEndpointEnumerator` is either user given or system populated and GlobalEndpointManager.TryGetAccountPropertiesFromAllLocationsAsync should use it.

2024-01-24 04:39 UTC, kirankumarkolli requested changes
Conceptually, we can imagine that this.serviceEndpointEnumerator is either user given or system populated and GlobalEndpointManager.TryGetAccountPropertiesFromAllLocationsAsync should use it

2024-01-24 23:20 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        /// Nevertheless, this parameter remains optional and is recommended for implementation when a customer has configured a private endpoint for their Cosmos DB account.
```suggestion
        /// Nevertheless, this parameter remains optional and is recommended for implementation when a customer has configured a private endpoint with a custom DNS hostname (instead of accountname-region.documents.azure.com) etc. for their Cosmos DB account.
```

2024-01-24 23:20 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
> +        ///  This function is optional and is recommended for implementation when a customer has configured one or more private endpoints for their Cosmos DB account.
Dito - note of custom DNS records

2024-01-24 23:23 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/GatewayAccountReader.cs
> +                    AccountProperties databaseAccount = await GlobalEndpointManager.GetDatabaseAccountFromAnyLocationsAsync(
I discussed this with Debdatta oflline - I am ok with either using GlobalEndpoint, RegionalEndpoints, GeneratedEndpointsBasedoOnEffectivePreferredRegions - or if (!RegionalEndpoints.IsEmpty) { Global endpoints + regional Endpoints) else { global endpoints + generated Regional Endpoints based on effective preferred regions)

2024-01-24 23:25 UTC, FabianMeiswinkel requested changes
LGTM except for the one open issue around picking the right set of endpoints to reach out to, to get account info

2024-01-25 07:59 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        public ISet<string> RegionalEndpoints { get; set; }
The original purpose of using `ISet` was avoid confusion on the ordering. However, this can be replaced by the `IEnumerable` as well. Therefore refactored the code to reflect the same.

2024-01-25 08:00 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        /// Nevertheless, this parameter remains optional and is recommended for implementation when a customer has configured a private endpoint for their Cosmos DB account.
Updated the verbiage.

2024-01-25 08:00 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
> +        ///  This function is optional and is recommended for implementation when a customer has configured one or more private endpoints for their Cosmos DB account.
Updated the verbiage.

2024-01-25 08:02 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/GatewayAccountReader.cs
> +                    AccountProperties databaseAccount = await GlobalEndpointManager.GetDatabaseAccountFromAnyLocationsAsync(
Refactored the code based on the above suggestions. Per my conversation with @FabianMeiswinkel, the SDK should first attempt to fetch the account information from the global and regional endpoints. If the attempts are un-successful, the SDK will then append the preferred regions with the default endpoint and re-attempt to fetch the account information.

2024-01-25 14:00 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +                tasksToWaitOn.Add(this.TryGetAccountPropertiesFromAllLocationsAsync());
Sorry - I do not get this. Why start the same task twice? - I know it was done before - still don't understand why?

2024-01-25 15:54 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        public IEnumerable<string> RegionalEndpoints { get; set; }
Why is it called RegionalEndpoints? How do we know these are pointing to a Regional endpoint? Or are they "Custom DNS endpoints"? If these were RegionalEndpoints then they should have a region attached, for exmaple:

`RegionalEndpoints = { (WestUS, "http://customdns", EastUS, "http://customdns2")};`

2024-01-26 00:51 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        public IEnumerable<string> RegionalEndpoints { get; set; }
As discussed offline, I have updated the API naming to `AccountInitializationCustomEndpoints`.

2024-01-26 02:45 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +                tasksToWaitOn.Add(this.TryGetAccountPropertiesFromAllLocationsAsync());
Agreed, No clue why was it added twice. IMO, keeping any one of these would suffice. If we all agree, I will remove the other duplicate task. Thoughts @ealsur , @kirankumarkolli ?

2024-01-26 16:10 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +                tasksToWaitOn.Add(this.TryGetAccountPropertiesFromAllLocationsAsync());
The reasoning I believe is because this uses an Enumerator as input, so it starts 2 parallel loops that drain from the same enumerator https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2355

2024-01-26 16:11 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        public IEnumerable<string> RegionalEndpoints { get; set; }
Please update the PR title to remove "Regional"

2024-01-26 18:09 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        public IEnumerable<string> RegionalEndpoints { get; set; }
Updated the title and the description.

2024-01-26 18:10 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        /// During the CosmosClient initialization the account information, including the available regions, is obtained from the <see cref="CosmosClient.Endpoint"/>.
Added relevant description to the API doc.

2024-01-26 19:07 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        /// Gets and sets the custom private endpoints for geo-replicated database accounts in the Azure Cosmos DB service.
```suggestion
        /// Gets and sets the custom endpoints to use for account initialization for geo-replicated database accounts in the Azure Cosmos DB service. 
```

2024-01-26 19:08 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        /// Nevertheless, this parameter remains optional and is recommended for implementation when a customer has configured a private endpoint with a custom DNS hostname
```suggestion
        /// Nevertheless, this parameter remains optional and is recommended for implementation when a customer has configured a endpoint with a custom DNS hostname

```

2024-01-26 19:08 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
> +        /// <summary>
Replicate any documentation changes here too

2024-01-26 19:09 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/GatewayAccountReader.cs
> +                customPrivateEndpoints: this.connectionPolicy.CustomPrivateEndpoints,
Naming: consistent across

2024-01-26 19:24 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
>                  {
This needs to also cover for customendpoints right?

2024-01-26 19:28 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +                IEnumerator<string>? locations,
Conceptually do two concepts needed? 

I.e. even given the locations `LocationHelper.GetLocationEndpoint(this.DefaultEndpoint, location)` can be used to pre-populate the endpoints right? It can even be made lazy like current enumeration. 

This way the code flow gets simpler right?

2024-01-26 19:32 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +                tasksToWaitOn.Add(this.TryGetAccountPropertiesFromAllLocationsAsync());
Yup! faster enumeration was the idea. Jake did it long time back, there were pathologicalses where it ends-up doing all regions and if CX regions is at end.

2024-01-26 19:33 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +                IEnumerator<string>? locations,
Am waiting on this.

2024-01-26 19:33 UTC, kirankumarkolli requested changes
https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4265/files#r1468064408

2024-01-26 20:47 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
>                  {
The `GetAccountPropertiesHelper` constructor is already capturing the custom endpoints within `serviceEndpointEnumerator`. 

The method `GetAccountPropertiesAsync()` will iterate through the `this.ServiceEndpointEnumerator` which already contains the custom endpoints. So, we should be covered.

2024-01-26 21:07 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +                IEnumerator<string>? locations,
@FabianMeiswinkel and I had an offline conversation around this. Ideally the SDK should attempt to reach out to all the endpoints (global + custom private) before appending the location names to the default global endpoint. So, for example please consider the following code snippet:

```
CosmosClientOptions clientOptions = new CosmosClientOptions()
{
    ApplicationPreferredRegions = new List<string>()
    {
        Regions.EastUs,
        Regions.WestUs,
    },
    RegionalEndpoints = new List<string>()
    {
        { "custom.p-1.documents.azure.com" },
        { "custom.p-2.documents.azure.com" },
    },    
    EnablePartitionLevelFailover = true,
    ConnectionMode = ConnectionMode.Direct,
};

CosmosClient client = new CosmosClient(
    "https://testaccount.documents-test.windows-int.net:443/",
    "key==",
    clientOptions
);
```

The account endpoints should be resolved with the following order:

1. **First Attempt:** https://testaccount.documents-test.windows-int.net:443
2. **Second Attempt:** https://custom.p-1.documents.azure.com:443 
3. **Third Attempt:** https://custom.p-2.documents.azure.com:443
4. **Fourth Attempt:** https://testaccount-EastUs.documents-test.windows-int.net:443
5. **Fifth Attempt:** https://testaccount-WestUs.documents-test.windows-int.net:443

The purpose of the `LocationHelper.GetLocationEndpoint(this.DefaultEndpoint, location)` is to append the region names to the default endpoint (basically see the `4` and `5` steps in the above example) and return the same.

Therefore, I would be more inclined to keep the implementation as is - to define the scope and purposes of the respective methods.

2024-01-29 16:28 UTC, xinlian12 commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +                    await Task.WhenAny(serviceEndpointTask, timerTask);
since we are waiting only on the new tasks, which means we will be unaware of result of previous tasks until one of the two new tasks completes. But I think it will be fine as only max 5s latency will be added here?

2024-01-29 20:11 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +                    Task timerTask = Task.Delay(TimeSpan.FromSeconds(5));
When looking at the original code, the 5 second delay was only for the main endpoint. Only if the main endpoint took longer than 5 seconds we would start the loop. 

Adding the 5 seconds on each iteration, would that be desired?

What if the logic remains similar as before?

1. Use `this.DefaultEndpoint` + 5 seconds
2. If 5 seconds fired, then do a loop on Custom Endpoints + Preferred Locations as a single list unit. The single list can have first the Custom Endpoints and then the Preferred Regions.

That way the logic remains the same, you are just adding Custom Endpoints to the list before Preferred Regions?

2024-01-29 21:22 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +                    Task timerTask = Task.Delay(TimeSpan.FromSeconds(5));
Yup that's the intention of omment: https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4265#discussion_r1468064408

2024-01-29 23:50 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +                    Task timerTask = Task.Delay(TimeSpan.FromSeconds(5));
Refactored the code as discussed.

2024-01-29 23:50 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +                IEnumerator<string>? locations,
Refactored the code as discussed @kirankumarkolli.

2024-01-30 00:10 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        /// Gets and sets the custom private endpoints for geo-replicated database accounts in the Azure Cosmos DB service.
Updated.

2024-01-30 00:10 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        /// Nevertheless, this parameter remains optional and is recommended for implementation when a customer has configured a private endpoint with a custom DNS hostname
Updated.

2024-01-30 00:10 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
> +        /// <summary>
Updated.

2024-01-30 00:10 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/GatewayAccountReader.cs
> +                customPrivateEndpoints: this.connectionPolicy.CustomPrivateEndpoints,
Refactored across.

2024-01-30 02:22 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +                    await Task.WhenAny(serviceEndpointTask, timerTask);
Right. However, the code has been refactored recently and the `5s` latency is applicable only for the global endpoint task.

2024-01-30 17:49 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +            IList<string> accountInitializationCustomEndpoints,
Should this be:

```suggestion
            IList<string>? accountInitializationCustomEndpoints,
```

or are we creating a default empty list?

2024-01-30 17:50 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +                Task globalEndpointTask = this.GetAndUpdateAccountPropertiesAsync(this.DefaultEndpoint);
Is this code changing in spacing? It shows all this changed but really looking at it, it's not

2024-01-30 17:52 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +                    await this.GetAndUpdateAccountPropertiesAsync(
Previous code had a `lock` on the `MoveNext` because this is executed from 2 concurrent Tasks. Should this maintain the thread-safety?

2024-01-30 17:53 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +                IList<string> accountInitializationCustomEndpoints)
If we compare this with `null`, then should this be 
```suggestion
                IList<string>? accountInitializationCustomEndpoints)

```

And use instead `HasValue`?

2024-01-30 17:54 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +            IList<string> accountInitializationCustomEndpoints,
Yes, the list is created as an empty collection by default. Here is [the code](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/users/kundadebdatta/4236_add_custom_domain_names/Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs#L47) which does the initialization.

2024-01-30 17:55 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +                if (locations != null
Since it's nullable, should we use `HasValue` instead?
```suggestion
                if (locations.HasValue && locations.Value.Count > 0

```

2024-01-30 18:26 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +            private readonly IEnumerator<Uri> ServiceEndpointEnumerator;
```suggestion
            private readonly IEnumerator<Uri> ServiceDefaultEndpointEnumerator;
```

2024-01-30 18:35 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +                        serviceEndpoints.Add(
For public constract, how about taking it as URI? 
That way some kinds of mis-configurations will be covered by the contract it-self?

2024-01-30 18:37 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +                IList<Uri> serviceEndpoints = new List<Uri>();
Contract is IEnumrable, so we can do `yield return` for every element. 
It avoids the list materialization unnecessarily in most common cases.

2024-01-30 18:38 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
>              public async Task<AccountProperties> GetAccountPropertiesAsync()
if (this.Locations == null)
                {
                    return await this.GetOnlyGlobalEndpointAsync();
                }

Also consider he custom endpints?

2024-01-30 18:47 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +                    await this.GetAndUpdateAccountPropertiesAsync(
Also interesting this is cancellation is not wired through inside `getDatabaseAccountFn`, can be an indepdnent follow-up.

2024-01-30 18:52 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +                    await this.GetAndUpdateAccountPropertiesAsync(
Lock is a hacky way to serialize execution and generate a Task for concurrent execution. => Lock is still needed.

2024-01-30 18:52 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
>              private async Task GetAndUpdateAccountPropertiesAsync(Uri endpoint)
> this.TransientExceptions.Add(new OperationCanceledException("GlobalEndpointManager: Get account information canceled"));

Include the URI for context

2024-01-30 21:25 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +            IList<string> accountInitializationCustomEndpoints,
But could the user assign it to `null`?

2024-01-30 21:38 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +            IList<string> accountInitializationCustomEndpoints,
Yes, the Cx can assign it to `null`. However the place where we set this value has [already has a null check](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/b8788d409c64fa2c9a4d3dd33afc734c7f273fc0/Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs#L840C22-L843) which should cover us.

2024-02-06 01:31 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +                    await this.GetAndUpdateAccountPropertiesAsync(
Refactored the code to add the locking mechanism for thread safety.

2024-02-06 01:32 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +                    await this.GetAndUpdateAccountPropertiesAsync(
Refactored. For the follow up part, will create a separate discussion thread/ task.

2024-02-06 01:32 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
>              private async Task GetAndUpdateAccountPropertiesAsync(Uri endpoint)
Refactored.

2024-02-06 01:34 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
>              public async Task<AccountProperties> GetAccountPropertiesAsync()
I have refactored the code, to change the logic a little bit. I now introduced a Boolean flag `this.ShouldVisitGlobalEndpointOnly = (locations == null || locations.Count == 0) && (accountInitializationCustomEndpoints == null || accountInitializationCustomEndpoints.Count == 0);` to visit the global endpoint specifically, when the locations and private endpoints are empty.

2024-02-06 01:35 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +                        serviceEndpoints.Add(
Updated the public contract to reflect this.

2024-02-06 01:37 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +                if (locations != null
Looks like, even the nullable collections `<IList<string>? list` doesn't have a definition of `HasValue`. 

![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/87335885/3694616e-3504-40b7-9af2-879fa54060a3)

2024-02-06 01:37 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +                IList<string> accountInitializationCustomEndpoints)
Looks like, even the nullable collections `<IList<string>? list` doesn't have a definition of `HasValue`. 

![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/87335885/3694616e-3504-40b7-9af2-879fa54060a3)

2024-02-06 01:55 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +                this.ShouldVisitGlobalEndpointOnly = (locations == null || locations.Count == 0) && (accountInitializationCustomEndpoints == null || accountInitializationCustomEndpoints.Count == 0);
```suggestion
                this.LimitToGlobalEndpointOnly = (locations == null || locations.Count == 0) && (accountInitializationCustomEndpoints == null || accountInitializationCustomEndpoints.Count == 0);
```

2024-02-06 01:59 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +                if (!this.ShouldVisitGlobalEndpointOnly)
nit: Unsure the value of this check here

2024-02-06 02:01 UTC, kirankumarkolli approved these changes

2024-02-06 22:16 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +                this.ShouldVisitGlobalEndpointOnly = (locations == null || locations.Count == 0) && (accountInitializationCustomEndpoints == null || accountInitializationCustomEndpoints.Count == 0);
Refactored to reflect the name change.

2024-02-06 22:23 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +                if (!this.ShouldVisitGlobalEndpointOnly)
Agree. But, I feel we should still keep it, because this method might become useful in some other places. With that, the validation might be helpful for any other caller in the future, to understand the purpose of the method.

2024-02-07 00:07 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +                out Uri? serviceEndpoint)
Nullable practically is for value types not reference types. 
I.e. Uri can be already assigned NULL what's the value of marking it nullable?

Gues this is applicable across all contracts.

2024-02-07 20:29 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +                out Uri? serviceEndpoint)
Had a offline sync up with @kirankumarkolli. This is happening because of the way our project is set up. All project templates starting with .NET 6 (C# 10) enable the nullable context for the project. Projects created with earlier templates don't include this element, and these features are off unless you enable them in the project file or use pragmas.

See [this document ](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-reference-types)for more details.

![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/87335885/bf9270bc-5b56-4288-80ea-f711510c1099)

2024-02-08 01:40 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs
> +            if (customEndpoints == null)
Please also validate for the relative URLs?

2024-02-08 01:44 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +                        DefaultTrace.TraceCritical("GlobalEndpointManager: serviceEndpoint is null for TryMoveNextServiceEndpointhreadSafe.");
Unrelated: How about include the regions attempted or tried.

2024-02-08 01:46 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +                if (this.CancellationTokenSource.IsCancellationRequested)
nit: Redundant check, while condition is already covering it.

2024-02-08 01:59 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
>                  Assert.IsTrue(clientOptions.EnablePartitionLevelFailover);
Assert that ConnectionPolicy is set?

2024-02-08 02:02 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
> +                Assert.IsNotNull(clientOptions.ApplicationPreferredRegions);
Please check that the endpoints are visited.

2024-02-08 22:23 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +                if (this.CancellationTokenSource.IsCancellationRequested)
Removed.

2024-02-08 22:23 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
>                  Assert.IsTrue(clientOptions.EnablePartitionLevelFailover);
Done.

2024-02-08 22:23 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
> +                Assert.IsNotNull(clientOptions.ApplicationPreferredRegions);
Updated the test to add explicit validation.

2024-02-08 22:43 UTC, ealsur approved these changes

2024-02-09 00:15 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayAccountReaderTests.cs
> +                Assert.AreEqual(endpointSucceeded, privateEndpoint3);
Moq has inbuilt way to verify the callers. 
Either it can be very explicit at argument level or aggregate count level. 

For example below code is checking for aggregate times its expected to get called.
```
            mockHttpClient.Verify(e => e.GetAsync(It.IsAny(), ...), Times.Exactly(3));
```

2024-02-09 00:17 UTC, kirankumarkolli approved these changes

2024-02-09 07:49 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayAccountReaderTests.cs
> +                Assert.AreEqual(endpointSucceeded, privateEndpoint3);
`mockHttpClient.Verify` can validate how many times the `mockHttpClient.GetAsync()` was invoked, and irrespective of the response type, in this case, the method will be invoked `4` times (because we have 4 service endpoints and each endpoint will invoke the method). 

However, our purpose is to validate the `privateEndpoint3` was indeed returned a valid response, which I believe can't be validated with `mockHttpClient.Verify()`.

2024-02-09 07:50 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs
> +            if (customEndpoints == null)
Will follow up as a separate task.

2024-02-09 07:50 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +                        DefaultTrace.TraceCritical("GlobalEndpointManager: serviceEndpoint is null for TryMoveNextServiceEndpointhreadSafe.");
Will follow up as a separate PR.

2024-02-09 15:04 UTC, FabianMeiswinkel approved these changes
LGTM - Thanks

2024-02-09 15:04 UTC, merged