CosmosClientOptions: Adds validation to check HttpFactory and ServerCallback are set together
Azure/azure-cosmos-dotnet-v3 pull request #4283
Opened 2024-01-26 02:49 UTC by sourabh1007

## Description

As part of this PR, validating if `HTTPClientFactory` and `DisableServerCertificateValidation` flag or `ServerCertificateCustomValidationCallback` option are set together. Throws `ArgumentException` if it is true.

## Type of change
- [] Bug fix (non-breaking change which fixes an issue)

2024-01-26 18:14 UTC, NaluTripician requested changes
Could you please add some context to the PR description on why both cannot be set. Other than that, LGTM.

2024-01-26 19:01 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +            if (this.HttpClientFactory != null && this.ServerCertificateCustomValidationCallback != null)
Clarification: The combination that we want to fail is DisableServertCert and ServerCertificateCustomValdiatonCallback right?

2024-01-26 19:07 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +            if (this.HttpClientFactory != null && this.ServerCertificateCustomValidationCallback != null)
Disableservercert flag internally sets this callback in clientoptions only.

2024-01-28 19:32 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +            if (this.HttpClientFactory != null && this.ServerCertificateCustomValidationCallback != null)
ohh sorry I misread the discussion. Yes, it was flag and callback. Thanks for pointing it out.

2024-01-29 18:49 UTC, kirankumarkolli approved these changes

2024-01-29 18:49 UTC, kirankumarkolli commented
Lets port this to 3.38 release.

/cc: @kundadebdatta

2024-01-30 01:20 UTC, NaluTripician approved these changes

2024-01-30 01:20 UTC, merged