SystemTextJsonSerializer: Adds Default STJ Serializer
Azure/azure-cosmos-dotnet-v3 pull request #4332
Opened 2024-02-28 17:16 UTC by kundadebdatta

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Include samples if adding new API, and include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #IssueNumber

2024-02-29 08:39 UTC, bartelink commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosSystemTextJsonSerializer.cs
> +                return (T)this.systemTextJsonSerializer.Deserialize(stream, typeof(T), default);
```suggestion
                return this.systemTextJsonSerializer.Deserialize<T>(stream, default);
```

2024-03-11 16:38 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosSystemTextJsonSerializer.cs
> +                return (T)this.systemTextJsonSerializer.Deserialize(stream, typeof(T), default);
In order to use the `System.Text.Json` (STJ) serializer, we currently depend on the `Azure.Core` nuget package (specifically for this class `JsonObjectSerializer`). The current version of `Azure.Core` library, referred in our v3 .NET SDK is `1.19.0`, which is quite old. This internally uses `System.Text.Json` v `4.6.0`.

STJ `4.6.0` doesn't support the way you suggested to use the generic Deserializer.

2024-03-11 17:41 UTC, bartelink commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosSystemTextJsonSerializer.cs
> +                return (T)this.systemTextJsonSerializer.Deserialize(stream, typeof(T), default);
OK, that makes sense

2024-03-11 17:46 UTC, bartelink commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Poco/STJ/Cars.cs
> +            "BMW C18",
Hm, need more typesafety in the language

2024-03-11 17:50 UTC, bartelink commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Poco/STJ/Cars.cs
> +        [JsonConstructor]
pretty sure this is not required for up to date STJ versions
unless the older version being used dictates this, maybe best to not tag it?

2024-03-11 18:20 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Poco/STJ/Cars.cs
> +        [JsonConstructor]
Removed and validated the tests are passing.

2024-03-11 19:26 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosDefaultSystemTextJsonSerializer.cs
> +    /// This class provides a default implementation of STJ Cosmos Linq Serializer.
Maybe: 
```suggestion
    /// This class provides a default implementation of System.Text.Json for CosmosClient
```

2024-03-11 22:33 UTC, Maya-Painter commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosDefaultSystemTextJsonSerializer.cs
> +            JsonSerializerOptions jsonSerializerOptions)
Just a heads up that any `JsonSerializerOptions` passed in here are not going to be reflected in `SerializeMemberName()` as it is now, which may cause some confusion.

For example, if customers passed in a JsonSerializerOption such as below

```
            JsonSerializerOptions options = new()
            {
                PropertyNamingPolicy = JsonNamingPolicy.CamelCase
            }
```

This would not be honored by SerializeMemberName unless it included special handling for this, e.g.

```
        public override string SerializeMemberName(MemberInfo memberInfo)
        {
            System.Text.Json.Serialization.JsonExtensionDataAttribute jsonExtensionDataAttribute =
                memberInfo.GetCustomAttribute<System.Text.Json.Serialization.JsonExtensionDataAttribute>(true);
            if (jsonExtensionDataAttribute != null)
            {
                return null;
            }

            JsonPropertyNameAttribute jsonPropertyNameAttribute = memberInfo.GetCustomAttribute<JsonPropertyNameAttribute>(true);
            if (!string.IsNullOrEmpty(jsonPropertyNameAttribute?.Name))
            {
                return jsonPropertyNameAttribute.Name;
            }

            return System.Text.Json.JsonNamingPolicy.CamelCase.ConvertName(memberInfo.Name);
        }
```

SerializeMemberName is included on the interface since customers will need to modify it themselves.

2024-03-12 17:36 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosDefaultSystemTextJsonSerializer.cs
> +    public class CosmosDefaultSystemTextJsonSerializer : CosmosLinqSerializer
>CosmosLinqSerializer [](http://example.com/codeflow?start=57&length=20)

Did you mean to implement LinqSerializer or just plain-old CosmosSerializer?

If this is intentional, can you add coverage for LINQ scenarios?

Here's a sample PR that touched relevant query surface area:
[https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4138/files](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4138/files)

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqAggregateCustomSerializationBaseline.cs

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqTranslationWithCustomSerializerBaseline.cs

2024-03-12 17:37 UTC, adityasa requested changes
:clock1:

2024-03-19 22:23 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosDefaultSystemTextJsonSerializer.cs
> +            JsonSerializerOptions jsonSerializerOptions)
Discussed with @Maya-Painter offline. One possible solution could be to remove the `JsonSerializerOptions` from the `CosmosDefaultSystemTextJsonSerializer()` constructor. That way, the serializerOptions won't be passed from the end users and we could avoid handling the custom attributes.

The usage will look like the below:

```
        CosmosClientOptions clientOptions = new CosmosClientOptions()
        {
            Serializer = new CosmosDefaultSystemTextJsonSerializer()
        };
```

Thoughts @ealsur , @kirankumarkolli ?

2024-03-19 22:27 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosDefaultSystemTextJsonSerializer.cs
> +            JsonSerializerOptions jsonSerializerOptions)
I'm guessing that it depends on our goal. Is the goal to provide a base implementation to cover the most general cases? If yes, then makes sense to not have the custom options. Or if we know which custom options are invalid, then we could throw if the customer is setting those?

Another idea would be to allow customers to inherit and override the LINQ serialization, so a user with custom options can create a superset class that inherits from this but has a custom SerializeMemberName (I think this is valid right now). But in this case discovery that they need to add their own implementation might be obscure.

2024-03-20 20:14 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosDefaultSystemTextJsonSerializer.cs
> +            JsonSerializerOptions jsonSerializerOptions)
I agree with the second point. I think to add such custom scenarios, the end users can create their own custom serializer that inherits the default serializer and add an override for the `SerializeMemberName()` method.

Therefore, I have added more documentation on the `SerializeMemberName()` method to cover this. Will update the PR description to make things more clear.

@Maya-Painter : Let me know if you have any concerns/ thoughts.

Cc: @ealsur , @kirankumarkolli .

2024-03-20 21:13 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosDefaultSystemTextJsonSerializer.cs
> +    /// This class provides a default implementation of STJ Cosmos Linq Serializer.
Updated.

2024-03-21 00:41 UTC, Maya-Painter commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosDefaultSystemTextJsonSerializer.cs
> +            JsonSerializerOptions jsonSerializerOptions)
I'm fine with it as long as this class and any potential LINQ GitHub issues arising from its use belong to the SDK team :)

2024-03-21 20:24 UTC, joegoldman2 commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosDefaultSystemTextJsonSerializer.cs
> +                return JsonSerializer.Deserialize<T>(reader.ReadToEnd(), this.jsonSerializerOptions);
```suggestion
                return JsonSerializer.Deserialize<T>(stream, this.jsonSerializerOptions);
```
STJ is able to deserialize the stream directly without needing to allocate an intermediate string.

2024-03-21 20:24 UTC, joegoldman2 commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosDefaultSystemTextJsonSerializer.cs
> +    public class CosmosDefaultSystemTextJsonSerializer : CosmosLinqSerializer
Should the name be `CosmosSystemTextJsonSerializer` instead?

2024-04-11 23:23 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosDefaultSystemTextJsonSerializer.cs
> +    public class CosmosDefaultSystemTextJsonSerializer : CosmosLinqSerializer
Refactored the code to reflect the same.

2024-04-12 00:54 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosSystemTextJsonSerializer.cs
> +    public class CosmosSystemTextJsonSerializer : CosmosLinqSerializer
Contract JSON file update is needed right?

2024-04-12 00:56 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosSystemTextJsonSerializer.cs
> +        ///     PropertyNamingPolicy = JsonNamingPolicy.CamelCase
CTOR taking the serializeroptions but the guidance going into the description. 
Its lots confusing, @ealsur thoughts?

2024-04-12 05:45 UTC, joegoldman2 commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosSystemTextJsonSerializer.cs
> +                return JsonSerializer.Deserialize<T>(reader.ReadToEnd(), this.jsonSerializerOptions);
```suggestion
                return JsonSerializer.Deserialize<T>(stream, this.jsonSerializerOptions);
```
STJ is able to deserialize the stream directly without needing to allocate an intermediate string.

2024-04-12 22:17 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosSystemTextJsonSerializer.cs
> +        ///     PropertyNamingPolicy = JsonNamingPolicy.CamelCase
Not sure I understand the comment. From what I read. This is a note for the LINQ serialization for users that may need to adapt this particular method for their custom options if any.
Maybe this needs to go into `<remarks>` instead of description might be the only thing I can think of.

2024-04-15 18:01 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosSystemTextJsonSerializer.cs
> +    public class CosmosSystemTextJsonSerializer : CosmosLinqSerializer
Yes, needed to update the contract JSON.

2024-04-15 18:14 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosSystemTextJsonSerializer.cs
> +                return JsonSerializer.Deserialize<T>(reader.ReadToEnd(), this.jsonSerializerOptions);
Right now, the `System.Text.JSON` package depends on the `Azure.Core` version `1.19.0`, which uses the STJ version `4.6.0`. This version of the STJ serializer doesn't support the `Deserialize()` directly with a `stream`. Hence the conversion is needed at the moment.

2024-04-15 19:03 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqAggregateCustomSerializationBaseline.cs
> +            defaultCosmosSerializer = new CosmosSystemTextJsonSerializer(new JsonSerializerOptions());
Is this used? If not, please remove.

2024-04-15 19:04 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqAggregateCustomSerializationBaseline.cs
> +                => cosmosClientBuilder.WithCustomSerializer(customCosmosSerializer));
>customCosmosSerializer [](http://example.com/codeflow?start=60&length=22)

Should this be defaultCosmosSerializer?

2024-04-15 19:04 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqAggregateCustomSerializationBaseline.cs
> +        private static CosmosSerializer defaultCosmosSerializer;
>default [](http://example.com/codeflow?start=40&length=7)

Please rename to stjCosmosSerializer

2024-04-15 19:05 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqAggregateCustomSerializationBaseline.cs
> +        private static CosmosClient defaultClient;
>default [](http://example.com/codeflow?start=36&length=7)

Please rename to stjClient (if it intends to use new STJ serializer)

2024-04-15 19:05 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqAggregateCustomSerializationBaseline.cs
> +        private static Cosmos.Database testDbDefault;
>testDbDefault [](http://example.com/codeflow?start=39&length=13)

testDbSTJ

2024-04-15 19:05 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqAggregateCustomSerializationBaseline.cs
> +        private static Container testContainerDefault;
testContainerSTJ

2024-04-15 19:23 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqAggregateCustomSerializationBaseline.cs
> +        private static Cosmos.Database testDbDefault;
Updated with latest commit.

2024-04-15 19:23 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqAggregateCustomSerializationBaseline.cs
> +        private static CosmosClient defaultClient;
Updated with latest commit.

2024-04-15 19:23 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqAggregateCustomSerializationBaseline.cs
> +        private static CosmosSerializer defaultCosmosSerializer;
Updated with latest commit.

2024-04-15 19:24 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqAggregateCustomSerializationBaseline.cs
> +                => cosmosClientBuilder.WithCustomSerializer(customCosmosSerializer));
Yes - it should be the `defaultCosmosSerializer`. Thanks! I have renamed it though.

2024-04-15 19:24 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqAggregateCustomSerializationBaseline.cs
> +            defaultCosmosSerializer = new CosmosSystemTextJsonSerializer(new JsonSerializerOptions());
It should be. I have refactored the test to use this serializer.

2024-04-15 19:40 UTC, adityasa commented
>                     "Select number -> Min w/ mapping", b => getQuery(b)

Nit - please include serializer name here too.

---
Refers to: Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqAggregateCustomSerializationBaseline.cs:154 in 683ca13. [](commit_id = 683ca137d0f817993e77ffc9162f8b601d5b1c00, deletion_comment = False)

2024-04-15 19:40 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqAggregateCustomSerializationBaseline.cs
> +                    "Avg, Serializer Name: " + entry.Key, b => getQuery(b)
>Serializer Name: [](http://example.com/codeflow?start=26&length=16)

Neat!

2024-04-15 19:40 UTC, adityasa approved these changes
:shipit:

2024-04-15 20:37 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosDefaultSystemTextJsonSerializer.cs
> +    public class CosmosDefaultSystemTextJsonSerializer : CosmosLinqSerializer
This is now addressed.

2024-04-16 05:35 UTC, joegoldman2 commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosSystemTextJsonSerializer.cs
> +                return JsonSerializer.Deserialize<T>(reader.ReadToEnd(), this.jsonSerializerOptions);
Ok, clear. Can you add a TODO not to forget to update the implementation once the version of STJ will be updated?

2024-04-16 05:45 UTC, bartelink commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosSystemTextJsonSerializer.cs
> +                return JsonSerializer.Deserialize<T>(reader.ReadToEnd(), this.jsonSerializerOptions);
snap! https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4332#discussion_r1520153811

2024-04-18 22:05 UTC, Maya-Painter commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosSystemTextJsonSerializer.cs
> +        public override string SerializeMemberName(MemberInfo memberInfo)
I've updated the STJ sample code and made some improvements to this function in this PR https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4420.  Could you update this function to look like this - https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos.Samples/Usage/SystemTextJson/CosmosSystemTextJsonSerializer.cs ? Thanks!

2024-04-19 00:45 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosSystemTextJsonSerializer.cs
> +        public override string SerializeMemberName(MemberInfo memberInfo)
Thanks @Maya-Painter. We are trying to gather some feedback on this from the .NET team on this. I will take your changes as well, and update the PR.

2024-04-23 11:02 UTC, eiriktsarpalis commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosSystemTextJsonSerializer.cs
> +        public override string SerializeMemberName(MemberInfo memberInfo)
The `JsonTypeInfo`/`JsonPropertyInfo` types contain authoritative information on the JSON contract used by a particular type/property. See https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/custom-contracts for more details.

2024-04-23 21:29 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosSystemTextJsonSerializer.cs
> +        public override string SerializeMemberName(MemberInfo memberInfo)
Thank you @eiriktsarpalis !

2024-05-10 17:27 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosSystemTextJsonSerializer.cs
> +        public override string SerializeMemberName(MemberInfo memberInfo)
Thanks for your suggestion @eiriktsarpalis! Looks like, these ([JsonSerializerOptions.TryGetTypeInfo](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fdotnet%2Fapi%2Fsystem.text.json.jsonserializeroptions.trygettypeinfo%3Fview%3Dnet-8.0&data=05%7C02%7Cdkunda%40microsoft.com%7Ce3b58671a1f243d198dd08dc632f838f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638494302946820285%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=dWcECXAzip0CNwP2%2FdqUxZ0ySHvwKiYvhRtBZv07dww%3D&reserved=0), [custom contracts](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/custom-contracts)) are applicable for the latest versions of the `System.Text.JSON` package, and it's not available in `4.6.0`.
 
In order to use the `System.Text.Json` (STJ) serializer, we currently depend on the `Azure.Core` nuget package (specifically for this class `JsonObjectSerializer`). The current version of `Azure.Core` library, referred in our v3 .NET SDK is `1.19.0`, which is quite old. This internally uses `System.Text.Json` version `4.6.0`.
 
I am planning to keep this suggestion as follow-up task [4479](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/4479) to upgrade the `Azure.Core` library to the latest. Even the latest version of `Azure.Core` [1.39.0]( https://nuget.info/packages/Azure.Core/1.39.0) library uses the STJ version `4.7.2`.
 
![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/87335885/334e51d8-046d-4ba5-b7d9-416ce79ef406)

2024-05-10 17:34 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Poco/STJ/Cars.cs
> +            "BMW C18",
I wouldn't worry about it too much since this is an unit test.

2024-05-10 17:35 UTC, adityasa submitted a review, later dismissed
:shipit:

2024-05-11 00:22 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosSystemTextJsonSerializer.cs
> +            if (stream.CanSeek && stream.Length == 0)
Is `canSeek` is not really required right?

2024-05-11 00:34 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosSystemTextJsonSerializer.cs
> +        public override string SerializeMemberName(MemberInfo memberInfo)
How about only make this type public once is fully addressed?

2024-05-11 08:36 UTC, bartelink commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosSystemTextJsonSerializer.cs
> +                writer: writer,
its great that I don't need to care as this will be an impl detail deep in a library but this formatting/named params is way overkill and makes it look like some really exciting stuff is going on, which there isnt
is the intention to disambiguate from some adjacent overload?
in general I'd be nice if this code was scannable so people can compare their impls quickly before deleting them in favor of this one

2024-05-11 08:46 UTC, bartelink commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosSystemTextJsonSerializer.cs
> +        public override string SerializeMemberName(MemberInfo memberInfo)
The fact that Azure.Core 'uses' (gets by with) an old version does not of itself mean that this lib can't take a dependency on a higher version. I'd ask, what version would simplify and/or _significantly_ improve perf here? Then validate the answer by lookign at package download counts at https://www.nuget.org/packages/system.text.json.
For instance 6.0.1 has a net6.0 variant and seems to be in popular use, and is only 18 months newer - it's not like STJ is known to be a pain to upgrade.
But of course, I'm just being a devil's advocate; there's lots of silent votes for the status quo!
Hopefully there will be a security reason along to trigger a forced upgrade in due course ;)
The other benefit of taking a higher dep is that perf in general has been on an upward trajectory, and the perceived experience of the SDK would hence also improve for people that don't explicitly pin latest in their apps

2024-05-29 19:50 UTC, Arcalise08 commented
Any update on this PR? It's been a few weeks and this is a much-anticipated change.

2024-05-31 20:33 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosSystemTextJsonSerializer.cs
> +            if (typeof(Stream).IsAssignableFrom(typeof(T)))
Can this check be before above one?

2024-05-31 20:54 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosSystemTextJsonSerializer.cs
> +            MemoryStream streamPayload = new ();
Do different payload sizes make any difference on performance?

2024-05-31 20:56 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosSystemTextJsonSerializer.cs
> +                writer: writer,
@Bartelink is the ASK to inline arguments? (make code compact)

2024-05-31 21:05 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosSystemTextJsonSerializer.cs
> +            JsonExtensionDataAttribute jsonExtensionDataAttribute =
Quick clarification: Is this API called for every propertyname conversion? If so the cardinality for each type conversion is much higher right? 

Assuming the mapping is fixed (one type is loaded), is below code optimal?

2024-05-31 21:19 UTC, bartelink commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosSystemTextJsonSerializer.cs
> +                writer: writer,
Pretty much... I don't think the explicitly named args add anything in this case (even if they can sometimes be a really good idea). If you do that, it becomes a single line, and conveys "we're just serializing in a perfectly normal fashion here", whereas a multi line thing has me wondering, what subtlety are we trying to emphasize here?

2024-06-04 00:20 UTC, kirankumarkolli commented
> Any update on this PR? It's been a few weeks and this is a much-anticipated change.

@Arcalise08 due to some reprioritizations this work was paused. We expect it to resume it after 2 weeks. 
We will try to opportunistically accelerate its close as soon as possible.

2024-06-17 17:21 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosSystemTextJsonSerializer.cs
> +            if (stream.CanSeek && stream.Length == 0)
My understanding is that the `.CanSeek` check is required, otherwise the `.Length` call may fail. [See this](https://learn.microsoft.com/en-us/dotnet/api/system.io.stream.canseek?view=net-8.0#remarks) for more details.

![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/87335885/88c8db32-eb03-40e1-b506-6db21eda3575)

2024-06-17 17:57 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosSystemTextJsonSerializer.cs
> +            if (typeof(Stream).IsAssignableFrom(typeof(T)))
Refactored the code to address this.

2024-06-17 22:35 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosSystemTextJsonSerializer.cs
> +            MemoryStream streamPayload = new ();
As discussed its a follow-up work item.

2024-06-17 22:35 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosSystemTextJsonSerializer.cs
> +            JsonExtensionDataAttribute jsonExtensionDataAttribute =
Its only called from LINQ and can be followed-up later.

2024-06-17 23:46 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosSystemTextJsonSerializer.cs
> +            JsonExtensionDataAttribute jsonExtensionDataAttribute =
This will be addressed by [Task-4479](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/4479)

2024-06-17 23:47 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosSystemTextJsonSerializer.cs
> +            MemoryStream streamPayload = new ();
A follow up task [4479](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/4479) created to track this.

2024-06-17 23:47 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Serializer/CosmosSystemTextJsonSerializer.cs
> +        public override string SerializeMemberName(MemberInfo memberInfo)
This is now addressed with the latest commit.

2024-06-17 23:52 UTC, kirankumarkolli approved these changes

2024-06-18 00:11 UTC, aavasthy approved these changes
👍

2024-06-18 00:27 UTC, ealsur approved these changes

2024-06-18 02:17 UTC, merged

2024-06-30 09:17 UTC, itsawindup commented
Forgive me if I am being a bit slow, but since the change from public to internal in commit 1ff1f06, I can't see a way to use this in my own code.  Have I missed something obvious?

2024-09-07 08:04 UTC, bartelink commented
@kirankumarkolli @kundadebdatta Please follow up by adding a quick summary as to the final state of play here.
Thousands of people will hit this issue via search, and this saga had lots of twists and turns along the way!

2024-09-09 20:30 UTC, kirankumarkolli commented
@bartelink apologies, we change the usage model towards the end of the PR stage and missed to reflect that in the description.
@kundadebdatta can you please refresh the description.

2024-09-09 20:47 UTC, kundadebdatta commented
> @kirankumarkolli @kundadebdatta Please follow up by adding a quick summary as to the final state of play here. Thousands of people will hit this issue via search, and this saga had lots of twists and turns along the way!

Thanks for bringing this up @bartelink ! I have updated the summary to explain how to use this serializer publicly by default. For your reference:

There is a separate [PR-4589](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4589) which explains the steps to use the `CosmosSystemTextJsonSerializer` publicly by setting `UseSystemTextJsonSerializerWithOptions` parameter in the `CosmosClientOpions` for both preview and GA contract. 

I hope this will be helpful! Please feel free to reach out, if you have any questions.

2024-09-09 22:53 UTC, bartelink commented
I guess the problem is that over the years there's been lots of PRs and/or snippets. I know this PR has `[Internal]` in the title, but the average person without context won't appreciate what that implies, and will instead focus on the "Adds Default STJ Serializer" part of the title and say "OK, it was merged some time ago and I'm on latest, and I can't see this `CosmosDefaultSystemTextJsonSerializer` anywhere".

----

So the problem is that someoe scanning even the current overview might conclude that there is a `CosmosDefaultSystemTextJsonSerializer`. For very good reasons I agree with, that has has wound up not being `public`. So I guess I was hoping that the last piece of info on this thread (and maybe a prominent note in the overview) could summarise the key points:

- There are two abstract classes in `Microsoft.Azure.Cosmos`: `CosmosSerializer` and `CosmosLinqSerializer` that allow you to customize everything
- Normally you don't want to do that though:
  1. The `CosmosDefaultSystemTextJsonSerializer` in the overview exists, but it ultimately ended up being `internal`
  2. But, that's OK - there's a newer API (see #4589) that provides access by doing
    
         var opts = new CosmosClientOptions {
             UseSystemTextJsonSerializerWithOptions = System.Text.Json.JsonSerializerOptions.Default };

----

Something like this, but written in proper English ;) ?

To apply the `CosmosDefaultSystemTextJsonSerializer` in the overview of this issue on 3.43.0 or later, you set the value of the `CosmosClientOptions.UseSystemTextJsonSerializerWithOptions` property to an instance of `System.Text.Json.JsonSerializerOptions` , e.g.:

     var opts = new CosmosClientOptions { UseSystemTextJsonSerializerWithOptions = System.Text.Json.JsonSerializerOptions.Default };
     var client = new CosmosClient(...., opts);

2024-09-10 18:23 UTC, kirankumarkolli commented
Updated the title to remove default and also the updated PR description to reference the PR which made the contracts public.