[Internal} Direct Package: Upgrades Direct package version to 3.33.0
Azure/azure-cosmos-dotnet-v3 pull request #4353
Opened 2024-03-15 18:55 UTC by NaluTripician

# Pull Request Template

## Description

Upgrades Direct package version to 3.33.0

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #IssueNumber

2024-03-21 22:02 UTC, kundadebdatta commented
Could you please update the PR description with some of the relevant changes/ features that are actually a part of Direct `3.33.0` ?

2024-03-21 22:08 UTC, NaluTripician commented
> Could you please update the PR description with some of the relevant changes/ features that are actually a part of Direct `3.33.0` ?

Updated description. @sourabh1007 can you please make sure your Distributed Tracing changes are reflected correctly.

2024-03-21 22:20 UTC, kirankumarkolli submitted a review, later dismissed

2024-03-21 23:26 UTC, kundadebdatta approved these changes
LGTM!

2024-03-22 01:23 UTC, sourabh1007 commented
> > Could you please update the PR description with some of the relevant changes/ features that are actually a part of Direct `3.33.0` ?
> 
> Updated description. @sourabh1007 can you please make sure your Distributed Tracing changes are reflected correctly.

Nothing is changed in distributed tracing, we marked n/w level telemetry stable and then reverted. So, we don't need any changelog for this.

2024-03-23 03:19 UTC, sourabh1007 approved these changes

2024-03-25 20:27 UTC, adityasa approved these changes
:shipit:

2024-03-27 22:22 UTC, NaluTripician commented
After discussion with @kundadebdatta, we decided to update the test baseline files for two tests that were failing on the CI pipeline as well as locally to move this PR forward. For one test (GroupBy), the order of the xml was moved around. For the other (NonValueAggregates), some field names were changes. These tests began failing after changing the direct package version.

2024-03-28 18:19 UTC, philipthomas-MSFT commented
@NaluTripician Can you explain "Bug Fixes for Fault Injection Connection Timeout Rules" in detail?

2024-03-28 18:54 UTC, NaluTripician commented
> @NaluTripician Can you explain "Bug Fixes for Fault Injection Connection Timeout Rules" in detail? Is moving to 3.33.0 the fix?

Yes, there were changes made in 3.33.0 that fixes behavior for connection timeout rules where some timeouts were not actually being timed out.

2024-03-28 20:19 UTC, kundadebdatta submitted a review, later dismissed
Looks good to me. Thanks!

2024-04-01 18:50 UTC, philipthomas-MSFT approved these changes

2024-04-02 15:30 UTC, ealsur requested changes

2024-04-02 15:30 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Regions.cs
> +        public const string TaiwanNorth = "TaiwanNorth";
This is wrong, right? The value is missing spaces?

2024-04-02 15:34 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/QueryPlanBaselineTests.GroupBy.xml
> -            <AliasToAggregateType>
This seems to be just reordering of nodes? Could it be that these are not needed?

2024-04-02 17:11 UTC, NaluTripician commented on Microsoft.Azure.Cosmos/src/Regions.cs
> +        public const string TaiwanNorth = "TaiwanNorth";
Good catch, changing

2024-04-02 17:14 UTC, NaluTripician commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/QueryPlanBaselineTests.GroupBy.xml
> -            <AliasToAggregateType>
That is what we originally thought, for some reason the tests fail locally and on the CI pipelines if these changes are not there.

2024-04-02 17:44 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Regions.cs
> +        public const string TaiwanNorth = "TaiwanNorth";
@kirankumarkolli there is a test: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/e04ce514f850cdcaa003b64ec19384662c53e18a/Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DirectContractTests.cs#L58

But the test checks the enum names, not the values. Maybe we need to add that testing.

2024-04-03 04:41 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DirectContractTests.cs
> +            string[] locationNames = typeof(LocationNames)
nit: Is it used?

2024-04-03 04:43 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DirectContractTests.cs
> +                Assert.IsTrue(locationNameValue == regionNameValue);
Prefer Asset.AreEqual()

In-case of assertion failure will include the values for troubleshooting.

2024-04-03 14:09 UTC, ealsur commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DirectContractTests.cs
> +    using System.Drawing;
Why do we need this?

2024-04-03 17:13 UTC, NaluTripician commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DirectContractTests.cs
> +            string[] locationNames = typeof(LocationNames)
Removed

2024-04-03 17:13 UTC, NaluTripician commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DirectContractTests.cs
> +    using System.Drawing;
removed/sorted usings

2024-04-03 18:00 UTC, ealsur approved these changes

2024-04-03 19:26 UTC, kirankumarkolli approved these changes

2024-04-03 19:27 UTC, merged