Update Regions.cs - Adding new region for USSec
Azure/azure-cosmos-dotnet-v3 pull request #4381
Opened 2024-03-29 20:48 UTC by trande4884

Adding new region for USSec

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Include samples if adding new API, and include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #IssueNumber

2024-04-01 17:21 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Regions.cs
> +        public const string USSecWestCentral = "USSec West Central";
The current version of `Cosmos.Direct` package version `3.32.1` have the `USSecWestCentral` region marked as `internal`. See this [code path](https://msdata.visualstudio.com/CosmosDB/_git/CosmosDB?path=/Product/Microsoft.Azure.Documents/SharedFiles/LocationNames.cs&version=GBsdkReleases/direct/EN20231101_3.32.1&line=275&lineEnd=276&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents) for more details. This means that when the customer select this region, it will eventually fail during validation.

We will need to wait until a new version of `Cosmos.Direct` package is released which will mark this region as public. Can you use [this TSG](https://msdata.visualstudio.com/CosmosDB/_wiki/wikis/CosmosDB.wiki/74268/Onboarding-New-Regions-in-Cosmos-.NET-v3-SDK) to create a new version of the direct package which contains the required changes please?

2024-04-01 17:22 UTC, kundadebdatta requested changes
Please see comments.

2024-04-02 17:53 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Regions.cs
> +        public const string USSecWestCentral = "USSec West Central";
@kundadebdatta how about adding a UT which iterates through all public and tries to use them for both ApplicationRegion and Preferred regions> 

It will catch any gaps that might slip through right?

2024-04-02 17:55 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Regions.cs
> +        public const string USSecWestCentral = "USSec West Central";
Sounds great to me. That way, we could catch the invalid/ unavailable regions faster.

2024-04-02 20:04 UTC, trande4884 commented on Microsoft.Azure.Cosmos/src/Regions.cs
> +        public const string USSecWestCentral = "USSec West Central";
@kirankumarkolli and @kundadebdatta Taylor and I are largely unfamiliar with this code, are you able to make the suggested changes to "catch gaps that might slip"? What is a "UT"? Some assistance on getting this done would be great!

2024-04-02 20:49 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Regions.cs
> +        public const string USSecWestCentral = "USSec West Central";
@trande4884 : "UT" basically stands for "Unit Test". While you work on the Direct package release, I can take this and update your PR to add the Unit Test toc over the scenario described.

2024-04-02 20:51 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Regions.cs
> +        public const string USSecWestCentral = "USSec West Central";
One more point - Can you please create a feature branch and submit a PR to address these changes. Forking is not supported for our pipelines and hence the PR will miss the necessary gates required for merging. Cc: @trande4884.

2024-04-03 16:48 UTC, kirankumarkolli commented
/azp run

2024-04-03 18:16 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Regions.cs
> +        public const string USSecWestCentral = "USSec West Central";
This PR is the same as https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4386?

2024-04-03 18:42 UTC, Tayham commented on Microsoft.Azure.Cosmos/src/Regions.cs
> +        public const string USSecWestCentral = "USSec West Central";
#4386 is going to be the PR going forward. This PR can be abandoned / closed.

2024-04-03 18:55 UTC, closed without merging