SDK 3.38.2: Adds version bump and changelog.
Azure/azure-cosmos-dotnet-v3 pull request #4391
Opened 2024-04-05 20:47 UTC by philipthomas-MSFT

# Pull Request Template

## Description

This bumps the SDK GA version from 3.38.1 to 3.38.2 and preview version from 3.39.0-preview.1 to 3.40.0-preview.0. Please see the below changes in the GA public contract.

![diff API_3 38 2](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/86612891/34becf51-4eb7-4b87-acd2-0d9904949b88)

Also highlighted below are the preview contract changes.

![diff API_3 40 0-preview 0](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/86612891/5f9be2ed-03a8-4e6d-abe0-b78d5d094e65)

_[Note: To understand about the GA and preview versions styles, please take a look at our [versioning guidelines and principles](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/docs/versioning.md)]_

2024-04-05 21:57 UTC, ealsur commented on Directory.Build.props
> +		<ClientOfficialVersion>3.38.2</ClientOfficialVersion>
SHouldn't this be 3.39.0?

3.38.2 would be a hotfix release, not a full release from master. Hotfix releases cannot alter public surface (add new APIs): https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/docs/versioning.md

2024-04-06 02:39 UTC, kirankumarkolli commented
Are contracts changes upto date? 

The images above shows some contracts/APIs are deleted right? Is that expected?

2024-04-08 12:33 UTC, philipthomas-MSFT commented on Directory.Build.props
> +		<ClientOfficialVersion>3.38.2</ClientOfficialVersion>
Thanks. I am fixing.

2024-04-08 12:33 UTC, philipthomas-MSFT commented
> Are contracts changes upto date?
> 
> The images above shows some contracts/APIs are deleted right? Is that expected?

I should have checked this. Thanks for pointing it out.

2024-04-08 16:01 UTC, Maya-Painter commented
The changelog doesn't seem to include any query changes - is this intentional?

2024-04-08 17:18 UTC, philipthomas-MSFT commented
> The changelog doesn't seem to include any query changes - is this intentional?

Query PRs have been added. Thanks.

2024-04-08 21:11 UTC, kirankumarkolli commented on changelog.md
> +- [4380](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4380) ChangeFeedProcessor: Refactors AVAD Metadata Contract for ChangeFeed and ChangeFeedProcessor
For preview please call out the breaking change very explicitly. 

This needs to pop-up differently from Added/fixed sections

2024-04-08 21:12 UTC, kirankumarkolli commented on changelog.md
> +- [4281](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4281) FaultInjection: Adds Fault Injection Library
Its not a end CX feature, ideally the PR should have marked it [INTERNAL]

Can we please exclude it?

2024-04-08 21:13 UTC, kirankumarkolli commented on changelog.md
> +- [4316](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4316) Distributed Tracing: Refactors code to rename net.peer.name attribute to server.address
@jcocchi should this be called as breaking change?

2024-04-08 21:14 UTC, kirankumarkolli commented on changelog.md
> +- [4317](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4317) Client Telemetry: Refactors code to stop throwing an exception
@sourabh1007 does it need to go into release notes?

Seems missing [INTERNAL] case.

2024-04-08 22:06 UTC, philipthomas-MSFT commented on changelog.md
> +- [4281](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4281) FaultInjection: Adds Fault Injection Library
removed. Thank you.

2024-04-08 22:11 UTC, jcocchi commented on changelog.md
> +- [4316](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4316) Distributed Tracing: Refactors code to rename net.peer.name attribute to server.address
Yes, the rename is breaking, but OTel attributes aren't stable yet. We should still call out this change

2024-04-08 22:11 UTC, jcocchi commented on changelog.md
> +- [4377](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4377) integrated cache: Adds BypassIntegratedCache for public release
Nit for casing consistency

```suggestion
- [4377](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4377) Integrated Cache: Adds BypassIntegratedCache for public release
```

2024-04-08 22:16 UTC, adityasa submitted a review, later dismissed
:shipit:

2024-04-08 22:35 UTC, philipthomas-MSFT commented on changelog.md
> +- [4316](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4316) Distributed Tracing: Refactors code to rename net.peer.name attribute to server.address
> Yes, the rename is breaking, but OTel attributes aren't stable yet. We should still call out this change

@sourabh1007 @jcocchi Can you ping me offline with what you want this to say, or just make the change and commit. Thanks.

2024-04-08 22:56 UTC, NaluTripician requested changes
Would probably be good to include that the new Taiwan regions are included in `Regions.cs` with the Direct Package upgrade in the changelog

2024-04-08 23:08 UTC, philipthomas-MSFT commented
> Would probably be good to include that the new Taiwan regions are included in `Regions.cs` with the Direct Package upgrade in the changelog

I can agree with that. The PR was Internal. Was that a mistake?
#4386

2024-04-08 23:19 UTC, jcocchi commented on changelog.md
> +- [4316](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4316) Distributed Tracing: Refactors code to rename net.peer.name attribute to server.address
How about the below

```suggestion
- [4316](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4316) Distributed Tracing: Refactors code to rename net.peer.name attribute to server.address. **Warning:** This is a breaking change, only `server.address` will be emitted starting with this version.
```

2024-04-08 23:33 UTC, NaluTripician commented
> > Would probably be good to include that the new Taiwan regions are included in `Regions.cs` with the Direct Package upgrade in the changelog
> 
> I can agree with that. The PR was Internal. Was that a mistake? #4386

I think normally Direct package upgrades are marked as Internal, but for this upgrade I was unaware of the region changes and that is why it was marked that way. I think we can add something like [this ](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/4b2196bc6023dca0e6a396612efb4a1ca14cf09a/changelog.md?plain=1#L57)to the changelog and link to the direct upgrade PR. Also worth changing our direct upgrade guide to specify this which I will do.

2024-04-09 01:26 UTC, sourabh1007 commented on changelog.md
> +- [4317](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4317) Client Telemetry: Refactors code to stop throwing an exception
Yes, it should be "internal", Client telemetry one.

2024-04-09 01:45 UTC, philipthomas-MSFT commented on changelog.md
> +- [4317](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4317) Client Telemetry: Refactors code to stop throwing an exception
removing from changelog

2024-04-09 01:53 UTC, philipthomas-MSFT commented
> > > Would probably be good to include that the new Taiwan regions are included in `Regions.cs` with the Direct Package upgrade in the changelog
> > 
> > 
> > I can agree with that. The PR was Internal. Was that a mistake? #4386
> 
> I think normally Direct package upgrades are marked as Internal, but for this upgrade I was unaware of the region changes and that is why it was marked that way. I think we can add something like [this ](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/4b2196bc6023dca0e6a396612efb4a1ca14cf09a/changelog.md?plain=1#L57)to the changelog and link to the direct upgrade PR. Also worth changing our direct upgrade guide to specify this which I will do.

Ok. @NaluTripician , added the new regions and direct package version update to the changelog. @kirankumarkolli

2024-04-09 01:53 UTC, philipthomas-MSFT commented on changelog.md
> +- [4323](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4323) Query: Adds Support for LINQ Custom Serializer in Public Release
@adityasa has already approved this PR once. Can you approve it again please?

2024-04-09 15:52 UTC, NaluTripician submitted a review, later dismissed

2024-04-09 17:18 UTC, sourabh1007 approved these changes

2024-04-09 17:57 UTC, kirankumarkolli approved these changes

2024-04-09 17:57 UTC, kirankumarkolli commented
@ealsur can you please also take a look?

2024-04-09 18:27 UTC, ealsur commented on Microsoft.Azure.Cosmos/contracts/API_3.38.2.txt
> +namespace Microsoft.Azure.Cosmos
Remove this file

2024-04-09 18:28 UTC, ealsur commented on changelog.md
> +- [4352](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4352) Documentation: Fixes spelling in ReplicaValidationDesign
This is a PR without any code changes that fixes a spelling on one of our repo docs, I would not include it. It's not anything shipped in the sdk

2024-04-09 18:28 UTC, ealsur commented on changelog.md
> +- [4380](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4380) ChangeFeedProcessor: Refactors AVAD Metadata Contract for ChangeFeed and ChangeFeedProcessor
Above item says AllVersionsAndDeletes and this one says AVAD, should we be consistent with the text for customer's clarity?

2024-04-09 18:29 UTC, ealsur commented on changelog.md
> +  > Note: There is added support for the following regions: `USSec West Central`, `Taiwan North` and `Taiwan Northwest`.
`USSec West Central` is internal, not public.

2024-04-09 19:35 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/contracts/API_3.38.2.txt
> +namespace Microsoft.Azure.Cosmos
done.

2024-04-09 19:35 UTC, philipthomas-MSFT commented on changelog.md
> +- [4352](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4352) Documentation: Fixes spelling in ReplicaValidationDesign
done

2024-04-09 19:36 UTC, philipthomas-MSFT commented on changelog.md
> +  > Note: There is added support for the following regions: `USSec West Central`, `Taiwan North` and `Taiwan Northwest`.
done

2024-04-09 19:36 UTC, philipthomas-MSFT commented on changelog.md
> +- [4380](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4380) ChangeFeedProcessor: Refactors AVAD Metadata Contract for ChangeFeed and ChangeFeedProcessor
done

2024-04-09 19:40 UTC, ealsur approved these changes

2024-04-09 19:42 UTC, kirankumarkolli approved these changes

2024-04-09 20:17 UTC, merged