[Internal] Distributed Tracing: Fixes Client Config Test
Azure/azure-cosmos-dotnet-v3 pull request #4407
Opened 2024-04-11 18:39 UTC by sourabh1007

## Description

**What is the change?**
Added "back", logic to generate activity id, even if customer is not subscribed to any source.

**Why is change required?**
As part of PR https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4333, I removed network level traces generation, along with that, this code was also removed where we were making sure that _traceid_ is generated, even if customer is not subscribed to the any traces.

**Why was it not caught in PR pipelines?**
It is part of emulator test, and we don't run emulator test in "preview" mode, in our PR pipelines.

## Type of change
- [] Bug fix (non-breaking change which fixes an issue)

## Closing issues
This would unblock 3.39.0 release

2024-04-11 18:59 UTC, philipthomas-MSFT approved these changes

2024-04-12 00:51 UTC, kirankumarkolli requested changes
Please port the commit from master

2024-04-12 11:23 UTC, sourabh1007 commented
@kirankumarkolli cherry-picked from master

2024-04-15 15:02 UTC, kirankumarkolli commented
Please check: https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4408#issuecomment-2057077230

2024-04-15 16:36 UTC, sourabh1007 commented
Creating new PR

2024-04-15 16:36 UTC, closed without merging