Query: Adds support for multi-value Group By query for LINQ
Azure/azure-cosmos-dotnet-v3 pull request #4481
Opened 2024-05-13 00:57 UTC by leminh98

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Include samples if adding new API, and include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #IssueNumber

2024-05-13 07:55 UTC, bartelink commented
Semi-related issues in case they are easy to address in the same block of work:
- https://github.com/Azure/azure-cosmos-dotnet-v3/issues/2607
- https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3728
(I'd love records support as it would let me remove some horrendous expression tree manipulation workarounds)

2024-05-16 03:53 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestGroupByMultiValueTranslation.xml
> +      <ErrorMessage><![CDATA[Status Code: BadRequest,{"errors":[{"severity":"Error","location":{"start":129,"end":134},"code":"SC1001","message":"Syntax error, incorrect syntax near 'value'."}]},0x80
This seems to indicate wrong query is being generated?

2024-05-16 03:54 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestGroupByMultiValueTranslation.xml
> +SELECT root["FamilyId"] AS familyId, ARRAY_LENGTH(root) AS familyIdCount
>ARRAY_LENGTH(root) [](http://example.com/codeflow?start=37&length=18)

Should this be COUNT(root)

2024-05-16 03:55 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestGroupByMultiValueTranslation.xml
> +      <ErrorMessage><![CDATA[Status Code: BadRequest,{"errors":[{"severity":"Error","location":{"start":7,"end":9},"code":"SC2102","message":"Property reference 'v1' is invalid in the select list bec
Same as before. Seems like invalid query is being generated?

2024-05-16 03:55 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestGroupByMultiValueTranslation.xml
> +      <ErrorMessage><![CDATA[Status Code: BadRequest,{"errors":[{"severity":"Error","location":{"start":93,"end":98},"code":"SC1001","message":"Syntax error, incorrect syntax near 'value'."}]},0x800A
Invalid query?

2024-05-16 03:57 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestGroupByMultiValueTranslation.xml
>    </Result>
>Result [](http://example.com/codeflow?start=4&length=6)

Can you please include the output as well?

2024-05-16 03:57 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestGroupByMultiValueTranslation.xml
> +SELECT r0 AS keyAlias, ARRAY_LENGTH(r0) AS count
>ARRAY_LENGTH(r0) [](http://example.com/codeflow?start=23&length=16)

This should be COUNT, no?

2024-05-16 03:58 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestGroupByMultiValueTranslation.xml
> +SELECT root["id"] AS Key, root["id"] AS key
>AS Key [](http://example.com/codeflow?start=18&length=6)

Neat

2024-05-16 04:02 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestGroupByMultiValueTranslation.xml
> +      <ErrorMessage><![CDATA[Status Code: BadRequest,{"errors":[{"severity":"Error","location":{"start":99,"end":110},"code":"SC2103","message":"Property reference 'root[\"Int\"]' is invalid in the O
>Status Code: BadRequest,{"errors":[{"severity":"Error","location":{"start":99,"end":110},"code":"SC2103","message":"Property reference 'root[\"Int\"]' is invalid in the ORDER BY clause because it is not contained in either an aggregate function or the GROUP BY clause."},{"severity":"Error","location":{"start":44,"end":48},"code":"SC2102","message":"Property reference 'root' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause."}]},0x800A0B00 [](http://example.com/codeflow?start=29&length=505)

Can you resolve these errors?

2024-05-16 04:03 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestGroupByMultiValueTranslation.xml
> +      <ErrorMessage><![CDATA[Status Code: BadRequest,{"errors":[{"severity":"Error","location":{"start":44,"end":48},"code":"SC2102","message":"Property reference 'root' is invalid in the select list
Is there a way for customers to resolve this error?

2024-05-16 04:04 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqGeneralBaselineTests.cs
> +                inputs[i].ignoreOrderingForAnonymousTypeObject = true;
We should avoid this for ORDER BY queries.

2024-05-16 04:04 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqTestsCommon.cs
> +            return queryResults.OrderBy(x => x).ToList().SequenceEqual(dataResults.OrderBy(x => x).ToList());
Ternary would be useful:
return ignoreOrdering?
 . . . :
 . . .;

2024-05-16 04:05 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqGeneralBaselineTests.cs
> +                inputs[i].ignoreOrderingForAnonymousTypeObject = true;
>ignoreOrderingForAnonymousTypeObject [](http://example.com/codeflow?start=26&length=36)

I would pass this as an argument to the constructor rather than modifying after the fact.

2024-05-16 04:05 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqTestsCommon.cs
> +        internal bool ignoreOrderingForAnonymousTypeObject;
readonly?

2024-05-16 04:10 UTC, adityasa requested changes
:clock1:

2024-05-16 04:13 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Linq/ExpressionToSQL.cs
> +                case ExpressionType.New:
I am not able to make the 1:1 connection between new expression and multi-value group by.
IOW, it's not clear why _every_ new expression here is a multi-value GROUP BY and vice-versa.

2024-05-21 09:48 UTC, leminh98 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestGroupByMultiValueTranslation.xml
> +      <ErrorMessage><![CDATA[Status Code: BadRequest,{"errors":[{"severity":"Error","location":{"start":99,"end":110},"code":"SC2103","message":"Property reference 'root[\"Int\"]' is invalid in the O
this is expected errors since we don't support order by and group by togerther

2024-05-21 09:48 UTC, leminh98 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestGroupByMultiValueTranslation.xml
> +      <ErrorMessage><![CDATA[Status Code: BadRequest,{"errors":[{"severity":"Error","location":{"start":44,"end":48},"code":"SC2102","message":"Property reference 'root' is invalid in the select list
none other than not combining groupby and order by since we dont support it

2024-05-21 09:51 UTC, leminh98 commented on Microsoft.Azure.Cosmos/src/Linq/ExpressionToSQL.cs
> +                case ExpressionType.New:
it's group by syntax as defined by LINQ
[https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.groupby?view=net-8.0](https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.groupby?view=net-8.0)

2024-05-21 10:08 UTC, leminh98 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestGroupByMultiValueTranslation.xml
>    </Result>
the data set is randomly generated. I don't think that would work with the baseline. Unless we fix the seed

2024-06-25 08:04 UTC, leminh98 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestGroupByMultiValueTranslation.xml
> +      <ErrorMessage><![CDATA[Status Code: BadRequest,{"errors":[{"severity":"Error","location":{"start":129,"end":134},"code":"SC1001","message":"Syntax error, incorrect syntax near 'value'."}]},0x80
fixed

2024-06-25 08:04 UTC, leminh98 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestGroupByMultiValueTranslation.xml
> +SELECT root["FamilyId"] AS familyId, ARRAY_LENGTH(root) AS familyIdCount
I think it should be count(1)

2024-06-25 08:05 UTC, leminh98 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestGroupByMultiValueTranslation.xml
> +      <ErrorMessage><![CDATA[Status Code: BadRequest,{"errors":[{"severity":"Error","location":{"start":7,"end":9},"code":"SC2102","message":"Property reference 'v1' is invalid in the select list bec
fixed

2024-06-25 08:05 UTC, leminh98 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestGroupByMultiValueTranslation.xml
> +      <ErrorMessage><![CDATA[Status Code: BadRequest,{"errors":[{"severity":"Error","location":{"start":93,"end":98},"code":"SC1001","message":"Syntax error, incorrect syntax near 'value'."}]},0x800A
fixed

2024-06-25 08:05 UTC, leminh98 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestGroupByMultiValueTranslation.xml
> +SELECT r0 AS keyAlias, ARRAY_LENGTH(r0) AS count
fixed

2024-06-26 20:48 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestGroupByMultiValueTranslation.xml
> +      <ErrorMessage><![CDATA[Status Code: BadRequest,{"errors":[{"severity":"Error","location":{"start":81,"end":107},"code":"SC2204","message":"'OFFSET LIMIT' clause is not supported in subqueries."
>Status Code: BadRequest,{"errors":[{"severity":"Error","location":{"start":81,"end":107},"code":"SC2204","message":"'OFFSET LIMIT' clause is not supported in subqueries."}]},0x800A0B00 [](http://example.com/codeflow?start=29&length=184)

Should we catch this earlier (during LINQ translation phase) or we don't have such provisions?

2024-06-26 20:51 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqTestsCommon.cs
> +            }
Nit, may be more efficient to use hashset/dictionary instead of double comparisons.

2024-06-26 20:52 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqTestsCommon.cs
> +        private static bool CompareListOfAnonymousType(List<object> queryResults, List<dynamic> dataResults, bool ignoreOrderingForAnonymousTypeObject)
>ignoreOrderingForAnonymousTypeObject [](http://example.com/codeflow?start=114&length=36)

I would rename this to simply ignoreOrder

2024-06-26 21:08 UTC, adityasa submitted a review, later dismissed
:shipit:

2024-07-01 17:40 UTC, leminh98 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestGroupByMultiValueTranslation.xml
> +      <ErrorMessage><![CDATA[Status Code: BadRequest,{"errors":[{"severity":"Error","location":{"start":81,"end":107},"code":"SC2204","message":"'OFFSET LIMIT' clause is not supported in subqueries."
We don't have that capabilities

2024-07-01 17:42 UTC, leminh98 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqTestsCommon.cs
> +            }
I'm doing double comparisions for parity with the other compare method below (CompareListOfArrays)

2024-07-01 17:42 UTC, leminh98 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqTestsCommon.cs
> +            }
I'm doing double comparisions for parity with the other compare method below (CompareListOfArrays)

2024-07-02 18:06 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqTestsCommon.cs
> +        private static void ValidateResults(List<object> queryResultsList, List<dynamic> dataResultsList, bool ignoreOrderingForAnonymousTypeObject)
Rename to just ignoreOrder?

2024-07-02 18:07 UTC, adityasa approved these changes

2024-07-03 14:16 UTC, adityasa approved these changes

2024-07-08 17:00 UTC, Maya-Painter approved these changes

2024-07-09 04:07 UTC, merged