Query: Adds DOCUMENTID extension method for LINQ
Azure/azure-cosmos-dotnet-v3 pull request #4489
Opened 2024-05-14 11:15 UTC by leminh98

# Pull Request Template

## Description

This PR adds the extension method to support the documentId system function in LINQ

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #2607

2024-05-16 03:40 UTC, adityasa commented
Please include test coverage.

2024-05-16 03:40 UTC, adityasa requested changes
:clock1:

2024-05-22 22:03 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqTranslationBaselineTests.TestDocumentIdBuiltinFunction.xml
> +  </Result>
>Result [](http://example.com/codeflow?start=4&length=6)

Can we include the output as well in the baseline?
I am curious what the output looks like in this case.

2024-05-22 22:07 UTC, adityasa commented on Microsoft.Azure.Cosmos/src/Linq/BuiltinFunctions/OtherBuiltinSystemFunctions.cs
> +                    true,
Named parameter would be nice

2024-05-22 22:09 UTC, adityasa approved these changes
:shipit:

2024-05-31 21:19 UTC, leminh98 commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqTranslationBaselineTests.TestDocumentIdBuiltinFunction.xml
> +  </Result>
We can't because the data is RNG every execution

2024-05-31 21:21 UTC, Maya-Painter approved these changes

2024-05-31 22:12 UTC, adityasa commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqTranslationBaselineTests.TestDocumentIdBuiltinFunction.xml
> +  </Result>
It's a new change, but I believe there are some tests that use deterministic data and include it in the output.

2024-05-31 22:14 UTC, kirankumarkolli approved these changes

2024-05-31 22:15 UTC, adityasa approved these changes
:shipit:

2024-06-04 19:01 UTC, Maya-Painter approved these changes

2024-06-04 19:40 UTC, adityasa approved these changes
:shipit:

2024-06-04 20:06 UTC, kirankumarkolli approved these changes

2024-06-04 20:06 UTC, merged