SDK 3.40.1: Adds version bump and changelog
Azure/azure-cosmos-dotnet-v3 pull request #4522
Opened 2024-06-01 09:26 UTC by hdornadula

# Pull Request Template

## Description

This bumps the SDK version 3.40.1. There were no changes to the GA public contract.

Preview contract changes:
![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/169304810/3d748be9-df4a-4ab1-a456-4b19c6e94df8)
![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/169304810/f53f9765-3388-467b-a3ba-1c10f24144c6)
![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/169304810/bf98373c-f52d-4bfc-aabe-8b7dddb6b6ff)
![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/169304810/6e985449-349a-4693-8914-a93a43b80145)
![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/169304810/30e7244a-0f17-4dbe-9d76-31df3042583c)

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #IssueNumber

2024-06-03 09:49 UTC, kundadebdatta approved these changes

2024-06-03 19:53 UTC, ealsur requested changes

2024-06-03 19:53 UTC, ealsur commented on changelog.md
> +### <a name="3.41.0-preview.1"/> [3.41.0-preview.1](https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.41.0-preview.1) - 2024-05-31
The screenshot shows `DeleteAllByPartitionKey` being added (green), and the files being compared are not the preview versions.

The content of API_3.40.1.txt seems to be from a preview SDK

2024-06-03 19:53 UTC, ealsur commented on Microsoft.Azure.Cosmos/contracts/API_3.40.1.txt
> +        public abstract Task<ResponseMessage> DeleteAllItemsByPartitionKeyStreamAsync(PartitionKey partitionKey, RequestOptions requestOptions=null, CancellationToken cancellationToken=default(Cancel
This is wrong, this method is not public in `3.40.1`

2024-06-03 19:54 UTC, ealsur commented on changelog.md
> +- [4488](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4488) Add test (#4488)
This PR's title is `[Internal] Query: Adds Multi-key Group By LINQ to SQL translation tests` - should it be removed? Since it's internal

2024-06-04 00:14 UTC, kirankumarkolli commented on changelog.md
> +- [4511](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4511) FaultInjection: Refactors applyPercentage name to injectionRate to make feature clearer. (#4511)
So-far fault injection ones are not listed in release notes. Please exclude it.

2024-06-04 00:15 UTC, kirankumarkolli commented on changelog.md
> +- [4507](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4507) Query : Fixes ORDER BY query issue when partial partition key is specified with hierarchical partition (#4507)
@adityasa can you please take a look?

2024-06-04 17:14 UTC, ealsur commented on changelog.md
> +- [4507](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4507) Query : Fixes ORDER BY query issue when partial partition key is specified with hierarchical partition (#4507)
If the release will also include the binary fix, should we include it in the changelog so people can identify it if they do run into the error?

2024-06-06 23:08 UTC, hdornadula commented on changelog.md
> +### <a name="3.41.0-preview.1"/> [3.41.0-preview.1](https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.41.0-preview.1) - 2024-05-31
@ealsur , I think I know what went wrong here. 

1. Based on the modification in Directory.Build.props, I ran a Preview release 
`dotnet build /p:IsPreview=true -c Release`
2. Based on this build, I then generated the API document for the official version
`GenAPI.exe -assembly:"Microsoft.Azure.Cosmos.Client.dll" -apiOnly -s:text -out:API_3.40.1.txt`

To fix this, do I run a local release build first ? Or can I just re-run the GenAPI.exe with the correct API file name for preview release?
`dotnet build -c Release`

2024-06-07 20:39 UTC, closed without merging