[Internal] ClientRetryPolicy: Fixes Partition Failover on Next region when RG Fails with `HttpRequestException`
Azure/azure-cosmos-dotnet-v3 pull request #4565
Opened 2024-06-28 19:27 UTC by kundadebdatta

# Pull Request Template

## Description

### Background:

During one of our recent backend DR drills, it was found that, when the primary region's routing gateway is experiencing an outage, and the server and master partition were taken down, the .NET v3 SDK kept retrying on the same region for `20` minutes, until the primary write region came back up. This issue have been identified as intermittent and titled as "hanging cosmos client".

**Account Setup For 3 regions :** Create a cosmos account (single master) with 3 regions, **WestUs2** (Write), **EastUs2** (Read) and **NorthCentralUS** (Read). The PPAF configuration from the BE is to failover to **EastUs2**, in case **WestUs2** is unavailable.

**Scenario:** While creating the cosmos client, in the application preferred region, provide **WestUs2**, **EastUs2** and **NorthCentralUS** as preferred regions.

```
            CosmosClientOptions clientOptions = new CosmosClientOptions()
            {
                ApplicationPreferredRegions = new List<string>()
                {
                    Regions.WestUs2,
                    Regions.EastUs2,
                    Regions.NorthCentralUS
                },
                EnablePartitionLevelFailover = true,
```

There were `2` different accounts (each with `100` partitions), and `40` different clients were set up in the same region (West US 2) per account, which boils down to total `80` cosmos clients.

There is only `1` cluster involved in each region i.e. all `200` partitions for both accounts are on `westus2-be2` (and same for `EastUs2` and `NorthCentralUS`)

After initializing and warming up the cosmos client, the cluster (stopped all Server+ Master nodes) was brought down at `2024-05-09 20:30` for `8` minutes. This also brings down the Routing Gateway service in the West US 2 region.

**Current Behavior:** The SDK keeps retrying on the region **WestUs2** for writing the document (since WestUs2 is the single write region) and after keep retrying for `25` minutes, the attempt finally marks successful once the region came back up. This issue is identified as the request got "hung" for `25` minutes. To understand this better, take a look at the below diagnostics:

<details>
  <summary>Diagnostics Snippet - Scenario: Routing Gateway, along with Server and Master partitions are completely down.</summary>
  
```json
       "Summary": {
          "DirectCalls": {
              "(503, 20006)": 1,
              "(403, 3)": 19,
              "(410, 20001)": 99,
              "(201, 0)": 1,
              "(204, 0)": 1
          },
          "GatewayCalls": {
              "(200, 0)": 2,
              "(0, 0)": 9
          }
      }
```
</details>

### Why Did This Happened?

Note: This is applicable for write requests in a single master write account. When the complete cluster (nodes, that hosts all the server partitions + master partition) is down due to an outage, and the routing gateway is not reachable, after some retries in the `GoneAndRetryWithRequestRetryPolicy` the write request finally fails with a `TransportGenerated410`.

<details>

  <summary>Diagnostics Snippet - Transport Stack Failure.</summary>

```json
{
    "ResponseTimeUTC": "2024-04-24T22:19:31.5361673Z",
    "ResourceType": "Document",
    "OperationType": "Create",
    "LocationEndpoint": "https://mmankos-0404-ppaf-3-westus2.documents-staging.windows-ppe.net/",
    "StoreResult": {
        "ActivityId": "c3f0c0fa-f198-4eea-95c8-adbc378b8559",
        "StatusCode": "Gone",
        "SubStatusCode": "TransportGenerated410",
        "LSN": -1,
        "PartitionKeyRangeId": null,
        "GlobalCommittedLSN": -1,
        "ItemLSN": -1,
        "UsingLocalLSN": false,
        "QuorumAckedLSN": -1,
        "SessionToken": null,
        "CurrentWriteQuorum": -1,
        "CurrentReplicaSetSize": -1,
        "NumberOfReadRegions": -1,
        "IsValid": false,
        "StorePhysicalAddress": "rntbd://cdb-ms-stage-westus2-be2.documents-staging.windows-ppe.net:14351/apps/08a9385f-af01-40f2-bd90-10d4f17133a4/services/80c902b9-1d8f-48b2-a0fc-11a9e5bf8eed/partitions/f1f7ae05-77cd-4f52-b733-955cfb301b70/replicas/133554390203135475p/",
        "RequestCharge": 0,
        "RetryAfterInMs": null,
        "BELatencyInMs": null,
        "ReplicaHealthStatuses": [
            "(port: 14351 | status: Connected | lkt: 4/24/2024 10:09:38 PM)"
        ],
        "transportRequestTimeline": {
            "requestTimeline": [
                {
                    "event": "Created",
                    "startTimeUtc": "2024-04-24T22:19:26.9718530Z",
                    "durationInMs": 0.002
                },
                {
                    "event": "ChannelAcquisitionStarted",
                    "startTimeUtc": "2024-04-24T22:19:26.9718550Z",
                    "durationInMs": 4564.25
                },
                {
                    "event": "Failed",
                    "startTimeUtc": "2024-04-24T22:19:31.5361050Z",
                    "durationInMs": 0
                }
            ],
            "serviceEndpointStats": {
                "inflightRequests": 11,
                "openConnections": 1
            },
            "connectionStats": {
                "waitforConnectionInit": "True"
            }
        },
        "TransportException": "A client transport error occurred: The connection attempt timed out. (Time: 2024-04-24T22:19:31.5358378Z, activity ID: f5c15e36-470d-44e0-9c41-61d2132b82af, error code: ConnectTimeout [0x0006], base error: HRESULT 0x80131500, URI: rntbd://cdb-ms-stage-westus2-be2.documents-staging.windows-ppe.net:14351/, connection: <not connected> -> rntbd://cdb-ms-stage-westus2-be2.documents-staging.windows-ppe.net:14351/, payload sent: False)"
    }
}
```
</details>

This triggers a force address refresh, which after `3` attempts fails with a `HttpRequestException` since the gateway service itself is not rechable.

<details>
  <summary>Diagnostics Snippet - HTTP Response Stack.</summary>

```json
"HttpResponseStats": [
    {
        "StartTimeUTC": "2024-04-24T22:20:57.1125860Z",
        "DurationInMs": 505.6518,
        "RequestUri": "https://mmankos-0404-ppaf-3-westus2.documents-staging.windows-ppe.net//addresses/?$resolveFor=dbs%2fIkltAA%3d%3d%2fcolls%2fIkltALjPvaU%3d%2fdocs&$filter=protocol eq rntbd&$partitionKeyRangeIds=15",
        "ResourceType": "Document",
        "HttpMethod": "GET",
        "ActivityId": "c3f0c0fa-f198-4eea-95c8-adbc378b8559",
        "ExceptionType": "System.Threading.Tasks.TaskCanceledException",
        "ExceptionMessage": "A task was canceled."
    },
    {
        "StartTimeUTC": "2024-04-24T22:20:57.6182567Z",
        "DurationInMs": 5009.6365,
        "RequestUri": "https://mmankos-0404-ppaf-3-westus2.documents-staging.windows-ppe.net//addresses/?$resolveFor=dbs%2fIkltAA%3d%3d%2fcolls%2fIkltALjPvaU%3d%2fdocs&$filter=protocol eq rntbd&$partitionKeyRangeIds=15",
        "ResourceType": "Document",
        "HttpMethod": "GET",
        "ActivityId": "c3f0c0fa-f198-4eea-95c8-adbc378b8559",
        "ExceptionType": "System.Threading.Tasks.TaskCanceledException",
        "ExceptionMessage": "A task was canceled."
    },
    {
        "StartTimeUTC": "2024-04-24T22:21:03.6319840Z",
        "DurationInMs": 13527.8359,
        "RequestUri": "https://mmankos-0404-ppaf-3-westus2.documents-staging.windows-ppe.net//addresses/?$resolveFor=dbs%2fIkltAA%3d%3d%2fcolls%2fIkltALjPvaU%3d%2fdocs&$filter=protocol eq rntbd&$partitionKeyRangeIds=15",
        "ResourceType": "Document",
        "HttpMethod": "GET",
        "ActivityId": "c3f0c0fa-f198-4eea-95c8-adbc378b8559",
        "ExceptionType": "System.Net.Http.HttpRequestException",
        "ExceptionMessage": "A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (mmankos-0404-ppaf-3-westus2.documents-staging.windows-ppe.net:443)"
    }
]
```
</details>

This  [...]

2024-06-28 19:29 UTC, kundadebdatta commented
For better understanding, I have attached the diagnostics for the write request that took more than 20 mins to complete.

[req_ok_30m.json](https://github.com/user-attachments/files/16036031/req_ok_30m.json)

2024-06-28 20:45 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs
> +                    this.partitionKeyRangeLocationCache.TryMarkEndpointUnavailableForPartitionKeyRange(
What if this returns false? Should it return NoRetry like the other calls in this file?

2024-07-01 16:50 UTC, FabianMeiswinkel requested changes
I think we need the meeting - to me this sounds like an issue even without PPAF enabled - because at the point in question RGW is simply down. So, I don't think any change filtering to scope to PPAF can be the right one? Or am I missing something in the repro instructions?

2024-07-01 17:03 UTC, kundadebdatta commented
> I think we need the meeting - to me this sounds like an issue even without PPAF enabled - because at the point in question RGW is simply down. So, I don't think any change filtering to scope to PPAF can be the right one? Or am I missing something in the repro instructions?

>> The only difference when PPAF is enabled vs disabled is that, there is a chance that the faulty partition will be failed over. So the retry might be successful, while without PPAF, there is no way that partition could fail over.

2024-07-01 20:41 UTC, j82w commented on Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs
> +                if (this.isPertitionLevelFailoverEnabled)
This will still be broken for non-PPAF accounts. Why isn't this incrementing and breaking out of retries after some time interval or retry count?

2024-07-01 21:16 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs
> +                if (this.isPertitionLevelFailoverEnabled)
For non-PPAF, I think if a `CancellationToken` is provided, then the request will time out when the token expires. On the "breaking out of retry" part, I will mention that in the design doc, so that we all can agree on a common approach.

2024-07-02 12:46 UTC, j82w commented on Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs
> +                if (this.isPertitionLevelFailoverEnabled)
Is the design for non-PPAF accounts that the client retry policy should retry forever on gateway outages unless a customer passes in a cancellation token?

2024-07-09 20:46 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs
> +                    this.partitionKeyRangeLocationCache.TryMarkEndpointUnavailableForPartitionKeyRange(
Shall we defer this decision to the `ShouldRetryOnEndpointFailureAsync()` method, as per the current flow ? It will anyway return a no retry when it reaches `MaxRetryCount`:

```
            if (this.failoverRetryCount > MaxRetryCount || (!this.enableEndpointDiscovery && !overwriteEndpointDiscovery))
            {
                DefaultTrace.TraceInformation("ClientRetryPolicy: ShouldRetryOnEndpointFailureAsync() Not retrying. Retry count = {0}, Endpoint = {1}", 
                    this.failoverRetryCount,
                    this.locationEndpoint?.ToString() ?? string.Empty);
                return ShouldRetryResult.NoRetry();
            }
```

2024-07-10 13:03 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs
> +                if (this.isPertitionLevelFailoverEnabled)
There is a max retry count enforcement already - in ShouldRetryOnEndpointFailureAsync line 292 and following of this file

2024-07-10 16:49 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs
> +                if (this.isPertitionLevelFailoverEnabled)
The looping behavior is not changing, the same limits still apply. When PPAF is not enabled, on a write operation, there is  no other region to attempt unless the Gateway Account refresh returns new information, so yes, the client is expected to loop until the max retry hits as has always been.

2024-07-10 22:10 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs
> +                    this.partitionKeyRangeLocationCache.TryMarkEndpointUnavailableForPartitionKeyRange(
Good idea.

2024-07-12 16:35 UTC, ealsur approved these changes

2024-07-12 18:24 UTC, FabianMeiswinkel approved these changes
LGTM

2024-07-15 21:33 UTC, kirankumarkolli approved these changes

2024-07-16 16:45 UTC, merged