Users/philipthomas msft/add feedranges to avad contract
Azure/azure-cosmos-dotnet-v3 pull request #4566
Opened 2024-07-02 14:37 UTC by philipthomas-MSFT

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Include samples if adding new API, and include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #IssueNumber

2024-07-31 18:00 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedProcessorBuilder.cs
> +            if (this.changeFeedProcessorOptions.Mode == ChangeFeedMode.AllVersionsAndDeletes)
This sounds like a different change? Should these be a different PR?

2024-07-31 18:00 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedProcessorBuilder.cs
> +                throw new NotImplementedException($"Using the 'WithStartFromBeginning' option with ChangeFeedProcessor is not supported with {ChangeFeedMode.AllVersionsAndDeletes} mode.");
NotImplementedException is meant for methods without code, this sounds like InvalidOperationException

2024-07-31 18:02 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/Observers/ChangeFeedObserverContextCore.cs
> +        FeedRange FeedRange => new FeedRangeEpk(this.Headers.FeedRangeEpk.Range);
`ChangeFeedObserverContextCore` already receives data (`leaseToken`) that is not part of the response. You can do the same thing without wiring things through the Headers and through the Iterator:

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/908f037c8ad20d5f88948629e3a02a025aec0b8f/Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedProcessing/FeedProcessorCore.cs#L128

2024-07-31 18:05 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/ChangeFeed/ChangeFeedPartitionKeyResultSetIteratorCore.cs
> +                feedRangeEpk: lease?.FeedRange is FeedRangeEpk epk ? epk : default);
nit: This can be null, should the contract on the Context be `FeedRange?` so the consumer sees that it can be null?

2024-07-31 18:06 UTC, ealsur requested changes
Can we split this into different PRs? This PR is doing 3 things:

* Adding StartTime validation for AVAD
* Adding FeedRange in Context for all kinds of CFP
* Adding FindOverlappingRanges APIs to COntainers (completely unrelated to CFP)

2024-07-31 18:08 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +        public abstract Task<IReadOnlyList<Cosmos.FeedRange>> FindOverlappingRangesAsync(Cosmos.PartitionKey partitionKey, IReadOnlyList<Cosmos.FeedRange> feedRanges, CancellationToken cancellationTo
How are customers supposed to use these 2 new methods and which are the use cases? Can we add the details to the PR Description? Which are the expectations? What happens if the SDK has stale caches, is the customer ok with receiving stale results?

2024-07-31 18:09 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            foreach (Documents.Routing.Range<string> range in ContainerCore.ConvertToRange(feedRanges))
This can throw. If the input is a FeedRange that is not FeedRangeEpk, ConvertToRange returns null

2024-07-31 18:11 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                    range1: await this.ConvertToRangeAsync(
`range1` does not change value inbetween iterations, shouldn't we be calculating it once before the loop instead of every time?

2024-07-31 18:12 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            Cosmos.FeedRange feedRange,
What if `feedRange` and `feedRanges` are from different Containers, what's the use case we are trying to solve?

2024-08-01 11:42 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedProcessorBuilder.cs
> +            if (this.changeFeedProcessorOptions.Mode == ChangeFeedMode.AllVersionsAndDeletes)
@ealsur This is really all 1 feature set, not 3 different individual features which is why I decided to put them all together in 1 PR. Normally, I would agree, but they all work together to define a feature set. I agree that I need to add more details on the use case in documentation and I will include that, but making 3 PRs is going to be counterproductive.

2024-08-01 11:43 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedProcessorBuilder.cs
> +                throw new NotImplementedException($"Using the 'WithStartFromBeginning' option with ChangeFeedProcessor is not supported with {ChangeFeedMode.AllVersionsAndDeletes} mode.");
I agree. Makes sense @ealsur

2024-08-01 11:44 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +        public abstract Task<IReadOnlyList<Cosmos.FeedRange>> FindOverlappingRangesAsync(Cosmos.PartitionKey partitionKey, IReadOnlyList<Cosmos.FeedRange> feedRanges, CancellationToken cancellationTo
@ealsur I agree that I need to add more details on the use case in documentation and I will include that.

2024-08-01 11:47 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            Cosmos.FeedRange feedRange,
@ealsur I will document this in detail so that it is clear. Thanks for the review.

2024-08-01 11:48 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                    range1: await this.ConvertToRangeAsync(
@ealsur Will circle back with you once I have the documentation so that we can achieve alignment and clarity. Thanks for review.

2024-08-01 11:49 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/Observers/ChangeFeedObserverContextCore.cs
> +        FeedRange FeedRange => new FeedRangeEpk(this.Headers.FeedRangeEpk.Range);
@ealsur Will circle back with you once I have the documentation so that we can achieve alignment and clarity. Thanks for review.

2024-08-01 11:50 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/ChangeFeed/ChangeFeedPartitionKeyResultSetIteratorCore.cs
> +                feedRangeEpk: lease?.FeedRange is FeedRangeEpk epk ? epk : default);
@ealsur acknowledged.

2024-08-01 11:50 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            foreach (Documents.Routing.Range<string> range in ContainerCore.ConvertToRange(feedRanges))
@ealsur acknowledged.

2024-08-05 16:53 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedProcessorBuilder.cs
> +                throw new NotImplementedException($"Using the 'WithStartFromBeginning' option with ChangeFeedProcessor is not supported with {ChangeFeedMode.AllVersionsAndDeletes} mode.");
moved this to a different PR that is already complete.

2024-08-05 16:54 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/Observers/ChangeFeedObserverContextCore.cs
> +        FeedRange FeedRange => new FeedRangeEpk(this.Headers.FeedRangeEpk.Range);
this was moved to another PR.

2024-08-05 16:54 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/ChangeFeed/ChangeFeedPartitionKeyResultSetIteratorCore.cs
> +                feedRangeEpk: lease?.FeedRange is FeedRangeEpk epk ? epk : default);
moved to another PR

2024-08-05 16:54 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +        public abstract Task<IReadOnlyList<Cosmos.FeedRange>> FindOverlappingRangesAsync(Cosmos.PartitionKey partitionKey, IReadOnlyList<Cosmos.FeedRange> feedRanges, CancellationToken cancellationTo
detailed documentation added and being reviewed by customer.

2024-08-05 16:55 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            Cosmos.FeedRange feedRange,
Document is being reviewed.

2024-08-05 17:11 UTC, kirankumarkolli commented
Can we please expand with more context on the API requirement. 
FeedRange API in response seems like covers the requirement already right?

2024-08-05 18:28 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            foreach (Documents.Routing.Range<string> range in ContainerCore.ConvertToRange(feedRanges))
@ealsur  I am assuming you are talking about this, https://github.com/Azure/azure-cosmos-dotnet-v3/blob/ce57c96942123148f6001ea5879a2c8a37d9417c/Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs#L1313

but honestly, when can a FeedRange, in this case, never able to cast to a FeedRangeEpk? This is done so that I can get the Range<string> which is the only thing that I really care about.

2024-08-06 02:28 UTC, kirankumarkolli commented
Discussed offline and waiting for clarification on the issue.

2024-08-06 18:23 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            foreach (Documents.Routing.Range<string> range in ContainerCore.ConvertToRange(feedRanges))
resolving this, but please feel free to re-open so we can discuss. Thanks. @ealsur

2024-08-07 20:26 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos.Encryption.Custom/src/EncryptionContainer.cs
> +        public override Task<IReadOnlyList<Cosmos.FeedRange>> FindOverlappingRangesAsync(
As discussed offline lets please update the API's

2024-08-14 17:56 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos.sln
> +# Visual Studio Version 17
Forces everyone to use VS2022 right? 
Moving to latest version is not really needed and also unrelated to the PR scope.

2024-08-14 17:56 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos.sln
> +# Visual Studio Version 17
This whole file can be reverted.

2024-08-14 18:00 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +            throw await Task.FromException<NotImplementedException>(default);
await is forced as contract is using async right?
Just removing async from definition will make the implementation simple with just throw new NIE()

2024-08-14 18:08 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +        public virtual async Task<bool> IsSubsetAsync(Cosmos.FeedRange parentFeedRange, Cosmos.PartitionKey partitionKey, CancellationToken cancellationToken = default)
This API is NOT must but convenience API right? 
I.e. developer can still create a FeedRange.FromPartitionKey() can call below API.

If so one alternative is we can cover that part of below API code doc remarks/usage section.

2024-08-14 18:15 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                range1: ContainerCore.ConvertToRange(parentFeedRange),
FeedRange might be FeedRangeEpk or FeedRangePartitionKey. 

ConvertToRange just does a cast and Range, won't it result in NRE? 
Or the expectation is this methos always called with EpkRange?

2024-08-14 18:15 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +            throw await Task.FromException<NotImplementedException>(default);
already changed this

2024-08-14 18:21 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos.Encryption.Custom/src/EncryptionContainer.cs
> +
Undo this file? (no changes right)

2024-08-14 18:26 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
> +        "Boolean IsSubset(Microsoft.Azure.Cosmos.FeedRange, Microsoft.Azure.Cosmos.FeedRange)": {
Please update PR description with below details
- Title: Refresh
- New API's
- Usage example

2024-08-14 18:29 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        public override async Task<bool> IsSubsetAsync(FeedRange parentFeedRange, PartitionKey partitionKey, CancellationToken cancellationToken = default)
How would this play out with Hierarchical Partition Keys? Would this need to validate that the PartitionKey is not partial first? Otherwise, the call to GetPointRange will yield invalid results

2024-08-14 18:32 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        private async Task<Documents.Routing.Range<string>> ConvertToRangeAsync(PartitionKey partitionKey, CancellationToken cancellationToken)
FeedRangeInternal has `GetEffectiveRangesAsync` which return the Ranges regardless of the type (Epk, PK, etc).

2024-08-14 18:32 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        private async Task<Documents.Routing.Range<string>> ConvertToRangeAsync(PartitionKey partitionKey, CancellationToken cancellationToken)
You can cast the FeedRange to FeedRangeInternal and use it.

2024-08-14 18:34 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +        public virtual async Task<bool> IsSubsetAsync(Cosmos.FeedRange parentFeedRange, Cosmos.PartitionKey partitionKey, CancellationToken cancellationToken = default)
True. A single API just taking FeedRange can serve both purposes.

2024-08-14 18:36 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        public override async Task<bool> IsSubsetAsync(FeedRange parentFeedRange, PartitionKey partitionKey, CancellationToken cancellationToken = default)
Thinking about it, if we end up using this: https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4566#discussion_r1717387625, then the partial PK would get converted to a Range which should work correctly, but it would require to use the GetEffectiveRangesAsync method to be resilient to partial PKs

2024-08-15 13:19 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +        public virtual async Task<bool> IsSubsetAsync(Cosmos.FeedRange parentFeedRange, Cosmos.PartitionKey partitionKey, CancellationToken cancellationToken = default)
Sure, thought there was an explicit need to allow for this but if user has access to `FeedRange.FromPartitionKey()`, then it makes sense.

2024-08-15 14:31 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        public override bool IsSubset(FeedRange parentFeedRange, FeedRange childFeedRange)
Using the Overlapping APIs will return true for example if:

parentFeedRange: [A, F)
childFeedRange: [C, X)

Because they overlap.

But childFeedRange is not a subset. Subset means it's either the same or a smaller part?

2024-08-15 14:57 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        private async Task<Documents.Routing.Range<string>> ConvertToRangeAsync(PartitionKey partitionKey, CancellationToken cancellationToken)
changed. please review.

2024-08-15 14:57 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        public override async Task<bool> IsSubsetAsync(FeedRange parentFeedRange, PartitionKey partitionKey, CancellationToken cancellationToken = default)
changed. please review.

2024-08-15 15:06 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                range1: ContainerCore.ConvertToRange(parentFeedRange),
changed. please review.

2024-08-15 16:02 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            FeedRangeInternal childFeedRangeInternal = (FeedRangeInternal)childFeedRange;
`FeedRange` public type can be mocked or implemented by customer and might not always cast to `FeedRangeInternal`.  Throw argument exception in those cases.

2024-08-15 16:09 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            ContainerResponse containerResponse = await this.ReadContainerAsync();
In the use case IsSUbset is expected to be called at higher usage, each call will result in invocation to ReadContainerAsync() which is a NW call and also result in master budget throttling (de-stabilizing the account).

2024-08-15 16:12 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            ContainerResponse containerResponse = await this.ReadContainerAsync();
`GetCachedRIDAsync` can be used as workaround, with Cavet that in-case of container recreation it might return stale till some other operation refreshes it.

2024-08-15 16:23 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                .Where(pair => Documents.Routing.Range<string>.CheckOverlapping(
Overlapping still superset of subset requirement right?

2024-08-15 17:44 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        public override bool IsSubset(FeedRange parentFeedRange, FeedRange childFeedRange)
Correct. Or change the API to be Overlapping or something different than Subset.

2024-08-15 17:44 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                .Where(pair => Documents.Routing.Range<string>.CheckOverlapping(
https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4566#discussion_r1718487929

2024-08-15 18:41 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            ContainerResponse containerResponse = await this.ReadContainerAsync();
See GetFeedRangesAsync for reference on how to use GetCachedRIDAsync

2024-08-17 23:39 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                throw new ArgumentException($"Arguments for '{nameof(parentFeedRange)}' and '{nameof(childFeedRange)}' are not supported.");
How about include the Type which will help in troubleshooting

2024-08-17 23:40 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                    var overlaps = parentRanges
Convention use actual type not `var`

2024-08-17 23:42 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        private static bool IsSubset(dynamic overlaps)
Type is dynamic? Please make it specific type

2024-08-19 16:40 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                        .FirstOrDefault();
Can you please expand on why decision is limited to first combination?

Setup: [A, b), [B, C), [C, D)

Example1: Expectation `false`
Parent: [A, C)
Child: [A, D)

Example2: Expectation `true`
Parent: [A, C)
Child: [B, C)

2024-08-19 17:56 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                        .FirstOrDefault();
It supports the following as subsets:

Parent: (A,Z)
Child: (A,Z), (A,M), (M,A) and (G, T)

But not

Parent: (A,M)
Child: (G,Z) overlap, but not subset.

Tests https://github.com/Azure/azure-cosmos-dotnet-v3/blob/6aa94875770581f5d57b27cb778735519c217c81/Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs#L1879C9-L1896C9

2024-08-19 19:59 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                        .FirstOrDefault();
From offline conversation: 

FeedRange
	- Exact
	- PKValue (Hash - algorithm)
		- Single PK			=> Single EPK value
		- Hierarchal PK     => Range

Input: 
	Parent: [A, C) 
	Child : [B, D) 
	expected: 	IsChild = True
				Overlap = False

Collection current state: [A, b), [B, C), [C, D) [D, f) -> (f == FFFFF)
GetEffectiveRangesAsync
	Parent: [A, C) -> List() { [A, b), [B, C) }
	Child : [B, D) -> List() { [B, C), [C, D) }

SelectMany: IEnum<Overlap> => CheckOverlapping
	[A, b), [B, C) => false
	[A, b), [C, D) => false
	[B, C), [B, C) => true
	[B, C), [C, D) => false

ContainerCore.IsSubset
	Overlap: [B, C), [B, C) => true


Example: 
	// [B, D)
	PartitionKey partitionKey = new PartitionKeyBuilder()
	.Add("WA")
	.Add(Guid.NewGuid().ToString())
	.Build();
	
	FeedRange feedRange = FeedRange.FromPartitionKey(partitionKey);
    container.IsSubsetAsync(
                    parentFeedRange: new FeedRangeEpk(new Documents.Routing.Range<string>(parentMin, parentMax, true, false)),
                    childFeedRange: feedRange,
                    cancellationToken: CancellationToken.None);	
	
bool IsSubset(EPKFeedRange, PkFeedRange) {

	PkFeedRange.GetEffectiveRangesAsync() -> { [B, C), [C, D) }
	-> [B, D)

	return IsSubset(EPKFeedRange, PkFeedRange.ToEpkRange());
}

bool IsSubset(EPKFeedRange, EPKFeedRange) {
}

2024-08-20 00:12 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                        .FirstOrDefault();
fixed.

2024-08-20 16:53 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +        public virtual Task<bool> IsSubsetAsync(Cosmos.FeedRange parentFeedRange, Cosmos.FeedRange childFeedRange, CancellationToken cancellationToken)
Please include the code sample references in code-doc.

2024-08-20 16:53 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +        public virtual Task<bool> IsSubsetAsync(Cosmos.FeedRange parentFeedRange, Cosmos.FeedRange childFeedRange, CancellationToken cancellationToken)
```suggestion
        public virtual Task<bool> IsSubsetAsync(Cosmos.FeedRange parentFeedRange, Cosmos.FeedRange childFeedRange, CancellationToken cancellationToken = default)

```

2024-08-20 16:54 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +        public virtual Task<bool> IsSubsetAsync(Cosmos.FeedRange parentFeedRange, Cosmos.FeedRange childFeedRange, CancellationToken cancellationToken)
PR description: Samples swapped between ParititonKey and HierarchicalPartitionKey

2024-08-20 16:55 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                throw new ArgumentException($"Arguments for '{nameof(parentFeedRange)}' and '{nameof(childFeedRange)}' are not supported.");
Including the type information in exception message will help troubleshooting right?

2024-08-20 16:58 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                    IRoutingMapProvider routingMapProvider = await this.ClientContext.DocumentClient.GetPartitionKeyRangeCacheAsync(NoOpTrace.Singleton);
NoOpTrace used, is it intentional?

2024-08-20 16:59 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                        min: parentRanges.FirstOrDefault().Min,
FirstOrDefault vs First ony?

2024-08-20 17:31 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                        min: parentRanges.FirstOrDefault().Min,
In-general GetEffectiveRangeAsync() return ordered ranges but its not guaranteed, ideal if we can explicitly sort and consume. In other cases order of them doesn't matter.

2024-08-20 17:31 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                && String.Compare(childRange.Max, parentRange.Max) <= 0;
max is exclusive right. '=" will violate that constraint?

2024-08-20 17:31 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInlineCore.cs
> +        public override async Task<bool> IsSubsetAsync(FeedRange parentFeedRange, FeedRange childFeedRange, CancellationToken cancellationToken)
```suggestion
        public override async Task<bool> IsSubsetAsync(FeedRange parentFeedRange, FeedRange childFeedRange, CancellationToken cancellationToken=default)

```

2024-08-20 17:31 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                && String.Compare(childRange.Max, parentRange.Max) <= 0;
One option is to leverage Range.Contains
- Parent.Contains(Child.Min) = True
- (Parent.Max == Child.Max) || Parent.Contains(Child.Max)

2024-08-20 17:31 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
> +                ContainerResponse containerResponse = await this.cosmosDatabase.CreateContainerIfNotExistsAsync(
FYI... Default container creation will mostly have a single partition with [00, FF) range => GetEffectiveRangeAsync() will at-max return one entry in these tests.

2024-08-21 18:46 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                throw new ArgumentException($"Arguments for '{nameof(parentFeedRange)}' and '{nameof(childFeedRange)}' are not supported.");
Done.

2024-08-21 19:06 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +        public virtual Task<bool> IsSubsetAsync(Cosmos.FeedRange parentFeedRange, Cosmos.FeedRange childFeedRange, CancellationToken cancellationToken)
Done.

2024-08-21 19:09 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +        public virtual Task<bool> IsSubsetAsync(Cosmos.FeedRange parentFeedRange, Cosmos.FeedRange childFeedRange, CancellationToken cancellationToken)
Done.

2024-08-21 19:11 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                    IRoutingMapProvider routingMapProvider = await this.ClientContext.DocumentClient.GetPartitionKeyRangeCacheAsync(NoOpTrace.Singleton);
Done.

2024-08-21 19:16 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                        min: parentRanges.FirstOrDefault().Min,
> FirstOrDefault vs First ony?

I can live with _First_. Initially I was thinking that _FirstOrDefault_ would be better, but _First_ has exception handling and be better because it should never be empty and if it is, we should not be masked with a default value. So I changed it.

2024-08-21 19:21 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                        min: parentRanges.FirstOrDefault().Min,
> In-general GetEffectiveRangeAsync() return ordered ranges but its not guaranteed, ideal if we can explicitly sort and consume. In other cases order of them doesn't matter.

Resolving this conversation since this is duplicated in another one.

2024-08-21 20:02 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                        min: parentRanges.FirstOrDefault().Min,
> In-general GetEffectiveRangeAsync() return ordered ranges but its not guaranteed, ideal if we can explicitly sort and consume. In other cases order of them doesn't matter.

Done.

2024-08-22 14:02 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                && String.Compare(childRange.Max, parentRange.Max) <= 0;
Done. Also included case to deal with FeedRangePartitionKey.

2024-08-22 14:03 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
> +                ContainerResponse containerResponse = await this.cosmosDatabase.CreateContainerIfNotExistsAsync(
Duly noted. Thanks.

2024-08-22 15:00 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +        public virtual Task<bool> IsSubsetAsync(
IMO it would be easier to find this API (and similar for feed range in the future) if we would prefix them with FeedRange. So, FeedRangeIsSubsetAsync or FeedRangeIsPartOfAsync

2024-08-22 15:02 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            if (parentFeedRange is not FeedRangeInternal parentFeedRangeInternal)
You can convert and FeedRange into a FeedRangeINternal by using toString/fromString? - also the typeof belo uses the wrong type in case we would want to restrict to FeedRangeINternal

2024-08-22 15:03 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            using (ITrace trace = Tracing.Trace.GetRootTrace("ContainerCore FeedRange IsSubset Async", TraceComponent.Unknown, Tracing.TraceLevel.Info))
What about retry policies - getFeedRanges also hit an issue where Matias had to applya change to avoid DocumentClientException from leaking out - is the same relevant here?

2024-08-22 15:11 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            return feedRange is FeedRangePartitionKey
That logic I think is broken. There is nothing preventing FeedRangeEpk today to have minInclusive false etc. - This needs to work for all flavors of ranges. This is where the relevant code lives in Java - basically every FeedRangeINternal implementation has a way to return a normalizedRange (minIncluded == true, maxIncluded == false) that way you can simplify processing ranges afterards - https://github.com/Azure/azure-sdk-for-java/blob/db5dea70e5539dc129f957e83f93e1df7d9d7026/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/feedranges/FeedRangeInternal.java#L80-L149

2024-08-22 15:12 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
> +                    parentFeedRange: new FeedRangeEpk(new Documents.Routing.Range<string>(parentMin, parentMax, true, false)),
you are missing tests with minIncluded being false for example - the full matrix would need to work (I am no fan that we ever opened these many possibilities in the first place - but it is what it is )

2024-08-22 15:20 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +        public virtual Task<bool> IsSubsetAsync(
I can agree.

2024-08-22 15:22 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            if (parentFeedRange is not FeedRangeInternal parentFeedRangeInternal)
@FabianMeiswinkel  This is done because users can mock FeedRange so wanted to make sure that it is valid. I have unit test to support this.

2024-08-22 15:25 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            using (ITrace trace = Tracing.Trace.GetRootTrace("ContainerCore FeedRange IsSubset Async", TraceComponent.Unknown, Tracing.TraceLevel.Info))
I believe you are referring to this

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/a1144f4f08033fe9c98bbaf55f1162430bf53e9f/Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs#L273C13-L323C14

If, so, sure, I can try catch and throw CosmosExceptionFactory.Create(dce, trace);

2024-08-22 15:26 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            return feedRange is FeedRangePartitionKey
@FabianMeiswinkel is `minInclusive=false` used in our scenarios anywhere? 
Just curious to know, for completeness agree to cover it.

2024-08-22 15:26 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            using (ITrace trace = Tracing.Trace.GetRootTrace("ContainerCore FeedRange IsSubset Async", TraceComponent.Unknown, Tracing.TraceLevel.Info))
Great point

2024-08-22 15:28 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            return feedRange is FeedRangePartitionKey
I don't think so - but given the SharedFiles/Range API allows it you never know when somebody has the idea to use it. And refactoring Range to disallow these combinations would be more work.

2024-08-22 15:30 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            return feedRange is FeedRangePartitionKey
@FabianMeiswinkel the idea was that if the Range<string>.Min and .Max are the same, then we wanted isMinInclusive and isMaxInclusive to both be true. FeedRangePartitionKey was the only case where it's Range<string>.Min and .Max would be the same, so it made sense to check for type FeedRangePartitionKey. But you believe that there are other types, so checking for Range<string>.Min and .Max equality is more effective and covers more cases?

2024-08-22 15:30 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            if (parentFeedRange is not FeedRangeInternal parentFeedRangeInternal)
Fabian are you referring to PartitionKeyInternal?

2024-08-22 15:32 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +        public virtual Task<bool> IsSubsetAsync(
Convention we followed so-far is `Is` as prefix, how about `IsFeedRangePartOfAsync`
Contains, Includes, subset are other synonyms.

2024-08-22 15:40 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            if (parentFeedRange is not FeedRangeInternal parentFeedRangeInternal)
NO i was referring to this - [https://github.com/Azure/azure-cosmos-dotnet-v3/blob/a1144f4f08033fe9c98bbaf55f1162430bf53e9f/Microsoft.Azure.Cosmos/src/FeedRange/FeedRanges/FeedRangeInternal.cs#L63-L79 and this ](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/a1144f4f08033fe9c98bbaf55f1162430bf53e9f/Microsoft.Azure.Cosmos/src/FeedRange/FeedRange.cs#L15-L35)

and https://github.com/Azure/azure-cosmos-dotnet-v3/blob/a1144f4f08033fe9c98bbaf55f1162430bf53e9f/Microsoft.Azure.Cosmos/src/FeedRange/FeedRanges/FeedRangeInternal.cs#L63-L78

As long as FeedRangeInternal.TryParse succeeds to parse parentFeedRange and childFeedRange.ToJsonString we are good - of course if they are of a FeedRangeINternal instance you can cast directly - that way the contract is clear - and you can simply report the json representation that can't be converted into a FeedRangeINternal.

2024-09-06 21:14 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +        public virtual Task<bool> IsSubsetAsync(
+1 on Kiran's proposal - i like IsFeedRangePartOfAsync

2024-09-06 22:00 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            return feedRange is FeedRangePartitionKey
@FabianMeiswinkel I am back on this. Can you confirm my last statement? Should I check if min and max are same, or is FeedRangePartitionKey type check sufficient? If min and max same check is necessary, can you clarify the scenarios?

2024-09-06 22:01 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
> +                    parentFeedRange: new FeedRangeEpk(new Documents.Routing.Range<string>(parentMin, parentMax, true, false)),
@FabianMeiswinkel  Will address this when this conversation is clarified. https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4566#discussion_r1747759979

2024-09-06 22:19 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                    _ = FeedRangeInternal.TryParse(parentFeedRange?.ToJsonString(), out FeedRangeInternal parentFeedRangeInternal);
Parse failures need to be errored out.

2024-09-06 22:24 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            Documents.Routing.Range<string> range1,
```suggestion
            Documents.Routing.Range<string> parentRange,

```

2024-09-06 22:25 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            Documents.Routing.Range<string> range2)
```suggestion
            Documents.Routing.Range<string> childRange)

```

2024-09-06 22:27 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                && (range1.Max == range2.Max || range1.Contains(range2.Max));
`range1.Max == range2.Max` only when maxInclusive is `False`.

2024-09-06 22:40 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                ? Documents.Routing.Range<string>.GetPointRange(ranges.Min(range => range.Min))
For single EPK value, a single Range is expected as outcome, no conversion is needed. 

So in-case of single range we can just return it. 
And try to merge only when there are more than one.

2024-09-06 22:42 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                    isMinInclusive: true,
All returned ranges are expected to have consistent 'minInclusive' and 'maxInclusive', the same combination can be used here instead of hardcoding (guess this is what Fabian is mentioning above)

2024-09-06 22:43 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                ? Documents.Routing.Range<string>.GetPointRange(ranges.Min(range => range.Min))
Also it void dependency on type check `FeedRangePartitionKey` and makes it generic.

2024-09-06 22:50 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            return feedRange is FeedRangePartitionKey
The latter is probably less work - only needs changes here to be more robust right now - the former IMO would result in long-term better code maintainability - but it is mor churn and higher risk - so, for this PR my recommendation would be to just make this method robust against all kind of ranges

2024-09-06 22:51 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            return feedRange is FeedRangePartitionKey
The FeedRangePartitionKey check MO is not acceptable because nobody knows when someone introduces a new FeedRange - all internal - using weird range configs. Not super likely - but possible and no-one would remember this code place also needing changes.

2024-09-06 22:54 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                : new Documents.Routing.Range<string>(
Range type already has MinComparer and MaxComparer defined and should be used for cosistency. 

Possible usecase here is to sort the ranges using MinComparer and choose first and last entries. 
ref: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/0fdb5e4222fad67ca6206b820d0d19e89fe4832c/Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPartitionProvider.cs#L173

2024-09-06 23:06 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +    using Microsoft.Azure.Cosmos.Serialization.HybridRow.Schemas;
Unused

2024-09-06 23:06 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +    using Microsoft.Azure.Documents.Routing;
Not required, Range types are explicitly qualified.

2024-09-07 15:21 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                    _ = FeedRangeInternal.TryParse(parentFeedRange?.ToJsonString(), out FeedRangeInternal parentFeedRangeInternal);
I was actually going to block myself on this one. Will work on this today.

2024-09-07 15:21 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            Documents.Routing.Range<string> range1,
nit IMHO but sure.

2024-09-07 15:22 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                && (range1.Max == range2.Max || range1.Contains(range2.Max));
explain why. we went over this, so for my education, explain why this is important.

2024-09-07 15:24 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +    using Microsoft.Azure.Documents.Routing;
Not everywhere. There are cases where it is necessary. In this case, why is it not?

2024-09-07 15:26 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            return feedRange is FeedRangePartitionKey
ok. let me review your suggestions and give my assessment. Thanks @FabianMeiswinkel

2024-09-07 15:29 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                ? Documents.Routing.Range<string>.GetPointRange(ranges.Min(range => range.Min))
i think the other 50% of conversations address this so I will resolve this conversation. Feel free to reopen if "I" lack clarify.

2024-09-09 20:31 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +    using Microsoft.Azure.Documents.Routing;
if it used then no issue. Apologies.

2024-09-09 23:36 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                && (range1.Max == range2.Max || range1.Contains(range2.Max));
Assuming that both ranges have the same minInclusive and maxExclusive values, then we are good. 
In our scenario that's the case, we can ignore this part.

2024-09-10 13:14 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            Documents.Routing.Range<string> range1,
done.

2024-09-10 13:15 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +    using Microsoft.Azure.Cosmos.Serialization.HybridRow.Schemas;
Done.

2024-09-10 16:37 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            return feedRange is FeedRangePartitionKey
Done. Please review.

2024-09-10 16:38 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                    isMinInclusive: true,
Done. Please review.

2024-09-10 16:38 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                : new Documents.Routing.Range<string>(
Done. Please review.

2024-09-10 17:33 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            List<Documents.Routing.Range<string>> normalizedRanges = ranges
What's the purpose of normalization?

Reducing one value: With different hash value versions it non-trivial (V1, V2, Sub-Partition), Lets please not persue this path unless its the only option.

2024-09-10 17:35 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            string max = normalizedRanges.First().Max;
It avoids sorting on Max which is unnecessary

2024-09-10 17:36 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            // NOTE(philipthomas-MSFT): If only one rangee exists, return it immediately.
Curious: alias in comments, can you please share context (it's not the pattern in the code)

2024-09-10 17:39 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            string max = normalizedRanges.First().Max;
hmm. Really? Can we count on that? sorting on Min alone and expecting Last Max will always be the largest seems risky.

2024-09-10 17:41 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            List<Documents.Routing.Range<string>> normalizedRanges = ranges
Fabian made a case that this is needed, unless I am missing something here. Without it, can we always count on IsMinInclusive to be true?

2024-09-10 17:44 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            // NOTE(philipthomas-MSFT): If only one rangee exists, return it immediately.
I work on too many repos LOL. It is a logic app requirement and when I work on any of these repos in parallel, this tends to happen. I can remove it if it's a problem.

2024-09-10 17:44 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            List<Documents.Routing.Range<string>> normalizedRanges = ranges
We are just flowing the incoming ranges minIncusives and maxExclusives.
There are no assumptions now about what the values of minInclusive or maxExclusive right?

2024-09-10 17:46 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            string max = normalizedRanges.First().Max;
It is by definition otherwise the whole Range(min, max) abstraction is broken.

2024-09-10 17:46 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            // NOTE(philipthomas-MSFT): If only one rangee exists, return it immediately.
removed.

2024-09-10 17:46 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            // NOTE(philipthomas-MSFT): If only one rangee exists, return it immediately.
At-least that's not the pattern in our repos, consistency is preferred.

2024-09-10 17:46 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            string max = normalizedRanges.First().Max;
changed.

2024-09-10 17:47 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            List<Documents.Routing.Range<string>> normalizedRanges = ranges
will wait for @FabianMeiswinkel to weigh in, but not sure I like flip flopping.

2024-09-11 19:26 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        {
minInclusive = false: throw NotImplemented

Then fool proof this method to cover for, maxExclusive = true/false combinations.

2024-09-12 13:42 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        {
throwing this in FeedRangeEpk instead.

2024-09-12 16:12 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                && (parentRange.Max == childRange.Max || parentRange.Contains(childRange.Max));
Assuming maxEpk is same for parent and child for both then few combinations are still incorrectly returning subset right?

maxExclusive has four combinations 
True, True
True, False, 
False, False (Invalid but returns true)
False, True (Invalid but returns true)

2024-09-12 16:14 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
> +                            parentFeedRange: new FeedRangeEpk(new Documents.Routing.Range<string>("", "3FFFFFFFFFFFFFFF", false, true)),
This and below tests are two combinations, Paramaterized tests will help avoid code duplication.

2024-09-12 16:19 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        {
Let's please add unit test coverage for this helper method directly (marking it internal) as discussed yesterday.

2024-09-12 17:26 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                && (parentRange.Max == childRange.Max || parentRange.Contains(childRange.Max));
For **False, False (Invalid but returns true)** and **False, True (Invalid but returns true)** we said a False isMinInclusive should throw the exception, but you say here (Invalid but returns true), but it can't throw the exception and return true, so what is the expected behavior here?

**True, False** is already tested in [GivenParentAndChildFeedRangesTrueIsMinInclusiveIsFeedRangePartOfAsyncTestAsync](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/d5a999b2e85658717d26487dc5a9f96236b84fd0/Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs#L1906), and sure I can add **True, True** by adding that to the data row since this seems to be happy path.

So, it really goes back to **False, False (Invalid but returns true)** and **False, True (Invalid but returns true)**. Exception or return true?

2024-09-12 17:27 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
> +                            parentFeedRange: new FeedRangeEpk(new Documents.Routing.Range<string>("", "3FFFFFFFFFFFFFFF", false, true)),
fixing when https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4566#discussion_r1757289156 is resolved

2024-09-12 17:31 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                && (parentRange.Max == childRange.Max || parentRange.Contains(childRange.Max));
Both the combinations are for maxExclusive only but for (parent, child)
The way to read it is (parentMaxInclusive, childMaxInclusive)

2024-09-12 20:53 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                && (parentRange.Max == childRange.Max || parentRange.Contains(childRange.Max));
done.

2024-09-12 20:57 UTC, NaluTripician approved these changes
Left one comment regarding the testing. Other than that LGTM

2024-09-12 20:57 UTC, NaluTripician commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
> +        [DataRow("", "FFFFFFFFFFFFFFFF", true)] // Full range.
nit: for the` DataRow`s do you want to add a the `DisplayName` in place of the comment. Could be useful to have the scenario displayed if anything breaks in the future.

2024-09-12 21:14 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        {
IsSubset tests done.

2024-09-12 21:28 UTC, NaluTripician submitted a review, later dismissed

2024-09-13 12:08 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            ranges.Sort(Documents.Routing.Range<string>.MinComparer.Instance);
Lets please also assert assumption that all minInclusive and maxInclusive are same if-not error out.

2024-09-13 12:17 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
> +            Documents.Routing.Range<string> parentRange = new Documents.Routing.Range<string>(parentMinimum, parentMaximum, true, true);
Please include test coverage for maxInclusive combinations

2024-09-13 12:21 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
> +                ContainerResponse containerResponse = await this.cosmosDatabase.CreateContainerIfNotExistsAsync(
Every combination is creating a new container, these tests will take longer to run. 
For functional part we can just create a container once and use it. 

We can follow-up on this after this PR.

2024-09-13 12:25 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
> +            yield return new object[] { "", "3FFFFFFFFFFFFFFF", false, "", "FFFFFFFFFFFFFFFF", false, true }; // child is subset of the parent
Please correct me if I understood it in-correctly. 
minInclusive: `false` will result in FeedRangeEpk creation throwing ArgumentException right?

2024-09-13 12:30 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
> +            yield return new object[] { "", "3FFFFFFFFFFFFFFF", true, "3FFFFFFFFFFFFFFF", "7FFFFFFFFFFFFFFF", true, false }; // child is not a subset of parent
Thoughts on how we can make these tests mangeable forward? 
These combinations and replicating values consistency will be a challenge.

Can be followed-up after this PR

2024-09-13 12:32 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
> +            yield return new object[] { "", "3333333333333333", true, "3FFFFFFFFFFFFFFF", "7FFFFFFFFFFFFFFF", true, false }; // child is not a subset of parent
Above two are of same exclusive sets right, are both combinations needed?

2024-09-13 12:55 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                && (parentRange.Max == childRange.Max || parentRange.Contains(childRange.Max));
> False, False (Invalid but returns true)
Actually this combination is Valid.

False, True is still invalid and should return false.

2024-09-14 12:55 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                && (parentRange.Max == childRange.Max || parentRange.Contains(childRange.Max));
what is the logic behind this? or am I supposed to add the logic to look for that combination and fail it? By your own writing above, you say it should return true. Are we still not clear?

maxExclusive has four combinations
True, True
True, False,
False, False (Invalid but returns true)
**False, True (Invalid but returns true)**

2024-09-14 12:59 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            ranges.Sort(Documents.Routing.Range<string>.MinComparer.Instance);
Clarify. Because your statement is ambiguous. Should isMinInclusive and isMaxInclusive be the same or should all the ranges in the list each have the same isMinInclusive and isMaxInclusive. The latter makes sense. The former does not.

2024-09-14 13:04 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
> +                ContainerResponse containerResponse = await this.cosmosDatabase.CreateContainerIfNotExistsAsync(
Sure Kirin. But we will speak offline on this.

2024-09-14 13:06 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
> +            yield return new object[] { "", "3FFFFFFFFFFFFFFF", true, "3FFFFFFFFFFFFFFF", "7FFFFFFFFFFFFFFF", true, false }; // child is not a subset of parent
Let's follow up. I see an opportunity to bring others into the conversation for learning purposes. But in short, DynamicData vs DataRow is the way to make it more manageable. Add creating test helpers to hold this data does not work with DynamicData.

2024-09-14 13:07 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
> +            yield return new object[] { "", "3333333333333333", true, "3FFFFFFFFFFFFFFF", "7FFFFFFFFFFFFFFF", true, false }; // child is not a subset of parent
write the exact line in comment, because I see nothing that is the same

2024-09-14 13:07 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
> +            Documents.Routing.Range<string> parentRange = new Documents.Routing.Range<string>(parentMinimum, parentMaximum, true, true);
responded to that already.

2024-09-15 12:50 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
> +                ContainerResponse containerResponse = await this.cosmosDatabase.CreateContainerIfNotExistsAsync(
Also, every test in the class is creating new containers. I am just following consistency.

2024-09-15 13:16 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            ranges.Sort(Documents.Routing.Range<string>.MinComparer.Instance);
EnsureConsistentInclusivity method added with tests.

2024-09-15 13:17 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        /// <summary>
Discussion requested @kirankumarkolli

2024-09-15 13:17 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                && (parentRange.Max == childRange.Max || parentRange.Contains(childRange.Max));
Discussion requested @kirankumarkolli

2024-09-15 13:17 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
> +            Documents.Routing.Range<string> parentRange = new Documents.Routing.Range<string>(parentMinimum, parentMaximum, true, true);
Discussion requested @kirankumarkolli

2024-09-15 13:17 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
> +                ContainerResponse containerResponse = await this.cosmosDatabase.CreateContainerIfNotExistsAsync(
Discussion requested @kirankumarkolli

2024-09-15 13:17 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
> +            yield return new object[] { "", "3FFFFFFFFFFFFFFF", true, "3FFFFFFFFFFFFFFF", "7FFFFFFFFFFFFFFF", true, false }; // child is not a subset of parent
Discussion requested @kirankumarkolli

2024-09-15 13:17 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
> +            yield return new object[] { "", "3333333333333333", true, "3FFFFFFFFFFFFFFF", "7FFFFFFFFFFFFFFF", true, false }; // child is not a subset of parent
Discussion requested @kirankumarkolli

2024-09-16 09:15 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                    if (!FeedRangeInternal.TryParse(parentFeedRange.ToJsonString(), out FeedRangeInternal parentFeedRangeInternal))
This is only necessary for any FeedRange which cannotbe casted into feedRangeInternal - it should not happen all the time - after all it si a pretty heavy perf overhead (admittedly not on the hot path).

2024-09-16 09:17 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        /// <summary>
I think #preview should only gate public vs. internal. We would always want this code to ship (and test) - but only make it public for now in preview package.

2024-09-16 09:18 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        /// <summary>
@philipthomas-MSFT you are missing a retry policy here - the implementation uses GetCachedRidAsync - which could be stale (after container delete and recreate with same container name) - there is a retry policy that handles this and would retry after force updating the collection cache - please check other usages of GetCachedRidAsycn and you should find the retry policy.

2024-09-16 09:25 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                isMinInclusive: firstRange.IsMinInclusive,
This method would also need to check isMinInclusivea nd IsMaxINclusive. You could have two ranges AA-BB (MaxInclsuive) and AA-BB (MaxExclusive) where right now the result would randomly fail. I would argue that the implementation is pretty inefficient - usual sort operations will have complxity of n * Log(n) - while finding the min and max range can always be done with a single iteration over the list.

2024-09-16 09:26 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            bool areAllMaxsSame = ranges.All(range => range.IsMaxInclusive == firstRange.IsMaxInclusive);
Inefficient - merge both checks into one to avoid iterating over the list twice.

2024-09-16 09:29 UTC, FabianMeiswinkel requested changes
Left few comments

2024-09-16 15:00 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                isMinInclusive: firstRange.IsMinInclusive,
@FabianMeiswinkel you tell me. I feel like I am reacting to whatever you or @kirankumarkolli are saying and I am trying my best to understand the why behind it. There are many conversations going on with this PR, not just this one conversation, where things are not clear. Like another conversation where I was asked to use TryParse and FromJsonString/ToJsonString and not just look to see if the FeedRange can be cast to FeedRangeInternal, the way it was before. Now you are saying I should.

https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4566#discussion_r1727240699
and
https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4566#discussion_r1760796715

2024-09-16 17:08 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                isMinInclusive: firstRange.IsMinInclusive,
And @kirankumarkolli you give a thumbs up to what @FabianMeiswinkel says, but I still seek clarity. If you have something to add to help remove ambiguity, please, I would appreciate your input.

So we are talking about https://github.com/Azure/azure-cosmos-dotnet-v3/blob/c6bff5bbbc9c8f5bddcb47980a055947fa7b7c31/Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs#L1374C30-L1374C57

2024-09-16 19:01 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
> +            Documents.Routing.Range<string> parentRange = new Documents.Routing.Range<string>(parentMinimum, parentMaximum, true, true);
added more scenarios. updated DisplayName of DataRow to show IsMinInclusive and IsMaxInclusive combinations. Also added to description of documentation.

2024-09-17 14:21 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
> +            yield return new object[] { "", "3FFFFFFFFFFFFFFF", true, "3FFFFFFFFFFFFFFF", "7FFFFFFFFFFFFFFF", true, false }; // child is not a subset of parent
Added comments for now, but thinking of a better solution that I will create a PR on after this is completed.

2024-09-18 15:33 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/IsFeedRangePartOfAsyncTests.cs
> +        public void GivenParentRangeWhenChildRangeComparedThenValidateIfSubset(
Please review @kirankumarkolli

2024-09-18 17:19 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +        public abstract Task<bool> IsFeedRangePartOfAsync(
To make it non-breaking in-nature, one possibility is to mark it virtual with default NotImplemented

@FabianMeiswinkel thoughts?

2024-09-18 17:25 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos.Encryption.Custom/src/EncryptionContainer.cs
> +            throw new NotImplementedException();
done

2024-09-18 17:27 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +        public abstract Task<bool> IsFeedRangePartOfAsync(
I went down that road before which means I had to place code blocks in PREVIEW tags. This now follows what we have been doing consistently with other implementations added to Container, like the more recent GetChangeFeedProcessorBuilderWithAllVersionsAndDeletes. Let's not block with this.

2024-09-18 17:30 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +        public abstract Task<bool> IsFeedRangePartOfAsync(
We absolutely have to block on it. Adding new abstract members to a non-final class is a breaking change. It slipped through the cracks before, but we can and should learn from our mistakes.

2024-09-18 17:37 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        {
```C#
        [TestMethod]
        [DataRow(true, true, true)]
        [DataRow(true, false, true)]
        [DataRow(false, false, true)]
        [DataRow(false, true, false)]
        public void TestSubRange(bool parentMaxInclusive, bool childMaxInclusive, bool expectation)
        {
            Documents.Routing.Range<string> parentRange = new Documents.Routing.Range<string>("", "FF", true, parentMaxInclusive);
            Documents.Routing.Range<string> childRange = new Documents.Routing.Range<string>("", "FF", true, childMaxInclusive);

            bool subsetResult = ContainerCore.IsSubset(parentRange, childRange);
            Assert.IsTrue((subsetResult && expectation) || (!subsetResult && !expectation));
        }
```

2024-09-18 17:38 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs
> -
Revert this file (unrelated right)

2024-09-18 17:45 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/IsFeedRangePartOfAsyncTests.cs
> +            return (min, maxValue); // max is inclusive
Our goal is to test without normalizing the ranges.

2024-09-18 17:47 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        {
ref: https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4566/files?diff=unified&w=0#r1765469550

2024-09-18 17:50 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +        public abstract Task<bool> IsFeedRangePartOfAsync(
Ok. Guys. Like I said before, I went down that path of virtual but needed to do extra to get that to work. So if I go back, please, we can discuss, but don't suggest to me to change it.

2024-09-18 17:52 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs
> -
done

2024-09-18 17:53 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        {
Why are you referencing TestSubRange?

2024-09-18 17:54 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/IsFeedRangePartOfAsyncTests.cs
> +            return (min, maxValue); // max is inclusive
What are you talking about? I am not normalizing ranges.

2024-09-18 18:29 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/IsFeedRangePartOfAsyncTests.cs
> +            return (min, maxValue); // max is inclusive
Please check ExclusiveMaxRangeStrategy  which is normalizing values.

2024-09-18 18:30 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/IsFeedRangePartOfAsyncTests.cs
> +            return (min, maxValue); // max is inclusive
Our goal is to test minInclusive=True, maxInclusive={True/False} combinations.

2024-09-18 18:35 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        {
It's the test case of the IsSubset.

2024-09-18 19:46 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        {
Please review the changes. Thanks.

2024-09-18 19:47 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/IsFeedRangePartOfAsyncTests.cs
> +            return (min, maxValue); // max is inclusive
Please review the changes. Thanks.

2024-09-18 20:25 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +        public virtual Task<bool> IsFeedRangePartOfAsync(
Will the new API be GA or need to start in preview?

2024-09-18 20:29 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/IsFeedRangePartOfAsyncTests.cs
> +        [DataRow(false, true, "B", "Z", true, true, "A", "Z", false, DisplayName = "Given parent range excludes its min and starts after the child range, but both end inclusively, child is not a subs
minInclusive=false is not a valid combination and not supported.
It will hep reduce the text matrix.

2024-09-18 20:32 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        {
Please note that the test case used the same EPK values to cover the corner cases. 
This is still a gap in tests.

Can we please add above test?

2024-09-18 21:17 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        {
They are part of this test GivenParentRangeWhenChildRangeComparedThenValidateIfSubset. Again, TestSubRange is not a test. Do we need to have another call?

2024-09-18 21:22 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/IsFeedRangePartOfAsyncTests.cs
> +        [DataRow(false, true, "B", "Z", true, true, "A", "Z", false, DisplayName = "Given parent range excludes its min and starts after the child range, but both end inclusively, child is not a subs
and so, if I remove any minInclusive = false, we are left with these 4 combinations.

```cs
[DataRow(true, true, "A", "Z", true, true, "A", "Z", true, DisplayName = "Given both parent and child ranges are fully inclusive and equal, child is a subset")]
[DataRow(true, true, "A", "Z", true, false, "A", "Y", true, DisplayName = "Given parent range is fully inclusive and child range has an exclusive max, child is a subset")]
[DataRow(true, false, "A", "Y", true, true, "A", "Z", false, DisplayName = "Given parent range has an exclusive max but child range exceeds the parent’s max with an inclusive bound, child is not a subset")]
[DataRow(true, false, "A", "Y", true, false, "A", "Y", true, DisplayName = "Given both parent and child ranges share an inclusive min and exclusive max, child is a subset")]


//[DataRow(true, true, "A", "Z", false, true, "B", "Z", true, DisplayName = "Given parent range is fully inclusive and child range starts exclusively after parent, but both end inclusively, child is a subset")]
//[DataRow(true, true, "A", "Z", false, false, "B", "Y", true, DisplayName = "Given parent range is fully inclusive and child range is fully exclusive within the parent, child is a subset")]
//[DataRow(true, false, "A", "Y", false, true, "B", "Z", false, DisplayName = "Given child range exceeds the parent’s exclusive max with an inclusive max, child is not a subset")]
//[DataRow(true, false, "A", "Y", false, false, "B", "Y", true, DisplayName = "Given parent range is partially inclusive and child is fully exclusive but within the parent’s bounds, child is a subset")]
//[DataRow(false, true, "B", "Z", true, true, "A", "Z", false, DisplayName = "Given parent range excludes its min and starts after the child range, but both end inclusively, child is not a subset")]
//[DataRow(false, true, "B", "Z", true, false, "A", "Y", false, DisplayName = "Given parent range excludes its min and child range is less than parent’s exclusive min, child is not a subset")]
//[DataRow(false, true, "B", "Z", false, true, "B", "Z", false, DisplayName = "Given both parent and child ranges are exclusive at the start and inclusive at the end with the same values, child is not a subset")]
//[DataRow(false, true, "B", "Z", false, false, "B", "Y", false, DisplayName = "Given parent range excludes its min and includes its max, and child is fully exclusive within the parent’s bounds, child is not a subset")]
//[DataRow(false, false, "B", "Y", true, true, "A", "Z", false, DisplayName = "Given parent range excludes both min and max, and child range is larger with inclusive bounds, child is not a subset")]
//[DataRow(false, false, "B", "Y", true, false, "A", "Y", false, DisplayName = "Given parent range excludes both min and max, and child range is larger with an inclusive min, child is not a subset")]
//[DataRow(false, false, "B", "Y", false, true, "B", "Z", false, DisplayName = "Given parent range excludes both bounds and child range exceeds parent’s max, child is not a subset")]
//[DataRow(false, false, "B", "Y", false, false, "B", "Y", false, DisplayName = "Given both parent and child ranges are fully exclusive and equal, child is not a subset")]
```

I am fine with that.

2024-09-18 21:30 UTC, philipthomas-MSFT reviewed
running UpdateContracts so blocking myself

2024-09-18 21:35 UTC, philipthomas-MSFT commented
> running UpdateContracts so blocking myself

Done.

2024-09-18 21:41 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        {
What that test does is part of GivenParentRangeWhenChildRangeComparedThenValidateIfSubset

2024-09-18 21:50 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        {
adding this so you can see.

[DataRow(true, <b>TRUE</b>, "A", "Z", true, <b>TRUE</b>, "A", "Z", true, DisplayName = "Given both parent and child ranges are fully inclusive and equal, child is a subset")]
[DataRow(true, <b>TRUE</b>, "A", "Z", true, <b>FALSE</b>, "A", "Y", true, DisplayName = "Given parent range is fully inclusive and child range has an exclusive max, child is a subset")]
[DataRow(true, <b>FALSE</b>, "A", "Y", true, <b>TRUE</b>, "A", "Z", false, DisplayName = "Given parent range has an exclusive max but child range exceeds the parent’s max with an inclusive bound, child is not a subset")]
[DataRow(true, <b>FALSE</b>, "A", "Y", true, <b>FALSE</b>, "A", "Y", true, DisplayName = "Given both parent and child ranges share an inclusive min and exclusive max, child is a subset")]

2024-09-18 22:28 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        {
As I called out its just not even the EPK values also make difference. 

In these combinations the EPK values are different, in the suggested test case the EPK values are same.

2024-09-18 22:39 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        {
In 

[DataRow(true, TRUE, "A", "Z", true, TRUE, "A", "Z", true, DisplayName = "Given both parent and child ranges are fully inclusive and equal, child is a subset")]

and

[DataRow(true, FALSE, "A", "Y", true, FALSE, "A", "Y", true, DisplayName = "Given both parent and child ranges share an inclusive min and exclusive max, child is a subset")]

they are the same, just like the other test. Still not clear as to what you think is not covered here.

2024-09-18 22:44 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        {
now, I do see room for perhaps adding

[DataRow(true, true, "A", "A", true, true, "A", "A", true, DisplayName = "Given both parent and child ranges are fully inclusive and equal, and min and max range is the same, child is a subset")]

where is add in what a FeedRange could look like for PartitionKey where min and max is the same, making isMinInclusive and isMaxInclusive the same.

2024-09-18 22:46 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        {
and perhaps this also

[DataRow(true, true, "A", "A", true, true, "B", "B", false)]

2024-09-19 03:24 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        {
Pivoting onto the test to point an bug in the code. 
Please use the test sample shared to root cause the bug.

2024-09-19 06:40 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        {
I think the problem is the data for the test on the old test. Not the implementation of **IsSub**. What you are seeing in the old test is a scenario that should not exist. Now, I will concede obviously, if I am learning something and we are gaining clarity.

This is the scenario that fails on the old test.

```cs
[DataRow(false, true, false)]
public void TestSubRange(bool parentMaxInclusive, bool childMaxInclusive, bool expectation)
```

with both parent and child min and max set to "" and "FF", respectively.

```cs
Documents.Routing.Range<string> parentRange = new Documents.Routing.Range<string>("", "FF", true, parentMaxInclusive);
Documents.Routing.Range<string> childRange = new Documents.Routing.Range<string>("", "FF", true, childMaxInclusive);
```

translation below

```txt
Parent
	min: ""
	max: "FF"
	isMinInclusive: true
	isMaxInclusive: false
	
Child
	min: ""
	max: "FF"
	isMinclusive: true
	isMaxInclusive: true
```

if the Parent **FeedRange** is set to _isMaxInclusive_ = false "MaxExclusive", then it's value of **max** can't be "FF", since that basically means it is not "MaxExclusive", especially if the Child **FeedRange** is set _isMaxInclusive_ = true with a **max** value set to "FF".

That is why the new test is more data accurate.

```cs
[DataRow(true, false, "", "1FF", true, true, "", "FF", false)]
GivenParentRangeWhenChildRangeComparedThenValidateIfSubset(
            bool parentIsMinInclusive,
            bool parentIsMaxInclusive,
            string parentMinValue,
            string parentMaxValue,
            bool childIsMinInclusive,
            bool childIsMaxInclusive,
            string childMinValue,
            string childMaxValue,
            bool expectedIsSubset)
```

translation below

```txt
Parent
	min: ""
	max: "1FF"
	isMinInclusive: true
	isMaxInclusive: false
	
Child
	min: ""
	max: "FF"
	isMinclusive: true
	isMaxInclusive: true
```

Here, it is more accurate. A "MaxExclusive" Parent will not have a **max** of "FF", because if it was "FF", then that is not "MaxExclusive", especially if we accept, for this test, that Child is _isMaxInclusive_ of "FF". So that is why Parent **max** is "1FF", because it is "MaxExclusive", and Child **max** is "FF" because it is "MaxInclusive".

I am including two new DataRow scenarios so that you can see this against the new test so we can stop looking at the old one.

```cs
[DataRow(true, false, "", "1FF", true, true, "", "FF", false)] // This is correct scenario
[DataRow(true, false, "", "FF", true, true, "", "FF", true)] // This should never happen
```

2024-09-19 12:43 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +#if PREVIEW
Clarification: Why different convention? 
Existing pattern is either PREVIEW or no API (not even internal right)? 

Of-course it's a virtual with default implementation, may be non-breaking.

2024-09-19 13:06 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        {
Yes, please. I am free. Just ping me.

2024-09-19 13:10 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +#if PREVIEW
wrapping this in a PREVIEW pattern is not enough because other things that follow public/internal pattern will not have access to it, specifically, ContainerCore.Items.cs which actually has the implementation. If I wrap implementation in ContainerCore.Item.cs into PREVIEW, then so the tests will have to be done the same way. This is the way I had it before, but you had issue with that. I go to this way and there is still issues.

2024-09-19 15:20 UTC, philipthomas-MSFT reviewed
blocking myself as I diagram Container structure and best place for IsFeedRangePartOfAsync

2024-09-19 15:59 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +#if PREVIEW
created diagrams and trying different alternatives to this.

2024-09-19 16:31 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +#if PREVIEW
take another look.

2024-09-19 19:02 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        {
Notes: 

True, false,  0, 100  => [0,  99]
True, true,   0,  99  => [0,  99]
true, true,   0, 100  => [0, 100]
true, false,  0, 101  => [0, 100]


P: True, false [MinEPK, MaxEPK)
C: True, True  [MinEPK, MaxEPK]
IsSubset: False


True, false,  0, 100  => [0,  99]
true, true,   0, 100  => [0, 100]
Expectation: False


True, false,  0, 101  => [0, 100]
true, true,   0, 100  => [0, 100]
Expectation: True



True, false, "", "FF", 
true, true,  "", "FF", 

true, false, "", "1FF", 
true, true, "", "FF"



EPK Values: 
- SDK don't control
- Either backend feeds
- OR user input (which can be any combination)

Our goal: Is to be functionally complete cover all possibilities

2024-09-19 19:03 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        {
Range assumptions: 
- minInclusive: True
- minEpk <= maxEpk

2024-09-20 11:43 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInternal.cs
> +        public abstract Task<bool> IsFeedRangePartOfAsync(
blocking myself as I move some things around.

2024-09-20 18:07 UTC, NaluTripician approved these changes

2024-09-20 18:20 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        {
Above unit tests still failing for (false, false) combination

2024-09-20 18:42 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        {
This is the (parentMaxIncusive=false, childMaxIncusive=false) combination. All my tests are green. If I am still missing something, please be specific.

```
[DataRow(true, FALSE, "A", "Y", true, FALSE, "A", "Y", false, DisplayName = "Given both parent and child ranges share an inclusive min and exclusive max, child is not a subset")]
```

2024-09-20 18:47 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +#if PREVIEW
the old version had whitespace. I simply removed it.

2024-09-20 20:55 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        {
It's the third data row combination which is failing. 
Let's please include below test case for validation.

```C#
        [TestMethod]
        [DataRow(true, true, true)]
        [DataRow(true, false, true)]
        [DataRow(false, false, true)]
        [DataRow(false, true, false)]
        public void TestSubRange(bool parentMaxInclusive, bool childMaxInclusive, bool expectation)
        {
            Documents.Routing.Range<string> parentRange = new Documents.Routing.Range<string>("", "FF", true, parentMaxInclusive);
            Documents.Routing.Range<string> childRange = new Documents.Routing.Range<string>("", "FF", true, childMaxInclusive);

            bool subsetResult = ContainerCore.IsSubset(parentRange, childRange);
            Assert.AreEqual(expectation, subsetResult);
        }
```

2024-09-21 04:52 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        {
ok. fixed and added more DataRows on the test.

2024-09-23 16:08 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +        /// - **Partition Key and Routing Map Setup**:
This will go into the public documentation. 

For public documentation we limit to the public contract and expectations. 
Implementation details can be moved inside implementation like ContainerCore?

2024-09-23 17:59 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInlineCore.cs
> +            return base.IsFeedRangePartOfAsync(
Needs to be wrapped through OperationHelperAsync as other method implementations

2024-09-23 18:42 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInlineCore.cs
> +            return base.IsFeedRangePartOfAsync(
Done

2024-09-23 18:45 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInlineCore.cs
> +                operationType: Documents.OperationType.ReadFeed,
Please add a code note that ReadFeed is overloaded here (not exact match)

2024-09-23 18:45 UTC, kirankumarkolli approved these changes

2024-09-23 18:53 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInlineCore.cs
> +                operationType: Documents.OperationType.ReadFeed,
done

2024-09-23 21:05 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        internal static bool IsSubset(
This logic seems similar to other places, like https://github.com/Azure/azure-cosmos-dotnet-v3/blob/2cc12dcfc07537b6f6716d33f57ab4cb1626c0a2/Microsoft.Azure.Cosmos/src/Routing/PartitionKeyHashRange.cs#L46, should this be reused instead?

2024-09-24 14:14 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/FeedRange/FeedRanges/FeedRangeEpk.cs
> +            if (!range.IsMinInclusive)
@ealsur This is `range.IsMinInclusive` check, not IsMaxInclusive.

2024-09-24 14:19 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                isMaxInclusive: firstRange.IsMaxInclusive);
@ealsur can you explain why?

2024-09-24 14:22 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            ranges.Sort(Documents.Routing.Range<string>.MinComparer.Instance);
@ealsur GetEffectiveRangesAsync does not sort.

2024-09-24 14:24 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            if (ranges.FirstOrDefault() is var firstRange)
@ealsur no, it should not be empty. is this `ranges.FirstOrDefault() is var firstRange` what is causing alarm for you?

2024-09-24 15:02 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        internal static bool IsSubset(
@ealsur Just so I am clear, is the proposal to convert these parent and child ranges, `Range<string>`, over to `PartitionKeyHashRange` and `PartitionKeyHash` just so that we can use _TryOverlappingRange_? If this is truly is doing 100% of what IsSubset is doing, then I would need to validate this, if this is something you strongly recommend.

2024-09-24 17:52 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            ranges.Sort(Documents.Routing.Range<string>.MinComparer.Instance);
GetEffectiveRanges are served through IRoutingMapProvider which does server results in order I think. 
@philipthomas-MSFT is that not the case?

2024-09-24 17:53 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                isMaxInclusive: firstRange.IsMaxInclusive);
All ranges (minInclude, maxInclusive) are pre-validated to be same. So first or last are fine.

2024-09-24 17:54 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            if (ranges.FirstOrDefault() is var firstRange)
First**OrDefault**() highlighted part is what Matias is referring to.

2024-09-24 18:15 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        internal static bool IsSubset(
Interesting, peeking into them few observations (Contains is the right mapping)
- Are only used in tests but in library (worth moving them to test projects)
- Composition is `PartitionKeyHash` which only has value but not Inclusive or not (assumptions that both are inclusive looking at Container implementation)

2024-09-24 18:15 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        internal static bool IsSubset(
Assuming above interpretation is right, my proposal is to move them to test project.

2024-09-24 18:34 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        internal static bool IsSubset(
Is it safe to say that since this is moving, there is no need to further explore whether this is something that could be used in place of the newly added _IsSub_?

2024-09-24 18:43 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            if (ranges.FirstOrDefault() is var firstRange)
changed.

2024-09-24 18:44 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            ranges.Sort(Documents.Routing.Range<string>.MinComparer.Instance);
nothing substantiates that sorting is ever happening. nor any tests exist to assert this. I will see if I can test this further if we feel this is worth the block.

2024-09-24 18:45 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                isMaxInclusive: firstRange.IsMaxInclusive);
resolving if the response is acceptable, or if we need to further investigate, I can.

2024-09-24 21:27 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            ranges.Sort(Documents.Routing.Range<string>.MinComparer.Instance);
PkRange cache order and then searches so result should be already ordered. 
For now I am fine with another sort (most of the times it should match 1 entry so its no-op.

2024-09-25 09:52 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            ranges.Sort(Documents.Routing.Range<string>.MinComparer.Instance);
Before I resolve this. https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4566#discussion_r1723670832

2024-09-25 10:01 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        internal static bool IsSubset(
Going to resolve this and push to get approvals today. We need to deliver this so unless something is critical, let's table these discussions and press forward to a delivery.

2024-09-25 14:05 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/FeedRange/FeedRanges/FeedRangeEpk.cs
> +            if (!range.IsMinInclusive)
Right. I'm sorry for not being clear with the question. This checks validates if MinInclusive has a value that we don't expect (false) but there is no validation for MaxExclusive. Which led me to believe both values (true and false) are valid. Hence my question, when do we expect MaxExclusive to be true, otherwise should we validate it?

2024-09-25 14:27 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/FeedRange/FeedRanges/FeedRangeEpk.cs
> +            if (!range.IsMinInclusive)
@ealsur Yes, `IsMaxInclusive of False` (another way of saying MaxExclusive) can exist, and in most cases it is defaulted to False.

Just a quick search of IsMaxInclusive being false.

https://github.com/search?q=repo%3AAzure%2Fazure-cosmos-dotnet-v3%20IsMaxInclusive&type=code

2024-09-25 14:36 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        internal static bool IsSubset(
My point is merely, you want to avoid introducing a new implementation of something that might already exist, risking having a bug on the logic where other places were already proven. I think we are already doing this in other places:

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/e645450e0ebed13eac3e2645be86b10cf73b4fb7/Microsoft.Azure.Cosmos/src/Routing/CollectionRoutingMap.cs#L143-L164

Not a blocking comment, but rather something to consider.

2024-09-25 14:44 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        internal static bool IsSubset(
Noted. Thanks

2024-09-25 14:45 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/FeedRange/FeedRanges/FeedRangeEpk.cs
> +            if (!range.IsMinInclusive)
@ealsur known scenario of where msIncusive True is single PK value. AFAIK no other case exists right now in .NET JAVA has a normalization flow where its changes MaxEPK reduces y 1 etc... but not .NET. 

The idea is to cover all combinations for maxInclusive so-that we will be functionally fool-proof and assert that minInclusive is always True.

2024-09-25 14:48 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            ranges.Sort(Documents.Routing.Range<string>.MinComparer.Instance);
Good call-out, our current implementation is guaranting and not as contract. 
This path will never be perf critical and we can live with current state. Feel free to resolve it.

2024-09-25 15:11 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        internal static bool IsSubset(
If there is no previous existing logic that might apply, feel free to disregard.

2024-09-25 16:43 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/FeedRange/FeedRanges/FeedRangeEpk.cs
> +            if (!range.IsMinInclusive)
Hopefully this is satisfactory response @ealsur . Thanks again for your review.

2024-09-30 12:08 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +            Cosmos.FeedRange parentFeedRange,
I don't think the parent/child prefix makes much sense? Maybe left and right?

2024-09-30 12:17 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                isMinInclusive: firstRange.IsMinInclusive,
@philipthomas-MSFT - it does not address the concern. You have added a check in FeedRangeEpK to disallow MinInclusive being False. Technically a breaking change but I think this is fine because in no combination I am aware of we would ever use a Range with minIclusive==false. But You can still have isMaxIncluded being both true and false (for point ranges - based off of a single logical PartitionKey). So your consistency check is too strict - it would fail for FeedRanges for a single logical partition.

2024-09-30 12:18 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/IsFeedRangePartOfAsyncTests.cs
> +            this.containerInternal = await IsFeedRangePartOfAsyncTests.CreateSinglePartitionContainer(this.cosmosDatabase);
Would be good to have test coverage for containers with V1 and V2 hashes.

2024-09-30 12:20 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/IsFeedRangePartOfAsyncTests.cs
> +        [DataRow("", "FFFFFFFFFFFFFFFF", true, DisplayName = "Full range is subset")]
Test cases should not just include random EPKs but probably also the edge cases (Full EPK is subset of Full EPK, and a Point range (with IsMaxInclusive==false) being subset and not subset of a parent range)

2024-09-30 12:38 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                isMinInclusive: firstRange.IsMinInclusive,
we add the check here.

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/4e2a95b58ac88f5695ff75ca5a004c3ded1f50ed/Microsoft.Azure.Cosmos/src/FeedRange/FeedRanges/FeedRangeEpk.cs#L28C13-L31C14

2024-09-30 12:42 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/IsFeedRangePartOfAsyncTests.cs
> +        [DataRow("", "FFFFFFFFFFFFFFFF", true, DisplayName = "Full range is subset")]
Are you looking at the other tests? This test was just for testing a PartitionKey as the name says. I have other tests that are more exhaustive.

2024-09-30 12:43 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +            Cosmos.FeedRange parentFeedRange,
let's address these other concerns and we can discuss name refactoring later.

2024-09-30 14:34 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/IsFeedRangePartOfAsyncTests.cs
> +        [DataRow("", "FFFFFFFFFFFFFFFF", true, DisplayName = "Full range is subset")]
Based on new scenarios as discussed in Teams, are these covered now? Just one scenario where we need clarity.

2024-09-30 14:40 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                isMinInclusive: firstRange.IsMinInclusive,
> But You can still have isMaxIncluded being both true and false (for point ranges - based off of a single logical PartitionKey). So your consistency check is too strict - it would fail for FeedRanges for a single logical partition.

@FabianMeiswinkel  What check are you referring to specifically that is too strict? The EnsureConsistentInclusivity is just for making sure any ranges that come from GetEffectiveRanges has consistency. And you are suggesting that there are cases where it could and should be inconsistent?

2024-09-30 14:43 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/IsFeedRangePartOfAsyncTests.cs
> +            this.containerInternal = await IsFeedRangePartOfAsyncTests.CreateSinglePartitionContainer(this.cosmosDatabase);
> Would be good to have test coverage for containers with V1 and V2 hashes.

Would like to hear from others on this? Are we expecting different behavior for V1 and V2 at this moment? Is this required for the existing customer base. I would rather create a separate PR for this later to avoid scope creep.

2024-09-30 14:51 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +            Cosmos.FeedRange parentFeedRange,
> I don't think the parent/child prefix makes much sense? Maybe left and right?

I would agree with this but want to make sure we are aligned if we decide to do this by setting some guidelines.

**Parent** refactors to _Left_, superior scoped object.
**Child** refactors to _Right_, inferior scoped object, comparison point.

2024-09-30 16:17 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                            throw new ArgumentException(string.Format(ClientResources.FeedToken_UnknownFormat, parentFeedRange.ToJsonString()));
nit: Include the name of the parameter in exception (same for childFeedRange as well)

2024-09-30 16:24 UTC, kirankumarkolli approved these changes

2024-09-30 16:33 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +            Cosmos.FeedRange parentFeedRange,
The names are part of public contract, ideal if we can close on the naming. 

Parent and Child might lead developer to map server partition parent/child relationship, which is not guaranteed (FeedRange can be a super-set/sub-set). 

Left/Right also feels like some relationship. 

ref: https://learn.microsoft.com/en-us/dotnet/api/system.collections.icomparer.compare?view=net-8.0#system-collections-icomparer-compare(system-object-system-object)
This API contract from .NET used to names 'x', 'y'. 
May be that's good here? 

/cc: @jcocchi

2024-09-30 16:40 UTC, jcocchi commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +            Cosmos.FeedRange parentFeedRange,
Is the intent only comparing parent/ child feed ranges or could it be used to determine if *any* feed range is a subset of *any other* range? If the logic of the function supports comparing any two ranges then I like Kiran's suggestion to keep the naming more generic

`IsFeedRangeSubsetAsync(x, y)`

2024-09-30 17:18 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                            throw new ArgumentException(string.Format(ClientResources.FeedToken_UnknownFormat, parentFeedRange.ToJsonString()));
sure. done.

2024-09-30 17:22 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/IsFeedRangePartOfAsyncTests.cs
> +        [DataRow("", "FFFFFFFFFFFFFFFF", true, DisplayName = "Full range is subset")]
@FabianMeiswinkel  the scenarios, are fixed. I had to throw in some extra to do the substraction if the child is MaxExclusive so that it fits in the range of the parent.

```
yield return new object[] { "10", "11", false, "10", "10", true, true }; // The child range, which starts at 10 and ends just before 11 (non-inclusive), does not fits entirely within the parent range, which starts and ends at 10 (inclusive), due to the parent's inclusive boundary at 10.
yield return new object[] { "A", "B", false, "A", "A", true, true }; // The child range, which starts at A and ends just before B (non-inclusive), does not fits entirely within the parent range, which starts and ends at A (inclusive), due to the parent's inclusive boundary at A.

```

2024-09-30 17:24 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +            Cosmos.FeedRange parentFeedRange,
Its really any feed range comparision with another feed range at the end of the day.

2024-09-30 17:28 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +            Cosmos.FeedRange parentFeedRange,
+1 on x and y - there is no need for this to be any range due to splits etc.(and parent/child can easily lead down that road)

2024-09-30 17:29 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +            Cosmos.FeedRange parentFeedRange,
So, I am fine with x, y. Unfortunately, I need to refactor a lot, and change all the documentation that I have, so I need to get a thumbs up or ping me in Teams to move forward.

2024-10-01 12:33 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +            Cosmos.FeedRange parentFeedRange,
Ok. So I just updated Container.cs with this since that is the public contract. I will fix documentation where necessary before it goes public.

2024-10-01 20:53 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +            if (ranges.Count == 1)
nit: Assert that the ranges is not empty

2024-10-01 20:56 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                    throw new ArgumentNullException(parentFeedRange == null
nit: For in-correct combination (maxInclusive=true, maxInclude=false) fail ArgumentOutOfRangeException

2024-10-01 20:58 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        private static string GetExclusiveMaxValue(string value)
nit: Dead code, can be removed?

2024-10-01 20:59 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +        private static bool IsValidHex(string value)
nit: Dead code

2024-10-02 17:56 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +        /// Determines whether the given child feed range is a part of the specified parent feed range.
```suggestion
        /// Determines whether a feed range contains another feed range.

```

2024-10-02 17:56 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +        /// This method performs a comparison between the effective ranges of the child and parent feed ranges, determining if the child is fully contained within the parent.
Its implementation details and not needed on public documentation.

2024-10-02 17:57 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +        /// <param name="x">The feed range representing the parent range.</param>
nit: parent and child are still used as reference here in documentation.

2024-10-02 17:58 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +        /// <param name="x">The feed range representing the parent range.</param>
How about using outer and inner in documentation instead of parent and child?

2024-10-02 18:16 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                (true, false) => throw new NotSupportedException("The combination where the parent range's maximum is inclusive and the child range's maximum is exclusive is not supported in the curr
```suggestion
                (true, false) => throw new NotSupportedException("The combination where the parent range's maximum is inclusive and the child range's maximum is exclusive is not supported in the current implementation."),

```

2024-10-02 18:17 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> +                (true, false) => throw new NotSupportedException("The combination where the parent range's maximum is inclusive and the child range's maximum is exclusive is not supported in the curr
This message developer sees or gets.

2024-10-02 18:17 UTC, kirankumarkolli approved these changes

2024-10-02 18:30 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +        /// This method performs a comparison between the effective ranges of the child and parent feed ranges, determining if the child is fully contained within the parent.
done

2024-10-02 18:31 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
> +        /// <param name="x">The feed range representing the parent range.</param>
keeping it at x and y.

2024-10-02 18:33 UTC, kirankumarkolli approved these changes

2024-10-02 18:48 UTC, NaluTripician approved these changes
LGTM

2024-10-02 23:23 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos.Encryption.Custom/src/EncryptionContainer.cs
> +                parentFeedRange,
NIT: x and y like in the base class please.

2024-10-02 23:23 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionContainer.cs
> +            Cosmos.FeedRange parentFeedRange,
NIT: x and y like in base class

2024-10-02 23:24 UTC, FabianMeiswinkel approved these changes
LGTM except for the two NITs

2024-10-03 13:28 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos.Encryption/src/EncryptionContainer.cs
> +            Cosmos.FeedRange parentFeedRange,
Done @FabianMeiswinkel , @NaluTripician  and @kirankumarkolli . Please approve again.

2024-10-03 13:28 UTC, philipthomas-MSFT commented on Microsoft.Azure.Cosmos.Encryption.Custom/src/EncryptionContainer.cs
> +                parentFeedRange,
Done @FabianMeiswinkel , @NaluTripician  and @kirankumarkolli . Please approve again.

2024-10-03 17:20 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> -﻿//------------------------------------------------------------
Seems like the line feed are overwirtten. 
Can you please update it limit only the required changes.

2024-10-03 17:21 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
> -﻿//------------------------------------------------------------
In-case if you have accepted suggestions it might also result into this state.

2024-10-04 15:28 UTC, NaluTripician approved these changes

2024-10-04 15:28 UTC, merged