draft: configuration
Azure/azure-cosmos-dotnet-v3 pull request #4631
Opened 2024-08-06 19:52 UTC by ax-ms

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Include samples if adding new API, and include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #IssueNumber

2024-08-09 16:48 UTC, ealsur commented on Microsoft.Azure.Cosmos/src/Resource/Settings/AccountProperties.cs
> +        public bool EnableNReginSynchronousCommit { get; set; }
nit: 
```suggestion
        internal bool EnableNRegionSynchronousCommit { get; set; }
```

2024-08-09 16:56 UTC, kirankumarkolli requested changes
this branch can be used for local development and update is always sync from msdata repo.

2024-08-09 16:59 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/Settings/AccountProperties.cs
> +        public bool EnableNReginSynchronousCommit { get; set; }
Can you please offline share (teams IM) related spec?

2024-09-13 18:17 UTC, kirankumarkolli commented
Closing the PR for now please re-open when needed

2024-09-13 18:17 UTC, closed without merging