Open Telemetry: Fixes Operation name to open follow Otel convention
Azure/azure-cosmos-dotnet-v3 pull request #4643
Opened 2024-08-16 10:44 UTC by sourabh1007

## Description

ref #4553 

Operation Name db.operation.name
Batch/bulk operations:

execute_batch
execute_bulk
batch_< operation name >
bulk_< operation name >

Change feed operations:

query_change_feed

Conflicts operations:

delete_conflict
query_conflicts
~~read_all_conflicts~~
read_conflict

Container operations:

create_container
create_container_if_not_exists
delete_container
~~query_containers~~
~~read_all_containers~~
read_container
replace_container

Database operations:

create_database
create_database_if_not_exists
delete_database
~~query_databases~~
~~read_all_databases~~

Encryption key operations:

create_client_encryption_key
~~query_encryption_keys~~
~~read_all_encryption_keys~~
read_client_encryption_key
replace_client_encryption_key

Item operations:

create_item
delete_all_items_by_partition_key
delete_item
patch_item
query_items
~~read_all_items~~
~~read_all_items_of_logical_partition~~
read_many_items
read_item
replace_item
upsert_item

Permission operations:

create_permission
delete_permission
~~query_permissions~~
~~read_all_permissions~~
read_permission
replace_permission
upsert_permission

Stored procedure operations:

create_stored_procedure
delete_stored_procedure
execute_stored_procedure
~~query_stored_procedures~~
~~read_all_stored_procedures~~
read_stored_procedure
replace_stored_procedure

Throughput operations:

read_throughput
replace_throughput

Trigger operations:

create_trigger
delete_trigger
~~query_triggers~~
~~read_all_triggers~~
read_trigger
replace_trigger
User operations:

create_user
delete_user
~~query_users~~
~~read_all_users~~
read_user
replace_user
upsert_user

User-defined function operations:

create_user_defined_function
delete_user_defined_function
~~query_user_defined_functions~~
read_all_user_defined_functions
read_user_defined_function

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #IssueNumber

2024-08-19 16:44 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos.sln
> +# Visual Studio Version 17
Undo changes to this this file

2024-08-22 09:07 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos.sln
> +# Visual Studio Version 17
always it creates a PR with "non-draft" status :(

2024-08-27 13:39 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Batch/BatchCore.cs
> +            if (this.isHomogenousOperations)
Is that really necessary? IMO it creates more harm/confusion than benefit - transactional batch should always be executeBatch - it doesn't really matter what operations you do anyway - and in many cases it will be a mx anyway.

2024-08-27 13:41 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Batch/BatchCore.cs
> +                operationName: OpenTelemetryConstants.Operations.PatchItemStream,
From Luidmila's proposal I did not get the feeling it would make sense to distinguish xxxItem from xxxItemStream - either we want to normalize operation names between SDKs - then distinguishing how serialization is done doesn't matter and causes just confusion - or we keep is separate for each SDK/language.

2024-08-27 13:44 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedEstimatorIterator.cs
> +                operationName: OpenTelemetryConstants.Operations.QueryChangeFeedEstimator,
dito - no need to know whether it is estimator or not. if that is used - put it in an attribute - like the filter type - but not a dimension of operation name

2024-08-27 13:45 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Resource/FeedIterators/FeedIteratorInlineCore{T}.cs
> +                        operationName: OpenTelemetryConstants.Operations.TypedQueryItems,
dito - no need to use operation name to distinguish types from stream

2024-08-27 13:46 UTC, FabianMeiswinkel requested changes
Left few comments

2024-08-27 15:01 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Batch/BatchCore.cs
> +            if (this.isHomogenousOperations)
it was decided to get more information about the batch. @jcocchi @kirankumarkolli what you think about it?

2024-08-27 16:43 UTC, jcocchi commented on Microsoft.Azure.Cosmos/src/Batch/BatchCore.cs
> +            if (this.isHomogenousOperations)
We did call out homogeneous vs. heterogeneous in the proposal, but my understanding of the implementation might have been flawed. This only came up in the database semantic conventions because of how homogenous vs. heterogeneous operations effect SQL traces, and I was trying to equate this to our own APIs.

Transactional Batch - I was thinking represents heterogeneous operations, regardless of what a user is actually doing in the transaction. We don't need to inspect the batch to determine if all operations are actually the same type or not, we should just tell them there was a batch. I'm aligned `executeBatch` covers this case well

Bulk - I thought this was always homogenous and if there was a group of creates and a group of reads, they would get separate network requests for each type for each partition key. After chatting with @sourabh1007 seems like my understanding was wrong. In that case, I don't think we need to call out heterogenous vs homogeneous here either- we can just prepend whatever the operation type was with `bulk_`

2024-08-27 16:43 UTC, jcocchi commented on Microsoft.Azure.Cosmos/src/Batch/BatchCore.cs
> +                operationName: OpenTelemetryConstants.Operations.PatchItemStream,
Do other SDKs have stream APIs? Maybe we can add an extra attribute to indicate stream in .NET instead and keep operation name uniform?

2024-08-27 16:43 UTC, jcocchi commented on Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchInternal.cs
> +                this.homogenousOperation = this.isHomogenousOperations ? itemBatchOperation.OperationName : null;
I'm not sure I understand this line, if there's a heterogeneous operation in the transactional batch, would the operation name be null?  `executeBatch` as the operation name is a better alternative in this case

2024-08-27 16:43 UTC, jcocchi commented on Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedEstimatorIterator.cs
> +                operationName: OpenTelemetryConstants.Operations.QueryChangeFeedEstimator,
I think it's useful to capture estimator vs. change feed reads as part of the operation name because the intent of the request is totally different, agree the type of change feed read can be attributes

2024-08-27 16:43 UTC, jcocchi commented on Microsoft.Azure.Cosmos/src/ChangeFeed/ChangeFeedPartitionKeyResultSetIteratorCore.cs
> +                                operationName: OpenTelemetryConstants.Operations.QueryChangeFeedForPartitionKeyRange,
Just to clarify- this is tracking requests for all of the existing PK ranges for a given container right? Not requests for actual change feed data?

Querying for partition key ranges feels different than querying change feed for data, it's more of a metadata call. I agree querying change feed for data based on FeedRange vs. based on a PK (or query etc. in the future) can be captured as an attribute though

2024-08-27 16:43 UTC, jcocchi commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryConstants.cs
> +            public const string ExecuteBulk = "execute_bulk";
Do we have `execute_bulk` in .NET? When would this be used?

2024-08-27 16:43 UTC, jcocchi commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryConstants.cs
> +            public const string ExecuteBatchPrefix = "batch_";
Assuming this is for transactional batch, do we need `batch_`? Would there be a separate trace for each item in the transactional batch or just one top level for the whole operation (represented by `execute_batch`?

2024-08-28 16:24 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Batch/BatchCore.cs
> +                operationName: OpenTelemetryConstants.Operations.PatchItemStream,
Stream APIs: Removing stream from operation name and later we can add a new attribute to indicate that, it is a stream API as a non breaking change.

2024-08-28 16:29 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedEstimatorIterator.cs
> +                operationName: OpenTelemetryConstants.Operations.QueryChangeFeedEstimator,
We are going ahead with, what we have right now.

2024-08-28 16:35 UTC, jcocchi commented on Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedEstimatorIterator.cs
> +                operationName: OpenTelemetryConstants.Operations.QueryChangeFeedEstimator,
To clarify, operation names would be:
- query_change_feed
- query_change_feed_for_partition_key_range
- query_change_feed_estimator

Attributes we can add later if we decide to include if the `query_change_feed` was for a particular pk or not

2024-08-29 01:59 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchInternal.cs
> +                this.homogenousOperation = this.isHomogenousOperations ? itemBatchOperation.OperationName : null;
it is an implementation of `batch_< operation name >` and `execute_batch` operation name for homogenous and heterogenous operation. but anyway, it doen't matter now. we are going to remove this implementation and I am going to remove this code.

2024-08-29 02:00 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryConstants.cs
> +            public const string ExecuteBulk = "execute_bulk";
as per our last discussion, there won't be `execute_bulk` operation name. There is always going to be `bulk_< operation name >` operation name for each operational traces.

2024-08-29 02:02 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryConstants.cs
> +            public const string ExecuteBatchPrefix = "batch_";
For transactional batch, there is going to be only one top level trace for whole operation. and batch_size will tell the number of items in the batch.

2024-09-04 00:22 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/ChangeFeed/ChangeFeedPartitionKeyResultSetIteratorCore.cs
> +                                operationName: OpenTelemetryConstants.Operations.QueryChangeFeedForPartitionKeyRange,
I really don't think this makes sense - one of the initial decisions was that operation level activities/traces should map to operations a customer triggered. QueryPKRanges is never something a customer directly triggers. How do you want to represent the call hierarchy here - we have transport level traces - that is where these kind of traces can show up. PKRanges queryor change feed is simply a concept that customers can't digest.

2024-09-04 00:26 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedEstimatorIterator.cs
> +                operationName: OpenTelemetryConstants.Operations.QueryChangeFeedEstimator,
what about query_change_feed_for_feed_range then?

2024-09-04 00:27 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedEstimatorIterator.cs
> +                operationName: OpenTelemetryConstants.Operations.QueryChangeFeedEstimator,
I still think it explodes operation names too much. If you feel strong about it, go ahead with this in .Net - but in Java I will use attributes for the filter type (and we don't have an explicit estimator API - so, that one is void anyway)

2024-09-04 00:28 UTC, jcocchi commented on Microsoft.Azure.Cosmos/src/ChangeFeed/ChangeFeedPartitionKeyResultSetIteratorCore.cs
> +                                operationName: OpenTelemetryConstants.Operations.QueryChangeFeedForPartitionKeyRange,
Maybe I misunderstood what this call is from. Is this the same as calls to `GetFeedRangesAsync()`? This is used as part of the change feed pull model and is the documented way to parallelize reading change feed in the pull model across multiple partitions (ref: https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/change-feed-pull-model?tabs=dotnet#use-feedrange-for-parallelization)

2024-09-04 00:32 UTC, jcocchi commented on Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedEstimatorIterator.cs
> +                operationName: OpenTelemetryConstants.Operations.QueryChangeFeedEstimator,
Doesn't java have `getCurrentState()` and `getEstimatedLag()` ? (ref https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/how-to-use-change-feed-estimator?tabs=java#implement-the-change-feed-estimator)

The goal of having these names is to normalize them across SDKs where possible so I think we should land on a mutually agreeable set but I'm definitely open to more discussion!

2024-09-04 00:55 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/ChangeFeed/ChangeFeedPartitionKeyResultSetIteratorCore.cs
> +                                operationName: OpenTelemetryConstants.Operations.QueryChangeFeedForPartitionKeyRange,
That would be just query_feed_ranges - nothing with change feed - and at least in Java it also is handled by the cache most of the time (we allow customers to side-step the cache). Anyway, if there would be an operation for COntainer.GetFeedRangesAsync that makes sense - but it should be query_feed_range or read_all_feed_ranges - nothing related to change feed. The changedfeed for pkranges is purely background task that we use to maintain our internal caches for partitions

2024-09-04 01:01 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedEstimatorIterator.cs
> +                operationName: OpenTelemetryConstants.Operations.QueryChangeFeedEstimator,
Yes - we have those APIs in the SDK but mapping query_change_feed_estimator to ChangeFeedProcessor.getCurrentState isn't necessarily intuitive

2024-09-04 01:02 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedEstimatorIterator.cs
> +                operationName: OpenTelemetryConstants.Operations.QueryChangeFeedEstimator,
So, we can either leave those as query_change_feed (because that is what is happening after all against the backend)
Or if we want to distinguish them I could live with change_feed_processor_context change_feed_processor_estimate or somethign along those lines

2024-09-04 01:04 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedEstimatorIterator.cs
> +                operationName: OpenTelemetryConstants.Operations.QueryChangeFeedEstimator,
But query_change_feed  with some attribute that provides more context IMO better draws the big picture. I am pretty flexible here - I just think the _estimator suffix is really confusing in Java because the is no explicit ChangeFeedEstimator class/API like in .Net - and the getEstimate API is kind of deprecated - anything new will only be added to getCurrentState

2024-09-05 02:44 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedEstimatorIterator.cs
> +                operationName: OpenTelemetryConstants.Operations.QueryChangeFeedEstimator,
As we discussed, rename it to `get_change_feed_processor_estimate`

2024-09-05 02:44 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/ChangeFeed/ChangeFeedPartitionKeyResultSetIteratorCore.cs
> +                                operationName: OpenTelemetryConstants.Operations.QueryChangeFeedForPartitionKeyRange,
As we discussed, need to remove the activity create for this call, as it is a metadata call.

2024-09-16 10:30 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryResponse{T}.cs
> +            return responseMessage is QueryResponse ? Documents.OperationType.Query : Documents.OperationType.Invalid;
This looks pretty hacky to me - why not have Response<T> return ResourceType and OperationType?

2024-09-17 03:02 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/CosmosClient.cs
> +                openTelemetry: new (OpenTelemetryConstants.Operations.CreateDatabaseIfNotExists, (response) => new OpenTelemetryResponse(response)));
CreateDatabaseStreamAsync

2024-09-17 03:16 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Resource/FeedIterators/FeedIteratorInlineCore{T}.cs
> +                        openTelemetry: new (OpenTelemetryConstants.Operations.QueryItems, (response) => new OpenTelemetryResponse<T>(responseMessage: response)));
FeedIterator.ReadNextAsync != QueryItems

2024-09-17 03:27 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryConstants.cs
> +            public const string QueryChangeFeed = "query_change_feed";
Is "_" expected in `change_feed`?

2024-09-17 03:56 UTC, jcocchi commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryConstants.cs
> +            public const string DeleteAllItemsByPartitionKeyStream = "delete_all_items_by_partition_key_stream";
Are we removing "stream" from the name for consistency across languages?

2024-09-17 03:56 UTC, jcocchi commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryConstants.cs
> +            public const string QueryChangeFeed = "query_change_feed";
these are two words so "_" makes sense

2024-09-17 04:32 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryConstants.cs
> +            public const string DeleteAllItemsByPartitionKeyStream = "delete_all_items_by_partition_key_stream";
yes, I missed it somehow.

2024-09-17 17:25 UTC, kirankumarkolli approved these changes

2024-09-17 19:10 UTC, kirankumarkolli approved these changes

2024-09-17 20:05 UTC, FabianMeiswinkel approved these changes
LGTM

2024-09-17 21:07 UTC, jcocchi approved these changes

2024-09-18 01:31 UTC, kirankumarkolli approved these changes

2024-09-18 01:31 UTC, merged