[Internal] Fault Injection: Adds Gateway mode support
Azure/azure-cosmos-dotnet-v3 pull request #4667
Opened 2024-09-04 19:54 UTC by NaluTripician

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Include samples if adding new API, and include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #IssueNumber

2024-10-11 09:51 UTC, philipthomas-MSFT approved these changes
LGTM with the one caveat. In our discussion on yesterday, would like to see you apply some of the things we discussed. Other than that, good job.

2024-11-06 21:21 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/FaultInjection/src/implementation/ChaosInterceptor.cs
> +    using Antlr4.Runtime.Misc;
Why do you need this?

2024-11-06 21:22 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/FaultInjection/src/implementation/FaultInjectionConditionInternal.cs
> +            if (partitionKeyRangeIds != null && partitionKeyRangeIds.Count() > 0)
use Any() instead - otherwise the enumerable needs to be iterated over twice.

2024-11-06 21:22 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/FaultInjection/src/implementation/FaultInjectionConditionInternal.cs
> +
NIT: excessive LF

2024-11-06 21:27 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/FaultInjection/src/implementation/FaultInjectionConditionInternal.cs
> +                return request.OperationType == this.operationType;
ctor should prevent this.operationType form being set to null - ArgumentNullException in ctor is missing.

2024-11-06 21:28 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/FaultInjection/src/implementation/FaultInjectionConditionInternal.cs
> +                return request.OperationType == this.operationType;
Similar misses I think in other validators as well.

2024-11-06 21:31 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/FaultInjection/tests/FaultInjectionGatewayModeTests.cs
> +
NIT: remove LF

2024-11-06 21:32 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/FaultInjection/tests/FaultInjectionGatewayModeTests.cs
> +            (this.database, this.container) = await TestCommon.GetOrCreateMultiRegionFIDatabaseAndContainers(this.client);
Method shoudl be named with Async suffix

2024-11-06 21:33 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/FaultInjection/tests/Utils/TestCommon.cs
> +        internal static async Task<(Database, Container)> GetOrCreateMultiRegionFIDatabaseAndContainers(CosmosClient client)
NIT: Async suffix in method name

2024-11-06 21:34 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +                //    await this.chaosInterceptorFactory.ConfigureChaosInterceptorAsync();
why ommented out?

2024-11-06 21:35 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +                //    await this.chaosInterceptorFactory.ConfigureChaosInterceptorAsync();
I mean can be deleted now?

2024-11-06 21:36 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/CosmosClient.cs
> +        public async Task InitilizeFaultInjectionAsync()
This should certainly not be public API, correct?

2024-11-06 21:36 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/CosmosClient.cs
> +        public async Task InitilizeFaultInjectionAsync()
Blocking mainly on this

2024-11-06 21:37 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
> +        },
Revert

2024-11-06 21:38 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos.Encryption.Custom/tests/Microsoft.Azure.Cosmos.Encryption.Custom.Tests/Contracts/DotNetSDKEncryptionCustomAPI.json
> +    "Microsoft.Azure.Cosmos.Encryption.Custom.CompressionOptions;System.Object;IsAbstract:False;IsSealed:False;IsInterface:False;IsEnum:False;IsClass:True;IsValueType:False;IsNested:False;IsGenericTy
These changes are unrelated to this PR? Revert?

2024-11-06 21:39 UTC, FabianMeiswinkel requested changes
Looks good to me overall - but few comments need some work (the CosmosClient public API especially)

2024-11-12 02:26 UTC, NaluTripician commented on Microsoft.Azure.Cosmos/FaultInjection/src/implementation/FaultInjectionConditionInternal.cs
> +                return request.OperationType == this.operationType;
I believe here that enums in C# are non-nullable types, so OperationType here and other types in validator can never be null.  Will have a complier error if checking for null type.

2024-11-12 09:43 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/FaultInjection/src/implementation/ChaosInterceptor.cs
> +        private const string FautInjecitonId = "FaultInjectionId";
```suggestion
        private const string FautInjectionId = "FaultInjectionId";
```

2024-11-12 09:44 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/FaultInjection/src/implementation/ChaosInterceptor.cs
> +                    new Guid(request.Headers.Get(ChaosInterceptor.FautInjecitonId)));
```suggestion
                    new Guid(request.Headers.Get(ChaosInterceptor.FautInjectionId)));
```

2024-11-12 09:44 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/FaultInjection/src/implementation/ChaosInterceptor.cs
> +                    request.Headers.Get(ChaosInterceptor.FautInjecitonId));
```suggestion
                    request.Headers.Get(ChaosInterceptor.FautInjectionId));
```

2024-11-12 09:45 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/FaultInjection/src/implementation/ChaosInterceptor.cs
> +                    new Guid(request.Headers.Get(ChaosInterceptor.FautInjecitonId)));
```suggestion
                    new Guid(request.Headers.Get(ChaosInterceptor.FautInjectionId)));
```

2024-11-12 09:45 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/FaultInjection/src/implementation/ChaosInterceptor.cs
> +                    request.Headers.Get(ChaosInterceptor.FautInjecitonId));
```suggestion
                    request.Headers.Get(ChaosInterceptor.FautInjectionId));
```

2024-11-12 09:46 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/FaultInjection/src/implementation/ChaosInterceptor.cs
> +                    new Guid(request.Headers.Get(ChaosInterceptor.FautInjecitonId)));
```suggestion
                    new Guid(request.Headers.Get(ChaosInterceptor.FautInjectionId)));
```

2024-11-12 09:46 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/FaultInjection/src/implementation/ChaosInterceptor.cs
> +                    request.Headers.Get(ChaosInterceptor.FautInjecitonId));
```suggestion
                    request.Headers.Get(ChaosInterceptor.FautInjectionId));
```

2024-11-12 09:50 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/FaultInjection/src/implementation/FaultInjectionConditionInternal.cs
> +                return request.OperationType == this.operationType;
True for OperationType but in line 300 pkRangeIds could be null for example. I think it would be good to null-check arguments in the ctors of the validators (where applicable)

2024-11-12 09:55 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/FaultInjection/src/implementation/FaultInjectionServerErrorResultInternal.cs
> +                            Encoding.UTF8.GetBytes($"Fault Injection Server Error: Gone, rule: {ruleId}"))),
I think you unintentionally use the wrong encoding here. Encoding.UTF8 will add a byte order bark (first byte(s) indicating that the subsequent string is UTF8). Gateway (or backend) normally would not use byte order marks. So, I think instead you shoudl deinfe a Utf8Encoding passing false into the ctor and reuse that instance to apply UTF8 encoding without byte order mark.

2024-11-12 16:30 UTC, NaluTripician commented on Microsoft.Azure.Cosmos/FaultInjection/src/implementation/ChaosInterceptor.cs
> +                    request.Headers.Get(ChaosInterceptor.FautInjecitonId));
All of these also seem to be missing an L too --> `FaultInjectionId`. Thanks for the catch.

2024-11-14 16:54 UTC, FabianMeiswinkel approved these changes
LGTM - Thanks!

2024-11-15 00:03 UTC, kirankumarkolli approved these changes

2024-11-18 19:38 UTC, NaluTripician commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
> +        "Microsoft.Azure.Cosmos.Fluent.CosmosClientBuilder WithAvailibilityStrategy(Microsoft.Azure.Cosmos.AvailabilityStrategy)": {
Looks like these comments were on an outdated version of the branch, this appears to be addressed

2024-11-18 19:38 UTC, NaluTripician commented on Microsoft.Azure.Cosmos/src/CosmosClient.cs
> +        public async Task InitilizeFaultInjectionAsync()
Looks like these comments were on an outdated version of the branch, this was removed

2024-11-18 19:39 UTC, merged