Trigger Failover On 3092 And 1022expand=1
Azure/azure-cosmos-dotnet-v3 pull request #4670
Opened 2024-09-09 19:58 UTC by kundadebdatta

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Include samples if adding new API, and include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

## Closing issues

To automatically close an issue: closes #IssueNumber

2024-09-10 00:09 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/ResourceThrottleRetryPolicy.cs
> +            this.isMultiMasterWriteRegion = !request.IsReadOnlyRequest
I think you are missing the condition that >1 write region need to be available (honoring preferred regions, excludedRegions etc.) - Could be included in GlobalEndpointManager.CanUseMultipleriteRegion but glancing at the code I did not see this check.

2024-09-10 00:11 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/direct/GoneAndRetryWithRequestRetryPolicy.cs
> +            return exception is LeaseLostException
No LeaseLostException has completely different meaning - that is thrown when Change Feed Processor is losing the CFP lease.

2024-09-10 00:12 UTC, FabianMeiswinkel requested changes
Looks good except for few minor comments

2024-09-10 00:13 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/direct/GoneAndRetryWithRequestRetryPolicy.cs
> +            return exception is LeaseLostException
Yes, this is taken care in the original msdata PR: `1453704`

2024-09-10 00:15 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/direct/GoneAndRetryWithRequestRetryPolicy.cs
> +            return exception is LeaseLostException
I have created a new exception type: `LeaseNotFoundException`. That PR has more context on it. We can follow up on that PR itself!

2024-09-17 18:25 UTC, kundadebdatta commented
Was a demo PR. Closing since the original ones got merged.

2024-09-17 18:25 UTC, closed without merging