[INTERNAL] Samples: Fixes upgrades to latest versions (vulnerabilities) and also warnings
Azure/azure-cosmos-dotnet-v3 pull request #4693
Opened 2024-09-14 03:52 UTC by kirankumarkolli

[INTERNAL] Samples: Fixes upgrades to latest versions (vulnerabilities) and also warnings

For few select package latest version is configured
```
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="*" />
    <PackageReference Include="Newtonsoft.Json" Version="*" />
    <PackageReference Include="System.Text.Json" Version="*" />
```

NOTE: With this its possible that post a new package published with breaking changes the build might break (which will help catch in-case samples are out-of-sync)

2024-09-17 23:16 UTC, Pilchie requested changes
Blocking only on the BOM changes. Other than that, just curious, and a note that we should eventually update to .NET 8.0 as well.

2024-09-17 23:16 UTC, Pilchie commented on Microsoft.Azure.Cosmos.Samples/Usage/CFPullModelAllVersionsAndDeletesMode/CFPullModelAllVersionsAndDeletesMode.csproj
> +    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
I notice you didn't add `System.Text.Json` here.  How did you decide when to add it and when not to?

2024-09-17 23:16 UTC, Pilchie commented on Microsoft.Azure.Cosmos.Samples/Usage/ChangeFeed/ChangeFeed.csproj
> +    <PackageReference Include="System.Net.Security" Version="4.3.2" />
And here you added these two?

2024-09-17 23:16 UTC, Pilchie commented on Microsoft.Azure.Cosmos.Samples/Usage/PowerShellRestApi/PowerShellRestApi.csproj
> +    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
Is this needed here?

2024-09-17 23:16 UTC, Pilchie commented on Microsoft.Azure.Cosmos.Samples/Usage/ReEncryption/ReEncryption.csproj
>      <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.2.0" />
You didn't update these one?

2024-09-17 23:16 UTC, Pilchie commented on Microsoft.Azure.Cosmos.Samples/Usage/ReEncryption/ReEncryption.csproj
> +    <PackageReference Include="System.Drawing.Common" Version="8.0.8" />
Is this right?

2024-09-17 23:16 UTC, Pilchie commented on Microsoft.Azure.Cosmos.Samples/Usage/ApplicationInsights/ApplicationInsights.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
It looks like you might have add/removed the BOM on many of these files.  Is that intentional?

2024-09-17 23:16 UTC, Pilchie commented on Microsoft.Azure.Cosmos.Samples/Usage/AzureFunctions/AzureFunctions.csproj
>      <TargetFramework>net6.0</TargetFramework>
Should we update all of these to `net8.0` while we're here?

2024-09-17 23:28 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos.Samples/Usage/ApplicationInsights/ApplicationInsights.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
Its all VS magic, nothing intentional.

2024-09-17 23:29 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos.Samples/Usage/AzureFunctions/AzureFunctions.csproj
>      <TargetFramework>net6.0</TargetFramework>
True little bit explored, it will need changes to the pipelines as well. 
Thoughts we can follow-up on .NET8 independently, is that okey?

2024-09-17 23:30 UTC, Pilchie commented on Microsoft.Azure.Cosmos.Samples/Usage/AzureFunctions/AzureFunctions.csproj
>      <TargetFramework>net6.0</TargetFramework>
Absolutely.

2024-09-17 23:33 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos.Samples/Usage/CFPullModelAllVersionsAndDeletesMode/CFPullModelAllVersionsAndDeletesMode.csproj
> +    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
That's a great catch.
WE have a transient dependency on STJ and it got flagged in these projects but no on other projects, as existing dependencies already on patched ones. 

But I too agree that its better be explicit. Will fix it.

2024-09-17 23:35 UTC, Pilchie commented on Microsoft.Azure.Cosmos.Samples/Usage/ApplicationInsights/ApplicationInsights.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
Can you get a hex editor and look at the file and see what the encoding is? None of these files have any characters beyond ASCII, so it should be fine regardless. We are probably just going from UTF-8 with BOM to UTF-8 without BOM or vice versa. Checking with some .NET folks about what they suggest.

2024-09-17 23:35 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos.Samples/Usage/ApplicationInsights/ApplicationInsights.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
Guess its different between VScode and VS, will address it.

2024-09-17 23:48 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos.Samples/Usage/ChangeFeed/ChangeFeed.csproj
> +    <PackageReference Include="System.Net.Security" Version="4.3.2" />
These are transitive ones flagged by build, let me revalidate it again.

2024-09-18 00:56 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos.Samples/Usage/ChangeFeed/ChangeFeed.csproj
> +    <PackageReference Include="System.Net.Security" Version="4.3.2" />
These are transitive dependencies from V2 ChangeFeedProcessor (which is deprecated)
its a migration sample project

2024-09-18 01:00 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos.Samples/Usage/PowerShellRestApi/PowerShellRestApi.csproj
> +    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
True, the JSOn payloads are already hardcoded.

2024-09-18 01:41 UTC, Pilchie approved these changes
Looks great - thanks!

2024-09-18 11:36 UTC, philipthomas-MSFT approved these changes

2024-09-20 19:23 UTC, adityasa approved these changes

2024-09-20 19:23 UTC, merged