Hedging: Adds support for writes on multi region accounts
Azure/azure-cosmos-dotnet-v3 pull request #4706
Opened 2024-09-18 18:27 UTC by NaluTripician

# Pull Request Template

## Description

Adds support to use hedging on write requests for multimaster accounts. Note that this does come with the caveat that there will be more 409 errors thrown by the SDK. This is expected and applications that adapt this feature should be prepared to handle these exceptions. 

This feature will also be an opt in feature for Availability Strategies and users will need to especially specify that in the availability strategy definition. 

```
ItemRequestOptions requestOptions = new ItemRequestOptions
{
    AvailabilityStrategy = new CrossRegionHedgingAvailabilityStrategy(
        threshold: TimeSpan.FromMilliseconds(100),
        thresholdStep: TimeSpan.FromMilliseconds(50),
        multiMasterWritesEnabled: true)
};
```

## Type of change

Please delete options that are not relevant.

- [] New feature (non-breaking change which adds functionality)

## Closing issues

To automatically close an issue: closes #4457

2024-10-11 21:39 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Routing/AvailabilityStrategy/CrossRegionHedgingAvailabilityStrategy.cs
> +        public bool MultiMasterWriteHedge { get; private set; }
Let's please update summary about violation of idempotency which is by-design. 
=> application might not be able to deterministic on Create vs Replace in case of Upsert etc...

2024-10-11 21:40 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Routing/AvailabilityStrategy/CrossRegionHedgingAvailabilityStrategy.cs
> +        public bool MultiMasterWriteHedge { get; private set; }
Its internal, this is needed on public API

2024-10-19 00:02 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Routing/AvailabilityStrategy/CrossRegionHedgingAvailabilityStrategy.cs
> +        public bool MultiMasterWriteHedge { get; private set; }
```suggestion
        public bool EnableMultiMasterWriteHedge { get; private set; }
```

2024-10-19 00:03 UTC, kirankumarkolli approved these changes

2024-10-19 21:47 UTC, Pilchie requested changes
The feature is not named "multi-master", right? We call it multiple write regions, or active-active in docs. We should change the API to match.

2024-10-24 19:32 UTC, NaluTripician commented on Microsoft.Azure.Cosmos/src/Routing/AvailabilityStrategy/CrossRegionHedgingAvailabilityStrategy.cs
> +        public bool MultiMasterWriteHedge { get; private set; }
Will change to also include Kevin's request

2024-11-06 20:53 UTC, kundadebdatta commented on Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
> +        public bool CanSupportMultipleWriteLocations(RequestMessage request)
Optimization to remove code duplication and better maintainability: Looks like the method is overloaded and the content is mostly duplicated:

![{552ED43D-0693-4CE8-BD87-FAD41950190F}](https://github.com/user-attachments/assets/c65eff94-41e3-4e73-b3fd-86750e7dc358)

Instead, we can do something like the below, to remove the dependency on the `DocumentServiceRequest` and `RequestMessage` and create a generic method which will work in both the flows:

![{B625C67F-37E9-43CA-A3BD-FD02423C987C}](https://github.com/user-attachments/assets/f38e72c1-325b-401f-b7a6-2ccd702e479c)

2024-11-14 16:51 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Routing/AvailabilityStrategy/CrossRegionHedgingAvailabilityStrategy.cs
> +        /// Note that this does come with the caveat that there will be more 409 errors thrown by the SDK.
```suggestion
        /// Note that this does come with the caveat that there will be more 409 / 412 errors thrown by the SDK.
```

2024-11-14 16:52 UTC, FabianMeiswinkel approved these changes
LGTM with few minor comments

2024-11-25 15:34 UTC, FabianMeiswinkel submitted a review, later dismissed
LGTM - Thanks

2024-11-25 18:37 UTC, Pilchie reviewed
A few comment nits.

2024-11-25 18:37 UTC, Pilchie commented on Microsoft.Azure.Cosmos/src/Routing/AvailabilityStrategy/AvailabilityStrategy.cs
> +        /// This is expected and applications that adapt this feature should be prepared to handle these exceptions.
```suggestion
        /// This is expected and applications that adopt this feature should be prepared to handle these exceptions.
```

2024-11-25 18:37 UTC, Pilchie commented on Microsoft.Azure.Cosmos/src/Routing/AvailabilityStrategy/CrossRegionHedgingAvailabilityStrategy.cs
> +        /// Whether hedging for write requests on accounts with multi-region writes are enabled
```suggestion
        /// Whether hedging for write requests on accounts with multi-region writes is enabled.
```

2024-11-25 18:37 UTC, Pilchie commented on Microsoft.Azure.Cosmos/src/Routing/AvailabilityStrategy/CrossRegionHedgingAvailabilityStrategy.cs
> +        /// This is expected and applications that adapt this feature should be prepared to handle these exceptions.
```suggestion
        /// This is expected and applications that adopt this feature should be prepared to handle these exceptions.
```

2024-11-25 18:59 UTC, NaluTripician commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosAvailabilityStrategyTests.cs
> +        [TestCategory("MultiRegion-MultiMaster")]
```suggestion
        [TestCategory("MultiMaster")]
```

2024-11-25 18:59 UTC, NaluTripician commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosAvailabilityStrategyTests.cs
> +        [TestCategory("MultiRegion-MultiMaster")]
```suggestion
        [TestCategory("MultiMaster")]
```

2024-11-25 18:59 UTC, NaluTripician commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosAvailabilityStrategyTests.cs
> +        [TestCategory("MultiRegion-MultiMaster")]
```suggestion
        [TestCategory("MultiMaster")]
```

2024-11-25 18:59 UTC, NaluTripician commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosAvailabilityStrategyTests.cs
> +        [TestCategory("MultiRegion-MultiMaster")]
```suggestion
        [TestCategory("MultiMaster")]
```

2024-11-25 19:02 UTC, Pilchie approved these changes

2024-11-25 20:41 UTC, FabianMeiswinkel approved these changes
LGTM

2024-11-26 22:48 UTC, merged