CrossRegionHedging: Fixes NullReference Bug
Azure/azure-cosmos-dotnet-v3 pull request #4869
Opened 2024-11-05 19:03 UTC by dibahlfi

# Pull Request Template

## Description

This change is to fix CosmosNullReferenceException that happens when a client passes a CancellationToken along with the request. Please see(https://github.com/Azure/azure-cosmos-dotnet-v3/issues/4737) for more information.

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)

## Closing issues

To automatically close an issue: closes #4737

2024-11-05 21:42 UTC, kundadebdatta submitted a review, later dismissed
One minor comment. Otherwise, LGTM.

2024-11-05 21:45 UTC, NaluTripician commented on Microsoft.Azure.Cosmos/src/Routing/AvailabilityStrategy/CrossRegionHedgingAvailabilityStrategy.cs
> +                                        cancellationTokenSource, trace);
See Debdatta's comment about having parameter on following line to follow pattern.

2024-11-05 21:46 UTC, dibahlfi commented on Microsoft.Azure.Cosmos/src/Routing/AvailabilityStrategy/CrossRegionHedgingAvailabilityStrategy.cs
> +                    cancellationTokenSource, trace);
sure will move it to next line.

2024-11-05 21:46 UTC, dibahlfi commented on Microsoft.Azure.Cosmos/src/Routing/AvailabilityStrategy/CrossRegionHedgingAvailabilityStrategy.cs
> +            CancellationTokenSource cancellationTokenSource, ITrace trace)
sure will move it to next line.

2024-11-05 21:46 UTC, dibahlfi commented on Microsoft.Azure.Cosmos/src/Routing/AvailabilityStrategy/CrossRegionHedgingAvailabilityStrategy.cs
> +                                        cancellationTokenSource, trace);
sure will move it to next line.

2024-11-05 21:47 UTC, NaluTripician commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosAvailabilityStrategyTests.cs
> +                ItemResponse<AvailabilityStrategyTestObject> ir = await container.ReadItemAsync<AvailabilityStrategyTestObject>(
nit: consider using https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.testtools.unittesting.assert.throwsexception?view=visualstudiosdk-2019

2024-11-05 21:48 UTC, NaluTripician requested changes
A few nits other than that LGTM. Good work, thanks!

2024-11-05 22:18 UTC, NaluTripician commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosAvailabilityStrategyTests.cs
> +                ItemResponse<AvailabilityStrategyTestObject> ir = await container.ReadItemAsync<AvailabilityStrategyTestObject>(
The Assert will limit the check to the one method call we are testing rather than the whole test method. IMO this is a bit better but either way is OK and this is not blocking

2024-11-05 22:30 UTC, dibahlfi commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosAvailabilityStrategyTests.cs
> +                ItemResponse<AvailabilityStrategyTestObject> ir = await container.ReadItemAsync<AvailabilityStrategyTestObject>(
Thanks. will make the switch to Assert statement.

2024-11-06 00:04 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Routing/AvailabilityStrategy/CrossRegionHedgingAvailabilityStrategy.cs
> +                                        cancellationTokenSource, trace);
@NaluTripician curious who is the consumer for below snipper (its unrelated to this PR)

```C#
                                if (completedTask.IsFaulted)
                                {
                                    AggregateException innerExceptions = completedTask.Exception.Flatten();
                                }
```

2024-11-06 00:09 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosAvailabilityStrategyTests.cs
> +                ItemResponse<AvailabilityStrategyTestObject> ir = await container.ReadItemAsync<AvailabilityStrategyTestObject>(
It's possible that this cancellation token validation might get performed early and not hit the targeted code right?
Thoughts on scoping it to local unit-testing (not E2E)?

2024-11-06 00:19 UTC, NaluTripician commented on Microsoft.Azure.Cosmos/src/Routing/AvailabilityStrategy/CrossRegionHedgingAvailabilityStrategy.cs
> +                                        cancellationTokenSource, trace);
If I recall correctly from when we added this, it is needed for if there is an exception that needs to be thrown to the customer

2024-11-06 00:56 UTC, sourabh1007 commented
We are changing the behavior here, previously if operation was cancelled due to cancellation token, it used to return a valid `HedgingResponse`, now we are returning exception. Is this expected?

2024-11-06 00:57 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Routing/AvailabilityStrategy/CrossRegionHedgingAvailabilityStrategy.cs
> +            catch (OperationCanceledException oce ) when (cancellationTokenSource.IsCancellationRequested)
why do we need this `when (cancellationTokenSource.IsCancellationRequested)`?

2024-11-06 16:25 UTC, dibahlfi commented on Microsoft.Azure.Cosmos/src/Routing/AvailabilityStrategy/CrossRegionHedgingAvailabilityStrategy.cs
> +            catch (OperationCanceledException oce ) when (cancellationTokenSource.IsCancellationRequested)
we need to return CosmosOperationCanceledException instead of NullReferenceException when the token is cancelled by the client.

2024-11-06 17:42 UTC, dibahlfi commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosAvailabilityStrategyTests.cs
> +                ItemResponse<AvailabilityStrategyTestObject> ir = await container.ReadItemAsync<AvailabilityStrategyTestObject>(
not sure I got this. Lets discuss it.

2024-11-11 16:28 UTC, dibahlfi commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosAvailabilityStrategyTests.cs
> +                ItemResponse<AvailabilityStrategyTestObject> ir = await container.ReadItemAsync<AvailabilityStrategyTestObject>(
added additional unit test

2024-11-14 16:03 UTC, kirankumarkolli submitted a review, later dismissed

2024-11-14 18:30 UTC, NaluTripician approved these changes
LGTM - thanks!

2024-11-19 18:32 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Routing/AvailabilityStrategy/CrossRegionHedgingAvailabilityStrategy.cs
> +                                        cancellationTokenSource, trace);
@NaluTripician can you please follow-up on this?

2024-11-25 22:04 UTC, NaluTripician commented on Microsoft.Azure.Cosmos/src/Routing/AvailabilityStrategy/CrossRegionHedgingAvailabilityStrategy.cs
> +                                        cancellationTokenSource, trace);
Yes, we throw if there was an exception and there are no more regions to hedge to

2024-12-01 17:29 UTC, dibahlfi commented
@microsoft-github-policy-service agree company="Microsoft"


On Mon, Nov 25, 2024 at 4:08 PM microsoft-github-policy-service[bot] <
***@***.***> wrote:

> @dibahlfi <https://github.com/dibahlfi> please read the following
> Contributor License Agreement(CLA). If you agree with the CLA, please reply
> with the following information.
>
> @microsoft-github-policy-service agree [company="{your company}"]
>
> Options:
>
>    - (default - no company specified) I have sole ownership of
>    intellectual property rights to my Submissions and I am not making
>    Submissions in the course of work for my employer.
>
> @microsoft-github-policy-service agree
>
>
>    - (when company given) I am making Submissions in the course of work
>    for my employer (or my employer has intellectual property rights in my
>    Submissions by contract or applicable law). I have permission from my
>    employer to make Submissions and enter into this Agreement on behalf of my
>    employer. By signing below, the defined term “You” includes me and my
>    employer.
>
> @microsoft-github-policy-service agree company="Microsoft"
>
> Contributor License Agreement Contribution License Agreement
>
> This Contribution License Agreement (*“Agreement”*) is agreed to by the
> party signing below (*“You”*),
> and conveys certain license rights to Microsoft Corporation and its
> affiliates (“Microsoft”) for Your
> contributions to Microsoft open source projects. This Agreement is
> effective as of the latest signature
> date below.
>
>    1. *Definitions*.
>    *“Code”* means the computer software code, whether in human-readable
>    or machine-executable form,
>    that is delivered by You to Microsoft under this Agreement.
>    *“Project”* means any of the projects owned or managed by Microsoft
>    and offered under a license
>    approved by the Open Source Initiative (www.opensource.org).
>    *“Submit”* is the act of uploading, submitting, transmitting, or
>    distributing code or other content to any
>    Project, including but not limited to communication on electronic
>    mailing lists, source code control
>    systems, and issue tracking systems that are managed by, or on behalf
>    of, the Project for the purpose of
>    discussing and improving that Project, but excluding communication
>    that is conspicuously marked or
>    otherwise designated in writing by You as “Not a Submission.”
>    *“Submission”* means the Code and any other copyrightable material
>    Submitted by You, including any
>    associated comments and documentation.
>    2. *Your Submission*. You must agree to the terms of this Agreement
>    before making a Submission to any
>    Project. This Agreement covers any and all Submissions that You, now
>    or in the future (except as
>    described in Section 4 below), Submit to any Project.
>    3. *Originality of Work*. You represent that each of Your Submissions
>    is entirely Your original work.
>    Should You wish to Submit materials that are not Your original work,
>    You may Submit them separately
>    to the Project if You (a) retain all copyright and license information
>    that was in the materials as You
>    received them, (b) in the description accompanying Your Submission,
>    include the phrase “Submission
>    containing materials of a third party:” followed by the names of the
>    third party and any licenses or other
>    restrictions of which You are aware, and (c) follow any other
>    instructions in the Project’s written
>    guidelines concerning Submissions.
>    4. *Your Employer*. References to “employer” in this Agreement include
>    Your employer or anyone else
>    for whom You are acting in making Your Submission, e.g. as a
>    contractor, vendor, or agent. If Your
>    Submission is made in the course of Your work for an employer or Your
>    employer has intellectual
>    property rights in Your Submission by contract or applicable law, You
>    must secure permission from Your
>    employer to make the Submission before signing this Agreement. In that
>    case, the term “You” in this
>    Agreement will refer to You and the employer collectively. If You
>    change employers in the future and
>    desire to Submit additional Submissions for the new employer, then You
>    agree to sign a new Agreement
>    and secure permission from the new employer before Submitting those
>    Submissions.
>    5. *Licenses*.
>
>
>    - *Copyright License*. You grant Microsoft, and those who receive the
>    Submission directly or
>    indirectly from Microsoft, a perpetual, worldwide, non-exclusive,
>    royalty-free, irrevocable license in the
>    Submission to reproduce, prepare derivative works of, publicly
>    display, publicly perform, and distribute
>    the Submission and such derivative works, and to sublicense any or all
>    of the foregoing rights to third
>    parties.
>    - *Patent License*. You grant Microsoft, and those who receive the
>    Submission directly or
>    indirectly from Microsoft, a perpetual, worldwide, non-exclusive,
>    royalty-free, irrevocable license under
>    Your patent claims that are necessarily infringed by the Submission or
>    the combination of the
>    Submission with the Project to which it was Submitted to make, have
>    made, use, offer to sell, sell and
>    import or otherwise dispose of the Submission alone or with the
>    Project.
>    - *Other Rights Reserved*. Each party reserves all rights not
>    expressly granted in this Agreement.
>    No additional licenses or rights whatsoever (including, without
>    limitation, any implied licenses) are
>    granted by implication, exhaustion, estoppel or otherwise.
>
>
>    6. *Representations and Warranties*. You represent that You are
>    legally entitled to grant the above
>    licenses. You represent that each of Your Submissions is entirely Your
>    original work (except as You may
>    have disclosed under Section 3). You represent that You have secured
>    permission from Your employer to
>    make the Submission in cases where Your Submission is made in the
>    course of Your work for Your
>    employer or Your employer has intellectual property rights in Your
>    Submission by contract or applicable
>    law. If You are signing this Agreement on behalf of Your employer, You
>    represent and warrant that You
>    have the necessary authority to bind the listed employer to the
>    obligations contained in this Agreement.
>    You are not expected to provide support for Your Submission, unless
>    You choose to do so. UNLESS
>    REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING, AND EXCEPT FOR THE
>    WARRANTIES
>    EXPRESSLY STATED IN SECTIONS 3, 4, AND 6, THE SUBMISSION PROVIDED
>    UNDER THIS AGREEMENT IS
>    PROVIDED WITHOUT WARRANTY OF ANY KIND, INCLUDING, BUT NOT LIMITED TO,
>    ANY WARRANTY OF
>    NONINFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
>    7. *Notice to Microsoft*. You agree to notify Microsoft in writing of
>    any facts or circumstances of which
>    You later become aware that would make Your representations in this
>    Agreement inaccurate in any
>    respect.
>    8. *Information about Submissions*. You agree that contributions to
>    Projects and information about
>    contributions may be maintained indefinitely and disclosed publicly,
>    including Your name and other
>    information that You submit with Your Submission.
>    9. *Governing Law/Jurisdiction*. This Agreement is governed by the
>    laws of the State of Washington, and
>    the parties consent to exclusive jurisdiction and venue in the federal
>    courts sitting in King County,
>    Washington, unless no federal subject matter jurisdiction exists, in
>    which case the parties consent to
>    exclusive jurisdiction and venue in the Superior Court of King County,
>    Washington. The parties waive all
>    defenses of lack of personal jurisdiction and forum non-conveniens.
>    10. * [...]

2025-01-02 19:19 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/AvailabilityStrategyUnitTests.cs
> +    using System.Net;
Order the usings

2025-01-02 19:20 UTC, kirankumarkolli approved these changes

2025-01-02 19:24 UTC, kirankumarkolli approved these changes

2025-01-03 15:30 UTC, merged