[Client encryption]: Fixes missing files errors at time of nuget publishing.
Azure/azure-cosmos-dotnet-v3 pull request #4896
Opened 2024-11-18 19:34 UTC by aavasthy

# Pull Request Template

## Description

Updated the Microsoft.Azure.Cosmos.Encryption package and  Microsoft.Azure.Cosmos.Encryption.Custom package so as to fix missing icon.png and license.txt errors when publishing these packages locally.

## Type of change
Below the are the errors the project throws while publishing the nuget package.
<img width="899" alt="image" src="https://github.com/user-attachments/assets/301ac421-93b8-4cd6-90aa-3a49f1a18d55">
<img width="932" alt="image" src="https://github.com/user-attachments/assets/b2a0ad13-ad13-4bd2-a659-2f21863b297b">

After the fix is implemented the nuget package publishes successfully.
<img width="937" alt="image" src="https://github.com/user-attachments/assets/afc3d1c2-3d73-43f1-94c3-09c2061ba169">
<img width="954" alt="image" src="https://github.com/user-attachments/assets/a21cf018-070d-432f-b91f-ba13ad5d3cb8">

- [X] Bug fix (non-breaking change which fixes an issue)
## Closing issues

To automatically close an issue: closes #IssueNumber

2024-11-18 21:19 UTC, Pilchie requested changes

2024-11-18 21:19 UTC, Pilchie commented on Microsoft.Azure.Cosmos.Encryption.Custom/src/LICENSE.txt
> +** Beginning of "BSD 2-Clause License" text. **
Most Microsoft Open Source code uses the MIT license, as does the main repo?  Why are we using this hybrid of the BSD-2, and CC0?

Also, assuming we can move to MIT, I think you can use a [`PackageLicenseExpression`](https://learn.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-a-license-expression-or-a-license-file) instead of file.

2024-11-18 21:33 UTC, aavasthy commented on Microsoft.Azure.Cosmos.Encryption.Custom/src/LICENSE.txt
> +** Beginning of "BSD 2-Clause License" text. **
I have added the same License.txt that we have in main repo https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/OSS/HdrHistogram/LICENSE.txt
But I can update it to using PackageLicenseExpression if that is recommended.
<PropertyGroup>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
</PropertyGroup>

2024-11-18 21:57 UTC, Pilchie commented on Microsoft.Azure.Cosmos.Encryption.Custom/src/LICENSE.txt
> +** Beginning of "BSD 2-Clause License" text. **
That is specific to that subdirectory where we pulled in the source from an external OSS library.  The main license is [MIT](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/LICENSE).

I think we should use PackageLicenseExpression with MIT as the value.

2024-11-18 22:17 UTC, aavasthy commented on Microsoft.Azure.Cosmos.Encryption.Custom/src/LICENSE.txt
> +** Beginning of "BSD 2-Clause License" text. **
Updated the file reference and using the main license file now and referencing it in the way it is being referenced in the main project (using  PackageLicenseFile).

2024-11-18 22:41 UTC, Pilchie commented on Microsoft.Azure.Cosmos.Encryption/src/Microsoft.Azure.Cosmos.Encryption.csproj
> +    <None Include="icon.png" Pack="true" PackagePath="\" />
Do we have a shared one of these that we can use instead of adding two identical versions?

2024-11-18 23:34 UTC, aavasthy commented on Microsoft.Azure.Cosmos.Encryption/src/Microsoft.Azure.Cosmos.Encryption.csproj
> +    <None Include="icon.png" Pack="true" PackagePath="\" />
I updated and kept the file outside in the common so that all three projects can refer it.

2024-11-19 00:01 UTC, NaluTripician approved these changes

2024-11-19 00:33 UTC, ananth7592 approved these changes
nit: Does the icon.png at line number 30 also needs to be changed to this new path https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj#L30 ?

2024-11-19 00:42 UTC, aavasthy commented
> nit: Does the icon.png at line number 30 also needs to be changed to this new path https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj#L30 ?

PackagePath="" places the Icon.png file at the root of the package so that is why the <PackageIcon> value does not need to change in this case.

2024-11-19 15:56 UTC, merged