Added Throughput Bucket to RequestOptions and ClientOptions
Azure/azure-cosmos-dotnet-v3 pull request #4940
Opened 2024-12-27 06:02 UTC by Achint-Agrawal

## Description

This PR add ThroughputBucket in RequestOptions and ClientOptions to support Throughput Bucketing

## Type of change

Please delete options that are not relevant.

- [] New feature (non-breaking change which adds functionality)
- [] This change requires a documentation update

2024-12-27 06:05 UTC, Achint-Agrawal commented on Microsoft.Azure.Cosmos.sln
> +VisualStudioVersion = 17.12.35514.174 d17.12
Revert file

2024-12-27 11:26 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        public int? ThroughputBucket { get; set; }
Is an int the only possible way to identify a throughput bucket or can names/identifiers be also used? The int/number seems like it will cause confusion for customers easily.

2024-12-27 11:28 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        public int? ThroughputBucket { get; set; }
How is this feature rolled-out? If there is any opt-in necessary on the service side in .Net SDK this should only be released in the preview nuget package first - and at least the PR description should have clear instructions for onboarding. If the feature is just enabled automatically for all accounts we can add this as public API assuming we have confidence in the public API in the normal nuget packaage (assuming all deployements including non-public clouds have been finished to enable the backend feature)

2024-12-27 11:31 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
> +        /// If <see cref="WithBulkExecution(bool)"/> is set to true, throughput bucket set on the CosmosClient is used.
Why this constraint? That seems super confusing. I get what you are saying - if bulk mode is enabled and request options have different values this is a challenge in .Net - but  why not throw an ArgumentException if request options has throughput bucket defined and bulk mode is enabled - that way the contract is enforced cleanly

2024-12-27 11:34 UTC, FabianMeiswinkel commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        /// <summary>
Please also add an aka.ms link to explain the concept and constraints of throughput buckets

2024-12-27 11:35 UTC, FabianMeiswinkel requested changes
Thanks - overall changes loog good. Mainly blocking on clarification for versioning/rollout/onboarding.

2024-12-29 19:46 UTC, Pilchie commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +                headers.Set(HttpConstants.HttpHeaders.ThroughputBucket, options.ThroughputBucket.ToString());
I know we only support a small number of buckets, but we should really specify a format here to not have something like thousands separators vary by client locale settings.

2024-12-30 03:02 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
> +        /// If <see cref="WithBulkExecution(bool)"/> is set to true, throughput bucket set on the CosmosClient is used.
+1 to throw and fail.

2024-12-30 03:12 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
> +        private void SetThroughputBucket(RequestMessage requestMessage)
[Non blocker] 
Our RequestOptions are stateless but pattern of overrides implementation in RequestInvokerHandler is odd.
One alternative way is to pass the CosmosClientOptions along with ReqeustMessge for RequestOptions.RequestOptions?

/cc: @FabianMeiswinkel thoughts?

2025-01-02 03:31 UTC, Achint-Agrawal commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        /// <summary>
The link added in seealso will contain this information. We are still working on publishing the documentation

2025-01-02 03:36 UTC, Achint-Agrawal commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        public int? ThroughputBucket { get; set; }
int is the only way to identify buckets right now. Bucket ids can be between 1 and 5. We might increase it to more buckets if needed.

2025-01-02 03:40 UTC, Achint-Agrawal commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        public int? ThroughputBucket { get; set; }
The feature is behind a config which is currently off. There is no opt in from the customer end. In the beginning, we will enable the config for a few customers as we receive requests for the feature. Eventually, the config will be turned on by default for all accounts. 

In the past, with Priority Based Execution, we saw a lot of push back from customers for using the preview SDK which impacts the adoption of the feature. If it is possible to do so, it would be great if we could keep the request option in the public SDK. Setting the throughput bucket does not have any impact - if the feature is disabled, the bucket is ignored. No error is thrown.

2025-01-02 03:47 UTC, Achint-Agrawal commented on Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
> +        /// If <see cref="WithBulkExecution(bool)"/> is set to true, throughput bucket set on the CosmosClient is used.
Sure will do this.
Same handling is done for PriorityLevel. Would it be ok to throw an Argument Exception for that as well? There might be existing customers who have not handled this and would start getting an error on upgrading the SDK version.

2025-01-02 05:31 UTC, Achint-Agrawal commented on Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
> +        /// If <see cref="WithBulkExecution(bool)"/> is set to true, throughput bucket set on the CosmosClient is used.
Made changes for ThroughputBucket. Keeping open to discuss any changes for PriorityLevel

2025-01-02 05:37 UTC, Achint-Agrawal commented on Microsoft.Azure.Cosmos/src/DocumentClient.cs
> +                headers.Set(HttpConstants.HttpHeaders.ThroughputBucket, options.ThroughputBucket.ToString());
used CultureInfo.InvariantCulture

2025-01-03 13:16 UTC, Achint-Agrawal commented on Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
> +        public int? ThroughputBucket { get; set; }
Changed to only expose this option for preview SDKs

2025-01-03 13:19 UTC, Achint-Agrawal commented on Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
> +        private void SetThroughputBucket(RequestMessage requestMessage)
I am assuming this is not specifically related to this PR but how we generally apply request options in RequestInvokerHandler and would be taken up separately if needed. Please let me know if this is not the case. Thanks

2025-01-03 14:44 UTC, FabianMeiswinkel submitted a review, later dismissed
LGTM - thanks

2025-01-06 07:40 UTC, kirankumarkolli commented on Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
> +        CosmosClientBuilder WithThroughputBucket(int? throughputBucket)
Is argument needs to be nullable? 
Application can avoid calling this API instead, right?

2025-01-06 08:28 UTC, Achint-Agrawal commented on Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
> +        CosmosClientBuilder WithThroughputBucket(int? throughputBucket)
Made it non nullable. Thanks

2025-01-07 11:29 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
> +                        $"Set {nameof(this.client.ClientOptions.ThroughputBucket)} in {nameof(this.client.ClientOptions)} instead.");
nit: What if throughputbucket is already set at client options also, along with request option?  Rephrase this message to "Set {nameof(this.client.ClientOptions.ThroughputBucket)} in {nameof(this.client.ClientOptions)} instead only" or something in similar lines.

2025-01-07 11:30 UTC, sourabh1007 commented on Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
> +        private void SetThroughputBucket(RequestMessage requestMessage)
nit: rename to "ValidateAndSetThroughputBucket"

2025-01-08 04:34 UTC, sourabh1007 approved these changes
LGTM

2025-01-08 05:46 UTC, kirankumarkolli approved these changes

2025-01-08 05:47 UTC, merged